### ISSUE TITLE
Simplify external plugins packaging

### ISSUE THREAD

**Issue by binarin** [rabbitmq/rabbitmq-server#1001]
Currently there is no easy way to package external plugin to a
.deb-package, because plugins directory is versioned (like
`/usr/lib/rabbitmq/lib/rabbitmq_server-3.6.5.905`). It's too tight
coupling for a plugin.

There should be a way to use some common plugins directory (like
`/usr/lib/rabbitmq/plugins`). I see two possible ways to implement
this:
- Use dpkg triggers to make rabbitmq-server package populate its
  plugins store with symlinks to plugins from common
  directory. Plugin .deb's will notify rabbitmq-server package, so it
  can refresh symlinks there.
- Transform `RABBITMQ_PLUGINS_DIR` into colon-separed list of paths.

First option is less intrusive, but only debian packagers will benefit
from it. Second one is more generic, but will require some relatively
clever way to properly populate `RABBITMQ_PLUGINS_DIR`.

WDYT? What option would you prefer for me to implement?

**Comment by michaelklishin** [comment]
@dumbbell WDYT?

@binarin I wonder how colon-separate lists would work on Windows?

**Comment by binarin** [comment]
Windows PATH variable uses `;` as delimiter. So path can be splitted depending on `os:type/0`  return value.

**Comment by binarin** [comment]
I've already implemented it in https://github.com/binarin/rabbitmq-server/commit/9dd2c6cd2dfea0baca6f4cd264bdc4db8ae5f574
Just haven't tested it yet.

**Comment by hairyhum** [comment]
This will also require changes in `rabbitmq_cli` plugins discovery.

**Comment by michaelklishin** [comment]
Fixed in #1016.
