### ISSUE TITLE
connection_timeout param in URI string is milliseconds not seconds 

### ISSUE THREAD

**Issue by TadMelton** [rabbitmq/rabbitmq-server#1015]
When creating a federation upstream, in the uri if connection_timeout amqp param is added it needs to be in milliseconds not seconds according to the documentation.  This was found in 3.4.3.

Example
amqp://user:password@SERVER?heartbeat=10&connection_timeout=10

should be

amqp://user:password@SERVER?heartbeat=10&connection_timeout=10000

**Comment by michaelklishin** [comment]
Moved to https://github.com/rabbitmq/rabbitmq-website/issues/293.
