### ISSUE TITLE
Autojoining woes

### ISSUE THREAD

**Issue by AlessandroEmm** [rabbitmq/rabbitmq-server#102]
Hey there

Maybe I'm not getting something: How do I initiate an auto cluster? 

I tried

```
[
   {rabbit, [
    {cluster_nodes, {['rabbit@c1', 'rabbit@c2'], disc}},
    {cluster_partition_handling, ignore},
    {default_user, <<"guest">>},
    {default_pass, <<"guest">>}
]}
].
```

On both nodes (c1 & c2).  The nodes start just fine and have the appropriate nodes entries:

```
 cat /var/lib/rabbitmq/mnesia/rabbit@c1/cluster_nodes.config 
{[rabbit@c1,rabbit@c2],[rabbit@c1,rabbit@c2]}.
```

Unfortunately they never join each other. If I initiate a manual join_cluster it does work flawlessy.

Theres nothing in the logs either. Is there any way to force the auto-joining?

Cheers
Alessandro

**Comment by dumbbell** [comment]
Auto-clustering only happens during the first start of the node, or after using `rabbitmq reset`. See paragraph #3 in the [documentation](http://www.rabbitmq.com/clustering.html#auto-config). There is no way to "force" auto-configuration again beside using `rabbitmq reset`.

If you are using a Debian-like Linux distribution for instance, installing the package starts the service as per the Debian policy. Therefore, you need to stop and reset the node before auto-clustering has a chance to kick in.

As a side not, please post your questions to the [mailing-list](https://groups.google.com/forum/#!forum/rabbitmq-users) in the future. This is our primary place for this purpose.

**Comment by AlessandroEmm** [comment]
@dumbbell Sorry for the stupid title. I posted it here to because I thought I may haven fallen into a bug or something. 
I did issue a reset multiple times (as it says in the doc) hence the nodes in the cluster cluster_nodes.config. One thing i noticed is that the clusters name we're different - could that be my issue? Or is there a minimum amount of nodes needed for autojoining to work?

**Comment by dumbbell** [comment]
There is an ongoing discussion with someone who have an issue similar to yours on the mailing-list. See:
https://groups.google.com/d/topic/rabbitmq-users/aI4jHe99fQg/discussion

This problem is unresolved as of now. Stay tuned :-)

**Comment by AlessandroEmm** [comment]
@dumbbell thanks! I will join the list then. You can close this thread. :-)

**Comment by michaelklishin** [comment]
Please ask questions on the mailing list.

**Comment by michaelklishin** [comment]
Looks like we've found the root case: #118.

**Comment by dumbbell** [comment]
Likewise, check #120 on the same topic.
