### ISSUE TITLE
Incorrect example in the management plugin documentation

### ISSUE THREAD

**Issue by bowensong** [rabbitmq/rabbitmq-server#1024]
In the [management plugin sample retention policies documentation](https://www.rabbitmq.com/management.html#sample-retention), it gives an example of the (partial) configuration file:
```
[
  ...
  {rabbitmq_management,
    {sample_retention_policies,
      %% List of {MaxAgeInSeconds, SampleEveryNSeconds}
      [{global,   [{605, 5}, {3660, 60}, {29400, 600}, {86400, 1800}]},
       {basic,    [{605, 5}, {3600, 60}]},
       {detailed, [{10, 5}]}]
    },
  ...
].
```

But when I copied & pasted it into my `rabbitmq.config` file, the first error I got is:
```
could not start kernel pid (application_controller) (error in config file "/etc/rabbitmq/rabbitmq.config" (12): syntax error before: ']')
```
And the line 12 is the last line in my `rabbitmq.config` file.
It is obvious that this example missed a `}` in the middle, so I added it, like this:
```
[
  {rabbitmq_management,
    {sample_retention_policies,
      %% List of {MaxAgeInSeconds, SampleEveryNSeconds}
      [{global,   [{605, 5}, {3660, 60}, {29400, 600}, {86400, 1800}]},
       {basic,    [{605, 5}, {3600, 60}]},
       {detailed, [{10, 5}]}]
      }
    },
    {rabbit,
      ...
    }
].
```

Then RabbitMQ still failing to start, and the error message changed to:
```
could not start kernel pid (application_controller) (invalid config data: application: rabbitmq_management; parameters must be a list)
```

Right, parameters must be a list! I had to change it again:
```
[
  {rabbitmq_management,
    [{sample_retention_policies,
      %% List of {MaxAgeInSeconds, SampleEveryNSeconds}
      [{global,   [{605, 5}, {3660, 60}, {29400, 600}, {86400, 1800}]},
       {basic,    [{605, 5}, {3600, 60}]},
       {detailed, [{10, 5}]}]
      }]
    },
    {rabbit,
      ...
    }
].
```
And now it works. What a waste of time because of the incorrect example.

Could anyone please fix it?

**Comment by michaelklishin** [comment]
Thank you for reporting. FYI, the website is open source and can be found at https://github.com/rabbitmq/rabbitmq-website.
