### ISSUE TITLE
3.13 log exchange does not respect message_containers feature flag

### ISSUE THREAD

**Issue by gomoripeti** [rabbitmq/rabbitmq-server#10346]
### Describe the bug

Tested on 3.13.0-rc.4 and main (3.13.0+rc.4.25.ga3c8880) as new version
and RabbitMQ 3.12.12+8.gf3f7408 Erlang 26.0.2 as old version in a mixed version cluster.

The logger exchange always creates message containers to encapsulate and publish log messages, even when the `message_containers` feature flag is disabled. This causes problems in mixed version clusters during a rolling upgrade, when some of the nodes are not ready to handle message containers.
For example the below crashes can happen in classic queue leader and slave respectively which are bound to the log exchange (where the log event happens on a new 3.13 node and the CQ processes run on old 3.12 nodes)

```
 ** {{badmatch,{mc,mc_amqpl,
                   {content,60,none,
                            <<160,64,10,116,101,120,116,47,112,108,97,105,110,0,
                              0,0,37,4,110,111,100,101,83,0,0,0,27,114,97,98,98,
                              105,116,45,49,64,80,101,116,101,114,115,45,77,97,
                              99,66,111,111,107,45,80,114,111,0,0,0,0,101,165,
                              215,176>>,
                            rabbit_framing_amqp_0_9_1,
                            [<<"2024-01-16 02:11:12.618266+01:00 [error] <0.1322.0> TEST2\n">>]},
                   #{id => <<"Ð\\çA45ªxzòäIQoÜ`">>,timestamp => 1705367472000,
                     exchange => <<"amq.rabbitmq.log">>,durable => false,
                     routing_keys => [<<"error">>],
                     rts => 1705367472618}}},
     [{rabbit_amqqueue_process,will_overflow,2,
                               [{file,"rabbit_amqqueue_process.erl"},
                                {line,837}]},
      {rabbit_amqqueue_process,maybe_deliver_or_enqueue,3,
                               [{file,"rabbit_amqqueue_process.erl"},
                                {line,707}]},
      {rabbit_amqqueue_process,handle_cast,2,
                               [{file,"rabbit_amqqueue_process.erl"},
                                {line,1575}]},
```

```
 ** Reason for termination ==
 ** {function_clause,
    [{rabbit_mirror_queue_slave,maybe_enqueue_message,
      [{delivery,false,false,<55988.1322.0>,
        {mc,mc_amqpl,
         {content,60,none,
          <<160,64,10,116,101,120,116,47,112,108,97,105,110,0,0,0,37,4,110,111,
            100,101,83,0,0,0,27,114,97,98,98,105,116,45,49,64,80,101,116,101,
            114,115,45,77,97,99,66,111,111,107,45,80,114,111,0,0,0,0,101,165,
            215,176>>,
          rabbit_framing_amqp_0_9_1,
          [<<"2024-01-16 02:11:12.618266+01:00 [error] <0.1322.0> TEST2\n">>]},
         #{id => <<"Ð\\çA45ªxzòäIQoÜ`">>,timestamp => 1705367472000,
           exchange => <<"amq.rabbitmq.log">>,durable => false,
           routing_keys => [<<"error">>],
           rts => 1705367472618}},
        undefined,noflow},
        {state,
	...
      [{file,"rabbit_mirror_queue_slave.erl"},{line,849}]},
     {rabbit_mirror_queue_slave,handle_cast,2,
      [{file,"rabbit_mirror_queue_slave.erl"},{line,332}]},
```	
      

### Reproduction steps

1. Create a 3-node cluster on 3.12.10
2. Enable log exchange on all nodes (in config `log.exchange = true`) and restart nodes
3. Bind classic mirrored queue to log exchange. Leader is on node2 and follower is on node3
4. Upgrade node1 to 3.13.0-rc.4
5. Emit a log entry on node1 in the remote_shell ` rabbit_log:error("TEST").`
...

### Expected behavior

No crash. Log exchange should emit old-style `basic_message` when message_containers feature flag is disabled.

**Comment by kjnilsson** [comment]
Great find @gomoripeti - I'll work on this today.

**Comment by kjnilsson** [comment]
@gomoripeti do you have capacity to take the PR for a test spin at all?

**Comment by gomoripeti** [comment]
sure, I will test it today!

(btw would it make sense to add some mixed-version ct smoke tests for the log exchange? (message container FF is just temporary, so Im thinking more of some generic "log on one version, deliver to queue on another version") I know this is open source but unfortunately I don't have capacity to contribute such ct tests)
