### ISSUE TITLE
Disallow use of the `rename_cluster_node` command by default or consider making it a no-op

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/rabbitmq-server#10367]
### Is your feature request related to a problem? Please describe.

Renaming RabbitMQ nodes is a rarely used feature which cannot work anymore as any feature that depends on Ra cannot support it. Ra uses the node name as part of each members permanent identity and this is not something that can be updated on the fly. Using the `rename_cluster_node` command on a system with quorum queues will no doubt cause all quorum queues to cease to work (if more than a quorum of nodes are renamed) as well as cause undefined behaviour. In addition khepri already does not support this feature.

### Describe the solution you'd like

Change the `rename_cluster_node` command to not do anything unless the `--force` flag is provided.

When the command is run without `--force` it will print a warning explaining that the feature is not to be used and that it will cuase undefined behaviour that is very likely to cause the cluster to break. This warning will also inform the operator that they can still run the command by providing the `--force` flag but that it is at their own risk and that they cannot expect the RabbitMQ team to help or support the end result.

The `--force` flag should not appear in the documentation of the command as this could operators to not be exposed to the warning. The command also needs to be documented as deprecated.

### Additional context

The alternative to renaming nodes is to remove the the node from the cluster then re-add a new node.

**Comment by dumbbell** [comment]
Should it be denied regardless of `--force` if there are any Ra clusters running?

**Comment by kjnilsson** [comment]
> Should it be denied regardless of `--force` if there are any Ra clusters running?

Possibly but ultimately that means we'd take the option out of the operators hand so as a stepping stone I thought it would suffice to warn by default and make them stop and think.

**Comment by lukebakken** [comment]
I think the command should become a no-op with a loud warning printed.

**Comment by michaelklishin** [comment]
> I think the command should become a no-op with a loud warning printed.

we did exactly that with a couple of other commands, like the original super-invasive health check.

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-server/pull/10369 makes `ctl rename_cluster_node` and its close relative `ctl update_cluster_nodes` no-ops, and removes their respective Mnesia-specific code paths.
