### ISSUE TITLE
Coerce default configuration values to binaries

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-server#1050]
Using Erlang strings for some configuration values (e.g. default virtual host) can make the whole system unstable (the broker starts but some plugins don't behave correctly). Some plugins can also fail on startup (e.g. MQTT plugin). See https://github.com/rabbitmq/rabbitmq-mqtt/issues/86#issuecomment-264833679.

A solution would be to coerce values to binaries. Candidate configuration entries would be [`default_user`, `default_pass`, etc](https://github.com/rabbitmq/rabbitmq-server/blob/stable/src/rabbit.erl#L773).

**Comment by michaelklishin** [comment]
Note that this is less of an issue in master due to the new config format (which does not use Erlang terms) available but still worth doing.
