### ISSUE TITLE
Definitions export from management UI does not include vhost metadata

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#10515]
https://vmware.slack.com/archives/C0RDGG81Z/p1707224857559109

# Reproduction steps:

## Create vhost

```
rabbitmqctl add_vhost test --default-queue-type quorum
```

## Export using CLI

```
rabbitmqctl export_definitions test-vhost-with-queue-type-from-cli.json
```

Note that the above file includes vhost metadata:

```
    "vhosts": [
        {
            "limits": [],
            "metadata": {
                "description": "Default virtual host",
                "tags": []
            },
            "name": "/"
        },
        {
            "limits": [],
            "metadata": {
                "description": "",
                "tags": [],
                "default_queue_type": "quorum"
            },
            "name": "test"
        }
    ],
```

## Export using management UI

Note that the exported file does _NOT_ contain metadata:

```
    "vhosts": [
        {
            "name": "/"
        },
        {
            "name": "test"
        }
    ],
```

**Comment by michaelklishin** [comment]
@lukebakken thank you for digging in and providing the details.

**Comment by lukebakken** [comment]
cc @pvladMQ

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-server/pull/11538 addresses the essential part of it. Virtual host limits are not considered to be, well, virtual host parameters by the HTTP API and the internally used schema database. They are runtime parameters.

So I think https://github.com/rabbitmq/rabbitmq-server/pull/11538 is an acceptable solution, at least for now.
