### ISSUE TITLE
Introduce a way to validate user credentials

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#1054]
E.g. to enforce a minimum length or certain characters to be present.

Since there is no consensus on what a reasonably secure password is (or if such a thing exists), this should be a pluggable module. The API would be roughly:

``` erlang
-spec validate(username(), password()) -> boolean()
```

This only makes sense for the internal authn/authz backend, of course.

Two implementations are considered for inclusion into the core:

 * Minimal length
 * Regular expressions

[NIST 800-63-3](https://nakedsecurity.sophos.com/2016/08/18/nists-new-password-rules-what-you-need-to-know/) is another interesting option but it would require maintaining a dictionary of ~ 100K words, so this is likely plugin material.

**Comment by kjnilsson** [comment]
Should `validate` optionally pass the username as well so that it would be possible to check that a password change for example isn't the same as before and that he usersname isn't present in the password itself?

**Comment by michaelklishin** [comment]
@kjnilsson good idea.

**Comment by dumbbell** [comment]
I agree. We should give as much context as we can. The virtual host could be useful too.

**Comment by michaelklishin** [comment]
Another good question is what the default should be. For best backwards compatibility it should be a function that always returns `true`. Of course, that doesn't help security one bit.

So, should we set a reasonable minimum, e.g. 5 or 8 characters (will be configurable)?

**Comment by michaelklishin** [comment]
@dumbbell we don't have a virtual host or tag list at the time of user creation.

**Comment by dumbbell** [comment]
How would an operator define a password policy? Would he implement and provide an Erlang module?

**Comment by kjnilsson** [comment]
Configuration could also include a list of regexes that would need to match. (e.g. upper/lower case non-alpha etc) as well as a a switch for disallowing the username appearing in the password.

**Comment by michaelklishin** [comment]
@kjnilsson regular expressions can be one of the out-of-the-box modules but I'm not sure it is essential.

**Comment by michaelklishin** [comment]
@dumbbell the same way modules are provided in other areas (e.g. peer discovery in master): with a plugin.

**Comment by kjnilsson** [comment]
@michaelklishin perhaps not but it would probably be enough to cover the majority of most user's password strength requirements.

**Comment by michaelklishin** [comment]
So far two policy implementations were suggested:

 * Minimal length
 * Regular expression matching

both seem reasonable to me.

**Comment by kjnilsson** [comment]
Can regex be used to check if the username is contained in the password? Else we could include a switch for doing that.

**Comment by michaelklishin** [comment]
One edge case I've found is the default user. I think we should intentionally bypass validation in this case: if it fails, we can only fail node boot and that may or may not be welcomed. Or make this an option :/

**Comment by kjnilsson** [comment]
I think the default user should adhere to any policy defined so perhaps failing boot is the right option? :/

**Comment by michaelklishin** [comment]
@kjnilsson a few other folks agree with you, alright.

**Comment by hairyhum** [comment]
Will there be multiple validators enabled at the same time? If so, can we make validator a pair of functions instead of a module?
So we can add new validators like this:
```
add_validator(fun default_validators:validate_length/2, fun default_validators:validate_length_message/2)
```
And plugin will be able to enable/disable validators on application start/stop.

**Comment by michaelklishin** [comment]
I don't think supporting multiple validators is worth it. Since it's a module, you can develop your own and combine a few existing functions. I doubt complex or multi-step validation rules are going to be all that common.

**Comment by dcorbacho** [comment]
@michaelklishin The management UI needs to be updated to capture the errors while changing password and notify the users. At the moment, the password change can fail but no error is given by the UI. See https://github.com/rabbitmq/rabbitmq-management/blob/master/src/rabbit_mgmt_wm_user.erl#L90 and related.

Similar thing goes for `add_user`, but in this case the user is first created with a fake password and then changed. Thus, the operator will see an user in the UI but won't be able to use it as the password is not the given one.  See https://github.com/rabbitmq/rabbitmq-management/blob/master/src/rabbit_mgmt_wm_user.erl#L119

```
(<0.724.0>) call rabbit_auth_backend_internal:add_user(<<"short">>,<<"tmp-b7jZmNtXkpCt3c2yaEa_kQ">>)
(<0.724.0>) returned from rabbit_auth_backend_internal:add_user/2 -> ok
(<0.724.0>) call rabbit_auth_backend_internal:change_password(<<"short">>,<<"short">>)
(<0.724.0>) returned from rabbit_auth_backend_internal:change_password/2 -> {error,
                                                                             "minimum required password length is 8"}
```

**Comment by michaelklishin** [comment]
This is now done for both `3.6.x` and `master`.
