### ISSUE TITLE
`rabbit_disk_monitor` can crash with `badarith` if win32sysinfo.exe request times out

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#10597]
### Describe the bug

Reported here:
https://groups.google.com/g/rabbitmq-users/c/1IIUetvreos

### Reproduction steps

If the call to the `win32sysinfo.exe` times out, `NaN` is saved as the free disk space, which can lead to `badarith` later on.

### Expected behavior

No crash.

**Comment by michaelklishin** [comment]
Man, we cannot switch to `fshc` (which is done, just needs a proper release with builds for all three key operating systems) fast enough.

Although this particular issue with timeouts would have to be handled there, too.

**Comment by lukebakken** [comment]
I don't think `fshc` will fix these persistent issues, since it does exactly the same thing as `win32sysinfo.exe` that ships with Erlang on Windows.

**Comment by PauloHMattos** [comment]
Hello @lukebakken @michaelklishin, is there any estimate to when this fix will be available in 3.12?

**Comment by michaelklishin** [comment]
@PauloHMattos it was not backported to `v3.12.x`. It will be available in `3.13.1` this week or the next.

**Comment by PauloHMattos** [comment]
`v3.12.x` it's no longer supported?

**Comment by michaelklishin** [comment]
There is a [doc guide](https://www.rabbitmq.com/docs/versions) that explains which release series are supported.

However, "supported" does not mean that we will backport everything to 3.12.x. This is not a critically important issue as its worst case outcome is that a single node metric won't be available and logs will be polluted with exception stack traces.

Time to upgrade to 3.13.1 when it comes out.

**Comment by PauloHMattos** [comment]
Ok. Thanks!
