### ISSUE TITLE
standalone release should ship the OTP_VERSION file

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-server#106]
right now rabbit_misc:otp_release/0 doesn't properly work on the standalone due to a missing OTP_VERSION file

See: https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_misc.erl#L981

**Comment by michaelklishin** [comment]
Cherry-picked to `stable` as I think this can safely go into `3.5.x`.
