### ISSUE TITLE
After upgrading to 3.13, management interface shows 500 for /api/deprecated-features/used

### ISSUE THREAD

**Issue by leonjoosse** [rabbitmq/rabbitmq-server#10625]
### Describe the bug

Today, we upgraded our rabbitmq server from 3.12.x to 3.13.0. 
When loading the management interface after upgrading, the page display a fat banner at the bottom, saying "Management API returned status code 500 -".
Inspecting the Network tab in the developer tools reveals that `/api/deprecated-features/used` returns a 500 Internal Server Error.
When looking in the rabbitmq logs, I can't find anything related to this call failing.

All feature flags are enabled (apart from the experimental `khepri_db`).
We are on RabbitMQ 3.13.0 and Erlang 26.2.2, running on Ubuntu 20.04.6.

I can imagine one needs more information to find the cause, please let me know what information is needed. I'm happy to provide more insight on configuration or logs. 

### Reproduction steps

1. Open RabbitMQ management page, login as normal
2. Go to Admin tab
3. 
...

### Expected behavior

I'd expect to have a functioning Deprecated Features endpoint.

### Additional context

Here is the failing request, copied from the browser (`ourcompany.com` is obviously not our real domain)

```
curl 'https://rabbitmqdev.ourcompany.com/api/deprecated-features/used' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en,en-GB;q=0.9,en-US;q=0.8,nl;q=0.7' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: m=59b9:true' \
  -H 'Referer: https://rabbitmqdev.ourcompany.com/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' \
  -H 'authorization: Basic ...' \
  -H 'content-type: application/json' \
  -H 'sec-ch-ua: "Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --compressed
```

And that responds
```
Content-Length: 0
```
The response body is empty.

-----

This is what the Admin tab looks like
![image](https://github.com/rabbitmq/rabbitmq-server/assets/4619700/e0f140ab-7fd9-428c-86a6-a77c06a77d6a)

-----

I believe this `rabbitmqctl` cmd belongs to the new deprecated features page, its output may be helpful:

```
..@rabbitmqdev:~$ sudo rabbitmqctl list_deprecated_features
Listing deprecated features ...
name                      deprecation_phase
classic_queue_mirroring   permitted_by_default
global_qos                permitted_by_default
management_metrics_collection   permitted_by_default
ram_node_type             permitted_by_default
transient_nonexcl_queues  permitted_by_default
```

**Comment by michaelklishin** [comment]
@leonjoosse what does the node log when this happens?

**Comment by SimonUnge** [comment]
Interesting. Would it be possible to see the policies you have running too?

**Comment by dumbbell** [comment]
Thank you for the report!

I see the internal format of the policy is an Erlang map instead of the expected Erlang proplist. How do you declare the policy in the first place?

**Comment by leonjoosse** [comment]
@SimonUnge @dumbbell Thanks for getting back on this. Here's the policies we defined. Only added them via the UI, they are there for quite a while already. Unfortunately, I don't know on which RabbitMQ version we added them. 

![image](https://github.com/rabbitmq/rabbitmq-server/assets/4619700/59e468fb-2173-417b-835e-839fdfaf668d)

The colleague usually managing the system got back today, on his advice I removed both policies. The error as described in the start post was immediately gone. I added both policies again, using the UI, with the exact same parameters.

This works for me, so closed the issue for now. If you have more questions, I'm happy to answer them!

**Comment by dumbbell** [comment]
Thank you for the additional feedback!

So somehow, the policy has been stored internally in an invalid format, despite the validity checks. The web UI itself can’t bypass these checks, so there must be something else going on.

Another question: did you used the definitions import/export feature?
