### ISSUE TITLE
`rabbitmq_auth_mechanism_ssl` usage docs seems invalid

### ISSUE THREAD

**Issue by getlarge** [rabbitmq/rabbitmq-server#10649]
### Describe the bug

The [usage](https://github.com/rabbitmq/rabbitmq-server/tree/main/deps/rabbitmq_auth_mechanism_ssl#usage) section of the `rabbitmq_auth_mechanism_ssl` plugin appears to be incorrect.

### Expected behavior

The first example should probably be:
```sh
auth_mechanisms.1 = PLAIN
auth_mechanisms.2 = AMQPLAIN
auth_mechanisms.3 = EXTERNAL
```
Otherwise the only mechanism available would be EXTERNAL.

**Comment by michaelklishin** [comment]
I understand what you are pointing at now. Yes, the keys must be different.

**Comment by michaelklishin** [comment]
Done https://github.com/rabbitmq/rabbitmq-server/commit/575d3d2e438747344be92ceef519f3b1621cee22
