### ISSUE TITLE
Instruction for building server package is incorrect

### ISSUE THREAD

**Issue by mydiemho** [rabbitmq/rabbitmq-server#1079]
The [instruction](http://www.rabbitmq.com/build-server.html#building-debian-package) for building Debian packages said to run this 
```
make package-deb VERSION=x.y.z.build UNOFFICIAL_RELEASE=true
```

However, there is no package-deb in the Makefile.  

I'm trying to build version 3.6.5 on a Xenial machine:

```
~/rabbitmq-server-3.6.5$ make package-deb VERSION=3.6.5 UNOFFICIAL_RELEASE=true
make: *** No rule to make target 'package-deb'.  Stop.
```

**Comment by michaelklishin** [comment]
In what Makefile specifically?

This belongs to [rabbitmq-website](https://github.com/rabbitmq/rabbitmq-website).
