### ISSUE TITLE
Channel Metrics Cardinality - /metrics stops working

### ISSUE THREAD

**Issue by akashsethiya** [rabbitmq/rabbitmq-server#10831]
### Describe the bug

I have a rabbitmq cluster (version 3.8.3) with 3 nodes. I have the rabbitmq_prometheus plugin enabled for metrics with the flag for per object metrics cz we need the queue depth metrics for each queue. 
As soon as we start scaling consumers and message load increases the /metrics endpoint stops working. 
I have a feeling it times out cz of the high cardinality of channel label in multiple metrics. Is there any way I can drop the channel lable or aggregate channel at the source itself.

### Reproduction steps

As soon as we start scaling consumers and message load increases the /metrics endpoint stops working.
I have a feeling it times out cz of the high cardinality of channel label in multiple metrics. Is there any way I can drop the channel lable or aggregate channel at the source itself.

### Expected behavior

The /metrics endpoint should respond within acceptable response time

**Comment by mkuratczyk** [comment]
RabbitMQ 3.8.3 is 4 years old and the whole 3.8 series has been out of support for a long time.
https://www.rabbitmq.com/release-information

**Comment by akashsethiya** [comment]
Does the newer version solves this problem? If yes whats the minimum version should i upgrade to ?

**Comment by mkuratczyk** [comment]
3.12 and 3.13 are the only community supported versions at this point. I can't tell if the problem will just go away, but likely yes. Either way, we are not going to investigate an issue in such an old version
