### ISSUE TITLE
A `rabbitmq-queues grow` equivalent is missing for streams

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#10830]
Much like quorum queues, streams generally assume that the (human) operator is explicit about [replica management](https://www.rabbitmq.com/docs/streams#replica-management).

Over time, `rabbitmq-queues add_replica` was largely replaced by `rabbitmq-queues grow`, which
operates on groups of queues, and is more useful during automation.

However, there is no `rabbitmq-streams grow`, an equivalent for streams. This is because streams were not designed for environments where replicas dynamically change often enough to warrant such a command. But we can at least consider it one more time.

**Comment by SimonUnge** [comment]
While we are at it, perhaps add a `shrink_all` dito too (We already have the code for it with `rabbit_stream_queue:delete_all_replicas`) ?

If not started by someone, I can add a PR this weekend or so.

**Comment by michaelklishin** [comment]
There's been some opposition to dynamically managing stream replicas. We may revisit this at some point but right now it looks like this issue won't be considered or tackled in the foreseeable future.
