### ISSUE TITLE
Topic-based authorisation for consumption

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-server#1085]
This is an umbrella issue. Related to #505.

## Current implementation of topic-based authorisation for publishes

Topic authorisation is enforced only on publishing: when a message is published to a topic exchange, there's a check against the routing key. The check takes place in the AMQP channel. Topic authorisation mainly targets MQTT and STOMP, but can also work with AMQP.

Topic permissions can be set the following way with the CLI:

```
rabbitmqctl set_topic_permissions -p '/' guest amq.topic '^a'
```
    
With this permission, `guest` can only publish messages with a routing key starting with `a` to the `amq.topic` exchange.

## Topic authorisation for consumption

This would target a client trying to consume from a topic. It would apply only to MQTT and STOMP, as it doesn't make much sense with AMQP.

We could add another permission, `read`, just like for standard permissions. With the CLI:

```
rabbitmqctl set_topic_permissions -p '/' guest amq.topic '^a' '^b'
```
    
With this permission, `guest` can consume from any topic starting with `b` (e.g. `b/c` for MQTT).

### `rabbitmq-common`

The internal authz backend must be updated to add the new permission.

### `rabbitmq-server`

Nothing much here, there would be no check this for AMQP 0-9-1 because it already has a reasonably fine grained permission system which is not based around topics.

### CLI

The commands to manage topic permissions (set, list) must updated.

### Management plugin

The endpoint to manage topic permissions (set, list) must updated.

### LDAP backend

Nothing in theory, as queries should check for the `read` permission. Documentation should be updated, and maybe a test could be added.

### AMQP backend

Just documentation update.

### HTTP backend

Just documentation update.

### MQTT

The [check when suscribing to a topic](https://github.com/rabbitmq/rabbitmq-mqtt/blob/master/src/rabbit_mqtt_processor.erl#L834) should use the new `check_topic_access/4` callback.

### STOMP

A call to `check_topic_access/4` should be added for subscription to a topic, as there's no check downstream (at the AMQP level). There's no such call in the plugin when sending to a topic, as the security check for publishing is already done at the AMQP level, in the channel.

**Comment by uvzubovs** [comment]
Would you please clarify how this is expected to work on the consumer end? The regex that controls which routing keys are delivered seems to be applied to the consumer user and exchange, but consumer is connected to a queue. Will all messages go to the queue but only some dispatched to the consumer? What happens to the remaining messages? And, why are there 2 regular expressions in the rabbitmqctl command for the consumer?

**Comment by michaelklishin** [comment]
Message distribution happens at the routing stage, therefore that's where the permission is verified.
Everything that's routed is then consumed by consumers unconditionally. This is not really different from any past version of RabbitMQ.

**Comment by uvzubovs** [comment]
From your response and [https://github.com/rabbitmq/rabbitmq-website/commit/de19f01ca6cc7affef0dba5415f7e092f641b061](url) do I understand correctly that consumer permission is tested in the MQTT plug-in, i.e. if MQTT consumer attempts to subscribe to MQTT topic "foo" then MQTT plugin will only create queue with binding key "foo" if such permission exists, and that is all that controls message delivery to the MQTT consumer?

**Comment by michaelklishin** [comment]
MQTT plugin has a chance to perform checks as it needs to but it introduces no new settings, by design:

 * https://github.com/rabbitmq/rabbitmq-mqtt/pull/128/files
 * https://github.com/rabbitmq/rabbitmq-mqtt/pull/115/files
 * https://github.com/rabbitmq/rabbitmq-mqtt/pull/116/files

**Comment by michaelklishin** [comment]
So when MQTT plugin handles a `SUBSCRIBE` or `PUBLISH` frame or has to send a message on behalf of a client (think Last Will), it has a way of checking topic authorization permissions.

**Comment by uvzubovs** [comment]
Ok. Thank you for confirming.

One authorization use-case requires restricting the MQTT consumers to "own" topics, i.e. have one permission apply to all users. Mosquitto [solves](https://mosquitto.org/man/mosquitto-conf-5.html) this problem via %u substitution, i.e. "data/%u" permission would only allow the user "foo" to subscribe to the "data/foo" topic and user "bar" to "data/bar" topic. Is this supported?

**Comment by michaelklishin** [comment]
Topic authorization patterns are regular expressions. There are no variable substitution in this feature or anywhere else in RabbitMQ.

**Comment by uvzubovs** [comment]
Do you think you could accept this as an enhancement? Otherwise, topic authorization may not be practical when the number of user is too large to list.

**Comment by michaelklishin** [comment]
@uvzubovs I can see how it'd be useful to have. We will discuss it with the team.

**Comment by uvzubovs** [comment]
Thank you. Mosquitto also [supports](https://mosquitto.org/man/mosquitto-conf-5.html) %c substitution for the client id. This is important when consumer needs to know from which client the message came in case it needs to respond back to that client -- kind of like request/reply -- and, so, client publishes a message and subscribes to the topic that reflects that client's MQTT client id.

**Comment by michaelklishin** [comment]
@uvzubovs there is a separate issue for this feature specifically in the MQTT plugin https://github.com/rabbitmq/rabbitmq-mqtt/issues/95.

We will consider a spike that replaces username and client ID (or similar, e.g. subscription ID in STOMP) in patterns before 3.7.0.

**Comment by uvzubovs** [comment]
Before 3.7.0 meaning in 3.6..x?

**Comment by michaelklishin** [comment]
Before 3.7.0 RC1 ships.
