### ISSUE TITLE
Socket-based authorization does not work for protocol adapters like MQTT

### ISSUE THREAD

**Issue by gotthardp** [rabbitmq/rabbitmq-server#109]
When the rabbit_direct.erl is calling the rabbit_access_control:check_vhost_access() it sets the Sock parameter to 'undefined', what prevents proper socket-based access control (like e.g. done by rabbitmq-auth-backend-ip-range).

**Comment by michaelklishin** [comment]
I think this should be fixed on the case-by-case basis, as there is no socket in the direct client's case. So this is the wrong repo to report this.

We can either try using a "fake socket" record, or try passing the actual client socket, or pass more info in extra client parameters. So belongs to the Erlang client and MQTT/STOMP.

**Comment by gotthardp** [comment]
There is no need to change the Erlang client nor MQTT/STOMP. The information is available to the server already. It just doesn't pass them to the authentication function. See my e-mail on the mailing list. Hence I think this is a correct repository.

**Comment by michaelklishin** [comment]
Commented what I'd do on the list. Thank you for looking into this!

**Comment by michaelklishin** [comment]
Should be fixed by #110, given that the relevant plugins are updated or already support the new record.
