### ISSUE TITLE
long-long-int ("L"-prefixed) table field decoding is not supported

### ISSUE THREAD

**Issue by lukasgeyer** [rabbitmq/rabbitmq-server#1093]
Setting the `x-message-ttl` argument to a `long-long-int` value (which is allowed according to https://www.rabbitmq.com/ttl.html#per-queue-message-ttl, *The argument can be of AMQP type short-short-int, short-int, long-int, or long-long-int.*) causes a `no function clause matching` exception to be thrown :
```
=CRASH REPORT==== 30-Jan-2017::16:20:52 ===
  crasher:
    initial call: rabbit_reader:init/4
    pid: <0.24601.16>
    registered_name: []
    exception error: no function clause matching
                     rabbit_binary_parser:parse_table(<<13,120,45,109,101,115,
                                                        115,97,103,101,45,116,
                                                        116,108,76,0,0,0,0,0,
                                                        0,11,184>>) (src/rabbit_binary_parser.erl, line 50)
      in function  rabbit_framing_amqp_0_9_1:decode_method_fields/2 (src/rabbit_framing_amqp_0_9_1.erl, line 786)
      in call from rabbit_command_assembler:process/2 (src/rabbit_command_assembler.erl, line 81)
      in call from rabbit_reader:process_frame/3 (src/rabbit_reader.erl, line 978)
      in call from rabbit_reader:handle_input/3 (src/rabbit_reader.erl, line 1035)
      in call from rabbit_reader:recvloop/4 (src/rabbit_reader.erl, line 446)
      in call from rabbit_reader:run/1 (src/rabbit_reader.erl, line 428)
      in call from rabbit_reader:start_connection/4 (src/rabbit_reader.erl, line 386)
    ancestors: [<0.24599.16>,<0.284.0>,<0.283.0>,<0.282.0>,rabbit_sup,
                  <0.164.0>]
    messages: [{'EXIT',#Port<0.43454>,normal}]
    links: [<0.24599.16>]
    dictionary: [{process_name,
                      {rabbit_reader,<<"127.0.0.1:42236 -> 127.0.0.1:5672">>}},
                  {{ch_pid,<0.24609.16>},{1,#Ref<0.0.1572865.75873>}},
                  {{channel,1},
                   {<0.24609.16>,{method,rabbit_framing_amqp_0_9_1}}}]
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 4193
  neighbours:
```
Using `long-long-uint` (`6c`) instead of `long-long-int` (`4c`) works. The frame is identical in both cases (except for the value type).
```
0000   01 00 01 00 00 00 2c 00 32 00 0a 00 00 09 71 75  ......,.2.....qu
0010   65 75 65 4e 61 6d 65 08 00 00 00 17 0d 78 2d 6d  eueName......x-m
0020   65 73 73 61 67 65 2d 74 74 6c 6c 00 00 00 00 00  essage-ttll.....
0030   00 0b b8 ce                                      ....

0000   01 00 01 00 00 00 2c 00 32 00 0a 00 00 09 71 75  ......,.2.....qu
0010   65 75 65 4e 61 6d 65 08 00 00 00 17 0d 78 2d 6d  eueName......x-m
0020   65 73 73 61 67 65 2d 74 74 6c 4c 00 00 00 00 00  essage-ttlL.....
0030   00 0b b8 ce                                      ....
```
RabbitMQ is `3.6.6`, Erlang is `19.2.1`. The same problem is also experienced on `3.6.5` and `19.1.5`.

**Comment by michaelklishin** [comment]
Do you have a script that reproduces this?

Also, does it make sense to use signed integers for TTL?

**Comment by lukasgeyer** [comment]
As most of the script-based libraries only support `long-long-uint`, but not `long-long-int` this minimal working example uses a patched version of `pika` to generate a `4c` instead of a `6c`. Declaring *any* entity with a `long-long-int` field value seems to trigger the exception:
```
+++ data.py     2017-01-31 08:34:07.000000000 +0100
@@ -119 +119 @@
-        pieces.append(struct.pack('>cq', b'l', value))
+        pieces.append(struct.pack('>cq', b'L', value))
```
```
import pika
connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
channel = connection.channel()
channel.queue_declare(queue='queueName', auto_delete=True, arguments={'fieldName': long(3000)})
```
```
=INFO REPORT==== 31-Jan-2017::08:43:41 ===
accepting AMQP connection <0.7099.3> (127.0.0.1:42853 -> 127.0.0.1:5672)

=CRASH REPORT==== 31-Jan-2017::08:43:41 ===
  crasher:
    initial call: rabbit_reader:init/4
    pid: <0.7099.3>
    registered_name: []
    exception error: no function clause matching
                     rabbit_binary_parser:parse_table(<<9,102,105,101,108,100,
                                                        78,97,109,101,76,0,0,
                                                        0,0,0,0,11,184>>) (src/rabbit_binary_parser.erl, line 50)
      in function  rabbit_framing_amqp_0_9_1:decode_method_fields/2 (src/rabbit_framing_amqp_0_9_1.erl, line 786)
      in call from rabbit_command_assembler:process/2 (src/rabbit_command_assembler.erl, line 81)
      in call from rabbit_reader:process_frame/3 (src/rabbit_reader.erl, line 978)
      in call from rabbit_reader:handle_input/3 (src/rabbit_reader.erl, line 1035)
      in call from rabbit_reader:recvloop/4 (src/rabbit_reader.erl, line 446)
      in call from rabbit_reader:run/1 (src/rabbit_reader.erl, line 428)
      in call from rabbit_reader:start_connection/4 (src/rabbit_reader.erl, line 386)
    ancestors: [<0.7097.3>,<0.277.0>,<0.276.0>,<0.275.0>,rabbit_sup,
                  <0.153.0>]
    messages: [{'EXIT',#Port<0.28188>,normal}]
    links: [<0.7097.3>]
    dictionary: [{{channel,1},
                   {<0.7107.3>,{method,rabbit_framing_amqp_0_9_1}}},
                  {process_name,
                      {rabbit_reader,<<"127.0.0.1:42853 -> 127.0.0.1:5672">>}},
                  {{ch_pid,<0.7107.3>},{1,#Ref<0.0.262145.55082>}}]
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 4046
  neighbours:

=SUPERVISOR REPORT==== 31-Jan-2017::08:43:41 ===
     Supervisor: {<0.7097.3>,rabbit_connection_sup}
     Context:    child_terminated
     Reason:     function_clause
     Offender:   [{pid,<0.7099.3>},
                  {name,reader},
                  {mfargs,
                      {rabbit_reader,start_link,
                          [<0.7098.3>,
                           {acceptor,{0,0,0,0,0,0,0,0},5672},
                           #Port<0.28188>]}},
                  {restart_type,intrinsic},
                  {shutdown,30000},
                  {child_type,worker}]


=SUPERVISOR REPORT==== 31-Jan-2017::08:43:41 ===
     Supervisor: {<0.7097.3>,rabbit_connection_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.7099.3>},
                  {name,reader},
                  {mfargs,
                      {rabbit_reader,start_link,
                          [<0.7098.3>,
                           {acceptor,{0,0,0,0,0,0,0,0},5672},
                           #Port<0.28188>]}},
                  {restart_type,intrinsic},
                  {shutdown,30000},
                  {child_type,worker}]
```
I agree that it does not make sense to use a signed integer for the TTL, but there seems to be a general problem with `long-long-int` (apart from the fact that the documentation requires a signed integer to be used, see https://www.rabbitmq.com/ttl.html#per-queue-message-ttl).

**Comment by michaelklishin** [comment]
@lukasgeyer well, what client did you originally reproduce this with? I haven't seen anyone report this in ~ 8 years around RabbitMQ clients, so I am considering just updating the docs. But perhaps we can support signed values easily and safely, needs a bit of investigation.

**Comment by michaelklishin** [comment]
So it can be a matter of adding one [more clause for `L` fields](https://github.com/rabbitmq/rabbitmq-common/blob/stable/src/rabbit_binary_parser.erl#L71) (as opposed to `l`, that's a lowercase L):

```
?SIMPLE_PARSE_TABLE($L, Value:64/signed, long);
```

Will wait for a client to reproduce with without hacking Pika.

**Comment by michaelklishin** [comment]
While not really relevant for TTL, I've noticed that Java client [doesn't support decoding of `L` values](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/ValueReader.java#L190) or [encoding them](https://github.com/rabbitmq/rabbitmq-java-client/blob/8374f588ff0efdab4956024a985a9adf68aedd37/src/main/java/com/rabbitmq/client/impl/ValueWriter.java#L178), and as you've pointed out, with a bunch of dynamically typed languages unsigned value types typically do not exist.

So this might explain why this wasn't reported earlier: most likely this can only be reproduced with a handful of clients, like librabbitmq-c and perhaps Objective-C, Go, Rust, Haskell ones.

**Comment by michaelklishin** [comment]
Yup, [.NET client is the same way](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/5d0377b4b0cf6e640ba2477f54ee76787813ccdf/projects/client/RabbitMQ.Client/src/client/impl/WireFormatting.cs#L145).

**Comment by lukasgeyer** [comment]
The initial client was `AMQP-CPP`, but the frame is the same, regardless of the client. 
```
#include <event2/event.h>
#include <amqpcpp.h>
#include <amqpcpp/libevent.h>

int main()
{
    auto evbase = event_base_new();

    AMQP::LibEventHandler handler(evbase);

    AMQP::TcpConnection connection(&handler, AMQP::Address("amqp://guest:guest@localhost/"));

    AMQP::Table queueArguments;
    queueArguments.set("x-message-ttl", static_cast<std::int64_t>(3000));

    AMQP::TcpChannel channel(&connection);
    channel.declareQueue("queueName", queueArguments);

    event_base_dispatch(evbase);
    event_base_free(evbase);

    return 0;
}
```
> But perhaps we can support signed values easily and safely, needs a bit of investigation.

Does this mean that RabbitMQ does not support `*-int` at all, or is it just `long-long-int`?

I am fine with updating the documentation of Per-Queue Message TTL (and using `long-long-uint` instead), but is the fact that RabbitMQ does not support `long-long-int` documented somewhere too (if not it most probably should, shouldn't it)?

**Comment by michaelklishin** [comment]
@lukasgeyer yes, it does mean that. I'm pretty surprised the docs even mention those types, it could easily say "an integer".

I do not object to supporting `L` fields.

**Comment by lukasgeyer** [comment]
Out of curiosity, is there any negative impact on the server when this exception is thrown (except for the related client)?

**Comment by michaelklishin** [comment]
See [RabbitMQ Errata to AMQP 0-9-1 spec](http://www.rabbitmq.com/amqp-0-9-1-errata.html), which mentions a couple of relevant topics in section 4.

While supporting `L` fields is a matter of adding one function clause in `rabbit_binary_parser`, it looks like the behaviour we currently have is not necessarily a mistake.

I did discover another curious thing. In `rabbit_binary_parser`, `l` (a lowercase L) is treated as a signed 64 bit value prefix. [The spec](http://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf) in section 4.2.1 suggests it should mean "unsigned" and `L` should mean signed.

While we can update a few clients we maintain, I'm not sure this is worth fixing in general, given how many existing apps can be affected in subtle ways without any real upside to the fix.

As a middle ground solution that won't affect existing clients, we can add a clause for `L` fields that also decodes them as 64-bit signed integers.

@lukasgeyer WDYT?

**Comment by michaelklishin** [comment]
No, it's treated the same way as if a client sent something else that's unparseable.

**Comment by michaelklishin** [comment]
@lukasgeyer I have submitted a PR that will decode `L` values as 64-bit long signed values without changing how `l` fields are handled. See RabbitMQ Errata document section 3 and the above comment. I hope this is sufficient for your case. Since it's backwards-compatible, we can ship it in 3.6.7.

**Comment by lukasgeyer** [comment]
Thanks for the reference, I had a look at the 0.9.1 specification only and wondered why RabbitMQ would behave different in this case and that there must be something going on.

I agree with your middle ground solution, this should not break any existing client and will add (standards-compliant) support for those who use `L`. This is definitely a solution to our use case, thanks.

**Comment by michaelklishin** [comment]
@lukasgeyer thank you, unless there's something serious that I'm overlooking, this should land in `3.6.7`.
