### ISSUE TITLE
3.11: two Raft replicas are in the timeout state, one is a candidate

### ISSUE THREAD

**Issue by gsingla294** [rabbitmq/rabbitmq-server#10936]
### Describe the bug

I am frequently facing an issue which is mentioned in discussion #10934 where 2 Raft state on 2 pods goes into timeout and one in candidate state. 
![image](https://github.com/rabbitmq/rabbitmq-server/assets/11535412/71ce0d1c-8562-46b6-9e34-ba66d7b59505)

There @michaelklishin mentioned to upgrade to 3.13.1 
Any specific updated in 3.13 which might resolve the issue or any other improvement/update done regarding this issue?
This will help us in to understand why it occurs.

### Reproduction steps

Create a 3 pod MQ cluster on AKS kubernetes cluster.
I might not have steps to reproduce it as there is not specific pattern and it is happening randomly.

### Expected behavior

Raft state should not go in timeout state.

**Comment by mkuratczyk** [comment]
We don't know if 3.13 will fix your problem but this doesn't change the fact that 3.11 is out of community support. It's on your to provide this is still a problem in the latest version.

Also, you shared effectively no data to investigate. If you want us to investigate, share logs from all nodes when this issue occurs on 3.13.

**Comment by gsingla294** [comment]
As you are an expert @mkuratczyk do you have any quick clue on why this might be happening? I can do more research on that. This will help in identifying meanwhile we upgrade as in production upgrade might take time.

**Comment by mkuratczyk** [comment]
Clues should be in the logs.

If you can't upgrade production - deploy a test env where you'll try to trigger this behaviour on 3.13.

**Comment by lukebakken** [comment]
This user has opened the following discussion - https://github.com/rabbitmq/rabbitmq-server/discussions/10951

**Comment by michaelklishin** [comment]
@gsingla294 you have been told to upgrade or seek help elsewhere in  https://github.com/rabbitmq/rabbitmq-server/discussions/10934 and you have figured you'd just start another discussion instantly. And then https://github.com/rabbitmq/rabbitmq-server/discussions/10951 without mentioning 3.11 because you think are are dummies.

This is nothing short of spam and disrespect towards the core team => you won't be able to file any issues in this org for a while.
