### ISSUE TITLE
Differentiate between Auth Error and Denied

### ISSUE THREAD

**Issue by ngoossens** [rabbitmq/rabbitmq-server#1094]
Currently it seems there is no way to determine the difference between an auth error (e.g. auth_backend service down) or auth being denied by a auth_backend.

This can cause issues when trying to reestablish a connection and falsely notifying the user their credentials are incorrect when it is actually a backend failure.

The problem affects different protocols for example AMQP with `authentication_failure_close` enabled will return `ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.` while STOMP will return `Access refused for user 'username'`

Could more information be provided as part of these messages?

**Comment by michaelklishin** [comment]
This is not necessarily by accident: if a backend is down, RabbitMQ can only do one thing: deny access. Clients do not really care what really happened most of the time (hosted RabbitMQ is the only case I can think of), nor can they do much about it. Server logs should make it reasonably clear what happened.

Lastly, some backends can be down while others can't: internal and cache don't necessarily have the same context.

So I'm not convinced this is a good idea, or would be much of an improvement for many cases. Please take this to rabbitmq-users and convince the team there.

**Comment by ngoossens** [comment]
Thanks for the reply @michaelklishin. I will consider my arguments and decide whether a post to rabbitmq-users is required.
