### ISSUE TITLE
Management UI creates classic queue instead of virtual host default queue type in some circumstances

### ISSUE THREAD

**Issue by SignalWhisperer** [rabbitmq/rabbitmq-server#11088]
### Describe the bug

In the management UI, when I go to create a new queue and elect to use the `Default for virtual host`, I am presented with the queue `Durability` selector. When the virtual host default queue type is `quorum` or `stream`, selecting `Transient` will give me a `classic` queue instead. Selecting `Durable` gives me the expected queue type.

<img width="372" alt="image" src="https://github.com/rabbitmq/rabbitmq-server/assets/772200/eaa8436a-1f14-4e43-8f30-10849813203f">
<br>
<img width="230" alt="image" src="https://github.com/rabbitmq/rabbitmq-server/assets/772200/ecac0465-9d3b-4af7-a59c-49c6993c58f9">
<br>
<img width="315" alt="image" src="https://github.com/rabbitmq/rabbitmq-server/assets/772200/d1fc6ee3-2d6b-4587-ac3e-ba659cf1c639">
<br>
<img width="408" alt="image" src="https://github.com/rabbitmq/rabbitmq-server/assets/772200/ba50f880-7cc4-4838-9135-1db4d4678d9e">
<img width="407" alt="image" src="https://github.com/rabbitmq/rabbitmq-server/assets/772200/296e2b1e-0b1c-4208-9414-12e320a30716">

<br>
<br>

When selecting `quorum` or `stream` as the queue `Type` instead of `Default for virtual host`, the `Durability` selector disappears.

<img width="318" alt="image" src="https://github.com/rabbitmq/rabbitmq-server/assets/772200/a7aea217-3dbc-4f8f-86f5-7b092bb9565d">

### Reproduction steps

1. Create a new virtual host with `quorum` or `stream` as the default queue type
2. Go to the `Queues and Streams` tab
3. Select your new virtual host in the `Virtual host` selector
4. Select `Default for virtual host` for the queue `Type` selector
5. _Observe there is a `Durability` selector visible_
6. Give the queue a name
7. Select `Transient` for the `Durability` selector
8. Create the queue
9. _Observe it is created as a `classic` queue_

### Expected behavior

The `Durability` selector should not be shown when the default queue type for that virtual host is `quorum` or `stream`.

It should also not give me a `classic` queue when I select `Transient` but rather an error message (debatable as fixing the above expected behaviour would render the error message irrelevant).

**Comment by SignalWhisperer** [comment]
Sorry, I forgot to mention this was identified on RabbitMQ 3.13.0 and repeated on 3.13.1.

**Comment by SimonUnge** [comment]
I would say its intentional:

```
    case vhost:get_metadata(V) of
        #{default_queue_type := DefaultQueueType}
          when is_binary(DefaultQueueType) andalso
               not HasQTypeArg ->
            Type = rabbit_queue_type:discover(DefaultQueueType),
            IsPermitted = is_queue_args_combination_permitted(
                            Durable, Exclusive),
            IsCompatible = rabbit_queue_type:is_compatible(
                             Type, Durable, Exclusive, AutoDelete),
            case IsPermitted andalso IsCompatible of
                true ->
                    %% patch up declare arguments with x-queue-type if there                                                                                                                                                                                 
                    %% is a vhost default set the queue is durable and not exclusive                                                                                                                                                                         
                    %% and there is no queue type argument                                                                                                                                                                                                   
                    %% present                                                                                                                                                                                                                               
                    rabbit_misc:set_table_value(Args0,
                                                <<"x-queue-type">>,
                                                longstr,
                                                DefaultQueueType);
                false ->
                    Args0
            end;
...
```

The alternative would be to always patch the args and later fail.

**Comment by michaelklishin** [comment]
Quorum queues and streams never meant to be durable. In 4.x, transient entities will no longer exist.
