### ISSUE TITLE
4.x: reduce default maximum message size further (e.g. to 64 or 50 MiB)

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#11187]
This is a follow-up to https://github.com/rabbitmq/rabbitmq-server/pull/1812.

We can and should lower the limit from its current 128 MiB. The idea in #1812 was to gradually lower it from its original 512 MiB default but we have missed the opportunity to go to, say, 64 MiB in 3.13.x. Oh well.

I guess 4.0 can use a 64 MiB or a 50 MiB limit.

Background: https://github.com/rabbitmq/rabbitmq-server/issues/11072.

**Comment by gomoripeti** [comment]
thank you for creating this ticket.

I don't have a good sense of what is a typical and acceptable large message, we don't have good statistics yet about them. We only notice large messages when they cause problems.

Therefore I'm in favour of using the opportunity of 4.0 being a major version bump with breaking changes and reduce the default more drastically, let's say 1MB or 4MB. (This is just default, so users who need them can adjust it)

It's easier to gather metrics about average sizes than maximum size, but I will try to gather some data before 4.0.

**Comment by michaelklishin** [comment]
@gomoripeti 50 MiB should be plenty for most, plus this is the default, not the hard limit. We should keep reducing the hard limit all the way down to something like 100 MiB.

**Comment by michaelklishin** [comment]
This is one of those settings where any default is "wrong". What we can do is be more defensive with a lower limit, so 50 MiB is as good as 64 MiB.

**Comment by carlhoerberg** [comment]
For the record, I'm fully against this change. While it might not be optimal the broker should handle large messages and any new artificial limit will break peoples product code.

**Comment by kjnilsson** [comment]
I disagree it is artificial (although we should perform further testing). The fact that RabbitMQ has not had any sensible limits in the past just means that the problem of large messages has never been solved. RabbitMQ queue type storage engines (particularly replaced ones) aren't optimised or designed for very large message sizes. Therefore it is essential that the broker is limited to a range that we can validate is can cope with well.

This is not without precedence: Azure Service Bus standard tier has a limit of 256KB rising to 100MB for the premium tier. SQS is also limited to 256KiB and, IIRC, uses S3 via their client libraries to store larger messages and pass a reference around.

Lowing max message size limits will force users to design their messages system in a more reliable and safe way. This is, IMO, a very good thing.

**Comment by carlhoerberg** [comment]
That's a very bad thing, it forces ppl off RabbitMQ. What RabbitMQ should do is to optimize for that use case. What is the fundamental problem (don't look at RabbitMQ in its current state) to have large messages in a stream or message queue? How is it more efficient from an end users perspective to add another layer in their stack, the same bytes still have to be uploaded and downloaded somewhere? Why not together with the message metadata?

**Comment by lhoguin** [comment]
When the message reaches sizes as high as 50MiB or more, there isn't much that can be done to optimise anything. Best we can do is ensure rabbit doesn't blow up, and even then only so much can be done. A message broker that deals with small messages is a very different beast to one that deals with very large messages. For messages this size we would likely require a separate component: meaning that within rabbit we wouldn't keep the payload and metadata together (the same thing users should do today).

That said, 256KiB is a bit low, we definitely can handle more than that at least in classic queues and I'm sure in other parts of rabbit as well.

Changing the default to 50MiB wouldn't change the problem much, it's still high enough that we can't completely prevent nodes from blowing up. But it's a step toward a safer default. Ideally the default would be a size we actually test during development.

Finally, we are only changing the default. Users can easily configure greater values if needed.

**Comment by michaelklishin** [comment]
> While it might not be optimal the broker should handle large messages and any new artificial > limit will break peoples production code

@carlhoerberg you are welcome to use your company's data set to see how many users actually use messages larger than 64 MiB and 512 MiB. From our team's experience, not many and those who do generally agree that storing large messages in a blob store is a reasonable idea. In my 14 years around RabbitMQ, I recall exactly one case where large message support was specifically required and using a blob store was impossible.

Anyone is welcome to develop a new queue type and a set of client library optimizations outlined above, and demonstrate their effectiveness. In particular companies that directly 
make money off of RabbitMQ.

**Comment by michaelklishin** [comment]
> RabbitMQ queue type storage engines (particularly replicated ones) aren't optimised or designed for very large message sizes

To expand on this: the core team does run various workloads with large messages (up to a few dozens of MiBs). We know well what kind of effects it has both on the message stores used in RabbitMQ and on the **inter-node connectivity links**.

Today RabbitMQ uses Erlang distribution for most key distribution/replicated features, such as: message routing between nodes (performed by connections/channels, depending on the protocol), quorum queues, the schema data store (including Khepri). Streams use dedicated TCP connections and that is one of the key factors behind their efficiency with practical workloads.

How is that relevant to this issue? Very directly: Erlang/OTP has long had a problem with distribution links being a bottleneck when (Erlang) messages in a workload are large. [Starting with Erlang 22](https://www.erlang.org/blog/otp-22-highlights/#fragmented-distribution-messages), the inter-node communication protocol has changed to use fragmented (chunked) transfers and that has made a massive positive difference for RabbitMQ cluster stability with loads close to peak.

And yet, we have since decided to use dedicated connections for streams, and that turned out
to be the right decision for multiple technical reasons.

So workloads with large and very large messages (I'd call that all messages above 8 MiB and 32 MiB, respectively) do put stress to various parts of the system that may not seem related.

An attempt to support large and very large messages would require changing inter-node communication in many — in fact, most — places, and it is pretty difficult to justify given
that comfortably over 95% of users do not use messages larger than 32 MiB from the core team's experience.

This would likely make Ra replication borrow from what we use in Osiris (the foundational library for RabbitMQ Streams), see how well that works for QQs and Khepri, then produce a major Ra version, consider an upgrade path (a royal pain of most significant changes in any distributed data service), then integrate it. Assuming that it all goes well, this may ship in RabbitMQ 5.x.

Or, perhaps, key contributors can simply agree that we can improve things somewhat for large messages (> 8 MiB) but that very large messages simply belong to the blob store. In particular given that some companies **charge you extra** if you want to publish messages over just 256 kiB in size.

**Comment by michaelklishin** [comment]
And finally, speaking of links and data-based decisions.

A 50 MiB message would require a `50MiB * 8 bits per byte = 400MBit/s` network link to transfer just one message's payload per second. At 125MiB that'd be 1 GBit/s. A 500 MiB message? 4 GBit/s.

Most typical links offered by many infrastructure providers is usually lower than 1 GBit/s.
So to run a realistic workload where messages are that large would require using
an amount of bandwidth well above the standard.

By using a blob store you get some if not all the well known benefits of caching: less
data to transfer, only the apps that need to access the complete blob will (as opposed
to gigantic messages being shoved down their throats), etc.

And if you think that network bandwidth is dirt cheap and "infinite", consider [this story](https://blog.twitch.tv/en/2023/12/05/an-update-on-twitch-in-korea/). Apparently
very large data volumes present all kinds of less-than-obvious problems.

**Comment by Openegg15** [comment]
Hello, I can't get your result :( could you make a short explanatory video?
▶️ [https://www.google.com/url?q=https://rausauboocad.net/4/7446717&source=gmail&ust=1716691528073000&usg=AOvVaw3JKd7aljBG60oF20SH6_JP](https://www.google.com/url?q=https%3A%2F%2Frausauboocad.net%2F4%2F7446717&source=gmail&ust=1716691528073000&usg=AOvVaw3JKd7aljBG60oF20SH6_JP&fbclid=IwZXh0bgNhZW0CMTAAAR1TgswIg8LcAjuYU3rAMZfPrIuAnLugsaOuh5uRw27zb3Dli68odRaOpKc_aem_ARf1KSpu-FHJKFMZ_rdkcvEgrU9oWN-xLnc0UjYQvuLWphs95s9_vrud7dnV5H9ATBNURhVKti-CMLvL_c2mPEjV)

**Comment by madmalkav** [comment]
Dunno if useful but in my 10 years working in industrial environments with other MQ software that sets default to 4MB, I rarely  had to increase that limit, and I don't remember setting it to more than 10 or 12MB

**Comment by michaelklishin** [comment]
The new value (for 4.0) was set to 16 MiB. It is

 * Roughly the mid-point of several values mentioned in this thread and privately by teams with very large RabbitMQ cluster fleets
 * A value that CQv2 (maybe by then called CQv3) will handle well and reasonably efficiently as of 4.0 (per discussion with @lhoguin)
