### ISSUE TITLE
Improve logs on stop.

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#1122]
If rabbitmq fails to stop, it can be hard to investigate a reason. Stopping broker should log more information.

**Comment by OdellDotson** [comment]
Issue should be marked as closed, no?
[This](https://github.com/rabbitmq/rabbitmq-server/pull/1141) and [this](https://github.com/rabbitmq/rabbitmq-common/pull/187) seem to have addressed the issue.

**Comment by michaelklishin** [comment]
@OdellDotson thank you.
