### ISSUE TITLE
Core metrics GC throw badarg when checking processes.

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#1125]
Follow up to #1118 
When using `direct` connections, badarg error is logged every N seconds.
https://github.com/rabbitmq/rabbitmq-server/blob/stable/src/rabbit_core_metrics_gc.erl#L104
`is_process_alive` will fail with `badarg` trying check a remote process.
We should consider using `rpc` or ignoring remote processes.

**Comment by michaelklishin** [comment]
Ignoring is sufficient since core metrics are node-local by definition.

**Comment by hairyhum** [comment]
But the issue happens when we have remote PID in it, so this specific case is not node-local.

More context:

- start rabbitmq,
- start erlang client in separate erlang node,
- open a connection using `amqp_params_direct`
- open a channel
- wait 
- search logs for:
```
2017-02-24 18:11:43.449 [info] <0.11098.4> Stopping RabbitMQ
2017-02-24 18:12:49.491 [error] <0.11090.4> ** Generic server rabbit_core_metrics_gc terminating 
** Last message in was start_gc
** When Server state == {state,#Ref<0.0.7864323.113940>,120000}
** Reason for termination == 
** {badarg,[{erlang,is_process_alive,[<27525.720.0>],[]},{rabbit_core_metrics_gc,gc_process,3,[{file,"src/rabbit_core_metrics_gc.erl"},{line,104}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{ets,do_foldl,4,[{file,"ets.erl"},{line,585}]},{ets,foldl,3,[{file,"ets.erl"},{line,574}]},{rabbit_core_metrics_gc,gc_connections,0,[{file,"src/rabbit_core_metrics_gc.erl"},{line,62}]},{rabbit_core_metrics_gc,handle_info,2,[{file,"src/rabbit_core_metrics_gc.erl"},{line,42}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]}]}
2017-02-24 18:12:49.491 [error] <0.11090.4> CRASH REPORT Process rabbit_core_metrics_gc with 0 neighbours exited with reason: bad argument in call to erlang:is_process_alive(<27525.720.0>) in rabbit_core_metrics_gc:gc_process/3 line 104
```

**Comment by michaelklishin** [comment]
My point is that stats GC processes should ignore non-local processes.

**Comment by hairyhum** [comment]
But if this non-local process will be killed without an event it can still be lost, right?

**Comment by michaelklishin** [comment]
You are right, we should RPC to target process' nodes (or do what we already do if the pid is local).
