### ISSUE TITLE
Look at the issues with RabbitMQ packaging the official Docker image has to work around

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#113]
A RabbitMQ Docker image is available from the Docker hub:
https://registry.hub.docker.com/_/rabbitmq/

The source for this image is on GitHub:
https://github.com/docker-library/rabbitmq

By quickly reading those files, they work around some issues they have with our startup scripts. We should look at this and improve the situation.

**Comment by michaelklishin** [comment]
If we've merged the two improvements discovered on our end, should this be closed?

**Comment by dumbbell** [comment]
I was waiting for some last comments from Docker people. They are happy now :-)
