### ISSUE TITLE
Shovels cant be deleted if they dont connect

### ISSUE THREAD

**Issue by womblep** [rabbitmq/rabbitmq-server#11316]
### Describe the bug

A shovel that is created but hasnt made a connection due to misconfiguration or connection issues cannot be deleted either via the shovel_management plugin or via rabbitmqctl

### Reproduction steps

create a shovel that wont connect properly (SSL parameter mismatch or misconfiguration)
try to delete the shovel via shovel_management
![image](https://github.com/rabbitmq/rabbitmq-website/assets/20149897/08bb29b8-ce01-4906-b741-fea0dc4a9a18)

try to delete via rabbitmqctl
>rabbitmqctl delete_shovel test
Deleting shovel test in vhost /
Error:
Shovel with the given name was not found on the target node 'rabbit@rabbitmq2' and / or virtual host '/'

### Expected behavior

Shovel should be removed

**Comment by lukebakken** [comment]
Hello, thanks for using RabbitMQ.

Please, you _must_ let us know what version of RabbitMQ and Erlang you are using.

**Comment by michaelklishin** [comment]
I cannot reproduce with 3.13.2.
