### ISSUE TITLE
prometheus.filter_aggregated_queue_metrics_pattern has no effect

### ISSUE THREAD

**Issue by LoisSotoLopez** [rabbitmq/rabbitmq-server#11315]
### Describe the bug

`prometheus.filter_aggregated_queue_metrics_pattern` configuration is to contain a string representing the queue names for queues to filter out when collecting metrics on the `prometheus_rabbit_core_metrics_collector`. 

Such config gets read from the `rabbitmq_prometheus` app environment [here](https://github.com/rabbitmq/rabbitmq-server/blob/41922cad4d72377d1616b2e35dd86e617f5c97d4/deps/rabbitmq_prometheus/src/rabbit_prometheus_handler.erl#L175). A few lines below if such env. var. existed it is treated as a RegEx, gets compiled and inserted on the process dictionary. If no such env. var. existed, nothing gets put on the process dictionary. [Later on the program flow](https://github.com/rabbitmq/rabbitmq-server/blob/41922cad4d72377d1616b2e35dd86e617f5c97d4/deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl#L738), the functions on the `prometheus_rabbitmq_core_metrics_collector` read the process dictionary and propagate as `QueueFilters` either the compiled RegEx or the `false` atom.

This `QueueFilters` would be used to determine whether an entry on any of the `ets` tables storing metrics gets filtered out or not, [such as here](https://github.com/rabbitmq/rabbitmq-server/blob/41922cad4d72377d1616b2e35dd86e617f5c97d4/deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl#L545), but since the `QueueFilters` variable is either a compiled regular expression or `false`, the `is_list()` check will never return true and apply the filter.

### Reproduction steps

1. Run the tests on  `deps/rabbitmq_prometheus/test/rabbit_prometheus_http_SUITE.erl` prepending the following function call to any test that returns metrics via functions implementing the queue filtering.

```
    rabbit_ct_broker_helpers:rpc(
      Config, 0, application, set_env, [rabbitmq_prometheus, filter_aggregated_queue_metrics_pattern, ".*"]),
```

Such line filters out any metric related to queues which name matches the ".*" regex, so no metric should get collected and test asserts should fail, but they don't.

### Expected behavior

Either the filters get evaluated in the proper way or we remove the lines of codes related to them.

### Additional context

Observed while solving #11217

**Comment by mkuratczyk** [comment]
Personally I have no problem removing an option that I wasn't aware existed, which doesn't do anything anyway. :)

**Comment by gomoripeti** [comment]
thanks Michal for the feedback 🚀
