### ISSUE TITLE
rabbit_heartbeat.erl compile error with erlang OTP 27

### ISSUE THREAD

**Issue by Terbium-135** [rabbitmq/rabbitmq-server#11328]
### Describe the bug

After switching to elixir 1.17-rc.0 and erlang OTP 27 I am unable to compile rabbit_common:

```
===> Compiling rabbit_common
===> Compiling src/rabbit_heartbeat.erl failed
rabbit_heartbeat.erl:22:39: syntax error before: 'maybe'

rabbit_heartbeat.erl:20:2: type heartbeaters() undefined
rabbit_heartbeat.erl:32:13: type heartbeaters() undefined
rabbit_heartbeat.erl:38:13: type heartbeaters() undefined
rabbit_heartbeat.erl:49:21: type heartbeaters() undefined
rabbit_heartbeat.erl:50:22: type heartbeaters() undefined
```

Switching back to elixir 1.16.2 and OTP 26.2 compiles flawlessly.

### Reproduction steps

Switch to elixir 1.17-rc.0 and erlang OTP 27 and try to compile rabbit_common

### Expected behavior

Expecting a clean compile

**Comment by michaelklishin** [comment]
Erlang 27 is [not supported by RabbitMQ](https://www.rabbitmq.com/blog/2024/05/23/erlang27-support) at this time. [This branch](https://github.com/rabbitmq/rabbitmq-server/tree/otp27-support) reflects the current state of Erlang 27 support, plus this specific compilation error is addressed by https://github.com/rabbitmq/rabbitmq-server/pull/11251.

**Comment by Terbium-135** [comment]
Thank you very much!
Appreciate the links
