### ISSUE TITLE
Log vhost and user id with connection info

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-server#1140]
When connection is established, we see the following in the logs:

accepting AMQP connection <0.2155.1393> (10.102.192.2:45914 -> 10.102.196.133:5671)
Connection <0.1115.1392> (10.102.208.5:8035 -> 10.102.196.133:5671) has a client-provided name: MyApp

Since the source IP is almost always a load balancer or HAProxy, would it be possible to also log the vhost and user id somewhere? We have situations where clients are feeding incorrect names in connection_name, thus spoofing other apps as far as the logs are concerned, which complicates troubleshooting. Thanks!

**Comment by michaelklishin** [comment]
Virtual and username aren't available at the time when a connection is accepted. They are provided by clients at a later step.

We will discuss if we should log more as some users want exactly the opposite: less logging, which will be easier to configure in 3.7.0.

#589 addresses the load balancer IP concern.

**Comment by uvzubovs** [comment]
Can vhost and user id be logged when connection name is logged?

**Comment by michaelklishin** [comment]
Not all connections have client-provided names. I will add a new log entry and let the rest of the team decide.

**Comment by uvzubovs** [comment]
It would help if everything is logged together, if possible, please. Otherwise, we have to do quite a bit of acrobatics to collate entries on source IP/port.

**Comment by gerhard** [comment]
@uvzubovs would it be enough if we logged the vhost?

**Comment by uvzubovs** [comment]
I'll take what I can get  and as much as you can give ;)

**Comment by michaelklishin** [comment]
I personally think that if we log vhost, TCP socket details and client-provided connection name (if any) it would be really odd to not log usernames.

**Comment by carlhoerberg** [comment]
@uvzubovs with the new PROXY protocol support coming up you will get the real source IP, not the proxy's
