### ISSUE TITLE
Clients keep losing connection with RabbitMQ Server 3.6.7

### ISSUE THREAD

**Issue by BlaM** [rabbitmq/rabbitmq-server#1148]
I just upgraded the Debian-Package of RabbitMQ from 3.6.6 to 3.6.7 and immediately started to have problems with both an PHP client (using https://github.com/php-amqplib/php-amqplib (v2.4) and a node.js client (using https://github.com/squaremo/amqp.node (v0.4.1)). 

Both kept losing their connection to the server in short intervals. Since the problem appeared in two clients at the same time I assume the problem lies in the new version of RabbitMQ.

I have now downgraded to 3.6.6 again and it's back to working. However that also means that I don't have the option to search for the reason of the problem anymore. I just thought I'd let you know.

node error message:

    [Error: Connection closed: 541 (INTERNAL-ERROR) with message "INTERNAL_ERROR"]

PHP error message:

    'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Broken pipe or closed connection'

**Comment by kjnilsson** [comment]
Thank you, did you happen to inspect the rabbitmq server logs during the time you were running 3.6.7? The server logs are typically what we'd need to be able to investigate this.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
See server logs and please post them to rabbitmq-users, plus relevant sections of your code. I tried [PHP tutorial 1](https://github.com/rabbitmq/rabbitmq-tutorials/tree/master/php) against 3.6.7 and it works just fine, as do at least 4 other clients we test against (Java, .NET, Ruby, Go).

**Comment by michaelklishin** [comment]
I can't reproduce with Node.js tutorials either:

```
# consumer
node ./src/receive.js
 [*] Waiting for messages in hello. To exit press CTRL+C
 [x] Received Hello World!
```

```
# publisher
node ./src/send.js
 [x] Sent Hello World!
```

**Comment by michaelklishin** [comment]
This [rabbitmq-users thread](https://groups.google.com/forum/#!searchin/rabbitmq-users/Rabbitmq$203.6.7$20connection$20closed%7Csort:relevance/rabbitmq-users/XfQgta5v6Z0/1V6y2h8GFAAJ) is likely what you're hitting (this is a guess).

**Comment by michaelklishin** [comment]
This [rabbitmq-users thread](https://groups.google.com/forum/#!searchin/rabbitmq-users/Rabbitmq$203.6.7$20connection$20closed%7Csort:relevance/rabbitmq-users/XfQgta5v6Z0/1V6y2h8GFAAJ) is likely what you're hitting (this is a guess).

**Comment by BlaM** [comment]
That thread looks very similar. Thank you. Might be able to find my solution there.

**Comment by michaelklishin** [comment]
@BlaM we are investigating what may be missing so for now the solution is to upgrade Erlang to something newer than R16B03 (which is the only version affected as far as we can tell), e.g. 19.x.

**Comment by BlaM** [comment]
I think the affected server is on Erlang 17.3 (according to the installed Debian package).

**Comment by michaelklishin** [comment]
R16B03 and 17.x are affected.

**Comment by michaelklishin** [comment]
They won't be in 3.6.8 which should be out very soon.

**Comment by michaelklishin** [comment]
[3.6.8 is out](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_8) and fixes Erlang R16B03 and 17.x compatibility. We recommend all users to move to at least 18.0, and ideally 19.x.

**Comment by robvelor** [comment]
I'm seeing this issue on 3.6.9 with erlang 19 on docker image of 3.6.9.

**Comment by michaelklishin** [comment]
@robvelor I'm sorry but we cannot possibly help you with that much information provided. Please make sure you are familiar with [the Heartbeats guide](http://www.rabbitmq.com/heartbeats.html) and post server logs and a snippet of your code to rabbitmq-users, RabbitMQ's public mailing list.
