### ISSUE TITLE
HTTP API returning different status code on Queue/Exchange creation

### ISSUE THREAD

**Issue by marlier** [rabbitmq/rabbitmq-server#1150]
Prior to 3.6.7, the RabbitMQ HTTP API returned a 204 when a Queue or Exchange was successfully created.  Those endpoints now return a 201 in that circumstance.  Though the prior behavior technically was not correct, it has been encoded in to software that uses the HTTP API, such as the [Ansible RabbitMQ modules](https://github.com/ansible/ansible-modules-extras/blob/devel/messaging/rabbitmq_exchange.py#L206).

Though I generally support the change to return a 201, it would be nice to mention this in the release notes, and possibly write a test or two against it to avoid unexpected changes in the future.

**Comment by michaelklishin** [comment]
This is [mentioned in release notes](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_7) and is due to our embedded HTTP server change (which won't be reverted).

**Comment by michaelklishin** [comment]
Hm, apparently it was mentioned in the mailing list announcement but not release notes. I will copy it over, thanks.

**Comment by michaelklishin** [comment]
Done. Note that we've been mentioning it in something like 6-7 preview release announcements. It's unfortunate that those don't get much attention. But now it's in the release notes and should be visible.

**Comment by essen** [comment]
Worth nothing:

Checking on a specific status code is not a good practice, you only really should care about receiving a 2xx. The only reason you would look for a special status code is if you need to handle it differently than others of the same class of status codes (401 for example). If you do a request and get a 2xx and don't need to differentiate between the different 2xx codes, then don't match specifically against it.

**Comment by michaelklishin** [comment]
I agree with @essen but honestly, our own test suites checked for specific status codes right before we made the switch to Cowboy ;)

**Comment by essen** [comment]
Yes... :-(

**Comment by marlier** [comment]
Appreciate the quick response, guys!  I PR'd ansible (the one specific example that I know of): https://github.com/ansible/ansible/pull/22715

**Comment by michaelklishin** [comment]
@marlier oh, fantastic, thank you very much!
