### ISSUE TITLE
rabbitmq-server fails to start when log directory does not exist

### ISSUE THREAD

**Issue by powersj** [rabbitmq/rabbitmq-server#1151]
### Issue
If the /tmp directory gets wiped out or removed after each for boot for example rabbitmq-server will fail to start. The message will be something like the following:
```
{"init terminating in do_boot",{error,{cannot_log_to_file,"/var/log/rabbitmq/rabbit@zesty.log",{error,{cannot_create_parent_dirs,"/var/log/rabbitmq/rabbit@zesty.log",eacces}}}}}
```

### Expected Behavior
If the RABBITMQ_LOG_BASE directory on start up does not exist, it should be recreated. 

### Observed Behavior
Start up fails.

Here is journalct output: https://paste.ubuntu.com/24190277/
Here is an strace: https://paste.ubuntu.com/24190280/

### Steps to Reproduce
1. Install Ubuntu 17.04 via ISO or using a LXD env.
2. wget https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_6_7/rabbitmq-server_3.6.7-1_all.deb
3. apt-get update
4. dpkg -i rabbitmq-server_3.6.7-1_all.deb
5. apt-get -f install
6. systemctl status rabbitmq-server.service  # Note that rabbitmq is running successfully
7. systemctl stop rabbitmq-server.service
8. rm -rf /var/log/rabbitmq
9. systemctl start rabbitmq-server.service  # Start will fail

**Comment by michaelklishin** [comment]
The message says `cannot_create_parent_dirs`: it does try to create the log directory. Debian and RPM packages prepare the directories they will use. Sorry but I'm not sure what else RabbitMQ can realistically do.

**Comment by powersj** [comment]
To make sure I am following you, by parent directory is it trying to create "/var/log/rabbitmq"? Are there more clues for me to gather to understand why that would that fail?

**Comment by michaelklishin** [comment]
It's not technically correct to link to master but still: here's an [exact place where RabbitMQ will try to pre-create its log directory](https://github.com/rabbitmq/rabbitmq-server/blob/fdf783f9accd0b7c914b17907c0d7528750fb961/src/rabbit_lager.erl#L146).

**Comment by michaelklishin** [comment]
@powersj what it tries to do is basically `mkdir -p`. If `/var/log/` permissions don't allow RabbitMQ's effective user to create `/var/log/rabbitmq`, it will fail.

This is another thing that package scripts take care of that but if you install via binary distribution you can either let it use a local (`./var/log/…`) directory or override log directory or pre-create it with the suitable permissions.

**Comment by powersj** [comment]
ok I think what I had missing is understanding RabbitMQ's user permissions, as I was running as root.

Completely understand about the package scripts. The scenario in this case was using tmpfs for /var/log; I guess the answer is, "don't do that". Thanks!

**Comment by michaelklishin** [comment]
I wouldn't necessarily say that you shouldn't do that because I know nothing about your goals and how RabbitMQ was provisioned. I think storing logs on a durable volume makes more sense (if log rotation is set up).

It's been a while since I last used tmpfs or ramfs. A few years ago storing the entire node data directory for RabbitMQ, MySQL, PostgreSQL worked OK.

**Comment by michaelklishin** [comment]
I see a couple of curious things in your strace output (major props for posting it):

 * I don't see any calls that use `/var/log/*`
 * I do see calls that involve SELinux, which is known to wreck havoc and confusion by restricting more than the operator expects by default ;)

**Comment by michaelklishin** [comment]
RabbitMQ user permissions are pretty boring: packages set up a non-privileged user, `rabbitmq`, and pre-create some directories for the node to use that `rabbitmq` has permissions to. That's basically it.

**Comment by powersj** [comment]
Awesome, thanks for taking the time to help clear that up in my head :)

**Comment by michaelklishin** [comment]
@powersj my pleasure. Feel free to post questions to the rabbitmq-users Google group next time you have them :)
