### ISSUE TITLE
-setcookie in RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS not respected when clustering in v3.6

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-server#1155]
When configuring a v3.6.8 cluster via `{cluster_nodes, {['rabbit@rmq0','rabbit@rmq1'], disc}}`, `-setcookie` in `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` is not respected.

An Erlang cookie is still created in `$HOME/.erlang.cookie` and it takes precedence over `-setcookie` passed as a flag to `erl`. I would expect 2 things to happen:

1. When `-setcookie` is provided as an `erl` flag, `$HOME/.erlang.cookie` will not be created. I haven't checked if this is OTP behaviour or RabbitMQ-specific.
1. When `-setcookie` is provided as an `erl` flag, it takes precedence over `$HOME/.erlang.cookie` and will be used when clustering RabbitMQ nodes.

Thoughts?

**Comment by michaelklishin** [comment]
Please make it `RABBITMQ_ERLANG_COOKIE`. We don't want to invent a new term.

**Comment by michaelklishin** [comment]
It should not be RabbitMQ-specific, we probably just pass BEAM CLI arguments in such a way that it's not parsed correctly (or passed on at all)

**Comment by hairyhum** [comment]
Cannot reproduce. Need more data on prerequisites

Downloaded 3.6.8 generic unix.
Configured `/ets/hosts` to see `rmq0` and `rmq1` hosts.
Set environment variables:
```
export RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS='-setcookie foo'
export RABBITMQ_NODENAME=rabbit@rmq0 #rabbit@rmq1 on other node
```

Run rabbitmq server in generic unix dir:
```
export RABBITMQ_HOME=`pwd`
sbin/rabbitmq-server
```

Checked cluster status:
```
RABBITMQ_CTL_ERL_ARGS='-setcookie foo' sbin/rabbitmqctl -n rabbit@rmq0 cluster_status
# Cluster status of node rabbit@rmq0 ...
# [{nodes,[{disc,[rabbit@rmq0,rabbit@rmq1]}]},
#  {running_nodes,[rabbit@rmq1,rabbit@rmq0]},
#  {cluster_name,<<"rabbit@MacBookdfedotov">>},
#  {partitions,[]},
#  {alarms,[{rabbit@rmq1,[]},{rabbit@rmq0,[]}]}]
```

Checked cookie:
```
RABBITMQ_CTL_ERL_ARGS='-setcookie foo' sbin/rabbitmqctl -n rabbit@rmq0 eval 'erlang:get_cookie().' 
# foo

RABBITMQ_CTL_ERL_ARGS='-setcookie foo' sbin/rabbitmqctl -n rabbit@rmq1 eval 'erlang:get_cookie().' 
# foo
```

**Comment by gerhard** [comment]
Could not reproduce on a clean 3 node 3.6.8, it must have been some left-behind state that was causing this issue.
