### ISSUE TITLE
4.x: consider removing `rabbitmq_tracing` from the distribution

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#11553]
[Wireshark](https://www.rabbitmq.com/amqp-wireshark) is superior in nearly every way and `rabbitmq_tracing` was never meant to be used in production.

The only case where this plugin is superior to Wireshark is direct Erlang client publishing, that is, Shovels or Federation links that connect to `localhost`. This is not relevant to 99.9% of applications that are not in Erlang and do not run on RabbitMQ nodes.

**Comment by razvanphp** [comment]
I read the blog post and this looks very promising.

One question tho, from our use-case: can we debug the `mqtt` and `web-mqtt` traffic in the same way?

Thank you!
R

**Comment by luos** [comment]
In many cases it's easier to use tracing to see what actually reaches RabbitMQ and the queues, what is the outcome of routing the message. Also, many people use it as an audit log of messages (which we do not recommend, but still). 

Not sure what's the reasoning for removing it, but I think it is useful for many users.
