### ISSUE TITLE
Dynamic shovel(s) cannot be deleted

### ISSUE THREAD

**Issue by ChesterMino** [rabbitmq/rabbitmq-server#11569]
### Describe the bug

Dear Team,

After upgrading from 3.8.2 to 3.13.2 we started to experience issues, when some of the dynamic shovels cannot be deleted. The issue was reproduced several times during last few weeks.

### Reproduction steps

1. The shovel is not present in the 'Shovel status' but is present in the 'Shovel management'. 
2. When trying to remove the shovel using UI, error msg pops up saying the shovel could not be removed. Following line can be found in the log file: `Shovel with the name ‘my-shovel’ was not found on virtual host '/'`
3. When trying to remove the shovel using cmd `rabbitmqctl clear_parameter shovel “my-shovel”` , following msg is returned: `Clearing runtime parameter “my-shovel" for component "shovel" on vhost "/" ... Error:{:noproc, {:gen_server, :call, [:rabbit_shovel_dyn_worker_sup_sup, :which_children, :infinity]}}`
4. To fix the issue we need to disable/enable shovel plugin(s) on the node , where the shovel is 'defined'.

### Expected behavior

Keeping consistency of defined shovel(s)

### Additional context

We are running 5 nodes cluster of 3.13.2 (binaries) with erlang 26.2.5

Thanks!

Dominik

**Comment by michaelklishin** [comment]
Duplicate of #11324 (judging from the little information we have), although https://github.com/rabbitmq/rabbitmq-server/pull/11318 (which stems from Erlang 26's stricter TLS setting validation) can also be relevant: Shovels may fail to start because of that setting, which simply triggers #11324 in environments where it previously was never present.

**Comment by ChesterMino** [comment]
Hei, sry for opening in wrong topic. Thx for references.
