### ISSUE TITLE
通过api接口获取的信息和web管理台的信息不一样

### ISSUE THREAD

**Issue by 893271511** [rabbitmq/rabbitmq-server#1157]
通过api接口获取一个channel的state为flow，但是在rabbitmq web管理台看到此channel的state为idel，请问这是为什么？

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
Channel state can (and often does) change multiple times a second. `rabbitmqctl list_channels` queries channels on the spot ("in real time") while management UI uses statistics that are emitted every N (5 by default) seconds and reports channel state as in flow if it's been in flow in the last several seconds (IIRC). A really busy channel may seem like it's almost always in the flow control state — even that isn't necessarily a reason to be concerned.

**Comment by 893271511** [comment]
{
    "global_prefetch_count": 0,
    "messages_unconfirmed": 0,
    "node": "rabbit@test",
    "name": "10.32.64.120:50303 -> 10.32.55.40:5672 (6)",
    "confirm": false,
    "transactional": true,
    "state": "flow",
    "consumer_count": 1,
    "idle_since": "2017-03-23 14:59:41",
    "vhost": "/",
    "acks_uncommitted": 0,
    "prefetch_count": 1,
    "message_stats": {
        "publish_details": {
            "rate": 0.0
        },
        "ack": 3,
        "deliver_get": 3,
        "deliver": 3,
        "publish": 511,
        "ack_details": {
            "rate": 0.0
        },
        "deliver_details": {
            "rate": 0.0
        },
        "deliver_get_details": {
            "rate": 0.0
        }
    },
    "connection_details": {
        "peer_host": "10.32.64.120",
        "name": "10.32.64.120:50303 -> 10.32.55.40:5672",
        "peer_port": 50303
    },
    "messages_uncommitted": 0,
    "number": 6,
    "messages_unacknowledged": 0,
    "user": "admin"
}

这是用/api/channels取出的信息，这个channel当前没有生产消息 "publish_details": {"rate": 0.0，但state为flow？

**Comment by michaelklishin** [comment]
@893271511 please use English as automatic translation tools can be really confusing. This is not a support forum. [Credit flow](https://www.rabbitmq.com/blog/2015/10/06/new-credit-flow-settings-on-rabbitmq-3-5-5/) is applied to all operations, not just publishes, so publishing rate can be 0 but a channel is still throttled by another process it uses.
