### ISSUE TITLE
prelaunch fails when epmd only binds to IPv6

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#116]
To reproduce:

 * Ensure you have Erlang 17.x (at least R16B01)
 * export ERL_EPMD_ADDRESS="0:0:0:0:0:0:0:1" RABBITMQ_NODE_IP_ADDRESS="0:0:0:0:0:0:0:1"
 * Try starting rabbitmq-server

You'll get `{'EXIT',nodistribution}` from `net_kernel`.

**Comment by michaelklishin** [comment]
It seems to be that `epmd` fails to start because it fails to parse abbreviated IPv6 addresses. Will investigate more but at least for now, this may be an issue we can't fix.

**Comment by Gsantomaggio** [comment]
In this [rabbitmq-users gruop thread](https://groups.google.com/forum/#!topic/rabbitmq-users/mbsT8PSJTHQ), you can find more info about EPMD and IPV6
