### ISSUE TITLE
Three node cluster with `cluster_partition_handling:pause_minority` doesn't go down as intended in case of partial partition

### ISSUE THREAD

**Issue by szank** [rabbitmq/rabbitmq-server#1161]
Hi, 
We have noticed strange behaviour of our RabbitMQ cluster when we had some connectivity issues in our environment. I have managed to distill it to a test case. 
We have three RabbitMQ nodes rabbit-02, rabbit-03 and rabbit-05. 
All three are working in pause_minority mode with net_tick_time set to 10 seconds 

At the start of the test, each node have an open management connection to the two other nodes. 
In real life scenario, a connection between node rabbit-02 and rabbit-03 have been dropped, and could't be established for few seconds. At the same time connections rabbit-02 <-> rabbit-05 & rabbit-03 <-> rabbit-05 were OK. 

Now, if the connection have been reestablished in below net_tick_time, everything was OK. If the connection was down for more than net_tick_time, things went south. To reliably reproduce the issue, I have started with 3 node cluster, and added a firewall rule to block connections between rabbit-02 and rabbit-03. 

Here are the logs : 
rabbitmq-02
```
=INFO REPORT==== 28-Mar-2017::13:47:51 ===
rabbit on node 'rabbit@rabbitmq-03' down

=INFO REPORT==== 28-Mar-2017::13:47:51 ===
node 'rabbit@rabbitmq-03' down: econnaborted

=ERROR REPORT==== 28-Mar-2017::13:47:51 ===
Partial partition detected:
* We saw DOWN from rabbit@rabbitmq-03
* We can still see rabbit@rabbitmq-05 which can see rabbit@rabbitmq-03
* pause_minority mode enabled
We will therefore pause until the *entire* cluster recovers

=WARNING REPORT==== 28-Mar-2017::13:47:51 ===
Cluster minority/secondary status detected - awaiting recovery

=INFO REPORT==== 28-Mar-2017::13:47:51 ===
Stopping RabbitMQ

=INFO REPORT==== 28-Mar-2017::13:47:51 ===
stopped TCP Listener on 0.0.0.0:5672

=INFO REPORT==== 28-Mar-2017::13:47:51 ===
Stopped RabbitMQ application
```

rabbitmq-03
```
=INFO REPORT==== 28-Mar-2017::13:47:50 ===
rabbit on node 'rabbit@rabbitmq-02' down

=INFO REPORT==== 28-Mar-2017::13:47:51 ===
node 'rabbit@rabbitmq-02' down: connection_closed

=ERROR REPORT==== 28-Mar-2017::13:47:51 ===
Partial partition detected:
* We saw DOWN from rabbit@rabbitmq-02
* We can still see rabbit@rabbitmq-05 which can see rabbit@rabbitmq-02
* pause_minority mode enabled
We will therefore pause until the *entire* cluster recovers

=WARNING REPORT==== 28-Mar-2017::13:47:51 ===
Cluster minority/secondary status detected - awaiting recovery

=INFO REPORT==== 28-Mar-2017::13:47:51 ===
Stopping RabbitMQ

=INFO REPORT==== 28-Mar-2017::13:47:58 ===
stopped TCP Listener on 0.0.0.0:5672

=INFO REPORT==== 28-Mar-2017::13:48:03 ===
Stopped RabbitMQ application
```

rabbitmq-05
```
=WARNING REPORT==== 28-Mar-2017::13:47:51 ===
Received a 'DOWN' message from 'rabbit@rabbitmq-02' but still can communicate with it

=WARNING REPORT==== 28-Mar-2017::13:47:51 ===
Received a 'DOWN' message from 'rabbit@rabbitmq-03' but still can communicate with it

=INFO REPORT==== 28-Mar-2017::13:47:51 ===
rabbit on node 'rabbit@rabbitmq-02' down

=INFO REPORT==== 28-Mar-2017::13:47:51 ===
Keep rabbit@rabbitmq-02 listeners: the node is already back

=INFO REPORT==== 28-Mar-2017::13:47:51 ===
Mirrored queue 'DEADBEEF' in vhost '/': Slave <rabbit@rabbitmq-05.3.5326.0> saw deaths of mirrors <rabbit@rabbitmq-02.2.5273.0>

=INFO REPORT==== 28-Mar-2017::13:47:51 ===
Mirrored queue 'DEADBEEF' in vhost '/': Promoting slave <rabbit@rabbitmq-05.3.5326.0> to master

=INFO REPORT==== 28-Mar-2017::13:47:51 ===
Mirrored queue 'DEADBEEF' in vhost '/': Adding mirror on node 'rabbit@rabbitmq-03': <19288.27284.46>

=INFO REPORT==== 28-Mar-2017::15:48:03 ===
rabbit on node 'rabbit@rabbitmq-03' down

=INFO REPORT==== 28-Mar-2017::15:48:03 ===
Keep rabbit@rabbitmq-03 listeners: the node is already back

=INFO REPORT==== 28-Mar-2017::15:48:03 ===
Mirrored queue 'test-queue' in vhost '/': Master <rabbit@rabbitmq-05.3.5326.0> saw deaths of mirrors <rabbit@rabbitmq-03.1.27284.46>
```

rabbitmqctl cluster_status : 
rabbitmq-02
```
[root@rabbitmq-02 ~]#  rabbitmqctl cluster_status
Cluster status of node 'rabbit@rabbitmq-02' ...
[{nodes,[{disc,[rabbit@rabbitmq-05,'rabbit@rabbitmq-02','rabbit@rabbitmq-03']}]},
{alarms,[{rabbit@rabbitmq-05,[]}]}]
```

rabbitmq-03
```
[root@rabbitmq-03 ~]# rabbitmqctl cluster_status
Cluster status of node 'rabbit@rabbitmq-03' ...
[{nodes,[{disc,[rabbit@rabbitmq-05,'rabbit@rabbitmq-02','rabbit@rabbitmq-03']}]},
{alarms,[{rabbit@rabbitmq-05,[]}]}]
```

rabbitmq-05
```
[root@rabbitmq-05 ~]# rabbitmqctl cluster_status
Cluster status of node rabbit@rabbitmq-05 ...
[{nodes,[{disc,[rabbit@rabbitmq-05,'rabbit@rabbitmq-02','rabbit@rabbitmq-03']}]},
{running_nodes,[rabbit@rabbitmq-05]},
{cluster_name,<<"rabbit@rabbitmq-02">>},
{partitions,[]},
{alarms,[{rabbit@rabbitmq-05,[]}]}]
```

As you can see, rabbitmq-02 and rabbitmq-03 notice the partial partition and go down, as intended by the pause_minority policy. They still listening on the management interface though, and rabbitmq-05 is still connected to the other two on the management interface. 
This causes rabbitmq-05 to stay up. 

Now, if I just stop/partition out rabbitmq-02 , and then stop/partition out rabbitmq-03, then rabbitmq-05 goes down, because it notices that two other nodes are down. 
In my case, two nodes are down, but the last one stays up. 

The netstat result from rabbitmq-05 
```
[root@rabbitmq-05 ~]# netstat -an4 | grep 25672
tcp4       0      0 rabbitmq-05.25672     rabbitmq-02.63900     ESTABLISHED
tcp4       0      0 rabbitmq-05.25672     rabbitmq-03.18855  ESTABLISHED
tcp4       0      0 *.25672                *.*                    LISTEN
```
The node have connections established to the other two nodes. The healthcheck in the pause_minority mode doesn't verify if the node on the other side is actually working, or awaiting recovery, so rabbitmq-05 thinks that everything is OK with the the other nodes. 

Also, 
```
[root@rabbitmq-05 ~]# rabbitmqctl environment
Application environment of node rabbit@rabbitmq-05 ...
[{amqp_client,[{prefer_ipv6,false},{ssl_options,[]}]},
 {asn1,[]},
 {compiler,[]},
 {crypto,[]},
 {inets,[]},
 {kernel,
     [{error_logger,tty},
      {inet_default_connect_options,[{nodelay,true}]},
      {inet_dist_listen_max,25672},
      {inet_dist_listen_min,25672},
      {net_ticktime,10}]},
 {mnesia,[{dir,"/ssdroot/rabbitmq/rabbit@rabbitmq-05"}]},
 {mochiweb,[]},
 {os_mon,
     [{start_cpu_sup,false},
      {start_disksup,false},
      {start_memsup,false},
      {start_os_sup,false}]},
 {public_key,[]},
 {rabbit,
     [{auth_backends,[rabbit_auth_backend_internal]},
      {auth_mechanisms,['PLAIN','AMQPLAIN']},
      {backing_queue_module,rabbit_priority_queue},
      {channel_max,0},
      {channel_operation_timeout,15000},
      {cluster_keepalive_interval,10000},
      {cluster_nodes,{[],disc}},
      {cluster_partition_handling,pause_minority},
      {collect_statistics,fine},
      {collect_statistics_interval,5000},
      {config_entry_decoder,
          [{cipher,aes_cbc256},
           {hash,sha512},
           {iterations,1000},
           {passphrase,undefined}]},
      {credit_flow_default_credit,{200,100}},
      {default_permissions,[<<".*">>,<<".*">>,<<".*">>]},
      {default_user,<<"guest">>},
      {default_user_tags,[administrator]},
      {default_vhost,<<"/">>},
      {delegate_count,16},
      {disk_free_limit,50000000},
      {enabled_plugins_file,"/usr/local/etc/rabbitmq/enabled_plugins"},
      {error_logger,{file,"/var/log/rabbitmq/rabbit@rabbitmq-05.log"}},
      {fhc_read_buffering,false},
      {fhc_write_buffering,true},
      {frame_max,131072},
      {halt_on_upgrade_failure,true},
      {handshake_timeout,10000},
      {heartbeat,60},
      {hipe_compile,true},
      {hipe_modules,
          [rabbit_reader,rabbit_channel,gen_server2,rabbit_exchange,
           rabbit_command_assembler,rabbit_framing_amqp_0_9_1,rabbit_basic,
           rabbit_event,lists,queue,priority_queue,rabbit_router,rabbit_trace,
           rabbit_misc,rabbit_binary_parser,rabbit_exchange_type_direct,
           rabbit_guid,rabbit_net,rabbit_amqqueue_process,
           rabbit_variable_queue,rabbit_binary_generator,rabbit_writer,
           delegate,gb_sets,lqueue,sets,orddict,rabbit_amqqueue,
           rabbit_limiter,gb_trees,rabbit_queue_index,
           rabbit_exchange_decorator,gen,dict,ordsets,file_handle_cache,
           rabbit_msg_store,array,rabbit_msg_store_ets_index,rabbit_msg_file,
           rabbit_exchange_type_fanout,rabbit_exchange_type_topic,mnesia,
           mnesia_lib,rpc,mnesia_tm,qlc,sofs,proplists,credit_flow,pmon,
           ssl_connection,tls_connection,ssl_record,tls_record,gen_fsm,ssl]},
      {lazy_queue_explicit_gc_run_operation_threshold,250},
      {log_levels,[{connection,info}]},
      {loopback_users,[<<"guest">>]},
      {memory_monitor_interval,2500},
      {mirroring_flow_control,true},
      {mirroring_sync_batch_size,4096},
      {mnesia_table_loading_timeout,30000},
      {msg_store_credit_disc_bound,{2000,500}},
      {msg_store_file_size_limit,16777216},
      {msg_store_index_module,rabbit_msg_store_ets_index},
      {msg_store_io_batch_size,2048},
      {num_ssl_acceptors,1},
      {num_tcp_acceptors,10},
      {password_hashing_module,rabbit_password_hashing_sha256},
      {plugins_dir,"/usr/local/lib/erlang/lib/rabbitmq_server-3.6.6/plugins"},
      {plugins_expand_dir,"/ssdroot/rabbitmq/rabbit@rabbitmq-05-plugins-expand"},
      {queue_index_embed_msgs_below,4096},
      {queue_index_max_journal_entries,32768},
      {reverse_dns_lookups,false},
      {sasl_error_logger,{file,"/var/log/rabbitmq/rabbit@rabbitmq-05-sasl.log"}},
      {server_properties,[]},
      {ssl_allow_poodle_attack,false},
      {ssl_apps,[asn1,crypto,public_key,ssl]},
      {ssl_cert_login_from,distinguished_name},
      {ssl_handshake_timeout,5000},
      {ssl_listeners,[]},
      {ssl_options,[]},
      {tcp_listen_options,
          [{backlog,128},
           {nodelay,true},
           {linger,{true,0}},
           {exit_on_close,false}]},
      {tcp_listeners,[5672]},
      {trace_vhosts,[]},
      {vm_memory_high_watermark,0.4},
      {vm_memory_high_watermark_paging_ratio,0.5}]},
 {rabbit_common,[]},
 {rabbitmq_management,
     [{cors_allow_origins,[]},
      {cors_max_age,1800},
      {http_log_dir,none},
      {listener,[{port,15672}]},
      {load_definitions,none},
      {process_stats_gc_timeout,300000},
      {rates_mode,basic},
      {sample_retention_policies,
          [{global,[{605,5},{3660,60},{29400,600},{86400,1800}]},
           {basic,[{605,5},{3600,60}]},
           {detailed,[{10,5}]}]},
      {stats_event_max_backlog,250}]},
 {rabbitmq_management_agent,[]},
 {rabbitmq_web_dispatch,[]},
 {ranch,[]},
 {sasl,[{errlog_type,error},{sasl_error_logger,false}]},
 {ssl,[]},
 {stdlib,[]},
 {syntax_tools,[]},
 {webmachine,[{error_handler,rabbit_webmachine_error_handler}]},
 {xmerl,[]}]
```

We would prefer to make the whole cluster go down. We would be able to step in, resolve any problems and then start the nodes again. 
It is more important for us to not loose any messages, then to have the cluster up. That's why we are using pause_minority mode. 

I haven't verified yet what happens with the persistent messages stored on the nodes that went down, when the cluster is restored. 
We have persistent queues with HA (mode set to {exactly, 2}). We would expect them to be there when we bring the nodes up. 
Will follow up on this issue when I verify the cluster behaviour.

**Comment by michaelklishin** [comment]
`pause_minority` isn't supposed to shut everything down and FWIW it's not a commonly requested behaviour.

What RabbitMQ version is used? what specifically do you mean by "healthcheck" in ` The healthcheck in the pause_minority mode doesn't verify if the node on the other side is actually working`? Node detect for peer availability using a [heartbeat-like mechanism](http://www.rabbitmq.com/nettick.html) but `pause_minority` recovery assumes that all peer nodes are reachable (using a similar yet different mechanism since net ticks is a runtime feature as far as RabbitMQ is concerned).

**Comment by michaelklishin** [comment]
> They still listening on the management interface though, and rabbitmq-05 is still connected to the other two on the management interface.

Sorry but you are getting ahead of yourself with these claims. Management UI uses periodically emitted stats, so it is often (if not always) a little behind the actual state of events. Those stats are NEVER used to make decisions, only for displaying them in the UI over HTTP API.
So node 5 cannot possibly not shut down because of the management UI.

The reason why it does not shut down is simple: `pause_minority` sees that after 2 and 3 did shut down there was a majority of 1 node left and node 5 was in it. Therefore it *does not* have to shut down by definition. I also don't think that many users would want it to shut down.

If you are happy with manually resolving such scenarios, use the `ignore` strategy and have your monitoring system stop all nodes in case any partitions are reported. Also take a look at [Unsynchronised Mirrors](http://www.rabbitmq.com/ha.html) in the docs, it describes a scenario in which you can decide to keep the data and sacrifice availability or do the opposite.

**Comment by michaelklishin** [comment]
Another incorrect assumption: it's not on node 5 to determine if its peers are available or awaiting anything. They might have gone for good, for example. It's on nodes 2 and 3 to detect that all previously known cluster peers are reachable (again, not using `net_tick` but a similar an fairly basic connectivity check known as `net_adm:ping/1`) and then resume.

I don't see anything in the logs that suggests that `pause_minority` doesn't work as expected. Perhaps one of my fellow team members has more to say before I ask to move this to the mailing list is an open ended discussion.

**Comment by szank** [comment]
Hi, 
1. We are using 3.6.6 on FreeBSD 11. The maintained have not yet pushed out the 3.6.8
2. I mixed up management interface and clustering interface. Sorry about that. My rabbitmq-05 node have clustering connection open to the other two nodes. 

3. In the case I have described, a connectivity issue between two nodes, have brought both of them down, leaving single point of failure for the 3 node cluster. 

We are more worried about the last node failing, and us loosing some messages, than by having a downtime. Loosing messages is much more costly for us. 

MongoDB for example handles it much better. I have filed this bug because I was expecting MongoDB-like behaviour with Rabbitmq, where problems on one node, doesn't create a single point of failure for the cluster. 

I am fine with moving it to the mailing list.

**Comment by michaelklishin** [comment]
@szank so you want all nodes to shut down whenever there's a single partial partition instead of "introducing a SPoF" by having a single operational node?
Sure, there are systems where losing the majority of nodes is considered unrecoverable but I assure you not everyone prefers that kind of behaviour and it's possibly the biggest issue we are currently contemplating in a future RabbitMQ version which may mirroring to Raft (which is what modern MongoDB versions use for operation log replication). Let me just say that not everyone is happy with this kind of behaviour and it is particularly problematic with partial partitions which RabbitMQ currently promotes to full partitions.

There is `pause_if_all_down` and `autoheal` strategies but they aren't any closer to a cluster-wide shutdown than `pause_minority`.

**Comment by NicholasMarty** [comment]
@michaelklishin I have another similiar issues where the partition handling isn't quite working as I'd expect it to work based on the description. The setup is kinda identical to the one mentioned by szank (3 nodes, each configured with `pause_minority`). Is this discussion continued somewhere (and if so: where can I find it?) or should I add my problem either in this issue, a new issue or somewhere else?

**Comment by michaelklishin** [comment]
@NicholasMarty post as much detail as you can to rabbitmq-users.
