### ISSUE TITLE
Improve rabbitmqctl stop PIDFILE failure detection.

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#1162]
When `rabbitmqctl stop PIDFILE` cannot contact a node, it returns a zero exit code even if PID is invalid or points to a different process.
PID can be used to detect if process is running and if it's a node process to return a better exit code.

**Comment by gerhard** [comment]
We have decided to introduce a new `rabbitmqctl shutdown` command as per #1166 . This allows us to get the improved shutdown behaviour without making any changes to the stop command which has been working well for many years now.
