### ISSUE TITLE
prelaunch assumes IPv4

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#117]
``` erlang
gen_tcp:listen(Port, [inet, {reuseaddr, true}])
```

won't work well if `epmd` and RabbitMQ is configured to use IPv6. We should support IPv6-only environments, too.

**Comment by yottatsa** [comment]
I found that https://github.com/yandex/inet64_tcp fixes clustering over IPv6 if you talking about it.

**Comment by michaelklishin** [comment]
Thanks. Not just clustering but also our own code. But it's good to know about that project.

**Comment by michaelklishin** [comment]
Fixed by #391, thank you, @dcorbacho.
