### ISSUE TITLE
Queue Master Location does not work using the ARGS

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-server#1172]
Using the queues `args` the master location does not work

using this code in a cluster with 3 nodes:
```java
Map<String, Object> args_master = new HashMap<String, Object>();
 args_master.put("x-queue-master-locator", "min-masters");
  for (int i = 0; i < 20; i++) {
      channel.queueDeclare("my_queue_" + i, true, false, false, args_master);
 }
```

it creates the queues always to the same node:

![screen shot 2017-04-03 at 18 22 02](https://cloud.githubusercontent.com/assets/386987/24619513/7b513dfa-189a-11e7-822b-fa1348aa1cca.png)

The problem seems to be [here](https://github.com/rabbitmq/rabbitmq-server/blob/stable/src/rabbit_queue_master_location_misc.erl#L65)

testing it:

```
  R =  proplists:lookup(<<"x-queue-master-locator">> , Args),
  io:format("~p~n",[R]),
```
the result is: `{<<"x-queue-master-locator">>,longstr,<<"min-masters">>}`  

so this code:
```
get_location_mod_by_args(#amqqueue{arguments=Args}) ->
    case proplists:lookup(<<"x-queue-master-locator">> , Args) of
        {<<"x-queue-master-locator">> , Strategy}  ->
 ``` 

should be:

```
case proplists:lookup(<<"x-queue-master-locator">> , Args) of
     {<<"x-queue-master-locator">> , longstr , Strategy}  ->
```

or
```
case proplists:lookup(<<"x-queue-master-locator">> , Args) of
  {<<"x-queue-master-locator">> , _ ,  Strategy}  ->
```

**Comment by michaelklishin** [comment]
@Gsantomaggio thanks for the detailed report!
