### ISSUE TITLE
Failed installation of rabbitmq-server 3.6.9-1

### ISSUE THREAD

**Issue by folt** [rabbitmq/rabbitmq-server#1174]
I installed a clean virtual machine on Ubuntu 16.04
Then did "update" and "upgrate" and "rebot"
Then executed the command 
`curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash`
Rabbitmq-server installed
command `rabbitmq-plugins list`
does not work

`Error: Failed to initialize erlang distribution: {{shutdown,
                                                   {failed_to_start_child,
                                                    auth,
                                                    {"Error when reading ./.erlang.cookie: eacces",
                                                     [{auth,init_cookie,0,
                                                       [{file,"auth.erl"},
                                                        {line,286}]},
                                                      {auth,init,1,
                                                       [{file,"auth.erl"},
                                                        {line,140}]},
                                                      {gen_server,init_it,6,
                                                       [{file,
                                                         "gen_server.erl"},
                                                        {line,328}]},
                                                      {proc_lib,
                                                       init_p_do_apply,3,
                                                       [{file,"proc_lib.erl"},
                                                        {line,240}]}]}}},
                                                  {child,undefined,
                                                   net_sup_dynamic,
                                                   {erl_distribution,
                                                    start_link,
                                                    [['rabbitmq-cli-60',
                                                      shortnames]]},
                                                   permanent,1000,supervisor,
                                                   [erl_distribution]}}.`

And generally rabbitmq-server does not work as a whole

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
`Error when reading ./.erlang.cookie: eacces` is the line you are looking for.
