### ISSUE TITLE
Priorities greater than 255

### ISSUE THREAD

**Issue by creactiviti** [rabbitmq/rabbitmq-server#1181]
We are using RabbitMQ to run long running jobs. Jobs are auto-assigned a priority based on their creation date (lower priority for earlier jobs). We do this so that earlier jobs get more priority in the queue over newer jobs and so that jobs complete in a linear fashion rather than running "all at once".

 Problem is that we often have batches of jobs much larger then 255. i.e. thousands of them at a time. Would that be possible to change the priority field from an unsigned byte to an unsigned integer to support a larger priority range?

**Comment by michaelklishin** [comment]
No. Using that many priorities is unnecessary. We never intended to see even 50 used.

**Comment by michaelklishin** [comment]
Now that I'm near a keyboard, here are some more details:

 * Changing a property type will both deviate from the spec (which we really don't like) and require all existing clients to be updated. It is currently possible to use clients from years ago with modern RabbitMQ versions with very few limitations.

 * For priority queues behind the scenes a new backing queue is created. Using 255 or even thousands of priorities means you will have resource usage similar to having close to that many queues.

Lastly, I'm yet to see a justification where 10 or maybe 20 — leave alone over 255 — priorities are really necessary.

**Comment by sp3c1** [comment]
Hey, well I kind of have one, yet but unrelated to that. A delayed queue of different expiration times on messages, where you would set priority to some ridiculous large int representing the UNIX timestamp so that short lived messages wont queue behind a long running one scheduled previously. Something like #1449
