### ISSUE TITLE
RabbitMQ should support running with "rabbit@IP" long-name

### ISSUE THREAD

**Issue by fiksn** [rabbitmq/rabbitmq-server#1182]
We are running RabbitMQ on Kubernetes. For clustering I tried [rabbitmq-autocluster](http://aweber.github.io/rabbitmq-autocluster/) plugin with Etcd2. It would be great if Erlang distribution directly used IP. The latest discussion about this topic I found is http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2009-December/005650.html

Based on that I came up with:

``
sed -i  '/RABBITMQ_USE_LONGNAME/iRABBITMQ_NODENAME="$RABBITMQ_NODENAME -name test$$@${RABBITMQ_NODENAME##*@}"'  /usr/lib/rabbitmq/lib/rabbitmq_server-${RABBITMQ_VERSION}/sbin/rabbitmqctl ; sed -i '/start_rabbitmq_server() {/iRABBITMQ_NAME_TYPE="-name"' /usr/lib/rabbitmq/lib/rabbitmq_server-${RABBITMQ_VERSION}/sbin/rabbitmq-server
``

then I also do export RABBITMQ_NODENAME="rabbit@$(hostname -i)" before starting "rabbitmq-server". (Note that I don't set RABBITMQ_USE_LONGNAME at all, with it it doesn't work)

With RabbitMQ 3.6.0 that trick worked fine, but not in later 3.6 versions. I can workaround by using rabbit_cli.beam from 3.6.0 with a later version. This hack is in use for development but I wouldn't really dare to run it in production.

I believe https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_cli.erl#L183 is not really fine. What I mean is: i'd expect when RABBITMQ_NODENAME and RABBITMQ_USE_LONGNAME are set, RabbitMQ should use those settings. If RABBITMQ_NODENAME is not set or not a FQDN it can still fall back to old logic. 

In my case I don't really want to use DNS for inter-cluster communication, but as far as I understand it also wouldn't work if I did (due to the ".no-domain" addendum).

Thanks for your help.

**Comment by michaelklishin** [comment]
CLI node names are intentionally made unique and `RABBITMQ_NODENAME` is not supposed to be used by CLI tools.

**Comment by michaelklishin** [comment]
According to https://github.com/aweber/rabbitmq-autocluster/issues/28#issuecomment-237293428, https://github.com/rabbitmq/rabbitmq-server/pull/892 makes it possible to use IP addresses in containerized environments. @binarin may recall what were the specific issues. 

However, `RABBITMQ_NODENAME` never was meant to be used for CLI tools and CLI tools intentionally use uniquely generated names, otherwise you cannot run more than one instance of the tool at once (there will be a node name conflict).

**Comment by fiksn** [comment]
Yep, rabbitmq-autocluster with k8s support works like a charm w/ 3.6.9 RabbitMQ.

What was irritating me was the ".no-domain", but it seems that is used only for CLI tools not by rabbitmq-server itself. Thanks for the links and sorry for opening the invalid ticket.

**Comment by bitnitdit** [comment]
Hi, @michaelklishin:

You've said,"CLI node names are intentionally made unique and RABBITMQ_NODENAME is not supposed to be used by CLI tools."
But in this link: [https://www.rabbitmq.com/clustering.html](https://www.rabbitmq.com/clustering.html), section "A Cluster on a Single Machine", it still uses RABBITMQ_NODENAME, 
```RABBITMQ_NODE_PORT=5672 RABBITMQ_NODENAME=rabbit rabbitmq-server -detached```
```RABBITMQ_NODE_PORT=5673 RABBITMQ_NODENAME=hare rabbitmq-server -detached```
and the steps this section provides do not work, that is, using those steps can not setup a rabbitmq cluster on a single machine. 

Is there any other method to setup a rabbitmq cluster on a single machine? Thanks!

**Comment by lukebakken** [comment]
@bitnitdit - I believe the "CLI tools" to which @michaelklishin refers are commands like `rabbitmqctl`, `rabbitmq-plugins` and _not_ the `rabbitmq-server` start script.

@fiksn if you would like to use `rabbit@IP` style node names, you can follow the [directions I posted here](https://groups.google.com/forum/#!msg/rabbitmq-users/zh-c-R2Pch0/QlNo5MGuBwAJ).

**Comment by michaelklishin** [comment]
[What I mean by CLI tools](http://www.rabbitmq.com/cli.html).

**Comment by bitnitdit** [comment]
@lukebakken, @michaelklishin , thank you all very much!
