### ISSUE TITLE
TLS listiners fail on v 3.6.8-1  and above, Using Erlang 19.1

### ISSUE THREAD

**Issue by abelgo** [rabbitmq/rabbitmq-server#1183]
My cluster has always been easy to update until version 3.6.8 came along.
rabbitmq-server_3.6.8-1_all.deb results in start up failure ubuntu 14

logs from testing server package install failed node restart

Apr 13 12:38:40 testnet systemd[1]: rabbitmq-server.service: Unit entered failed state.
Apr 13 12:38:40 testnet systemd[1]: rabbitmq-server.service: Failed with result 'exit-code'.
dpkg: error processing package rabbitmq-server (--install):

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

=INFO REPORT==== 13-Apr-2017::12:38:37 ===
Error description:
   {could_not_start,rabbit,
       {{case_clause,
            {error,
                {{shutdown,
                     {failed_to_start_child,
                         {ranch_listener_sup,
                             {acceptor,{0,0,0,0,0,0,0,0},5671}},
                         {shutdown,
                             {failed_to_start_child,ranch_acceptors_sup,
                                 badarg}}}},
                 {child,undefined,'rabbit_tcp_listener_sup_:::5671',
                     {tcp_listener_sup,start_link,
                         [{0,0,0,0,0,0,0,0},
                          5671,ranch_ssl,
                          [inet6,
                           {backlog,128},
                           {nodelay,true},
                           {linger,{true,0}},
                           {exit_on_close,false},
                           {versions,['tlsv1.2','tlsv1.1',tlsv1]},
                           {depth,4},
                           {server_renegotiate,true},
                           {cacertfile,"/etc/rabbitmq/cert/cacert.pem"},
                           {certfile,"/etc/rabbitmq/cert/cert.pem"},
                           {keyfile,"/etc/rabbitmq/cert/key.pem"}],
                          rabbit_connection_sup,[],
                          {rabbit_networking,tcp_listener_started,
                              ['amqp/ssl',
                               [{backlog,128},
                                {nodelay,true},
                                {linger,{true,0}},
                                {exit_on_close,false},
                                {versions,['tlsv1.2','tlsv1.1',tlsv1]},
                                {depth,4},
                                {server_renegotiate,true},
                                {cacertfile,"/etc/rabbitmq/cert/cacert.pem"},
                                {certfile,"/etc/rabbitmq/cert/cert.pem"},
                                {keyfile,"/etc/rabbitmq/cert/key.pem"}]]},
                          {rabbit_networking,tcp_listener_stopped,
                              ['amqp/ssl',
                               [{backlog,128},
                                {nodelay,true},
                                {linger,{true,0}},
                                {exit_on_close,false},
                                {versions,['tlsv1.2','tlsv1.1',tlsv1]},
                                {depth,4},
                                {server_renegotiate,true},
                                {cacertfile,"/etc/rabbitmq/cert/cacert.pem"},
                                {certfile,"/etc/rabbitmq/cert/cert.pem"},
                                {keyfile,"/etc/rabbitmq/cert/key.pem"}]]},
                          1,"SSL Listener"]},
                     transient,infinity,supervisor,
                     [tcp_listener_sup]}}}},
        [{rabbit_networking,start_listener0,5,
             [{file,"src/rabbit_networking.erl"},{line,294}]},
         {rabbit_networking,'-start_listener/5-lc$^0/1-0-',5,
             [{file,"src/rabbit_networking.erl"},{line,282}]},
         {rabbit_networking,start_listener,5,
             [{file,"src/rabbit_networking.erl"},{line,282}]},
         {rabbit_networking,'-boot_ssl/1-lc$^0/1-0-',3,
             [{file,"src/rabbit_networking.erl"},{line,142}]},
         {rabbit_networking,boot_ssl,1,
             [{file,"src/rabbit_networking.erl"},{line,142}]},
         {rabbit_networking,boot,0,
             [{file,"src/rabbit_networking.erl"},{line,128}]},
         {rabbit_boot_steps,'-run_step/2-lc$^1/1-1-',1,
             [{file,"src/rabbit_boot_steps.erl"},{line,49}]},
         {rabbit_boot_steps,run_step,2,
             [{file,"src/rabbit_boot_steps.erl"},{line,49}]}]}}

Log files (may contain more information):
   /var/log/rabbitmq/rabbit@testnet.log
   /var/log/rabbitmq/rabbit@testnet-sasl.log

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
There is no evidence that this is something in RabbitMQ, please post your config file to rabbitmq-users.

3.6.7 upgraded the TCP acceptor library we use which may include stricter validations of listener parameters. RabbitMQ itself certainly did not introduce any.

**Comment by michaelklishin** [comment]
…as well as server logs. Thanks.

**Comment by michaelklishin** [comment]
@essen do you see from the trace what option may trip up Ranch validation?

**Comment by essen** [comment]
The log doesn't provide me with enough information. The configuration and log files would certainly help.

**Comment by abelgo** [comment]
Sorry didn't want to publicly post the security info
The config appears noting out of the ordinary.
This is a self signed cert.

[

  {rabbit, [

     {reverse_dns_lookups, true},
     
     {ssl_listeners, [5671]},

     {ssl_options, [
                    {depth, 4},
                    {server_renegotiate, true},
                    {cacertfile,"/etc/rabbitmq/cert/cacert.pem"},
                    {certfile,"/etc/rabbitmq/cert/cert.pem"},
                    {keyfile,"/etc/rabbitmq/cert/key.pem"}

                   ]}
   ]}
   ,

{rabbitmq_management,
  [{listener, [{port, 15672},
               {ssl,  true},
               {ssl_opts, [
                    {cacertfile,"/etc/rabbitmq/cert/cacert.pem"},
                    {certfile,"/etc/rabbitmq/cert/cert.pem"},
                    {keyfile,"/etc/rabbitmq/cert/key.pem"}
              ]}   
              ]}
             ]} 
   , 

   {rabbitmq_web_stomp,
      [{ssl_config, [{port,       61617},
                     {backlog,    1024},
                     {password,   "testertester"},
                     {cacertfile,"/etc/rabbitmq/cert/cacert.pem"},
                     {certfile,"/etc/rabbitmq/cert/cert.pem"},
                     {keyfile,"/etc/rabbitmq/cert/key.pem"}

                     ]}
      ]}


].

**Comment by abelgo** [comment]
Ok guys I will do some more testing tonight then generate some better logs to try and figure out whats happening

**Comment by michaelklishin** [comment]
I tried it and the problematic option is `server_renegotiate`. It is not supported by Ranch (try searching the ninenines/ranch repository) and not listed in the [Erlang ssl app doc guide](http://erlang.org/doc/man/ssl.html). Therefore it was previously ignored but Ranch now rejects all unknown options.

I suspect you want `secure_renegotiate`.

**Comment by abelgo** [comment]
Perfect. I'm not particularly familiar whit Erlang or ranch the config was something on a cluster I set up almost 4 years ago. But that did that trick. Thanks for taking the time to investigate the issue. Much appreciated
