### ISSUE TITLE
RabbitMQ Visualizer not working

### ISSUE THREAD

**Issue by mojtabye** [rabbitmq/rabbitmq-server#1184]
RabbitMQ Visualiser is not working for me, I opened an [issue](https://github.com/rabbitmq/rabbitmq-management-visualiser/issues/8) and here is @michaelklishin 's answer.

> This very likely has nothing to do with the visualizer. HTTP API fails to serialize a particular data set to JSON because it contains a pid, a type that has no meaningful representation in JSON. We've fixed a bunch of those since 3.6.8 but it's not clear what the

<img width="1407" alt="screen shot 2017-04-13 at 5 34 01 pm" src="https://cloud.githubusercontent.com/assets/13944347/25005860/d28d2bba-206f-11e7-8ec7-71660fad0c69.png">

I am using `CentOS Linux release 7.3.1611 RabbitMQ 3.6.9, Erlang 19.3`.
<img width="381" alt="screen shot 2017-04-13 at 9 15 53 pm" src="https://cloud.githubusercontent.com/assets/13944347/25014974/2c759b5c-208f-11e7-9a7e-16df71877217.png">

<img width="700" alt="screen shot 2017-04-13 at 9 22 54 pm" src="https://cloud.githubusercontent.com/assets/13944347/25015059/75d0e126-208f-11e7-9656-60f20efab5d6.png">
<img width="650" alt="screen shot 2017-04-13 at 9 23 05 pm" src="https://cloud.githubusercontent.com/assets/13944347/25015062/770af4f0-208f-11e7-8bfa-983970fb22e6.png">

I tried to downgrade erlang from [erlang-rpm](https://github.com/rabbitmq/erlang-rpm/releases) to bellow versions but not working :(

1. erlang-19.3.0
2. erlang-19.2.3
3. erlang-18.3.4-5

`500 Internal Server Error`
`http://192.168.210.29:15672/api/all`

`{"error":"JSON encode error: {bad_term,<0.269.0>}","reason":"While encoding: \n[{queues,\n     [[{memory,26880},\n       {idle_since,<<\"2017-04-13 14:02:50\">>},\n       {consumer_utilisation,''},\n       {policy,''},\n       {exclusive_consumer_tag,''},\n       {consumers,0},\n       {recoverable_slaves,''},\n       {state,running},\n       {garbage_collection,\n           [{max_heap_size,0},\n            {min_bin_vheap_size,46422},\n            {min_heap_size,233},\n            {fullsweep_after,65535},\n            {minor_gcs,6}]},\n       {messages_ram,0},\n       {messages_ready_ram,0},\n       {messages_unacknowledged_ram,0},\n       {messages_persistent,0},\n       {message_bytes,0},\n       {message_bytes_ready,0},\n       {message_bytes_unacknowledged,0},\n       {message_bytes_ram,0},\n       {message_bytes_persistent,0},\n       {head_message_timestamp,''},\n       {backing_queue_status,\n           {struct,\n               [{mode,default},\n                {q1,0},\n                {q2,0},\n                {delta,[delta,0,0,0,0]},\n                {q3,0},\n                {q4,0},\n                {len,0},\n                {target_ram_count,infinity},\n                {next_seq_id,0},\n                {avg_ingress_rate,0.0},\n                {avg_egress_rate,0.0},\n                {avg_ack_ingress_rate,0.0},\n                {avg_ack_egress_rate,0.0}]}},\n       {messages_paged_out,0},\n       {message_bytes_paged_out,0},\n       {name,<<\"DBConsumer\">>},\n       {vhost,<<\"/\">>},\n       {durable,true},\n       {auto_delete,false},\n       {exclusive,false},\n       {owner_pid,none},\n       {arguments,{struct,[]}},\n       {pid,<0.269.0>},\n       {reductions,5023},\n       {reductions_details,[{rate,0.0}]},\n       {messages_ready,0},\n       {messages_ready_details,[{rate,0.0}]},\n       {messages_unacknowledged,0},\n       {messages_unacknowledged_details,[{rate,0.0}]},\n       {messages,0},\n       {messages_details,[{rate,0.0}]}],\n      [{memory,13090336},\n       {idle_since,<<\"2017-04-13 14:03:02\">>},\n       {consumer_utilisation,''},\n       {policy,''},\n       {exclusive_consumer_tag,''},\n       {consumers,0},\n       {recoverable_slaves,''},\n       {state,running},\n       {garbage_collection,\n           [{max_heap_size,0},\n            {min_bin_vheap_size,46422},\n            {min_heap_size,233},\n            {fullsweep_after,65535},\n            {minor_gcs,4}]},\n       {messages_ram,15294},\n       {messages_ready_ram,15294},\n       {messages_unacknowledged_ram,0},\n       {messages_persistent,468314},\n       {message_bytes,165813318},\n       {message_bytes_ready,165813318},\n       {message_bytes_unacknowledged,0},\n       {message_bytes_ram,5928988},\n       {message_bytes_persistent,165813318},\n       {head_message_timestamp,''},\n       {backing_queue_status,\n           {struct,\n               [{mode,default},\n                {q1,0},\n                {q2,0},\n                {delta,[delta,16384,453020,0,475136]},\n                {q3,15293},\n                {q4,1},\n                {len,468314},\n                {target_ram_count,infinity},\n                {next_seq_id,475136},\n                {avg_ingress_rate,0.0},\n                {avg_egress_rate,0.0},\n                {avg_ack_ingress_rate,0.0},\n                {avg_ack_egress_rate,0.0}]}},\n       {messages_paged_out,0},\n       {message_bytes_paged_out,0},\n       {name,<<\"DataProviderConsumer\">>},\n       {vhost,<<\"/\">>},\n       {durable,true},\n       {auto_delete,false},\n       {exclusive,false},\n       {owner_pid,none},\n       {arguments,{struct,[]}},\n       {pid,<0.272.0>},\n       {reductions,936890},\n       {reductions_details,[{rate,0.0}]},\n       {messages_ready,468314},\n       {messages_ready_details,[{rate,0.0}]},\n       {messages_unacknowledged,0},\n       {messages_unacknowledged_details,[{rate,0.0}]},\n       {messages,468314},\n       {messages_details,[{rate,0.0}]}]]},\n {exchanges,\n     [[{name,<<>>},\n       {vhost,<<\"/\">>},\n       {type,direct},\n       {durable,true},\n       {auto_delete,false},\n       {internal,false},\n       {arguments,{struct,[]}}],\n      [{name,<<\"DataProvider\">>},\n       {vhost,<<\"/\">>},\n       {type,topic},\n       {durable,true},\n       {auto_delete,false},\n       {internal,false},\n       {arguments,{struct,[]}}],\n      [{name,<<\"amq.rabbitmq.log\">>},\n       {vhost,<<\"/\">>},\n       {type,topic},\n       {durable,true},\n       {auto_delete,false},\n       {internal,true},\n       {arguments,{struct,[]}}],\n      [{name,<<\"amq.headers\">>},\n       {vhost,<<\"/\">>},\n       {type,headers},\n       {durable,true},\n       {auto_delete,false},\n       {internal,false},\n       {arguments,{struct,[]}}],\n      [{name,<<\"amq.topic\">>},\n       {vhost,<<\"/\">>},\n       {type,topic},\n       {durable,true},\n       {auto_delete,false},\n       {internal,false},\n       {arguments,{struct,[]}}],\n      [{name,<<\"amq.match\">>},\n       {vhost,<<\"/\">>},\n       {type,headers},\n       {durable,true},\n       {auto_delete,false},\n       {internal,false},\n       {arguments,{struct,[]}}],\n      [{name,<<\"amq.rabbitmq.trace\">>},\n       {vhost,<<\"/\">>},\n       {type,topic},\n       {durable,true},\n       {auto_delete,false},\n       {internal,true},\n       {arguments,{struct,[]}}],\n      [{name,<<\"amq.direct\">>},\n       {vhost,<<\"/\">>},\n       {type,direct},\n       {durable,true},\n       {auto_delete,false},\n       {internal,false},\n       {arguments,{struct,[]}}],\n      [{name,<<\"amq.fanout\">>},\n       {vhost,<<\"/\">>},\n       {type,fanout},\n       {durable,true},\n       {auto_delete,false},\n       {internal,false},\n       {arguments,{struct,[]}}]]},\n {bindings,\n     [[{source,<<>>},\n       {vhost,<<\"/\">>},\n       {destination,<<\"DBConsumer\">>},\n       {destination_type,queue},\n       {routing_key,<<\"DBConsumer\">>},\n       {arguments,{struct,[]}},\n       {properties_key,<<\"DBConsumer\">>}],\n      [{source,<<>>},\n       {vhost,<<\"/\">>},\n       {destination,<<\"DataProviderConsumer\">>},\n       {destination_type,queue},\n       {routing_key,<<\"DataProviderConsumer\">>},\n       {arguments,{struct,[]}},\n       {properties_key,<<\"DataProviderConsumer\">>}],\n      [{source,<<\"DataProvider\">>},\n       {vhost,<<\"/\">>},\n       {destination,<<\"DataProviderConsumer\">>},\n       {destination_type,queue},\n       {routing_key,<<\"#\">>},\n       {arguments,{struct,[]}},\n       {properties_key,<<\"%23\">>}],\n      [{source,<<\"DataProvider\">>},\n       {vhost,<<\"/\">>},\n       {destination,<<\"DBConsumer\">>},\n       {destination_type,queue},\n       {routing_key,<<\"#.TRADE\">>},\n       {arguments,{struct,[]}},\n       {properties_key,<<\"%23.TRADE\">>}]]},\n {channels,[]},\n {connections,[]},\n {vhosts,\n     [[{name,<<\"/\">>},\n       {tracing,false},\n       {messages_ready,468314},\n       {messages_ready_details,[{rate,0.0}]},\n       {messages_unacknowledged,0},\n       {messages_unacknowledged_details,[{rate,0.0}]},\n       {messages,468314},\n       {messages_details,[{rate,0.0}]}]]}]"}`
<img width="1537" alt="screen shot 2017-04-13 at 9 13 40 pm" src="https://cloud.githubusercontent.com/assets/13944347/25015088/90dbc166-208f-11e7-8125-3fcb2a9f8488.png">

**Comment by michaelklishin** [comment]
Well, this repository is not for the visualiser and there is no need to report this multiple times.

**Comment by michaelklishin** [comment]
Since I can't find this thread on rabbitmq-users, I suspect that it was filed here with the idea that it's a core server problem. It's not but sorry about confusing you. HTTP API is in rabbitmq/rabbitmq-management but I've noticed what path is in question and reopened https://github.com/rabbitmq/rabbitmq-management-visualiser/issues/8 as there is now evidence of what endpoint is at fault.
