### ISSUE TITLE
Creating multiple "Publisher Confirms" channels causes Timed Out exceptions

### ISSUE THREAD

**Issue by tyh25** [rabbitmq/rabbitmq-server#1186]
Hi all,

I'm getting timed out exceptions when I have concurrent Tasks or even a single iterative main thread attempting to create multiple channels with Publisher Confirms enabled via IModel.ConfirmSelect().

The operation has timed out.
   at RabbitMQ.Util.BlockingCell.GetValue(TimeSpan timeout)
   at RabbitMQ.Client.Impl.SimpleBlockingRpcContinuation.GetReply(TimeSpan timeout)
   at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Framing.Impl.Model._Private_ChannelOpen(String outOfBand)
   at RabbitMQ.Client.Framing.Impl.Connection.CreateModel()
   at iHerb.Checkout.RabbitMQTester.Program2.<>c.<.cctor>b__9_1(Object message, Action`1 publishConfirms, String messageId)

This exception occurs intermittently on various IModel methods like CreateModel(), QueueDeclare(), BasicPublish(), etc. I could not find much information on the web or in the documentation on this particular issue. I am aware that threads should not share channels. But it seems the process of creating multiple Publisher Confirms channels is not thread-safe or even safe when creating channels iteratively. Even locking IConnection.CreateModel() does not appear to resolve this issue. 
[Program2.txt](https://github.com/rabbitmq/rabbitmq-server/files/926902/Program2.txt)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
Channels in the server share no state and it should not matter at all whether they have publisher confirms enabled or not.

There is no evidence behind your claim and you have provided no code or any other details that can be used to reproduce (even server and .NET client version). This is mailing list material.

**Comment by michaelklishin** [comment]
Also, see (and post) server logs.

**Comment by michaelklishin** [comment]
One case where creating a channel could fail is when you create enough of them to hit [a memory alarm](http://www.rabbitmq.com/alarms.html), after which the node will stop reading from the socket and no response will reach the client until the alarm clears.

Channels do consume some resources, and when that is multiplied by several thousands it can make a difference.
