### ISSUE TITLE
I/O average time per operation graph doesn't match legend in 3.6.9

### ISSUE THREAD

**Issue by cap10morgan** [rabbitmq/rabbitmq-server#1198]
In RabbitMQ 3.6.9: 
<img width="668" alt="screen shot 2017-04-26 at 10 44 49 am" src="https://cloud.githubusercontent.com/assets/59748/25451270/d8cc7dbe-2a7e-11e7-9f93-ee96bf24b155.png">

Note the discrepancy between the "File handle open attempt" legend value and where the line is at in the graph.

Here's the same chart from a 3.6.6 cluster (I don't have any instances of versions 3.6.7 or 3.6.8 to test with unfortunately):
<img width="616" alt="screen shot 2017-04-26 at 12 51 27 pm" src="https://cloud.githubusercontent.com/assets/59748/25451370/300bc742-2a7f-11e7-8ebc-2687d9e3a998.png">

**Comment by michaelklishin** [comment]
@cap10morgan may I ask you move this to rabbitmq-management? I suspect that the issue ca be with the visualization part, not stats collection or aggregation, so let's start with that assumption. Also, any script we can use to reproduce?

Thank you for providing the evidence of the discrepancy.

**Comment by michaelklishin** [comment]
FTR, it was moved to https://github.com/rabbitmq/rabbitmq-management/issues/384.
