### ISSUE TITLE
Introduce a randomized startup delay for peer discovery mechanisms that support registration

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#1202]
As of #486 and #1143 RabbitMQ has a pluggable peer discovery mechanism. This unifies an "autoclustering" feature the broker has had for a while with some ideas from @gmr's [rabbitmq-autocluster](https://github.com/rabbitmq/rabbitmq-autocluster).

However, we haven't adopted the randomized delay feature from the plugin. Consider a cluster of 5 nodes that is provisioned from scratch on AWS. Nodes 1 and 2 boot in parallel and discover no peers, therefore register as ones. This is a natural race condition. Other nodes discover 1 (or 2) and join them. As a result, due to the race condition there are 2 clusters instead of 1. Provision 1 cluster, get 1 for free!

This problem is present in automated cluster provisioning of some other tools and there are two common workarounds:

 * Provision a "seed node" first, then the rest
 * Inject a random delay to work around the race condition (in practice)

The latter approach may sound silly but it works well in practice and was adopted in some shape or form in several systems and distributed algorithms (Raft is a popular recent example). It also worked reasonably well for rabbitmq-autocluster.

Therefore I suggest that we introduce a similar delay, e.g. in the range of 5 to 90 seconds by default, for backends that support peer registration. Backends that rely on node config file or pre-configured DNS records are not affected by the above problem and therefore need no delay.

**Comment by gerhard** [comment]
It sounds reasonable with sufficient real-world implementations backing this approach, I cannot think of any reason why we shouldn't implement it in 3.7
