### ISSUE TITLE
Support more queue master-to-node distribution strategies

### ISSUE THREAD

**Issue by gsogol** [rabbitmq/rabbitmq-server#121]
Per request of @tsaleh:

Having an ability to create queues on different nodes via preconfigured a set of limited strategies would help alleviate a single node getting pounded. Multiple strategies can be given to consumers to pick from, similar to how most load balancers work: 1) # of exchanges/queues already bound on each node 1) by # of messages on each node (so create a queue on a node with least number of queues messages 2) by cpu/memory 3) # of current connections 4) by cpu/memory utilization

Leave the defaults as is, no arrangement but give an ability to configure. In my case, I would choose  the 1st one. I'm not saying do all of them but over time, you add more and more via a pluggable model.

**Comment by michaelklishin** [comment]
Exchanges are just routing tables that are always replicated to all nodes.

So you'd like to control which node queue masters are declared on via strategies? Currently it's the node the client is connected to.

**Comment by gsogol** [comment]
The queue that the client creates should be on a node where the specified strategy meets the criteria.

**Comment by michaelklishin** [comment]
OK, I believe my understanding is correct then. Makes sense, thank you!

**Comment by gsogol** [comment]
Thank you

**Comment by Ayanda-D** [comment]
@michaelklishin, question, for the min-masters policy, do we count & compare bound queues across all vhosts per rabbit node? and not specifically the vhosts of the queue being declared?

**Comment by michaelklishin** [comment]
@Ayanda-D all vhosts.

**Comment by Ayanda-D** [comment]
Okay. Thank you.

**Comment by michaelklishin** [comment]
Fixed by #217, https://github.com/rabbitmq/rabbitmq-test/pull/1, and https://github.com/rabbitmq/rabbitmq-website/pull/32.

**Comment by michaelklishin** [comment]
…and https://github.com/rabbitmq/rabbitmq-test/pull/2.
