### ISSUE TITLE
rabbitmqctl exits 0 when the rabbitmq node exits because it cannot cluster

### ISSUE THREAD

**Issue by jutkko** [rabbitmq/rabbitmq-server#1214]
We observe the following behaviour:

1. We bring up a cluster with 3 nodes (A, B, C)
1. We shut down the entire cluster in the order of A, B, C
1. We try to restart node A, which was not the last one to shut down
1. We run `rabbitmqctl wait` on Node A's rabbitMQ pid
1. Node A's restart attempt times out because Node C isn't up
1. `rabbitmqctl wait` returns 0

We don't expect to see return value 0 because the cluster isn't up or healthy.

Is this known behaviour?

@gerhard @deniseyu

**Comment by jutkko** [comment]
@vlad-stoian

**Comment by michaelklishin** [comment]
Our team does not use GitHub issues for questions.

Your observations are missing one critically important piece of information: node A gives up *and then stops* on step 5. If that's the case, then `rabbitmqctl wait` then also times out?

**Comment by XieXianbin** [comment]
when i update my rabbitmq cluster from 3.6.2-1 to 3.6.10-1, Appear again.
