### ISSUE TITLE
Segment used all available storage

### ISSUE THREAD

**Issue by PaniniHode** [rabbitmq/rabbitmq-server#12159]
### Describe the bug

https://github.com/rabbitmq/rabbitmq-server/issues/12141
Yesterday, i created the issue with bug report, and today it's just been deleted, i don't know why, i don't recieve  any further comments except request for segment files from @mkuratczyk , so i just recreate it

I'm facing the same issue from this discussions/issues:
https://github.com/rabbitmq/rabbitmq-server/issues/6447
https://github.com/rabbitmq/rabbitmq-server/discussions/5258
https://github.com/rabbitmq/discussions/issues/164

In some random moment, at least we couldn't find the pattern, queue starting to grown own segment files until disk is full(70GB in several hours, usually), queue not really high loaded, 100-1000 rps, ~2000 stored messages, 10-20 consumers. What's seems weird is reductions rps
<img width="662" alt="Screenshot 2024-08-28 at 1 16 50 PM" src="https://github.com/user-attachments/assets/c3c3a7fa-b7eb-4eb3-a3de-b46d19994b6a">

Hope this issue wasn't be deleted :)

### Reproduction steps

As i sad earlier, we couldn't find pattern, we look into segments files next time and save it to share

### Expected behavior

Normal disk usage by those queues

**Comment by michaelklishin** [comment]
@PaniniHode because it was moved to a discussion.
