### ISSUE TITLE
Consider making `rabbit` application transient.

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#1216]
OTP applications support `restart_type` option, which defines a VM behaviour when application is stopped. It can be `permanent`, `temporary` or `transient` http://erlang.org/doc/apps/kernel/application.html#start-2

Since the `rabbit` application is essential in most of deployments, it makes sense to make it `transient` by default, so the VM will be stopped when the application fails abnormally. That would be much less confusing for an operator, than an erlang VM running without RabbitMQ.

The current `temporary` restart type can be made optional.

**Comment by michaelklishin** [comment]
@binarin FYI, I hope it doesn't go against your embedding efforts.
