### ISSUE TITLE
Support message persistence in dynamic shovels

### ISSUE THREAD

**Issue by gfoligna** [rabbitmq/rabbitmq-server#1218]
Please, it would be great to support at least `{delivery_mode, 2}` in dynamic shovel. Persisting messages when running the server at a container, and most likely to run it in a pod at kubernetes, would be awesome.

**Comment by michaelklishin** [comment]
@gfoligna dynamic shovels support custom `publish-properties` which covers delivery mode amongst other things. Please start a rabbitmq-users thread if you think that's not sufficient for any reason.
