### ISSUE TITLE
Cannot bind to IPv6 interfaces

### ISSUE THREAD

**Issue by elw00d** [rabbitmq/rabbitmq-server#1222]
Trying rabbitmq-server 3.6.9 using next configuration:

```
[
  {rabbit, [
    {tcp_listeners, [{"::", 5672}]},  % This works OK
    {loopback_users, []},
    {load_definitions, "/etc/rabbitmq/rabbitmq_definitions.json"},
    {cluster_partition_handling, pause_minority},
    {rabbitmq_management, [{listener, [{port, 15672}, {ip, "0.0.0.0"}]}]}  % IPv6 doesn't work here
  ]},
  {kernel, [
    {inet_dist_use_interface, {0,0,0,0}},  %  IPv6 doesn't work here
    {inet_dist_listen_min, 44001},
    {inet_dist_listen_max, 44001}
  ]}
].
```

AMQP listener binds to `::` correctly.
But when I try to configure rabbitmq management plugin and kernel module, I can't do this. Management plugin crashes.
And for kernel `inet_dist_use_interface` option – existing IP format makes impossible to write there something that is not IPv4 address.

In dual-stack system by default (without special config) these modules bind to IPv4 interfaces only.

It seems to be bug.. But even if doesn't, IMO, it will be better to redesign configuration formats for TCP listeners to be same in whole configuration, to go away from different formats for each module.

**Comment by michaelklishin** [comment]
The `kernel.*` settings are not part of RabbitMQ. They come from Erlang/OTP.

**Comment by elw00d** [comment]
Ok.. and what about rabbitmq management plugin ?
