### ISSUE TITLE
Expand username and vhost variables in topic authorization patterns

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#1229]
This is a follow-up to #505 and #1085.

In some cases the number of users and therefore patterns is so large it becomes very difficult to manage. Expanding username and vhost as variables can make this much more manageable.
See https://github.com/rabbitmq/rabbitmq-server/issues/1085#issuecomment-298675230 for the original discussion.

For example, with a pattern `services/{vhost}/accounts/{username}/notifications`, connection vhost of `transactions` and effective username of `molly`, the pattern would expand to `services/transactions/accounts/molly/notifications`.

Implementation of this seems fairly straightforward, the most suitable place to perform expansion is right before caching the permission (as both vhost and username are immutable for the lifetime of a connection).

**UPD**: we have agreed to investigate the `{variable}` syntax first as it is very popular in HTTP routing libraries and frameworks. `:variable` is a runner-up.

**Comment by michaelklishin** [comment]
Note that the syntax in the example above is just that, an example. We can use `%username` or even `%u` (I'm not a fan of abbreviations, though).

**Comment by gerhard** [comment]
I'm in favour of explicit vars, not abbreviations. Makes sense otherwise.

**Comment by hairyhum** [comment]
I wonder how would escaping work. For example when username is something like `user/name`.

**Comment by michaelklishin** [comment]
@hairyhum we won't escape values as no matter how you do it, it is always wrong for someone. Use such usernames (and vhosts) at your own risk.

**Comment by gerhard** [comment]
I would assume that such usernames would not be allowed to enter the system. [Confident code](https://www.youtube.com/watch?v=T8J0j2xJFgQ) with guards at the edges and all that.

**Comment by hairyhum** [comment]
@gerhard making such usernames not allowed will create tons of problems, because they are allowed now.

**Comment by michaelklishin** [comment]
Topic authorization is not available in any GA release, there will be a clear warning in the docs. There already are ways to mess up the routing by using values with slashes, and they even slightly vary between protocols.

We can't just reject usernames with slashes but we could validate newly created ones (we have pluggable credential validation mechanism already). That's not in scope of this issue, however.

**Comment by hairyhum** [comment]
Then we should just mention the slashes issue in the topic authorization docs.
