### ISSUE TITLE
Definitions export from management UI  is not sorted in Alphabetical Order

### ISSUE THREAD

**Issue by mrs01dev** [rabbitmq/rabbitmq-server#12297]
### Is your feature request related to a problem? Please describe.

comparing definitions from different servers is not easy

### Describe the solution you'd like

Definitions  Items array should be sorted  sorted in Alphabetical Order
    "users": [],
    "vhosts": [    ],
    "permissions": [    ],
    "topic_permissions": [    ],
    "parameters": [    ],
    "global_parameters": [      ],
    "policies": [    ],
    "queues": [    ],
    "exchanges": [    ],
    "bindings": [     ]

**Comment by lukebakken** [comment]
This would be a great first issue for someone to tackle, if they cared about it enough.

**Comment by michaelklishin** [comment]
@mrs01dev so what? These exports are not meant to be looked at or edited by humans all that often.

Those who really care about ordering of keys in JSON documents can use tools such as `jq` to get their fix. Our small team has infinitely bigger fish to fry.

**Comment by michaelklishin** [comment]
There are also tools such as [JSON Diff](https://www.jsondiff.com/).
