### ISSUE TITLE
Log resource limits in kiB, MiB, GiB (as those are the limits we and other tools actually use)

### ISSUE THREAD

**Issue by dcorbacho** [rabbitmq/rabbitmq-server#1233]
When we do conversions to MB inside `vm_memory_monitor` we use [1 MiB (1048576 bytes)](https://github.com/rabbitmq/rabbitmq-server/blob/stable/src/vm_memory_monitor.erl#L46), as in the [log messages](https://github.com/rabbitmq/rabbitmq-server/blob/stable/src/vm_memory_monitor.erl#L225). But when we convert values such as the high watermark, we use [1MB (1000000 bytes)](https://github.com/rabbitmq/rabbitmq-server/blob/stable/src/rabbit_resource_monitor_misc.erl#L40).

Detected while testing https://github.com/rabbitmq/rabbitmq-server/issues/1224

**Comment by michaelklishin** [comment]
It should be noted that `/proc/meminfo` actually reports values in mebibytes/kibibytes according to [RHEL documentation](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/s2-proc-meminfo.html).

Therefore the use of each value should be analysed on a case by case basis.
