### ISSUE TITLE
UI plugin to move around messages

### ISSUE THREAD

**Issue by gsogol** [rabbitmq/rabbitmq-server#124]
Per @tsaleh request:

There's always a need to move messages around from either cluster to cluster or queue to queue within a cluster. Whether your need arose from network partitioning or due to application errors and dead-letter-queues, you need a built-in way to move messages by specifying origin and destination clusters and exchanges/queues. Having a consistent and out-of-the-box UI plugin will benefit the community. 

Secondly, having a CLI that does similar would be an added bonus.

**Comment by michaelklishin** [comment]
We already support moving messages within a cluster with the Shovel plugin. If you have Shovel and Shovel management plugins enabled, it's on the queue page (not very visible, that's true).

**Comment by gsogol** [comment]
The request is about a UI plugin. I know about shovels and federation. There are scenarios where you just tell the admin or in devops world a developer and s/he just goes in and manually moves the messages. There are many cases where you want to move messages from a DLQ back to a specific exchange to be processed because you fixed a bug on the subscriber side and want those messages replayed.

**Comment by michaelklishin** [comment]
I understand. We already have this for intra-cluster copying which uses a one-off Shovel. We'll see what may be missing.

**Comment by michaelklishin** [comment]
We think dynamic Shovels and the "Move messages" UI feature that works within a cluster are sufficient and no major pieces are missing.
