### ISSUE TITLE
management plugin shows redundant Args x-queue-type: quorum

### ISSUE THREAD

**Issue by jonenst** [rabbitmq/rabbitmq-server#12428]
### Is your feature request related to a problem? Please describe.

looking at the queues in the rabbitmq management plugin, the Args badge is redundant with the type column, it makes this display less readable. Maybe it should filtered out ?

![rabbitmanagementargsqueuetype](https://github.com/user-attachments/assets/145aa5f0-43e1-4fb1-8a20-614628a3186a)

Note: in my case I even used global DQT and there was not even an explicit arg used to create these queues so it's extra suprising.

### Describe the solution you'd like

x-queue-type Args not shown when the type is already visible in the next column ?
x-queue-type Args not shown when it's not explicitly set at queue creation (i.e. comes from vhost or global settings) ?

**Comment by michaelklishin** [comment]
It is important for troubleshooting of DQT specifically.

**Comment by jonenst** [comment]
I see, glad to know this was not just an oversight. Thanks for this great project, keep up the good work !!
