### ISSUE TITLE
rabbitmq management ui says network partition but rabbitmq_unreachable_cluster_peers_count=0

### ISSUE THREAD

**Issue by elelayan** [rabbitmq/rabbitmq-server#12440]
### Describe the bug

there is no metric to report a mnesia partition when network connection is re-established.

### Reproduction steps

1. create a 2 node cluster in 2 separate VMs with rabbitmq 3.12.14
3. add a firewall rule to drop traffic to port 25672 on one VMs
4. conntrack -F on one VM to break the existing connection
5. observe each nodes seing the other as down, then the warning appears in each node management ui that _Mnesia reports that this RabbitMQ cluster has experienced a network partition_. 
10. `curl http://node-1:15692/metrics | grep rabbitmq_unreachable_cluster_peers_count` and `curl http://node-1:15691/metrics | grep rabbitmq_unreachable_cluster_peers_count` both report value 0

...

### Expected behavior

According to #2508, rabbitmq_unreachable_cluster_peers_count should indicate the partition. It does not. There is no other metric that I can find related to the partition issue

**Comment by elelayan** [comment]
(simplified repro even more)

**Comment by gomoripeti** [comment]
Hi @elelayan 

In the original repro you had "after some time both nodes reach the other one." The `rabbitmq_unreachable_cluster_peers_count` metric shows if the other node is unreachable on the Erlang distribution level.

The RabbitMQ notion of "network-partion" is on the other hand Mnesia-specific (as hinted by the Management UI as well: "Mnesia reports that this RabbitMQ cluster has experienced a network partition.") Even after the Erlang distribution connection is restored, Mnesia DB can still be in a partitioned state before it is repaired.

During the discussion of https://github.com/rabbitmq/rabbitmq-server/issues/2508 it was decided that the Mnesia-specific "network-partition" notion is not applicable in the future (when using Khepri based clustering and metadata store) so it shouldn't be exposed via Prometheus. But you can still access the info via the Management API.

I think it is not a bug that a metric is missing - it is a feature request. But maybe I misunderstood and the bug you want to highlight is that the two nodes cannot reach each other via Erlang distribution and still `rabbitmq_unreachable_cluster_peers_count = 0`? (and it is independent from Mnesia network-partition)

**Comment by elelayan** [comment]
Hi @gomoripeti, thank you for your answer.
Indeed `rabbitmq_unreachable_cluster_peers_count = 1` as long as they can't reach each other.
My mistake for not reading correctly #2508: I was convinced that rabbitmq_unreachable_cluster_peers_count was indeed the metric to detect no network and mnesia partition.
I can only lament that a major issue like mnesia db is partitioned is not reported in monitoring.
Best
