### ISSUE TITLE
Latest rabbitmq server version Handshake Failure

### ISSUE THREAD

**Issue by kotireddy478** [rabbitmq/rabbitmq-server#12513]
### Describe the bug

Hi,

I'm trying to install rabbitmq 4.0.2/4.0.1 on Red Hat 8 Linux but it's giving below error:

> TLS server: In state hello at tls_dtls_connection.erl:696 generated SERVER ALERT: Fatal - Handshake Failure
> malformed_handshake_data

Could you please help? Please let me know if you need any additional info.

### Reproduction steps

1. download rabbitmq-server and erlang off the office repositories, direct download
2. install both the packages using dnf localinstall
3. generate ssl, configure, restart rabbitmq-server. The restart giving the above error.

### Expected behavior

UI should work

**Comment by mkuratczyk** [comment]
Are you using Erlang 27.1.1? If so, this is a known bug in Erlang. You can downgrade to 27.1 to avoid it for now.
Keep in mind that Erlang 27 is not officially supported by RabbitMQ:
https://www.rabbitmq.com/docs/which-erlang

**Comment by kotireddy478** [comment]
@mkuratczyk  Thanks for the reply. No - I've installed Erlang 26.2.5.3

**Comment by mkuratczyk** [comment]
Yeah, same bug. Seems like already fixed in 26.2.5.4:
https://github.com/erlang/otp/commit/1c6172ca5ed24f6bbeda6e68dfa316b7dac4a65f

**Comment by kotireddy478** [comment]
@mkuratczyk Thanks again, I have downloaded and installed erlang version 26.2.5.4 but still giving the same error. Do I need to clear any cache or anything else please?
