### ISSUE TITLE
The debian (and probably also the rpm) package should limit the erlang version to 19

### ISSUE THREAD

**Issue by oneiros-de** [rabbitmq/rabbitmq-server#1251]
Since erlang 20 officially breaks rabbitmq, the debian/rpm package should limit the erlang version the package depends on to 19.x

**Comment by michaelklishin** [comment]
Thank you for your time.

OTP 20 doesn't "break RabbitMQ" for all cases, only [upgrades from 19.x and earlier versions](https://groups.google.com/forum/#!searchin/rabbitmq-users/OTP$2020%7Csort:relevance/rabbitmq-users/_imbAavBYjY/ninEKhMYAgAJ) are problematic. We are working on supporting OTP 20 in 3.6.x, at least for most cases, hopefully 3.6.11 will tolerate upgrades in most scenarios (e.g. when only AMQP 0-9-1 and 1.0 are used).

Closing this with that assumption. If we can't support 20 well, we will consider restricting the version for 3.6.x.

**Comment by michaelklishin** [comment]
Also note that it's possible to restrict a particular package to a version/range without any package modifications:

 * [apt pinning](https://wiki.debian.org/AptPreferences)
 * [yum version locking plugin](https://scottlinux.com/2013/03/18/red-hat-6-or-centos-6-yum-tips-lock-package-versions-and-only-apply-security-updates/)

**Comment by oneiros-de** [comment]
Well, the page on erlang currently says "Erlang/OTP 20 is NOT supported due to breaking changes" - it would be nice if the packages would reflect that.

And yes, we have implemented apt pinnig.
