### ISSUE TITLE
Enable Node Tagging in RabbitMQ Clusters with Prometheus Integration

### ISSUE THREAD

**Issue by SimonUnge** [rabbitmq/rabbitmq-server#12542]
### Is your feature request related to a problem? Please describe.

Currently, with Prometheus, we can group the entire RabbitMQ cluster under a single name using rabbitmqctl set_cluster_name, and this name is exposed by Prometheus. However, it would be useful to have the ability to tag and name subsets of nodes within the cluster. These tags could then be exposed by Prometheus, allowing for more granular grouping and analysis of data from specific subsets of nodes.

### Describe the solution you'd like

Make use of global parameters to tag nodes. Perhaps something like:

```
rabbitmqctl set_global_parameter node_tags '{"tag1":["node1", "node2"], "tag2":["node2", "node3"], "tag3":["node1"]}'
```

And then pick up those values and expose them to prometheus.
Not being an expert on Prometheus (or say grafana to use the data), I can think of 3 ways to expose the tags. 

### Option 1: Expose Each Tag as Its Own Metric
```
rabbitmq_tag_info{rabbitmq_tag="tag1"} 1
rabbitmq_tag_info{rabbitmq_tag="tag3"} 1
```

**Pros:**
* Straightforward: Easy to visualize in Grafana because each tag gets its own metric. You can filter or group by the rabbitmq_tag label directly.
* Simple queries: Prometheus queries and Grafana dashboards would be simple to write because each tag is already broken out into its own metric.

**Cons:**
* Potentially high cardinality: If you have many nodes with many tags

### Option 2: Comma-Separated Value in a Label
```
rabbitmq_identity_info{rabbitmq_node="rabbit@node1",rabbitmq_cluster="misfits",rabbitmq_cluster_permanent_id="xyz", rabbitmq_tags="tag1,tag3"} 1
```

**Pros:**
* Minimal additional metrics:  Just appending a new label to an existing metric.
* Compact: Less cluttered in terms of labeling and metric structure.

**Cons:**
* Query complexity: Prometheus doesn’t support native splitting of a comma-separated value. This means Grafana would have difficulty using this as a tag filter directly. You’d need to rely on complex query functions (if they even exist) to parse the tag list.
* Limited flexibility: This approach works best for visualization, but not for operational queries where you may want to drill down into the data by individual tags.

### Option 3: Each Tag as a Label in rabbitmq_identity_info
```
rabbitmq_identity_info{rabbitmq_node="rabbit@node1",rabbitmq_cluster="misfits",rabbitmq_cluster_permanent_id="xyz", rabbitmq_tags_tag1="1", rabbitmq_tags_tag3="1"} 1
```
**Pros:**
* Flexible querying: Each tag becomes its own label, making it easy to query and filter by individual tags in Prometheus and Grafana.
* Native support in Grafana: Grafana would have no issues filtering or grouping by these labels, as each tag would be represented as a native label.

**Cons:**
* High cardinality: This could quickly lead to high cardinality if you have many tags, as each unique combination of tags across all nodes would create new time-series in Prometheus. Each tag would also create a new atom.
* Potential clutter: Adding multiple labels dynamically for each tag can make the metric hard to manage and read. Over time, if the number of tags grows, this can become cumbersome.

**Comment by michaelklishin** [comment]
This was closed after a discussion on community Slack. @SimonUnge will file another issue with a slightly different feature.
