### ISSUE TITLE
AQMP 0.9.1 over WebSockets support

### ISSUE THREAD

**Issue by vvuk** [rabbitmq/rabbitmq-server#12565]
### Is your feature request related to a problem? Please describe.

I've got an app written in a framework that can target both native and web (in this case Flutter/Dart, but equally Blazor WebAssembly, etc.). There are great AQMP or RabbitMQ client libraries for these environments, but they all talk AQMP directly over TCP. (Unless I'm missing something?)

### Describe the solution you'd like

I'd like a plugin for rabbitmq that accepts a HTTP(s) upgrade to websocket connection on a port, and then just talks the normal AQMP wire protocol through websockets. This can then be combined with the same thing on the client end. This can technically already be done with something like [websockify](https://github.com/novnc/websockify) but a plugin would be nice.

### Describe alternatives you've considered

STOMP over websockets -- not high performance enough for use case
MQTT over websockets -- could possibly work, but already have existing app using AQMP and AQMP semantics, and would like to stay with that

**Comment by michaelklishin** [comment]
@vvuk AMQP 0-9-1 support in RabbitMQ is not going away but those who want to use it over WebSockets will have to develop such a plugin themselves. This is nowhere near the list of our team's priorities.
