### ISSUE TITLE
Management plugin drops proc_used metric

### ISSUE THREAD

**Issue by BjoernT** [rabbitmq/rabbitmq-server#12573]
### Describe the bug

We have rabbitmq 3.10.7 with Erlang 25.0.4 and noticed that the management plugin keeps dropping the proc_used metric until the next restart of the plugin. We don't see any errors in the logs or OS indicating what might be the problem. 
We have setup a cluster of 3 nodes and only on the 1st node we are observing the issue, so any idea how to troubleshoot this issue would be appreciated

### Reproduction steps

Query ` https:/<ip>:15671/api/nodes | jq .` and 2/3 of the nodes provide the `proc_used, proc_total` metric

### Expected behavior

Provide metric or error message why helper library fails

**Comment by michaelklishin** [comment]
RabbitMQ 3.10 has been [out of community support for over two years](https://www.rabbitmq.com/release-information) now.
