### ISSUE TITLE
Implement locking support in peer discovery

### ISSUE THREAD

**Issue by dcorbacho** [rabbitmq/rabbitmq-server#1257]
Originally part of the `rabbitmq_autocluster` plugin: https://github.com/rabbitmq/rabbitmq-autocluster/pull/6

**Comment by michaelklishin** [comment]
`effort-medium` seems reasonable here because this involves 3 different engineers, multiple plugins and quite a bit of testing (on top of what's already been done in https://github.com/rabbitmq/rabbitmq-autocluster/pull/6).

**Comment by michaelklishin** [comment]
There is no PR for `rabbitmq-common` where [peer_discovery_backend](https://github.com/rabbitmq/rabbitmq-common/blob/rabbitmq-server-1257/src/rabbit_peer_discovery_backend.erl) resides.
