### ISSUE TITLE
`rabbitmqctl authenticate_user` is not being logged in `rabbitmq-diagnostics consume_event_stream`

### ISSUE THREAD

**Issue by simplepad** [rabbitmq/rabbitmq-server#12587]
### Describe the bug

`rabbitmqctl authenticate_user` is not being logged in `rabbitmq-diagnostics consume_event_stream`

### Reproduction steps

1. set up rabbitmq in a docker (latest)
2. execute `rabbitmq-diagnostics consume_event_stream --pattern user.*` and leave it running
3. execute `rabbitmqctl add_user testuser` and `rabbitmqctl authenticate_user testuser`
4. check the output of the command from step 2

### Expected behavior

both commands from step 3 produce events

### Additional context

actual:
only the `add_user` command produces an event, while authentication attemps are not getting logged at all (both successful and unsuccessful)

**Comment by michaelklishin** [comment]
@simplepad I'm not sure why you expect `rabbitmqctl authenticate_user` to produce internal events. 

That command is nothing more than a troubleshooting tool. It is not a client connection, therefore it does not generate any events.
