### ISSUE TITLE
i have a deployed a rabbitmq server on my server, it was working fine for many days aftre some time i am facing connection issue "Gracefully halting Erlang VM"

### ISSUE THREAD

**Issue by kishorpacefin** [rabbitmq/rabbitmq-server#12596]
### Describe the bug

This is my server details 

OS PID: 1564910
OS: Linux
Uptime (seconds): 6822
Is under maintenance?: false
RabbitMQ version: 3.9.13
Node name: rabbit@ip-172-20-5-148
Erlang configuration: Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]
Erlang processes: 370 used, 1048576 limit
Scheduler run queue: 1
Cluster heartbeat timeout (net_ticktime): 60

one node is running for this rabbitmq.

issues
---------
this server is running fine for many months , but suddenly i am getting this issue in the error log.
Gracefully halting Erlang VM

and also some issue i got in the normal log
```
discarding message {'$gen_cast',{force_event_refresh,#Ref<0.102402969.3932684290.12114>}} from <0.228.0> to <0.12271.33> in an old incarnation (1711426527) of this node (1711426528)
2024-10-28 04:13:48.338883+00:00 [erro] <0.228.0>
2024-10-28 04:13:48.338883+00:00 [erro] <0.228.0>
2024-10-28 04:13:48.338887+00:00 [erro] <0.228.0> Discarding message {'$gen_cast',{force_event_refresh,#Ref<0.102402969.3932684290.12114>}} from <0.228.0> to <0.7159.189> in an old incarnation (1711426527) of this node (1711426528)
```

please help me to solve this this is a productiion issue .

### Reproduction steps

i couldn't say how to recreate this issue because this issue came suddenly , we don;t know why this issue coming.

### Expected behavior

this issue should not coming

**Comment by mkuratczyk** [comment]
RabbitMQ 3.9.x has reached end of life years ago. See https://www.rabbitmq.com/release-information
