### ISSUE TITLE
RabbitMQ stops from time to time with segfault

### ISSUE THREAD

**Issue by lskbr** [rabbitmq/rabbitmq-server#1261]
I have a small RabbitMQ server with millions of messages. It all works well, but from time to time it simply stops. I saw a segfault being logged on dmesg, but besides that I don't have any extra information.
The machines had enougth ram and disk space.

I'm using RabbitMQ 3.6.9 with Erlang 19.3, on Ubuntu 16.04.2 LTS - Linux xcipp 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux.

rabbitmq.config:
```
[
    {kernel, [
      {inet_default_connect_options, [{nodelay, true}]},
      {inet_default_listen_options,  [{nodelay, true}]}
    ]},
    {rabbit, [
       {tcp_listeners, [{"192.168.1.224", 5672}]},
       {tcp_listen_options, [                         
                          {backlog,       4096},
                          {nodelay,       true},
                          {linger,        {true,0}},
                          {exit_on_close, false},
                          {sndbuf,        196608},
                          {recbuf,        196608}
                         ]},
       {vm_memory_high_watermark, 0.6},
       {vm_memory_high_watermark_paging_ratio, 0.30},
       {log_levels, [{channel, debug}, 
                  {connection, info}]}
    ]}
].
```

rabbitmq-env.conf

`RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="+A 128 +t 10048576"`

enabled_plugins

`[rabbitmq_management].`

/etc/sysctl.conf
```
net.ipv4.tcp_max_syn_backlog=2048
net.core.somaxconn = 1024
```

ulimit -a
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63685
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63685
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by lukebakken** [comment]
Hi @lskbr -

Without a core dump or exact means to reproduce this issue, we can't move forward. GitHub issues are used when an actionable piece of work has been defined.

Please post your findings to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users), ideally once you are able to produce a core file.

Other valuable information:

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information. When we have enough details and evidence we'd be happy to file a new issue.

Thanks!
Luke

**Comment by lskbr** [comment]
rabbitmqctl environment

```
Application environment of node rabbit@chipp...
[{amqp_client,[{prefer_ipv6,false},{ssl_options,[]}]},
 {asn1,[]},
 {compiler,[]},
 {cowboy,[]},
 {cowlib,[]},
 {crypto,[]},
 {inets,[]},
 {kernel,
     [{error_logger,tty},
      {inet_default_connect_options,[{nodelay,true}]},
      {inet_default_listen_options,[{nodelay,true}]},
      {inet_dist_listen_max,25672},
      {inet_dist_listen_min,25672}]},
 {mnesia,[{dir,"/var/lib/rabbitmq/mnesia/rabbit@chipp"}]},
 {os_mon,
     [{start_cpu_sup,false},
      {start_disksup,false},
      {start_memsup,false},
      {start_os_sup,false}]},
 {public_key,[]},
 {rabbit,
     [{auth_backends,[rabbit_auth_backend_internal]},
      {auth_mechanisms,['PLAIN','AMQPLAIN']},
      {background_gc_enabled,false},
      {background_gc_target_interval,60000},
      {backing_queue_module,rabbit_priority_queue},
      {channel_max,0},
      {channel_operation_timeout,15000},
      {cluster_keepalive_interval,10000},
      {cluster_nodes,{[],disc}},
      {cluster_partition_handling,ignore},
      {collect_statistics,fine},
      {collect_statistics_interval,5000},
      {config_entry_decoder,
          [{cipher,aes_cbc256},
           {hash,sha512},
           {iterations,1000},
           {passphrase,undefined}]},
      {credit_flow_default_credit,{400,200}},
      {default_permissions,[<<".*">>,<<".*">>,<<".*">>]},
      {default_user,<<"guest">>},
      {default_user_tags,[administrator]},
      {default_vhost,<<"/">>},
      {delegate_count,16},
      {disk_free_limit,50000000},
      {enabled_plugins_file,"/etc/rabbitmq/enabled_plugins"},
      {error_logger,{file,"/var/log/rabbitmq/rabbit@chipp.log"}},
      {fhc_read_buffering,false},
      {fhc_write_buffering,true},
      {frame_max,131072},
      {halt_on_upgrade_failure,true},
      {handshake_timeout,10000},
      {heartbeat,60},
      {hipe_compile,false},
      {hipe_modules,
          [rabbit_reader,rabbit_channel,gen_server2,rabbit_exchange,
           rabbit_command_assembler,rabbit_framing_amqp_0_9_1,rabbit_basic,
           rabbit_event,lists,queue,priority_queue,rabbit_router,rabbit_trace,
           rabbit_misc,rabbit_binary_parser,rabbit_exchange_type_direct,
           rabbit_guid,rabbit_net,rabbit_amqqueue_process,
           rabbit_variable_queue,rabbit_binary_generator,rabbit_writer,
           delegate,gb_sets,lqueue,sets,orddict,rabbit_amqqueue,
           rabbit_limiter,gb_trees,rabbit_queue_index,
           rabbit_exchange_decorator,gen,dict,ordsets,file_handle_cache,
           rabbit_msg_store,array,rabbit_msg_store_ets_index,rabbit_msg_file,
           rabbit_exchange_type_fanout,rabbit_exchange_type_topic,mnesia,
           mnesia_lib,rpc,mnesia_tm,qlc,sofs,proplists,credit_flow,pmon,
           ssl_connection,tls_connection,ssl_record,tls_record,gen_fsm,ssl]},
      {lazy_queue_explicit_gc_run_operation_threshold,1000},
      {log_levels,[{channel,debug},{connection,info}]},
      {loopback_users,[<<"guest">>]},
      {memory_monitor_interval,2500},
      {mirroring_flow_control,true},
      {mirroring_sync_batch_size,4096},
      {mnesia_table_loading_retry_limit,10},
      {mnesia_table_loading_retry_timeout,30000},
      {msg_store_credit_disc_bound,{4000,800}},
      {msg_store_file_size_limit,16777216},
      {msg_store_index_module,rabbit_msg_store_ets_index},
      {msg_store_io_batch_size,4096},
      {num_ssl_acceptors,1},
      {num_tcp_acceptors,10},
      {password_hashing_module,rabbit_password_hashing_sha256},
      {plugins_dir,
          "/usr/lib/rabbitmq/plugins:/usr/lib/rabbitmq/lib/rabbitmq_server-3.6.9/plugins"},
      {plugins_expand_dir,
          "/var/lib/rabbitmq/mnesia/rabbit@chipp-plugins-expand"},
      {queue_explicit_gc_run_operation_threshold,1000},
      {queue_index_embed_msgs_below,4096},
      {queue_index_max_journal_entries,32768},
      {reverse_dns_lookups,false},
      {sasl_error_logger,{file,"/var/log/rabbitmq/rabbit@chipp-sasl.log"}},
      {server_properties,[]},
      {ssl_allow_poodle_attack,false},
      {ssl_apps,[asn1,crypto,public_key,ssl]},
      {ssl_cert_login_from,distinguished_name},
      {ssl_handshake_timeout,5000},
      {ssl_listeners,[]},
      {ssl_options,[]},
      {tcp_listen_options,
          [{backlog,4096},
           {nodelay,true},
           {linger,{true,0}},
           {exit_on_close,false},
           {sndbuf,196608},
           {recbuf,196608}]},
      {tcp_listeners,[{"192.168.1.224",5672}]},
      {trace_vhosts,[]},
      {vm_memory_high_watermark,0.6},
      {vm_memory_high_watermark_paging_ratio,0.3}]},
 {rabbit_common,[]},
 {rabbitmq_management,
     [{cors_allow_origins,[]},
      {cors_max_age,1800},
      {http_log_dir,none},
      {listener,[{port,15672}]},
      {load_definitions,none},
      {management_db_cache_multiplier,5},
      {process_stats_gc_timeout,300000},
      {stats_event_max_backlog,250}]},
 {rabbitmq_management_agent,
     [{rates_mode,basic},
      {sample_retention_policies,
          [{global,[{605,5},{3660,60},{29400,600},{86400,1800}]},
           {basic,[{605,5},{3600,60}]},
           {detailed,[{605,5}]}]}]},
 {rabbitmq_web_dispatch,[]},
 {ranch,[]},
 {sasl,[{errlog_type,error},{sasl_error_logger,false}]},
 {ssl,[]},
 {stdlib,[]},
 {syntax_tools,[]},
 {xmerl,[]}]
```

 rabbitmqctl status
```
Status of node rabbit@chipp...
[{pid,20764},
 {running_applications,
     [{rabbitmq_management,"RabbitMQ Management Console","3.6.9"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.6.9"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.6.9"},
      {rabbit,"RabbitMQ","3.6.9"},
      {amqp_client,"RabbitMQ AMQP Client","3.6.9"},
      {rabbit_common,
          "Modules shared by rabbitmq-server and rabbitmq-erlang-client",
          "3.6.9"},
      {compiler,"ERTS  CXC 138 10","7.0.4"},
      {cowboy,"Small, fast, modular HTTP server.","1.0.4"},
      {ranch,"Socket acceptor pool for TCP protocols.","1.3.0"},
      {ssl,"Erlang/OTP SSL application","8.1.1"},
      {public_key,"Public key infrastructure","1.4"},
      {cowlib,"Support library for manipulating Web protocols.","1.0.2"},
      {crypto,"CRYPTO","3.7.3"},
      {mnesia,"MNESIA  CXC 138 12","4.14.3"},
      {os_mon,"CPO  CXC 138 46","2.4.2"},
      {xmerl,"XML parser","1.3.13"},
      {asn1,"The Erlang ASN1 compiler version 4.0.4","4.0.4"},
      {syntax_tools,"Syntax tools","2.1.1"},
      {inets,"INETS  CXC 138 49","6.3.6"},
      {sasl,"SASL  CXC 138 11","3.0.3"},
      {stdlib,"ERTS  CXC 138 10","3.3"},
      {kernel,"ERTS  CXC 138 10","5.2"}]},
 {os,{unix,linux}},
 {erlang_version,
     "Erlang/OTP 19 [erts-8.3] [source-d5c06c6] [64-bit] [smp:8:8] [async-threads:128] [hipe] [kernel-poll:true]\n"},
 {memory,
     [{total,1414497584},
      {connection_readers,11462752},
      {connection_writers,1866200},
      {connection_channels,25246672},
      {connection_other,22396568},
      {queue_procs,1011424240},
      {queue_slave_procs,0},
      {plugins,15718072},
      {other_proc,24336008},
      {mnesia,223200},
      {metrics,2163472},
      {mgmt_db,24265776},
      {msg_index,282584},
      {other_ets,5048568},
      {binary,231739096},
      {code,24747054},
      {atom,1033401},
      {other_system,14704561}]},
 {alarms,[]},
 {listeners,
     [{clustering,25672,"::"},{amqp,5672,"192.168.1.224"},{http,15672,"::"}]},
 {vm_memory_high_watermark,0.6},
 {vm_memory_limit,10082237644},
 {disk_free_limit,50000000},
 {disk_free,65727135744},
 {file_descriptors,
     [{total_limit,32668},
      {total_used,365},
      {sockets_limit,29399},
      {sockets_used,353}]},
 {processes,[{limit,1048576},{used,4034}]},
 {run_queue,0},
 {uptime,66222},
 {kernel,{net_ticktime,60}}]
```

[_usr_lib_erlang_erts-8.3_bin_beam.smp.123.crash.zip](https://github.com/rabbitmq/rabbitmq-server/files/1071522/_usr_lib_erlang_erts-8.3_bin_beam.smp.123.crash.zip)

**Comment by lukebakken** [comment]
@lskbr - could you also please provide the `rabbit.log` file?

**Comment by lskbr** [comment]
Here you have the dump file
[erl_crash.zip](https://github.com/rabbitmq/rabbitmq-server/files/1071553/erl_crash.zip)

**Comment by michaelklishin** [comment]
RabbitMQ doesn't have any native code. Feel free to try a different Erlang/OTP version.

**Comment by lskbr** [comment]
I tested with:
esl-erlang_19.2-1~ubuntu~xenial_amd64.deb
and 
esl-erlang_19.3-1~ubuntu~xenial_amd64.deb

The log file is very huge 1.8G.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
@lskbr one hour of logs before the time stamp listed in `dmesg` plus a few minutes of `dmesg` entries would be sufficient.

There are several 19.2.x and 19.3.x releases. Unfortunately both the OTP team has a curious approach to packaging where the original release (e.g. 19.3) is provided as a binary download but subsequent patches are provided as, well, patches. [Erlang Solutions](https://www.erlang-solutions.com/resources/download.html) provides packages the most recent patch version.

There is a [Erlang VM change log](https://github.com/erlang/otp/blob/master/erts/doc/src/notes.xml) entry that in 19.3.3 that mentions an issue memory allocation.

**Comment by lskbr** [comment]
Thx. Please close this issue, as I'm updating Erlang to 19.3.6.
I will open another issue with all required files if it happens again. Thx.

**Comment by michaelklishin** [comment]
@lskbr please open a JIRA ticket with Erlang/OTP as RabbitMQ itself does not allocate memory directly.

**Comment by ankita-anil-verma** [comment]
was this issue resolved?

**Comment by lskbr** [comment]
I’m not aware of this and I stopped using RabbitMq 1 yr ago.

Envoyé de mon iPhone

**Comment by michaelklishin** [comment]
RabbitMQ has no native code. Segfaults in the Erlang runtime are not common but there is no "fix for all of them", so YMMV. Use the [newest Erlang release supported](http://www.rabbitmq.com/which-erlang.html) and likely you will be fine.

**Comment by Pkuutn** [comment]
I have _weird_ segfaults with 3.7.8/OTP 21.1 (Erlang Solutions) - i.e. no faults with perftest load, but 100% reproducable with workload (it's a pre-prod environment, so 10-200 messages per second
Could someone point me to how to locate the RabbitMQ server source code part which is associated with segfault?
kernel: [319434.121690] 1_scheduler[13351]: segfault at 208 ip 000055ce50cb9104 sp 00007f965ce3e9d0 error 4 in beam.smp[55ce50afa000+2dc000]

**Comment by michaelklishin** [comment]
@Pkuutn see the comment above. RabbitMQ does NOT allocate memory directly, the `beam.smp` process is the Erlang runtime.

**Comment by lukebakken** [comment]
@Pkuutn - yes, those segfaults are weird. The source code for the Erlang VM is available here: https://github.com/erlang/otp

Debugging a `segfault` requires building a debug release of Erlang and using that, capturing the core file, and analyzing it with `gdb` or other tools.

Before doing this, I recommend building the absolute latest version of Erlang from source (`21.1.3` at this time) and seeing if that resolves your issue.

I also recommend checking your system logs or `dmesg` (Linux) / system event log (Windows) for clues.
