### ISSUE TITLE
Methods to determine deprecated features in use report incomplete/inaccurate information

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/rabbitmq-server#12619]
### Describe the bug

The command `rabbitmq-diagnostics check_if_any_deprecated_features_are_used` and the API endpoint `/api/deprecated-features/used` do not report accurate information on actual state of the system. The command/endpoint only seem to check for classic queue mirroring, and it doesn't report the state of other deprecated features in use.

### Reproduction steps

1. Start RabbitMQ 4.0.3 (latest at this time): `docker run --name bunny -p 15672:15672 --rm rabbitmq:4.0-management`
2. List deprecated features: `docker exec bunny rabbitmq-diagnostics --formatter=pretty_table list_deprecated_features`
    Observe `transient_nonexcl_queues` as deprecated feature, permitted by default
3. Create a transient non-exclusive classic queue:
    ```
    curl -v -u guest:guest -H "Content-Type: application/json" -d '{"auto_delete":false,"durable":false}' -X PUT http://localhost:15672/api/queues/%2F/myqueue
    ```
4. Query the state of deprecated features used: `curl -v -u guest:guest http://localhost:15672/api/deprecated-features/used`
5. Observe that none `[]` are reported
6. Observe that server logs print __Deprecated features: `transient_nonexcl_queues`: Feature `transient_nonexcl_queues` is deprecated.__
7. Run `docker exec bunny rabbitmq-diagnostics --formatter=pretty_table check_if_any_deprecated_features_are_used`
8. Observe the reported output: `Cluster reported no deprecated features in use`

### Expected behavior

The command `rabbitmq-diagnostics --formatter=pretty_table check_if_any_deprecated_features_are_used` reports that `transient_nonexcl_queues` deprecated feature is used.

The API endpoint `/api/deprecated-features/used` reports that `transient_nonexcl_queues` deprecated feature is used.

### Additional context

Setting `deprecated_features.permit.transient_nonexcl_queues = false` causes the queue declare operation to fail right away.

**Comment by michaelklishin** [comment]
It's the CLI command that specifically only checks for CMQs.

**Comment by Zerpet** [comment]
> It's the CLI command that specifically only checks for CMQs.

Strange, I can reproduce the issue using the HTTP API as well 😕

**Comment by michaelklishin** [comment]
Maybe the HTTP API endpoints do the same thing, the CLI command was the first thing I've taken a look at.

**Comment by dumbbell** [comment]
Adding a `is_feature_used` callback to `transient_nonexcl_queues` is enough to have it listed in the API enpoint:
```json
[
  {
    "name": "transient_nonexcl_queues",
    "desc": "",
    "deprecation_phase": "permitted_by_default",
    "doc_url": "https://blog.rabbitmq.com/posts/2021/08/4.0-deprecation-announcements/#removal-of-transient-non-exclusive-queues",
    "provided_by": "rabbit"
  }
]
```

It is not enough for the CLI command though, so it must not call the deprecated feature subsystem correctly.

**Comment by Zerpet** [comment]
@dumbbell I built the broker after merging both PRs locally, run the same commands as in the OP, and I got the expected result 👍 I'll defer the approval of the PRs to other folks more experienced with Erlang code.

**Comment by michaelklishin** [comment]
@dumbbell any reason not to backport #12675 #12674 to `v4.0.x`?

**Comment by dumbbell** [comment]
> @dumbbell any reason not to backport #12675 #12674 to `v4.0.x`?

To me, it’s bug and should be backported. I will set the labels accordingly.

**Comment by dumbbell** [comment]
Thank you for reviewing and merging!
