### ISSUE TITLE
export_all in rabbit_variable_queue breaks compilation in Erlang 20

### ISSUE THREAD

**Issue by goncalotomas** [rabbitmq/rabbitmq-server#1272]
Erlang 20 generates a warning when `export_all` is used inside a module. It is used at least in `rabbit_variable_queue.erl:362`. The proposed workaround to the warning is to use the `nowarn_export_all` flag, but removing the `warnings_as_errors` would also "fix" the compilation issue.
I as not able to submit a pull request with the `nowarn_exportall` approach because I don't understand where you'd add this particular flag without a rebar.config file.

Here is the official statement of the new warning from the Erlang 20 Release notes:

               OTP-14071    Application(s): compiler, stdlib

               By default, there will now be a warning when export_all
               is used. The warning can be disabled using
               nowarn_export_all.

**Comment by michaelklishin** [comment]
@goncalotomas thanks. We've been working on OTP 20 compatibility for about a month now and have never observed this. Can you please clarify how are you building the server?

RabbitMQ uses a patched version of erlang.mk, not rebar.

**Comment by michaelklishin** [comment]
Related to #1243.

**Comment by michaelklishin** [comment]
So the line was introduced in https://github.com/rabbitmq/rabbitmq-server/commit/492e23bf188820756e07076c4539692376cfcbc6 and [not present in `stable`](https://github.com/rabbitmq/rabbitmq-server/blame/stable/src/rabbit_variable_queue.erl).

I suspect it was added for more convenient debugging from the shell and can be removed.

**Comment by michaelklishin** [comment]
Managed to reproduce it with a clean umbrella clone.

**Comment by goncalotomas** [comment]
Having installed Erlang 20, I just cloned the repository and ran `make`.
