### ISSUE TITLE
MQTT 5.0: Connection close on non-authorized topic subscription attempt

### ISSUE THREAD

**Issue by AntonSmolkov** [rabbitmq/rabbitmq-server#12742]
### Describe the bug

The broker closes the MQTT connection when attempting to subscribe to a topic that is not allowed at the topic permissions level.

For example, with the following C# code, the entire connection is closed shortly after line 2:

```csharp
// GrantedQos0
await mqttClient.SubscribeAsync("allowed_topic", MqttQualityOfServiceLevel.AtMostOnce);
// NotAuthorized 
await mqttClient.SubscribeAsync("denied_topic", MqttQualityOfServiceLevel.AtMostOnce); 
// GrantedQos0 (not works with RabbitMQ)
await mqttClient.SubscribeAsync("allowed_topic_another", MqttQualityOfServiceLevel.AtMostOnce); 
```
Wireshark looks like this: _(notice Reason Code column)_
![image](https://github.com/user-attachments/assets/e796d28a-cc90-4cef-919e-bf80cdc38691)

RabbitMq logs report `subscribe_error` on connection:

```bash
rabbit-1  | 2024-11-16 12:45:34.588125+00:00 [debug] <0.989.0> User 'user1' authenticated successfully by backend rabbit_auth_backend_internal
rabbit-1  | 2024-11-16 12:45:34.588474+00:00 [info] <0.989.0> Accepted MQTT connection 127.0.0.1:58966 -> 127.0.0.1:1883 for client ID my-pod-name8
rabbit-1  | 2024-11-16 12:45:36.524394+00:00 [debug] <0.989.0> Received a SUBSCRIBE with subscription(s) [{mqtt_subscription,
rabbit-1  | 2024-11-16 12:45:36.524394+00:00 [debug] <0.989.0>                                             <<"allowed_topic">>,
rabbit-1  | 2024-11-16 12:45:36.524394+00:00 [debug] <0.989.0>                                             {mqtt_subscription_opts,0,false,
rabbit-1  | 2024-11-16 12:45:36.524394+00:00 [debug] <0.989.0>                                              false,0,undefined}}]
rabbit-1  | 2024-11-16 12:45:38.104373+00:00 [debug] <0.989.0> Received a SUBSCRIBE with subscription(s) [{mqtt_subscription,
rabbit-1  | 2024-11-16 12:45:38.104373+00:00 [debug] <0.989.0>                                             <<"denied_topic">>,
rabbit-1  | 2024-11-16 12:45:38.104373+00:00 [debug] <0.989.0>                                             {mqtt_subscription_opts,0,false,
rabbit-1  | 2024-11-16 12:45:38.104373+00:00 [debug] <0.989.0>                                              false,0,undefined}}]
rabbit-1  | 2024-11-16 12:45:38.105474+00:00 [error] <0.989.0> MQTT topic access refused: read access to topic 'denied_topic' in exchange 'amq.topic' in vhost 'mqtt' refused for user 'user1'
rabbit-1  | 2024-11-16 12:45:38.105653+00:00 [error] <0.989.0> Failed to add binding between exchange 'amq.topic' in vhost 'mqtt' and queue 'mqtt-subscription-my-pod-name8qos0' in vhost 'mqtt' for topic filter denied_topic: access_refused
rabbit-1  | 2024-11-16 12:45:38.105786+00:00 [error] <0.989.0> MQTT protocol error on connection 127.0.0.1:58966 -> 127.0.0.1:1883: subscribe_error
```
As far as i understand, this behavior doesn't complain to the MQTT5 standard.

For instance, the same code/approach, works fine with **EMQX** broker:
![image](https://github.com/user-attachments/assets/ee773a92-e629-412d-bfad-10f072ce2b6e)

Not an Erlang expert, but seems like the problem is somewhere [in this part of the code](https://github.com/rabbitmq/rabbitmq-server/blob/v4.0.3/deps/rabbitmq_mqtt/src/rabbit_mqtt_processor.erl#L435)

### Reproduction steps

1. Create user in the befault or any other auth backend
2. Grant ACL permision `.* .* .*` to the user 
3. Grant `^allowed_topic.*` read/write topic permission
4. Create MQTT Connection, subscribe to `allowed_topic` (sucess)
5. Subscribe to any other topic e.g. `denied_topic`
6. Connection is closed

### Expected behavior

The connection remains open, allowing further subscriptions to other allowed topics.

### Additional context

RabbitMQ 4.0.3

**Comment by michaelklishin** [comment]
Thank you for providing details and a traffic capture. According to the stack trace, the code that handles a `SUBSCRIBE` frame does not expect errors related to insufficient permissions.

**Comment by ansd** [comment]
> As far as i understand, this behavior doesn't complain to the MQTT5 standard.

@AntonSmolkov Where in the MQTT 5.0 spec do you read this?

> Expected behavior
The connection remains open, allowing further subscriptions to other allowed topics.

In its current implementation, RabbitMQ closes the MQTT connection if an authorisation check fails. This is done intentionally and is in line with how RabbitMQ behaves with other protocols such as AMQP 1.0 and AMQP 0.9.1.

Note that RabbitMQ complies with the following MQTT 5.0 requirement by sending the SUBACK packet before closing the connection as shown in your Wireshark capture above:

> When the Server receives a SUBSCRIBE packet from a Client, the Server MUST respond with a SUBACK packet [MQTT-3.8.4-1].
