### ISSUE TITLE
DQT defined in `rabbitmq.conf` is not injected into exported definitions

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/rabbitmq-server#12776]
default_queue_type is not reflected in definitions export nor /api/vhosts. Additionally, it seems ineffective in 3.13.

Affected versions: 3.13, 4.0, main.

Reproduction steps:

```
echo 'default_queue_type = quorum' > /tmp/dqt.conf
make run-broker RABBITMQ_CONFIG_FILE=/tmp/dqt.conf

# export_definitions doesn't mention DQT
rabbitmqctl export_definitions - | jq | rg quorum

# /api/vhosts returns DQT as undefined
curl -u guest:guest -s localhost:15672/api/vhosts | jq | rg default_queue_type
    "default_queue_type": "undefined",

# the setting is effective nonetheless
rabbitmqadmin declare queue name=foo
rabbitmqctl -q list_queues name type
name	type
foo	quorum
```

On v3.13.x, I get `foo classic` in that last command, so it seems like
`default_queue_type` is not being applied at all. `rabbitmqctl environment`
returns `{default_queue_type,rabbit_quorum_queue}` as expected.

**Comment by michaelklishin** [comment]
@mkuratczyk it will be effective for virtual hosts that have at least some metadata. It also can be configured per virtual host in 3.13.x and this is not a problem in `4.0.x`.

As for injecting the default into definitions, we already do this for `GET /api/queues/{vhost}`  and such, so it makes sense.

**Comment by michaelklishin** [comment]
I a have a prototype for `GET /api/vhosts` and an individual virtual host but definitions have proven to be more time consuming, so it will have to wait till next week.
