### ISSUE TITLE
Querying individual nodes path of the API for socket statistics data outputs always 0

### ISSUE THREAD

**Issue by jgkirschbaum** [rabbitmq/rabbitmq-server#12871]
### Describe the bug

Querying individual nodes path of the API for socket statistics data outputs always 0.

### Reproduction steps

`curl -su apiuser:apipassword https://rabbitmq-server-0.rabbitmq-nodes.rabbitmq/api/nodes/rabbit@rabbitmq-server-0.rabbitmq-nodes.rabbitmq | jq '.sockets_total,.sockets_used'`
outputs always
```
0
0
```
for `sockets_total` and `sockets_used`.

### Expected behavior

Report correct values for `sockets_total` and `sockets_used`.

### Additional context

Works correct in RabbitMQ v3.13.7.

**Comment by mkuratczyk** [comment]
This is an intentional change that falls under the "Several Disk I/O-Related Metrics were Removed" part of 4.0 release notes.
These days, you can just set a high limit of file descriptors and be done with it and if you want to monitor the exact usage, you can do this on the system level.

**Comment by jgkirschbaum** [comment]
Thank you for the quick response.

**Comment by michaelklishin** [comment]
Here's the [relevant documentation section](https://www.rabbitmq.com/docs/networking#tuning-for-large-number-of-connections) just FTR.
