### ISSUE TITLE
rabbitmq-script-wrapper: "exec" before "su rabbitmq ..." is useless

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#129]
In ec851de0e9a9d70620aacef5ad59592fbea75c81, I prefixes all commands with `exec` to stay in the same process (and not fork a new one). This is useless in front of `su rabbitmq -c '...'` because su(1) forks a process anyway.

This broke RabbitMQ's Docker image, something this commit was supposed to fix... Let's remove `exec` before `su`.

This is part of issue #113.

**Comment by dumbbell** [comment]
@tianon, any opinion on this branch (regarding your comment on @ec851de0)?

**Comment by tianon** [comment]
Sorry, :+1:; `su` does strange things.

**Comment by dumbbell** [comment]
Since RabbitMQ 3.5.0.
