### ISSUE TITLE
CLI tools: consider using `sudo` instead of `su`

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#1292]
See https://github.com/rabbitmq/rabbitmq-server-release/issues/32#issuecomment-315720890 and https://bugzilla.redhat.com/show_bug.cgi?id=1426600 for context.

This issue is about investigating if we can switch to `sudo` to accommodate SELinux on RHEL/CentOS 7.

**Comment by michaelklishin** [comment]
So far we think this is feasible but `sudo` introduces a new package dependency ([Ubuntu](https://packages.ubuntu.com/search?keywords=sudo), [Debian stable](https://packages.debian.org/search?keywords=sudo&searchon=names&suite=stable&section=all)), [RPM-based distros](http://rpmfind.net/linux/rpm2html/search.php?query=sudo).

**Comment by lukebakken** [comment]
Riak used `sudo` which caused trouble due to the packaging requirements as you point out. In addition, multiple customers complained about having the command present at all.

**Comment by michaelklishin** [comment]
I could find [earlier discussions](https://groups.google.com/forum/#!topic/rabbitmq-users/yDkUA-81MRw) of this plus similar issues reported for other projects. Looks like the issue should be fixed on the distribution end instead of every individual tool. `su` is not an unreasonable requirement for `rabbitmqctl`.
