### ISSUE TITLE
Memory footprint breakdown doesn't match total

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#1294]
In rabbitmq/rabbitmq-management@4af7b63dbed5577ee5c2be0cb86c911ba0662490, I commented out an assertion in the `memory_test` testcase because the memory breakdown reported by the broker is inconsistent.

The individual counters don't match `total` when we add them. The reason is that in 0872a15a050176ab7598bc3d1b21a2d5c5af3052, `total` is the OS process resident memory footprint (i.e. pages in physical memory, not counting paged out memory), but the individual counters correspond to memory allocated by Erlang.

We need to either report `erlang:memory(total)` as `total` again, remove/rename `total` so that it doesn't gives the impression it is the sum of individual counters, or remove the assertion.

**Comment by michaelklishin** [comment]
Yes, with RSS used to compute total we've seen enough cases where the new [OS] total does not match the [runtime-reported] breakdown. Simply dropping the assertion as something that's no longer relevant makes sense to me.
