### ISSUE TITLE
Error in rabbitmq.conf.example

### ISSUE THREAD

**Issue by arch273** [rabbitmq/rabbitmq-server#1330]
http://next.rabbitmq.com/management.html#configuration says to use "day" but the example config file uses "24hours".  Using "24hours" produces a badarg error.  "minute" "hour" "day" and "10" appear to work fine.

`Config file generation failed 
13:55:08.304 [error] Error generating configuration in phase apply_translations
13:55:08.305 [error] Error running translation for rabbitmq_management.sample_retention_policies, [error, badarg]`

https://github.com/rabbitmq/rabbitmq-server/blob/c8de5f78d736a952b7bd620570a21c95e4277fda/docs/rabbitmq.conf.example#L471-L474

**Comment by michaelklishin** [comment]
[rabbitmq-management config schema](https://github.com/rabbitmq/rabbitmq-management/blob/master/priv/schema/rabbitmq_management.schema) confirms your findings. It should be `day`.
