### ISSUE TITLE
operation queue.declare caused a channel exception not_found

### ISSUE THREAD

**Issue by bohea** [rabbitmq/rabbitmq-server#1333]
RabbitMQ 3.6.10
Erlang 19.3.6.2

=ERROR REPORT==== 17-Aug-2017::12:22:53 ===
Channel error on connection <0.754.0> 
operation queue.declare caused a channel exception not_found: failed to perform operation on queue 'x1' in vhost 'prod' due to timeout
-----------------------------------------------------------------------
No consumer can listen to this queue

restart rabbitmq: tried, no luck, same error
delete queue 'x1': tried, no luck, same error
delete vhost 'prod' and recreate same vhost: tried, no luck, same error

meantime other queues on this very vhost works good
![qq 20170817123951](https://user-images.githubusercontent.com/6581649/29396241-3dde808a-8349-11e7-99b8-63906fd1465d.png)

**Comment by lukebakken** [comment]
Hello!

In the future, post questions with information to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list. GitHub is used for bugs and other development-related items, not for general discussion or diagnosis.

Having said that, you should be able to delete this queue using this command:

```
rabbitmqctl eval 'rabbit_amqqueue:internal_delete({resource,<<"prod">>,queue,<<"x1">>}).'
```

Thanks -
Luke

**Comment by phygerr** [comment]
share one solution in my openstack environment，a problem has occurred in vhost /neutron ,lastly we use `curl -X DELETE -u admin:admin "http://192.168.1.1:15672/api/queues/%2Fneutron/q-agent-notifier-tunnel-delete"` delete the not found queue and resolved the problem.

also u can use 
```bash
curl -u admin:admin http://192.168.1.:15672/api/queues
./rabbitmqadmin -H http://192.168.1.1 list queues -u admin -p admin
./rabbitmqadmin -H http://192.168.1.1 list queues  -u admin -p admin |grep neutron
```
try to delete the not found queues to resolve problem.
