### ISSUE TITLE
Install the latest RabbitMQ 3.6.11 exception Erlang-19.0.4-1.el7.centos.x86_64.rpm

### ISSUE THREAD

**Issue by 501956430** [rabbitmq/rabbitmq-server#1336]
Install the latest RabbitMQ 3.6.11 exception
Erlang-19.0.4-1.el7.centos.x86_64.rpm

![qq 20170822164025](https://user-images.githubusercontent.com/20204491/29556496-9f132db6-8758-11e7-8883-3de6e4782471.png)

**Comment by Gsantomaggio** [comment]
Hi @501956430 
Please post this question and this information to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list. GitHub is used for bugs and other development-related items, not for general discussion or diagnosis.

**Comment by Gsantomaggio** [comment]
Tried on:
```
cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
```

With:

```
-rw-rw-r--. 1 vagrant vagrant 18580960 Aug 15  2016 erlang-19.0.4-1.el7.centos.x86_64.rpm
-rw-rw-r--. 1 vagrant vagrant  4963465 Aug 16 13:34 rabbitmq-server-3.6.11-1.el7.noarch.rpm
```

It works without problems.
```
sudo systemctl status rabbitmq-server
● rabbitmq-server.service - RabbitMQ broker
   Loaded: loaded (/usr/lib/systemd/system/rabbitmq-server.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-08-22 11:41:05 UTC; 5min ago
 Main PID: 12767 (beam)
   Status: "Initialized"
   CGroup: /system.slice/rabbitmq-server.service
           ├─12767 /usr/lib64/erlang/erts-8.0.3/bin/beam -W w -A 64 -P 1048576 -t 5000...
           ├─12909 /usr/lib64/erlang/erts-8.0.3/bin/epmd -daemon
           ├─13008 erl_child_setup 1024
           ├─13015 inet_gethost 4
           └─13016 inet_gethost 4
```

It'd be useful to have your logs, and the OS details

**Comment by michaelklishin** [comment]
See server and system logs. Very likely it's our good old friend SELinux (https://github.com/rabbitmq/rabbitmq-server-release/issues/39 and no shortage of mailing list threads).
