### ISSUE TITLE
rabbitmq 3.3.5 can't config automaticly start at boot on centos7

### ISSUE THREAD

**Issue by 564064202** [rabbitmq/rabbitmq-server#1351]
I have tried too many times,but I failed. I run order in shell ,it works,
but I write it to
 **supervisor**
 or
 **/etc/rc.d/init.d/functions** 
or 
**udo systemctl enable  rabbitmq-server**

all failed.!!!!!!!!!!!!!!!!!!!!!!!!!! 

can you help me

**Comment by Gsantomaggio** [comment]
@564064202 
Thank you for your time

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

**Comment by 564064202** [comment]
@Gsantomaggio I am so sorry I can't post it there,because I am in China,And our country forbidden use google domain ....

[http://images2017.cnblogs.com/blog/83201/201709/83201-20170905163511116-878346723.png](url)

**Comment by 564064202** [comment]
http://images2017.cnblogs.com/blog/83201/201709/83201-20170905163511116-878346723.png

**Comment by 564064202** [comment]
@Gsantomaggio hello

**Comment by Gsantomaggio** [comment]
@564064202 I already posted an answer on stackoverflow:
https://stackoverflow.com/questions/46049536/how-i-can-make-rabbitmq-server-auto-start-at-boot-timecentos-7

If you can't use the google group, please use stackoverflow
Thank you
