### ISSUE TITLE
Please create official rabbitmq windows docker image like linux

### ISSUE THREAD

**Issue by AceHack** [rabbitmq/rabbitmq-server#1353]
So I was able to get erlang and rabbitmq working on the latest preview of windows nanoserver insider edition. It's a bit kludgy but it's working!!!
I guess microsoft added whatever was missing in the latest edition to make things work.
Hope this image can help someone else.
You can type "build-image.cmd" to create the docker image
"run-containers.cmd" will startup two instance of rabbit one with host name "rabbitmq" and one with host name "joinmq"
One interesting thing here is the .erlang.cookie file. I had to do some playing to get the two rabbits to have the same .erlang.cookie file but not embed it in the image so it could be replaced at runtime.
"log-containers.cmd" will show you once the rabbit images have started fully (Would be real nice to have the RABBITMQ_LOGS=- logs here working on windows).
"join-cluster.cmd" will join the two instances into a cluster.

It would be great to see an officially supported windows docker container from rabbit

[rabbitmq-nanoserver-insider.zip](https://github.com/rabbitmq/rabbitmq-server/files/1286541/rabbitmq-nanoserver-insider.zip)

**Comment by michaelklishin** [comment]
[RabbitMQ Docker image](https://hub.docker.com/_/rabbitmq/) is maintained by Docker, Inc. We only provide examples for [rabbitmq-autocluster](https://github.com/rabbitmq/rabbitmq-autocluster) and related 3.7.0 plugins.

**Comment by michaelklishin** [comment]
[Here's the repository](https://github.com/docker-library/rabbitmq/).
