### ISSUE TITLE
Support no-local flag in basic.consume

### ISSUE THREAD

**Issue by sigiesec** [rabbitmq/rabbitmq-server#1361]
According to https://www.rabbitmq.com/specification.html,
> The no-local parameter is not implemented. The value of this parameter is ignored and no attempt is made to prevent a consumer from receiving messages that were published on the same connection.

It would be great if this feature were implemented by rabbitmq-server. Otherwise applications may need to implement that feature on the client side, and filter messages after they have been received from the broker, rather than preventing them to be transferred at all.

**Comment by michaelklishin** [comment]
@sigiesec possibly but in 10 years of RabbitMQ history this is maybe 3rd time I recall someone asking for it. Our small team has much higher priorities (that we are asked about every day), so at this point it's a `wontfix`.

**Comment by sigiesec** [comment]
@michaelklishin I can understand this is not a priority for your team. But I don't understand that you are closing the ticket. Keeping it open will allow to track that it is open, both for people from the community interested in the feature as well as maybe someone from the community who will work on it (I cannot promise but it might be that me or some colleague of mine might work on this).

**Comment by michaelklishin** [comment]
@sigiesec primarily because our team won't get to this any time soon, possibly at all. That doesn't mean that we wouldn't consider a contribution (or this issue won't be reopened should something change in our opinion or priorities).
