### ISSUE TITLE
"rabbitmqctl stop" should always exit with 0

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#1362]
Here's an example where `beam.smp` segfaulted. It appears that `systemd` attempted to use `rabbitmqctl` to gracefully bring down an already dead process:

```
Sep  5 03:59:15 ip-10-1-45-208 kernel: 1_scheduler[11717]: segfault at f0 ip 00000000004d189c sp 00007f58522be9e0 error 6 in beam.smp[400000+2cb000]
Sep  5 03:59:15 ip-10-1-45-208 systemd: rabbitmq-server.service: main process exited, code=killed, status=11/SEGV
Sep  5 03:59:15 ip-10-1-45-208 rabbitmqctl: Stopping and halting node 'rabbit@ip-10-1-45-208.ec2.internal' ...
Sep  5 03:59:15 ip-10-1-45-208 rabbitmqctl: Error: unable to connect to node 'rabbit@ip-10-1-45-208.ec2.internal': nodedown
Sep  5 03:59:15 ip-10-1-45-208 rabbitmqctl: DIAGNOSTICS
Sep  5 03:59:15 ip-10-1-45-208 rabbitmqctl: ===========
Sep  5 03:59:15 ip-10-1-45-208 rabbitmqctl: attempted to contact: ['rabbit@ip-10-1-45-208.ec2.internal']
Sep  5 03:59:15 ip-10-1-45-208 rabbitmqctl: rabbit@ip-10-1-45-208.ec2.internal:
Sep  5 03:59:15 ip-10-1-45-208 rabbitmqctl: * connected to epmd (port 4369) on ip-10-1-45-208.ec2.internal
Sep  5 03:59:15 ip-10-1-45-208 rabbitmqctl: * epmd reports: node 'rabbit' not running at all
Sep  5 03:59:15 ip-10-1-45-208 rabbitmqctl: no other nodes on ip-10-1-45-208.ec2.internal
Sep  5 03:59:15 ip-10-1-45-208 rabbitmqctl: * suggestion: start the node
Sep  5 03:59:15 ip-10-1-45-208 rabbitmqctl: current node details:
Sep  5 03:59:15 ip-10-1-45-208 rabbitmqctl: - node name: 'rabbitmq-cli-88@ip-10-1-45-208.ec2.internal'
Sep  5 03:59:15 ip-10-1-45-208 rabbitmqctl: - home dir: .
Sep  5 03:59:15 ip-10-1-45-208 rabbitmqctl: - cookie hash: /4YNV3w43TXn9+9e0suIUQ==
Sep  5 03:59:15 ip-10-1-45-208 systemd: Unit rabbitmq-server.service entered failed state.
Sep  5 03:59:15 ip-10-1-45-208 systemd: rabbitmq-server.service failed.
```

We may wish to configure `systemd` to not try to gracefully stop RabbitMQ when the exit code is 11.

This is tangentially related to #1359

**Comment by hairyhum** [comment]
Should we instead consider `rabbitmqctl stop` successful if the node is not running?

**Comment by michaelklishin** [comment]
making `rabbitmqctl stop` idempotent is an option for `3.7.0`.

**Comment by hairyhum** [comment]
Sorry, the exit code from `rabbitmqctl stop` command is 0 in `stable` https://github.com/rabbitmq/rabbitmq-server/commit/9cfd5bd64edd527db418ea2cbbb35d53054bfad5 . 
And it was changed to 69 in `master`. 
I'm not sure why does the service fail then.

**Comment by michaelklishin** [comment]
So far there is no consensus on whether `rabbitmqctl stop` should be idempotent, so we need an alternative solution (such as making systemd ignore certain exit codes).

**Comment by lukebakken** [comment]
I'll look into it more, though I'm pretty sure systemd is always going to run the `ExecStop` command. Now that I've read more of the docs the exit code of that command is possibly ignored.

**Comment by lukebakken** [comment]
@michaelklishin @hairyhum  - after further investigation, there isn't anything else necessary to be done. If RabbitMQ exits due to `SIGABRT` we know `rabbitmqctl stop` will fail. But, `systemd` does not take the exit code of the `ExecStop` command into account, only the exit code of the monitored process. This is what threw me for a loop earlier. Since we have modified our `systemd` configuration to restart RabbitMQ in `on-failure` scenarios, we should be all set.

**Comment by lukebakken** [comment]
See #693 for some history.

**Comment by lukebakken** [comment]
Closing the issue because it is not an accurate description of the problem that needs to be addressed.
