### ISSUE TITLE
Don't log an empty message

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#1364]
Report from a user via `rabbitmq-users` mailing list:

This is super minor, but I think it could be improved: enabling a plugin will trigger the stopping message, even though no applications are being stopped. 

As an example, here I'm running `rabbitmq-plugins enable rabbitmq_mqtt` and the following will be printed out: 

```
=INFO REPORT==== 15-Sep-2017::21:05:47 === 
Stopping RabbitMQ applications and their dependencies in the following order: 

=INFO REPORT==== 15-Sep-2017::21:05:47 === 
Plugins changed; enabled [rabbitmq_mqtt], disabled [] 
```

https://groups.google.com/d/topic/rabbitmq-users/Qfs7biioRyw/discussion

**Comment by johanrhodin** [comment]
Thanks guys, nice improvements! Will try when `3.6.13` is released.
