### ISSUE TITLE
Consider reducing flow status threshold

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#138]
Currently connections and channels would report itself as "blocked by credit flow" if they were blocked in the last 5 seconds. This means that in some environments, it may seem to an operator like they are in flow control permanently, even though they go in and out of the blocked state many times a second under high load.

We should consider adjusting the threshold to, say, 1 second.

**Comment by dumbbell** [comment]
One question before I merge the branch. IIRC, the management UI is refreshed every 5": could this change lead to connections/channels to appear as always running, even if they were in flow in the past 5"? I mean, could we end up in the opposite situation: currently it gives the impression connections/channels are always in flow, but with the change, it gives the impression they are never in flow?

**Comment by michaelklishin** [comment]
That's why we have an issue for adding a ratio. If alarm-driven flow is not in affect, the UI should not emphasize credit flow because it is transient and not displayed accurately with the current approach.

You should still notice resource-driven alarms just as easily with this change.

**Comment by dumbbell** [comment]
Yes, I agree the current UI does not convey the information appropriately.
