### ISSUE TITLE
Bug with greedy # route key binding

### ISSUE THREAD

**Issue by lamchakchan** [rabbitmq/rabbitmq-server#1383]
There is a bug with the `#` greedy multi word wild card.  When a pattern of `a.#.b` is created as binding between a topic exchange and a queue.  It routes a message with key of `a.b`.

**Comment by michaelklishin** [comment]
[Section 3.1.3.3 of the spec](http://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf) says that the `#` wildcard matches 0 or more segments. There are only a handful of examples in the spec so it’s not really clear whether it should match the way it does in your case. At this point subtle and not commonly reported edge cases like this one are not worth the risk of behavior changes for existing in stallations.

**Comment by michaelklishin** [comment]
If you consider your examples in terms of segments, they become:

 * Binding [routing] key: `a, #, b`
 * Message routing key: `a, b`

Since `#` matches 0 or more segments, this example works as it should if you ask me.

**Comment by lamchakchan** [comment]
I don't think this makes sense.  `#` allows for 0 to many words.  Using dots (`.`) as separators, what is the rule set that allows this operator to take in separators.  From real world observations for this case, I've seen this.

* binding : `a.#.b`
* routable keys : `a..b`, `a.b`, `a.x.b`
* non-routable keys: `ab`

From your interpretation, `#` should be greedy enough to eat up all separators.  I would also assumed after reading your thoughts (which makes sense), `ab` is allowable.

**Comment by lamchakchan** [comment]
I'm also finding discrepancy between for the `*` wild card as well.  

* binding : `a.*.b`
* routable keys : `a..b`, `a.x.b`
* non-routable keys: `a.b`

From section `3.1.3.3` as well

> The routing pattern follows the same rules as the routing key with the addition that * matches a single word, and # matches zero or more words. Thus the routing pattern `*.stock.#` matches the routing keys `usd.stock` and `eur.stock.db` but not stock.nasdaq.

**Comment by lamchakchan** [comment]
I'm not for fixing this as your said, this might break existing users.  I just need some clarity on syntax and the expected behavior of result within the documentation so I can base my implementation off of.

**Comment by michaelklishin** [comment]
@lamchakchan `a.*.b` is `a, *, b` in terms of segments, so it is not expected to match `a.b`. I don't know if `a..b` should even be a legal pattern but the spec provides no clarification. It is treated as a `a, (empty string), b` and therefore matches. 

Our team does not use GitHub issues for discussions, investigations, RCA and so on. Please start a mailing list thread if you have further questions.
