### ISSUE TITLE
rabbitmq-server crashed 

### ISSUE THREAD

**Issue by folt** [rabbitmq/rabbitmq-server#1385]
Аll worked well, but tonight rabbitmq-server stopped working with such message:
`Error in log handler

```
Event: {error,<0.214.0>,
           {<0.259.0>,
            "** Generic server ~p terminating \n** Last message in was ~p~n** When Server state == ~p~n** Reason for termination == ~n** ~p~n",
            [rabbit_node_monitor,ping_up_nodes,
             {state,
                 {state,
                     {dict,0,16,16,8,80,48,
                         {[],[],[],[],[],[],[],[],...},
                         {{[],[],[],[],[],[],...}}},
                     erlang},
                 [],
                 {state,
                     {dict,0,16,16,8,80,48,
                         {[],[],[],[],[],[],...},
                         {{[],[],[],[],...}}},
                     erlang},
                 undefined,
                 {erlang,#Ref<0.0.1.86626>},
                 not_healing,
                 <<8,99,36,25,77,31,158,134,18,64,197,232,...>>,
                 []},
             {{aborted,
                  {bad_config,dir,
                      "/usr/local/var/lib/rabbitmq/mnesia/server_node@localhost"}},
              [{mnesia,abort,1,[{file,"mnesia.erl"},{line,318}]},
               {rabbit_node_monitor,cluster_status_filename,0,
                   [{file,"src/rabbit_node_monitor.erl"},{line,98}]},
               {rabbit_node_monitor,read_cluster_status,0,
                   [{file,"src/rabbit_node_monitor.erl"},{line,143}]},
               {rabbit_mnesia,cluster_status,1,
                   [{file,"src/rabbit_mnesia.erl"},{line,415}]},
               {rabbit_node_monitor,alive_nodes,0,
                   [{file,"src/rabbit_node_monitor.erl"},{line,876}]},
               {rabbit_node_monitor,handle_info,2,
                   [{file,"src/rabbit_node_monitor.erl"},{line,623}]},
               {gen_server,try_dispatch,4,
                   [{file,"gen_server.erl"},{line,601}]},
               {gen_server,handle_msg,5,
                   [{file,"gen_server.erl"},{line,667}]}]}]}}
Error: badarg
Stack trace: [{ets,lookup,
                  [rabbit_exchange,
                   {resource,<<"/">>,exchange,<<"amq.rabbitmq.log">>}],
                  []},
              {rabbit_misc,dirty_read,1,
                  [{file,"src/rabbit_misc.erl"},{line,390}]},
              {rabbit_basic,publish,1,
                  [{file,"src/rabbit_basic.erl"},{line,109}]},
              {rabbit_error_logger,publish1,4,
                  [{file,"src/rabbit_error_logger.erl"},{line,104}]},
              {rabbit_error_logger,handle_event0,2,
                  [{file,"src/rabbit_error_logger.erl"},{line,80}]},
              {rabbit_error_logger_file_h,safe_handle_event,3,
                  [{file,"src/rabbit_error_logger_file_h.erl"},{line,121}]},
              {gen_event,server_update,4,[{file,"gen_event.erl"},{line,533}]},
              {gen_event,server_notify,4,[{file,"gen_event.erl"},{line,515}]}]

Error in log handler
====================
Event: {warning_msg,<0.214.0>,
                    {<0.253.0>,
                     "epmd does not know us, re-registering ~s at port ~b~n",
                     ["server_node",25672]}}
Error: badarg
Stack trace: [{ets,lookup,
                  [rabbit_exchange,
                   {resource,<<"/">>,exchange,<<"amq.rabbitmq.log">>}],
                  []},
              {rabbit_misc,dirty_read,1,
                  [{file,"src/rabbit_misc.erl"},{line,390}]},
              {rabbit_basic,publish,1,
                  [{file,"src/rabbit_basic.erl"},{line,109}]},
              {rabbit_error_logger,publish1,4,
                  [{file,"src/rabbit_error_logger.erl"},{line,104}]},
              {rabbit_error_logger,handle_event0,2,
                  [{file,"src/rabbit_error_logger.erl"},{line,80}]},
              {rabbit_error_logger_file_h,safe_handle_event,3,
                  [{file,"src/rabbit_error_logger_file_h.erl"},{line,121}]},
              {gen_event,server_update,4,[{file,"gen_event.erl"},{line,533}]},
              {gen_event,server_notify,4,[{file,"gen_event.erl"},{line,515}]}]
```

Error in log handler
```
Event: {error,<0.214.0>,
           {<0.253.0>,
            "** Generic server ~p terminating \n** Last message in was ~p~n** When Server state == ~p~n** Reason for termination == ~n** ~p~n",
            [rabbit_epmd_monitor,check,
             {state,
                 {erlang,#Ref<0.0.1.84860>},
                 erl_epmd,"server_node","localhost",25672},
             {emfile,
                 [{erlang,open_port,
                      [{spawn_executable,
                           "/usr/local/Cellar/erlang@19/19.3/lib/erlang/erts-8.3/bin/erl"},
                       [{args,
                            ["-sname","epmd-starter-855805092","-noshell",
                             "-eval","halt()."]},
                        exit_status,stderr_to_stdout,use_stdio]],
                      []},
                  {rabbit_nodes,ensure_epmd,0,
                      [{file,"src/rabbit_nodes.erl"},{line,224}]},
                  {rabbit_epmd_monitor,check_epmd,1,
                      [{file,"src/rabbit_epmd_monitor.erl"},{line,94}]},
                  {rabbit_epmd_monitor,handle_info,2,
                      [{file,"src/rabbit_epmd_monitor.erl"},{line,69}]},
                  {gen_server,try_dispatch,4,
                      [{file,"gen_server.erl"},{line,601}]},
                  {gen_server,handle_msg,5,
                      [{file,"gen_server.erl"},{line,667}]},
                  {proc_lib,init_p_do_apply,3,
                      [{file,"proc_lib.erl"},{line,247}]}]}]}}
Error: badarg
```
How to be?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
You have a number of exceptions in these logs that are not necessarily related but two of them might have the same root cause:

 * One is a `badarg` from an internal table operation
 * Another is a failed attempt to start a subprocess to re-register with epmd

Both are common when the node [runs out of file descriptors](http://www.rabbitmq.com/networking.html)

**Comment by folt** [comment]
<code>rabbitmqctl environment</code>
Application environment of node server_node@localhost ...
[{amqp_client,[{prefer_ipv6,false},{ssl_options,[]}]},
 {asn1,[]},
 {compiler,[]},
 {cowboy,[]},
 {cowlib,[]},
 {crypto,[]},
 {inets,[]},
 {kernel,
     [{error_logger,tty},
      {inet_default_connect_options,[{nodelay,true}]},
      {inet_dist_listen_max,25672},
      {inet_dist_listen_min,25672}]},
 {mnesia,[{dir,"/usr/local/var/lib/rabbitmq/mnesia/server_node@localhost"}]},
 {os_mon,
     [{start_cpu_sup,false},
      {start_disksup,false},
      {start_memsup,false},
      {start_os_sup,false}]},
 {public_key,[]},
 {rabbit,
     [{auth_backends,
          [rabbit_auth_backend_internal,rabbit_auth_backend_cache,
           rabbit_auth_backend_http]},
      {auth_mechanisms,['PLAIN','AMQPLAIN']},
      {background_gc_enabled,false},
      {background_gc_target_interval,60000},
      {backing_queue_module,rabbit_priority_queue},
      {channel_max,0},
      {channel_operation_timeout,15000},
      {cluster_keepalive_interval,10000},
      {cluster_nodes,{[],disc}},
      {cluster_partition_handling,ignore},
      {collect_statistics,fine},
      {collect_statistics_interval,5000},
      {config_entry_decoder,
          [{cipher,aes_cbc256},
           {hash,sha512},
           {iterations,1000},
           {passphrase,undefined}]},
      {credit_flow_default_credit,{400,200}},
      {default_permissions,[<<".*">>,<<".*">>,<<".*">>]},
      {default_user,<<"guest">>},
      {default_user_tags,[administrator]},
      {default_vhost,<<"/">>},
      {delegate_count,16},
      {disk_free_limit,50000000},
      {enabled_plugins_file,"/usr/local/etc/rabbitmq/enabled_plugins"},
      {error_logger,
          {file,"/usr/local/var/log/rabbitmq/server_node@localhost.log"}},
      {fhc_read_buffering,false},
      {fhc_write_buffering,true},
      {frame_max,131072},
      {halt_on_upgrade_failure,true},
      {handshake_timeout,10000},
      {heartbeat,60},
      {hipe_compile,false},
      {hipe_modules,
          [rabbit_reader,rabbit_channel,gen_server2,rabbit_exchange,
           rabbit_command_assembler,rabbit_framing_amqp_0_9_1,rabbit_basic,
           rabbit_event,lists,queue,priority_queue,rabbit_router,rabbit_trace,
           rabbit_misc,rabbit_binary_parser,rabbit_exchange_type_direct,
           rabbit_guid,rabbit_net,rabbit_amqqueue_process,
           rabbit_variable_queue,rabbit_binary_generator,rabbit_writer,
           delegate,gb_sets,lqueue,sets,orddict,rabbit_amqqueue,
           rabbit_limiter,gb_trees,rabbit_queue_index,
           rabbit_exchange_decorator,gen,dict,ordsets,file_handle_cache,
           rabbit_msg_store,array,rabbit_msg_store_ets_index,rabbit_msg_file,
           rabbit_exchange_type_fanout,rabbit_exchange_type_topic,mnesia,
           mnesia_lib,rpc,mnesia_tm,qlc,sofs,proplists,credit_flow,pmon,
           ssl_connection,tls_connection,ssl_record,tls_record,gen_fsm,ssl]},
      {lazy_queue_explicit_gc_run_operation_threshold,1000},
      {log_levels,[{connection,info}]},
      {loopback_users,[<<"guest">>]},
      {memory_monitor_interval,2500},
      {mirroring_flow_control,true},
      {mirroring_sync_batch_size,4096},
      {mnesia_table_loading_retry_limit,10},
      {mnesia_table_loading_retry_timeout,30000},
      {msg_store_credit_disc_bound,{4000,800}},
      {msg_store_file_size_limit,16777216},
      {msg_store_index_module,rabbit_msg_store_ets_index},
      {msg_store_io_batch_size,4096},
      {num_ssl_acceptors,1},
      {num_tcp_acceptors,10},
      {password_hashing_module,rabbit_password_hashing_sha256},
      {plugins_dir,"/usr/local/Cellar/rabbitmq/3.6.9_1/plugins"},
      {plugins_expand_dir,
          "/usr/local/var/lib/rabbitmq/mnesia/server_node@localhost-plugins-expand"},
      {queue_explicit_gc_run_operation_threshold,1000},
      {queue_index_embed_msgs_below,4096},
      {queue_index_max_journal_entries,32768},
      {reverse_dns_lookups,false},
      {sasl_error_logger,
          {file,"/usr/local/var/log/rabbitmq/server_node@localhost-sasl.log"}},
      {server_properties,[]},
      {ssl_allow_poodle_attack,false},
      {ssl_apps,[asn1,crypto,public_key,ssl]},
      {ssl_cert_login_from,distinguished_name},
      {ssl_handshake_timeout,5000},
      {ssl_listeners,[]},
      {ssl_options,[]},
      {tcp_listen_options,
          [{backlog,128},
           {nodelay,true},
           {linger,{true,0}},
           {exit_on_close,false}]},
      {tcp_listeners,[{"192.168.100.200",5672}]},
      {trace_vhosts,[]},
      {vm_memory_high_watermark,0.4},
      {vm_memory_high_watermark_paging_ratio,0.5}]},
 {rabbit_common,[]},
 {rabbitmq_amqp1_0,
     [{default_user,"guest"},
      {default_vhost,<<"/">>},
      {protocol_strict_mode,false}]},
 {rabbitmq_auth_backend_cache,
     [{cache_module,rabbit_auth_cache_ets},
      {cache_module_args,[]},
      {cache_refusals,false},
      {cache_ttl,240000},
      {cached_backend,rabbit_auth_backend_http}]},
 {rabbitmq_auth_backend_http,
     [{http_method,post},
      {resource_path,
          "http://192.168.100.200:8000/v1/api_rabbitmq/auth/resource/"},
      {topic_path,"http://192.168.100.200:8000/v1/api_rabbitmq/auth/topic/"},
      {user_path,"http://192.168.100.200:8000/v1/api_rabbitmq/auth/user/"},
      {vhost_path,"http://192.168.100.200:8000/v1/api_rabbitmq/auth/vhost/"}]},
 {rabbitmq_consistent_hash_exchange,[]},
 {rabbitmq_event_exchange,[]},
 {rabbitmq_federation,[{pgroup_name_cluster_id,false}]},
 {rabbitmq_federation_management,[]},
 {rabbitmq_jms_topic_exchange,[]},
 {rabbitmq_management,
     [{cors_allow_origins,[]},
      {cors_max_age,1800},
      {http_log_dir,none},
      {listener,[{port,15672}]},
      {load_definitions,none},
      {management_db_cache_multiplier,5},
      {process_stats_gc_timeout,300000},
      {stats_event_max_backlog,250}]},
 {rabbitmq_management_agent,
     [{rates_mode,basic},
      {sample_retention_policies,
          [{global,[{605,5},{3660,60},{29400,600},{86400,1800}]},
           {basic,[{605,5},{3600,60}]},
           {detailed,[{605,5}]}]}]},
 {rabbitmq_management_visualiser,[]},
 {rabbitmq_message_timestamp,[]},
 {rabbitmq_mqtt,
     [{allow_anonymous,true},
      {default_user,<<"guest">>},
      {exchange,<<"amq.topic">>},
      {num_ssl_acceptors,1},
      {num_tcp_acceptors,10},
      {prefetch,10},
      {retained_message_store,rabbit_mqtt_retained_msg_store_dets},
      {retained_message_store_dets_sync_interval,2000},
      {ssl_cert_login,false},
      {ssl_listeners,[]},
      {subscription_ttl,86400000},
      {tcp_listen_options,[{backlog,128},{nodelay,true}]},
      {tcp_listeners,[1883]},
      {vhost,<<"/">>}]},
 {rabbitmq_shovel,
     [{defaults,
          [{prefetch_count,1000},
           {ack_mode,on_confirm},
           {publish_fields,[]},
           {publish_properties,[]},
           {reconnect_delay,5}]}]},
 {rabbitmq_shovel_management,[]},
 {rabbitmq_stomp,
     [{default_user,[{login,<<"guest">>},{passcode,<<"guest">>}]},
      {default_vhost,<<"/">>},
      {hide_server_info,false},
      {implicit_connect,false},
      {num_ssl_acceptors,1},
      {num_tcp_acceptors,10},
      {ssl_cert_login,false},
      {ssl_listeners,[]},
      {tcp_listen_options,[{backlog,128},{nodelay,true}]},
      {tcp_listeners,[61613]},
      {trailing_lf,true}]},
 {rabbitmq_top,[]},
 {rabbitmq_tracing,
     [{directory,"/var/tmp/rabbitmq-tracing"},
      {password,<<"guest">>},
      {username,<<"guest">>}]},
 {rabbitmq_web_dispatch,[]},
 {rabbitmq_web_mqtt,
     [{cowboy_opts,[]},
      {num_ssl_acceptors,1},
      {num_tcp_acceptors,10},
      {ssl_config,[]},
      {tcp_config,[]}]},
 {rabbitmq_web_mqtt_examples,[{listener,[{port,15670}]}]},
 {rabbitmq_web_stomp,
     [{cowboy_opts,[]},
      {num_ssl_acceptors,1},
      {num_tcp_acceptors,10},
      {port,15674},
      {sockjs_opts,[]},
      {ssl_config,[]},
      {tcp_config,[]},
      {use_http_auth,false},
      {ws_frame,text}]},
 {rabbitmq_web_stomp_examples,[{listener,[{port,15670}]}]},
 {ranch,[]},
 {sasl,[{errlog_type,error},{sasl_error_logger,false}]},
 {sockjs,[]},
 {ssl,[]},
 {stdlib,[]},
 {syntax_tools,[]},
 {xmerl,[]}]
/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/
<code>rabbitmqctl status</code>
Status of node server_node@localhost ...
[{pid,5937},
 {running_applications,
     [{rabbitmq_top,"RabbitMQ Top","3.6.9"},
      {rabbitmq_tracing,"RabbitMQ message logging / tracing","3.6.9"},
      {rabbitmq_federation_management,"RabbitMQ Federation Management",
          "3.6.9"},
      {rabbitmq_management_visualiser,"RabbitMQ Visualiser","3.6.9"},
      {rabbitmq_shovel_management,
          "Management extension for the Shovel plugin","3.6.9"},
      {rabbitmq_management,"RabbitMQ Management Console","3.6.9"},
      {rabbitmq_web_stomp_examples,"Rabbit WEB-STOMP - examples","3.6.9"},
      {rabbitmq_web_stomp,"Rabbit WEB-STOMP - WebSockets to Stomp adapter",
          "3.6.9"},
      {rabbitmq_web_mqtt_examples,"Rabbit WEB-MQTT - examples","3.6.9"},
      {rabbitmq_web_mqtt,"RabbitMQ MQTT-over-WebSockets adapter","3.6.9"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.6.9"},
      {cowboy,"Small, fast, modular HTTP server.","1.0.4"},
      {cowlib,"Support library for manipulating Web protocols.","1.0.2"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.6.9"},
      {rabbitmq_consistent_hash_exchange,"Consistent Hash Exchange Type",
          "3.6.9"},
      {rabbitmq_jms_topic_exchange,
          "RabbitMQ JMS topic selector exchange plugin","3.6.9"},
      {rabbitmq_shovel,"Data Shovel for RabbitMQ","3.6.9"},
      {rabbitmq_auth_backend_http,"RabbitMQ HTTP Authentication Backend",
          "3.6.7"},
      {rabbitmq_stomp,"RabbitMQ STOMP plugin","3.6.9"},
      {rabbitmq_federation,"RabbitMQ Federation","3.6.9"},
      {rabbitmq_amqp1_0,"AMQP 1.0 support for RabbitMQ","3.6.9"},
      {rabbitmq_event_exchange,"Event Exchange Type","3.6.9"},
      {rabbitmq_mqtt,"RabbitMQ MQTT Adapter","3.6.9"},
      {rabbitmq_message_timestamp,"RabbitMQ Message Timestamp",[]},
      {rabbit,"RabbitMQ","3.6.9"},
      {ranch,"Socket acceptor pool for TCP protocols.","1.3.0"},
      {ssl,"Erlang/OTP SSL application","8.1.1"},
      {public_key,"Public key infrastructure","1.4"},
      {crypto,"CRYPTO","3.7.3"},
      {os_mon,"CPO  CXC 138 46","2.4.2"},
      {amqp_client,"RabbitMQ AMQP Client","3.6.9"},
      {rabbitmq_auth_backend_cache,"RabbitMQ Authentication Backend cache",[]},
      {rabbit_common,
          "Modules shared by rabbitmq-server and rabbitmq-erlang-client",
          "3.6.9"},
      {compiler,"ERTS  CXC 138 10","7.0.4"},
      {sockjs,"SockJS","0.3.4"},
      {syntax_tools,"Syntax tools","2.1.1"},
      {asn1,"The Erlang ASN1 compiler version 4.0.4","4.0.4"},
      {sasl,"SASL  CXC 138 11","3.0.3"},
      {inets,"INETS  CXC 138 49","6.3.6"},
      {mnesia,"MNESIA  CXC 138 12","4.14.3"},
      {xmerl,"XML parser","1.3.13"},
      {stdlib,"ERTS  CXC 138 10","3.3"},
      {kernel,"ERTS  CXC 138 10","5.2"}]},
 {os,{unix,darwin}},
 {erlang_version,
     "Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:64] [hipe] [kernel-poll:true] [dtrace]\n"},
 {memory,
     [{total,154503320},
      {connection_readers,88968},
      {connection_writers,1488},
      {connection_channels,17064},
      {connection_other,80992},
      {queue_procs,8324176},
      {queue_slave_procs,0},
      {plugins,4274432},
      {other_proc,44782760},
      {mnesia,47190536},
      {metrics,698464},
      {mgmt_db,124824},
      {msg_index,536568},
      {other_ets,8822176},
      {binary,2360584},
      {code,26045814},
      {atom,1041593},
      {other_system,10808497}]},
 {alarms,[]},
 {listeners,
     [{clustering,25672,"::"},
      {amqp,5672,"192.168.100.200"},
      {mqtt,1883,"::"},
      {stomp,61613,"::"},
      {'http/web-mqtt',15675,"::"},
      {http,15670,"::"},
      {'http/web-stomp',15674,"::"},
      {http,15672,"::"}]},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,8939565875},
 {disk_free_limit,undefined},
 {disk_free,undefined},
 {file_descriptors,
     [{total_limit,156},{total_used,10},{sockets_limit,138},{sockets_used,1}]},
 {processes,[{limit,1048576},{used,935}]},
 {run_queue,0},
 {uptime,481},
 {kernel,{net_ticktime,60}}

This situation kills the rabbit and it stops working. 
I suspect that the problem is that some customer often tries to connect to a rabbit. Either the client is triggered by a loop of connections to the rabbit that does not stop. Rabbit does not limit attempts to connect and does not handle the cycle from the client. However, these are only my guesses based on watching the rabbit's logos.

**Comment by ikebo** [comment]
ps -ef | grep empd
ps -ef | grep erl
and kill them

**Comment by michaelklishin** [comment]
We do not recommend killing nodes without gathering at least some data about their state. It may or may not be safe to kill them.

If a node is out of file descriptors it would not be able to accept any CLI tool connections, of course, so killing the process would be the only way to stop a node.

I don't see a reason to kill [epmd](https://www.rabbitmq.com/networking.html#epmd) at all, as for it to run out of file descriptors you'd have to have hundreds of inter-node connections which is rare.
