### ISSUE TITLE
when rabbitmq a node restart, ctl list_consumers show none, diff with web ui

### ISSUE THREAD

**Issue by imxuthus** [rabbitmq/rabbitmq-server#1386]
hi, all
my mq cluster have 5 node. 5th node autorestart with no error.
and i found a problem is, web ui show all green, but when i use "rabbitmqctl list_consumers | grep 5th-node-name, none.  grep other 4 node, all have result.
in web ui, Queues tab, click one queue @ 5th node, it show have consumers connect. ofcuz, incoming and deliver/get all ok.
why it happened? help~

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.
