### ISSUE TITLE
If rabbitmq can't read SSL certificates on startup, SSL connections hanng

### ISSUE THREAD

**Issue by grahamc** [rabbitmq/rabbitmq-server#1401]
I setup RabbitMQ with a LetsEncrypt certificate. The LE client originally created the certs as owned by root and not visible by the rabbitmq user. RabbitMQ started fine, and even said the SSL listener was working. I could connect over SSL, but any attempt to communicate would stall. The RabbitMQ server never logged the connection attempt. Chowning the certificate files to be readable by rabbitmq solved the problem.

### setup

1. create an ssl cert which rabbitmq cannot read
2. configure rabbitmq to use it
3. start rabbitmq

### expected behavior

an error message that the cert cannot be read

### actual behavior

RabbitMQ starts fine, and accepts TLS connections, but the connection hangs forever with no log about it.

### workaround

1. strace rabbitmq, see the failure to open the certs
2. chgrp the certs

---

Config:

```erlang
[
  {rabbit, [
     {ssl_listeners, [{"0.0.0.0", 5671}]},
     {ssl_options, [
                    {cacertfile,"/var/lib/acme/x/fullchain.pem"},
                    {certfile,"/var/lib/acme/x/cert.pem"},
                    {keyfile,"/var/lib/acme/x/key.pem"},
                    {verify,verify_none},
                    {fail_if_no_peer_cert,false}]},
     {log_levels, [{connection, debug}]}
   ]},
   {rabbitmq_management, [{listener, [{port, 15672}]}]}
].

```

* RabbitMQ version 3.6.10
* Erlang version 19.3
* RabbitMQ server and client application log files

server:

```
=INFO REPORT==== 23-Oct-2017::12:14:57 ===
Starting RabbitMQ 3.6.10 on Erlang 19.3
Copyright (C) 2007-2017 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/
              RabbitMQ 3.6.10. Copyright (C) 2007-2017 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: tty
  ######  ##        tty
  ##########
              Starting broker...
=INFO REPORT==== 23-Oct-2017::12:14:57 ===
node           : rabbit@zoidberg
home dir       : /var/lib/rabbitmq
config file(s) : /nix/store/lghq47nasv3kf3zkbffwa7z962c6rk3z-rabbitmq.config
cookie hash    : <...>
log            : tty
sasl log       : tty
database dir   : /var/lib/rabbitmq/mnesia/rabbit@zoidberg
=INFO REPORT==== 23-Oct-2017::12:15:00 ===
Memory limit set to 3190MB of 7976MB total.
=INFO REPORT==== 23-Oct-2017::12:15:00 ===
Enabling free disk space monitoring
=INFO REPORT==== 23-Oct-2017::12:15:00 ===
Disk free limit set to 50MB
=INFO REPORT==== 23-Oct-2017::12:15:00 ===
Limiting to approx 924 file handles (829 sockets)
=INFO REPORT==== 23-Oct-2017::12:15:00 ===
FHC read buffering:  OFF
FHC write buffering: ON
=INFO REPORT==== 23-Oct-2017::12:15:00 ===
Waiting for Mnesia tables for 30000 ms, 9 retries left
=INFO REPORT==== 23-Oct-2017::12:15:00 ===
=INFO REPORT==== 23-Oct-2017::12:15:00 ===
Waiting for Mnesia tables for 30000 ms, 9 retries left
=INFO REPORT==== 23-Oct-2017::12:15:00 ===
Priority queues enabled, real BQ is rabbit_variable_queue
=INFO REPORT==== 23-Oct-2017::12:15:00 ===
Starting rabbit_node_monitor
=INFO REPORT==== 23-Oct-2017::12:15:00 ===
Management plugin: using rates mode 'basic'
=INFO REPORT==== 23-Oct-2017::12:15:00 ===
msg_store_transient: using rabbit_msg_store_ets_index to provide index
=INFO REPORT==== 23-Oct-2017::12:15:01 ===
msg_store_persistent: using rabbit_msg_store_ets_index to provide index
=INFO REPORT==== 23-Oct-2017::12:15:01 ===
started TCP Listener on 127.0.0.1:5672
=INFO REPORT==== 23-Oct-2017::12:15:01 ===
started SSL Listener on 0.0.0.0:5671
=INFO REPORT==== 23-Oct-2017::12:15:01 ===
Management plugin started. Port: 15672
=INFO REPORT==== 23-Oct-2017::12:15:01 ===
Statistics database started.
 completed with 6 plugins.
=INFO REPORT==== 23-Oct-2017::12:15:01 ===
Server startup complete; 6 plugins started.
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * rabbitmq_management_agent
 * cowboy
 * cowlib
 * amqp_client
```

client: would send the AMQP bytes and then hang, verified with tcpdump.

* A runnable code sample, terminal transcript or detailed set of
  instructions that can be used to reproduce the issue
* Client library version (for all libraries used) openssl s_client,  php-amqplib/php-amqplib v2.7.0"
* Operating system, version, and patch level NixOS 17.09.1756.c99239bca0

**Comment by michaelklishin** [comment]
3.7.0 will validate file paths for existence (and readability) thanks to new [config format](http://next.rabbitmq.com/configure.html).

**Comment by michaelklishin** [comment]
And yes, 3.6.x does produce log entries but I suspect they go into the -sasl.log file which has all unhandled exceptions.

**Comment by grahamc** [comment]
Great to hear about 3.7.0! Thank you. I'm confused about -sasl though, as both logs are set to tty, and not in the tty output.

**Comment by Jleagle** [comment]
I'm running rabbitmq:3.7-management-alpine image and am getting the following errors. The files all exist in the paths specified but are owned by root. The errors don't seem to tell me this.

```
error: files specified, but missing
  - /etc/letsencrypt/live/x/fullchain.pem (RABBITMQ_MANAGEMENT_SSL_CACERTFILE)
  - /etc/letsencrypt/live/x/cert.pem (RABBITMQ_MANAGEMENT_SSL_CERTFILE)
  - /etc/letsencrypt/live/x/privkey.pem (RABBITMQ_MANAGEMENT_SSL_KEYFILE)
```

**Comment by lukebakken** [comment]
@Jleagle - we're working on improving the error reporting in situations like that. Those messages come from an external program that translates the `rabbitmq.conf` file into a format that RabbitMQ can use and we may not be able to change the message in the case you describe.

**Comment by nodenineinc** [comment]
I'm facing a similar trouble.  I have letsencrypt certs in /etc/letsencrypt/live/<hostname>/ and I -HAVE- set perms so that the rabbitmq user can read these files.  I have even temporarily edited /etc/passwd so the user rabbitmq has a shell and I can su to the rabbitmq user and cat each file just fine.... but the server process still says "ssl_options.cacertfile invalid, file doesn/t exist or isn't readable" upon startup.

Any ideas why the process would still be claiming it cannot read these files, when the rabbitmq user absolutely can read these files?

**Comment by lukebakken** [comment]
@nodenineinc please ask your question on the [`rabbitmq-users`](https://groups.google.com/forum/?pli=1#!forum/rabbitmq-users) mailing list.

* Specify what operating system and version you are using
* Specify what RabbitMQ and Erlang version you are using, and how they were installed
* Please attach your _complete_ RabbitMQ configuration files, and the output of the following commands:

```
ls -la /etc/letsencrypt
ls -la /etc/letsencrypt/live
ls -la /etc/rabbitmq
```

**Comment by michaelklishin** [comment]
And use `strace` to see what the read system calls return. There isn't anything sophisticated around certificate loading and you *can* inspect what's the kernel is being asked to do easily, so why guess or wait for responses from strangers on the Internet.
