### ISSUE TITLE
Consider 'exclusive exchanges' protocol extension

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-server#1409]
AMQP 0.9.1 spec doesn't define this, but we've got some cases where we don't desire behaviour of `auto-delete` or `transient` exchanges, but initiating channel also cleans up exchanges (and bindings) on termination, independent of the queue kind.

**Comment by michaelklishin** [comment]
I don't think we have seen much demand for it. Automatically deleted things lead to tricky race conditions and open ended consistency model questions, so I don't think it's worth having more of them.
