### ISSUE TITLE
Add handling for string configured queue master location strategies

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-server#1411]
Queue master location validator expects binary type configured location strategies. Validation for string configured location strategies shouldn't fail, but needs to be handled appropriately.

Reported here: https://groups.google.com/forum/#!topic/rabbitmq-users/XUbtu4UxbHQ

**Comment by michaelklishin** [comment]
Why can't strings be coerced to binaries?
