### ISSUE TITLE
what's the meaning of sender = self() for the various invocations of rabbit_basic:delivery/4

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-server#142]
Currently `rabbit_basic:delivery/4` sets the `#delivery`'s `sender` field to `self()` [1]. That field value is used by credit_flow to ack messages in various parts of our code[2]. The error_logger[3] and message dead lettering[4] will use `#delivery` records with `sender = self()` as well, whatever `self()` might mean in said context. 

On the other hand, the `#delivery` record has the `flow` field set to `noflow` by default, so the question is should we care about the `sender = self()` field usage? Could it be the source of bugs? What could it be set to if not `self()`?

1- https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_basic.erl#L122
2 - https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_amqqueue_process.erl#L1109
3 - https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_error_logger.erl#L108
4 - https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_dead_letter.erl#L39

**Comment by michaelklishin** [comment]
It can be a different process: a channel, including on a different node.

**Comment by michaelklishin** [comment]
We've discussed if `sender` can be moved out of the record as it is not used in multiple places. We can but this is not a particularly high priority for now.

**Comment by videlalvaro** [comment]
Perhaps not moving it out of the `#delivery` record but at least make it explicit when `rabbit_basic:delivery/4` by adding an extra param. Note: this will break plugins depending on that function (we can add a `rabbit_basic:delivery/5` tho).
