### ISSUE TITLE
When occurs heartbeat timeout then appear many no queue exception

### ISSUE THREAD

**Issue by jasonwang3** [rabbitmq/rabbitmq-server#1439]
RabbitMQ 3.6.1, Erlang R16B03

ha-mode: exactly
ha-params:  2
ha-sync-mode: | automatic
3 hosts totally.

When we declare many queue and binding sometimes will appear no queue exception:

_=ERROR REPORT==== 27-Nov-2017::20:21:55 ===
** Generic server <0.815.4344> terminating
** Last message in was heartbeat_timeout
** When Server state == {state,amqp_network_connection,
                            {state,#Port<0.3129894>,
                                <<"client *.*.*.97:49934 -> *.*.*.28:5672">>,
                                10,<0.18122.4344>,131072,<0.2760.4344>,
                                undefined,false},
                            <0.16813.4344>,
                            {amqp_params_network,<<"neuser">>,
                                <<"nepassword">>,<<"/">>,
                                "rmqrt03.com",5672,0,0,10,
                                infinity,none,
                                [#Fun<amqp_uri.11.49810338>,
                                 #Fun<amqp_uri.11.49810338>],
                                [],[]},
                            0,
                            [{<<"capabilities">>,table,
                              [{<<"publisher_confirms">>,bool,true},
                               {<<"exchange_exchange_bindings">>,bool,true},
                               {<<"basic.nack">>,bool,true},
                               {<<"consumer_cancel_notify">>,bool,true},
                               {<<"connection.blocked">>,bool,true},
                               {<<"consumer_priorities">>,bool,true},
                               {<<"authentication_failure_close">>,bool,true},
                               {<<"per_consumer_qos">>,bool,true},
                               {<<"direct_reply_to">>,bool,true}]},
                             {<<"cluster_name">>,longstr,
                              <<"rmqrt@rmqrt01.com">>},
                             {<<"copyright">>,longstr,
                              <<"Copyright (C) 2007-2016 Pivotal Software, Inc.">>},
                             {<<"information">>,longstr,
                              <<"Licensed under the MPL.  See http://www.rabbitmq.com/">>},
                             {<<"platform">>,longstr,<<"Erlang/OTP">>},
                             {<<"product">>,longstr,<<"RabbitMQ">>},
                             {<<"version">>,longstr,<<"3.6.1">>}],
:
** When Server state == {state,amqp_network_connection,
                            {state,#Port<0.3129894>,
                                <<"client *.*.*.97:49934 -> *.*.*.28:5672">>,
                                10,<0.18122.4344>,131072,<0.2760.4344>,
                                undefined,false},
                            <0.16813.4344>,
                            {amqp_params_network,<<"neuser">>,
                                <<"nepassword">>,<<"/">>,
                                "rmqrt03.com",5672,0,0,10,
                                infinity,none,
                                [#Fun<amqp_uri.11.49810338>,
                                 #Fun<amqp_uri.11.49810338>],
                                [],[]},
                            0,
                            [{<<"capabilities">>,table,
                              [{<<"publisher_confirms">>,bool,true},
                               {<<"exchange_exchange_bindings">>,bool,true},
                               {<<"basic.nack">>,bool,true},
                               {<<"consumer_cancel_notify">>,bool,true},
                               {<<"connection.blocked">>,bool,true},
                               {<<"consumer_priorities">>,bool,true},
                               {<<"authentication_failure_close">>,bool,true},
                               {<<"per_consumer_qos">>,bool,true},
                               {<<"direct_reply_to">>,bool,true}]},
                             {<<"cluster_name">>,longstr,
                              <<"rmqrt@rmqrt01.com">>},
                             {<<"copyright">>,longstr,
                              <<"Copyright (C) 2007-2016 Pivotal Software, Inc.">>},
                             {<<"information">>,longstr,
                              <<"Licensed under the MPL.  See http://www.rabbitmq.com/">>},
                             {<<"platform">>,longstr,<<"Erlang/OTP">>},
                             {<<"product">>,longstr,<<"RabbitMQ">>},
                             {<<"version">>,longstr,<<"3.6.1">>}],
:
** When Server state == {state,amqp_network_connection,
                            {state,#Port<0.3129894>,
                                <<"client *.*.*.97:49934 -> *.*.*.28:5672">>,
                                10,<0.18122.4344>,131072,<0.2760.4344>,
                                undefined,false},
                            <0.16813.4344>,
                            {amqp_params_network,<<"neuser">>,
                                <<"nepassword">>,<<"/">>,
                                "rmqrt03.den2.stg1.ebcolo.com",5672,0,0,10,
                                infinity,none,
                                [#Fun<amqp_uri.11.49810338>,
                                 #Fun<amqp_uri.11.49810338>],
                                [],[]},
                            0,
                            [{<<"capabilities">>,table,
                              [{<<"publisher_confirms">>,bool,true},
                               {<<"exchange_exchange_bindings">>,bool,true},
                               {<<"basic.nack">>,bool,true},
                               {<<"consumer_cancel_notify">>,bool,true},
                               {<<"connection.blocked">>,bool,true},
                               {<<"consumer_priorities">>,bool,true},
                               {<<"authentication_failure_close">>,bool,true},
                               {<<"per_consumer_qos">>,bool,true},
                               {<<"direct_reply_to">>,bool,true}]},
                             {<<"cluster_name">>,longstr,
                              <<"rmqrt@rmqrt01.den2.stg1.ebcolo.com">>},
                             {<<"copyright">>,longstr,
                              <<"Copyright (C) 2007-2016 Pivotal Software, Inc.">>},
                             {<<"information">>,longstr,
                              <<"Licensed under the MPL.  See http://www.rabbitmq.com/">>},
                             {<<"platform">>,longstr,<<"Erlang/OTP">>},
                             {<<"product">>,longstr,<<"RabbitMQ">>},
                             {<<"version">>,longstr,<<"3.6.1">>}],
...skipping..._

_=ERROR REPORT==== 27-Nov-2017::20:21:55 ===
** Generic server <0.815.4344> terminating
** Last message in was heartbeat_timeout
** When Server state == {state,amqp_network_connection,
                            {state,#Port<0.3129894>,
                                <<"client *.*.*.97:49934 -> *.*.*.28:5672">>,
                                10,<0.18122.4344>,131072,<0.2760.4344>,
                                undefined,false},
                            <0.16813.4344>,
                            {amqp_params_network,<<"neuser">>,
                                <<"nepassword">>,<<"/">>,
                                "rmqrt03.com",5672,0,0,10,
                                infinity,none,
                                [#Fun<amqp_uri.11.49810338>,
                                 #Fun<amqp_uri.11.49810338>],
                                [],[]},
                            0,
                            [{<<"capabilities">>,table,
                              [{<<"publisher_confirms">>,bool,true},
                               {<<"exchange_exchange_bindings">>,bool,true},
                               {<<"basic.nack">>,bool,true},
                               {<<"consumer_cancel_notify">>,bool,true},
                               {<<"connection.blocked">>,bool,true},
                               {<<"consumer_priorities">>,bool,true},
                               {<<"authentication_failure_close">>,bool,true},
                               {<<"per_consumer_qos">>,bool,true},
                               {<<"direct_reply_to">>,bool,true}]},
                             {<<"cluster_name">>,longstr,
                              <<"rmqrt@rmqrt01.den2.stg1.ebcolo.com">>},
                             {<<"copyright">>,longstr,
                              <<"Copyright (C) 2007-2016 Pivotal Software, Inc.">>},
                             {<<"information">>,longstr,
                              <<"Licensed under the MPL.  See http://www.rabbitmq.com/">>},
                             {<<"platform">>,longstr,<<"Erlang/OTP">>},
                             {<<"product">>,longstr,<<"RabbitMQ">>},
                             {<<"version">>,longstr,<<"3.6.1">>}],
:
** When Server state == {state,amqp_network_connection,
                            {state,#Port<0.3129894>,
                                <<"client 10.4.133.97:49934 -> 10.68.47.28:5672">>,
                                10,<0.18122.4344>,131072,<0.2760.4344>,
                                undefined,false},
                            <0.16813.4344>,
                            {amqp_params_network,<<"neuser">>,
                                <<"nepassword">>,<<"/">>,
                                "rmqrt03.com",5672,0,0,10,
                                infinity,none,
                                [#Fun<amqp_uri.11.49810338>,
                                 #Fun<amqp_uri.11.49810338>],
                                [],[]},
                            0,
                            [{<<"capabilities">>,table,
                              [{<<"publisher_confirms">>,bool,true},
                               {<<"exchange_exchange_bindings">>,bool,true},
                               {<<"basic.nack">>,bool,true},
                               {<<"consumer_cancel_notify">>,bool,true},
                               {<<"connection.blocked">>,bool,true},
                               {<<"consumer_priorities">>,bool,true},
                               {<<"authentication_failure_close">>,bool,true},
                               {<<"per_consumer_qos">>,bool,true},
                               {<<"direct_reply_to">>,bool,true}]},
                             {<<"cluster_name">>,longstr,
                              <<"rmqrt@rmqrt01.com">>},
                             {<<"copyright">>,longstr,
                              <<"Copyright (C) 2007-2016 Pivotal Software, Inc.">>},
                             {<<"information">>,longstr,
                              <<"Licensed under the MPL.  See http://www.rabbitmq.com/">>},
                             {<<"platform">>,longstr,<<"Erlang/OTP">>},
                             {<<"product">>,longstr,<<"RabbitMQ">>},
                             {<<"version">>,longstr,<<"3.6.1">>}],
:
** When Server state == {state,amqp_network_connection,
                            {state,#Port<0.3129894>,
                                <<"client *.*.*.97:49934 -> *.*.*:5672">>,
                                10,<0.18122.4344>,131072,<0.2760.4344>,
                                undefined,false},
                            <0.16813.4344>,
                            {amqp_params_network,<<"neuser">>,
                                <<"nepassword">>,<<"/">>,
                                "rmqrt03.com",5672,0,0,10,
                                infinity,none,
                                [#Fun<amqp_uri.11.49810338>,
                                 #Fun<amqp_uri.11.49810338>],
                                [],[]},
                            0,
                            [{<<"capabilities">>,table,
                              [{<<"publisher_confirms">>,bool,true},
                               {<<"exchange_exchange_bindings">>,bool,true},
                               {<<"basic.nack">>,bool,true},
                               {<<"consumer_cancel_notify">>,bool,true},
                               {<<"connection.blocked">>,bool,true},
                               {<<"consumer_priorities">>,bool,true},
                               {<<"authentication_failure_close">>,bool,true},
                               {<<"per_consumer_qos">>,bool,true},
                               {<<"direct_reply_to">>,bool,true}]},
                             {<<"cluster_name">>,longstr,
                              <<"rmqrt@rmqrt01.com">>},
                             {<<"copyright">>,longstr,
                              <<"Copyright (C) 2007-2016 Pivotal Software, Inc.">>},
                             {<<"information">>,longstr,
                              <<"Licensed under the MPL.  See http://www.rabbitmq.com/">>},
                             {<<"platform">>,longstr,<<"Erlang/OTP">>},
                             {<<"product">>,longstr,<<"RabbitMQ">>},
                             {<<"version">>,longstr,<<"3.6.1">>}],
...skipping..._

**No queue exception:**
operation queue.declare caused a channel exception not_found: "no queue 'broadcast:***-flow-mobile-attempt' in vhost '/'"

=ERROR REPORT==== 29-Nov-2017::23:30:19 ===
Channel error on connection <0.24105.7012> (*.*.*.227:34998 -> *.*.*.97:5672, vhost: '/', user: 'mquser'), channel 1:
operation queue.declare caused a channel exception not_found: "no queue 'broadcast:5a1f31deea78611aae49dbd9-flow-mobile-attempt' in vhost '/'"

=ERROR REPORT==== 29-Nov-2017::23:30:19 ===
Channel error on connection <0.25209.7364> (*.*.*.227:40386 -> *.*.*.97:5672, vhost: '/', user: 'mquser'), channel 1:
operation queue.declare caused a channel exception not_found: "no queue 'broadcast:***-flow-mobile-attempt' in vhost '/'"

=ERROR REPORT==== 29-Nov-2017::23:30:19 ===
Channel error on connection <0.25713.6058> (10.4.133.227:55238 -> 10.4.133.97:5672, vhost: '/', user: 'mquser'), channel 1:
operation queue.declare caused a channel exception not_found: "no queue 'broadcast:5a1f31ceae4bb4770816b859-flow-mobile-attempt' in vhost '/'"

=ERROR REPORT==== 29-Nov-2017::23:30:19 ===
Channel error on connection <0.25440.6058> (*.*.*.227:55230 -> *.*.*.97:5672, vhost: '/', user: 'mquser'), channel 1:
operation queue.declare caused a channel exception not_found: "no queue 'broadcast:***-flow-mobile-attempt' in vhost '/'"

I'm sure when we binding queue will after created queue but this issues appear more then once when we frequent create and bind queues

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
[Heartbeat timeouts](http://www.rabbitmq.com/heartbeats.html) is not necessarily (and most likely not) an indication of an issue. Please upgrade to 3.6.14 ASAP regardless.
