### ISSUE TITLE
RabbitMQ DeliveryMode.NON_PERSISTENT on message doesn't work.

### ISSUE THREAD

**Issue by chetanladdha** [rabbitmq/rabbitmq-server#1440]
I am trying to set DeliveryMode.NON_PERSISTENT on message but it gets ignored.
If I send delivery mode to producer then it gets considered.

`MessageProducer producer = session.createProducer(null);
 TextMessage msg = session.createTextMessage(line);
 msg.setJMSDeliveryMode(DeliveryMode.NON_PERSISTENT);
 producer.send(sendDestination, msg);`

Above message get received as PERSISTENT where as below gets as NON_PERSISTENT
`MessageProducer producer = session.createProducer(null);
producer.setDeliveryMode(DeliveryMode.PERSISTENT);
TextMessage msg = session.createTextMessage(line);
producer.send(sendDestination, msg);
`

**Comment by lukebakken** [comment]
Hello -

Could you please post this question to the [RabbitMQ users mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users)? The RabbitMQ team does not use GitHub issues to answer questions or do issue analysis.

When you post your question, please be sure to include the following information -

* RabbitMQ version and Erlang version
* Client library used and version
* Operating system platform and version.
* Complete code example to reproduce your issue (ideally).

Thanks -
Luke

**Comment by michaelklishin** [comment]
FTR: the code above is for JMS client. We don't have any evidence of an issue but if there is one, it's in that client, not the server.
