### ISSUE TITLE
Getting amqp (Hex package) ** (ArgumentError) argument error

### ISSUE THREAD

**Issue by nirmannarang** [rabbitmq/rabbitmq-server#1441]
While running **make all** step for RabbitMQ Server, I am getting the following error:

`Putting child 0x95a5d000 (escript/rabbitmqctl) PID 20257 on the chain.
Live child 0x95a5d000 (escript/rabbitmqctl) PID 20257
GEN escript/rabbitmqctl
Resolving Hex dependencies...
Dependency resolution completed:
amqp 0.2.4
csv 2.0.0
dialyxir 0.5.1
json 1.0.2
parallel_stream 1.0.5
simetric 0.2.0
temp 0.4.3

Getting amqp (Hex package)
** (ArgumentError) argument error
(stdlib) re.erl:734: :re.run("https://repo.hex.pm/tarballs/amqp-0.2.4.tar", {:re_pattern, 1, 0, 0, <<69, 82, 67, 80, 91, 0, 0, 0, 0, 0, 0, 0, 81, 0, 0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 47, 0, 64, 0, 0, 0, 1, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...>>}, [{:capture, :all, :index}, :global])
(elixir) lib/regex.ex:590: Regex.do_replace/4
(hex) lib/hex/scm.ex:103: Hex.SCM.update/1
(hex) lib/hex/scm.ex:150: Hex.SCM.checkout/1
(mix) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
(mix) lib/mix/dep/converger.ex:180: Mix.Dep.Converger.all/9
(mix) lib/mix/dep/converger.ex:189: Mix.Dep.Converger.all/9
(mix) lib/mix/dep/converger.ex:119: Mix.Dep.Converger.all/7
Reaping losing child 0x95a5d000 PID 20257
Makefile:73: recipe for target 'escript/rabbitmqctl' failed
make: *** [escript/rabbitmqctl] Error 1
Removing child 0x95a5d000 PID 20257 from chain.`

RabbitMQ Version: 3.7.0 (Building from source)
Erlang : OTP 20.0 (Built from source)
Hex: 0.17.1
Elixir: 1.5.2

OS Details:
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"

**Comment by hairyhum** [comment]
Hi,

I believe this is a hex.pm issue. Try deleting your mix and hex cache (often located in `~/.mix` and `~/.hex` directories) and run `make` again

I'm closing the issue, because we try to keep github issues for feature requests and bug reports. Please post following questions to [the mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) 

Thank you.
