### ISSUE TITLE
Why rabbitmq logs shown "Synchronising: all slaves already synced" but "no queue" exception found

### ISSUE THREAD

**Issue by jasonwang3** [rabbitmq/rabbitmq-server#1442]
This rabbitmq is 'rabbit@rmq01.com' and cluster with rmq02/rmq03.com
Mirrored queue 'broadcast:5a270c605ed6065b517ef1f5-flow-email-attempt' in vhost '/': Adding mirror on node 'rabbit@rmq02.com': <31272.15998.375>

=INFO REPORT==== 5-Dec-2017::21:15:24 ===
Mirrored queue 'broadcast:5a270c605ed6065b517ef1f5-flow-email-attempt' in vhost '/': Synchronising: 0 messages to synchronise

=INFO REPORT==== 5-Dec-2017::21:15:24 ===
Mirrored queue 'broadcast:5a270c605ed6065b517ef1f5-flow-email-attempt' in vhost '/': Synchronising: batch size: 4096

=INFO REPORT==== 5-Dec-2017::21:15:27 ===
Mirrored queue 'broadcast:5a270c605ed6065b517ef1f5-flow-email-attempt' in vhost '/': Synchronising: all slaves already synced

**operation queue.declare caused a channel exception not_found: "no queue 'broadcast:5a270c605ed6065b517ef1f5-flow-email-attempt' in vhost '/'"**

RabbitMQ 3.6.1, Erlang R16B03

**Comment by hairyhum** [comment]
Hi,

We try to keep github issues for feature requests and bug reports only.
Please post your question to [rabbitmq-users mailing list](https://groups.google.com/forum/#!topic/rabbitmq-users). 

Also I would suggest to add more logs and explain the context of this error: what happened with the nodes, who tries to declare a queue, also more logs from all the nodes would help.

**Comment by michaelklishin** [comment]
And please upgrade from 3.6.1 (to at least 3.6.14).
