### ISSUE TITLE
Network partition during peer discovery in auto clustering causes two clusters to form

### ISSUE THREAD

**Issue by AceHack** [rabbitmq/rabbitmq-server#1455]
* RabbitMQ version 3.7 offical docker image
See https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s/issues/12 for logs and env

1) Create DNS or K8s cluster for 5 nodes
2) Force network partitions between so only nodes 1 and 2 can talk to each other and only nodes 3, 4, and 5 can talk to each other
3) Let the rabbit-autocluster plugin run and do peer discovery and cluster formation occur
4) This will create 2 individual split brain cluster to form and be healthy
5) After a sufficent amount of time remove the network partition

![image](https://user-images.githubusercontent.com/578953/34194234-aec5d558-e525-11e7-84ec-b5cbcc714136.png)

NOTE:  This also occurs with mismatch erlang cookies, where 2 PCs have cookie 1 and 3 PCs have cookie 2.

See [here](https://github.com/kubernetes/charts/issues/3075) for more info
I also created a [rabbitmq-users post](https://groups.google.com/forum/?nomobile=true#!forum/rabbitmq-users) on this subject

**Comment by michaelklishin** [comment]
Peer discovery will cluster with the nodes that can be reached from the discovered list. Forming a cluster with a networking split already in place is going to have this effect. There aren't too many alternatives I can think of, one of them — wait for a set of nodes to be up before forming a cluster — has been tried in the rabbitmq-clusterer plugin and it turned out to be a true operational disaster. Now if one node is down, your entire cluster won't form.

So this works as expected from peer discovery at the moment.

**Comment by michaelklishin** [comment]
There is no consensus on the best way to address this => mailing list material.

**Comment by AceHack** [comment]
When adding rabbit to things like K8s it's impossible to know when you do a deploy 10s if not 100s of deploys are happening a day automated if a network partition is occuring or not.  This functions as designed would suggest rabbit-autocluster is not K8s production ready.

**Comment by michaelklishin** [comment]
@AceHack I'm sorry for how blunt I'm going to be but you need to stop fixating so much on the scenario you have discovered. This is not a new discovery, all this we have seen before with BOSH and Cloud Foundry, and things work pretty decently in practice as of 3.6.7+ and once we got rid of rabbitmq-clusterer. As rabbitmq-autocluster README states, peer discovery *is not a substitute for understanding of how RabbitMQ clustering works*. You seem to be a bit confused about that (sorry).

The reason why this is NOT a major problem is this: once a cluster is formed, peer discovery isn't used and nodes simply rejoin. Do you resize your cluster 10s or 100s times a day? In that case it is not production ready. Your specific suggestions on what can be changed are welcome on the mailing list.

**Comment by michaelklishin** [comment]
Another idea [brought up on rabbitmq-users](https://groups.google.com/d/msg/rabbitmq-users/VlRl4UMiG9Y/HIOLXwySDAAJ) that is easy to try is this: when a peer is contacted right after discovery, we can introduce the "N retries every T seconds" approach that we already use for re-joining nodes.

In theory it should help with the transient network partition scenario as long as it goes away in a certain window of time. As for possible downsides, the only one I can think of is much slower cluster formation in certain scenarios (when retries happen a lot).
