### ISSUE TITLE
Exchange amq.rabbitmq.log doesn't generate log messages in 3.7.0

### ISSUE THREAD

**Issue by carlhoerberg** [rabbitmq/rabbitmq-server#1456]
In RabbitMQ 3.7.0 the exchange `amq.rabbitmq.log` doesn't generate any log messages anymore.

**Comment by michaelklishin** [comment]
This is a consequence of the move to Lager in #94.

**Comment by michaelklishin** [comment]
Will reopen until this passes the master pipeline and is merged into `v3.7.x`.

**Comment by michaelklishin** [comment]
Note that this feature now has to be enabled with `log.exchange = true` in the config. It is now possible to use a different log severity for it.

**Comment by rolatsch** [comment]
Could you please tell me how to configure this in the classic config format?
I have tried many things but i don't get it.
Thanks!

**Comment by lukebakken** [comment]
@rolatsch - please post your question to the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users),

**Comment by michaelklishin** [comment]
@rolatsch as `rabbit.log.exchange.enabled` (which can be either `true` or `false`):

``` erlang
[
 {rabbit, [
           {log, [
                  {exchange, [
                              {enabled, true}]
                  }
                 ]}
          ]}
].
```

**Comment by rolatsch** [comment]
Thank you very much!
