### ISSUE TITLE
RABBITMQ_CTL_ERL_ARGS is not being honored by escript

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#1461]
Mailing list thread: https://groups.google.com/d/topic/rabbitmq-users/bckKQoN3Tao/discussion

In the `3.6.x` series of RabbitMQ, [this line](https://github.com/rabbitmq/rabbitmq-server/blob/v3.6.x/scripts/rabbitmqctl#L35) added `RABBITMQ_CTL_ERL_ARGS` as arguments to `erl`. The same happened for [`rabbitmq-plugins`](https://github.com/rabbitmq/rabbitmq-server/blob/v3.6.x/scripts/rabbitmq-plugins#L32) and other scripts.

In the `3.7.x` series, this variable is not used ([`rabbitmqctl`](https://github.com/rabbitmq/rabbitmq-server/blob/v3.7.x/scripts/rabbitmqctl#L32), [`rabbitmq-plugins`](https://github.com/rabbitmq/rabbitmq-server/blob/v3.7.x/scripts/rabbitmq-plugins#L32)).

**Comment by michaelklishin** [comment]
Re-openening until #1462 is merged.
