### ISSUE TITLE
 the max size of a message in rabbitmq

### ISSUE THREAD

**Issue by andyxning** [rabbitmq/rabbitmq-server#147]
we have a problem about the max size of a message in rabbitmq. 

recently, we have a problem that we sent a message with length about 220KB, however, it do not accepted by rabbitmq. So, i want to know:

1) if rabbitmq has a limit in the maximum size of a message.
2) if it does, what is the default one and how to tune that value.

**Comment by videlalvaro** [comment]
Message size is limited to 2GB https://github.com/rabbitmq/rabbitmq-server/blob/master/include/rabbit.hrl#L137

AFAIK there's no way to tune that value.

It's better to ask these kind of questions in our mailing list https://groups.google.com/forum/#!forum/rabbitmq-users

**Comment by michaelklishin** [comment]
You are running into [flow control/resource alarms](http://www.rabbitmq.com/alarms.html) that block publishers.

**Comment by maggyero** [comment]
The _maximum message size_ in RabbitMQ was 2 GiB up to version 3.7:
https://github.com/rabbitmq/rabbitmq-common/blob/v3.7.13/include/rabbit.hrl#L279

> %% Trying to send a term across a cluster larger than 2^31 bytes will
> %% cause the VM to exit with "Absurdly large distribution output data
> %% buffer". So we limit the max message size to 2^31 - 10^6 bytes (1MB
> %% to allow plenty of leeway for the #basic_message{} and #content{}
> %% wrapping the message body).
> -define(MAX_MSG_SIZE, 2147383648).

It is now 512 MiB in version 3.8:
https://github.com/rabbitmq/rabbitmq-common/blob/master/include/rabbit.hrl#L255

> %% Max message size is set to 512MiB.
> %% This is a hard limit. If user configures bigger max_message_size,
> %% this value is used instead.
> -define(MAX_MSG_SIZE, 536870912).

**Comment by michaelklishin** [comment]
It hasn't changed because 3.8 hasn't shipped yet. The limit was lowered and the default was changed in https://github.com/rabbitmq/rabbitmq-common/pull/289.

**Comment by wxlevel** [comment]
> It hasn't changed because 3.8 hasn't shipped yet. The limit was lowered and the default was changed in [rabbitmq/rabbitmq-common#289](https://github.com/rabbitmq/rabbitmq-common/pull/289).

As a message queue, the maximum message limit should be as small as possible. In my opinion, when the message size is larger than 10M, we should find a way to make the data sent to the message queue smaller. Otherwise, message queue performance will be severely affected.

**Comment by michaelklishin** [comment]
@wxlevel we have been recommending this for years, putting large objects into a blob store and passing their IDs around. This is not always an option and there is no way to pick the "right" maximum, in particular since RabbitMQ installations never report any metrics to our team.

At best we can slowly decrease the value over time, perhaps stopping at 100 MiB or so one day.
Every such change usually involves us receiving highly negative feedback from a small but very vocal group of users. This is not a factor we can just ignore every time.
