### ISSUE TITLE
Management UI - queue > "Publish message" lost support for multiple headers and properties

### ISSUE THREAD

**Issue by adammichalik** [rabbitmq/rabbitmq-server#1470]
RabbitMQ 3.6.14, Erlang 20.1, installed from package on Ubuntu 14.04 LTS
Chrome 63.0.3239.132 on macOs Sierra. Checked on Safari, too.

I upgraded from RabbitMQ 3.6.10 and was attempting to use the management UI to publish a message to the queue (`/#/queues/%2F/<queueName>`).

I find it now impossible to set multiple headers and properties on the message - only one pair of input boxes for each of them is present. In RabbitMQ 3.6.10 and earlier versions when I entered one pair of values, another pair of input fields was dynamically added on the page so that I could add multiple headers and properties.

The JS console says only on pageload:
```
ejs-1.0.min.js:1 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
EJS.request @ ejs-1.0.min.js:1
EJS @ ejs-1.0.min.js:1
format @ main.js:1028
(anonymous) @ main.js:2
i @ jquery-1.12.4.min.js:2
fireWith @ jquery-1.12.4.min.js:2
ready @ jquery-1.12.4.min.js:2
K @ jquery-1.12.4.min.js:2

sammy-0.7.6.min.js:5 [Thu Jan 11 2018 10:38:09 GMT+0100 (CET)] body 404 Not Found get /#/queues/%2F/<queueName>  Error: 404 Not Found get /#/queues/%2F/<queueName> 
    at Sammy.Application.error (sammy-0.7.6.min.js:5)
    at Sammy.Application.notFound (sammy-0.7.6.min.js:5)
    at Sammy.Application.runRoute (sammy-0.7.6.min.js:5)
    at Sammy.Application._checkLocation (sammy-0.7.6.min.js:5)
    at Sammy.Application.run (sammy-0.7.6.min.js:5)
    at start_app_login (main.js:67)
    at HTMLDocument.<anonymous> (main.js:3)
    at i (jquery-1.12.4.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.12.4.min.js:2)
    at Function.ready (jquery-1.12.4.min.js:2)
```

**Comment by michaelklishin** [comment]
This was reported in the management plugin repo several weeks ago and addressed.

**Comment by michaelklishin** [comment]
Duplicate of https://github.com/rabbitmq/rabbitmq-management/issues/51.

**Comment by adammichalik** [comment]
Thanks, I think you meant https://github.com/rabbitmq/rabbitmq-management/issues/511
