### ISSUE TITLE
Unable to delete queue, unreachable

### ISSUE THREAD

**Issue by MarkEngelsman** [rabbitmq/rabbitmq-server#1492]
I am running a cluster of 3 RabbitMQ nodes, with each queue on a master node being mirrored to another node.

Last sunday, one of our RabbitMQ nodes went unreachable by other nodes (so the cluster was broken). The behavior I expected was that the slave should become the master, and the other running node would become the slave.

This didn't happen. The queue went unreachable and nothing could connect to it. It became in a state were it was not possible anymore to connect to this queue.

Even deleting the queue was not possible anymore. Today, the same thing happened and now I have two queues which can't be deleted. I added a screenshot with the error I get when I try to delete the queue.
![screenshot_167](https://user-images.githubusercontent.com/15088936/35672595-5c998e00-073f-11e8-8027-83aecf98dcb1.png)

I also removed each of the nodes out of the cluster, deleted the Mnesia database, did a rabbitmq-server restart, put them back in the cluster, but the two 'ghost queues' are still there. If more information is needed, please tell me and I'll provide everything I can. 

Here is the output of the rabbitmqctl status, with versioning information et cetera:

[{pid,5016},
 {running_applications,
     [{rabbitmq_management,"RabbitMQ Management Console","3.6.10"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.6.10"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.6.10"},
      {cowboy,"Small, fast, modular HTTP server.","1.0.4"},
      {rabbit,"RabbitMQ","3.6.10"},
      {os_mon,"CPO  CXC 138 46","2.4.2"},
      {cowlib,"Support library for manipulating Web protocols.","1.0.2"},
      {amqp_client,"RabbitMQ AMQP Client","3.6.10"},
      {rabbit_common,
          "Modules shared by rabbitmq-server and rabbitmq-erlang-client",
          "3.6.10"},
      {mnesia,"MNESIA  CXC 138 12","4.15"},
      {ranch,"Socket acceptor pool for TCP protocols.","1.3.0"},
      {ssl,"Erlang/OTP SSL application","8.2"},
      {public_key,"Public key infrastructure","1.4.1"},
      {asn1,"The Erlang ASN1 compiler version 5.0","5.0"},
      {xmerl,"XML parser","1.3.15"},
      {compiler,"ERTS  CXC 138 10","7.1"},
      {crypto,"CRYPTO","4.0"},
      {syntax_tools,"Syntax tools","2.1.2"},
      {inets,"INETS  CXC 138 49","6.4"},
      {sasl,"SASL  CXC 138 11","3.0.4"},
      {stdlib,"ERTS  CXC 138 10","3.4"},
      {kernel,"ERTS  CXC 138 10","5.3"}]},
 {os,{win32,nt}},
 {erlang_version,
     "Erlang/OTP 20 [erts-9.0] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:64]\n"},
 {memory,
     [{total,143987216},
      {connection_readers,2059584},
      {connection_writers,6696},
      {connection_channels,204560},
      {connection_other,3203720},
      {queue_procs,1388704},
      {queue_slave_procs,0},
      {plugins,40826064},
      {other_proc,27338616},
      {mnesia,110152},
      {metrics,593776},
      {mgmt_db,22119888},
      {msg_index,45240},
      {other_ets,2754344},
      {binary,7535792},
      {code,24738924},
      {atom,1033401},
      {other_system,10618723}]},
 {alarms,[]},
 {listeners,
     [{clustering,25672,"::"},
      {amqp,5672,"::"},
      {amqp,5672,"0.0.0.0"},
      {http,15672,"::"},
      {http,15672,"0.0.0.0"}]},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,3435759206},
 {disk_free_limit,50000000},
 {disk_free,38501441536},
 {file_descriptors,
     [{total_limit,8092},
      {total_used,72},
      {sockets_limit,7280},
      {sockets_used,70}]},
 {processes,[{limit,1048576},{used,872}]},
 {run_queue,0},
 {uptime,161675},
 {kernel,{net_ticktime,60}}]

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Consider consulting server logs instead of taking a guess and wiping a node next time.

There are several threads that explain how to force delete an unresponsive queue.
Upgrading to 3.6.15 is the only thing that we can recommend without having access to the logs.
