### ISSUE TITLE
New configuration file format missing delegate_count setting

### ISSUE THREAD

**Issue by gmr** [rabbitmq/rabbitmq-server#1497]
RabbitMQ Version: 3.7.3

```
Config file generation failed 16:55:12.143 [error] You've tried to set delegate_count, but there is no setting with that name.
16:55:12.143 [error]   Did you mean one of these?
16:55:12.158 [error]     default_vhost
16:55:12.158 [error]     default_pass
16:55:12.158 [error]     default_user
...
16:55:12.352 [error] Conf file attempted to set unknown variable: delegate_count
```
The documentation @ http://www.rabbitmq.com/configure.html example for ``delegate_count`` makes it appear it's a setting that should work with the new conf file format.

My config that is tripping the error:

```
delegate_count = 128
```
I looked in the [schema](https://github.com/rabbitmq/rabbitmq-server/blob/master/priv/schema/rabbit.schema) and didn't see an entry for ``delegate_count``  and assume all that is needed as an entry there.

**Comment by michaelklishin** [comment]
The table in the docs are mostly unchanged from the classic format, they just list `rabbit.*` keys but your observations are correct. It's trivial to add.
