### ISSUE TITLE
Make it easier to delete queues that don't have a promotable master (for any reason)

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-server#1501]
Given the following queue:

```
"auto_delete": false,
"durable": false,
"exclusive": false,
"messages": 17,
"messages_ram": 17,
"messages_ready": 17,
"messages_ready_ram": 17,
"name": "manualsync-non_durable-2018.Feb.09-08:57:11.185",
"node": "rabbit@rmq0-ghost-queues",
"policy": "ha-all-manual",
"recoverable_slaves": null,
"slave_nodes": [
    "rabbit@rmq1-ghost-queues"
],
"state": "running",
"synchronised_slave_nodes": [
    "rabbit@rmq1-ghost-queues"
],
"vhost": "/"
```

With the following policy:

```
"apply-to": "all",
"definition": {
    "ha-mode": "all",
    "ha-sync-mode": "manual"
},
"name": "ha-all-manual",
"pattern": "^manualsync",
"priority": 0,
"vhost": "/"
```

The following is observed:

1. `rmq0-ghost-queues` is stopped
1. Queue slave running on `rmq1-ghost-queues` is promoted to master
1. `rmq0-ghost-queues` is started
1. A new queue slave is created on `rmq0-ghost-queues` - this remains unsynchronised
1. `rmq1-ghost-queues` is stopped
1. Queue slave running on `rmq0-ghost-queues` is not promoted to master because it's unsynchronised: `Mirrored queue 'manualsync-non_durable-2018.Feb.09-08:57:11.185' in vhost '/': Stopping all nodes on master shutdown since no synchronised slave is available`
1. `rmq1-ghost-queues` is started
1. Queue record in the `rabbit_queue` Mnesia table remains
1. Queue process doesn't get created on either nodes
1. Queue cannot be deleted, redefined or used

Queue can be deleted via:

1. `rabbitmqctl eval 'rabbit_amqqueue:internal_delete({resource, <<"/">>, queue, <<"manualsync-non_durable-2018.Feb.09-08:57:11.185">>}).'`
1. Restarting both nodes at the same time

Quick fix options:

1. Don't mirror non-durable queues
1. Use `ha-sync-mode: automatic` for mirrored non-durable queues. Caveat: for automatically sync-ing queues, keep them as empty as possible - syncing millions of messages or GBs of data on every node restart is known to trigger alarms and block all publishers for extended periods of time (hours, days, even forever in extreme scenarios).
1. Use mirrored durable queues instead, even when using `ha-sync-mode: manual`

https://ghost-queues.gcp.rabbitmq.com/ is available for inspection

![ghost-queues](https://user-images.githubusercontent.com/3342/36021263-2a94663e-0d7d-11e8-8a16-381b1ea20a03.png)

**Comment by gerhard** [comment]
Maybe interesting for #1492

**Comment by gerhard** [comment]
Having talked to @essen about this scenario, this is what we're thinking:

1. Users should be able to delete queues in an undefined state via the Management UI. The `DELETE /api/queues/vhost/name`  API endpoint should do the right thing and delete the queue even if the queue is in an undefined state.
1. AMQP `queue.delete` operation should do the right thing and delete the queue even if the queue is in an undefined state.
1. When this state is reached, `Mirrored queue 'manualsync-non_durable-2018.Feb.09-08:57:11.185' in vhost '/': Stopping all nodes on master shutdown since no synchronised slave is available`, we should also clean up the queue row from `rabbit_queue` Mnesia table
1. To guard against unclean shutdowns that do not get a chance of running the above step, on node startup, we should delete all non-durable queues for which no processes exist. This is a bit tricky since it might put too much pressure on Mnesia and will result in longer boot times. We are thinking to leave this step out and implement the first 3. If this issue is still mentioned, maybe consider implementing this step at that point in time.

What do you think?

**Comment by michaelklishin** [comment]
1 and 2 sound fairly safe. I'm not sure about 3: what if the node hosting master comes back, and quickly?

In 4 we have a chicken-and-egg problem since processes are started from a list of queues we have in the database. In fact, I'm quite sure we already delete all non-durable queues early.

**Comment by michaelklishin** [comment]
So this is expected behavior. We cannot delete such queues (the user never asked, they are not due for deletion due to the auto-delete flag, etc). It should be possible to delete such temporarily stopped queues manually.

Suggestions 1 and 2 make sense to me.

**Comment by gerhard** [comment]
Is it sensible to expect that when the node running the master shuts down, and there is no synchronised slave for a **non-durable** & **auto-delete** queue, that queue will be deleted an all messages will be lost?

To address your concern of the master coming back up quickly, maybe this operation could run on the node that used to be master and is now booting, meaning that it's either recovering from a crash or simply starting up normally, and therefore it was partitioned.

**Comment by michaelklishin** [comment]
Neither `exclusive` nor `auto-delete` really apply here. If a queue has no mirrors in sync and all mirrors are restarted, in theory we can consider deleting it but that will lead to claims that that is also a bug and we should never delete mirrored queues (e.g. we do not mirror exclusive queues to avoid such confusion).

We already have several hacks that work around scenarios if masters going away and quickly back up before queue consensus decisions migrate  to Raft.

So items 1 and 2 are fine with me, other options will shift the confusion elsewhere. It's an interplay between 3 features that were not meant to make sense together at all times. Promoting out-of-sync mirrors OR using durable queues for the data you don't want to lose makes a lot more sense than more and more implementation hacks.

**Comment by gerhard** [comment]
OK, that makes sense. What are your thoughts on promoting out-of-sync mirrors to masters? Should this be a manual operation? What information should the users have in order to make the best decision?

To me it makes sense to automatically promote the slave with the most messages, or the oldest slave if the number of messages is the same. What do others think?

**Comment by michaelklishin** [comment]
There is already an option that makes it possible to [promote out-of-sync mirrors](http://www.rabbitmq.com/ha.html#unsynchronised-mirrors). The user just has to opt in.

**Comment by gerhard** [comment]
Excellent! Should we promote this option by adding it to **Add / update a policy > Definition > HA** ?

![image](https://user-images.githubusercontent.com/3342/36606130-a4dfce4a-18ba-11e8-8a0d-92ca0d79344d.png)

**Comment by gerhard** [comment]
I've added the `ha-promote-on-shutdown: always` option to https://ghost-queues.gcp.rabbitmq.com/ (user: **demo** & pass: **demo**), we do not expect anymore ghost queues for `^manualsync-non_durable` queues.

**Comment by gerhard** [comment]
I agree. As long as we list `HA promote on shutdown ?` in the HA list of options I'm happy.

**Comment by michaelklishin** [comment]
@gerhard so what's the scope of this issue now? Making `queue.delete` more aggressive towards non-durable queues without an elected master and updating the docs?

**Comment by gerhard** [comment]
Yes, that sounds right to me. It's basically the first 2 points that I mentioned:

1. Users should be able to delete queues in an undefined state via the Management UI. The `DELETE /api/queues/vhost/name` API endpoint should do the right thing and delete the queue even if the queue is in an undefined state.
2. AMQP `queue.delete` operation should delete the queue even if the queue is in an undefined state.
