### ISSUE TITLE
Windows batch scripts and RMQ installation - issues with long names

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#1508]
As reported in this mailing list thread:

https://groups.google.com/d/topic/rabbitmq-users/mJdZw_-QHZ8/discussion

1. Batch scripts do not set certain epmd name env variables correctly:

The logic in these lines prevents `USE_LONGNAME` from being set in `rabbitmq-env-conf.bat`:

https://github.com/rabbitmq/rabbitmq-server/blob/master/scripts/rabbitmq-env.bat#L75-L88

And, as a bonus, they prevent the `RABBITMQ_USE_LONGNAME` env var from working, too.

2. [This line](https://github.com/rabbitmq/rabbitmq-server/blob/master/scripts/rabbitmq-service.bat#L147) will fail on Windows if longnames are in use. Solution is to port [these lines](https://github.com/rabbitmq/rabbitmq-server/blob/5598488204c7c762bd007e2732ca8e984b8a7302/scripts/rabbitmq-server#L72-L98) from the Unix startup scripts. This fix is required or else the service will be installed using node name `RabbitMQ` instead of what is specified by environment variables / config scripts.

**Comment by michaelklishin** [comment]
#1515 and #1516 were reverted due to CI failures that seem related.

**Comment by lukebakken** [comment]
Latest findings - using long names with `3.7.3` on Windows does not work with `rabbitmqctl`. I suspect it has to do with the fact that that name chosen when disterl starts is not a FQDN:

https://github.com/rabbitmq/rabbitmq-cli/blob/v3.7.x/lib/rabbitmq/cli/core/distribution.ex#L81-L104

If `longnames` are being used, then something like this should be used to in the case where `inet:get_rc()` does not return a `domain` value:

```
{ok, Hostname} = inet:gethostname(),
{ok,{hostent,FullHostname,[],inet,_,[_]}} = inet:gethostbyname(Hostname)
```

**Comment by lukebakken** [comment]
Turns out the above issue was due to setting `USE_LONGNAME="true"` rather than `USE_LONGNAME=true` - rabbitmq/rabbitmq-cli#244 will address that.
