### ISSUE TITLE
Autotuning of the number of async I/O threads

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#151]
See [this mailing list thread](https://groups.google.com/d/msg/rabbitmq-users/ijHVImbazFI/cxPtzoxKEUoJ).

I wonder if we can do autotuning that will work reasonably well on all supported platforms.

**Comment by binarin** [comment]
So is default value like ```16 * erlang:system_info(logical_processors_available)``` good enough?

**Comment by michaelklishin** [comment]
@binarin that sounds good but I'd add "but no fewer than 64".

**Comment by binarin** [comment]
Looks like detecting number of CPUs is not as simple as it seems on some OSes. Lev Walkin posted the following snippet in erlang-russian ML:
```
ncpus() ->
    case erlang:system_info(logical_processors_available) of
        unknown -> % Happens on Mac OS X.
            erlang:system_info(schedulers);
        N -> N
    end.
```

**Comment by michaelklishin** [comment]
@binarin combined with the "no fewer than 64" condition above, it sounds good to me. It's unlikely that there will be significantly more schedulers configured than there are logical cores. We might want to cap the maximum number, say, at 512 or 1024, too.
