### ISSUE TITLE
Messages with x-deaths from pre-3.5.1 versions cause queue crash on dead-lettering

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#152]
#78 needs to handle existing messages with `x-deaths`. See [this mailing list thread](https://groups.google.com/d/msg/rabbitmq-users/uQbeiWq5R3o/8QzpAhgbX6kJ).

**Comment by michaelklishin** [comment]
I think the right thing to do is to fold existing `x-deaths` by `{queue, reason}` pairs before trying to do anything with the counter.

**Comment by dumbbell** [comment]
Since RabbitMQ 3.5.1.
