### ISSUE TITLE
kernel.net_ticktime is not recognized in rabbitmq.conf (sysctl format)

### ISSUE THREAD

**Issue by CiCCkany** [rabbitmq/rabbitmq-server#1522]
* RabbitMQ version: 3.7.3
* Docker image: [3.7.3](https://github.com/docker-library/rabbitmq/blob/b5543df2789c16d8ea1c2119484378d4c23baa6c/3.7/debian/Dockerfile)

`kernel.net_ticktime` is not recognized as a valid option when it is set in rabbitmq.conf ([sysctl format](https://github.com/rabbitmq/rabbitmq-server/blob/v3.7.3/docs/rabbitmq.conf.example#L455)):
* rabbitmq.conf:
```
kernel.net_ticktime = 60
```
* RabbitMQ server log:
```
Config file generation failed 09:25:07.272 [error] You've tried to set kernel.net_ticktime, but there is no setting with that name.
09:25:07.272 [error]   Did you mean one of these?
09:25:07.310 [error]     collect_statistics
09:25:07.310 [error]     connection_max
09:25:07.310 [error]     default_vhost
09:25:07.310 [error] Error generating configuration in phase transform_datatypes
09:25:07.310 [error] Conf file attempted to set unknown variable: kernel.net_ticktime
BOOT FAILED
===========
Error description:
    rabbit:start_it/1 line 448
    rabbit:boot_error/2 line 848
    rabbit_lager:log_locations/0 line 59
    rabbit_lager:ensure_lager_configured/0 line 160
    rabbit_lager:lager_configured/0 line 167
    lager:list_all_sinks/0 line 317
    lager_config:get/2 line 71
    ets:lookup(lager_config, {'_global',handlers})
exit:generate_config_file
Log file(s) (may contain more information):
{"init terminating in do_boot",generate_config_file}
init terminating in do_boot (generate_config_file)

Crash dump is being written to: /var/log/rabbitmq/erl_crash.dump...done
```
It is recognized when it is set in advanced.config (Erlang format):
* advanced.config:
```
[{kernel, [{net_ticktime, 60}]}].
```

**Comment by michaelklishin** [comment]
I could not find any docs that claim that it is but adding `net_ticktime` to the schema is easy enough.

**Comment by CiCCkany** [comment]
@michaelklishin It is in the [rabbitmq.conf.example](https://github.com/rabbitmq/rabbitmq-server/blob/v3.7.3/docs/rabbitmq.conf.example#L455)

**Comment by acogoluegnes** [comment]
Not sure this is doable, as the `kernel` application is started and runs before the `rabbit` application. `rabbit_config` [needs to unload an application to update its configuration](https://github.com/rabbitmq/rabbitmq-server/blob/da988060c5557d453dd3de99a2e2f48f7f31fdfc/src/rabbit_config.erl#L68-L93), it logs this warning:
```
Unable to update config for app kernel from *.conf file. App is already running. Use advanced.config instead.
```

If there's no easy workaround, we'd better off keeping `kernel` settings in the advanced configuration and remove this line from the `rabbitmq.conf.example` file.

**Comment by michaelklishin** [comment]
@acogoluegnes good point. There’s `net_kernel:set_net_ticktime/{1,2}`, which we can call in a boot step. I wouldn’t mind moving the example to the advanced config but it is a fairly commonly used setting.

**Comment by acogoluegnes** [comment]
As per discussion with the team, we'll treat `kernel.net_ticktime` in a special way, avoiding the warning message for this entry in the kernel application configuration.

**Comment by michaelklishin** [comment]
I suggest we name it just `net_ticktime` to not suggest that other `kernel.*` keys may be configurable as well (which won't be the case).

**Comment by michaelklishin** [comment]
This issue ended up being more involved than we expected. See #1524 for discussion. There's a chance we will consider it to not be worth the potential risk.
