### ISSUE TITLE
unable to connect to node rabbit@localhost: nodedown , despite I copied the cookie all over.

### ISSUE THREAD

**Issue by yanivg111** [rabbitmq/rabbitmq-server#1540]
Thank you for using RabbitMQ and for taking the time to report an
issue.

## Does This Belong to GitHub or RabbitMQ Mailing List?

*Important:* please first read the `CONTRIBUTING.md` document in the
root of this repository. It will help you determine whether your
feedback should be directed to the RabbitMQ mailing list [1] instead.

## Please Help Maintainers and Contributors Help You

In order for the RabbitMQ team to investigate your issue, please provide
**as much as possible** of the following details:

* RabbitMQ version
* Erlang version
* RabbitMQ server and client application log files
* A runnable code sample, terminal transcript or detailed set of
  instructions that can be used to reproduce the issue
* RabbitMQ plugin information via `rabbitmq-plugins list`
* Client library version (for all libraries used)
* Operating system, version, and patch level

Running the `rabbitmq-collect-env` [2] script can provide most of the
information needed. Please make the archive available via a third-party
service and note that **the script does not attempt to scrub any
sensitive data**.

If your issue involves RabbitMQ management UI or HTTP API, please also provide
the following:

 * Browser and its version
 * What management UI page was used (if applicable)
 * How the HTTP API requests performed can be reproduced with `curl`
 * Operating system on which you are running your browser, and its version
 * Errors reported in the JavaScript console (if any)

This information **greatly speeds up issue investigation** (or makes it
possible to investigate it at all).  Please help project maintainers and
contributors to help you by providing it!

1. https://groups.google.com/forum/#!forum/rabbitmq-users
2. https://github.com/rabbitmq/support-tools/blob/master/scripts/rabbitmq-collect-env

**Comment by yanivg111** [comment]
Hi everyone,
I know there are a lot of stuff about this issue but I was unable to find the correct answer.
I'm following this guide trying to set up a pacemaker cluster for RabbitMQ (I know there is a newer way to set rabbitmq clustering but I've been asked to set this one):
https://www.rabbitmq.com/pacemaker.html

I've set up two ubuntu 16.04 machhines called rabbitmq1 & rabbitmq2 (rabbitmq version 3.6.15 Erlang 20.2).
I was able to set DRBD and Corosync succfully with a reource of floating IP between them.
Both machines in the same VLAN and able to ping eachother by name (firewall is off).

After all was set I added a this reource to pacemaker:
configure primitive bunny ocf:rabbitmq:rabbitmq-server params mnesia_base="/media/drbd1"

However this resource showing in error when I run "crm status":
bunny  (ocf::rabbitmq:rabbitmq-server):        FAILED (unmanaged)[ rabbitmq2 rabbitmq1 ]

when I try to investigate it by command "pcs resource debug-start bunny" I see this output:

stderr: INFO: Status of node rabbit@localhost Error: unable to connect to node rabbit@localhost: nodedown DIAGNOSTICS =========== attempted to contact: [rabbit@localhost] rabbit@localhost: erlang-solutions_1.0_all.deb connected to epmd (port 4369) on localhost erlang-solutions_1.0_all.deb epmd reports node 'rabbit' running on port 25672 erlang-solutions_1.0_all.deb TCP connection succeeded but Erlang distribution failed erlang-solutions_1.0_all.deb Hostname mismatch: node "rabbit@rabbitmq1" believes its host is different. Please ensure that hostnames resolve the same way locally and on "rabbit@rabbitmq1" current node details: - node name: 'rabbitmq-cli-65@rabbitmq1' - home dir: /var/lib/rabbitmq - cookie hash: O9bMZ3LMnkSPaakjdRYHuw==
 >  stderr: ERROR: Unexpected return from rabbitmqctl -n rabbit@localhost status: 69

Then I run this command "rabbitmqctl -n rabbit@localhost status" and get this output:

Error: unable to connect to node rabbit@localhost: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@localhost]

rabbit@localhost:
  * connected to epmd (port 4369) on localhost
  * epmd reports node 'rabbit' running on port 25672
  * TCP connection succeeded but Erlang distribution failed

  * Hostname mismatch: node "rabbit@rabbitmq1" believes its host is different. Please ensure that hostnames resolve the same way locally and on "rabbit@rabbitmq1"


current node details:
- node name: 'rabbitmq-cli-30@rabbitmq1'
- home dir: /var/lib/rabbitmq
- cookie hash: O9bMZ3LMnkSPaakjdRYHuw==

I tried copying this erlang cookie file to all usere home folder from this location /var/lib/rabbitmq/.erlang.cookie (both to the home folder of root user and to the home folder or rabbitmq user) but its not helping.
what am I doing wrong?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This is covered in quite a bit of detailed [in a dedicated doc section](http://www.rabbitmq.com/clustering.html#erlang-cookie).
