### ISSUE TITLE
Bintray apt repository misspell "artful" to "rtful"

### ISSUE THREAD

**Issue by cwchien** [rabbitmq/rabbitmq-server#1545]
Hi there,

I noticed the [dists](https://dl.bintray.com/rabbitmq/debian/dists/) path misspell "**a**rtful" to "rtful".
It stops apt from finding the artful Release file.

Thanks.

**Comment by michaelklishin** [comment]
This belongs to a different repo, we will see what can be done.

**Comment by michaelklishin** [comment]
We're investigating this, so far it doesn't seem to be a typo. The name gets mangled/chopped somewhere in the pipeline.

**Comment by cwchien** [comment]
OK. Thank a lot :)

**Comment by michaelklishin** [comment]
Update: we've engaged Bintray support a few weeks back, no resolution so far.
