### ISSUE TITLE
Per-vhost connection limit can be exceeded

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#1547]
Reported in this [`rabbitmq-users`](https://groups.google.com/d/topic/rabbitmq-users/yZ8-jbrnCn0/discussion) thread.

Steps to reproduce:

* Set `max-connections` to `128` for `/` vhost - `rabbitmqctl set_vhost_limits -p / '{"max-connections": 128}'`
* Run the Python `receive.py` tutorial program in a loop
    ```
    for ((i=0;i < 130;i++)) do; python ./receive.py & done
    ```
* Observe in the management UI that there are `130` connections
* Run another `python ./receive.py` process and the connection will be rejected
* If you insert `sleep 0.25` in the `for` loop the `129`th connection is rejected

It appears that the dirty read in [this code](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_connection_tracking.erl?utf8=%E2%9C%93#L243-L264) may contribute to this scenario.

**Comment by michaelklishin** [comment]
The limit can be exceeded in a short burst. This intentional: we decided to accept a certain inaccuracy
when the limit is loaded over doing a cluster-wide transaction on a potentially hot and critically important (for the apps) code path.
