### ISSUE TITLE
RabbitMQ 3.7.4 unpredictably fails to start with rabbit_peer_discovery_classic_config

### ISSUE THREAD

**Issue by triggetry** [rabbitmq/rabbitmq-server#1548]
When RabbitMQ is configured to use _rabbit_peer_discovery_classic_config_ for initial cluster formation the initial startup of RabbitMQ sometimes unpredictably fails with an erlang crash report. 

## Used Setup
* two (virtual) hosts on same physical machine. Each virtual host runs one docker container containing RabbitMQ
* cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
* Docker Network Mode: host
* Docker hosts and docker containers based on rhel 7.2 
* Erlang Version 19.3.6.5

## Observations
* The probability of the occurrence is maximized by minimizing the delay between the individual container starts. (Only when starting the containers virtually at the same time the issue occurs sometimes).
* On slow hardware the issue occurs less frequently (still using the very same configuration)
* On more powerful hardware the issue occurs more frequently.
* The frequency of occurrence is much lower if the test system is under load (caused by unrelated processes)
* When adding a delay of two seconds between the startup of the docker containers the problem does not occur anymore
* When adding a random delay within the start script of the containers (before the rabbit server is started) the problem does not occur anymore

## Potential External Causes already ruled out
* Issues with the file system: The problem also occurs if the rabbit nodes are configured as ram nodes
* Docker startup race conditions that lead to some resources not being available in time: The issue also occurs if the containers are started a few seconds after creation and have a constant delay at the beginning of the start script.
* The warnings about the erlang VM running in a native encoding of latin1 does not seem to have an influence on this issue. Also in docker image configurations with the locale set to UTF-8 (where this warning is not printed at startup) the issue occurs with the same frequency.

The [attached log](https://github.com/rabbitmq/rabbitmq-server/files/1808433/logs.zip) files were captured at 5 events when the issue simultaneously occurred on both hosts. Each log contains the corresponding crash report.

**Comment by lukebakken** [comment]
`rabbit_peer_discovery_classic_config` requires a [list of nodes](https://www.rabbitmq.com/cluster-formation.html#peer-discovery-classic-config) in its configuration.

Please provide enough instructions or a script to *exactly* reproduce your environment:

* Complete RabbitMQ configuration files
* Host name values
* Docker container version

Ideally we'd have instructions to reproduce this outside of docker to remove that as a variable. Thank you.

**Comment by michaelklishin** [comment]
They all come down to

```
system_limit,rabbit_exchange
```

So the internal database failed to create a set of tables. A quick inspection of OTP codebase suggests that `system_limit` is used for cases that have little to do with kernel limits but nonetheless it's not something that RabbitMQ is responsible for or something that's widely reported. This is mailing list material.

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/vzyWRVKqIiQ).

There is a couple of interesting scenarios that go beyond peer discovery but come down to the same chicken-and-egg parallel cluster formation issue. If we identify things we can improve in a backward-compatible way, we will file new focused issues. However, a random startup delay for such scenarios [with parallel node startup on initial boot] is a good idea anyway, which we will mention in the Cluster Formation guide.

Thank you for providing the logs, @triggetry.
