### ISSUE TITLE
Auto-delete Queues Went into a Bad State

### ISSUE THREAD

**Issue by ioradu** [rabbitmq/rabbitmq-server#1553]
We are running a 4-node RabbitMQ-3.7.3 cluster with Erlang-20.2 and we encountered an issue where some auto-delete queues went into a state where we could not delete them
using both HTTP API and management UI (HTTP requests timed out). Also, the UI displayed NaN in Ready, Unacked, Persistent, Total and Consumer Count columns.
From our perspective it looked like the queues should have been deleted automatically since no consumer was attached at that point.
Finally, we managed to delete them using:

> rabbitmqctl eval '{ok, Q} = rabbit_amqqueue:lookup(rabbit_misc:r(<<"vhost">>, queue, <<"queue">>)), rabbit_amqqueue:delete_crashed(Q).'

Unfortunately, we don't have a way to reproduce this bug since it happened only once since we started using this cluster 2 weeks ago.
I've seen that someone reported a similar issue on RMQ users mailing list (https://groups.google.com/forum/#!topic/rabbitmq-users/mEkUQ46CRsI)

Technical info:
* RabbitMQ version: 3.7.3
* Erlang version: 20.2
* Operating System: RHEL 7
* RabbitMQ client: kombu

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
We cannot identify the cause without full server logs.

**Comment by michaelklishin** [comment]
There's already #1501 and #1549 for making it possible to delete such queues. There is no single reason that can lead queue masters to become unresponsive and in most cases there are no known ways to reproduce. Unfortunately we cannot fix an issue that we cannot reproduce at least some of the time.
