### ISSUE TITLE
Memory monitor isn't there when FHC assumes it to be

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#157]
See [this thread](https://groups.google.com/forum/#!topic/rabbitmq-users/ydTzwg7Gjkk). My reading of it is that VM monitor isn't there when FHC assumes it is.

**Comment by michaelklishin** [comment]
Memory monitor is started by `rabbit_alarm`
which is started later than `file_handle_cache`, so if the FHC needs to go read
a lot of data from disk very early on, there's a race condition.

**Comment by dumbbell** [comment]
Since RabbitMQ 3.5.2.
