### ISSUE TITLE
Need ability to install and run full suite without sudo

### ISSUE THREAD

**Issue by GregTD42** [rabbitmq/rabbitmq-server#1574]
Last year, michaelklishin commented:

Even a suggestion to not require sudo for CLI tools in e.g. Debian package — not something we would agree to, quite obviously — would be considered an actionable issue and not just a discussion that belongs to the mailing list.Something one of the engineers can assign and begin working on because there's a clear problem definition and enough information to at least get started.
--

So, here's the reason for the request.  i work in a corporate & medical environment.  I am not going to get sudo access to any of our servers, because I'm a developer, not a system admin.

We have installed (without using sudo) Apache Airflow (in /apps/dist/airflow).  I've been tasked with figuring out if we can use something like Celery with our Airflow installation.  Celery defaults to using RabbitMQ, which brings me here.

I'm hoping you'll reconsider the "not something we would agree to, quite obviously."  The more seriously the corporate world takes security, the fewer people who will have sudo access.  Regardless of how your product behaves when installed with apt-get or yum, those of us stuck in this situation just can't use your product if you don't provide a way for us to install and run it non-sudo.

Thank you,
Greg

**Comment by michaelklishin** [comment]
There is a way to install and run RabbitMQ without `sudo`, it's called the [generic binary release](http://www.rabbitmq.com/install-generic-unix.html). Uncompress the package anywhere you need and run `./sbin/rabbitmq-server`, then `./sbin/rabbitmqctl` and such to do just about anything that will not require binding to ports below < 1024.

**Comment by michaelklishin** [comment]
FTR, the last time the same question was asked was in #1076. It was given the same answer: use the generic binary distribution, not a Debian or RPM package which will require `sudo` (and that is hardly an uncommon requirement for a data service).

There are options to run RabbitMQ locally without having `sudo` and using , too: run it in Vagrant (or Docker or similar) which provide have `sudo` and use local TCP port forwarding to forward local port(s) to those in the Vagrant VM. Celery must have a way to configure the port.

This is 100% mailing list material.

**Comment by michaelklishin** [comment]
[Debian](http://www.rabbitmq.com/install-debian.html#sudo-requirements), RPM and generic binary build installation guides were updated to mention their respective `sudo` requirements.
