### ISSUE TITLE
make -j <num> dist fails, when num > 1

### ISSUE THREAD

**Issue by ioradu** [rabbitmq/rabbitmq-server#1579]
I am trying to build `rabbitmq-server-3.7.4` (`rabbitmq-server_3.7.4.orig.tar.xz`) from sources.

When I use `make -j 1 dist`, it works perfectly while `make -j 16 dist` (or any number greater than 1), I got the following error:

```bash
Generated escript escript/rabbitmqctl with MIX_ENV=dev
 GEN    escript/rabbitmq-plugins
ln: failed to create hard link ‘escript/rabbitmq-plugins’: File exists
Makefile:88: recipe for target 'escript/rabbitmq-plugins' failed
make[2]: *** [escript/rabbitmq-plugins] Error 1
```

**Comment by michaelklishin** [comment]
Like nearly everything that's related to packaging and release production, this belongs to https://github.com/rabbitmq/rabbitmq-server-release/.

**Comment by ioradu** [comment]
Thanks. I'll post it there then.
