### ISSUE TITLE
Block queue.declare when a resource alarm is in effect

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#158]
Suggested [in this thread](https://groups.google.com/forum/#!topic/rabbitmq-users/z6LIRtsKbDY).

**Comment by pranjaljain** [comment]
@michaelklishin Is this the behaviour with the queues with rabbitmq 3.7?
Does the queue.declare gets blocked when resource alarms are in effect?

**Comment by michaelklishin** [comment]
This is not the behavior in 3.7 or 3.8. With a way to configure the maximum number of queues via [virtual host limits](https://www.rabbitmq.com/vhosts.html#limits) this is unlikely to be worked on, at least without more obvious demand.
