### ISSUE TITLE
rabbitmq  Generic server terminating because of msg_store_transient or gc

### ISSUE THREAD

**Issue by thao6626** [rabbitmq/rabbitmq-server#1584]
Hi, rabbitmq server terminated suddenly, i found the following log about the terminating.

From the log, I guess the reason is about disk usage, but i check the monitor data, the disk usage is low and normal. So, I do not understand why the rabbitmq server terminated suddenly. The log information is not much exact for me to understand it.

Please help to find the reason why the rabbitmq terminated.  

Thanks very mch !!!!

The extra infomation and log are listed:

* RabbitMQ version: RabbitMQ 3.6.10,
* Erlang version: Erlang 19.1
* RabbitMQ plugin information via `rabbitmq-plugins list`: 
`
[e ] amqp_client                       3.6.10

[e ] cowboy                            1.0.4

[e ] cowlib                            1.0.2

[  ] rabbitmq_amqp1_0                  3.6.10

[  ] rabbitmq_auth_backend_ldap        3.6.10

[  ] rabbitmq_auth_mechanism_ssl       3.6.10

[  ] rabbitmq_consistent_hash_exchange 3.6.10

[  ] rabbitmq_event_exchange           3.6.10

[  ] rabbitmq_federation               3.6.10

[  ] rabbitmq_federation_management    3.6.10

[  ] rabbitmq_jms_topic_exchange       3.6.10

[E ] rabbitmq_management               3.6.10

[e ] rabbitmq_management_agent         3.6.10

[  ] rabbitmq_management_visualiser    3.6.10

[  ] rabbitmq_mqtt                     3.6.10

[  ] rabbitmq_recent_history_exchange  3.6.10

[  ] rabbitmq_sharding                 3.6.10

[  ] rabbitmq_shovel                   3.6.10

[  ] rabbitmq_shovel_management        3.6.10

[  ] rabbitmq_stomp                    3.6.10

[  ] rabbitmq_top                      3.6.10

[  ] rabbitmq_tracing                  3.6.10

[  ] rabbitmq_trust_store              3.6.10

[e ] rabbitmq_web_dispatch             3.6.10

[  ] rabbitmq_web_mqtt                 3.6.10

[  ] rabbitmq_web_mqtt_examples        3.6.10

[  ] rabbitmq_web_stomp                3.6.10

[  ] rabbitmq_web_stomp_examples       3.6.10

[  ] sockjs                            0.3.4

`

* Operating system, version, and patch level: Linux version 3.2.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 SMP Debian 3.2.88-1

`=ERROR REPORT==== 24-Apr-2018::03:46:31 ===
** Generic server <0.269.0> terminating
** Last message in was {'$gen_cast',{combine,129093,129092}}
** When Server state == {state,
                            {dict,0,16,16,8,80,48,
                                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            [#Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>,
                             #Fun<rabbit_msg_store.15.27512095>],
                            {gc_state,
                                "/home/rabbitmq/mnesia/rabbit@xxxxx-hostname/msg_store_transient",
                                rabbit_msg_store_ets_index,
                                {state,4128864,
                                    "/home/rabbitmq/mnesia/rabbit@xxxxx-hostname/msg_store_transient"},
                                4063327,4194401,<0.268.0>}}
** Reason for termination == 
** {{badmatch,[{file_summary,129093,11193583,129092,129094,16783778,true,1}]},
    [{rabbit_msg_store,combine_files,3,
                       [{file,"src/rabbit_msg_store.erl"},{line,1956}]},
     {rabbit_msg_store_gc,attempt_action,3,
                          [{file,"src/rabbit_msg_store_gc.erl"},{line,124}]},
     {rabbit_msg_store_gc,handle_cast,2,
                          [{file,"src/rabbit_msg_store_gc.erl"},{line,85}]},
     {gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1048}]},
     {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,257}]}]}

=INFO REPORT==== 24-Apr-2018::03:46:31 ===
Stopping message store for directory '/home/rabbitmq/mnesia/rabbit@xxxxx-hostname/msg_store_transient'
=ERROR REPORT==== 24-Apr-2018::03:46:32 ===
** Generic server msg_store_transient terminating
** Last message in was {'EXIT',<0.269.0>,
                           {{badmatch,
                                [{file_summary,129093,11193583,129092,129094,
                                     16783778,true,1}]},
                            [{rabbit_msg_store,combine_files,3,
                                 [{file,"src/rabbit_msg_store.erl"},
                                  {line,1956}]},
                             {rabbit_msg_store_gc,attempt_action,3,
                                 [{file,"src/rabbit_msg_store_gc.erl"},
                                  {line,124}]},
                             {rabbit_msg_store_gc,handle_cast,2,
                                 [{file,"src/rabbit_msg_store_gc.erl"},
                                  {line,85}]},
                             {gen_server2,handle_msg,2,
                                 [{file,"src/gen_server2.erl"},{line,1048}]},
                             {proc_lib,wake_up,3,
                                 [{file,"proc_lib.erl"},{line,257}]}]}}
** When Server state == {msstate,
                            "/home/rabbitmq/mnesia/rabbit@xxxxx-hostname/msg_store_transient",
                            rabbit_msg_store_ets_index,
                            {state,4128864,
                                "/home/rabbitmq/mnesia/rabbit@xxxxx-hostname/msg_store_transient"},
                            129094,#Ref<0.1.516947969.51911>,
                            {dict,0,16,16,8,80,48,
                                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            undefined,22330234,44702177,`

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
GC here refers to "file compaction", not memory GC. Without a way to reproduce at least some of the time we cannot suggest much.
