### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by levshanton** [rabbitmq/rabbitmq-server#1585]
RabbitMQ link for download is unavailable:
https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.3/rabbitmq-server-3.7.3.exe
So downloading with chocolatey is unavailable too

**Comment by michaelklishin** [comment]
The link does work for me. The release is still there. Perhaps there was a GitHub connectivity issue of sorts.

**Comment by michaelklishin** [comment]
As [installation docs](http://www.rabbitmq.com/download.html) suggest, binary release artefacts can be obtained from multiple sources.

**Comment by michaelklishin** [comment]
I see @levshanton is Russia-based. Russian Internet censorship agency has been blocking subnets of AWS, Google Cloud, Azure, Digital Ocean and so on en masse over the last week or so (we are talking millions of IP addresses). I wouldn't be surprised if GitHub was affected at some point.

Get on an out-of-country VPN to compare.

**Comment by michaelklishin** [comment]
Our team confirmed that the file can be downloaded successfully from

 * Spain
 * The UK
 * France
 * North America (US and Canada, east and west coasts alike)
