### ISSUE TITLE
Connecting process with rabbitmq is too long

### ISSUE THREAD

**Issue by Sarga** [rabbitmq/rabbitmq-server#1592]
Hello.

We are using
RabbitMQ server - 3.7.4 (hipe enabled)
Erlang - 20.3
OS - Debian 8.10, kernel 4.9.30-2+deb9u2~bpo8+1
php amqp extension - 1.9.3

rabbitmq config
```
 [
  {rabbit, [
    {tcp_listen_options, [
         {backlog,       128},
         {nodelay,       true},
         {linger,        {true, 0}},
         {exit_on_close, false}
    ]},
    {hipe_compile, true},
    {log_levels, [{connection, warning, debug}]},
    {vm_memory_high_watermark, "4096M"},
    {vm_memory_high_watermark_paging_ratio, 0.9},
    {default_user, <<"guest">>},
    {default_pass, <<"guest">>}
  ]},
  {kernel, [
    {inet_default_connect_options, [{nodelay, true}]},
    {inet_default_listen_options, [{nodelay, true}]}
  ]}
,
  {rabbitmq_management, [
    {listener, [
      {port, 15672}
    ]}
  ]}
].
```

plugin list
```
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status: * = running on rabbit@devserver
 |/
[  ] rabbitmq_amqp1_0                  3.7.4
[  ] rabbitmq_auth_backend_cache       3.7.4
[  ] rabbitmq_auth_backend_http        3.7.4
[  ] rabbitmq_auth_backend_ldap        3.7.4
[  ] rabbitmq_auth_mechanism_ssl       3.7.4
[  ] rabbitmq_consistent_hash_exchange 3.7.4
[  ] rabbitmq_event_exchange           3.7.4
[  ] rabbitmq_federation               3.7.4
[  ] rabbitmq_federation_management    3.7.4
[  ] rabbitmq_jms_topic_exchange       3.7.4
[E*] rabbitmq_management               3.7.4
[e*] rabbitmq_management_agent         3.7.4
[  ] rabbitmq_mqtt                     3.7.4
[  ] rabbitmq_peer_discovery_aws       3.7.4
[  ] rabbitmq_peer_discovery_common    3.7.4
[  ] rabbitmq_peer_discovery_consul    3.7.4
[  ] rabbitmq_peer_discovery_etcd      3.7.4
[  ] rabbitmq_peer_discovery_k8s       3.7.4
[  ] rabbitmq_random_exchange          3.7.4
[  ] rabbitmq_recent_history_exchange  3.7.4
[  ] rabbitmq_sharding                 3.7.4
[  ] rabbitmq_shovel                   3.7.4
[  ] rabbitmq_shovel_management        3.7.4
[  ] rabbitmq_stomp                    3.7.4
[  ] rabbitmq_top                      3.7.4
[  ] rabbitmq_tracing                  3.7.4
[  ] rabbitmq_trust_store              3.7.4
[e*] rabbitmq_web_dispatch             3.7.4
[  ] rabbitmq_web_mqtt                 3.7.4
[  ] rabbitmq_web_mqtt_examples        3.7.4
[  ] rabbitmq_web_stomp                3.7.4
[  ] rabbitmq_web_stomp_examples       3.7.4
```

Periodically we trace that the connecting process with rabbitmq is too long (longer than 50 ms).

To exclude the problems with the network, our programmer has wrote a test script, which I’ve ran on the same server with rabbitmq. Also, I’ve removed all the loading from the server before running.
As a result, we see that at local execution, the time for connection and authorization sometimes increases

08/05/2018 18: 40: 30.000 1009 ms
08/05/2018 18: 40: 51.000 1128 ms
08/05/2018 18: 41: 40.000 1009 ms

 test script
```
<?php
$credentials = [
    'host' => '127.0.0.1',
    'login' => 'login',
    'password' => 'password',
];
$connection = new \AMQPConnection($credentials);
/**
 * @param AMQPConnection $connection
 *
 * @throws AMQPConnectionException
 */
function connect(\AMQPConnection $connection) {
    echo '.';
    $start = microtime(true);
    $connection->connect();
    $elapsedTime = round((microtime(true) - $start) * 1000);
    if ($elapsedTime > 50) {
        echo PHP_EOL . ((new \DateTime())->format('d/m/Y H:i:s.v')) . ' ' . $elapsedTime . ' ms' . PHP_EOL;
    }
    $connection->disconnect();
}
while (true) {
    try {
        connect($connection);
    } catch (\AMQPConnectionException $e) {
        echo 'Connection exception: ' . $e->getMessage();
    }
    usleep(300000);
}
```

 
I assume that the time increases at the authorization stage. Because the connection is complete locally.
Tell me please:

1) Am I right about authorization? Perhaps this problem is already known
2) Is it possible to somehow measure the authorization time in the rabbitmq itself? Because apparently, the php extension is not able to complete connect and pass the authorization separately.
3) Perhaps you can tell me how else I can debug it

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
All messaging protocols RabbitMQ supports assume that connections are long lived. This is not always possible with PHP but your code demonstrates the worst possible anti-pattern with every other client that doesn't have PHP's limitations.

Opening a connection is a multi-step negotiation process before you even get to authentication and virtual host access check (most of what really is "authorisation" happens later when a client tries to perform an operation, which your code does not). In other words, it is multiple round trips. Setting up a TCP connection and doing multiple round trips is significantly more expensive than any "authorisation" code in RabbitMQ.

You can easily see this in a [Wireshark traffic capture](https://www.rabbitmq.com/amqp-wireshark.html).

Don't open and close a connection per operation.
