### ISSUE TITLE
Reduce channel_max default to about 2K

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#1593]
We see scenarios in which applications leak channels and in turn server resources year after year. A reasonably low default would produce visible failures in such applications early on, before they put a strain in the node they are connected to.

The default is not particularly scientific. It's hard to justify more than 1K channels per connection in 99% of cases, so let's double it to give existing applications some head room.

**Comment by gerhard** [comment]
I've noticed that [`connection_max` defaults to `infinity`](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/tcp_listener_sup.erl#L52). Would it make sense to pick a sane default here as well, possibly the same one?

**Comment by michaelklishin** [comment]
100K connections can be perfectly reasonable. 100K channels never is.

**Comment by gerhard** [comment]
OK, in which case I can see 2 options:

1. Default `connection_max` to `100000`
1. Leave `connection_max` unchanged and rely on the OS file descriptor limit, even if this is shared between actual files (I'm thinking queue segments) and TCP sockets.

This is what other stateful services are doing:
* PostgreSQL has  [`max_connections` with a default of `100`](https://www.postgresql.org/docs/current/static/runtime-config-connection.html#GUC-MAX-CONNECTIONS)
* Cassandra has [`native_transport_max_concurrent_connections` with a default of `-1`](https://docs.datastax.com/en/cassandra/2.1/cassandra/configuration/configCassandra_yaml_r.html#configCassandra_yaml_r__native_transport_max_concurrent_connections)
* IBM MQ has [`TCPChannels` with a default of `200`](https://www.ibm.com/support/knowledgecenter/SSFKSJ_7.5.0/com.ibm.mq.ref.dev.doc/q102890_.htm)
* ActiveMQ has [`maximumConnections ` with a default of `2^31-1`](https://github.com/apache/activemq/blob/master/activemq-client/src/main/java/org/apache/activemq/transport/tcp/TcpTransportServer.java#L123)
