### ISSUE TITLE
Add user-provided connection name to connection.closed events

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#1596]
That can be useful, in particular since connection process PIDs can't/shouldn't be used by non-BEAM programming languages.

See [this rabbitmq-users thread](https://groups.google.com/d/msg/rabbitmq-users/QHcZpMeTe4E/l2999FW8BAAJ).

If no user-provided connection name is available, the key should probably be excluded: this would make most sense to rabbitmq-event-exchange consumers.

**Comment by hairyhum** [comment]
I'm not sure it will be useful in that specific case, because there is the `name` field already enough to identify a connection. And it is in fact used in the management for that. Still might be useful for something else.
