### ISSUE TITLE
Unable to connect to RabbitMQ

### ISSUE THREAD

**Issue by yarodevuci** [rabbitmq/rabbitmq-server#1598]
I am using ubuntu, When I run flask server on EC2 directly I have no problem to connect to rabbitMq from iOS device, but when I move server to apache2 and use mod wsgi I am unable to connect to it
Anyone know what could be the issue?
RabbitMQ v: 3.6.15 Erlang 18.3

**Comment by lukebakken** [comment]
Please post this to [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users). In addition, this question appears to be out-of-scope for RabbitMQ - please provide details as to exactly how Apache 2 and `mod_wsgi` fit in.
