### ISSUE TITLE
failed_to_unzip_plugin, autocluster, "/usr/lib/rabbitmq/lib/rabbitmq_server-3.6.13/plugins/autocluster-0.10.0.ez", enfile

### ISSUE THREAD

**Issue by Zhan-Jie** [rabbitmq/rabbitmq-server#1605]
rabbitmq cluster is running on kubernetes. After the rabbitmq pods were deleted and host VMs were restarted， one rabbitmq node failed to unzip autocluster plugin . 
ERROR stack trace:
Stack trace:
   [{rabbit_plugins,prepare_plugin,2,
                    [{file,"src/rabbit_plugins.erl"},{line,281}]},
    {rabbit_plugins,'-prepare_plugins/1-lc$^0/1-0-',2,
                    [{file,"src/rabbit_plugins.erl"},{line,213}]},
    {rabbit_plugins,prepare_plugins,1,
                    [{file,"src/rabbit_plugins.erl"},{line,213}]},
    {rabbit,broker_start,0,[{file,"src/rabbit.erl"},{line,300}]},
    {rabbit,start_it,1,[{file,"src/rabbit.erl"},{line,424}]},
    {init,start_em,1,[]},
    {init,do_boot,3,[]}]

[rabbit-logs.zip](https://github.com/rabbitmq/rabbitmq-server/files/2024849/rabbit-logs.zip)

**Comment by michaelklishin** [comment]
The nodes do not do anything sophisticated with plugin archives: they, well, unzip them into an "plugin expansion" directory. Which must exist and be writeable. There is nothing specific to Kubernetes about that. I suspect that using a stateful set — which makes sense and [is highly recommended for other reasons](http://www.rabbitmq.com/cluster-formation.html#peer-discovery-k8s) — should take care of that.

According to the log, the error is `enfile` which [suggests](http://www.virtsync.com/c-error-codes-include-errno) that the node needs its [file descriptor limit](http://www.rabbitmq.com/networking.html#tuning-for-large-number-of-connections-open-file-handles-limit) to be increased.
