### ISSUE TITLE
Erlang/OTP 21 Compatibility

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#1616]
Erlang/OTP 21 has [plenty of breaking changes](http://www.erlang.org/news/123), some of which affect RabbitMQ, our build system and dependencies. This issue is a publicly available "umbrella issue" that can be used to monitor progress on the OTP 21 compatibility track.

Note that Elixir is only [OTP 21-compatible](https://github.com/elixir-lang/elixir/issues/6611) starting with 1.6.6, although 1.6.5 was "compatible enough" for us to make progress with it.

Known incompatibilities and other new features that affect us discovered so far:

 * OTP-14692 breaks compilation without extra compiler options that silence warnings
 * New logging subsystem breaks certain assumptions in Lager
 * We've observed issues with client connection handshake timeouts that we cannot reproduce on OTP 20
 * Regression that breaks erl_call: [ERL-634](https://bugs.erlang.org/browse/ERL-634)
 * Regression that breaks all tests that use httpc: [ERL-636](https://bugs.erlang.org/browse/ERL-636)
 * Major regression in `os:getenv/1` on Windows: [ERL-644](https://bugs.erlang.org/browse/ERL-644) addressed in `21.0.1` (republished as `21.0`)
 * Support for some (insecure) cipher suites in TLS has been removed or disabled by default
 * OTP-14370 may affect CLI tools test suite and likely all multi-node test suites
 * OTP-14928 may require changes to server scripts
 * OTP-14346 may require changes to RabbitMQ server scripts
 * OTP-13295 seems to cause extra logging in CLI tools which may need silencing
 * OTP-15001 may have an effect on connection error handling
 * OTP-14961 is potentially useful for more detailed memory allocators info
 * OTP-14902 may affect the Erlang client
 * OTP-14594 may have positive effects: requires benchmarking
 * OTP-15087 (the `OTP_RELEASE` macro) can be potentially helpful

Specific contained tasks:

 * [x] rabbit_common compiles
 * [x] core server compiles
 * [x] rabbitmq-cli compiles
 * [x] rabbitmq-management compiles
 * [x] rabbitmq-amqp1.0 compiles
 * [x] rabbitmq-stomp compiles
 * [x] rabbitmq-mqtt compiles
 * [x] Erlang AMQP 0-9-1 client compiles
 * [x] Erlang AMQP 1.0 client compiles
 * [x] rabbitmq-federation compiles
 * [x] rabbitmq-shovel compiles
 * [x] rabbitmq-trust-store compiles
 * [x] All other plugins in the umbrella compile
 * [x] rabbit_common passes tests
 * [x] Nodes can start and stop, including using CT helpers
 * [x] Nodes can accept client connections and complete AMQP 0-9-1 handshake
 * [x] `gmake ct-fast` in core server passes
 * [x] AMQP 0-9-1 Erlang client passes tests
 * [x] rabbitmq-cli passes tests
 * [x] rabbitmq-management passes tests
 * [x] core server with necessary plugins passes client test suites
 * [x] rabbitmq-amqp1.0 passes tests
 * [x] rabbitmq-stomp passes tests
 * [x] rabbitmq-mqtt passes tests
 * [x] rabbitmq-shovel passes tests
 * [x] rabbitmq-federation passes tests
 * [x] rabbitmq-peer-discovery-k8s passes tests
 * [x] rabbitmq-peer-discovery-etcd passes tests
 * [x] rabbitmq-peer-discovery-consul passes tests
 * [x] rabbitmq-peer-discovery-aws passes tests
 * [x] rabbitmq-trust-store passes tests 
 * [x] rabbitmq-top is updated to handle new ETS table info items
 * [x] [Lager supports OTP 21](https://github.com/erlang-lager/lager/issues/455) ([as of `3.6.3`](https://github.com/erlang-lager/lager/commit/05bc579028d3e87f3e043238e08480354c9fd222))
 * [x] All core server suites pass
 * [x] Upgrade tests are updated to include upgrades from OTP 21 and pass
 * [x] All other plugins in the umbrella pass their tests
 * [x] New OTP 21 Concourse pipeline version is all green ([core server](https://ci.rabbitmq.com/teams/main/pipelines/server-release:v3.8.x-erlang-git), [tier 1 plugins](https://ci.rabbitmq.com/teams/main/pipelines/server-release:v3.8.x-erlang-git?groups=qa%3Aplugins), [packages](https://ci.rabbitmq.com/teams/main/pipelines/server-release:v3.8.x-erlang-git?groups=qa%3Apkg), [upgrades](https://ci.rabbitmq.com/teams/main/pipelines/server-release:v3.8.x-erlang-git?groups=qa%3Aupgrades), [clients](https://ci.rabbitmq.com/teams/main/pipelines/server-release:v3.8.x-erlang-git?groups=(qa%3Aclients)))
 * [x] Server scripts are updated to use the same effective I/O subsystem defaults
 * [x] Windows build on OTP 21 is comparable to earlier versions in terms of efficiency
 * [x] Zero dependency Erlang RPM is updated to OTP 21
 * [x] Standalone MacOS package bundles OTP 21
 * [x] [Supported Erlang versions guide](http://www.rabbitmq.com/which-erlang.html) is updated for OTP 21
 * [ ] [Upgrades doc guide](http://www.rabbitmq.com/upgrade.html) is updated for OTP 21 (as needed)

Things that may not be functionally important but still would be nice to have for us:

 * [x] Confidence that Ranch supports OTP 21
 * [x] Confidence that [Elixir supports OTP 21](https://github.com/elixir-lang/elixir/issues/6611) (as of 1.6.6)

**Comment by josevalim** [comment]
Elixir v1.6.6 is out and fully supports Erlang/OTP 21.

**Comment by michaelklishin** [comment]
@josevalim thank you for the update!

**Comment by croensch** [comment]
Why do we need pinning in the installation routine? (https://www.rabbitmq.com/install-debian.html)
Could we not set the min/max erlang version for the dependency to be stable*? AFAIK apt also allows for installing "unstable" but i don't exactly know how it works.
apt show is
```
Package: rabbitmq-server
Version: 3.7.6-1
Depends: init-system-helpers (>= 1.13~), erlang-nox (>= 1:19.3) | esl-erlang (>= 1:19.3), adduser, logrotate, socat`
```
*so like my six-step ansible script can install a stable server, or containers that get rebuild often... pinning a version there just looks overly complicated and locks that down to break later just my 2 cents
Or am i wrong?

**Comment by michaelklishin** [comment]
@croensch this is not a discussion forum. There can be plenty of reasons for pinning that have nothing to do with OTP 21. In fact the pinning section long predates this issue or OTP 21 RCs.

**Comment by michaelklishin** [comment]
All discussions, questions, opinions, suggestions, ideas belong to the mailing list. This issue is about making RabbitMQ compatible with OTP 21 and getting OTP 21 test coverage to the same level as other supported series.

**Comment by gerhard** [comment]
Worth keeping an eye on this: [Node not responding to init:stop() - Erlang/OTP 21](http://erlang.org/pipermail/erlang-questions/2018-July/095869.html)

**Comment by michaelklishin** [comment]
There will be a couple of additional OTP 21 compatibility improvements in 3.7.8 but they hopefully don't affect more than a low single digit % of users.
