### ISSUE TITLE
Request to add "user" header to connection.closed event.

### ISSUE THREAD

**Issue by dldiehl77** [rabbitmq/rabbitmq-server#1620]
I was just testing the enhancement in 3.7.6-rc.2 where you added client_properties to the connection.closed event.  It looks great.

Would it be possible/reasonable to add the "user" header as well?  I am referring to the same "user" header that appears in the connection.created event, of course.  Having the "user" header on the connection.closed event would allow me to know what user it was that lost their connection.

Would that be possible to add?

thanks in advance.

dave

**Comment by michaelklishin** [comment]
We are not guaranteed to have a username when a connection is lost (authentication may or may not have completed by then), so assuming it will be there is not a good idea. You have a connection identifier on `connection.created` events, consider using that instead.
