### ISSUE TITLE
Error When enabling ldap auth rabbitmq 3.7

### ISSUE THREAD

**Issue by sconrod-tester** [rabbitmq/rabbitmq-server#1621]
Thank you for using RabbitMQ and for taking the time to report an
issue.

## Does This Belong to GitHub or RabbitMQ Mailing List? Github

*Important:* please first read the `CONTRIBUTING.md` document in the
root of this repository. It will help you determine whether your
feedback should be directed to the RabbitMQ mailing list [1] instead.

## Please Help Maintainers and Contributors Help You

In order for the RabbitMQ team to investigate your issue, please provide
**as much as possible** of the following details:

Error:
./rabbitmq-env: 111: /etc/rabbitmq/rabbitmq-env.conf: auth_backends.1: not found

* RabbitMQ version 3.7
* Erlang version 20.3
* RabbitMQ server and client application log files
* A runnable code sample, terminal transcript or detailed set of
  instructions that can be used to reproduce the issue
* RabbitMQ plugin information via `rabbitmq-plugins list`
* Client library version (for all libraries used)
* Operating system, version, and patch level

Running the `rabbitmq-collect-env` [2] script can provide most of the
information needed. Please make the archive available via a third-party
service and note that **the script does not attempt to scrub any
sensitive data**.

If your issue involves RabbitMQ management UI or HTTP API, please also provide
the following:

 * Browser and its version
 * What management UI page was used (if applicable)
 * How the HTTP API requests performed can be reproduced with `curl`
 * Operating system on which you are running your browser, and its version
 * Errors reported in the JavaScript console (if any)

This information **greatly speeds up issue investigation** (or makes it
possible to investigate it at all).  Please help project maintainers and
contributors to help you by providing it!

1. https://groups.google.com/forum/#!forum/rabbitmq-users
2. https://github.com/rabbitmq/support-tools/blob/master/scripts/rabbitmq-collect-env

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
> ./rabbitmq-env: 111: /etc/rabbitmq/rabbitmq-env.conf: auth_backends.1: not found

is not a whole lot of information to work with but almost certainly this is due to the fact that `rabbitmq-env.conf`, which must be a **shell script** which contains environment variables, was populated with a [new style configuration file](http://www.rabbitmq.com/configure.html#config-file-formats), which has a similar name (`rabbitmq.conf`). Obviously RabbitMQ config file is not a valid shell script so it cannot be loaded.
