### ISSUE TITLE
Why rabbitmq doesn't release connections?

### ISSUE THREAD

**Issue by forstef** [rabbitmq/rabbitmq-server#1625]
Thank you for using RabbitMQ and for taking the time to report an
issue.

## Does This Belong to GitHub or RabbitMQ Mailing List?

*Important:* please first read the `CONTRIBUTING.md` document in the
root of this repository. It will help you determine whether your
feedback should be directed to the RabbitMQ mailing list [1] instead.

## Please Help Maintainers and Contributors Help You

In order for the RabbitMQ team to investigate your issue, please provide
**as much as possible** of the following details:

* RabbitMQ version 3.7.5
* Erlang version 20
* RabbitMQ server and client application log files
* A runnable code sample, terminal transcript or detailed set of
  instructions that can be used to reproduce the issue
* RabbitMQ plugin information via `rabbitmq-plugins list`
[E*] rabbitmq_management               3.7.5
[e*] rabbitmq_management_agent         3.7.5
[E*] rabbitmq_mqtt                     3.7.5
[e*] rabbitmq_web_dispatch             3.7.5
* Client library version (for all libraries used)
* Operating system, version, and patch level
Linux cloud 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

Running the `rabbitmq-collect-env` [2] script can provide most of the
information needed. Please make the archive available via a third-party
service and note that **the script does not attempt to scrub any
sensitive data**.

If your issue involves RabbitMQ management UI or HTTP API, please also provide
the following:

 * Browser and its version
 * What management UI page was used (if applicable)
 * How the HTTP API requests performed can be reproduced with `curl`
 * Operating system on which you are running your browser, and its version
 * Errors reported in the JavaScript console (if any)

This information **greatly speeds up issue investigation** (or makes it
possible to investigate it at all).  Please help project maintainers and
contributors to help you by providing it!

1. https://groups.google.com/forum/#!forum/rabbitmq-users
2. https://github.com/rabbitmq/support-tools/blob/master/scripts/rabbitmq-collect-env

I have few(about 4 clients) mqtt clients  connect to rabbitmq server through gprs, but the gprs network is unstable, so connection may broken, and clients will reconnect when connection are dead.
but the connections are  still there, a few days later,  the server established thousands of connections, and the connections seems alive, but in deed, I only have 4 clients.

tcp6       0      0 192.168.1.160:2883      223.104.255.87:33568    ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.254.241:63524   ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.255.132:42290   ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.255.219:59710   ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.254.9:63831     ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.255.132:14798   ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.255.244:40706   ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.255.98:60495    ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.254.76:32274    ESTABLISHED
tcp6       0      0 192.168.1.160:2883      218.76.43.93:63489      ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.254.221:55914   ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.254.89:12751    ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.254.77:56453    ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.255.181:53147   ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.255.76:58105    ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.255.117:32528   ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.254.12:22623    ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.255.87:56940    ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.255.223:43791   ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.254.143:27460   ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.255.76:5863     ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.255.120:62188   ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.254.59:22511    ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.254.148:41887   ESTABLISHED
tcp6       0      0 192.168.1.160:2883      223.104.254.61:11525    ESTABLISHED
......

so why rabbitmq doesn't release these connections?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This is answered in a couple of doc guides:

 * [Heartbeats](http://www.rabbitmq.com/heartbeats.html)
 * Networking: [Dealing with High Connection Churn](http://www.rabbitmq.com/networking.html#dealing-with-high-connection-churn)
