### ISSUE TITLE
Setting specified NodeName error

### ISSUE THREAD

**Issue by Costriod** [rabbitmq/rabbitmq-server#1628]
Hi bro,
According to this page (http://www.rabbitmq.com/configure.html#customise-environment), Setting specified NodeName on '/etc/rabbitmq/rabbitmq-env.conf' like this,
<pre></code>NODENAME=rabbitmq@myhost.com</code></pre>
but there is error when the rabbitmq-server started, after adding the following variable ‘USE_LONGNAME=true’ like this, 
<pre></code>
NODENAME=rabbitmq@myhost.com
USE_LONGNAME=true
</code></pre>
then it worked correctly.
Perhaps this page might puzzle the fresh

**Comment by lukebakken** [comment]
> but there is error when the rabbitmq-server started

It would be helpful to let us know what the error is. I suspect it has something to do with using a fully-qualified hostname as your node name - i.e. `myhost.com` instead of a short name like `myhost`.

If you have suggestions for improving the documentation, we would gladly accept a pull request [here](https://github.com/rabbitmq/rabbitmq-website/pulls). Thanks.

**Comment by michaelklishin** [comment]
It depends on what the value is. We can definitely add a note to that section.

**Comment by Costriod** [comment]
RabbitMQ v3.7.6 , Erlang v20.3
the error log：
<pre><code>
Jun 22 19:30:04 localhost.localdomain rabbitmq-server[2037]: Crash dump is being written to: /var/log/rabbitmq/erl_crash.dump...done
Jun 22 19:30:04 localhost.localdomain systemd[1]: rabbitmq-server.service: main process exited, code=exited, status=1/FAILURE
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: 19:30:04.917 [error] ** System NOT running to use fully qualified hostnames **
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: ** Hostname 192.168.1.20 is illegal **
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: 19:30:04.926 [error] ** System NOT running to use fully qualified hostnames **
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: ** Hostname 192.168.1.20 is illegal **
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: Error: unable to perform an operation on node 'rabbitmq@192.168.1.20'. Please see diagnostics information and suggestions below.
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: Most common reasons for this are:
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: * Target node is not running
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: In addition to the diagnostics info below:
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: * See the CLI, clustering and networking guides on http://rabbitmq.com/documentation.html to learn more
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: * Consult server logs on node rabbitmq@192.168.1.20
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: DIAGNOSTICS
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: ===========
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: attempted to contact: ['rabbitmq@192.168.1.20']
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: rabbitmq@192.168.1.20:
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: * connected to epmd (port 4369) on 192.168.1.20
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: * epmd reports: node 'rabbitmq' not running at all
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: other nodes on 192.168.1.20: [rabbitmqcli35]
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: * suggestion: start the node
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: Current node details:
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: * node name: rabbitmqcli35@localhost
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: * effective user's home directory: /var/lib/rabbitmq
Jun 22 19:30:04 localhost.localdomain rabbitmqctl[2396]: * Erlang cookie hash: tRgN9rAjHRNfqa1qWDBo2g==
Jun 22 19:30:04 localhost.localdomain systemd[1]: Failed to start RabbitMQ broker.
</code></pre>

local ip is 192.168.1.20
<pre><code>
[root@localhost ~]# cat /etc/rabbitmq/rabbitmq-env.conf 
NODENAME=rabbitmq@192.168.1.20
#USE_LONGNAME=true
[root@localhost ~]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:f7:a5:1d brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.20/24 brd 192.168.1.255 scope global enp0s3
       valid_lft forever preferred_lft forever
    inet6 fe80::452d:3755:a582:5e31/64 scope link 
       valid_lft forever preferred_lft forever
</code></pre>

it works when I uncomment 'USE_LONGNAME=true'
