### ISSUE TITLE
Unable to connect to RabbitMQ using SSL, have followed documents, and troubleshooting guides with no help

### ISSUE THREAD

**Issue by postables** [rabbitmq/rabbitmq-server#1629]
I have tried the following guides and troubleshooting resources:
* https://www.rabbitmq.com/troubleshooting-ssl.html
* https://www.rabbitmq.com/ssl.html 
*https://github.com/streadway/amqp/blob/e5adc2ada8b8efff032bf61173a233d143e9318e/examples_test.go#L28

I generated my test certificates using `basic` profile from `tls-gen` https://github.com/michaelklishin/tls-gen

I get the following error when trying to dial a TLS connection from my golang client:
`2018/06/25 15:01:27 Exception (403) Reason: "SASL could not negotiate a shared mechanism"
exit status 1`
```
rabbitmqctl list_users
Listing users ...
darkmatter	[]
guest	[administrator]
```
```
rabbitmqctl list_permissions
Listing permissions in vhost "/" ...
darkmatter	.*	.*	.*
guest	.*	.*	.*
```
```
=INFO REPORT==== 25-Jun-2018::15:01:21 ===
Starting RabbitMQ 3.5.7 on Erlang 18.3
Copyright (C) 2007-2015 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

=INFO REPORT==== 25-Jun-2018::15:01:21 ===
node           : rabbit@darkmatter
home dir       : /var/lib/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config
cookie hash    : MUlyEYVRgkR1tY5d+ulPeg==
log            : /var/log/rabbitmq/rabbit@darkmatter.log
sasl log       : /var/log/rabbitmq/rabbit@darkmatter-sasl.log
database dir   : /var/lib/rabbitmq/mnesia/rabbit@darkmatter
```

Here's my config file:
```erl
[
        {rabbit,[
		{auth_backends, [rabbit_auth_backend_internal]},
                {auth_mechanisms, ['EXTERNAL']}, % comment test
                {ssl_listeners,[5671]},
                {ssl_options,[
                             {versions,['tlsv1.2', 'tlsv1.1']},
                             {cacertfile,"/tmp/ca_certificate.pem"},
                             {certfile,"/tmp/server_certificate.pem"},
                             {keyfile,"/tmp/server_key.pem"},
                             {verify,verify_peer},
			     {password, "bunnies"},
                             {fail_if_no_peer_cert,false}]}
        ]}
].
```

Golang code:
```Go
func main() {
	cfg := tls.Config{}
	cfg.RootCAs = x509.NewCertPool()
	if ca, err := ioutil.ReadFile("/tmp/ca_certificate.pem"); err == nil {
		cfg.RootCAs.AppendCertsFromPEM(ca)
	}

	// for this example we use the tls-gen to generate the keys
	if cert, err := tls.LoadX509KeyPair("/tmp/client_certificate.pem", "/tmp/client_key.pem"); err == nil {
		cfg.Certificates = append(cfg.Certificates, cert)
	}
	conn, err := amqp.DialTLS("amqps://darkmatter:password@darkmatter/", &cfg)
	defer conn.Close()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%+v", conn)
	conn.Close()
}
```

**Comment by postables** [comment]
Small update:

If I change `{auth_mechanisms, ['EXTERNAL']}` to `{auth_mechanisms, ['EXTERNAL','PLAIN']}` authentication works, however it doesn't appear to connect via TLS??

**Comment by lukebakken** [comment]
Hello! Just FYI the RabbitMQ team does not use GitHub to have discussions or diagnose issues like this one. In the future, please post to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list.

I'm not sure why you are using this configuration:

```
{auth_mechanisms, ['EXTERNAL']},
```

Using that in conjunction with usernames / password but only configuring the internal auth backend won't work. This is why adding `PLAIN` fixed your issue. You can read more about it here: https://www.rabbitmq.com/authentication.html

I'm not sure why you don't think TLS is working in your scenario. You have RabbitMQ configured to only listen via TLS so there's no other option. If you'd like, post to the mailing list and include a packet capture demonstrating that TLS isn't actually being used.

Thanks for using RabbitMQ.

**Comment by michaelklishin** [comment]
`EXTERNAL` by definition makes the broker assume that authentication has been done via some other method, such as TLS peer [x509 certificate chain] verification.

Two unrelated notes: RabbitMQ 3.5.x has been out of support for well over a year. In addition you run on an Erlang version with [known major bugs](http://www.rabbitmq.com/which-erlang.html) that affect RabbitMQ. Consider moving to Erlang 20.3.x and RabbitMQ 3.7.x.

**Comment by lukebakken** [comment]
Good catch @michaelklishin I didn't even notice the RMQ and Erlang versions. @postables thank you for providing that info, though, many people don't bother.

**Comment by postables** [comment]
@michaelklishin  Thank you for the warning!  In production we are using up to date versions of RabbitMQ, I'm just doing this testing on my development machine quickly which is why it's using out-dated versions. What you mention about `EXTERNAL` is that why `EXTERNAL+PLAIN` works because RabbitMQ is doing the authentication via password and then using the TLS certs for encryption of traffic?

@lukebakken  Ah gotcha, sorry for cluttering up your issues I'll post on that mailing list from now on. Haha no problem I know what it's like troubleshooting user issues with no info it SUCKS lol.

**Comment by michaelklishin** [comment]
@postables correct, with just `EXTERNAL`, assuming that the client also specified that mechanism, RabbitMQ will not even try to perform authentication. So using it without TLS or another mechanism RabbitMQ cannot be aware of (e.g. IP address-based or maybe even a hardware authentication device) is a **Bad Idea**™.

**Comment by postables** [comment]
Gotcha. Thanks again
