### ISSUE TITLE
How to set log output both in console and log file

### ISSUE THREAD

**Issue by 82398485** [rabbitmq/rabbitmq-server#1637]
Hello,
I found all the server  scripts contains the codes below, but how to set log output both in console and log file?

if [ "$RABBITMQ_LOGS" = '-' ]; then
    SASL_ERROR_LOGGER=tty
    RABBIT_LAGER_HANDLER=tty
    RABBITMQ_LAGER_HANDLER_UPGRADE=tty
else
    SASL_ERROR_LOGGER=false
    RABBIT_LAGER_HANDLER='"'${RABBITMQ_LOGS}'"'
    RABBITMQ_LAGER_HANDLER_UPGRADE='"'${RABBITMQ_UPGRADE_LOG}'"'
fi

**Comment by lukebakken** [comment]
Searching Google with `site:rabbitmq.com log console` brings up [this document](https://www.rabbitmq.com/logging.html) as the first hit.

If that is not sufficient, please post follow-up questions to [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users).

**Comment by 82398485** [comment]
I have already solved problem. 
At version 3.6.X , can not both output.
But version 3.7.X, is OK.

Thanks.
