### ISSUE TITLE
Support identifying cluster nodes by FQDN and port number

### ISSUE THREAD

**Issue by xavierhardy** [rabbitmq/rabbitmq-server#1652]
Cluster nodes cannot identify themselves using the TCP port on which they actually listen. This makes clustering impossible in a managed container environment if you can't change the container's hostname and if the FQDN is the same for all of the cluster nodes (only the TCP port differs).

https://www.rabbitmq.com/clustering.html

More precisely, could it be possible to allow this kind of configuration?
```erl
[
  {rabbit, [
    {cluster_nodes, {['rabbit@ha.example.com:7777', 'rabbit@ha.example.com:8888'], disc}}
  ]}
].
```
This is really a show stopper in my case; we might have to use another message queue, that supports this kind of clustering configuration.

**Comment by michaelklishin** [comment]
RabbitMQ and its underlying runtime assume that hostnames (or IP addresses) are unique and can be changed. The runtime even provides [a way to customise hostname resolution](http://erlang.org/doc/apps/erts/inet_cfg.html) that doesn't require superuser privileges to manage. This is a pretty fundamental thing and it's not going to change any time soon.

FWIW this is not a commonly reported issue by containerised environment users. That said, use a different tool if it works for you.

**Comment by michaelklishin** [comment]
Also, nodes can use exactly the same [sets of ports](https://www.rabbitmq.com/networking.html#selinux-ports) (and in most deployments, they do), which makes this idea… not particularly well thought out, at least.

**Comment by michaelklishin** [comment]
Our team does not use GitHub issues for discussions but here's one last idea. The prefix in node name (the `rabbit@`) part *can* change and that's the part that changes when more than one node runs on the same host (together with ports to avoid conflicts).

Our team routinely runs multiple nodes on the same host (without any containers but it doesn't change much) by overriding node name and ports, e.g.

```
# node1, uses all defaults
RABBITMQ_NODENAME=rabbit@mercurio ./sbin/rabbitmq-server
```

and

```
# node2 overrides node name and 2 ports
RABBITMQ_NODE_PORT=5673 RABBITMQ_NODENAME=hare@mercurio RABBITMQ_SERVER_START_ARGS="-rabbitmq_management listener [{port,15673}]" ./sbin/rabbitmq-server
```

And that's it.

**Comment by xavierhardy** [comment]
Thanks for replying so fast, but no, we do not want them on the same host (that's why we need clustering in the first place), it's just that these nodes have the same FQDN because they are behind an LB that allows to select specific container instances using their TCP/UDP ports.

Imagine this kind of configuration:
instances: rabbit@4c01db0b339c , rabbit@d7886598dbe2, rabbit@d894ede837d2
4c01db0b339c runs on host A, with the IP address 192.168.1.1 with an unknown port on the host which is exposed on TCP port 5555 on the load balancer (whose FQDN is ha.example.com).
d7886598dbe2 on host B, 192.168.1.2, unknown host port, exposed on the same LB on TCP port 6666
d894ede837d2 on host C, 192.168.1.3, unknown host port, exposed on the same LB on TCP port 7777

Our only solution would be to use the container host IP addresses and to force the TCP port on the different hosts. This is risky for two reasons:
- this host is used by other containers that select a random TCP port, our container might not start on that host if for instance, 5672 is not available
- relying on IP addresses is a bad idea since the environment architecture assumes they might change at any moment, which is one of the reasons why people should rely on the FQDN of the LB

I hope my explanation is clear enough, I understand that this feature might not be desirable in RabbitMQ. I think we'll have to postponed supporting HA in our environment for now. Thank you very much for your answer.

**Comment by lukebakken** [comment]
I can't say I completely understand your situation, because IMHO your load balancer should not have any effect on RabbitMQ clustering.

I believe you should be able to create an `erl_inetrc` file with the following contents:

```
{host, {192,168,1,1}, ["4c01db0b339c"]}.
{host, {192,168,1,2}, ["d7886598dbe2"]}.
{host, {192,168,1,3}, ["d894ede837d2"]}.
{lookup, [file, native]}.
```

It is basically an `/etc/hosts` file for the Erlang VM. This file should be readable in each RabbitMQ instance. Create the `/etc/rabbitmq/rabbitmq-env.conf` file with the following contents:

```
export ERL_INETRC=/path/to/erl_inetrc
```

Then, your RabbitMQ configuration would be as follows:

```
[
  {rabbit, [
    {cluster_nodes, {['rabbit@4c01db0b339c', 'rabbit@d7886598dbe2', 'rabbit@d894ede837d2'], disc}}
  ]}
].
```
