### ISSUE TITLE
Improved error reporting for private keys that cannot be loaded

### ISSUE THREAD

**Issue by Pkuutn** [rabbitmq/rabbitmq-server#1653]
If, by any reason, RabbitMQ server could not open ssl key file, it should show error/debug/etc message.
We had 2 cases:
- ssl key file protected by password
- ssl key file with wrong owner and permissions
In this RabbitMQ server starts, opens port, but do not reply on open ssl port.
No error messages in log file on debug level also.
Reproduced with:
3.6.12 OTP 20.1
3.7.5 OTP 20.3
3.7.7 OTP 21

**Comment by michaelklishin** [comment]
3.7.x does verify if certificate and key paths exist and the files are readable on start. The key isn't loaded by the TLS implementation until it is used and we are limited by what kind of errors it reports back and how sensible they are. We report all issues discovered to the Erlang/OTP team, most recently  [ERL-664](https://bugs.erlang.org/browse/ERL-664) where blank or ill-formatted key files resulted in no errors.

**Comment by michaelklishin** [comment]
In fact, the "does not reply on open ssl port" thing sounds a lot like `ERL-664`.

**Comment by michaelklishin** [comment]
This keeps coming up so to clarify: node's inability to report a TLS certificate or private key file issue early comes down to the TLS implementation. A [bug was discovered and reported](https://bugs.erlang.org/browse/ERL-664) to the Erlang team. A fix shipped in Erlang 21.1.
