### ISSUE TITLE
Generic server rabbit_epmd_monitor terminating 

### ISSUE THREAD

**Issue by mabown** [rabbitmq/rabbitmq-server#1654]
We are facing a crash report for a while after started rabbitmq service. Below you can find crash report text and status output.

Crash Report
2018-07-28 07:47:54.182 [error] <0.322.0> ** Generic server rabbit_epmd_monitor terminating 
** Last message in was check
** When Server state == {state,{erlang,#Ref<0.695054671.1317011457.252848>},erl_epmd,"rabbit","testserver1",25672}
** Reason for termination == 
** {enoent,[{erlang,open_port,[{spawn_executable,false},[{args,["-sname","epmd-starter-133468332","-noshell","-eval","halt()."]},exit_status,stderr_to_stdout,use_stdio]],[{file,"erlang.erl"},{line,2213}]},{rabbit_nodes_common,ensure_epmd,0,[{file,"src/rabbit_nodes_common.erl"},{line,76}]},{rabbit_epmd_monitor,check_epmd,1,[{file,"src/rabbit_epmd_monitor.erl"},{line,108}]},{rabbit_epmd_monitor,handle_info,2,[{file,"src/rabbit_epmd_monitor.erl"},{line,79}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,637}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,711}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2018-07-28 07:47:54.183 [error] <0.322.0> CRASH REPORT Process rabbit_epmd_monitor with 0 neighbours crashed with reason: {enoent,[{erlang,open_port,[{spawn_executable,false},[{args,["-sname","epmd-starter-133468332","-noshell","-eval","halt()."]},exit_status,stderr_to_stdout,use_stdio]],[{file,"erlang.erl"},{line,2213}]},{rabbit_nodes_common,ensure_epmd,0,[{file,"src/rabbit_nodes_common.erl"},{line,76}]},{rabbit_epmd_monitor,check_epmd,1,[{file,"src/rabbit_epmd_monitor.erl"},{line,108}]},{rabbit_epmd_monitor,handle_info,2,[{file,"src/rabbit_epmd_monitor.erl"},{line,79}]},{gen_server,try_dispatch,4,[{file,"gen..."},...]},...]}
2018-07-28 07:47:54.184 [error] <0.321.0> Supervisor rabbit_epmd_monitor_sup had child rabbit_epmd_monitor started with rabbit_epmd_monitor:start_link() at <0.322.0> exit with reason {enoent,[{erlang,open_port,[{spawn_executable,false},[{args,["-sname","epmd-starter-133468332","-noshell","-eval","halt()."]},exit_status,stderr_to_stdout,use_stdio]],[{file,"erlang.erl"},{line,2213}]},{rabbit_nodes_common,ensure_epmd,0,[{file,"src/rabbit_nodes_common.erl"},{line,76}]},{rabbit_epmd_monitor,check_epmd,1,[{file,"src/rabbit_epmd_monitor.erl"},{line,108}]},{rabbit_epmd_monitor,handle_info,2,[{file,"src/rabbit_epmd_monitor.erl"},{line,79}]},{gen_server,try_dispatch,4,[{file,"gen..."},...]},...]} in context child_terminated
2018-07-28 07:48:54.177 [error] <0.760.0> ** Generic server rabbit_epmd_monitor terminating 

rabbitmqctl status output

Status of node rabbit@testserver1 ...
[{pid,5780},
 {running_applications,
     [{rabbitmq_management,"RabbitMQ Management Console","3.7.7"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.7.7"},
      {rabbitmq_web_stomp,"Rabbit WEB-STOMP - WebSockets to Stomp adapter",
          "3.7.7"},
      {rabbitmq_stomp,"RabbitMQ STOMP plugin","3.7.7"},
      {rabbitmq_mqtt,"RabbitMQ MQTT Adapter","3.7.7"},
      {rabbitmq_delayed_message_exchange,"RabbitMQ Delayed Message Exchange",
          "20171201-3.7.x"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.7.7"},
      {rabbit,"RabbitMQ","3.7.7"},
      {amqp_client,"RabbitMQ AMQP Client","3.7.7"},
      {rabbit_common,
          "Modules shared by rabbitmq-server and rabbitmq-erlang-client",
          "3.7.7"},
      {ranch_proxy_protocol,"Ranch Proxy Protocol Transport","1.5.0"},
      {cowboy,"Small, fast, modern HTTP server.","2.2.2"},
      {ranch,"Socket acceptor pool for TCP protocols.","1.5.0"},
      {ssl,"Erlang/OTP SSL application","9.0"},
      {mnesia,"MNESIA  CXC 138 12","4.15.4"},
      {public_key,"Public key infrastructure","1.6"},
      {asn1,"The Erlang ASN1 compiler version 5.0.6","5.0.6"},
      {os_mon,"CPO  CXC 138 46","2.4.5"},
      {recon,"Diagnostic tools for production use","2.3.2"},
      {cowlib,"Support library for manipulating Web protocols.","2.1.0"},
      {crypto,"CRYPTO","4.3"},
      {jsx,"a streaming, evented json parsing toolkit","2.8.2"},
      {inets,"INETS  CXC 138 49","7.0"},
      {xmerl,"XML parser","1.3.17"},
      {lager,"Erlang logging framework","3.6.3"},
      {goldrush,"Erlang event stream processor","0.1.9"},
      {compiler,"ERTS  CXC 138 10","7.2"},
      {syntax_tools,"Syntax tools","2.1.5"},
      {syslog,"An RFC 3164 and RFC 5424 compliant logging framework.","3.4.2"},
      {sasl,"SASL  CXC 138 11","3.2"},
      {stdlib,"ERTS  CXC 138 10","3.5"},
      {kernel,"ERTS  CXC 138 10","6.0"}]},
 {os,{win32,nt}},
 {erlang_version,
     "Erlang/OTP 21 [erts-10.0] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:64]\n"},
 {memory,
     [{connection_readers,34720},
      {connection_writers,1356},
      {connection_channels,7212},
      {connection_other,104364},
      {queue_procs,49864},
      {queue_slave_procs,0},
      {plugins,1808180},
      {other_proc,31758652},
      {metrics,209740},
      {mgmt_db,281488},
      {mnesia,105032},
      {other_ets,2980928},
      {binary,796720},
      {msg_index,29504},
      {code,28069482},
      {atom,1172689},
      {other_system,10116293},
      {allocated_unused,11864880},
      {reserved_unallocated,0},
      {strategy,rss},
      {total,[{erlang,77526224},{rss,89391104},{allocated,89391104}]}]},
 {alarms,[]},
 {listeners,
     [{clustering,25672,"::"},
      {amqp,5672,"::"},
      {amqp,5672,"0.0.0.0"},
      {'amqp/ssl',5671,"::"},
      {'amqp/ssl',5671,"0.0.0.0"},
      {mqtt,1884,"::"},
      {mqtt,1884,"0.0.0.0"},
      {'mqtt/ssl',8883,"::"},
      {'mqtt/ssl',8883,"0.0.0.0"},
      {stomp,61613,"::"},
      {stomp,61613,"0.0.0.0"},
      {'http/web-stomp',1983,"::"},
      {'http/web-stomp',1983,"0.0.0.0"},
      {'https/web-stomp',15671,"::"},
      {'https/web-stomp',15671,"0.0.0.0"},
      {http,15672,"::"},
      {http,15672,"0.0.0.0"}]},
 {vm_memory_calculation_strategy,rss},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,3435785420},
 {disk_free_limit,50000000},
 {disk_free,112424361984},
 {file_descriptors,
     [{total_limit,8092},
      {total_used,3},
      {sockets_limit,7280},
      {sockets_used,1}]},
 {processes,[{limit,1048576},{used,558}]},
 {run_queue,1},
 {uptime,331},
 {kernel,{net_ticktime,60}}]

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The node fails to start a subprocess that will register it with epmd. `rabbit_epmd_monitor` is not critical to a node's operation since nodes register with epmd anyway and the only reason why it exists is `epmd` being killed in certain conditions on Windows while the node is still running.

This is mailing list material.

**Comment by michaelklishin** [comment]
[Kernel/OS resource limits](http://www.rabbitmq.com/networking.html#tuning-for-large-number-of-connections-open-file-handles-limit) and security mechanisms can prevent nodes from starting subprocesses.

**Comment by lukebakken** [comment]
This is due to `init:get_argument(progname)` returning `false`, which is unexpected. `false` is then used as the executable to be spawned:

https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_nodes_common.erl#L73-L81
