### ISSUE TITLE
disconvery peer consul how to join cluster

### ISSUE THREAD

**Issue by shuipingyu** [rabbitmq/rabbitmq-server#1655]
by rabbitmq 3.7.x，disconvery peer consul can register success，but join cluster failer,find debug log,no  join cluster log。

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
This plugin's README mentions the need to first get familiar with [RabbitMQ clustering fundamentals](http://www.rabbitmq.com/clustering.html) before learning [how peer discovery works](http://www.rabbitmq.com/cluster-formation.html#peer-discovery). There must be errors of some kind somewhere: we cannot possibly suggest anything without them.
