### ISSUE TITLE
 multiple consumers  according to switch network

### ISSUE THREAD

**Issue by 9527kevin** [rabbitmq/rabbitmq-server#1656]
Hi,I use rabbitmq to do an Instant Messaging app. I found that the  queue will appear multiple consumers when mobile phone switched network, such as wifi to 4G network or something else.
Because our java server need to  judge whether need to send  remote push according to the number of consumers,such as zero consumer to send  and one consumer is not send. So, if multiple consumers are caused by switching networks, the push is abnormal. BTW,  do you has  any better  idea about how to send remote push?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
We don't have a whole lot of details to work with but when network interface changes, that's likely the effect of

 * The fact that [it takes time to detect connection unavailability](http://www.rabbitmq.com/heartbeats.html)
 * Clients such as Java (my best guess this is on Android) will [automatically recover from network failures](http://www.rabbitmq.com/api-guide.html#recovery) by default.

See [server logs](https://www.rabbitmq.com/logging.html#logged-events) for connection lifecycle events and other clues.
