### ISSUE TITLE
Wrong amqps URI validation

### ISSUE THREAD

**Issue by inikulshin** [rabbitmq/rabbitmq-server#1663]
RabbitMQ version: **3.6.10**
Erlang version: **19.3**

Somehow amqp://:5761 is a valid URI, but amqp**s**://:5761 is not:

![image](https://user-images.githubusercontent.com/17042537/43822357-8ef2fc9e-9af4-11e8-8333-3b7d5ca0a446.png)

https://www.rabbitmq.com/uri-spec.html

> Apart from the scheme identifier, the syntax of the "amqps" URI scheme is identical to that of the "amqp" URI scheme:

**Comment by lukebakken** [comment]
Hello! Please report what you're seeing on the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list and how to reproduce it. Also, please note that version 3.6.10 is outdated so for this to be considered an issue it must be reproducible on the latest version of the 3.6 series or 3.7 series. Thanks.

**Comment by michaelklishin** [comment]
Addressed in the Erlang client. As expected this had nothing to do with the server or even Shovel. URIs with port but not host should have been rejected as invalid (as in, make no sense in the context of Shovel) but weren't.
