### ISSUE TITLE
cannot create directory ‘/var/run/rabbitmq’: Permission denied

### ISSUE THREAD

**Issue by mundus08** [rabbitmq/rabbitmq-server#1665]
After reboot on Debian 9 rabbitmq does not start and reports
  cannot create directory ‘/var/run/rabbitmq’: Permission denied

The reason might be that rabbitmq is started by systemd with user rabbitmq. User rabbitmq has no write permission in /var/run

```
root@vm-test-02:/etc/init.d# systemctl cat rabbitmq-server.service
# /lib/systemd/system/rabbitmq-server.service
# systemd unit example
[Unit]
Description=RabbitMQ broker
After=network.target epmd@0.0.0.0.socket
Wants=network.target epmd@0.0.0.0.socket

[Service]
Type=notify
User=rabbitmq
Group=rabbitmq
NotifyAccess=all
TimeoutStartSec=3600
# The following setting will automatically restart RabbitMQ
# in the event of a failure. systemd service restarts are not a
# replacement for service monitoring. Please see
# http://www.rabbitmq.com/monitoring.html
Restart=on-failure
RestartSec=10
WorkingDirectory=/var/lib/rabbitmq
ExecStart=/usr/lib/rabbitmq/bin/rabbitmq-server
ExecStop=/usr/lib/rabbitmq/bin/rabbitmqctl stop
ExecStop=/bin/sh -c "while ps -p $MAINPID >/dev/null 2>&1; do sleep 1; done"
# See rabbitmq/rabbitmq-server-release#51
SuccessExitStatus=69

[Install]
WantedBy=multi-user.target

-------------------------
Version
root@vm-test-02:/etc/init.d# apt-cache policy rabbitmq-server
rabbitmq-server:
  Installed: 3.6.15-1

root@vm-test-02:/etc/init.d# uname -a
Linux vm-test-02 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux

```

**Comment by mundus08** [comment]
To fix this i added 
```
[Service]
PermissionsStartOnly=true
ExecStartPre=-/bin/mkdir /var/run/rabbitmq
ExecStartPre=-/bin/chown -R rabbitmq:rabbitmq  /var/run/rabbitmq
```
to the systemd unit file. This works on Debian 9.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by lukebakken** [comment]
@mundus08 for what it's worth, I could not reproduce this using Debian Stretch and the following RabbitMQ + Erlang combinations:

* `3.7.8-rc3` and Erlang 21
* `3.6.16` and Erlang 20.3.6

This is the `Vagrantfile` I used for the second test: 
[Vagrantfile.txt](https://github.com/rabbitmq/rabbitmq-server/files/2271460/Vagrantfile.txt)

**Comment by mundus08** [comment]
It was my fault - I use an ansible role which changes the PID file location.
Thanks for your great support!

**Comment by michaelklishin** [comment]
Thank you for reporting back.
