### ISSUE TITLE
cluster with pause_minority survive node  less than 1/2 after network disconnect

### ISSUE THREAD

**Issue by fasdfvasf** [rabbitmq/rabbitmq-server#1667]
In one cluster composed by 7 MQ nodes with pause_minority mode, the node name for these 7 nodes are (1,2,3,4,5,7,8)
•	Node 1,2,3 in DC1(datacenter)
•	Node 4,5 in DC2
•	Node 7,8 in DC3
There are network link connected between each DC, such as DC1-DC2,DC2-DC3,DC1-DC3.

Then cut off the network link between DC1-DC2. It means
nodes (1,2,3) and (4,5) become network isolated; however, nodes (7,8) can still talk to node (1,2,3) and (4,5).

After a while(Net Tick Time), only node 1,7,8 survive in the cluster.

> Cluster status of node 'rabbit@rabbit-7'
> [{nodes,[{disc,['rabbit@rabbit-1','rabbit@rabbit-2','rabbit@rabbit-3',
>                 'rabbit@rabbit-4','rabbit@rabbit-5','rabbit@rabbit-7',
>                 'rabbit@rabbit-8']}]},
>  {running_nodes,['rabbit@rabbit-1','rabbit@rabbit-8','rabbit@rabbit-7']},
>  {cluster_name,<<"rabbit@rabbit-1">>},
>  {partitions,[]},

node (2,3) and (4,5) are all stopped by “Partial partition detected”.
This is error log reported by node 2.
>=ERROR REPORT==== 9-Aug-2018::14:36:07 ===
>Partial partition detected:
> * We saw DOWN from rabbit@rabbit-5
> * We can still see rabbit@rabbit-8 which can see rabbit@rabbit-5
> * pause_minority mode enabled
>We will therefore pause until the *entire* cluster recovers

>=WARNING REPORT==== 9-Aug-2018::14:36:07 ===
>Cluster minority/secondary status detected - awaiting recovery

This is error log reported by node 3.
>=ERROR REPORT==== 9-Aug-2018::14:36:01 ===
>Partial partition detected:
> * We saw DOWN from rabbit@rabbit-5
> * We can still see rabbit@rabbit-8 which can see rabbit@rabbit-5
> * pause_minority mode enabled
>We will therefore pause until the *entire* cluster recovers

>=WARNING REPORT==== 9-Aug-2018::14:36:01 ===
>Cluster minority/secondary status detected - awaiting recovery

This is error log reported by node 4.
>=ERROR REPORT==== 9-Aug-2018::14:36:12 ===
>Partial partition detected:
> * We saw DOWN from rabbit@rabbit-1
> * We can still see rabbit@rabbit-8 which can see rabbit@rabbit-1
> * pause_minority mode enabled
>We will therefore pause until the *entire* cluster recovers

>=WARNING REPORT==== 9-Aug-2018::14:36:12 ===
>Cluster minority/secondary status detected - awaiting recovery

This is error log reported by node 5.
>=ERROR REPORT==== 9-Aug-2018::14:36:09 ===
>Partial partition detected:
> * We saw DOWN from rabbit@rabbit-1
> * We can still see rabbit@rabbit-8 which can see rabbit@rabbit-1
> * pause_minority mode enabled
>We will therefore pause until the *entire* cluster recovers

>=WARNING REPORT==== 9-Aug-2018::14:36:09 ===
>Cluster minority/secondary status detected - awaiting recovery

I assume nodes (7,8) and (1,2,3) can survive with pause-minority mode. But it does not.

And I test again, depending the time MQ node detect down node, 4,5,7,8 survived, and 1,2,3 are stopped by “Partial partition detected”…..

And if we have a 6 nodes cluster in 3 DC. DC1(1,2) DC2(4,5),DC3(7,8). When cut off the network link between DC1-DC2, the same behavior acted by MQ cluster described as above. how can I to select the survived cluster, I would like it survived in DC1&DC3 or DC2&DC3 either, and take control of it.
•	RabbitMQ version 3.6.14

And when it entering “awaiting recovery”
>Cluster minority/secondary status detected - awaiting recovery

It will await_cluster_recovery(fun all_nodes_up/0). Can it wait until in a majority part?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
