### ISSUE TITLE
RabbitMQ apt-packages do not specify maximum erlang version, leading to breaking with erlang 21

### ISSUE THREAD

**Issue by fake-name** [rabbitmq/rabbitmq-server#1668]
I'm running a rabbitmq server on ubuntu 14.04.

I installed rabbitmq from the official apt repository: `http://www.rabbitmq.com/debian/`. My erlang install is from Erlang Solutions.

Basically, Erlang Solutions. provides erlang 21 for 14.04, but `http://www.rabbitmq.com/debian/` does not provide RabbitMQ >= 3.7.7 for 14.04, while also not specifying a maximum erlang version.

The end result is a simple `apt-get update` will lead to a broken install. 

If rabbitmq isn't forward compatibile with new versions of erlang (and it is indeed not, which is what prompted this bug report), the packages should specify a specific erlang version, or at least a major version ceiling so simple `apt-get update` commands don't hose a running system.

**Comment by michaelklishin** [comment]
http://www.rabbitmq.com/debian/ has been deprecated for a couple of years and is not mentioned in the [Debian installation guide](http://www.rabbitmq.com/install-debian.html) besides the deprecation note.

**Comment by fake-name** [comment]
My install is a few years old. It worked up until yesterday.

**Comment by michaelklishin** [comment]
@fake-name that's unfortunate but things don't last forever in the land of software. You should perhaps check out the [change log](http://www.rabbitmq.com/changelog.html) and [Erlang compatibility docs](http://www.rabbitmq.com/which-erlang.html) every once in a few years.

RabbitMQ 3.6.x (now EOL) supports 5 Erlang/OTP series (which have *a lot* of breaking changes between them). For 3.7.x we identified and [announced breaking changes in OTP 21](https://groups.google.com/forum/#!msg/rabbitmq-users/KbOldePfgYw/cjYzldEJAQAJ) before it went GA. There are few projects that are as proactive about future Erlang release compatibility.

There is a dedicated section on [Erlang/OTP package pinning](http://www.rabbitmq.com/which-erlang.html) in the docs.

We would consider introducing an upper limit for versions but it will take a bit more convincing on the mailing list.

FTR, this repo has nothing to do with packaging. [rabbitmq-server-release](https://github.com/rabbitmq/rabbitmq-server-release/] is where all packaging bits reside.

**Comment by fake-name** [comment]
> FTR, this repo has nothing to do with packaging. [rabbitmq-server-release](https://github.com/rabbitmq/rabbitmq-server-release/] is where all packaging bits reside.

Whoops, too many repos. Sorry about that.

Also, mailing lists are where discussions go to die. At least use a forum.

**Comment by michaelklishin** [comment]
@fake-name thanks but our mailing list gets between 600 and 1000 messages a month with nearly every thread getting answered. I'm afraid we won't be moving away from it because it clearly works (and we have the data to prove it).

**Comment by lukebakken** [comment]
@michaelklishin what do you think about redirecting from http://www.rabbitmq.com/debian/ to bintray?
