### ISSUE TITLE
auth_mechanisms 'EXTERNAL' not getting sent

### ISSUE THREAD

**Issue by Fredholm** [rabbitmq/rabbitmq-server#1676]
With RabbitMQ version 3.7.6 the mechanism list sent from the server is empty. When I try to use 'EXTERNAL' instead of 'PLAIN'.
https://imgur.com/dRjMWJq

'PLAIN' works fine and I got most stuff working.
Here's the config file:

``` erlang
[

	{rabbit, [

		{auth_backends, [rabbit_auth_backend_internal]},

		{auth_mechanisms, ['EXTERNAL']},

		{ssl_cert_login_from, common_name},

	        {ssl_listeners, [5671]},

		{ssl_options, [{cacertfile,"/etc/ssl/cacert.pem"},

                    {certfile,"/etc/ssl/cert.pem"},

                    {keyfile,"/etc/ssl/key.pem"},

                    {verify,verify_peer},

                    {fail_if_no_peer_cert,true}]}

	]}

].
```

With the following config: 

``` erlang
		{auth_mechanisms, ['PLAIN', 'EXTERNAL']},
```

Then only `PLAIN` shows up.

**Comment by michaelklishin** [comment]
`EXTERNAL` is not an implemented mechanism (by definition RabbitMQ isn't involved), so the code that loads provided [mechanisms](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_reader.erl#L1338) will not include it. It's a good question whether it should be unconditionally included. Probably but it doesn't trip up any of the clients we maintain.

**Comment by michaelklishin** [comment]
The `EXTERNAL` method turns out to be registered by the [`rabbitmq-auth-mechanism-ssl` plugin](https://github.com/rabbitmq/rabbitmq-auth-mechanism-ssl/blob/master/src/rabbit_auth_mechanism_ssl.erl#L38).
