### ISSUE TITLE
web-mqtt not adapt proxy_protocol

### ISSUE THREAD

**Issue by theagechen** [rabbitmq/rabbitmq-server#1680]
Rabbitmq3.7.4
Erlang20.3

Protocol: web-mqtt: 15675 is very useful.

However, it does not adapt to haproxy's send-proxy protocol.
I hope to have a similar configuration like amqp 
(https://www.rabbitmq.com/networking.html#proxy-protocol)

So I can see the real ip of the client connected via haproxy on the web console.

**Comment by michaelklishin** [comment]
This repository has nothing to do with Web MQTT. It has [a separate one](https://github.com/rabbitmq/rabbitmq-web-mqtt).
