### ISSUE TITLE
I had a problem using python to put information on rabbitmq

### ISSUE THREAD

**Issue by Amerone** [rabbitmq/rabbitmq-server#1688]
Here is my version of rabbitmq:
rabbitmq-server-3.7.7
otp_win64_21.0.1

The following is the rabbitmq log printed information:
operation none caused a connection exception unexpected_frame: "expected method frame, got non method frame instead"

The following is the exception information printed by python:
raise exceptions.ChannelClosed()
pika.exceptions.ChannelClosed

This exception occurs when the number of messages to rabbitmq bars reaches 2,164 through python
I need your help!

**Comment by lukebakken** [comment]
Hello,

The RabbitMQ team does not use GitHub issues for issue diagnosis. Please provide the following in a message to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list and we'll help out there:

* Python version
* Pika version
* Complete set of code that reproduces this issue. This is important!

Thanks
