### ISSUE TITLE
Mention backup directory in the "upgrade failed" message

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#169]
If an upgrade fails for whatever reason and re-tried, we should mention backup directory location instead of just "previous upgrade failed."

**Comment by hairyhum** [comment]
What I get from code is there are log of backup dir if backup is taken, but `previous_upgrade_failed` error message is thrown if it cannot take a backup. Or should it report directory where it cannot create backup?

**Comment by michaelklishin** [comment]
@hairyhum we should mention the backup directory, even if things failed (I think, feel free to disagree). The idea is to answer the most common question people have when they see that message: where can I find the backup dir?
