### ISSUE TITLE
Error: unable to connect to node rabbit@xxxx

### ISSUE THREAD

**Issue by zj4775** [rabbitmq/rabbitmq-server#1693]
Hi
   i can not start the rabbitmq ,and i modify the hostname with "hostname zj21" (do not restart server) and modify /etc/hosts /etc/hostname file but also do not work.and i can not troubleshooting with below error log ,can help me?

the error log is:
  
[root@zj21 local]# journalctl -xe
Sep 03 21:49:33 zj21 rabbitmq-server[11729]: Error description:
Sep 03 21:49:33 zj21 rabbitmq-server[11729]: undef
Sep 03 21:49:33 zj21 rabbitmq-server[11729]: Log files (may contain more information):
Sep 03 21:49:33 zj21 rabbitmq-server[11729]: /var/log/rabbitmq/rabbit@zj21.log
Sep 03 21:49:33 zj21 rabbitmq-server[11729]: /var/log/rabbitmq/rabbit@zj21-sasl.log
Sep 03 21:49:33 zj21 rabbitmq-server[11729]: Stack trace:
Sep 03 21:49:33 zj21 rabbitmq-server[11729]: [{mnesia,system_info,[directory],[]},
Sep 03 21:49:33 zj21 rabbitmq-server[11729]: {rabbit_mnesia,ensure_mnesia_dir,0,
Sep 03 21:49:33 zj21 rabbitmq-server[11729]: [{file,"src/rabbit_mnesia.erl"},{line,511}]},
Sep 03 21:49:33 zj21 rabbitmq-server[11729]: {rabbit_node_monitor,prepare_cluster_status_files,0,
Sep 03 21:49:33 zj21 rabbitmq-server[11729]: [{file,"src/rabbit_node_monitor.erl"},{line,101}]},
Sep 03 21:49:33 zj21 rabbitmq-server[11729]: {rabbit,'-boot/0-fun-0-',0,[{file,"src/rabbit.erl"},{line,283}]},
Sep 03 21:49:33 zj21 rabbitmq-server[11729]: {rabbit,start_it,1,[{file,"src/rabbit.erl"},{line,417}]},
Sep 03 21:49:33 zj21 rabbitmq-server[11729]: {init,start_em,1,[]},
Sep 03 21:49:33 zj21 rabbitmq-server[11729]: {init,do_boot,3,[]}]
Sep 03 21:49:34 zj21 rabbitmq-server[11729]: {"init terminating in do_boot",undef}
Sep 03 21:49:34 zj21 rabbitmq-server[11729]: init terminating in do_boot (undef)
Sep 03 21:49:34 zj21 rabbitmq-server[11729]: Crash dump is being written to: erl_crash.dump...done
Sep 03 21:49:34 zj21 systemd[1]: rabbitmq-server.service: main process exited, code=exited, status=1/FAILURE
Sep 03 21:49:36 zj21 rabbitmqctl[12022]: Stopping and halting node rabbit@zj21
Sep 03 21:49:36 zj21 rabbitmqctl[12022]: Error: unable to connect to node rabbit@zj21: nodedown
Sep 03 21:49:36 zj21 rabbitmqctl[12022]: DIAGNOSTICS
Sep 03 21:49:36 zj21 rabbitmqctl[12022]: ===========
Sep 03 21:49:36 zj21 rabbitmqctl[12022]: attempted to contact: [rabbit@zj21]
Sep 03 21:49:36 zj21 rabbitmqctl[12022]: rabbit@zj21:
Sep 03 21:49:36 zj21 rabbitmqctl[12022]: * connected to epmd (port 4369) on zj21
Sep 03 21:49:36 zj21 rabbitmqctl[12022]: * epmd reports: node 'rabbit' not running at all
Sep 03 21:49:36 zj21 rabbitmqctl[12022]: no other nodes on zj21
Sep 03 21:49:36 zj21 rabbitmqctl[12022]: * suggestion: start the node
Sep 03 21:49:36 zj21 rabbitmqctl[12022]: current node details:
Sep 03 21:49:36 zj21 rabbitmqctl[12022]: - node name: 'rabbitmq-cli-63@zj21'
Sep 03 21:49:36 zj21 rabbitmqctl[12022]: - home dir: .
Sep 03 21:49:36 zj21 rabbitmqctl[12022]: - cookie hash: Z/j7JGfu03+p4i6YGz504Q==
Sep 03 21:49:36 zj21 polkitd[840]: Unregistered Authentication Agent for unix-process:11714:588903 (system bus name :1.114, object path /org/freedesktop/Policy
Sep 03 21:49:36 zj21 systemd[1]: Failed to start RabbitMQ broker.
-- Subject: Unit rabbitmq-server.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit rabbitmq-server.service has failed.
--
-- The result is failed.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
`mnesia:system_info/1` is undefined. Your Erlang/OTP installation must be incomplete, e.g. on Debian and Ubuntu `erlang-mnesia` must be missing. We highly recommend using [the recommended repositories](http://www.rabbitmq.com/which-erlang.html) for installing a compatible version of Erlang.
