### ISSUE TITLE
Rabbitmq-server does not shutdown properly

### ISSUE THREAD

**Issue by stefanscheid** [rabbitmq/rabbitmq-server#1697]
Hi,

rabbitmq-server does not shutdown properly on systemctl or service requests.
It kills the process instead after timeout.
It worked fine on Ubuntu 16.04. 

Any ideas? I did not find any matching issues here nor on other sites.

Thanks!

Versions:
Ubuntu: 18.04.1 LTS on VMWARE Fusion
Rabbit: 3.6.10-1
Erlang: 1:20.2.2+dfsg-1ubuntu2

Symptom:
<img width="880" alt="bildschirmfoto 2018-09-08 um 08 36 41" src="https://user-images.githubusercontent.com/34167411/45251291-d7d45e00-b343-11e8-8764-e22047e79e5f.png">
<img width="513" alt="bildschirmfoto 2018-09-08 um 08 53 54" src="https://user-images.githubusercontent.com/34167411/45251355-f5ee8e00-b344-11e8-8481-80f9666c8e2f.png">
<img width="498" alt="bildschirmfoto 2018-09-08 um 09 03 30" src="https://user-images.githubusercontent.com/34167411/45251421-1cf98f80-b346-11e8-8409-a8bedcb87ea8.png">
All same results.

Log:
<img width="897" alt="bildschirmfoto 2018-09-08 um 08 42 36" src="https://user-images.githubusercontent.com/34167411/45251292-db67e500-b343-11e8-8372-a2c8d621d819.png">

**Comment by lukebakken** [comment]
Please note that both the version of Erlang and RabbitMQ you are using are out-of-date.

I can't reproduce using RabbitMQ `3.6.16` and Erlang `20.3.8.6`. Please see the attached `Vagrantfile` for setup.

[Vagrantfile.txt](https://github.com/rabbitmq/rabbitmq-server/files/2363438/Vagrantfile.txt)

**Comment by lukebakken** [comment]
FWIW, this is some output after running `systemctl stop rabbitmq-server`. Note that it stopped gracefully.

```
root@UBUNTU-18:~# systemctl status rabbitmq-server
● rabbitmq-server.service - RabbitMQ broker
   Loaded: loaded (/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Sat 2018-09-08 15:25:59 UTC; 11s ago
  Process: 4437 ExecStop=/bin/sh -c while ps -p $MAINPID >/dev/null 2>&1; do sleep 1; done (code=exited, status=0/SUCCESS)
  Process: 4289 ExecStop=/usr/lib/rabbitmq/bin/rabbitmqctl stop (code=exited, status=0/SUCCESS)
  Process: 3636 ExecStart=/usr/lib/rabbitmq/bin/rabbitmq-server (code=exited, status=0/SUCCESS)
 Main PID: 3636 (code=exited, status=0/SUCCESS)
   Status: "Initialized"

Sep 08 15:25:28 UBUNTU-18 rabbitmq-server[3636]:   ######  ##        /var/log/rabbitmq/rabbit@UBUNTU-18-sasl.log
Sep 08 15:25:28 UBUNTU-18 rabbitmq-server[3636]:   ##########
Sep 08 15:25:28 UBUNTU-18 rabbitmq-server[3636]:               Starting broker...
Sep 08 15:25:30 UBUNTU-18 rabbitmq-server[3636]: systemd unit for activation check: "rabbitmq-server.service"
Sep 08 15:25:30 UBUNTU-18 systemd[1]: Started RabbitMQ broker.
Sep 08 15:25:30 UBUNTU-18 rabbitmq-server[3636]:  completed with 0 plugins.
Sep 08 15:25:56 UBUNTU-18 systemd[1]: Stopping RabbitMQ broker...
Sep 08 15:25:56 UBUNTU-18 rabbitmqctl[4289]: Stopping and halting node 'rabbit@UBUNTU-18'
Sep 08 15:25:56 UBUNTU-18 rabbitmq-server[3636]: Gracefully halting Erlang VM
Sep 08 15:25:59 UBUNTU-18 systemd[1]: Stopped RabbitMQ broker.
```

**Comment by lukebakken** [comment]
Also, the recommended version of RabbitMQ is `3.7.7`. `3.6.16` is the last supported version in the `3.6.X` series and will not be supported indefinitely.

**Comment by stefanscheid** [comment]
Great, thanks. Works.

:-DDD i mean, the upgrade doc contains a hard learning curve for those that are not born with Debian.

**Comment by tomkins** [comment]
@stefanscheid this seems to be an Ubuntu packaging bug: https://bugs.launchpad.net/ubuntu/+source/rabbitmq-server/+bug/1784757
