### ISSUE TITLE
Please update cowboy.

### ISSUE THREAD

**Issue by lemenkov** [rabbitmq/rabbitmq-server#170]
Hello!

Currently, rabbitmq-server uses a very outdated cowboy library which lacks some interesting patches. More specifically I'd love to have ninenines/cowboy@e67d839154a0c031e667903da013a4a49be86ced (make SSL certificate password optional) and ninenines/cowboy@9ac784df3b41bf31df4e77a65ccf90cb67aa0014 (support for specifying the ciphers for the SSL transport) applied. Especially the latter one. Both patches included in a cowboy-0.6.0 so it might be better just to update to that version w/o cherry-picking anything.

Why I love to have these patches applied?

First one just simplifies configuration. We won't need to provide strange "password" value even if we don't use it. Second patch is more interesting one, and there is a sad story behind this particular feature request.

We're trying to use rabbitmq-web-stomp with the latest rabbitmq-server (3.5.3) on Ubuntu with Erlang R16B03. Unfortunately this Erlang version is very optimistic about the ssl ciphers supported. When we tried to access web-page over https ( https://amqp.example.com:15674/stomp ) both browsers around (Chrome and Firefox) failed to establish a connection due to wrong SSL handshake - Erlang replies with a list of ciphers it doesn't support. A good old curl works btw, but that's another story.

That's not the only RabitMQ web-page affected by this Erlang R16B defect. For example we stumbled upon the same issue while trying to access web-management page ( https://amqp.example.com:15672 ).

But in case of a web-management there is a simple workaround. If we limit a list of SSL ciphers available (using something like "{ciphers,[{rsa,aes_128_cbc,sha}]}") it works perfectly. I'm sure upgrading to the 17.x.y version will also works but that's again another story.

Unfortunately the cowboy version, which you bundled with RabbitMQ, doesn't allow cipher list setup unless a second patch applied. We have to fallback to HTTP. That's sad.

cc @digipigeon

**Comment by michaelklishin** [comment]
Moved to https://github.com/rabbitmq/rabbitmq-web-stomp/issues/13. We are aware of the limitations.
Chances are we'll hire someone to work on this soon.
