### ISSUE TITLE
cluster last node start failure

### ISSUE THREAD

**Issue by panjunDev** [rabbitmq/rabbitmq-server#1702]
rabbit:3.7.7 Erlang 20.3.8.6
errormsg:
2018-09-19 02:27:43.572 [error] <0.298.0> Supervisor worker_pool_sup had child 1 started with worker_pool_worker:start_link(worker_pool) at <0.596.0> exit with reason no such process or port in call to erlang:link(<0.426.0>) in context child_terminated
2018-09-19 02:27:43.572 [error] <0.597.0> ** Generic server <0.597.0> terminating
** Last message in was {'$gen_cast',{submit_async,#Fun<rabbit_queue_index.36.122888644>}}
** When Server state == undefined
** Reason for termination == 
** {noproc,[{erlang,link,[<0.426.0>],[]},{rabbit_queue_index,'-queue_index_walker/1-fun-0-',2,[{file,"src/rabbit_queue_index.erl"},{line,693}]},{worker_pool_worker,handle_cast,2,[{file,"src/worker_pool_worker.erl"},{line,122}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1050}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-09-19 02:27:43.572 [error] <0.597.0> CRASH REPORT Process <0.597.0> with 0 neighbours exited with reason: no such process or port in call to erlang:link(<0.426.0>) in gen_server2:terminate/3 line 1166

thks!

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.
