### ISSUE TITLE
Login failed error message is not getting disappeared even after successful login.

### ISSUE THREAD

**Issue by kritika0205** [rabbitmq/rabbitmq-server#1704]
* RabbitMQ version 3.7.7
* Erlang version 21.0.1
 * Browser and its version Internet Explorer 11.2485.14393.0

Steps to reproduce-
1. Navigate to the RabbitMQ server.
2. Enter wrong credentials.
3. An error message would pop up.
4. Now enter correct credentails and log in.

Observed behavior: The error message of log in failed doesn't disappear even after successful log in.
Expected Behavior: It should disappear.
![rabbitmq issue](https://user-images.githubusercontent.com/15031697/45750717-85d9e500-bc2d-11e8-9db4-d2792723b7e5.png)

**Comment by lukebakken** [comment]
Hello, thanks for using RabbitMQ and for including all of that information. I have opened rabbitmq/rabbitmq-management#609 to track this since that's the repository where this code lives.

**Comment by lukebakken** [comment]
This will be addressed by rabbitmq/rabbitmq-management#610, thanks.
