### ISSUE TITLE
Protection from unbounded growth in rabbit_event

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#1722]
We have identified that with certain workloads and very high connection churn `rabbit_event` mailbox can grow very large. We should investigate if it would be safe to make it drop messages when it's falling behind, much like Lager log handlers do.

Per discussion with @lukebakken.

**Comment by michaelklishin** [comment]
Addressed in the PRs above.

**Comment by lukebakken** [comment]
@dcorbacho awesome!! 🎉

**Comment by vrsbrazil** [comment]
Hey guys!

First of all, thank you for that update, it really improved the memory leak!

I however have noticed that even though it definetly reduced the memory leak, it is still there somehow, the way I was able to reproduce it was by stopping consumption of the queue for some time (about 10 minutes) as it received payloads greater than 1MB at a rate of 2-5 per second.

When you enable consumption to resume, even though the messages are consumed, the memory does not decrease. During consumption however this leak still persists, only at this version at a much lower rate, I would say the update improved memory leak at about 70%, but it is definetly still there.

Thank you.

**Comment by vrsbrazil** [comment]
OK, I thought this was the problem I am experiencing then. I am however getting the behaviour described above, the messages are being acknowledged and the list_queues shows no messages waiting, but the memory usage keeps enlarging, any thoughts on this? I am using the latest version.

**Comment by michaelklishin** [comment]
This team does not use GitHub issues for discussions, investigations and so on. They belong to the mailing list.

We also do not speculate if we can. [There are tools](http://www.rabbitmq.com/memory-use.html) that provide evidence of what consumes memory on a node. You have provided no evidence that it's `rabbit_event` or the event exchange plugin that are responsible for this.

There always will be an upper limit to what the event exchange consumer can do. Switching to multiple consumers would require a significant redesign that cannot go into a patch release. We don't see enough demand for that work compared to other major changes.

**Comment by michaelklishin** [comment]
From our experience it's almost always high connection or channel churn that produces a lot of internal events. Reduce the churn or don't use the event exchange plugin if it cannot keep up in your environment. Again, collecting data e.g. with rabbitmq-top is highly recommended over guessing.
