### ISSUE TITLE
Proposal: Delivery confirms

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#1727]
Motivation:

Some RabbitMQ setups are using more than one cluster, communicating via [federation](https://github.com/rabbitmq/rabbitmq-federation) and [shovel](https://github.com/rabbitmq/rabbitmq-shovel).
Such systems are used to replicate messages across multiple datacenters or wide geographical distances. Using clustering in such systems may be unsafe due to unreliable network.
However applications using such systems may need to have a confirmation when a message is replicatied to a different cluster and not only the one, which it's publishing to.
This may be addressed by additional confirmation from the queue to the publisher channel when the message is acked. 
Because we are expecting network interruptions, "exactly once" delivery is not possible so there is no need to implement MQTT-like QOS2. If the confirmation is lost at some point, the publisher will have to react to that by republishing the message. And the consumer will have to deduplicate the message.

Proposal:

Additional client/server capability to negotiate: `confirm_ondelivery`
Additional publisher confirm frame: `confirm.select_ondelivery`
Additional confirmation frames: `basic.ack_ondelivery`, `basic.nack_ondelivery` (if queue fails/deleted)
Keep track of publisher channel in queues (maybe only for channels where this feature is enabled).
Send ondelivery acks when message is acked by consumer.

Names are not final of course.

**Comment by kjnilsson** [comment]
This isn't something we're keen to do as it introduces a dependency on remote clusters for local availability. We already have a disaster recover solution with async message replication in the commercial RabbitMQ offering. https://docs.vmware.com/en/VMware-Tanzu-RabbitMQ-for-Kubernetes/3.13/tanzu-rabbitmq-kubernetes/standby-replication.html
