### ISSUE TITLE
Introduce a rabbitmqctl command for purging queues

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#175]
See [this thread](https://groups.google.com/forum/#!topic/rabbitmq-users/EQjm3ochFMI). We are not looking to replace `rabbitmqadmin` or anything close but we need to have a command that could be used to relieve memory pressure and executed manually. Adding a policy with a short TTL is not obvious to most operators.

**Comment by videlalvaro** [comment]
I was thinking about rabbitmqctl and its commands. Why don't we add some sort of plug in system for `rabbit_control_main` that allows to plug in commands easily?

**Comment by michaelklishin** [comment]
Sounds good. We also may choose to group commands at some point, namespacing is a good idea for plugins.

**Comment by michaelklishin** [comment]
Fixed in #215.
