### ISSUE TITLE
Random RabbitMQ crashes without any specific reason

### ISSUE THREAD

**Issue by flxfxp** [rabbitmq/rabbitmq-server#1752]
We use RabbitMQ for sending financial order book data at an ingress of 300-400 orderbooks per second.

Once every 2-3 days or so RabbitMQ crashes, or rather hangs. Ports (5672/15672) stay open but don't respond to any commands.  We're using the rabbitmq:3.7.5-management docker image (erts-9.3.1) with /var/lib/rabbitmq mounted as a volume. Consumers are written in Python with pika 0.11.2.

As far as I can tell, there are no specific errors in the logs: https://gist.github.com/flxfxp/5b07c038eb50dc3af61fbfd6200ec3f9

Any suggestions? Please let me know if you need any additional information.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
The only repeated exception in the logs looks like https://github.com/rabbitmq/rabbitmq-server/issues/1538. That cannot affect all but maybe 2 rarely used HTTP API operations.

There are [known Erlang bugs](https://bugs.erlang.org/browse/ERL-430) that can prevent activity on all TCP sockets but 20.3.x should not be affected. The node can also be [out of file handles](https://www.rabbitmq.com/networking.html#open-file-handle-limit), which would prevent all new connections from being accepted.

Please upgrade to 3.7.8 and OTP 20.3.8 or 21.1 first, make sure you have [monitoring in place]() and start a mailing list thread if you find any more clues with 3.7.8.
