### ISSUE TITLE
Ranch listener rabbit_web_dispatch_sup_15672, connection process <0.4894.165>, stream 9 had its request process <0.4927.165> exit with reason badarg and stacktrace

### ISSUE THREAD

**Issue by peteroneil** [rabbitmq/rabbitmq-server#1755]
Thank you for using RabbitMQ and for taking the time to report an
issue.

In order for the RabbitMQ team to investigate your issue, please provide
**as much as possible** of the following details:

* RabbitMQ version - 3.7.4
* Erlang version - 20.3
* RabbitMQ server and client application log files 
[rabbit@lsprbqdc201.log.2.gz](https://github.com/rabbitmq/rabbitmq-server/files/2534286/rabbit.lsprbqdc201.log.2.gz)

* A runnable code sample, terminal transcript or detailed set of
  instructions that can be used to reproduce the issue

Log into the Admin gui http://mq.mydomain:15672/#/queues as any user, including guest
Select queue
'Get Message' with Nack Message requeue true
GUI returne 500 error
    ERROR - RabbitMQ management API call failed: HTTP 500: Internal Server Error

* RabbitMQ plugin information via `rabbitmq-plugins list`

[E*] prometheus_rabbitmq_exporter      v3.7.2.1
[e*] rabbitmq_amqp1_0                  3.7.4
[  ] rabbitmq_auth_backend_cache       3.7.4
[  ] rabbitmq_auth_backend_http        3.7.4
[E*] rabbitmq_auth_backend_ldap        3.7.4
[  ] rabbitmq_auth_mechanism_ssl       3.7.4
[  ] rabbitmq_consistent_hash_exchange 3.7.4
[  ] rabbitmq_event_exchange           3.7.4
[E*] rabbitmq_federation               3.7.4
[  ] rabbitmq_federation_management    3.7.4
[  ] rabbitmq_jms_topic_exchange       3.7.4
[E*] rabbitmq_management               3.7.4
[e*] rabbitmq_management_agent         3.7.4
[  ] rabbitmq_mqtt                     3.7.4
[  ] rabbitmq_peer_discovery_aws       3.7.4
[e*] rabbitmq_peer_discovery_common    3.7.4
[E*] rabbitmq_peer_discovery_consul    3.7.4
[  ] rabbitmq_peer_discovery_etcd      3.7.4
[  ] rabbitmq_peer_discovery_k8s       3.7.4
[  ] rabbitmq_random_exchange          3.7.4
[  ] rabbitmq_recent_history_exchange  3.7.4
[  ] rabbitmq_sharding                 3.7.4
[E*] rabbitmq_shovel                   3.7.4
[E*] rabbitmq_shovel_management        3.7.4
[  ] rabbitmq_stomp                    3.7.4
[  ] rabbitmq_top                      3.7.4
[  ] rabbitmq_tracing                  3.7.4
[  ] rabbitmq_trust_store              3.7.4
[e*] rabbitmq_web_dispatch             3.7.4
[  ] rabbitmq_web_mqtt                 3.7.4
[  ] rabbitmq_web_mqtt_examples        3.7.4
[  ] rabbitmq_web_stomp                3.7.4
[  ] rabbitmq_web_stomp_examples       3.7.4

* Operating system, version, and patch level
user@host:/var/log/rabbitmq# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

Running the `rabbitmq-collect-env` [2] script can provide most of the
information needed. Please make the archive available via a third-party
service and note that **the script does not attempt to scrub any
sensitive data**.

If your issue involves RabbitMQ management UI or HTTP API, please also provide
the following:

 * Browser and its version - Chrome Version 70.0.3538.77 (Official Build) (64-bit)
 * What management UI page was used (if applicable) #/queues
 * How the HTTP API requests performed can be reproduced with `curl` :+1: 
curl -i -u guest:password -H "content-type:application/json" -X POST http://lstrbqdc203:15672/api/queues/%2f/ab.lead.herobase.dlq/get -d'{"count":5,"requeue":true,"encoding":"auto","truncate":50000,"ackmode":"nack"}'

 * Operating system on which you are running your browser, and its version. Various including Windows 7
 * Errors reported in the JavaScript console (if any) - none

This information **greatly speeds up issue investigation** (or makes it
possible to investigate it at all).  Please help project maintainers and
contributors to help you by providing it!

1. https://groups.google.com/forum/#!forum/rabbitmq-users
2. https://github.com/rabbitmq/support-tools/blob/master/scripts/rabbitmq-collect-env

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
According to the log, JSON parser threw an exception but there are no details to work with. Please upgrade to 3.7.8 and if that still can be reproduced, take a [traffic capture](http://www.rabbitmq.com/amqp-wireshark.html) and post it to rabbitmq-users. Thanks.

**Comment by lukebakken** [comment]
@peteroneil - you are using an invalid value for `ackmode`. Allowed values are:

```
ack_requeue_false
ack_requeue_true
reject_requeue_false
reject_requeue_true
```

This is documented in the HTTP API docs: [link](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.8/priv/www/api/index.html)
