### ISSUE TITLE
40ms acknowledgement delay for first Basic.Publish package in every channel

### ISSUE THREAD

**Issue by ghost** [rabbitmq/rabbitmq-server#1763]
I observe a strange behavior of the RabbitMQ server. After opening a channel and publishing a message (Basic.Publish), the server sends a acknowledgement packet 40ms after the first received packet of Basic.Publish.

Wireshark dump (image):
![selection_001](https://user-images.githubusercontent.com/7406597/48130778-cf929380-e29e-11e8-959f-d89f69c7737a.png)

Whireshark dump (csv source):
[dump.txt](https://github.com/rabbitmq/rabbitmq-server/files/2557293/dump.txt)

The problem is aggravated by the fact that if a channel is opened/closed on a connection, the next publication (Basic.Publish) of the message (through all open channels) will have a 40ms delay.

Our system uses a large number of channels per connection and this behavior negates performance.

Questions:
1. What are the reasons (my error in operation)?
2. Ability to configure timeouts?

Below is the minimum working code example and information of the system.

```python
import threading
import time

import rabbitpy as rbp


def publish(conn: rbp.Connection):
    with conn.channel() as ch:
        rbp.Queue(ch, 'queue').declare()

        rbp.Message(ch, 'Message').publish('', 'test_queue')
        time.sleep(1)
        rbp.Message(ch, 'Message').publish('', 'test_queue')


def main():
    with rbp.Connection(url='amqp://guest:guest@localhost:5672/%2F') as cn:
        threads = [threading.Thread(target=publish, args=(cn,)) for _ in range(2)]

        [t.start() for t in threads]

        [t.join() for t in threads]


if __name__ == '__main__':
    main()
```

System Information:

> Linux Rokker-PC 4.15.0-38-generic #41~16.04.1-Ubuntu SMP Wed Oct 10 20:16:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

rabbitmqctl status:

> Status of node 'rabbit@Rokker-PC' ...
> [{pid,31556},
>  {running_applications,
>      [{rabbitmq_management,"RabbitMQ Management Console","3.5.7"},
>       {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.5.7"},
>       {webmachine,"webmachine","1.10.3-rmq3.5.7-gite9359c7"},
>       {mochiweb,"MochiMedia Web Server","2.7.0-rmq3.5.7-git680dba8"},
>       {rabbitmq_management_agent,"RabbitMQ Management Agent","3.5.7"},
>       {rabbit,"RabbitMQ","3.5.7"},
>       {inets,"INETS  CXC 138 49","6.4.2"},
>       {mnesia,"MNESIA  CXC 138 12","4.15.1"},
>       {os_mon,"CPO  CXC 138 46","2.4.3"},
>       {amqp_client,"RabbitMQ AMQP Client","3.5.7"},
>       {xmerl,"XML parser","1.3.15"},
>       {sasl,"SASL  CXC 138 11","3.1"},
>       {stdlib,"ERTS  CXC 138 10","3.4.2"},
>       {kernel,"ERTS  CXC 138 10","5.4"}]},
>  {os,{unix,linux}},
>  {erlang_version,
>      "Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:64] [hipe] [kernel-poll:true]\n"},
>  {memory,
>      [{total,42966544},
>       {connection_readers,0},
>       {connection_writers,0},
>       {connection_channels,0},
>       {connection_other,5680},
>       {queue_procs,13192},
>       {queue_slave_procs,0},
>       {plugins,516864},
>       {other_proc,13645040},
>       {mnesia,62016},
>       {mgmt_db,204520},
>       {msg_index,36384},
>       {other_ets,1075672},
>       {binary,14568},
>       {code,17874309},
>       {atom,752561},
>       {other_system,8765738}]},
>  {alarms,[]},
>  {listeners,[{clustering,25672,"::"},{amqp,5672,"::"}]},
>  {vm_memory_high_watermark,0.4},
>  {vm_memory_limit,13445326438},
>  {disk_free_limit,50000000},
>  {disk_free,141350633472},
>  {file_descriptors,
>      [{total_limit,65436},
>       {total_used,3},
>       {sockets_limit,58890},
>       {sockets_used,1}]},
>  {processes,[{limit,1048576},{used,183}]},
>  {run_queue,0},
>  {uptime,657}]

Thanks!

P.S In the example I use the rabbitpy library. But the behavior is observed in another library - the pika. But judging by the network traffic is not a problem of libraries.

**Comment by michaelklishin** [comment]
A message is published when its properties (Content Header in the traffic dump) is, which happens 41ms after the `basic.publish` frame. So this is a matter of client implementation (specifically framing) and client-side TCP stack settings. It should be fairly easy to compare by just switching to e.g. the Java client/PerfTest.

You can find similar questions on rabbitmq-users in the past where client latency wasn't the primary contributing factor. In those cases runtime scheduler flags usually made most difference.

**Comment by michaelklishin** [comment]
More findings previously posted to https://github.com/gmr/rabbitpy/issues/116:

Your code opens N channels before publishing concurrently and this client has [a per-connection lock around channel.open operations](https://github.com/gmr/rabbitpy/blob/master/rabbitpy/connection.py#L174). So all threads in your code contend on that lock and possibly more (I couldn't quickly find where published message framing happens: clients often use a per-connection lock for serialised outgoing frames as well).

Pre-allocating channels will avoid contention on the channel management lock.

**Comment by lukebakken** [comment]
@RokkerRuslan - you are using an ancient version of RabbitMQ (`3.5.7`). Please use the latest version.

In addition, I can't reproduce this with RabbitMQ 3.7.8 / Erlang 21.1.1 on OS X using your latest script from [here](https://github.com/gmr/rabbitpy/issues/116#issuecomment-436614324). Basically, I see a small delay in the ACK after every publish, as you would expect, considering that publishing takes work.

[port-5672-csv.txt](https://github.com/rabbitmq/rabbitmq-server/files/2557574/port-5672-csv.txt)

**Comment by RokkerRuslan** [comment]
I can reproduce this with [RabbitMQ 3.7.8](https://github.com/docker-library/rabbitmq/blob/1a8fd1c6ee027baafb7144c24ad3c995ba5e0d24/3.7/debian/Dockerfile)

**Comment by lukebakken** [comment]
> I can reproduce this with RabbitMQ 3.7.8

Have you tried on a different system? Are you using a VM? Have you tried running RabbitMQ on one system and your application on another (i.e. not `localhost` connections)? Have you compared with the behavior of a different application, like PerfTest?

**Comment by michaelklishin** [comment]
We have already provided some feedback on the observations and the workload being tested. The rest of this discussion belongs to the mailing list.

**Comment by lukebakken** [comment]
@michaelklishin sounds good. @RokkerRuslan I'll keep an eye on the mailing list.
