### ISSUE TITLE
RabbitMQ dosen't reply basic.ack or basic.nack when using publisher confirm

### ISSUE THREAD

**Issue by gujun4990** [rabbitmq/rabbitmq-server#1766]
Version:
RabbitMQ: 3.6.16
erlang_version: Erlang/OTP 20 [erts-9.3]
mnesia: 4.15.3

Phenomenon:
I have 5 RabbitMQ nodes and use {"ha-mode": "all"} mirror queue to construct RabbitMQ cluster. All RabbitMQ nodes are containerized. After  I stop any 3 nodes, I found everything is OK except that RabbitMQ dosen't reply basic.ack or basic.nack when using publisher confirm. I can confirm that RabbitMQ dose't reply basic.ack or basic.nack because I have captured packets using wireshark. So I don't understand what caused this problem.
BTW: I use non-publisher confirm mode, everything is OK. I use pause_minority configuration for network.

**Comment by gujun4990** [comment]
Based on the second comment, I had modified RabbitMQ ha policy {"ha-mode": "exactly", "ha-params":2} and found that RabbitMQ dose't also reply basic.ack or basic.nack when using publisher confirm. So I am very confused what caused this problem.

**Comment by lukebakken** [comment]
Hello,

Please post this to [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) and we can discuss there. If an actual issue is found, we will then file an issue on GitHub.

Please provide *exact* steps to reproduce, including the application code you are using to publish messages.

**Comment by gujun4990** [comment]
I had analyzed the related code and the pause_minority configuration cause the problem. When the count of cluster nodes are less than half, the publisher confirm mode will stay pausing state for RabbitMQ. So the publisher will not receive basic.ack or basic.nack. Thank you. @lukebakken @michaelklishin
