### ISSUE TITLE
Channel health checks should use a sensible timeout when requesting channel stats

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#1783]
[rabbit_health_check:node_health_check/1](https://github.com/rabbitmq/rabbitmq-server/blob/v3.7.7/src/rabbit_health_check.erl#L54) relies on a function that can potentially [block forever](https://github.com/rabbitmq/rabbitmq-server/blob/v3.7.7/src/rabbit_channel.erl#L337). This
means that health check "delegate" processes (CLI or HTTP API request handlers) can potentially
accumulate.

`rabbit_channel:info/1` should be invoked with a timeout to avoid "handler" process accumulation.

`rabbit_channel:info/1` is used by multiple code paths so picking a default is not entirely trivial. Applying a channel operation timeout (15s by default) makes most sense to me.

**Comment by michaelklishin** [comment]
@lukebakken

**Comment by lukebakken** [comment]
[sigh] good find
