### ISSUE TITLE
The durable queues are missed when restarting the rabbitmq

### ISSUE THREAD

**Issue by songdony** [rabbitmq/rabbitmq-server#1793]
Thank you for using RabbitMQ and for taking the time to report an
issue.

I used  to set the durable message  with RabbitMQ.However,when I restarted the RabbitMQ,the durable message missed.That's my code. Where did I go wrong?
RabbitMQ version:3.1.3
Erlang version:5.10.4
In order for the RabbitMQ team to in
vesgate your issue, please provide
**as much as possible** of the following details:

* RabbitMQ version
* Erlang version
* RabbitMQ server and client application log files
* A runnable code sample, terminal transcript or detailed set of
  instructions that can be used to reproduce the issue
* RabbitMQ plugin information via `rabbitmq-plugins list`
* Client library version (for all libraries used)
* Operating system, version, and patch level

Running the `rabbitmq-collect-env` [2] script can provide most of the
information needed. Please make the archive available via a third-party
service and note that **the script does not attempt to scrub any
sensitive data**.

If your issue involves RabbitMQ management UI or HTTP API, please also provide
the following:

 * Browser and its version
 * What management UI page was used (if applicable)
 * How the HTTP API requests performed can be reproduced with `curl`
 * Operating system on which you are running your browser, and its version
 * Errors reported in the JavaScript console (if any)

This information **greatly speeds up issue investigation** (or makes it
possible to investigate it at all).  Please help project maintainers and
contributors to help you by providing it!

1. https://groups.google.com/forum/#!forum/rabbitmq-users
2. https://github.com/rabbitmq/support-tools/blob/master/scripts/rabbitmq-collect-env

**Comment by michaelklishin** [comment]
RabbitMQ 3.1.3 is [over 5 years old](http://www.rabbitmq.com/changelog.html). I'm sorry but we wouldn't investigate this even if we had enough details. Please [upgrade](http://www.rabbitmq.com/upgrade.html) first. You will have to [upgrade Erlang](http://www.rabbitmq.com/which-erlang.html) as well.

Publishing messages as persistent is one thing. They have to be routed to durable queues. They might have had TTL or the queues did. There are too many unknowns to provide even the most basic guidance.

**Comment by songdony** [comment]
> RabbitMQ 3.1.3 is [over 5 years old](http://www.rabbitmq.com/changelog.html). I'm sorry but we wouldn't investigate this even if we had enough details. Please [upgrade](http://www.rabbitmq.com/upgrade.html) first. You will have to [upgrade Erlang](http://www.rabbitmq.com/which-erlang.html) as well.
> 
> Publishing messages as persistent is one thing. They have to be routed to durable queues. They might have had TTL or the queues did. There are too many unknowns to provide even the most basic guidance.



> RabbitMQ 3.1.3 is [over 5 years old](http://www.rabbitmq.com/changelog.html). I'm sorry but we wouldn't investigate this even if we had enough details. Please [upgrade](http://www.rabbitmq.com/upgrade.html) first. You will have to [upgrade Erlang](http://www.rabbitmq.com/which-erlang.html) as well.
> 
> Publishing messages as persistent is one thing. They have to be routed to durable queues. They might have had TTL or the queues did. There are too many unknowns to provide even the most basic guidance.

Thanks.

**Comment by michaelklishin** [comment]
I don't see any evidence of messages being published as persistent by this code but even more importantly, your snippet has a glaring omission: it closes the connection without using [publisher confirms](http://www.rabbitmq.com/confirms.html) to ensure successful handling of the publishes. Fire-and-forget publishing doesn't carry a lot of guarantees.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.
