### ISSUE TITLE
MQTT CLIENT ID SEEMS TO BE LOST IN CONVERSION OF MQTT PACKET TO AMQP PACKET

### ISSUE THREAD

**Issue by venkatagadepalli** [rabbitmq/rabbitmq-server#1822]
Thank you for using RabbitMQ and for taking the time to report an
issue.

## Does This Belong to GitHub or RabbitMQ Mailing List?

*Important:* please first read the `CONTRIBUTING.md` document in the
root of this repository. It will help you determine whether your
feedback should be directed to the RabbitMQ mailing list [1] instead.

## Please Help Maintainers and Contributors Help You

In order for the RabbitMQ team to investigate your issue, please provide
**as much as possible** of the following details:

* RabbitMQ version
* Erlang version
* RabbitMQ server and client application log files
* A runnable code sample, terminal transcript or detailed set of
  instructions that can be used to reproduce the issue
* RabbitMQ plugin information via `rabbitmq-plugins list`
* Client library version (for all libraries used)
* Operating system, version, and patch level

Running the `rabbitmq-collect-env` [2] script can provide most of the
information needed. Please make the archive available via a third-party
service and note that **the script does not attempt to scrub any
sensitive data**.

If your issue involves RabbitMQ management UI or HTTP API, please also provide
the following:

 * Browser and its version
 * What management UI page was used (if applicable)
 * How the HTTP API requests performed can be reproduced with `curl`
 * Operating system on which you are running your browser, and its version
 * Errors reported in the JavaScript console (if any)

This information **greatly speeds up issue investigation** (or makes it
possible to investigate it at all).  Please help project maintainers and
contributors to help you by providing it!

1. https://groups.google.com/forum/#!forum/rabbitmq-users
2. https://github.com/rabbitmq/support-tools/blob/master/scripts/rabbitmq-collect-env

**Comment by venkatagadepalli** [comment]
bash-4.2# rabbitmq_version="$(rabbitmqctl eval '{_,_,V}=proplists:lookup(rabbit,application:which_applications()),V.' | tr -d '"')"
bash-4.2# echo "RabbitMQ: $rabbitmq_version"
RabbitMQ: 3.7.0
bash-4.2# erlang_version="$(rabbitmqctl eval 'erlang:system_info(otp_release).' | tr -d '"')"
bash-4.2# echo "Erlang: $erlang_version"
Erlang: 20

The issue is raised in mailing list too
https://groups.google.com/forum/#!topic/rabbitmq-users/9K1MiOoq9OU

Only below headers are received in amqp message

MessageHeaders key is amqp_receivedDeliveryMode and value is  NON_PERSISTENT]#
MessageHeaders key is amqp_receivedRoutingKey and value is  xxxx.xxxx.xxxx]#
MessageHeaders key is x-received-from and value is  [{exchange=amq.topic, uri=, redelivered=false, cluster-name=}]]#
MessageHeaders key is amqp_receivedExchange and value is  amq.topic]#
MessageHeaders key is x-mqtt-dup and value is  false]#
MessageHeaders key is x-mqtt-publish-qos and value is  0]#
MessageHeaders key is amqp_deliveryTag and value is  1]#
MessageHeaders key is amqp_consumerQueue and value is  xxx.xxx.xxx.xxx]#
MessageHeaders key is amqp_redelivered and value is  false]#
MessageHeaders key is id and value is  c43ef494-b2b8-28e1-c438-c6cae5a05bdb]#
MessageHeaders key is amqp_consumerTag and value is  amq.ctag-5Zp8XeEAM9V-_FYSu1igew]#
MessageHeaders key is timestamp and value is  1547097159463]#

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
There is no client ID property in AMQP 0-9-1. There are arbitrary headers and the appID property but the latter doesn't necessarily represent the same thing semantically. It is also possible to put any value into the payload.

This repository has nothing to do with MQTT.
