### ISSUE TITLE
A quorum queue in single active consumer mode leaks consumers

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#1825]
Discovered when doing acceptance of #1799.

The steps to reproduce are roughly this:

 * Set up a 2 or 3 node cluster
 * Declare a quorum queue
 * Open a few channels
 * Add consumers on them
 * Close some channels
 * Publish messages
 * Close more channels

At some point you will notice no deliveries and ghost consumers:

<img width="838" alt="screenshot 2019-01-10 at 23 43 45" src="https://user-images.githubusercontent.com/1090/50996327-a1e1f900-1532-11e9-999c-28f1845614ad.png">

**Comment by acogoluegnes** [comment]
I reproduced on a single node, with a sequence similar to what @michaelklishin described.

![image](https://user-images.githubusercontent.com/514737/51024908-02048980-158b-11e9-8c0f-dbd9e66145e4.png)

No deliveries as well, but the list of consumers becomes normal after a while:

![image](https://user-images.githubusercontent.com/514737/51025023-50198d00-158b-11e9-8cc5-b48dccd83c3e.png)

The consumers list from the CLI isn't consistent, but the list of channels is:

```
$ escript/rabbitmqctl list_consumers
Listing consumers on vhost / ...
queue_name	channel_pid	consumer_tag	ack_required	prefetch_count	arguments
sac.qq.consumers.leak	<rabbit@acogoluegnes-inspiron.2.3627.0>	9	false	0	[]
$ escript/rabbitmqctl list_channels 
Listing channels ...
pid	user	consumer_count	messages_unacknowledged
<rabbit@acogoluegnes-inspiron.2.16712.0>	guest	1	0
<rabbit@acogoluegnes-inspiron.2.16717.0>	guest	1	0
<rabbit@acogoluegnes-inspiron.2.16722.0>	guest	1	0
```

Investigating.
