### ISSUE TITLE
Feature request: timestamp when queued, time-in-queue metrics

### ISSUE THREAD

**Issue by g--** [rabbitmq/rabbitmq-server#1828]
Hi there!

My feature request would be to automatically add timestamps to every message as they are accepted by the queue.  The motivation behind this is to unlock some queue health monitors.  Specifically:

1. Rabbit-published metrics such as "average/max time in queue", and even "average/max time until acknowledged".  This could be used evaluate if there are sufficient queue consumers.

2. Rabbit-published metrics such as "oldest message in queue".  This could be used to alert situations where a low-volume queue is not making any progress because of broken/hung consumers.  In this situation queue-size alarm wouldn't have caught the problem.  (This happened to us in a pre-production environment)

3. consumer-published metrics such as "average time until message is resolved" which gives the consumer an opportunity to add fields to the metrics. 

I did a quick search of the mailing list and found this exchange suggesting the message producers and consumers should be responsible for metrics.[1]  Although this is possible for most features 1 and 3 above, feature 2 is not possible without rabbitmq integration.  In addition, features 1 and 3 require all producers to include the timestamp--retrofitting existing code takes a while.

Thanks!

[1] https://groups.google.com/forum/#!searchin/rabbitmq-users/%22time$20in$20queue%22%7Csort:date/rabbitmq-users/yo53sBppoAM/9lNSqwfoDAAJ

**Comment by michaelklishin** [comment]
[rabbitmq-message-timestamp](https://github.com/rabbitmq/rabbitmq-message-timestamp) does just that.

There is a metric on how old the head of the queue is as of #54, it doesn't work all that well in practice
and may or may not survive a major message store redesign.

**Comment by AndrewWinterman** [comment]
> [rabbitmq-message-timestamp](https://github.com/rabbitmq/rabbitmq-message-timestamp) does just that.
> 
> There is a metric on how old the head of the queue is as of #54, it doesn't work all that well in practice and may or may not survive a major message store redesign.

Are there plans to re-open this issue for quorum queues? Why doesn't it work all that well in practice?
