### ISSUE TITLE
The rabbitmq_event_exchange plug-in for one of the servers in the RabbitMQ cluster fails, causing the IoT service to subscribe to no event messages connected to this server

### ISSUE THREAD

**Issue by yzpangu** [rabbitmq/rabbitmq-server#1840]
The rabbitmq_event_exchange plug-in for one of the servers in the RabbitMQ cluster fails, causing the IoT service to subscribe to no event messages connected to this server。

The problem is resolved after restarting the RabbitMQ cluster

**Comment by lukebakken** [comment]
Hello and thanks for using RabbitMQ.

Unfortunately, you haven't provided enough information. Please post the following to the `rabbitmq-users` [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users):

* RabbitMQ, Erlang and operating system version
* List of plugins enabled
* Complete RabbitMQ log file
* Description of the problem. What does "fails" mean? Does the event exchange simply stop publishing messages? Do your consumers report errors?
