### ISSUE TITLE
Research: Possibility to recover and reconcile Mnesia data after node reconnection

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#1841]
## Partition handling and mnesia database.

This issue explains to some degree what is happening with the mnesia database and the RabbitMQ schema when nodes disconnect.

It also describes a possibility to recover RabbitMQ from disconnects when it’s a false-positive.

### Mnesia replication:

- Multi-master
  - Each node has its own view on the cluster status
- Per-table replication
- Tables may be in memory or on disk
- Requires all replicas to be up to replicate
  - Keeps track of nodes status, “disables” a node on disconnect
  - If node is “disabled” - data will not replicate there
  - Each node has its own list of enabled/disabled nodes
- If a live node rejoins the cluster, the data will not be re-merged.
- If a node restarts - it will rejoin the cluster and get data from the cluster, resetting the current node data if it was disconnected live.

- There are lower-level tools to re-merge data, utilised by tools like [unsplit](https://github.com/uwiger/unsplit) and [reunion](https://github.com/snar/reunion)

- If nodes are disconnected, they update their own schemas only. This can cause a “partial partition”, where nodes A and B may be considered disconnected, while still being connected to C.

- All this behaviours arise from the assumption that nodes will rarely disconnect, but crash and restart instead.

### RabbitMQ use of mnesia:

- Only some tables are replicated
- Rabbitmq uses both in-memory and on-disk tables
  - In-memory tables contain “trainsient” entities, which should not survive node restart
  - Because in-memory tables contain transient entities, there is an assumption that as soon as node restarts all transient entities disappear.
    - This is not entirely true for clusters, because some transient data is replicated (e.g. transient queues)
    - Because of that there is some additional code to cleanup those entities when a cluster goes down. This code is executed on other nodes.
- RabbitMQ also assumes that mnesia data is consistent and relies on the mnesia data for queue master location. Each time a new master is promoted - the replicated table is updated to reflect that.
- When a node stops, other nodes will update the mnesia database to remove transient entities and maybe update mirroring master.
  - This is done by the node monitor on monitor ‘DOWN’ message from the `rabbit` process. This message will fire if a node is down OR if the rabbit application stops

- This behaviour means that in case of disconnect, RabbitMQ will update the mnesia data and cause actual inconsistency in the database if rejoined.

- RabbitMQ does not try to rejoin the mnesia database unless autoheal is configured. Then it will restart some nodes to reload data from other nodes.
- If pause-minority/pause-of-all-down configured, the paused nodes will stop and restart when rejoined, reloading data from other nodes.

## Node disconnection:

When an erlang node disconnects from another node it will trigger `DOWN` messages on all monitors across the connection. Then it will trigger all node monitor `nodedown` messages.

In RabbitMQ it means all channels get DOWN messages from queues and vice-versa. Mirrored queues will be notified of the ring change. The node monitor module will first get the `DOWN` message from the application and then the `nodedown` from the node.

RabbitMQ node monitor tries to create a “proper partition” on the `nodedown` message, asking all the nodes it can still communicate to to check if they can communicate with the “disconnected node”. If they can, they send a message to the original node, which may cause it do disconnect from the “proxy” node.

If there are three nodes A, B and C.

1. A gets a nodedown from C
1. A asks B if it can connect to C `check_partial_partition`
1. If it can, B sends `partial_partition` to A
1. A disconnects from B

If there are more nodes, on step 2, A will send `check_partial_partition` to all of them.

## Mnesia recovery:

It should be possible to recover mnesia schema consistency by re-adding nodes to the cluster. This will cause an `inconsistent_database` message, but if there are no actual difference in data on different nodes, the cluster will actually be consistent after that. And can continue replicating.

If there are differences in the data on different partitions, it can be recovered as in [unsplit](https://github.com/uwiger/unsplit) application.

Node monitor tries to update the database on monitor `DOWN` message, removing the queues. It should be possible to re-add the queues from rejoining node.

To make rejoin possible, we should review all the monitors, which can trigger the false-positive DOWN message across the cluster.

Some actions, like mirrored queues promotion, may be delayed if the node can be rejoined.

It will be more challenging to rejoin nodes if there are actual data changes. If we had some sort of versioning, indicating that the user performed actual schema changes during partition, we could bail out and not try to recover mnesia consistency.

**Comment by michaelklishin** [comment]
I believe the conclusion of a spike was that as concluded before, Mnesia does not really assume that two sides of a partition can be reconciled without a reset on one side. So our efforts are exclusively on Mnevis now.
