### ISSUE TITLE
Upgrades may not replace the rabbit.schema file

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#1843]
`rabbitmq-users` message: [link](https://groups.google.com/d/msg/rabbitmq-users/4-G-RkBpKaA/THx7oMKYDwAJ)

Reproduction steps:

* Install and start RabbitMQ
* Stop RabbitMQ, upgrade to newer version with different `rabbit.schema` file
* Start RabbitMQ

The old cuttlefish schema may be in use. See the 3.7.9 to 3.7.10 upgrade for an example.

**Comment by michaelklishin** [comment]
@mohag schema files also come from plugins, so your understanding is basically correct.

**Comment by michaelklishin** [comment]
@hairyhum has most context here

**Comment by michaelklishin** [comment]
I think copying the file and overriding the one that's already there is what most people would expect: we want to have the latest schema file. The overhead of this is negligible.
