### ISSUE TITLE
statistics not available for exchange with bindings from another exchange

### ISSUE THREAD

**Issue by lazedo** [rabbitmq/rabbitmq-server#1844]
* RabbitMQ 3.7.8
* Erlang 20.3.8.5

configured topic exchange A
clients publishing to A with several keys
consumers for A getting updates by subscribed keys as expected
exchange statistics available in management-ui

configured topic exchange B
and a binding from A to B
consumers for B getting updates by subscribed keys as expected
exchange statistics for B in/out are not available

configured x-consistent-hash C
and a binding from A to C
consumers for C getting updates hashing key as expected
exchange statistics for C in/out are not available

i can try to fix this if someone points me in the right direction (erlang module)

Thanks

**Comment by michaelklishin** [comment]
This is expected. Exchanges are just names for routing tables and E2E routing simply "expands the table" before routing actually happens.
