### ISSUE TITLE
RabbitMQ denied new connection and Managemet GUI inaccessable after 2-3 hours later.

### ISSUE THREAD

**Issue by drony** [rabbitmq/rabbitmq-server#1862]
here is the log file summary

2019-02-03 09:17:17 =ERROR REPORT====
** Generic server <0.28955.255> terminating
** Last message in was {tcp,#Port<0.717023>,<<48,240,2,0,31,98,97,107,101,108,111,114,47,112,114,111,100,117,99,116,47,112,114,49,52,47,100,101,118,105,99,101,47,114,97,119,123,34,99,112,117,48,82,101,115,101,116,82,101,97,115,111,110,34,58,34,91,83,87,95,67,80,85,95,82,69,83,69,84,93,32,61,32,83,111,102,116,119,97,114,101,32,114,101,115,101,116,32,67,80,85,34,44,34,99,112,117,49,82,101,115,101,116,82,101,97,115,111,110,34,58,34,91,83,87,95,67,80,85,95,82,69,83,69,84,93,32,61,32,83,111,102,116,119,97,114,101,32,114,101,115,101,116,32,67,80,85,34,44,34,100,101,118,105,99,101,73,112,34,58,34,49,48,46,55,46,56,50,46,50,50,57,34,44,34,100,101,118,105,99,101,77,97,99,34,58,34,50,52,58,48,65,58,67,52,58,65,69,58,57,50,58,50,56,34,44,34,105,100,102,86,101,114,115,105,111,110,34,58,34,118,51,46,51,45,98,101,116,97,49,45,50,56,56,45,103,97,54,55,50,101,52,102,52,52,34,44,34,111,110,108,105,110,101,34,58,102,97,108,115,101,44,34,115,116,97,66,83,83,73,68,34,58,34,67,67,58,50,68,58,69,48,58,69,49,58,67,51,58,67,66,34,44,34,115,116,97,83,83,73,68,34,58,34,102,101,115,116,34,44,34,115,116,97,83,105,103,110,97,108,34,58,45,55,56,44,34,115,116,97,116,117,115,82,101,97,115,111,110,34,58,51,44,34,118,101,114,115,105,111,110,34,58,34,49,46,55,46,49,57,48,49,51,48,46,49,54,48,48,34,125,192,0>>}
** When Server state == {state,#Port<0.717023>,"5.26.166.166:62794 -> 5.9.147.236:1883",true,undefined,true,running,{none,<0.25.256>},<0.3918.256>,false,none,{proc_state,#Port<0.717023>,#{"device/raw/24:0A:C4:AE:92:28/cfg" => [0],device/raw/24:0A:C4:AE:92:28/cmd" => [0],"device/raw/cfg" => [0],"device/raw/cmd" => [0]},{<<"amq.ctag-9s6qm3FKMgUEdeTzWHbD3g">>,undefined},{0,nil},{0,nil},undefined,4,"pr1424:0A:C4:AE:92:28",true,undefined,{<0.6306.256>,undefined},<0.13262.256>,<<"amq.topic">>,{amqp_adapter_info,{5,9,147,236},1883,{5,26,166,166},62794,<<"5.26.166.166:62794 -> 5.9.147.236:1883">>,{'MQTT',"N/A"},[{variable_map,#{<<"client_id">> => <<"pr1424:0A:C4:AE:92:28">>}},{channels,1},{channel_max,1},{frame_max,0},{client_properties,[{<<"product">>,longstr,<<"MQTT client">>},{client_id,longstr,<<"pr1424:0A:C4:AE:92:28">>}]},{ssl,false}]},none,<0.470.0>,{auth_state,<<"admin">>,{user,<<"admin">>,[administrator],[{rabbit_auth_backend_internal,none}]},<<"/">>},#Fun<rabbit_mqtt_processor.0.123174653>,{5,26,166,166}},<0.13262.256>,{state,fine,5000,#Ref<0.3099276887.596115465.117228>}}
** Reason for termination == 
** {badarg,[{erlang,port_command,[#Port<0.717023>,<<208,0>>],[{file,"erlang.erl"},{line,3137}]},{rabbit_mqtt_processor,process_request,3,[{file,"src/rabbit_mqtt_processor.erl"},{line,303}]},{rabbit_mqtt_processor,process_frame,2,[{file,"src/rabbit_mqtt_processor.erl"},{line,72}]},{rabbit_mqtt_reader,process_received_bytes,2,[{file,"src/rabbit_mqtt_reader.erl"},{line,274}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1050}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
2019-02-03 09:17:17 =CRASH REPORT====
  crasher:
    initial call: rabbit_mqtt_reader:init/1
    pid: <0.28955.255>
    registered_name: []
    exception exit: {{badarg,[{erlang,port_command,[#Port<0.717023>,<<208,0>>],[{file,"erlang.erl"},{line,3137}]},{rabbit_mqtt_processor,process_request,3,[{file,"src/rabbit_mqtt_processor.erl"},{line,303}]},{rabbit_mqtt_processor,process_frame,2,[{file,"src/rabbit_mqtt_processor.erl"},{line,72}]},{rabbit_mqtt_reader,process_received_bytes,2,[{file,"src/rabbit_mqtt_reader.erl"},{line,274}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1050}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]},[{gen_server2,terminate,3,[{file,"src/gen_server2.erl"},{line,1166}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
    ancestors: [<0.12728.256>,<0.490.0>,<0.489.0>,<0.488.0>,rabbit_mqtt_sup,<0.463.0>]
    message_queue_len: 3
    messages: [{tcp_closed,#Port<0.717023>},{'EXIT',<0.6306.256>,normal},{'EXIT',<0.13262.256>,{shutdown,normal}}]
    links: [<0.12728.256>]
    dictionary: [{{credit_from,<0.6306.256>},398},{rand_seed,{#{jump => #Fun<rand.16.10897371>,max => 288230376151711743,next => #Fun<rand.15.10897371>,type => exsplus},[202832595309705357|249194460086343576]}},{gen_server_call_timeout,60000},{credit_flow_default_credit,{400,200}}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 15100
  neighbours:
2019-02-03 09:17:17 =SUPERVISOR REPORT====
     Supervisor: {<0.12728.256>,rabbit_mqtt_connection_sup}
     Context:    child_terminated
     Reason:     {badarg,[{erlang,port_command,[#Port<0.717023>,<<208,0>>],[{file,"erlang.erl"},{line,3137}]},{rabbit_mqtt_processor,process_request,3,[{file,"src/rabbit_mqtt_processor.erl"},{line,303}]},{rabbit_mqtt_processor,process_frame,2,[{file,"src/rabbit_mqtt_processor.erl"},{line,72}]},{rabbit_mqtt_reader,process_received_bytes,2,[{file,"src/rabbit_mqtt_reader.erl"},{line,274}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1050}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]}
     Offender:   [{pid,<0.28955.255>},{name,rabbit_mqtt_reader},{mfargs,{rabbit_mqtt_reader,start_link,[<0.3918.256>,{acceptor,{0,0,0,0},1883}]}},{restart_type,intrinsic},{shutdown,30000},{child_type,worker}]

2019-02-03 09:17:17 =SUPERVISOR REPORT====
     Supervisor: {<0.12728.256>,rabbit_mqtt_connection_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.28955.255>},{name,rabbit_mqtt_reader},{mfargs,{rabbit_mqtt_reader,start_link,[<0.3918.256>,{acceptor,{0,0,0,0},1883}]}},{restart_type,intrinsic},{shutdown,30000},{child_type,worker}]

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
I don't see where recent MQTT plugin code can be responsible for opening new [Erlang] ports (subprocesses) and it definitely cannot affect management UI in any way. So both likely have the same root cause and running out of file descriptors will affect management UI and any other listener/connecting client.

**Comment by michaelklishin** [comment]
#1863 (also redirected to the list) confirms that the node indeed runs out of file descriptors.

**Comment by michaelklishin** [comment]
FTR, the port references above refer to sockets and come from [rabbit_net](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_net.erl#L157). We are trying to reproduce connection supervisor termination when the node is exhausted of file descriptors.

**Comment by michaelklishin** [comment]
Further investigation concluded that

 * With 100 and 500 exceptions per second but enough file descriptor new clients can successfully connect
 * The supervisor in question, `rabbit_mqtt_connection_sup `, is per connection (meaning that there's one for every MQTT client connection), so its exit is expected and not going to affect the plugin's ability to accept more connections.
