### ISSUE TITLE
File descriptors running out

### ISSUE THREAD

**Issue by drony** [rabbitmq/rabbitmq-server#1863]
my rabbitmq setup running on windows server 2016. initial size is 7280 and total subscriber just 350. after 2-3 hours later rabbitmq file descriptors running out but active connection just ~300.
if file descriptors limit up to 32k this time 10 hours later running out.

https://github.com/rabbitmq/rabbitmq-server/issues/1862

**Comment by lukebakken** [comment]
Please read what @michaelklishin said [here](https://github.com/rabbitmq/rabbitmq-server/issues/1862#issuecomment-460267352) and do *_not_* open a new issue on GitHub.

Read [this](https://github.com/rabbitmq/rabbitmq-server/blob/master/CONTRIBUTING.md#github-issues), then provide the necessary information for us to help in a message posted to the mailing list. Do *not* paste large amounts of text - please attach configuration and log files to your message:

https://groups.google.com/forum/#!forum/rabbitmq-users

**Comment by michaelklishin** [comment]
File descriptors of a node can be inspected with `lsof -p [pid]` on Linux and [handle](https://docs.microsoft.com/en-us/sysinternals/downloads/handle) on Windows.

If the latter is available, RabbitMQ will report file and socket handles separately in the management UI.

There is no evidence that RabbitMQ itself leaks file descriptors. It is extremely likely that one of the applications [leaks connections](https://www.rabbitmq.com/connections.html#monitoring) or messages pile up, meaning the message store has to use more and more segment files.

Collecting more data about the node(s) that exhibit this behavior will lead you to an answer.

Consider at least providing RabbitMQ version information when you ask for help, too.
