### ISSUE TITLE
Queues become unbound to default exchange, but in an inconsistent way

### ISSUE THREAD

**Issue by Avivsalem** [rabbitmq/rabbitmq-server#1872]
Hi.
I have a 3 node cluster, and today i encountered a weird and buggy behavior.
I'm using the latest version (3.7.11) and It seems that I have reproduced what is described [here](https://groups.google.com/forum/#!topic/rabbitmq-users/3tlWiaeRBDc):
The end result displayed these weird symptoms:
1. some of my queues did not appear bound to the default exchange (didn't show up on api/bindings)
2. even though they were not bound to default exchange, publishing on default exchange with queue name as routing key, was successfull. (message got into queue).
3. publishing to an exchange that has no other bindings and has the default exchange as alternate-exchange, with queue name as routing key, resulted in an unrouteable error (which, before the incident, resulted in successful publish to queue)

so there is inconsistency in the behaviour.
the solution was to delete the queue, re-declare it as non-durable, delete it, and re-declare it as durable again.

it seems like a race condition in the cluster shutdown, causes some inconsistencies in your durable queues registry (making it still publishable directly from the default exchange, but not via alternate-exchange to the default exchange).

while moving to qurom queues in 3.8.0 may solve some of the race itself, i think it might worth taking a look into how such inconsistency is possible in the queue registry (possibly a bug in the implementation of the default exchange?)

I hope this information is helpful, and thank you in advance!

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
I'm filing a new umbrella issue for [similar threads](https://groups.google.com/forum/#!topic/rabbitmq-users/3tlWiaeRBDc) even though we never managed to reproduce it, even with steps that supposedly "do it 100% of the time".

**Comment by michaelklishin** [comment]
Also note that default exchange routing is a special case and will be even more explicitly so as of #1833 and friends. There will no longer be any explicit bindings to the default exchange as they are not necessary and only consume resourcsee.

**Comment by michaelklishin** [comment]
Duplicate of #1873.

**Comment by Avivsalem** [comment]
Thank you for response!
2 things:
1. Our method of reproduction is very simple... 
Set up a 3 node cluster with durable queues. 
Simultaneously (we were using multi exec in moba xterm) call rabbitmqctl stop_app on all three nodes. 
When cluster starts up again, the symptoms appear on some queues. 

2. You said that in 3.8.0, there will be no more bindings to the default exchange... Will it still be possible to use the default exchange as alternate exchange? (because in my symptoms, when no binding exists to the default exchange, the alternate exchange routing to it stops working...)

**Comment by michaelklishin** [comment]
The removal of explicit default exchange bindings is meant to be backward compatible. They are already gone in `3.8.0-beta.2`, we can add a test with default exchange being set to AE.

We already explained many times on the list that shutting down all nodes concurrently (at the same time) is not a scenario we consider realistic and plan dedicating time to. Non-replicated parts of the system (e.g. Shovels) cannot deterministically work out which node they should migrate to when all of them are going down concurrently. Stopping nodes one by one is a different story.

Raft-based features in 3.8 will require a quorum of nodes to be online and in some cases, extra steps
for the operator to take to indicate that a system now has one extra node that certain quorum queues should use as a member or that a certain node is about to be removed for good. https://github.com/rabbitmq/rabbitmq-cli/issues/286, https://github.com/rabbitmq/rabbitmq-cli/issues/287 are two examples. It is easy to see how a simultaneous node shutdown is a scenario where even a robust and predictable consensus protocol cannot guarantee much.

**Comment by lukebakken** [comment]
@Avivsalem -

> Our method of reproduction is very simple...Set up a 3 node cluster with durable queues.

* How many queues?
* Any other queue properties other than "durable"?
* What policies are in place? Are the queues mirrored?

These details matter, and the lack of them is why we still yet have to reproduce this issue.

**Comment by michaelklishin** [comment]
@Avivsalem you can export definitions in the environment that you use to reproduce and send it to me privately (`mklishin` at Pivotal domain).

**Comment by Avivsalem** [comment]
@lukebakken, @michaelklishin 
i'm sorry, but i cannot export defenitions and share them... but here is my setup:
1. HW: 3 nodes, 8 CPU, 8GB ram, 500GB ssd storage each.
2. SW: Centos 7 + rabbitmq 3.7.11 + erlang 21.2.3
rabbit:
3 nodes
cluster_partition_policy: pause_minority
170 durable queues - not binded to any exchange (but the default...)
single policy on all queues:
  ha-mode: excatly
  ha-params: 2
  ha-sync-mode: manual
  ha-promote-on-failure: when_synced
one internal durable direct exchange called NULL with alternate-exchange=''
no bindings from NULL

all 170 queues are empty and synced.
rabbitmqctl stop_app is called simultaniously on all 3 nodes.

when cluster starts up again, some queues (~100) are not bound to the default exchange...
publish directly on default exchange with routing_key=QUEUE works.
publish on NULL with routing_key=QUEUE works for queues which are bound to default exchange.
for queues which are not bound to default exchange, we get UnroutableError

hope that's more helpfull...
if i've missed something you need to know, let me know

**Comment by lukebakken** [comment]
@Avivsalem thanks, that's the sort of detail we need.

**Comment by hairyhum** [comment]
@Avivsalem Can you please check if you have lines like this in the logs:
`Queue <...> failed to initialise`
And maybe even something like that:
`{function_clause,[{rabbit_variable_queue,d,[{delta`

That would confirm the findings from other people with the similar issue.

**Comment by Avivsalem** [comment]
I'll Check

**Comment by Avivsalem** [comment]
@hairyhum
We have lots of "queue <> failed to initialise"
In the logs. 

But not the other stuff you wrote.

**Comment by michaelklishin** [comment]
@Avivsalem thanks, we have a PR under review that may help with this specific case. If you let us know what package type you use we can produce a "pre-merge" build for you to try.

**Comment by Avivsalem** [comment]
@michaelklishin
Thanks! 
I use rpm for centos 7.
Although I doubt that anyone will let me install a non stable version on prod environment 😝

**Comment by michaelklishin** [comment]
We wouldn't ask you to test it in production. Is there really no other way?

**Comment by Avivsalem** [comment]
It would require me to set up a test cluster with the same specs... I'm not optimistic.. 
Send me the version and I'll see what I can do...

**Comment by lukebakken** [comment]
@Avivsalem 

Unfortunately, your reproduction steps don't work on my local workstation. When RabbitMQ starts and I publish messages to the `NULL` exchange, everything works fine.

See my reproduction steps and scripts I used here:

https://gist.github.com/lukebakken/602dafac58d2d3cc20028199b618af23

**Comment by Avivsalem** [comment]
I notices that you forgot to call channel.confirm_delivery()
On the publishing channel... You have to do it once, after creation. Without it, you won't get unroutable errors...

**Comment by Avivsalem** [comment]
Also, you can call /api/bindings and see if all the queues appear bound to default exchange

**Comment by Avivsalem** [comment]
And one more thing... My fault...
I forgot to tell you that the policy also states 
Queue-mode:lazy
Queue-master-locator:min-masters... 

Sorry!

**Comment by lukebakken** [comment]
@Avivsalem - thanks for reviewing my test. For the `mandatory` flag, all I had to do was add a callback for `Basic.Return` [here](https://gist.github.com/lukebakken/602dafac58d2d3cc20028199b618af23#file-publish-msgs-py-L15-L20) and ensure that the code processes events for a while before exiting, in case a `Basic.Return` comes in "late". Delivery confirmations would also be an option but they don't have an affect on the `mandatory` flag ([comment](https://github.com/pika/pika/blob/master/pika/adapters/blocking_connection.py#L2173-L2176))

**Comment by Avivsalem** [comment]
Still. In our code we call confirm_delivery on the channel First... So, if you aim to reproduce, you might wanna add that anyway... 😝

**Comment by lukebakken** [comment]
I'll keep that in mind, but a basic test to the default exchange with routing key `foobarbaz` produces the expected result -

```
$ python ./test-publish.py 
INFO       2019-02-14 08:01:33,795 __main__                       <module>                             13  : pika version: 0.13.0
INFO       2019-02-14 08:01:33,797 pika.adapters.base_connection  _create_and_connect_to_socket        237 : Pika version 0.13.0 connecting to ::1:5672
INFO       2019-02-14 08:01:33,799 pika.adapters.blocking_connection __init__                             1201: Created channel=1
INFO       2019-02-14 08:01:33,800 __main__                       <module>                             27  : Exiting in 5 seconds...
ERROR      2019-02-14 08:01:33,800 __main__                       on_return_callback                   16  : Basic.Return: (<Basic.Return(['exchange=', 'reply_code=312', 'reply_text=NO_ROUTE', 'routing_key=foobarbaz'])>,)
INFO       2019-02-14 08:01:33,801 pika.adapters.blocking_connection close                                712 : Closing connection (200): Normal shutdown
INFO       2019-02-14 08:01:33,801 pika.channel                   close                                529 : Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN socket=('::1', 64730, 0, 0)->('::1', 5672, 0, 0) params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
INFO       2019-02-14 08:01:33,801 pika.channel                   _on_closeok                          1090: Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN socket=('::1', 64730, 0, 0)->('::1', 5672, 0, 0) params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
INFO       2019-02-14 08:01:33,801 pika.connection                close                                1309: Closing connection (200): Normal shutdown
INFO       2019-02-14 08:01:33,801 pika.connection                _on_terminate                        2095: Disconnected from RabbitMQ at localhost:5672 (200): Normal shutdown
INFO       2019-02-14 08:01:33,802 pika.adapters.blocking_connection _flush_output                        480 : Connection closed; result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED socket=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>, reason_code=200, reason_text='Normal shutdown')
```

**Comment by lukebakken** [comment]
Well, the test still passes in that no messages are returned, with or without `confirm_delivery` (gist is updated).

![works-on-my-machine-badge-small](https://user-images.githubusercontent.com/514926/52801151-2512d500-3032-11e9-925f-dec7d7dbece3.png)

**Comment by Avivsalem** [comment]
The only thought that crosses my mind that it might be something to do with the network delays we have, since we run the nodes on different machines...
While your nodes all run on same machine. 

But other than that, I ran out... 
Thanks for all the effort!

**Comment by lukebakken** [comment]
Right, it's probably more instantaneous locally. I might try adding small delays between the first `stop_app` and the other two.

**Comment by Avivsalem** [comment]
No... You got it all wrong...
We call the stop_app simultaneously on all three machines (not via script, but via mutli exec on ssh... Actually hitting enter at the same time on all three terminals) 

What I meant is, that the nodes negotiation on shutdown is somewhat delayed by the network, maybe causing the race.

**Comment by lukebakken** [comment]
I could see about using something like `toxiproxy` to introduce some delay in distributed Erlang connections. What's probably happening in your environment is that one node does in fact appear to "go down" before the other two (either due to slight delays in ssh or distributed Erlang communication) so some part of partition detection happens.

We never clarified if your environment is VM-based or bare metal, and what kind of network connects nodes.

**Comment by Avivsalem** [comment]
3 VMs. Regular network. Nothing special

**Comment by michaelklishin** [comment]
Please take this to the mailing list.
