### ISSUE TITLE
Chocolatey release?

### ISSUE THREAD

**Issue by rgl** [rabbitmq/rabbitmq-server#1896]
Can you please update the chocolatey package for latest 3.7.12 version?

**Comment by michaelklishin** [comment]
We submit releases regularly but they can take months to go through approval (for example, last week `3.7.7` was approved. It was released in in July 2018).

**Comment by rgl** [comment]
https://github.com/rabbitmq/chocolatey-package/blob/master/rabbitmq.nuspec#L6 still says 3.7.7. is that expected? does that repository contains the latest package source?

**Comment by michaelklishin** [comment]
@rgl yes and no. Submissions to NuGet don't require committing or pushing to GitHub. We will submit 3.7.12 next week but as I said above, you may get it months from now. The bottleneck in the NuGet release process is not submission automation.

**Comment by rgl** [comment]
I understand. Thank you!

**Comment by michaelklishin** [comment]
[3.7.12](https://chocolatey.org/packages/rabbitmq/3.7.12) was approved by a reviewer. It doesn't support Erlang 21 as a dependency but `3.7.13` will.
