### ISSUE TITLE
Install rabbitmq server on Linux with brew (linuxbrew)

### ISSUE THREAD

**Issue by chiddekel** [rabbitmq/rabbitmq-server#1899]
Good news, on Linux e.g Ubunt, Fedora, Debian - you can install rabbitmq using linuxbrew.
brew install rabbitmq

http://linuxbrew.sh/#install

**Comment by michaelklishin** [comment]
Thank you for the heads-up. I suggest that you post this to rabbitmq-users, our public mailing list.
