### ISSUE TITLE
"Ghost" queues on rabbitmq

### ISSUE THREAD

**Issue by c-datculescu** [rabbitmq/rabbitmq-server#190]
Hello all.

Today we hit quite a big issue in a production environment. Due to some failures in our network, we ended up at some point with a ghost queue (it is a queue that is declared on one node, but cannot be deleted whatsoever). 

Rabbitmqadmin just hangs when deleting and so do other attempts at resolving this.

I am unsure how to reproduce this behavior and i have not got a slightest idea where to start. The error log contains nothing as well.

One maybe important thing, at some point we ended up with only one node in the cluster and we had to recluster the other nodes manually one at a time.

**Comment by c-datculescu** [comment]
After some tinkering we managed to get rid of the "ghost" queue. One node from the cluster was blocking the entire operation on that queue plus on a shovel generated queue. Removing the node fixed the issue for now but this led to message loss across the entire cluster.

**Comment by michaelklishin** [comment]
If queue master is not available, operations currently will wait for it to come back (unless the queue is not durable, in which case it will be relocated to another node). Use mirroring (then master will be moved) or non-durable queues. There's an issue for introducing timeouts in multiple places, too.
