### ISSUE TITLE
New metric: unroutable message [drop] rate

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#1904]
There are multiple features that can help narrow down unroutable messages but they require some setup. We have enough evidence that many users spend a lot of time guessing as to what's going on before they finally read the docs on e.g. Publisher confirms or Firehose and apply/use those features.

Per discussion with the team, a new metric that demonstrates the rate of dropped unroutable messages would be very helpful. It would complement the already existing return rate but count the occurrences of events when a message was dropped because it wasn't published as `mandatory` and did not route to any queue[s].

**Comment by gerhard** [comment]
Reminding myself to add this to [rabbitmq-prometheus](https://github.com/rabbitmq/rabbitmq-prometheus) when it becomes available.

**Comment by gerhard** [comment]
Should we add this to https://github.com/rabbitmq/rabbitmq-prometheus/blob/master/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl#L37 as well?

**Comment by michaelklishin** [comment]
Definitely but let's get it through QA and merge it first.

**Comment by gerhard** [comment]
![image](https://user-images.githubusercontent.com/3342/56739086-d6866300-6765-11e9-8fb8-4cd229837aee.png)

The rest of this party is at https://github.com/rabbitmq/rabbitmq-server/pull/1988#issuecomment-486670955

**Comment by michaelklishin** [comment]
Per discussion with @dumbbell: when/if we backport feature flag support to `v3.7.x`, this can be backported as well.
