### ISSUE TITLE
Allow infinite queues by storing the queue's existance only on-disk

### ISSUE THREAD

**Issue by thedrow** [rabbitmq/rabbitmq-server#1907]
Given that there is a memory overhead for each declared queue there's a [practical limit on the number of queues](http://rabbitmq.1065348.n5.nabble.com/Max-messages-allowed-in-a-queue-in-RabbitMQ-td26063.html) which is a shame if you want to have a topology that for example fans out messages to thousand of queues (for example: sending notifications for all my followers on a social network).
A lazy queue stores messages only on-disk but requires an Erlang process which does consume memory and by default has a limit.
The queue type I'm proposing, once declared store both the messages and the queue's existence on-disk and does not create a new Erlang process.
Instead, a configurable amount of processes will be created and if a message is not routable to a queue declaration stored in-memory, it will be passed on to the "infinite queues" Erlang processes.

Granted, this limits the performance of such queues but allow one to be able to create very complex topologies.

Celery has a deprecated AMQP backend (which is now replaced by the RPC backend) that creates a queue per message. It could have used this feature if there wasn't a reply-to feature.
In any case, this feature has other valid usecases such as handling the case of in house data centers which lack the capacity to store all queues in memory due to lack of servers.

**Comment by lukebakken** [comment]
Let me re-paste the message that is displayed when you click "New Issue" -

----

Thank you for using RabbitMQ.

**STOP NOW AND READ THIS** BEFORE OPENING A NEW ISSUE ON GITHUB

Unless you are CERTAIN you have found a reproducible problem in RabbitMQ or
have a **specific, actionable** suggestion for our team, you must first ask
your question or discuss your suspected issue on the mailing list:

https://groups.google.com/forum/#!forum/rabbitmq-users

Team RabbitMQ does not use GitHub issues for discussions, investigations, root
cause analysis and so on.

Please take the time to read the CONTRIBUTING.md document for instructions on
how to effectively ask a question or report a suspected issue:

https://github.com/rabbitmq/rabbitmq-server/blob/master/CONTRIBUTING.md#github-issues

Following these rules **will save time** for both you and RabbitMQ's maintainers.

Thank you.

**Comment by michaelklishin** [comment]
> A lazy queue stores messages only on-disk but requires an Erlang process which does consume memory and by default has a limit.

A queue is a stateful entity. That state has to be stored somewhere, and even if that somewhere is "on disk", it can only be done by a process. While a different design could use fewer processes for a given number of queues, I don't see how it could be 0. Queue process pooling was discussed at some point but it's not in the first 10 of priorities at the moment.
