### ISSUE TITLE
RabbitMQ management plugin "Queued messages" is empty 

### ISSUE THREAD

**Issue by nbari** [rabbitmq/rabbitmq-server#1951]
After upgrading to `3.7.11` or `3.7.13` when querying the web management plugin, the `Queued messages` always shows 0 as in the attached picture:

<img width="906" alt="Screenshot 2019-03-20 at 17 52 22" src="https://user-images.githubusercontent.com/364199/54704833-cf06e500-4b3b-11e9-81cf-bd07e6f61edc.png">

In previous versions the behavior was similar to the `Message rates`

**Comment by lukebakken** [comment]
First of all, "Queued messages" should be 0 or close to it if your consumers are keeping up with your producers. This is what I see locally when running RabbitMQ and PerfTest, for instance:

![rabbitmq-3 7 13-perftest](https://user-images.githubusercontent.com/514926/54705403-f9d04980-4af9-11e9-84bc-7102edaef754.png)

I suggest clearing the cache in your browser and then selecting a different time range. If the issue persists and you have reliable steps to reproduce, please post them to the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users).

**Comment by michaelklishin** [comment]
One minute of data and a single chart are not enough to draw any conclusions. A way to reproduce with `PerfTest` would be great. So would server logs and information about what the "previous versions" are. Please start a rabbitmq-users thread.

**Comment by nbari** [comment]
Not an issue/bug, my bad, after fixing some apps now they consume what is published in a reasonable amount of time keeping the  "Queued messages" to 0

**Comment by lukebakken** [comment]
@nbari thanks a lot for following up, we appreciate it.
