### ISSUE TITLE
User policy with overflow "reject-publish" does not revert to default value when overflow removed from policy.

### ISSUE THREAD

**Issue by kevinpayne** [rabbitmq/rabbitmq-server#1980]
This is a small issue I found when using `overflow` with user policies in RabbitMQ 3.7.4

1. Create a queue user policy with `overflow` value of `reject-publish` . Set `max-length` to 100. 
2. Verify producer receives nacks once downstream queue limit (100) has been reached. This works as expected.
3. Now update the same policy to remove the `overflow` property altogether.  The expectation is that overflow will revert to the default value `drop-head` and no longer send nacks to the producer.
4. Producer sends a message to the full queue and unexpectedly still receives nacks.

**Comment by lukebakken** [comment]
Fixed by #1994
