### ISSUE TITLE
RabbitMQ 3.7.* creates a lot of zombie processes on Linux

### ISSUE THREAD

**Issue by mihailnenov** [rabbitmq/rabbitmq-server#1984]
**_RabbitMQ_** creates a bunch of zombie processes on Linux, 3 per minute. This is most probably related to the concrete Linux kernel version, distribution, etc. 
I observed it with RabbitMQ 3.7.9 (rabbitmq-server-3.7.9-1.el7.noarch.rpm) and Erlang 21.2 (erlang-21.2-1.el7.centos.x86_64.rpm) 
and 3.7.14 (rabbitmq-server-3.7.14-1.el7.noarch.rpm) with Erlang 21.3.4 (erlang-21.3.4-1.el7.x86_64.rpm)

Here is the output of of "ps aux":

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  40692  1420 ?        Ss   18:38   0:00 /sbin/runuser -u rabbitmq -- /usr/lib/rabbitmq/bin/rabbitmq-server
rabbitmq    35  0.0  0.0  13836  1668 ?        S    18:38   0:00 /bin/sh /usr/lib/rabbitmq/bin/rabbitmq-server
rabbitmq   137  0.0  0.0      0     0 ?        Zs   18:38   0:00 [epmd] <defunct>
rabbitmq   138  0.0  0.0  15864   356 ?        S    18:38   0:00 /usr/lib64/erlang/erts-10.3.3/bin/epmd -daemon
rabbitmq   142  0.0  0.0      0     0 ?        Zs   18:38   0:00 [erl_child_setup] <defunct>
rabbitmq   168  0.0  0.0      0     0 ?        Z    18:38   0:00 [inet_gethost] <defunct>
rabbitmq   176  0.0  0.0      0     0 ?        Zs   18:38   0:00 [erl_child_setup] <defunct>
rabbitmq   201  1.6  0.2 4300768 68644 ?       Sl   18:38   0:04 /usr/lib64/erlang/erts-10.3.3/bin/beam.smp -W w -A 96 -MBas ageffcbf -MHas ageffcbf -MBlmbcs 512 -MHlmbcs 512 -MMmcs 30 -P 1048576 -t 5000000 -stbt db -zdbbl 128000 -K true -B i -- -root /usr/lib64/erlang -progname erl -- -home /var/lib/rabbitmq -- -pa /usr/lib/rabbitmq/lib/rabbitmq_server-3.7.14/ebin  -noshell -noinput -s rabbit boot -sname rabbit@ap-orca2s -boot start_sasl -config /etc/rabbitmq/advanced -conf /etc/rabbitmq/rabbitmq.conf -conf_dir /var/lib/rabbitmq/config -conf_script_dir /usr/lib/rabbitmq/bin -conf_schema_dir /var/lib/rabbitmq/schema -conf_advanced /etc/rabbitmq/advanced.config -kernel inet_default_connect_options [{nodelay,true}] -sasl errlog_type error -sasl sasl_error_logger false -rabbit lager_log_root "/var/log/rabbitmq" -rabbit lager_default_file "/var/log/rabbitmq/rabbitmq.log" -rabbit lager_upgrade_file "/var/log/rabbitmq/rabbit@ap-orca2s_upgrade.log" -rabbit enabled_plugins_file "/opt/rabbitmq/etc/enabled_plugins" -rabbit plugins_dir "/usr/lib/rabbitmq/plugins:/usr/lib/rabbitmq/lib/rabbitmq_server-3.7.14/plugins" -rabbit plugins_expand_dir "/opt/rabbitmq/mnesia/rabbit@ap-orca2s-plugins-expand" -os_mon start_cpu_sup false -os_mon start_disksup false -os_mon start_memsup false -mnesia dir "/opt/rabbitmq/mnesia/rabbit@ap-orca2s" -kernel inet_dist_listen_min 25672 -kernel inet_dist_listen_max 25672
rabbitmq   210  0.0  0.0      0     0 ?        Zs   18:38   0:00 [erl_child_setup] <defunct>
rabbitmq   239  0.0  0.0      0     0 ?        Zs   18:38   0:00 [epmd] <defunct>
rabbitmq   240  0.0  0.0      0     0 ?        Z    18:38   0:00 [epmd] <defunct>
rabbitmq   339  0.0  0.0  10688   696 ?        Ss   18:38   0:00 erl_child_setup 65536
rabbitmq   371  0.0  0.0      0     0 ?        Zs   18:38   0:00 [erl_child_setup] <defunct>
rabbitmq   386  0.0  0.0  15860   768 ?        Ss   18:38   0:00 inet_gethost 4
rabbitmq   387  0.0  0.0  22208   952 ?        S    18:38   0:00 inet_gethost 4
rabbitmq   411  0.0  0.0      0     0 ?        Zs   18:39   0:00 [epmd] <defunct>
rabbitmq   412  0.0  0.0      0     0 ?        Z    18:39   0:00 [epmd] <defunct>
rabbitmq   416  0.0  0.0      0     0 ?        Zs   18:39   0:00 [erl_child_setup] <defunct>
rabbitmq   464  0.0  0.0      0     0 ?        Zs   18:40   0:00 [epmd] <defunct>
rabbitmq   465  0.0  0.0      0     0 ?        Z    18:40   0:00 [epmd] <defunct>
rabbitmq   469  0.0  0.0      0     0 ?        Zs   18:40   0:00 [erl_child_setup] <defunct>
rabbitmq   523  0.0  0.0      0     0 ?        Zs   18:41   0:00 [epmd] <defunct>
rabbitmq   524  0.0  0.0      0     0 ?        Z    18:41   0:00 [epmd] <defunct>
rabbitmq   528  0.0  0.0      0     0 ?        Zs   18:41   0:00 [erl_child_setup] <defunct>
rabbitmq   600  0.0  0.0      0     0 ?        Zs   18:42   0:00 [epmd] <defunct>
rabbitmq   601  0.0  0.0      0     0 ?        Z    18:42   0:00 [epmd] <defunct>
rabbitmq   605  1.5  0.0      0     0 ?        Zs   18:42   0:00 [erl_child_setup] <defunct>
root       630  0.0  0.0  51740  1744 ?        Rs   18:42   0:00 ps aux
```

All defunct processes have "runuser" for a parent. These multiple processes are created periodicallly every minute, most probably ralated to some kind of internal heartbeat and I don't see way to configure this.
The server runs with the default configuration (no rabbitmq.conf) and no plugins activated.
Looks like the parent doesn't properly handle **SIGCHLD**, or _doesn't manage to handle it in certein conditions_.

Added a config file only to configure debug output, attached.

The **_RabbitMQ_** servier runs in **_CentOS_** docker container, on top of **_RedHat_**

_Host Linux distribution:_
```
bash-4.2# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

_Container:_
```
bash-4.2# cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
bash-4.2# cat /etc/centos-release-upstream
Derived from Red Hat Enterprise Linux 7.6 (Source)
```

_Linux kernel 3.10:_
```
bash-4.2# uname -a
Linux ap-orca2s.oneadr.net 3.10.0-957.10.1.el7.x86_64 #1 SMP Thu Feb 7 07:12:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

[BugReport.log](https://github.com/rabbitmq/rabbitmq-server/files/3090690/BugReport.log)
[BugReport-advanced.config.txt](https://github.com/rabbitmq/rabbitmq-server/files/3090691/BugReport-advanced.config.txt)
[BugReport-rebbimqctl-environment.txt](https://github.com/rabbitmq/rabbitmq-server/files/3090692/BugReport-rebbimqctl-environment.txt)
[BugReport-rebbimqctl-report.txt](https://github.com/rabbitmq/rabbitmq-server/files/3090693/BugReport-rebbimqctl-report.txt)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Neither `erl_child_setup` nor `epmd` are not started by RabbitMQ, they are started by the Erlang runtime.

A quick Google search for `epmd <defunct>` leads to https://github.com/joyent/containerpilot/issues/439, https://github.com/habitat-sh/core-plans/issues/1099, http://erlang.org/pipermail/erlang-questions/2015-December/087172.html.

**Comment by mihailnenov** [comment]
Thanks for your comments!
