### ISSUE TITLE
Provide more detailed rabbitmq.conf validation errors on startup

### ISSUE THREAD

**Issue by gmr** [rabbitmq/rabbitmq-server#1985]
I'm spending a fair amount of time playing "spot the error" in rabbitmq.conf due to poor error output on startup failure. I'd be nice if instead of just reporting `init terminating in do_boot (badarg)` on startup failure, the parameter and value that is causing the failure is returned in the output.

The startup failure is early enough that I do not get any log information and only get the erl_crash.dump file.

I did work out I could use the cuttlefish binary provided as part of the distribution to troubleshoot where the failures are by running `/usr/lib/rabbitmq/bin/cuttlefish -c /etc/rabbitmq/rabbitmq.conf -s /var/lib/rabbitmq/schema/`, but did not find it in the configuration documentation as a possible troubleshooting step. Ideally the output from cuttlefish could be spit out on a startup failure due to config validation.

Ubuntu Xenial
Erlang 21.3.5-1 (From RabbitMQ bintray Repo)
RabbitMQ 3.7.14

Example of failure output:
```
root@ansible:/etc/rabbitmq# /usr/lib/rabbitmq/bin/rabbitmq-server 

BOOT FAILED
===========

Error description:
    rabbit:start_it/1 line 484
    rabbit:boot_error/2 line 972
    rabbit_lager:log_locations/0 line 97
    rabbit_lager:ensure_lager_configured/0 line 198
    rabbit_lager:lager_configured/0 line 206
    lager:list_all_sinks/0 line 341
    lager_config:get/2 line 71
    ets:lookup(lager_config, {'_global',handlers})
error:badarg
Log file(s) (may contain more information):

{"init terminating in do_boot",badarg}
init terminating in do_boot (badarg)
```

The traceback also makes it appear that it's a lager issue when I've been able to prove it to be something else multiple times, in my latest case, specifying ` management.inactivity_timeout` instead of `management.tcp.inactivity_timeout`.

**Comment by lukebakken** [comment]
Hi @gmr thanks for the reproduction steps, I just observed this. We do have validation of config files on start but this obviously demonstrates a regression or something that can be improved. I'm investigating now.

**Comment by 15332318109** [comment]
same issues.When will it be released?

**Comment by michaelklishin** [comment]
@15332318109 we make no ETA promises. You are welcome to contribute a fix, this is open source software after all.

**Comment by 15332318109** [comment]
sorry  it is misoperation

but i like rabbitmq.As soon as possible to learn



祝工作顺利！

孙文博


手机：15332318109

邮件：wenbo.sun@quanshi.com
 
From: Michael Klishin
Date: 2019-04-24 15:00
To: rabbitmq/rabbitmq-server
CC: wenbo.sun; Mention
Subject: Re: [rabbitmq/rabbitmq-server] Provide more detailed rabbitmq.conf validation errors on startup (#1985)
@15332318109 we make no ETA promises. You are welcome to contribute a fix, this is open source software after all.

**Comment by lukebakken** [comment]
We're testing #1990 which should fix this issue. Thanks @velimir
