### ISSUE TITLE
Missing support for unsigned 32-bit integer field value type

### ISSUE THREAD

**Issue by TheCount** [rabbitmq/rabbitmq-server#20]
When sending a message with a header with value kind 'i' (meaning long-uint) as specified in AMQP 0-9-1 section 4.2.1, the rabbitmq-server responds with Connection.Close with an obscure "INTERNAL_ERROR". I haven't had the time to build a server and the management tool from the repositories right now, but the issue seems to be in rabbit_binary_parser.erl, lines 41 and onward, where the case for 'i' is simply missing.

**Comment by hairyhum** [comment]
There are bunch of types from 0-9-1 missing in `rabbit_binary_parser`. I'm not sure though what RType values should be used for them.
Missing types:
 'B' short-short-uint
 'U' short-int
 'u' short-uint
 'i' long-uint
 'L' long-long-int

And there are also 's' type tag, which means 'short-string' which is `OCTET *string-char` and in current implementation it is being parsed like `signed short` 
https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_binary_parser.erl#L66

**Comment by michaelklishin** [comment]
@hairyhum take a look at [AMQP 0-9-1 Errata](http://www.rabbitmq.com/amqp-0-9-1-errata.html) as well as [AMQP 0-8 and 0-9-1 differences](http://www.rabbitmq.com/amqp-0-8-to-0-9-1.html).

**Comment by hairyhum** [comment]
So we can at least add 'B', 'u', and 'i' types as 'unsignedbyte', 'unsignedshort' and 'unsignedint' respectively.
