### ISSUE TITLE
Configure the dead-letter queue conversion queue, and set the message expiration not 5 minutes, 24 hours. When the time arrives, it will occasionally not forward, and it will remain in the dead-letter queue.

### ISSUE THREAD

**Issue by 501956430** [rabbitmq/rabbitmq-server#2005]
Configure the dead-letter queue conversion queue, and set the message expiration not 5 minutes, 24 hours. When the time arrives, it will occasionally not forward, still stay in the dead-letter queue, use the rabbitmq-manager web client to operate the message: "get message" The message will be forwarded to the exchange queue. What is the reason, why can't it be automatically forwarded after the message expires? Can anyone help me?

code: 
`

@Bean
    public Queue orderDlxQueue(){
        return QueueBuilder.durable("orderDlxQueue")
                .withArgument("x-dead-letter-exchange", "expiration.direct")
                .withArgument("x-dead-letter-routing-key", "order")
                .build();
    }
`
` 
@Bean
    Binding orderDlxMessage() {
        return BindingBuilder.bind(orderDlxQueue()).to(dlxExchange()).with("order-routingKey");
    }`

rabbitmq-service version: 3.7.13
Erlang 21.3.6

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.
