### ISSUE TITLE
"Urgent" Dead letter exchange Message expired will not be forwarded, affecting normal use, who can help me?

### ISSUE THREAD

**Issue by 501956430** [rabbitmq/rabbitmq-server#2007]
After testing, it is concluded that at the same time, multiple messages are put into the dead letter queue, such as:
Article 1: Expiration time: 3 minutes, Article 2: Expiration time 1 hour, 3rd expiration time 30 minutes.
Conclusion: The first one can be forwarded normally, but the third message will wait until the second message expires before being forwarded to the exchange queue! why? Is this a forwarding strategy for death letters?
I want the effect message The third message expires and is immediately forwarded to the dead letter queue without waiting. Can anyone help me?

**Comment by 501956430** [comment]
Erlang version:21.3.5
rabbitmq-service version : 3.7.14

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
There isn't a whole lot of specific (e.g. a small app that demonstrates the behavior) to work with but
there is a [Caveats section](https://www.rabbitmq.com/ttl.html#per-message-ttl-caveats) in the TTL guide that says:

```
When setting per-message TTL expired messages can queue up behind non-expired ones
until the latter are consumed or expired.
```

```
Consumers will not have expired messages delivered to them. Keep in mind
that there can be a natural race condition between message expiration and
consumer delivery, e.g. a message can expire after it was written to the socket
but before it has reached a consumer.
```

```
When retroactively applying a per-message TTL policy, it is recommended
to have consumers online to make sure the messages are discarded quicker.

Given this behaviour of per-message TTL settings on existing queues, when the need
to delete messages to free up resources arises, queue TTL should be used
instead (or queue purging, or queue deletion).
```

In other words, message expiration happens when a message reaches head of the queue.
