### ISSUE TITLE
Queues crash with queue_supervisor_not_found  when starting nodes or recovering

### ISSUE THREAD

**Issue by luos** [rabbitmq/rabbitmq-server#2009]
Hi, 

It's possible to have crashing queues when RabbitMQ starts up, and starting queue 
crashes because the mirror has no running `rabbit_amqqueue_sup_sup`. 
This also can happen during recovery.

This can have multiple effects: 
- A queue is available but the messages are lost
- A queue is properly running with messages intact
- Queue is available without mirrors
- I think sometimes the queue locks up but I was not able to investigate this yet, displays NaN on the gui and no master is available, publishing to the queue says "Message was published but not routed"

Test setup: 
4 docker containers running locally in autoheal mode. 200 queues each with ~100 messages. Stop all containers, restart them at the same time. We saw the same issue in production after autoheal recovery. Mirroring is manual (default), ha=all. 

Scenario 1: Shut down all nodes, start them at the same time.

Scenario 2: One or more nodes are partitioned from the others and restarted because of autoheal.

Explanation: 

When a queue is starting it will try to start the mirrors, however the mirror node is not yet fully online. When a queue is started it calls `start_queue_process`:

https://github.com/rabbitmq/rabbitmq-server/blob/5c80bea709f4c89db3d8652f4a3e7d8421efb76e/src/rabbit_amqqueue_sup_sup.erl#L42-L46

Where `find_for_vhost` is matched to {ok,_} but it can return `queue_supervisor_not_found`:

https://github.com/rabbitmq/rabbitmq-server/blob/5c80bea709f4c89db3d8652f4a3e7d8421efb76e/src/rabbit_amqqueue_sup_sup.erl#L58-L63

It produces these errors: 

```
rmq1.379.autoheal.host | 2019-05-10 12:14:40.655 [error] <0.833.0> Queue <0.963.0> failed to initialise: {{badmatch,{error,{queue_supervisor_not_found,[]}}},[{rabbit_amqqueue_sup_sup,start_queue_process,3,[{file,"src/rabbit_amqqueue_sup_sup.erl"},{line,45}]},{rabbit_mirror_queue_misc,'-add_mirror/3-fun-0-',4,[{file,"src/rabbit_mirror_queue_misc.erl"},{line,250}]},{rabbit_misc,with_exit_handler,2,[{file,"src/rabbit_misc.erl"},{line,506}]},{rabbit_mirror_queue_misc,'-add_mirrors/3-lc$^0/1-0-',3,[{file,"src/rabbit_mirror_queue_misc.erl"},{line,238}]},{rabbit_mirror_queue_misc,add_mirrors,3,[{file,"src/rabbit_mirror_queue_misc.erl"},{line,238}]},{rabbit_mirror_queue_master,init_with_existing_bq,3,[{file,"src/rabbit_mirror_queue_master.erl"},{line,124}]},{rabbit_mirror_queue_master,init,3,[{file,"src/rabbit_mirror_queue_master.erl"},{line,99}]},{rabbit_amqqueue_process,init_it2,3,[{file,"src/rabbit_amqqueue_process.erl"},{line,207}]}]}
```

This causes the queue to crash and fail over. Messages are lost if the failover is to an other node. Sometimes the queue doesn't start and messages can not be published to it.

I confirmed that catching the exception fixes the issue, however I don't think it's the best fix: 

```erlang

case rabbit_vhost_sup_sup:get_vhost_sup(VHost, MirrorNode) of
                        {ok, _} ->
                            case
                                catch rabbit_amqqueue_sup_sup:start_queue_process(
                                       MirrorNode, Q, slave) of
                                       SPid when is_pid(SPid) ->
                                            log_info(QName, "Adding mirror on node ~p: ~p~n", [MirrorNode, SPid]),
                                            rabbit_mirror_queue_slave:go(SPid, SyncMode);
                                       Other ->
                                            log_warning(QName, "Error when trying to start Queue: ~p~n", [Other]),
                                            ok
                                end;
                        {error, Error} ->
                            log_warning(QName,
                                        "Unable to start queue mirror on node '~p'. "
                                        "Target virtual host is not running: ~p~n",
                                        [MirrorNode, Error]),
                            ok
                    end

```

With the fix above seems like all queues start and have the expected number of mirrors and can be published to.

For more logs see this gist: 
crash.log from rmq1: https://gist.github.com/luos/a813b2ee67905d5d18ebfe68c2d45453
docker compose output: https://gist.github.com/luos/c807af65a2df7bf18c94b2a11c480e35

Related: #1607 

https://groups.google.com/forum/#!msg/rabbitmq-users/pQWK71jp1uQ/4_VG2YNWBAAJ

Thanks

**Comment by michaelklishin** [comment]
Thank you for the specifics and spending some time to dive in. We are aware of this scenario, it's a natural distributed race condition. 

[Quorum queues](https://next.rabbitmq.com/quorum-queues.html) do not have this problem due to how Raft leader election works there. We also do not consider the scenario where all nodes are stopped and then started at the same time to be realistic besides initial cluster formation, for which there are [well documented solutions](https://www.rabbitmq.com/cluster-formation.html#initial-formation-race-condition).

You are welcome to submit a PR with your change. We will consider and QA it. Thank you.
