### ISSUE TITLE
rabbitmq-env.bat creates an extra empty folder when RABBITMQ_BASE contains spaces

### ISSUE THREAD

**Issue by hvariant** [rabbitmq/rabbitmq-server#2025]
Steps to reproduce:

1. Download rabbitmq-server-windows-3.7.15.zip and follow the Windows manual install [instructions](https://www.rabbitmq.com/install-windows-manual.html).
2. Set RABBITMQ_BASE to a path with white spaces, for example, "D:\R Q\base\".
3. run `rabbitmq-service.bat install`
4. Notice that an extra folder, 'D:\R', is created.

**Comment by lukebakken** [comment]
This will be addressed by #2068
