### ISSUE TITLE
Worker pool size for queue recovery is not configurable

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-server#2030]
Nodes with many queues (100k+) have been observed to take in excess of 1h to boot. The system appears to be idle, there is little CPU pressure. It was concluded that the worker pool determines the parallelism of queue recovery on node startup and is the culprit for slow node boot.

[The worker pool is currently limited to the number of schedulers](https://github.com/rabbitmq/rabbitmq-common/blob/v3.7.15/src/worker_pool_sup.erl#L35) and cannot be configured. The simplest thing may be to make the worker pool configurable, but I am not sure what side-effects will this have on the rest of the system.

The end-goal is to make systems with many CPUs and many queues quicker to boot.

cc @hairyhum

**Comment by michaelklishin** [comment]
A quick back-of-the-napkin calculation suggests with 100s of thousands of queues recovery definitely can take well over an hour with default worker pool size of 16 or 32 (computed as the number of runtime schedulers by default). We will make it configurable and let the user try a much higher value to compare.
