### ISSUE TITLE
Queue state flow dont return message

### ISSUE THREAD

**Issue by khs123** [rabbitmq/rabbitmq-server#2048]
Hi 
Iam using rabbit with celery to thousands task. I have a queue have 620.000.000 messages in queue
Picture: http://prntscr.com/o8kwjq
But queue state is flow but celery worker not get any message from this queue, i think rabbit block this.
Configure my server rabbit is 16 cores, 124Gb ram,  1.1 T ssd
Queue type is lazy queue
How can i fix this bugs to worker celery get messages normal ?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
That's not enough evidence to conclude anything. The consumer's channel can be limited by [prefetch](https://www.rabbitmq.com/confirms.html#channel-qos-prefetch), there is no evidence of the queue having any consumer and no RabbitMQ version information.
