### ISSUE TITLE
Running RabbitMQ inside container - cgroup (docker) memory limit

### ISSUE THREAD

**Issue by mthenw** [rabbitmq/rabbitmq-server#205]
Hi,

I'm running RabbitMQ cluster on multiple container across few EC2 instances. I use mirrored persistent queue. Under high load I've noticed that one of slave is crushing. It's caused by Docker's OOM killer. 

I guess that this is caused because RabbitMQ is not aware of cgroup memory limits and uses host memory info.

Is there a way to set memory limit through RabbitMQ configuration? Or are there any plans for supporting containers as runtime environment?

**Comment by michaelklishin** [comment]
> Is there a way to set memory limit through RabbitMQ configuration?

[Yes](http://www.rabbitmq.com/memory.html), and it is mentioned in our [production checklist](http://rabbitmq.com/production-checklist.html).

cgroups is an OS-level feature and RabbitMQ can't be aware of it unless the OS can notify us somehow. If there is a way to get such notification, we would consider it.

Please ask questions on the mailing list in the future.

**Comment by robsonpeixoto** [comment]
@michaelklishin Is possible to notify the memory using environment variable ?

**Comment by michaelklishin** [comment]
@robsonpeixoto please post your questions to rabbitmq-users.

**Comment by michaelklishin** [comment]
This was brought up as a somewhat related issue when discussing #1223.
We have file a new issue since there were no objections and the scope seems small enough: #1224.

Also related: #207.

**Comment by michaelklishin** [comment]
#1234 introduces a way to configure total available RAM amount via config file.
