### ISSUE TITLE
RabbitMQ server restart is throwing an error

### ISSUE THREAD

**Issue by Shailesh-Pandey** [rabbitmq/rabbitmq-server#2057]
We are trying to restart RabbitMQ server with below command but we are not successful.
On checking the status, we are getting below error
>>systemctl status rabbitmq-server.service
 
rabbitmq-server.service - RabbitMQ broker
   Loaded: loaded (/lib/systemd/system/rabbitmq-server.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-07-17 12:01:53 UTC; 6s ago
  Process: 28009 ExecStop=/usr/lib/rabbitmq/bin/rabbitmqctl shutdown (code=exited, status=69)
  Process: 27628 ExecStart=/usr/lib/rabbitmq/bin/rabbitmq-server (code=exited, status=1/FAILURE)
 Main PID: 27628 (code=exited, status=1/FAILURE)

Jul 17 12:01:53 blrkecqltyub203 systemd[1]: **Failed** to start RabbitMQ broker.
Jul 17 12:01:53 blrkecqltyub203 systemd[1]: rabbitmq-server.service: Unit entered failed state.
Jul 17 12:01:53 blrkecqltyub203 systemd[1]: rabbitmq-server.service: Failed with result 'exit-code'.

Also "rabbitmqctl add_user test test" is failing with "badargs".

**Comment by lukebakken** [comment]
Hello, and thank you for using RabbitMQ. When you clicked on "New Issue", you were presented with the following text. I'm providing it here so you can read it and follow the directions to post this to the mailing list. Please don't forget to provide important information like what version of RabbitMQ and Erlang you're using, what operating system, and how everything is installed.

----

Thank you for using RabbitMQ.

**STOP NOW AND READ THIS** BEFORE OPENING A NEW ISSUE ON GITHUB

Unless you are CERTAIN you have found a reproducible problem in RabbitMQ or
have a **specific, actionable** suggestion for our team, you must first ask
your question or discuss your suspected issue on the mailing list:

https://groups.google.com/forum/#!forum/rabbitmq-users

Team RabbitMQ does not use GitHub issues for discussions, investigations, root
cause analysis and so on.

Please take the time to read the CONTRIBUTING.md document for instructions on
how to effectively ask a question or report a suspected issue:

https://github.com/rabbitmq/rabbitmq-server/blob/master/CONTRIBUTING.md#github-issues

Following these rules **will save time** for both you and RabbitMQ's maintainers.

Thank you.

**Comment by michaelklishin** [comment]
```
Process: 28009 ExecStop=/usr/lib/rabbitmq/bin/rabbitmqctl shutdown (code=exited, status=69)
Process: 27628 ExecStart=/usr/lib/rabbitmq/bin/rabbitmq-server (code=exited, status=1/FAILURE)
```

suggests that `rabbitmqctl shutdown` exited with code `69` which as of [3.7.16](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.16) will be treated as an [acceptable scenario](https://github.com/rabbitmq/rabbitmq-server-release/pull/104) ([again](https://github.com/rabbitmq/rabbitmq-server-release/issues/51)).
