### ISSUE TITLE
Rabbitmq problem with requeue expired messages

### ISSUE THREAD

**Issue by samakovuluk** [rabbitmq/rabbitmq-server#2058]
I have created two exchanges WORKER and RETRY. And I set DLX and TTL to resend expired messages to original queue, but my messages are disappear in RETRY queue after 10s TTL. Pls help. Can you give me some explanation and solution.

**Comment by lukebakken** [comment]
Thank you for using RabbitMQ.

**STOP NOW AND READ THIS** BEFORE OPENING A NEW ISSUE ON GITHUB

Unless you are CERTAIN you have found a reproducible problem in RabbitMQ or
have a **specific, actionable** suggestion for our team, you must first ask
your question or discuss your suspected issue on the mailing list:

https://groups.google.com/forum/#!forum/rabbitmq-users

Team RabbitMQ does not use GitHub issues for discussions, investigations, root
cause analysis and so on.

Please take the time to read the CONTRIBUTING.md document for instructions on
how to effectively ask a question or report a suspected issue:

https://github.com/rabbitmq/rabbitmq-server/blob/master/CONTRIBUTING.md#github-issues

Following these rules **will save time** for both you and RabbitMQ's maintainers.

Thank you.
