### ISSUE TITLE
RAM limit configuration using absolute values

### ISSUE THREAD

**Issue by mthenw** [rabbitmq/rabbitmq-server#207]
Reporting this based on discussion from mailing list https://groups.google.com/forum/#!topic/rabbitmq-users/ESnCf64vfZ0

Similar to how disk limit can be set, there could be also configuration value for memory limit. This could be helpful when running rabbitmq inside docker container with cgroup memory limitations.

**Comment by michaelklishin** [comment]
Fixed in #378, thank you @dcorbacho!

**Comment by mthenw** [comment]
Awesome, thanks!
