### ISSUE TITLE
rabbit_topic_trie_binding data lost

### ISSUE THREAD

**Issue by gujun4990** [rabbitmq/rabbitmq-server#2079]
- RabbitMQ version: 3.6.16
- RabbitMQ configure cluster, use mirror queues and 3 replicated message by HA policy.
- We encounter a problem that **a queue's binding a topic exchange data** of rabbit_topic_trie_binding  table is lost on every RabbitMQ node, but  rabbit_route table is ok. We have no idea what caused the problem. Maybe RabbitMQ restart to cause.
- Another problem is we can't write the abnormal queue‘s ’binding data to rabbit_topic_trie_binding  table when we send '**queue.bind**' operation to RabbitMQ again. The code below:
`
add(Binding, InnerFun) ->
    binding_action(
      Binding,
      fun (Src, Dst, B) ->
              case rabbit_exchange:validate_binding(Src, B) of
                  ok ->
                      %% this argument is used to check queue exclusivity;
                      %% in general, we want to fail on that in preference to
                      %% anything else
                      case InnerFun(Src, Dst) of
                          ok ->
                              case mnesia:read({rabbit_route, B}) of
                                  []  -> add(Src, Dst, B);
                                  [_] -> fun () -> ok end
                              end;
                          {error, _} = Err ->
                              rabbit_misc:const(Err)
                      end;
                  {error, _} = Err ->
                      rabbit_misc:const(Err)
              end
      end, fun not_found_or_absent_errs/1).`
- When binding again, the rabbit_binding:add/2 just read rabbit_route binding data. So when the first prolem occurs, the binding again operation have no effect. 
- So I have no idea whether the problem is a bug, and I want to know the relationship between rabbit_route  and rabbit_topic_trie_binding table when using topic exchange. Please help me. Thank you.

**Comment by michaelklishin** [comment]
RabbitMQ 3.6.x has been out of support for [15 months](https://www.rabbitmq.com/changelog.html).

**Comment by michaelklishin** [comment]
See https://github.com/rabbitmq/rabbitmq-server/issues/1873 and the PRs and issues linked there (such as #1878, #1879, #1884). We haven't seen reports of route tables inconsistencies since then, so please [upgrade](https://www.rabbitmq.com/upgrade.html) to `3.7.17` before you conduct any more tests.

Unless you have a specific set of steps that reproduces #1873 with `3.7.17`, please direct all further questions to the mailing list.

**Comment by gujun4990** [comment]
Thank you for your reply. I will have a look the discussions.

**Comment by gujun4990** [comment]
> See #1873 and the PRs and issues linked there (such as #1878, #1879, #1884). We haven't seen reports of route tables inconsistencies since then, so please [upgrade](https://www.rabbitmq.com/upgrade.html) to `3.7.17` before you conduct any more tests.
> 
> Unless you have a specific set of steps that reproduces #1873 with `3.7.17`, please direct all further questions to the mailing list.

As our RabbitMQ cluster is containerized. so I plan to pull rabbitmq:3.7.17-management-alpine image from https://hub.docker.com/_/rabbitmq?tab=tags to produce the problem. I don't know the code you mentioned is merged.

**Comment by michaelklishin** [comment]
Milestones on issues and [release notes](https://www.rabbitmq.com/changelog.html) know. I wouldn't ask to use `3.7.17` if they weren't.
