### ISSUE TITLE
Backport rabbitmq/rabbitmq-server#2096

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#2099]
This separate issue is so that we can track the integration test and backporting part of https://github.com/rabbitmq/rabbitmq-server/pull/2096.

**Comment by lukebakken** [comment]
Fixed by https://github.com/rabbitmq/rabbitmq-server/commit/c4b9cbf46c221345a353916f01673fbc9b4c88b8
