### ISSUE TITLE
Emit events for queue.purge

### ISSUE THREAD

**Issue by sathishbabu96** [rabbitmq/rabbitmq-server#2102]
Is it possible to generate a new event like `queue.purged` whenever a queue is purged by the user?. The event can include information like who purged the queue, at what time, number of messages purged, vhost name of the queue.

**Comment by michaelklishin** [comment]
Adding a new event is straightforward and in this case, the number of purged messages in ready state [is already known](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_amqqueue.erl#L1244).

Feel free to contribute this small feature. Examples of emitted events can be found by searching for  `rabbit_event` call sites.

**Comment by sathishbabu96** [comment]
Hello Michael, I am interested in contributing this enhancement but I don't understand "can be found by searching `rabbit_event call` sites".

**Comment by michaelklishin** [comment]
Here's [where we emit `queue.delete`](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_amqqueue.erl#L1520). Doing something very similar for `queue.purge` (the `purge/1` function in the same module) is all it basically takes :)

**Comment by sathishbabu96** [comment]
Alright, I will do the changes and raise a pull request.

**Comment by michaelklishin** [comment]
IIRC this was done.
