### ISSUE TITLE
Windows service consumes 100% CPU when .conf file provided

### ISSUE THREAD

**Issue by Infactum** [rabbitmq/rabbitmq-server#2111]
Steps to reproduce:
- Get latest 3.7.18 release (also reproducible on 3.7.x)
- Install without specifying "service" option
- Create rabbit base dir (`C:\RabbitBase` for example) and put any blank or non-blank `rabbitmq.conf` file there
- Run RabbitMQ Command Prompt (sbin dir) with following commands
```
C:\Program Files\RabbitMQ Server\rabbitmq_server-3.7.18\sbin>set RABBITMQ_BASE=C:\RabbitBase

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.7.18\sbin>rabbitmq-service.bat install
C:\Program Files\erl10.4\erts-10.4\bin\erlsrv: Service RabbitMQ added to system.
Скопировано файлов:         1.

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.7.18\sbin>rabbitmq-service.bat start
Служба "RabbitMQ" запускается.
Служба "RabbitMQ" успешно запущена.
```
- erl.exe process will consume 100% CPU

Generated RabbitMQ service argument string from `HKEY_LOCAL_MACHINE\SOFTWARE\Ericsson\Erlang\ErlSrv\1.1\RabbitMQ`:
```
 -pa "C:/Program Files/RabbitMQ Server/rabbitmq_server-3.7.18/ebin" -boot start_sasl -s "rabbit" boot  -conf "C:/RabbitBase/rabbitmq.conf"                                       -conf_dir "C:/RabbitBase/config"                                       -conf_script_dir "C:/Program Files/RabbitMQ Server/rabbitmq_server-3.7.18/sbin/"                                       -conf_schema_dir "C:/RabbitBase/schema"                                       -conf_advanced "C:/RabbitBase/advanced.config" +W w +A "64" +MBas ageffcbf +MHas ageffcbf +MBlmbcs 512 +MHlmbcs 512 +MMmcs 30 +P 1048576 +t 5000000 +stbt db +zdbbl 128000  -kernel inet_default_connect_options "[{nodelay,true}]"  -sasl errlog_type error -sasl sasl_error_logger false -rabbit lager_log_root "\"C:/RabbitBase/log\"" -rabbit lager_default_file "\"C:/RabbitBase/log/rabbit@DESKTOP-IBH4D5V.log\"" -rabbit lager_upgrade_file "\"C:/RabbitBase/log/rabbit@DESKTOP-IBH4D5V_upgrade.log\"" -rabbit feature_flags_file "\"C:/RabbitBase/db/rabbit@DESKTOP-IBH4D5V-feature_flags\"" -rabbit enabled_plugins_file "\"C:/RabbitBase/enabled_plugins\"" -rabbit plugins_dir "\"C:/Program Files/RabbitMQ Server/rabbitmq_server-3.7.18/plugins\"" -rabbit plugins_expand_dir "\"C:/RabbitBase/db/rabbit@DESKTOP-IBH4D5V-plugins-expand\"" -rabbit windows_service_config "\"C:/RabbitBase/rabbitmq.conf\"" -mnesia dir "\"C:/RabbitBase/db/rabbit@DESKTOP-IBH4D5V-mnesia\"" -os_mon start_cpu_sup false -os_mon start_disksup false -os_mon start_memsup false  -kernel inet_dist_listen_min 25672 -kernel inet_dist_listen_max 25672 
```

**Comment by allustin** [comment]
https://github.com/rabbitmq/rabbitmq-server/blob/5dad9a1b9e47c9dcf45032910ab81281046716be/src/rabbit_config.erl#L220 is it helps ?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
The only way to find out more is to instrument the process. Sorting top processes by reductions using [rabbitmq-top](https://www.rabbitmq.com/memory-use.html#breakdown-top) and [`rabbitmq-diagnostics runtime_thread_stats`](https://www.rabbitmq.com/rabbitmq-diagnostics.8.html) are two ways to obtain relevant data using RabbitMQ-specific tools.

Please collect that data as well as `rabbitmqctl report` output and start a mailing list thread.

**Comment by michaelklishin** [comment]
I don't see how https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_config.erl#L220 would be relevant. The function is not recursive and I don't see how it could go into a loop consuming 100% of the CPU.

We strongly prefer to not guess on this team. We need to collect relevant data using RabbitMQ and OS tools about what consumes the CPU cycles.

**Comment by Infactum** [comment]
FYI  
https://groups.google.com/forum/#!topic/rabbitmq-users/vlnRBYFp5is
