### ISSUE TITLE
Should we increment publish counters for non-master queues?

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-server#2115]
After #1706 was merged, we started counting all queue mirrors & replicas in the message publish rates. Even though this does not feel like a bug, it differs from what we report in 3.7.x. If this is intended behaviour, we should add it to the 3.8 release notes.

To better illustrate the current 3.8.0-rc.2 behaviour, with 100 messages / s published into a single queue with 2 mirrors (1 master & 1 mirror), the **Exchange - Message rate out** shows 200 messages / s published. The queue itself also shows **Publish 200/s**. In other words, the `queue msg ingress rate = msg ingress rate x number of mirrors`. A picture to illustrate this:

![3 7 18-vs-3 8 0-rc 2-post-route-publish-rate](https://user-images.githubusercontent.com/3342/65448051-d03d0580-de2f-11e9-8994-a23b4afd9109.png)

This is the specific line which I believe is responsible for the change in behaviour: https://github.com/rabbitmq/rabbitmq-server/pull/1706/files#diff-98224c82bfd7f4172da6a5adff2c42b0R1969-R1970

I was going to confirm first thing tomorrow whether the same is happening for quorum queues. If the source of this is in the line that I linked to above, then I expect the same behaviour in QQs as well.

Not sure if it would help, but I was thinking to try out various 3.8 beta releases and confirm when this was first introduced.

cc @kjnilsson @dcorbacho @michaelklishin

**Comment by lukebakken** [comment]
> it differs from what we report in 3.7.x

Feels like a bug to me ... my 2¢

**Comment by gerhard** [comment]
Fix confirmed:

BEFORE FIX:
![before-rabbitmq-2119](https://user-images.githubusercontent.com/3342/65592515-a0ecdc80-df86-11e9-9578-9093664c1717.png)

AFTER FIX:
![after-rabbitmq-2119](https://user-images.githubusercontent.com/3342/65592525-a518fa00-df86-11e9-9e0a-89a93b600272.png)
