### ISSUE TITLE
rabbitmq shutdown_error

### ISSUE THREAD

**Issue by ighack** [rabbitmq/rabbitmq-server#2124]
I have 6 nodes. 

One of them sometime shutdown_error,I need reboot it.

in my log 
```
2019-09-28 12:50:42.218 [info] <0.32274.6978> Connection <0.32274.6978> (192.168.0.1:32953 -> 192.168.0.231:5672) has a client-provided name: rabbitConnectionFactory#333efb51:0
2019-09-28 12:50:42.223 [info] <0.32274.6978> connection <0.32274.6978> (192.168.0.1:32953 -> 192.168.0.231:5672 - rabbitConnectionFactory#333efb51:0): user 'CloudConfig' authent
icated and granted access to vhost 'CloudConfig'
2019-09-28 16:11:44.399 [warning] <0.14583.6922> closing AMQP connection <0.14583.6922> (192.168.0.1:25777 -> 192.168.0.231:5672 - rabbitConnectionFactory#333efb51:0, vhost: 'Clo
udConfig', user: 'CloudConfig'):
client unexpectedly closed TCP connection
2019-09-28 17:34:43.331 [error] <0.10276.6984> Supervisor {<0.10276.6984>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(direct, <0.10248.69
84>, <<"<rabbit@busappser7.3.10248.6984>">>) at undefined exit with reason noproc in context shutdown_error
2019-09-29 04:31:43.542 [error] <0.9307.6992> Supervisor {<0.9307.6992>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(direct, <0.10294.6992
>, <<"<rabbit@busappser7.3.10294.6992>">>) at undefined exit with reason shutdown in context shutdown_error
```

crash.log
```
2019-09-28 04:37:43 =SUPERVISOR REPORT====
     Supervisor: {<0.22378.6971>,amqp_channel_sup_sup}
     Context:    shutdown_error
     Reason:     noproc
     Offender:   [{nb_children,1},{name,channel_sup},{mfargs,{amqp_channel_sup,start_link,[direct,<0.22456.6971>,<<"<rabbit@busappser7.3.22456.6971>">>]}},{restart_type,temporary
},{shutdown,infinity},{child_type,supervisor}]
2019-09-28 08:04:43 =SUPERVISOR REPORT====
     Supervisor: {<0.17679.6974>,amqp_channel_sup_sup}
     Context:    shutdown_error
     Reason:     shutdown
     Offender:   [{nb_children,1},{name,channel_sup},{mfargs,{amqp_channel_sup,start_link,[direct,<0.17524.6974>,<<"<rabbit@busappser7.3.17524.6974>">>]}},{restart_type,temporary
},{shutdown,infinity},{child_type,supervisor}]
2019-09-28 10:13:44 =SUPERVISOR REPORT====
     Supervisor: {<0.11666.6976>,amqp_channel_sup_sup}
     Context:    shutdown_error
     Reason:     noproc
     Offender:   [{nb_children,1},{name,channel_sup},{mfargs,{amqp_channel_sup,start_link,[direct,<0.11410.6976>,<<"<rabbit@busappser7.3.11410.6976>">>]}},{restart_type,temporary
},{shutdown,infinity},{child_type,supervisor}]
2019-09-28 17:34:43 =SUPERVISOR REPORT====
     Supervisor: {<0.10276.6984>,amqp_channel_sup_sup}
     Context:    shutdown_error
     Reason:     noproc
     Offender:   [{nb_children,1},{name,channel_sup},{mfargs,{amqp_channel_sup,start_link,[direct,<0.10248.6984>,<<"<rabbit@busappser7.3.10248.6984>">>]}},{restart_type,temporary
},{shutdown,infinity},{child_type,supervisor}]
```

rabbitmq:3.7.8
Erlang:21.1.1
centos:7.2

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
`amqp_channel_sup_sup` is a supervisor that supervises channels of a connection. One of its children, `amqp_channel_sup`, which represents a  group of processes used by a single channel, has terminated with an exception, one of its child processes wasn't there to be shut down. There is not enough information to suggest why. Most likely the process hasn't fully been started at the time of connection process shutdown. Closing a connection force closes all of its channels, so there
is a natural race condition.

The reason why I think this is plausible is the warning above

> client unexpectedly closed TCP connection

which is documented in detail [in a dedicated section](https://www.rabbitmq.com/logging.html#logged-events).

`3.7.8` is 12 months and 10 patch release behind the [latest 3.7.x release](https://www.rabbitmq.com/changelog.html). Consider [upgrading](https://www.rabbitmq.com/upgrade.html)

**Comment by harshats9** [comment]
Hello,

Any updates on this issue. even we are faing the same

**Comment by harshats9** [comment]
> I have 6 nodes.
> 
> One of them sometime shutdown_error,I need reboot it.
> 
> in my log
> 
> ```
> 2019-09-28 12:50:42.218 [info] <0.32274.6978> Connection <0.32274.6978> (192.168.0.1:32953 -> 192.168.0.231:5672) has a client-provided name: rabbitConnectionFactory#333efb51:0
> 2019-09-28 12:50:42.223 [info] <0.32274.6978> connection <0.32274.6978> (192.168.0.1:32953 -> 192.168.0.231:5672 - rabbitConnectionFactory#333efb51:0): user 'CloudConfig' authent
> icated and granted access to vhost 'CloudConfig'
> 2019-09-28 16:11:44.399 [warning] <0.14583.6922> closing AMQP connection <0.14583.6922> (192.168.0.1:25777 -> 192.168.0.231:5672 - rabbitConnectionFactory#333efb51:0, vhost: 'Clo
> udConfig', user: 'CloudConfig'):
> client unexpectedly closed TCP connection
> 2019-09-28 17:34:43.331 [error] <0.10276.6984> Supervisor {<0.10276.6984>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(direct, <0.10248.69
> 84>, <<"<rabbit@busappser7.3.10248.6984>">>) at undefined exit with reason noproc in context shutdown_error
> 2019-09-29 04:31:43.542 [error] <0.9307.6992> Supervisor {<0.9307.6992>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(direct, <0.10294.6992
> >, <<"<rabbit@busappser7.3.10294.6992>">>) at undefined exit with reason shutdown in context shutdown_error
> ```
> 
> crash.log
> 
> ```
> 2019-09-28 04:37:43 =SUPERVISOR REPORT====
>      Supervisor: {<0.22378.6971>,amqp_channel_sup_sup}
>      Context:    shutdown_error
>      Reason:     noproc
>      Offender:   [{nb_children,1},{name,channel_sup},{mfargs,{amqp_channel_sup,start_link,[direct,<0.22456.6971>,<<"<rabbit@busappser7.3.22456.6971>">>]}},{restart_type,temporary
> },{shutdown,infinity},{child_type,supervisor}]
> 2019-09-28 08:04:43 =SUPERVISOR REPORT====
>      Supervisor: {<0.17679.6974>,amqp_channel_sup_sup}
>      Context:    shutdown_error
>      Reason:     shutdown
>      Offender:   [{nb_children,1},{name,channel_sup},{mfargs,{amqp_channel_sup,start_link,[direct,<0.17524.6974>,<<"<rabbit@busappser7.3.17524.6974>">>]}},{restart_type,temporary
> },{shutdown,infinity},{child_type,supervisor}]
> 2019-09-28 10:13:44 =SUPERVISOR REPORT====
>      Supervisor: {<0.11666.6976>,amqp_channel_sup_sup}
>      Context:    shutdown_error
>      Reason:     noproc
>      Offender:   [{nb_children,1},{name,channel_sup},{mfargs,{amqp_channel_sup,start_link,[direct,<0.11410.6976>,<<"<rabbit@busappser7.3.11410.6976>">>]}},{restart_type,temporary
> },{shutdown,infinity},{child_type,supervisor}]
> 2019-09-28 17:34:43 =SUPERVISOR REPORT====
>      Supervisor: {<0.10276.6984>,amqp_channel_sup_sup}
>      Context:    shutdown_error
>      Reason:     noproc
>      Offender:   [{nb_children,1},{name,channel_sup},{mfargs,{amqp_channel_sup,start_link,[direct,<0.10248.6984>,<<"<rabbit@busappser7.3.10248.6984>">>]}},{restart_type,temporary
> },{shutdown,infinity},{child_type,supervisor}]
> ```
> 
> rabbitmq:3.7.8 Erlang:21.1.1 centos:7.2

HI, any update on this?
