### ISSUE TITLE
Rolling cluster upgrade to 3.7.17+ fails if RabbitMQ code files are deployed to currently running nodes early

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#2132]
[Some users reported](https://groups.google.com/d/msg/rabbitmq-users/5ADWOmuDTSg/z_u2Pe5nBAAJ) that the Feature flags subsystem introduced in RabbitMQ 3.7.17 prevented the upgrade of their cluster.

The root cause appears to be that 3.7.17+ packages are deployed everywhere, then nodes are restarted one at a time. For nodes which are not yet restarted, this causes the new `rabbit_feature_flags` module to be loaded in a pre-feature-flags running node (so a version older than 3.7.17). This module fails to respond to the restarted remote node queries because the environment is unexpected (an old node) and the restarting node aborts the start.

**Comment by michaelklishin** [comment]
Backported to `v3.8.x` and `v3.7.x`.

**Comment by dumbbell** [comment]
Reopening because the patch is not the final version.
