### ISSUE TITLE
What should happen when rabbitmq.conf and advanced.config settings overlap?

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#2157]
[`rabbitmq-users` message](https://groups.google.com/d/msg/rabbitmq-users/gCR9jch0df4/K-yF5PhbAQAJ)

To reproduce, use the following configs:

`rabbitmq.conf`:

```
management.tcp.port = 15672
management.tcp.ip = ::
```

`advanced.config`:

```  
[
    {rabbitmq_management, [
        {listener, [
            {port, 15672}
        ]}
    ]}
].
```

The `advanced.config` configuration will take precedence. We could merge the settings, warn the user, do something, etc. The current behavior can be confusing.

**Comment by michaelklishin** [comment]
I'm not sure what would be the least confusing behavior here. If you configure the same thing in two (different) files, I don't think that's necessarily intentional.

**Comment by michaelklishin** [comment]
@dumbbell, @acogoluegnes and I agree that the current behavior makes sense.

**Comment by lukebakken** [comment]
I will make sure the docs are clear, thanks.
