### ISSUE TITLE
MQTT, STOMP performance degradation due to sync call to the connection process

### ISSUE THREAD

**Issue by velimir** [rabbitmq/rabbitmq-server#2168]
Hi,

MQTT Plugin (as well as STOMP and others) uses direct channels to communicate with rabbit.

Authorisation introduces synchronous call to the connection process for every message published on a channel to obtain amqp parameters used to connect to the broker (`rabbit_amqp_connection:amqp_params/2`): [here](https://github.com/rabbitmq/rabbitmq-server/blob/0991bbf81cbdb04e0ea91d019a82c70d96e90213/src/rabbit_channel.erl#L1334) and [here](https://github.com/rabbitmq/rabbitmq-server/blob/0991bbf81cbdb04e0ea91d019a82c70d96e90213/src/rabbit_channel.erl#L1337).

Original performance:

<img width="1327" alt="Screenshot 2019-11-19 at 16 06 44" src="https://user-images.githubusercontent.com/709160/69230733-be51b780-0b7f-11ea-8e4a-580da0c5dd3f.png">

Performance w/o sync call:

<img width="1334" alt="Screenshot 2019-11-19 at 16 41 47" src="https://user-images.githubusercontent.com/709160/69230771-c7428900-0b7f-11ea-8e0a-8a2c9b5a452f.png">

Would it be feasible to provide connection parameters (variable map) as a required parameter for the `rabbit_channel` to void the call to the connection process?
Would you be able advise on why it can't be done w/o call to the connection process?

**Comment by michaelklishin** [comment]
It can be done w/o a call to the connection process. The sync call has bitten us elsewhere (e.g. #1886) and something we should replace. It sounds doable but this API area is sensitive for cross-version Federation.

**Comment by michaelklishin** [comment]
PRs contributed by @velimir so far:

 * https://github.com/rabbitmq/rabbitmq-server/pull/2169
 * https://github.com/rabbitmq/rabbitmq-erlang-client/pull/127 (this is the potentially breaking part for Federation)
 * https://github.com/rabbitmq/rabbitmq-management/pull/755

**Comment by velimir** [comment]
@michaelklishin thanks for looking into this. That's great. I was afraid that there's something that I'm missing and the call is unavoidable.

 I should be able to add tests and fix broken ones later next week.

**Comment by michaelklishin** [comment]
I tested Federation with 3.6 and 3.7 upstreams as well as 3.6 and 3.7 downstreams. No issues with exchange federation which uses direct client.

I also did some basic benchmarking. My results are less impressive than those on the screenshot but nonetheless clock in at 14 to 32% improvement in throughput (median, 75th percentile, 99th percentile).

**Comment by velimir** [comment]
@michaelklishin Thanks for merging this. Any chance this will be available on 3.7.X?

**Comment by michaelklishin** [comment]
Channel state in `3.8` is quite different from `3.7`. Feel free to take a look at submitting the same changes against `3.7` if you need them there.

**Comment by michaelklishin** [comment]
FTR this was backported and also shipped in`v3.7.23`. Thanks again for contributing @velimir.
