### ISSUE TITLE
Exchange with amq. prefix can be created via definitions import

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#2170]
To reproduce, import the following definitions file:

[defs.json.txt](https://github.com/rabbitmq/rabbitmq-server/files/3876381/defs.json.txt)

The `amq.foobar` exchange will be created and it can't be removed.

Resolution: do not allow exchanges to be created with `amq` as the prefix.

[169904715]

**Comment by michaelklishin** [comment]
Filtering them out as well as the default exchange before import would do.
