### ISSUE TITLE
Import (some?) definitions after enabling plugins

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#2177]
See https://github.com/rabbitmq/rabbitmq-shovel/issues/13 for background.

Definition import was moved into the core but we still perform it before enabling plugins. I wonder if this should be the other way around. Admittedly there's a chicken-and-egg problem here either way: plugins can potentially depend on definitions (e.g. policies and parameters) and definitions can depend on plugins.

We can introduce a separate "delayed import" setting for definitions that depend on plugins being enabled.

**Comment by lukebakken** [comment]
@michaelklishin it seems that this issue is related - https://github.com/rabbitmq/rabbitmq-sharding/issues/39

**Comment by michaelklishin** [comment]
Addressed in https://github.com/rabbitmq/rabbitmq-server/issues/2384.

**Comment by michaelklishin** [comment]
Addressed in https://github.com/rabbitmq/rabbitmq-server/issues/2384 which will ship in `3.8.6`. Those on earlier versions can always [import definitions after node startup](https://www.rabbitmq.com/definitions.html).

**Comment by ebuildy** [comment]
Do you know when the bug appears? its working fine with 3.7.8

**Comment by lukebakken** [comment]
RabbitMQ version 3.8.4.

**Comment by michaelklishin** [comment]
It's not new in `3.8.4` but it affects more plugin types as of `3.8.4` because boot code paths have been substantially refactored.
