### ISSUE TITLE
I can create multiple queues with same name which shouldn't be possible

### ISSUE THREAD

**Issue by ozdotnet** [rabbitmq/rabbitmq-server#2215]
RabbitMQ server: 3.7.14
Erlang: 21.3
OS: Windows 10 Enterprise
RabbitMQ plugins: Federation, Shovel

As far as I know queuenames must be unique in a (v)host. I'm able to create multiple queues with exact same name.

How to reproduce:

1. Open `Management UI`
2. Go to `Queues `tab
3. Under section `Add a new queue`, give a queuename: `test_queue`
4. Click on `Add queue`
5. A queue with name `test_queue` is created
6. Repeat step `3.` until `5.` but add spaces behind the queuename, for example: `test_queue[   ]` (remove brackets when adding)
7. Exact same queuename is created.

This is a bug I think?

**Comment by michaelklishin** [comment]
`queue` and `queue    ` are different queue names. Management UI highlights trailing whitespace, that's all.

**Comment by michaelklishin** [comment]
To be specific: *modern versions* will highlight trailing whitespace. Without the highlighting the names will look identical in management UI because, well, whitespaces are not easy to spot on a Web page or in `rabbitmqctl list_queues` output. But they are nonetheless different queue names.
