### ISSUE TITLE
Partially concurrent definition import

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#2224]
Importing a definition file can take a while with tens or hundreds of thousands of entities. For each category, objects are imported sequentially. In some cases, it should be safe to import them
concurrently using a small work pool of fixed configurable size. This could make a significant difference at the cost of much higher CPU utilization.

Default work pool size can be the number of available schedulers.

**Comment by lukebakken** [comment]
Great idea 👍

**Comment by KushagraBindal** [comment]
Hi Luke/Michael,

Was just looking at the thread on community. I can also give it a try and may be it will solve my issue as well, can you please assist me what I need to do to try this.

Secondly, please let me know the approach that I should taken into my consideration for this test.

Regards
Kushagra

**Comment by michaelklishin** [comment]
We don't even have a PR to QA just yet but once we have it we will let you know. We are considering adding some metrics and logging around definition import time (I have just discussed this with @gerhard for an unrelated feature), which would help your case as well.

**Comment by KushagraBindal** [comment]
Thanks Michael. Meanwhile I am studying https://www.rabbitmq.com/monitoring.html. Maybe I will be able to apply some and which might give you better insight of the problem that system is having. 

If you have some suggestion around the same (plugins/tools) that I can give a try then please suggest and I will provide the outcome. May be then we can better conclude the things.

Regards
Kushagra
