### ISSUE TITLE
Add Error Logging When Low on Storage

### ISSUE THREAD

**Issue by gchallen** [rabbitmq/rabbitmq-server#2225]
I recently ran into a very frustrating problem when using the [Bitnami RabbitMQ container](https://hub.docker.com/r/bitnami/rabbitmq/) as part of a multi-container service.

During testing using a set of containers started by Docker Compose, periodically everything would just completely hang. I eventually tracked this back to the RabbitMQ Java client hanging on a simple send operation. No problems were visible in the logs produced by the RabbitMQ container, despite the fact that log verbosity seemed reasonably high—client connections and disconnections were being logged, for example.

Obviously my title ruined the suspense, but the problem was that the RabbitMQ container was low on storage and Rabbit had decided to refuse to accept new messages. To add to the confusion, the queue was configured as not persistent, although of course I understand that Rabbit may need storage for other purposes during normal operation. To further add to the confusion, my machine is _not_ low on storage—but the Docker daemon was low given how much it had been configured to use. (The default Bitnami Docker container also needs a fair amount of storage: equal to the amount of RAM.)

Just to spare others some pain and confusion it would seem reasonable for RabbitMQ to log a warning when it refuses a message because storage is low. Perhaps it would also be good default behavior to actually fail here, rather than just hang. I mean, does RabbitMQ really expect storage to suddenly become available while waiting? Would it even complete the request in the very unlikely case that this did in fact happen?

Thanks for all of your hard work on this excellent service. Hopefully my suggestion above would just make RabbitMQ a bit more usable for the next newbie...

**Comment by michaelklishin** [comment]
A mechanism for that has been around for close to a decade:

 * [Alarms](https://www.rabbitmq.com/alarms.html)
 * [Free disk space alarms](https://www.rabbitmq.com/disk-alarms.html)
 * [Configurable](https://github.com/rabbitmq/rabbitmq-server/blob/v3.8.x/docs/rabbitmq.conf.example#L363) minimum amount of free disk space that would trigger an alarm

An alarm blocks all publishers and produces very visible, multi-line log messages. If a node is so low on storage that it effectively cannot initialize its own data store, it would likely fail to start. In any case, such environment would not pass the [production check list](https://www.rabbitmq.com/production-checklist.html#resource-limits-disk-space).
