### ISSUE TITLE
pause_minority experiences race condition that takes down entire cluster

### ISSUE THREAD

**Issue by eherot** [rabbitmq/rabbitmq-server#2230]
**RabbitMQ Version**: 3.7.14

**Environment**: 5 Rabbit nodes running on Kubernetes v1.12.0 w/Flannel CNI

**What I did:**
One RabbitMQ pod (rabbitmq-3) was killed (manually, by me).

**What resulted:**
Kubernetes quickly (within a few seconds) rescheduled the pod on another node. Rather than the cluster noticing the loss of a single member and re-mirroring queues elsewhere, the following entries were logged:
```
Jan 31, 2020 @ 19:19:34.308 rabbitmq-1 * We saw DOWN from rabbit@rabbitmq-3.rabbitmq.default.svc.cluster.local
Jan 31, 2020 @ 19:19:34.308 rabbitmq-1 * We can still see rabbit@rabbitmq-2.rabbitmq.default.svc.cluster.local which can see rabbit@rabbitmq-3.rabbitmq.default.svc.cluster.local
Jan 31, 2020 @ 19:19:34.325 rabbitmq-1 * We saw DOWN from rabbit@rabbitmq-3.rabbitmq.default.svc.cluster.local
Jan 31, 2020 @ 19:19:34.325 rabbitmq-1 * We can still see rabbit@rabbitmq-0.rabbitmq.default.svc.cluster.local which can see rabbit@rabbitmq-3.rabbitmq.default.svc.cluster.local
Jan 31, 2020 @ 19:19:34.326 rabbitmq-2 * We saw DOWN from rabbit@rabbitmq-3.rabbitmq.default.svc.cluster.local
Jan 31, 2020 @ 19:19:34.326 rabbitmq-2 * We can still see rabbit@rabbitmq-1.rabbitmq.default.svc.cluster.local which can see rabbit@rabbitmq-3.rabbitmq.default.svc.cluster.local
Jan 31, 2020 @ 19:19:34.326 rabbitmq-1 * We saw DOWN from rabbit@rabbitmq-3.rabbitmq.default.svc.cluster.local
Jan 31, 2020 @ 19:19:34.326 rabbitmq-1 * We can still see rabbit@rabbitmq-4.rabbitmq.default.svc.cluster.local which can see rabbit@rabbitmq-3.rabbitmq.default.svc.cluster.local
Jan 31, 2020 @ 19:19:34.329 rabbitmq-4 * We saw DOWN from rabbit@rabbitmq-3.rabbitmq.default.svc.cluster.local
Jan 31, 2020 @ 19:19:34.329 rabbitmq-4 * We can still see rabbit@rabbitmq-1.rabbitmq.default.svc.cluster.local which can see rabbit@rabbitmq-3.rabbitmq.default.svc.cluster.local
Jan 31, 2020 @ 19:19:34.332 rabbitmq-0 * We saw DOWN from rabbit@rabbitmq-3.rabbitmq.default.svc.cluster.local
Jan 31, 2020 @ 19:19:34.332 rabbitmq-0 * We can still see rabbit@rabbitmq-1.rabbitmq.default.svc.cluster.local which can see rabbit@rabbitmq-3.rabbitmq.default.svc.cluster.local
```
(Although I omitted it from the above for clarity, each node also printed `pause_minority mode enabled` and `We will therefore pause until the *entire* cluster recovers`)

This indicates to me that there may be a race condition in the logic for determining which nodes are up and which nodes are down (notice the inconsistent reports in the entry above).

This looks like a bug to me, but I'm also wondering if there are network configuration tweaks (e.g. `net_ticktime`) that might prevent this from occurring in the future.

Note that the resulting chaos of nodes shutting down also caused every node to crash, taking down the management UI with it (I'll be drafting a second issue for that unless one already exists--I haven't looked yet).

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with. I'm afraid we cannot suggest much with the amount of information available here and your environment is 9 patch releases behind in the 3.7.x versions alone.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.
