### ISSUE TITLE
Cannot enable debug logging for console output

### ISSUE THREAD

**Issue by mitchellrj** [rabbitmq/rabbitmq-server#2240]
The configuration value of `log.file.level` does not impact the configured log level of console output. Setting the environment variable `RABBITMQ_LOGS` to `-` overrides that value and forces log output to be `info` level only.

In previous versions it was possible using the now deprecated `log_levels` setting, like so:
```
[{rabbit,[{log_levels,[{global,debug}]}]}].
```
But now of course RabbitMQ will not start with this configuration.

Relevant code:
https://github.com/rabbitmq/rabbitmq-server/blob/e4fdc7d6c657752b6e0df8f73d4c14159c292065/apps/rabbitmq_prelaunch/src/rabbit_prelaunch_early_logging.erl#L32

**Comment by lukebakken** [comment]
Hello and thanks for using RabbitMQ

Please always start discussions about RabbitMQ by stating what version you are using, the Erlang version, and on what operating system.

> The configuration value of log.file.level does not impact the configured log level of console output

It never has, as far as I know.

> Setting the environment variable RABBITMQ_LOGS to - overrides that value and forces log output to be info level only.

Yes, this is the expected behavior.

> Cannot enable debug logging for console output

You can always use the configuration file to enable debug console output.

What I'm _guessing_ that you're getting at with this issue report is that using the latest RabbitMQ code (`master` / 3.8.3) there is no way to enable debug console output using an environment variable. Is this correct?

**Comment by lukebakken** [comment]
Enabling debug output to the console via an environment variable will not be supported in 3.8.X. Please use a configuration file (cc @dumbbell)

**Comment by dumbbell** [comment]
@mitchellrj: `log.file.level` only changes the log level of the file output. To change the same parameter for the console, you can set `log.console.level`:

```ini
log.console.level = debug
```
Our documentation probably lacks that bit of information... I just tested that with RabbitMQ 3.8.2 to be sure and it worked. Here is the output of the terminal:

```text
2020-02-14 10:07:56.899 [debug] <0.304.0> segment_writer: deleting wal file: 00000003.wal
2020-02-14 10:07:56.899 [debug] <0.306.0> wal: opening new file "00000004.wal"
2020-02-14 10:07:56.899 [info] <0.315.0>
 Starting RabbitMQ 3.8.2 on Erlang 21.3.8.13
 Copyright (c) 2007-2019 Pivotal Software, Inc.
 Licensed under the MPL 1.1. Website: https://rabbitmq.com
(...)
2020-02-14 10:07:56.968 [debug] <0.315.0> Applying MFA: M = rabbit_nodes, F = boot, A = []
2020-02-14 10:07:56.968 [info] <0.315.0> Running boot step direct_client defined by app rabbit
2020-02-14 10:07:56.968 [debug] <0.315.0> Applying MFA: M = rabbit_direct, F = boot, A = []
2020-02-14 10:07:57.064 [info] <0.8.0> Server startup complete; 0 plugins started.
 completed with 0 plugins.
```

I would also like to correct the following message:

> Enabling debug output to the console via an environment variable will not be supported in 3.8.X and future versions.

In fact, it is already supported in `master` :-) A user can now set `$RABBITMQ_LOG=debug` to set the log level to debug, whatever the output is. We may backport this to 3.8.x, but it is part of a larger patch (see #2180).

**Comment by michaelklishin** [comment]
Our docs do mention `log.console.level`: [Logging to Console](https://www.rabbitmq.com/logging.html#logging-to-console).
