### ISSUE TITLE
RabbitMQ Docker fails to start after power loss

### ISSUE THREAD

**Issue by andi00** [rabbitmq/rabbitmq-server#2249]
Docker - rabbitmq:3.8.x-management

A power loss at service start can lead to a corrupt service which can't start anymore.
It looks like the root cause is the wal-File in the Folder /mnesia/'nodeId'/quorom/'nodeId'/ dictionary. 
If this file exist but is empty the service can't start.
If this file is missing or have a content there is no problem. 
Maybe a file check can be integrated.

Actually currently we don't use the quorom queues.
[log.zip](https://github.com/rabbitmq/rabbitmq-server/files/4229206/log.zip)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.
