### ISSUE TITLE
Windows Server does not recognizes rabbitmq.conf when it is creates **after** the installation

### ISSUE THREAD

**Issue by boldt** [rabbitmq/rabbitmq-server#2251]
# Related rabbitmq-users discussion

See: https://groups.google.com/forum/#!topic/rabbitmq-users/Pxt22s2NhBU

# My Environment

* RabbitMQ server: 3.8.2 (`rabbitmq-server-3.8.2.exe`)
* Erlang: 22.2: (`otp_win64_22.2.exe`)
* Operating system version: Windows Server 2012 / Windows Server 2016
* RabbitMQ plugins: Management

# Steps to reproduce

I was able to reproduce this issue on on two Servers, Windows Server 2012 and Windows Server 2016:

* Install `otp_win64_22.2.exe`
* Install `rabbitmq-server-3.8.2.exe` (RMQ is started now)
* Enable the management plugin: `rabbitmq-plugins enable rabbitmq_management`
* Create a `rabbitmq.conf` in `%AppData%\RabbitMQ` with the following content:

```
# Allow access to the guest user from anywhere on the network.
loopback_users.guest = false
```

The `%AppData%\RabbitMQ` looks as follows: 

![001](https://user-images.githubusercontent.com/750793/75090718-0a890b00-5566-11ea-9328-cc2b1948d0c1.jpg)

Restart the server from the start menu with:

* `RabbitMQ Service - stop` and
* `RabbitMQ Service - start`

The log-file looks as follows: 

![002](https://user-images.githubusercontent.com/750793/75090719-0ceb6500-5566-11ea-98c1-e903009ed77a.jpg)

# Issue

As it can be see in the screenshot, RMQ only recognizes the `advanced.config` and, but not the `rabbitmq.conf`. E.g., the `rabbitmq.conf` is not taken into account **after** the installation of RMQ.

# Workaround

I ran the following four steps from the start menu:

* `RabbitMQ Service - stop`
* `RabbitMQ Service - remove` - *additional !!!*
* `RabbitMQ Service - (re)install` - *additional !!!*
* `RabbitMQ Service - start`

Now, the `rabbitmq.conf` is taken into account.

# Conclusion

The `rabbitmq.conf` is taken into account, when it exists **before** the (re)installation of RMQ.

# Expected behavior

RMQ should be able to recognizes the `rabbitmq.conf` after the installation with a simple restart.

**Comment by michaelklishin** [comment]
As explained by someone else on the mailing list, Windows service must be reinstalled for the changes to be picked up. This may change in the future but Windows service peculiarities have a relatively low priority for our team right now.
