### ISSUE TITLE
Unable to delete a specific queue after RabbitMQ cluster recovery

### ISSUE THREAD

**Issue by klutarevich** [rabbitmq/rabbitmq-server#230]
I have a cluster of 2 servers (3.4.1) where one node just failed and left the cluster. I recovered it by restarting the server and it rejoined the cluster, all queues (durable) got synchronized except one. That queue was still inaccessible by applications on both publisher and subscriber side. I rerouted them to a different queue and tried to delete that one but all delete requests (via UI or rabbitmqadmin) hanged. I can still see it in Admin UI and it shows as not synchronized, binding removed and ? ? ? in Messages section. How can I delete that queue and create a new one with the original name?

**Comment by michaelklishin** [comment]
Please ask questions on rabbitmq-users.

**Comment by klutarevich** [comment]
What's rabbitmq-users? Google group?

**Comment by michaelklishin** [comment]
[Correct](http://www.rabbitmq.com/community.html).
