### ISSUE TITLE
RabbitMQ crashes if it can't open a file on Windows

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-server#231]
See for more details: http://stackoverflow.com/questions/31544330/rabbitmq-generic-server-rabbit-disk-monitor-terminating-eheap-alloc-cannot-al

**Comment by michaelklishin** [comment]
```
eheap_alloc: Cannot allocate 229520 bytes of memory (of type "old_heap").
```

is a runtime error. We can't do anything about it. Disk monitor termination should not affect the rest of the server. I feel these messages are completely unrelated to each other.

So, what can we do here?

**Comment by videlalvaro** [comment]
I think we need to preven the broker from bringing the whole system down, even more after something so trivial like running the disk monitor

**Comment by michaelklishin** [comment]
I'm not sure what that means.

Disk monitor does not bring the VM down. We have plenty of users that are examples of that.

RabbitMQ cannot bring the OS down. The error in the log comes from the VM unable to allocate memory (known issue resolved in 17.x).

The user falsely associates the two errors.

**Comment by videlalvaro** [comment]
"Whole system down" of course refers to the Erlang VM, not the OS.
