### ISSUE TITLE
[Feature] Mirror latest erlang installer(s) with RabbitMQ Downloads

### ISSUE THREAD

**Issue by tracker1** [rabbitmq/rabbitmq-server#2312]
Given the erlang pre-requisite (sitting at 4% download in the Southwest US, and probably going to take an hour) ... It would be nice if you'd tag an #Erlang release and include the dependencies for the latest erlang.

Or reach out to erlang to try to get them to post it to github releases or another cdn... it's the most painful part of installing RabbitMQ, at least in Windows. (aside, I would love to move off this).

**Comment by michaelklishin** [comment]
I'm afraid I am not certain what "tagging an Erlang" release would mean.

If the idea is that we would bundle an Erlang/OTP release, this may happen one day but would significantly complicate RabbitMQ packaging as there would have to be a package per supported OS.

Our team is responsible for packaging Erlang/OTP and we have tried to influence the way they are produced but with little success. The team at Ericsson have opinions and ways in which they do things. So instead we produce Erlang/OTP packages for the very latest patch releases for [Debian and RPM-based distributions](https://bintray.com/rabbitmq-erlang/) which are distributed to Bintray and PackageCloud.

We do not produce Windows packages and don't have the resources to take on that task. Both Ericsson and Erlang Solutions produce Windows packages, usually, they are up-to-date with the latest minor release, which for RabbitMQ is perfectly sufficient 99% of the time.

We have also contributed to the [most popular Docker image](https://github.com/docker-library/rabbitmq) to be automatically rebuilt with the latest patch release. So it's Windows packages specifically that are a little out of date and potentially distributed via a single geo location. I'm afraid the community and Erlang users should step up to the plate and solve that problem, or use Docker images and the Windows Subsystem for Linux or simply switch to a different supported OS.

And Erlang releases that everyone uses are [distributed via GitHub releases already](https://github.com/erlang/otp/releases), they are just not binary builds.
