### ISSUE TITLE
RABBITMQ_QUORUM_DIR usage causes feature flags to not get enabled

### ISSUE THREAD

**Issue by Vanlightly** [rabbitmq/rabbitmq-server#2317]
If you set the RABBITMQ_QUORUM_DIR to a value that is not the mnesia directory, then on start-up, none of the feature flags get enabled.

This seems to be related to the is_virgin_node() function in rabbit_mnesia.erl. It relies on rabbit_node_monitor:quorum_filename() to return the correct quorum queue data_dir but it doesn't. It is hardcoded:

```
quorum_filename() ->
    filename:join(rabbit_mnesia:dir(), "quorum").
```

**Comment by michaelklishin** [comment]
@dumbbell I could reproduce this and this (or a related `rabbit_env`) change has affected the tile.

**Comment by michaelklishin** [comment]
So it must stem from [rabbit_env:quorum_queue_dir/1`](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_env.erl#L833) but I haven't traced it down further yet.

**Comment by michaelklishin** [comment]
`rabbit_feature_flags:is_supported_locally/1` returns `false` for the `quorum_queues` flag in the problematic case. So something causes the flag to not be registered.

**Comment by michaelklishin** [comment]
Curious I no longer can reproduce this but now see the findings by @Vanlightly 👍

**Comment by michaelklishin** [comment]
`rabbit_mnesia:is_virgin_node/0` was last changed in 8600e543e384470f972d81238a94449433ea0645.

**Comment by michaelklishin** [comment]
Waiting for feedback to see if #2359 addressed this.

**Comment by Vanlightly** [comment]
I can confirm that this is fixed.
