### ISSUE TITLE
rabbitmqadmin doesn't respect --host switch over .rabbitmqadmin.conf

### ISSUE THREAD

**Issue by HariSekhon** [rabbitmq/rabbitmq-server#2319]
I've found that the `rabbitmqadmin` command was not respecting the `--host` switch on the command line and instead was using the `[default]` `hostname` field's value, leading to confusion over socket timeouts.

I had to find this out via tcpdump debugging, but it wasted time as this is not intuitive behaviour and not how most command line programs behave in terms of order or precedence.

Usually explicit command line switches should take priority over implicit values like the default values of a configuration file, or environment variables.

This was in RabbitMQ 3.6.16.

Please enforce order of precedence for the command line switches to take priority.

**Comment by michaelklishin** [comment]
Please provide your config file a set of steps to reproduce with `rabbitmqadmin` from the tip of `v3.8.x` branch (or 3.8.3). RabbitMQ 3.6 has been out of support for almost 2 years now. If this is still relevant and we have a clear way of reproducing, this will be reopened.
