### ISSUE TITLE
Debian package upgrade does not migrate 3rd party plugins

### ISSUE THREAD

**Issue by tonal** [rabbitmq/rabbitmq-server#232]
OS: Kubuntu 14.04 with all updates
rabbitmq-server from APT Repository `deb http://www.rabbitmq.com/debian/ testing main`

rabbitmq-server do not start after `aptitude safe-upgrade`
startup_err:

```
Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
```

startup_log:

```
BOOT FAILED
===========

Error description:
   {error,{"no such file or directory",
           "rabbitmq_delayed_message_exchange.app"}}

Log files (may contain more information):
   /var/log/rabbitmq/rabbit@hius2.log
   /var/log/rabbitmq/rabbit@hius2-sasl.log

Stack trace:
   [{app_utils,load_applications,2,[]},
    {app_utils,load_applications,1,[]},
    {rabbit,start_apps,1,[]},
    {rabbit,broker_start,0,[]},
    {rabbit,start_it,1,[]},
    {init,start_it,1,[]},
    {init,start_em,1,[]}]

{"init terminating in do_boot",{error,{"no such file or directory","rabbitmq_delayed_message_exchange.app"}}}^M
```

**Comment by tonal** [comment]
```
$ sudo rabbitmq-plugins list                                                         
[sudo] password for tonal:                                                                                            
WARNING - plugins currently enabled but missing: [rabbitmq_delayed_message_exchange]                                  

 Configured: E = explicitly enabled; e = implicitly enabled
 | Status:   [failed to contact rabbit@hius2 - status not shown]
 |/
[e ] amqp_client                       3.5.4
[  ] cowboy                            0.5.0-rmq3.5.4-git4b93c2d
[e ] mochiweb                          2.7.0-rmq3.5.4-git680dba8
[  ] rabbitmq_amqp1_0                  3.5.4
[  ] rabbitmq_auth_backend_ldap        3.5.4
[  ] rabbitmq_auth_mechanism_ssl       3.5.4
[  ] rabbitmq_consistent_hash_exchange 3.5.4
[  ] rabbitmq_federation               3.5.4
[  ] rabbitmq_federation_management    3.5.4
[E ] rabbitmq_management               3.5.4
[e ] rabbitmq_management_agent         3.5.4
[  ] rabbitmq_management_visualiser    3.5.4
[  ] rabbitmq_mqtt                     3.5.4
[  ] rabbitmq_shovel                   3.5.4
[  ] rabbitmq_shovel_management        3.5.4
[  ] rabbitmq_stomp                    3.5.4
[  ] rabbitmq_test                     3.5.4
[  ] rabbitmq_tracing                  3.5.4
[e ] rabbitmq_web_dispatch             3.5.4
[  ] rabbitmq_web_stomp                3.5.4
[  ] rabbitmq_web_stomp_examples       3.5.4
[  ] sockjs                            0.3.4-rmq3.5.4-git3132eb9
[e ] webmachine                        1.10.3-rmq3.5.4-gite9359c7
```

**Comment by tonal** [comment]
rabbitmq_delayed_message_exchange locate in `/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.3/plugins`
rabbitmq_delayed_message_exchange-0.0.1-rmq3.5.x-9bf265e4.ez
after move plugin to `/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.4/plugins` rabbitmq-server starts

**Comment by dumbbell** [comment]
Hi @tonal!

The `rabbitmq_delayed_message_exchange` plugin is not provided with RabbitMQ at this time. I suppose you installed it yourself when you were running 3.5.3, do you confirm this?

So our package does not handle third-party plugins correctly, we need to look at this.

**Comment by tonal** [comment]
Hi @dumbbell!
Yes. I manuali install rabbitmq_delayed_message_exchange plugin to 3.5.3

**Comment by gmr** [comment]
Would the "fix" here be to warn on missing plugins instead of crash?

**Comment by michaelklishin** [comment]
@gmr in some cases other plugins won't be able to start. Some may be crucial (e.g. rabbitmq-clusterer or rabbitmq-autocluster). I agree that we should not terminate without a sensible error message, of course.

**Comment by tonal** [comment]
Also for version 3.5.5-3
```
$ cat startup_err 

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()

$ cat startup_log 


BOOT FAILED
===========

Error description:
   {error,{"no such file or directory",
           "rabbitmq_delayed_message_exchange.app"}}

Log files (may contain more information):
   /var/log/rabbitmq/rabbit@hius2.log
   /var/log/rabbitmq/rabbit@hius2-sasl.log

Stack trace:
   [{app_utils,load_applications,2,[]},
    {app_utils,load_applications,1,[]},
    {rabbit,start_apps,1,[]},
    {rabbit,broker_start,0,[]},
    {rabbit,start_it,1,[]},
    {init,start_it,1,[]},
    {init,start_em,1,[]}]

{"init terminating in do_boot",{error,{"no such file or directory","rabbitmq_delayed_message_exchange.app"}}}
```
After move delayed_message plagin start Ok.
```
user@node:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.4/plugins$ sudo mv rabbitmq_delayed_message_exchange-0.0.1-rmq3.5.x-9bf265e4.ez ../../rabbitmq_server-3.5.5/plugins/
```

**Comment by michaelklishin** [comment]
You haven't installed delayed exchange for the new version.

**Comment by dumbbell** [comment]
Hi @tonal!

This is a known issue, see #232.

**Comment by michaelklishin** [comment]
After giving it some thought, I don't think simply copying the plugin archive is going to be safe in all cases: plugins can be no longer compatible with the new version. So this needs to be considered. Perhaps we need to give plugins a way to indicate RabbitMQ version support ranges, which is a can of worms of its own.

**Comment by tonal** [comment]
May be simple copy between minor subversions?

**Comment by dumbbell** [comment]
(Sorry about my previous comment, I thought it was a new issue, but you just added a comment :)

@michaelklishin: I think @tonal idea is fine. In the current situation, an upgrade leaves the service in a broken state. We can also make it a debconf choice, defaulting to "copy plugins", and add some filtering (for instance, when a 3rd-party plugin is integrated in the core).

**Comment by ikvmw** [comment]
@michaelklishin Can I close this?

**Comment by jogoossens** [comment]
What is the final solution for this kind of situation? Why not create packages for the more common plugins and distribute them through the normal rabbitmq repo's?

**Comment by lukebakken** [comment]
> Why not create packages for the more common plugins and distribute them through the normal rabbitmq repo's?

Team RabbitMQ does not have the time or resources to do this. The community of users who benefit from third-party plugins could come up with a solution.

**Comment by jogoossens** [comment]
Ok, but do minor updates work now in the meanwhile? Can we just put a plugin and expect it to work when rabbitmq gets apt upgraded? What about a major version upgrade, will it still try to keep the existing plugin (it might work with some luck?) ? :)
