### ISSUE TITLE
A way to put a node into a pre-upgrade mode ("drain" it)

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#2321]
## Problem Definition

There's increasing interest from deployment automation and technical ops engineers in a maintenance mode for a node. After https://github.com/rabbitmq/rabbitmq-cli/issues/408 and a Zoom discussion with @harshac @ansd @gerhard @Vanlightly @pjk25 and others we have settle on roughly these steps that a node entering maintenance mode can do. The final list can change or be modified over time:

* [x] Change this node's status to be "maintenance". Other nodes can use this information to avoid placing new leaders/master replicas on it.
* [x] Suspend all listeners so that no new connections are accepted
* [x] Close all existing client connections
* [x] Transfer primary classic mirrored queue replicas to other nodes
* [x] Transfer quorum queue leaders to other nodes. We will do this by shutting all Ra instances on this node down: this will trigger leader elections for quorum queues which target node won't participate in
* [x] Log all of the above at high severity (e.g. `alert`)

and then return.

At this point the node can only be shut down, it will look gone to other cluster peers and won't accept any client connections.

Note that there's already a health check that verifies if it's safe to shut the node down (it is not quorum-critical for any quorum queues, and there are synchronized mirrors for classic mirrored queues hosted on it).

Most steps above can be reversed, at least to bring the node back into an operational state. There are exceptions to this (we cannot recover closed client connections from the node itself) and things that are reversible to some extent if the operator decides to do it (e.g. queue leader/master replica placement rebalancing).

This is kind of an umbrella issue so paying attention to other issues and PRs that reference it is a good idea.

## Implementation

Primary PR: https://github.com/rabbitmq/rabbitmq-server/pull/2349

**Comment by pjk25** [comment]
Thanks for writing this up @michaelklishin

**Comment by dumbbell** [comment]
I like this outline, thank you for putting this up.

Steps 2 to 5 looks like `rabbit:stop()` basically. Will you use that directly, or do you plan to write a specific code for this part?

**Comment by michaelklishin** [comment]
We want this to be fine grained, reasonably easy to extend in the future and reversible to the extend it is possible, so `rabbit:stop/0` won't be used.

**Comment by joachim-kn** [comment]
I like to see this proposal, your description looks pretty much like what I had in mind when placing my support request at vmware support (SR #19061777109 - "Find the best way to gracefully shutdown a RabbitMQ HA cluster") on behalf of my company's account.
Specifically under (4) I would like to add that closing client connections should happen "gracefully" in the sense that ongoing messages transmissions would not interrupted, so there are no redelivered (potential duplicate) messages after the clients reconnect.
Thanks for writing this up @michaelklishin

**Comment by michaelklishin** [comment]
Connection closure won't be graceful. RabbitMQ nodes cannot know what data may be in flight or sitting in OS kernel buffers waiting to be "delivered" to the node, so we'd never know when we are "done". Exactly once delivery is not practically possible (but exactly once *processing* is and is perfectly possible with existing protocol and client library features).

Use [acknowledgments](https://www.rabbitmq.com/confirms.html) and assume that connections can always be interrupted at any moment for any number of reasons, not necessarily an upgrade.

**Comment by michaelklishin** [comment]
At the moment there is no proposal beyond the list of steps outlined in this issue. This may change (e.g. some steps will be dropped and others added) and for while all relevant issues and PRs will reference this one.

**Comment by michaelklishin** [comment]
This still needs more integration tests but is ready for exploratory testing and QA.

**Comment by michaelklishin** [comment]
Backported to `v3.8.x` for `3.8.8` behind a feature flag.
