### ISSUE TITLE
Message indices fail to recover, even if the broker shuts down gracefully with rabbitmqctl

### ISSUE THREAD

**Issue by pjk25** [rabbitmq/rabbitmq-server#2324]
In https://github.com/rabbitmq/rabbitmq-server/issues/2254, it's evident that even though the broker is gracefully shut down with `rabbitmqctl stop_app`, message indices are rebuilt from scratch on startup. This should not be the case (and the recovery does work in at least the simple case of starting the broker, declaring a durable queue, and stopping and starting it).

**Comment by pjk25** [comment]
I have determined that in this case, the persistent message store did not have time to shut down cleanly and write the necessary recovery data to disk.

I increased the timeout for child termination in the appropriate supervisor from it's 30 second default to 10 minutes, by adding `-rabbit worker_shutdown_timeout 600000` to the `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` of my container, and the node started up extremely quickly, around 2 minutes. Rebuilding the index in this same scenario takes around 45 minutes, so that's a big win.

I also timed the broker shutdown, and took around 95 seconds for the persistent message store to stop, so my timeout of 10 minutes was definitely overkill. However, I'm not certain if this is a case for changing the default in general from 30 seconds to something higher. For the sake of thoroughness, the `msg_store_index.ets` file produced in this scenario is 3.1GB (only 1.4GB of which ended up on disk during my previous test run with the default timeout). Unfortunately it's not obvious to the operator when the timeout occurs during shutdown so it took me some time to discover this.

@michaelklishin any thoughts on changing the default, or is there a way to log a message when the timeout aborts shutdown?

**Comment by pjk25** [comment]
I had a chance to monitor the container during `rabbitmqctl stop_app`, and there were two bursts of disk activity (I would imagine from writing the two .ets files), peaking at about 800MB/s and 600MB/s each. If one had slow disks, I suppose slow down the `rabbitmqctl stop_app` command, and necessitate a longer timeout.

**Comment by gerhard** [comment]
This is such an important find! Thanks @pjk25 for digging into it and finding the real reason for slow startup 🙌🏻

Any timeout value that we pick is guaranteed to be wrong. If the message store is running - looking at its reductions is one way of establishing that - then we shouldn't stop it. We don't know how fast the disks will be, or how much data needs writing, so we should fail the stop after the timeout and not kill the message store if it doesn't stop after an arbitrary amount of time.

cc-ing @kjnilsson & @dumbbell because they know a thing or two about this aspect.

**Comment by pjk25** [comment]
I'm not aware of a method of aborting termination from the child process, unless the supervisor's timeout is much longer and we do a soft timeout within the child that causes `rabbitmqctl stop_app` to fail. However, we'd need a way to let the operator extend the timeout on the live system and try again.

**Comment by lukebakken** [comment]
@pjk25 this is the `rabbitmq-users` discussion where the topic of message store shutdown timeouts came up - https://groups.google.com/d/msg/rabbitmq-users/kigg47y5Dt0/4VdOSel9DwAJ

My guess is that what you found [here](https://github.com/rabbitmq/rabbitmq-server/issues/2324#issuecomment-618912864) applies to that discussion as well.

RabbitMQ should not stop the VM until all data is quiesced. AFAIK like @pjk25 says children in a supervision tree can't influence their supervisor's shutdown timeout. One option is to pick a long shutdown timeout (like a day, not infinite!), and then update the user on the progress of the shutdown. If the user wishes, they can always `kill -9` the process. Our `systemd` configuration will have to be taken into account.

The behavior at shutdown is related to the behavior we've been discussing for "maintenance mode", too.

**Comment by michaelklishin** [comment]
Queue processes have a certain ability to monitor their state and its transition. As for supervisor timeouts, they have to be increased. This is a years-long discussion and no better solution emerged. Well, developing a custom supervisor type could be it but it this is a fundamental limitation since supervisors by design know very little about their child processes.

**Comment by pjk25** [comment]
I would be in favor of increasing the default timeout from 30 seconds to 5 minutes, since I don't see a downside to it. It appears that the longer graceful shutdown takes, the greater the benefit in startup time.

As for a soft timeout, it feels more complex than is warranted. I would prefer to do a more extensive check at startup, and provide the user with more info in the logs. Right now, we just check for the last recovery file. We could check for all 3, and if none are present, it's reasonable to assume a hard kill. If less than 3 are present, we could log a message to the effect of "recovery data is incomplete. Graceful shutdown may have been interrupted. Consider adjusting the 'worker_shutdown_timeout' if needed."

**Comment by michaelklishin** [comment]
Bumping the current timeout is a no-brainer if it is indeed 30 seconds for the supervisor in question.

What specifically do you mean by "all 3"?

**Comment by pjk25** [comment]
> Bumping the current timeout is a no-brainer if it is indeed 30 seconds for the supervisor in question.

`worker_shutdown_timeout` affects at least `amqp_channel_sup.erl`, `amqp_connection_type_sup.erl`, `rabbit_amqqueue_sup.erl`, `rabbit_client_sup.erl`, `rabbit_connection_helper_sup.erl`, `rabbit_connection_sup.erl`, `rabbit_restartable_sup.erl` and `rabbit_sup.erl`. Affecting only this supervisor would be tricky since we wouldn't want to break a user who had set a custom `worker_shutdown_timeout`.

> What specifically do you mean by "all 3"?

Great question.

For a given vhost, we write the File Summary ETS table to disk, as `file_summary.ets`, then in the case of rabbit_msg_store_ets_index, we write `msg_store_index.ets` to write the index to disk, then finally we write some erlang terms into `clean.dot` in our own format. The message store file if by far the largest, so I suspect partial writes to `clean.dot` will be exceedingly rare. So it short, the 3 usual files per vhost are `file_summary.ets`, `msg_store_index.ets` & `clean.dot`.

We'd have to give the index module a callback to the effect of `-spec infer_recovery_data_state() -> 'missing' | 'partial' | 'complete', but the logic does not feel complex.

**Comment by pjk25** [comment]
My opinion after having let this sit a bit is, let's increase the global timeout, maybe to 90 seconds, as it will cover a lot of cases, _and_ implement the partial recovery detection. It won't be perfect, but if we check for the 3 files instead of just the last, it would be easy to log a message to the user that "Partial recovery data was found; graceful shutdown may have been halted. Consider adjusting 'worker_shutdown_timeout' if necessary.".

**Comment by gerhard** [comment]
If we have to pick a default timeout for the persistent message store, 90 seconds doesn't feel sufficient. After all, this is the longest that a persistent message store will be given to gracefully stop, so 300 or even 600 seconds doesn't sound unreasonable **especially if** we know for a fact that the indices rebuild process required by an unclean shutdown takes 2700 seconds in our specific case.

Am I understanding correctly that if a message store stops in less than the default timeout period, the node stops? I want us to avoid introducing a fixed shutdown delay with this change.

Partial recovery detection sounds great, but it feels like a separate feature which is more involved than updating the default 30 seconds timeout.

Last question: how does changing the global timeout affect https://github.com/rabbitmq/rabbitmq-server-boshrelease/blob/v0.20.0/jobs/rabbitmq-server/templates/env.erb#L25-L31 ?

**Comment by michaelklishin** [comment]
Ubuntu and RPM package specs use a default shutdown timeout of 10 minutes as of https://github.com/rabbitmq/rabbitmq-server-release/pull/129.

**Comment by gerhard** [comment]
Sweet! I am assuming that the 10 minutes shutdown applies to all worker types.

Is the timeout that we are proposing here per worker type, or for everything?

**Comment by michaelklishin** [comment]
Most processes should not take close to 10 minutes to stop. Only queues and message stores should use a much higher value, and supervisors above them. The rest can use 120 seconds or so.

**Comment by gerhard** [comment]
This makes perfect sense, thanks Michael.

Part of implementing these timeout updates, can we also capture them in a single place? I don't mind if it's a bunch of macros in a single hrl file, or a new / existing doc page as long as we can see them all at once. The BOSH release is the only place that I am aware of having all worker types and associated timeouts in one file.

**Comment by pjk25** [comment]
The current 30 second timeout applies to a number of supervisors:
https://github.com/rabbitmq/rabbitmq-server/search?q=WORKER_WAIT&unscoped_q=WORKER_WAIT&type=Code

It's `rabbit_vhost_msg_store.erl` in particular that we would need to affect in particular for this issue, but the total timeout for the broker would therefore depend on how many vhosts there are.

Making the timeouts independently configurable would be a breaking change, so should the default just change to 120 (both in `rabbit.hrl` and the bosh release as linked above)?

**Comment by pjk25** [comment]
> Partial recovery detection sounds great, but it feels like a separate feature which is more involved than updating the default 30 seconds timeout.

Agreed. I can create a separate issue for that.

**Comment by gerhard** [comment]
> It's `rabbit_vhost_msg_store.erl` in particular that we would need to affect in particular for this issue, but the total timeout for the broker would therefore depend on how many vhosts there are.

Assuming that all message stores begin shutting down at the same time, and run concurrently, I propose that we introduce a new macro, e.g. `MSG_STORE_WORKER_WAIT`, and default it to `600000` (600 seconds)

Since `worker_shutdown_timeout` will no longer apply to message stores, we should introduce a new env, e.g. rabbit.message_store_shutdown_timeout and default it to `600000` (600 seconds). I don't think that this counts as a breaking change since we are refining the `worker_shutdown_timeout` for message stores.

What do you think @michaelklishin?

**Comment by michaelklishin** [comment]
@gerhard sounds reasonable.

**Comment by pjk25** [comment]
Great, now that we have consensus, I'll make these changes.

**Comment by pjk25** [comment]
https://github.com/rabbitmq/rabbitmq-common/pull/394 & https://github.com/rabbitmq/rabbitmq-server/pull/2362
