### ISSUE TITLE
Use `time_compat` module from Erlang 18.0's examples

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#233]
`erlang:now()` is deprecated in favor of a more complete and improved time and time correction API.

To support both the new and old APIs, Erlang 18.0 provides a `time_compat` module in ERTS' examples. We must audit every uses of `erlang:now()` and `os:timestamp()` to determine what we need and replace each of them with a call to `time_compat`.

Perhaps a similar issue should be opened in each affected plugin too. The `time_compat` module could be part of `rabbit_common` to help with this.

See a previous discussion in #203.

**Comment by dumbbell** [comment]
Once the entire Umbrella is converted, we can remove `rabbit_misc:now_to_ms()`.

**Comment by dumbbell** [comment]
The pull requests are ready for review.

Because some APIs and exchanged messages are modified, there are inter-dependencies between pull requests:

1. The following PRs must be reviewed and merged at the same time, otherwise plugins will break:
 * rabbitmq/rabbitmq-server#254
 * rabbitmq/rabbitmq-erlang-client#14
 * rabbitmq/rabbitmq-management#52
 * rabbitmq/rabbitmq-tracing#2

2. Then, and only when the PRs above were merged, the following PRs can be reviewed and merged in any order:
 * rabbitmq/rabbitmq-federation#11
 * rabbitmq/rabbitmq-shovel#4
 * rabbitmq/rabbitmq-stomp#25
 * rabbitmq/rabbitmq-clusterer#2

**Comment by michaelklishin** [comment]
:+1:
