### ISSUE TITLE
Handle SIGTERM in a way working with Docker

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#234]
See docker-library/rabbitmq#35.

**Comment by tianon** [comment]
:heart:!

**Comment by dumbbell** [comment]
Hi @tianon!

I pushed the proposed patch to the `rabbitmq-server-234` branch. Could you please give a try?

The diff is scary but the final RabbitMQ command line is simply put in a shell function. Then it checks the context: if RabbitMQ should be running in the foreground and the Erlang shell is disabled, then it setupts signal handlers. Otherwise, the behaviour is unchanged.

**Comment by tianon** [comment]
@dumbbell oh cool, I'll take a look!

**Comment by tianon** [comment]
So, the first issue I get testing that is:
```
trap: SIGHUP: bad trap
```

Looking at the change (which isn't too bad with `?w=1`: https://github.com/rabbitmq/rabbitmq-server/compare/master...rabbitmq-server-234?w=1), I'm also a little bit concerned that the strategy for fixing this is just to keep the wrapping `/bin/sh` alive and have it trap the signals instead -- that's essentially what our `tini` solution already does, albeit without the attempt to run `rabbitctl stop`.  If that's the way this needs to be fixed, it's OK, it just feels like a workaround. :smile:

**Comment by dumbbell** [comment]
Right, `dash` manpage doesn't mention if the `SIG` prefix is required, optional or forbidden, but the examples don't have this prefix. I will remove it.

About the strategy, there is no way in Erlang to setup signal handlers. It must be done either in a startup script or from an "Erlang port" (a forked program or a dlopen'd module). The latter is heavyweight and, IMHO, far less elegant than a startup script.

**Comment by dumbbell** [comment]
The `SIG` prefix was removed.

Oh, and thanks for the `?w=1` trick, I didn't know it :-)

**Comment by dumbbell** [comment]
Hello @tianon!

Did you have a chance to test the latest patch?

**Comment by tianon** [comment]
Seems to work OK. :+1:

I'm still a little leary of having the shell stay resident, but if this is the best path, sounds good enough! :metal:

**Comment by dumbbell** [comment]
Thank you for testing it!

Yeah, it's not ideal but there is nothing much we can do with Erlang. IMHO, the shell script is the cleanest/safest way to do it.

**Comment by tianon** [comment]
:+1: fair enough!

**Comment by andrewmichaelsmith** [comment]
Just a heads up for anyone running >=3.5.5 and scratching their head at this issue. It seems rabbitmq-server in the .db is not the same as the one in this pull request. Which I assume is why the issue persists (for me) on 3.5.5 .deb.
