### ISSUE TITLE
It is not possible to configure default_pass with value containing # character

### ISSUE THREAD

**Issue by KonstantinNosov** [rabbitmq/rabbitmq-server#2345]
`default_pass = 1234#678` in config results in `1234` password. `#678` part is treated as comment.
I've tried quotes around the value, escaping with \ and replacing # with %23 - no luck

**Comment by michaelklishin** [comment]
As you have found out, he `#` character starts a comment in the configuration format. We believe this is a reasonable limitation.

**Comment by michaelklishin** [comment]
Also, note that

 * The `advanced.config` file would not have this limitation, and
 * Default user credentials in the config file are arguably not a great security practice. You can [see users and permissions](https://www.rabbitmq.com/access-control.html#seeding) using definition import which again, would not have this limitation as it involves [password hashes](https://www.rabbitmq.com/passwords.html) as JSON values

**Comment by michaelklishin** [comment]
Here's an example which can also be found in the old [`rabbitmq.config.example`](https://github.com/rabbitmq/rabbitmq-server/blob/v3.7.x/docs/rabbitmq.config.example#L172) from older release series:

``` erl
%% advanced.config
{rabbit, [
  {default_user, <<"a-username">>},
  {default_pass, <<"a-pa##word">>}
]}.
```

In the above example, both values would not allow for the `"` character without escaping.

**Comment by KonstantinNosov** [comment]
thx. definitions hint is very helpful.
