### ISSUE TITLE
Failing operations on users and permissions should be logged as such

### ISSUE THREAD

**Issue by jordanfranssen** [rabbitmq/rabbitmq-server#2363]
Environment
RabbitMQ: 3.8.4
OS: CentOS 7

Additional logging is needed to meet cyber security guidelines in certain organizations. Below are several scenarios that do not produce expected logging.

The log file referenced is the rabbit.log (e.g. /var/log/rabbitmq/rabbit.log).

Logging configuration for RabbitMQ is set as follows in rabbitmq.conf:
```
log.file.level          = debug
log.default.level       = debug
log.connection.level    = debug
log.channel.level       = debug
log.queue.level         = debug
log.mirroring.level     = debug
log.upgrade.level       = debug
```

## Adding an Already-Existing User

In this case, I attempt to add a user that already exists. I expect the log to recognize the failure of the action due to the existence of that user.

Command (user "foobar" already **exists**):
`rabbitmqctl add_user foobar`

Command Line Output:
```
Adding user "foobar" ...
Password:
Error:
User "foobar" already exists
```

Log File:
```
2020-06-03 18:17:49.167 UTC [info] <0.28605.30> Creating user 'foobar'
```

## Deleting a Non-Existent User

In this case, I attempt to delete a user that does not exist. I expect the log to recognize the failure of the action and the reason.

Command (user "foobar" **does not exist**):
`rabbitmqctl delete_user foobar`

Command Line Output:
```
Deleting user "foobar" ...
Error:
{:no_such_user, "foobar"}
```

Log File:
```
2020-06-03 18:23:51.507 UTC [info] <0.29395.30> Deleting user 'foobar'
```

## Setting Permission for a Non-Existent User

In this case, I attempt to set permissions for a user that does not exist. I expect the log to recognize the failure of this action and the reason.

Command (user foobar **does not exist** ):
`rabbitmqctl set_permissions foobar '.*' '.*' '.*'`

Command Line Output:
```
Setting permissions for user "foobar" in vhost "/" ...
Error:
{:no_such_user, "foobar"}
```

Log File:
`2020-06-03 18:55:53.788 UTC [info] <0.32518.30> Setting permissions for 'foobar' in '/' to '.*', '.*', '.*'`

## Clearing Permissions

In this case, I successfully clear permissions for the user "foobar". I expect the log to recognize the success of this action.

Command (user foobar **exists** )
`rabbitmqctl clear_permissions foobar`

Command Line Output:
```
Clearing permissions for user "foobar" in vhost "/" ...
```

Log File:
**no relevant lines**

## Creating a Policy

In this case, I successfully create a policy called "foobar_policy" for vhost "foobar_vhost". I expect the log to recognize the success of this action.

Command (foobar_vhost **exists**):
`rabbitmqctl set_policy --vhost foobar_vhost foobar_policy 'foobar_queue' --apply-to queues '{"max-length":1}'`

Command Line Output:
```
Setting policy "foobar_policy" for pattern "foobar_queue" to "{"max-length":1}" with priority "0" for vhost "taskmanager" ...
```

Log File:
**no relevant lines**

**Comment by michaelklishin** [comment]
May I clarify what does "I expect the log to recognize the failure of the action and the reason" mean specifically? The messages from CLI in some examples already tell you what happened. Do you expect the same message to appear in the log? At what severity?

Are you aware of the fact that there is a [way to monitor internal events](https://www.rabbitmq.com/logging.html#internal-events)? It sometimes even has the acting user for context. Such user does not always exist (in particular when CLI tools are used) but it is a much more suitable tool for audit.

**Comment by michaelklishin** [comment]
I wonder if deleting a non-existent user should even be treated as an error. We have previously considered making it idempotent, e.g. deleting a non-existent queue is not an error. It does not mean we would not log the outcome as a warning but this is a good opportunity to review if some of these errors really should be treated as such.

The security and audit aspect here, as it often is, somewhat at odds with user friendliness.

**Comment by jordanfranssen** [comment]
I am reviewing our installation of RabbitMQ against the DISA Security Technical Implementation Guidelines which our organization adheres to.

Here are a couple examples of guidelines I'm trying to address here:
https://www.stigviewer.com/stig/application_security_and_development/2017-12-18/finding/V-69381
https://www.stigviewer.com/stig/application_security_and_development/2017-12-18/finding/V-69397
https://www.stigviewer.com/stig/application_security_and_development/2017-12-18/finding/V-69415
https://www.stigviewer.com/stig/application_security_and_development/2017-12-18/finding/V-69435

For security purposes, it is not enough that the user attempting the action is notified of its outcome. The attempt and outcome should also be logged at some level. Ideally it would be at the INFO level, but I'm willing to set logging to DEBUG to get the auditing I need if necessary.

Essentially, an auditor must have the ability to examine the logs and determine if anyone has been making any attempts to (legitimately or otherwise) affect the security in any way, including anything related to users, their access, and security policies within the software.

**Comment by michaelklishin** [comment]
I understand why you'd like to see the outcome logged. For these commands, it is reasonable and won't create a lot of log noise in most cases.

**Comment by michaelklishin** [comment]
When you create a policy, it already logs a message, the message simply does not make it very clear that the operation succeeded. The message can be changed to reflect that, though.

**Comment by michaelklishin** [comment]
@lukebakken and I concluded that we should continue treating deletion of a non-existent user as an error. `userdel(1)` and CLI tools of some other data services do it this way. Some of them also log warnings on both ends.
