### ISSUE TITLE
Wrong error code when connecting to a non-existent or forbidden vhost

### ISSUE THREAD

**Issue by drasil** [rabbitmq/rabbitmq-server#237]
* Connecting to a non-existent vhost in RabbitMQ 3.5.4 results in error code 541 (should be 404?).
* Connecting to an existing vhost in RabbitMQ 3.5.4 for which the user has no permissions results in error code 541 (should be 403?).

**Comment by michaelklishin** [comment]
Both `403` and `404` are [channel-level exceptions](http://www.rabbitmq.com/amqp-0-9-1-reference.html#constants).

`530` is the best fit for those cases. We'll evaluate if changing this is feasible: many (if not all) client libraries may need updating.

**Comment by Ayanda-D** [comment]
@michaelklishin, from the updates so far, error code `530` (not_allowed) will be returned for direct broker connections only, i.e. `amqp_direct_connection`. For network connections, problem is `rabbit_reader` throws an [exception](https://github.com/rabbitmq/rabbitmq-server/blob/rabbitmq-server-237/src/rabbit_reader.erl#L677) when [check_vhost_access](https://github.com/rabbitmq/rabbitmq-server/blob/rabbitmq-server-237/src/rabbit_access_control.erl#L134) fails. Socket is closed and nothing is sent back to help classify errors at the client end, and only the [expected](https://github.com/rabbitmq/rabbitmq-erlang-client/blob/master/src/amqp_network_connection.erl#L338) response is used. So [access_refused](https://github.com/rabbitmq/rabbitmq-erlang-client/blob/master/src/amqp_network_connection.erl#L340) will be returned to the client regardless of the error from `rabbit_access_control:check_vhost_access/3`. 

Would adding a `handle_exception` clause to `rabbit_reader` for such AMQP errors, avoiding the thrown exception, and sending `#'connection.close'{reply_code = 530, reply_text = <<"not allowed">>, ...}` back to the client before closing the socket be a way around this? or will this be violating amqp?

**Comment by michaelklishin** [comment]
I don't think it would, server-sent errors are
a part of the protocol.

Your suggestion sounds good, please submit a PR.
