### ISSUE TITLE
Umbrella issue: "upgrade" license to Mozilla Public License 2.0

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#2372]
This is an umbrella issue not specific to this repository.

Our team has been [given a green light](https://groups.google.com/forum/#!topic/rabbitmq-users/Ex8a2vHTw7I) to migrate to Mozilla Public License 2.0.

The migration will benefit RabbitMQ in several ways:

 * We won't be using a license that is considered to be "obsolete" and "obscure" by some current and prospective users
 * In general, the core team will have to answer fewer licensing-related questions and spend more time developing RabbitMQ
 * MPL2 explicitly mentions GPL, BSD and ASL2 compatibility (see Q13 and Q14 in [1]), while with MPL 1.1 we had to double- or triple-license our client libraries to eliminate potential compatibility confusion
 * MPL2 is arguably easier to reason about than 1.1

1. https://www.mozilla.org/en-US/MPL/2.0/FAQ/

**Comment by michaelklishin** [comment]
Relevant links:

 * [MPL2](https://www.mozilla.org/en-US/MPL/2.0/)
 * [MPL2 Revision FAQ](https://www.mozilla.org/en-US/MPL/2.0/Revision-FAQ/)
 * [MPL2 FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/)

**Comment by ArgTang** [comment]
#2408
