### ISSUE TITLE
Perform definition import after plugins are enabled

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#2384]
Currently there is a chicken-and-egg problem triangle between

 * Default data seeding
 * [Definition import](https://www.rabbitmq.com/definitions.html) on boot
 * Plugin activation

which can be problematic when definitions related to or dependent on plugins are involved, e.g. an exchange of a custom plugin-provided type.

We can potentially untangle this with a few low risk changes:

 * Avoid default data seeding when `load_definitions` is configured
 * Load definitions not in a core boot step but explicitly in a "post-run" phase, after plugins have been enabled
 * As a bonus, consider enabling client connection listeners after all plugins have been enabled (but this can be problematic: consider a Shovel that has to connect to the local node upon startup)

While definitions can be imported at any point after node startup, it would be convenient for Shovel and custom exchange type users if this limitation of `load_definitions` was lifted.

See #2381 for the background.

**Comment by tbnguyen1407** [comment]
Hello, this seems still not working for x-consistent-hash exchange plugin when an exchange of that type is defined in definitions.

I removed the exchange definition and see the plugin bootstep is still performed after definition import

![rabbitmq-definitions](https://user-images.githubusercontent.com/2490928/91546137-94ba8d80-e954-11ea-99c4-c045e3f00a2e.PNG)

Can you help take a look?

**Comment by lukebakken** [comment]
@tbnguyen1407 please provide complete instructions for how to reproduce, including a definitions file that will reproduce the issue. We don't have time to guess. Thank you.

**Comment by michaelklishin** [comment]
@tbnguyen1407 this does work for the consistent hash exchange plugin. In fact, this plugin was specifically affected by certain boot path refactoring in `3.8.4` and caused us to notice that the problem (which is not new) has worsened.

I can do another test but you have provided no details of what you actually did. Very likely you are using `management.load_definitions` which runs when the management plugin is activated, and not `load_definitions` which is a built-in option in 3.8.

https://github.com/docker-library/rabbitmq/pull/430 provides some details on the difference between the two.

**Comment by tbnguyen1407** [comment]
@michaelklishin yes seem I missed the new "load_definitions". It can work now. Thank you.
