### ISSUE TITLE
Consider adding a value "exceptAny" and "exceptAll" as a value of "x-match" attribute of Headers Exchange

### ISSUE THREAD

**Issue by juliofalbo** [rabbitmq/rabbitmq-server#2385]
Today, when we are using the Header's Exchange we can use the `x-match` argument to filter the messages that will be delivered to the queue, but we only have 2 possible values: **any** and **all**, and would be great if we can have something like **exceptAny** and **exceptAll** or instead of **x-match** something like **x-except**.

**SUGGESTION**:

Headers Exchange: `amqp.headers`

Queue 1: `queue.brazil`
Queue 2: `queue.denmark`
Queue 3: `queue.rest.of.the.world`

Bind Queue 1:
```
- Arguments
  country: brazil
  x-match: all
```
_Result: Any message with the header's argument country is `brazil` goes to the `queue.brazil` queue._

Bind Queue 2:
```
- Arguments
  country: denmark
  x-match: all
```
_Result: Any message with the header's argument country is `denmark` goes to the `queue.denmark` queue._

Bind Queue 3:
```
- Arguments
  country: brazil
  country: denmark
  x-match: exceptAny
```

or

```
- Arguments
  country: brazil
  country: denmark
  x-except: any
```
_Result: Any message when the header's argument country is different from `brazil` and `denmark` goes to the `queue.rest.of.the.world` queue._

**Comment by michaelklishin** [comment]
This is a reasonable idea. Thanks for the above average amount of details. Such modes are not a part of the AMQP 0-9-1 spec and the headers exchange is not popular enough to justify a major time investment for our team, so we make no promises if/when this extension may be introduced.

**Comment by juliofalbo** [comment]
I understand your point but maybe new features like that can make the headers exchange more popular.

But thank you for considering.

**Comment by ariel-anieli** [comment]
It seems addressed by https://github.com/rabbitmq/rabbitmq-server/pull/4143 & https://github.com/rabbitmq/rabbitmq-server/pull/4203; am I right?
