### ISSUE TITLE
CTL_ERL_ARGS can't be set

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#2394]
Reported here: https://groups.google.com/d/topic/rabbitmq-users/Ovp4iKNFL7Y/discussion

Broken by this commit:

https://github.com/rabbitmq/rabbitmq-server/commit/68c30553ccf306325a64b1fe6069e6bcc9c26b41

We may have to look at `CTL_DIST_PORT_*` settings as well.

**Comment by dumbbell** [comment]
Please ignore my commit referenced in this issue. I discovered you already prepared something after. I deleted my branch, yours looks good :-)
