### ISSUE TITLE
Spring boot: RabbitMq and Database management when error occurred in Exchange

### ISSUE THREAD

**Issue by aelmalki** [rabbitmq/rabbitmq-server#2404]
I have a problem to manage the RabbitMQ and Database transaction in case the exchange is not found. This is the simple sequence:
* Put message to Exchange
* Mark as sent the sent message in database

When the Exchange is not found, the message is not sent, however the row is updated in database, which doesn't respect the transactional behavior. Transaction are correctly managed for other error cases (DB error or RabbitMQ not available).

How can I manage this use case as transactional processing?

Transaction enabled in configuration:
```
@Bean
@ConditionalOnMissingClass("org.springframework.orm.jpa.JpaTransactionManager")
public RabbitTransactionManager rabbitTransactionManager(ConnectionFactory connectionFactory) {
    return new RabbitTransactionManager(connectionFactory);
}

@Bean
public RabbitTemplate rabbitTemplate(ConnectionFactory connectionFactory) {
    RabbitTemplate template = new RabbitTemplate(connectionFactory);
    template.setMessageConverter(jacksonMessageConverter());
    template.setChannelTransacted(true);
    return template;
}
```
My service:

```
@Override
@Transactional
public void push(Message message) {

    rabbitTemplate.convertAndSend(
                "MessageExchange",
                "binding.key",
                objectMapper.writeValueAsString(message));

    repository.markAsSent(message.getId());
}
```
Error fired after leaving method, not in the rabbitTemplate.convertAndSend method :

```
[AMQP Connection] ERROR o.s.a.r.c.CachingConnectionFactory.log : Channel shutdown: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'MessageExchange' in vhost '/', class-id=60, method-id=40)
[ThreadPoolTaskScheduler1] ERROR o.s.t.s.TransactionSynchronizationUtils.invokeAfterCompletion : TransactionSynchronization.afterCompletion threw exception
java.lang.IllegalStateException: Channel closed during transaction
    at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:1171)
    at com.sun.proxy.$Proxy143.txCommit(Unknown Source)
    at org.springframework.amqp.rabbit.connection.RabbitResourceHolder.commitAll(RabbitResourceHolder.java:153)
    at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$RabbitResourceSynchronization.afterCompletion(ConnectionFactoryUtils.java:332)
```

Thank you.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Please post Spring AMQP questions to StackOverflow and tag them with `spring-amqp`.

When multiple data services are involved in a transaction, you cannot "roll it back" and neither can Spring.
So your code has to be extra resilient and not proceed to next steps if you don't have a reasonable degree of certainty in that the "current" step has been finished (e.g. a message is published and confirmed).

[Publisher Data Safety](https://www.rabbitmq.com/publishers.html#data-safety) and [Unroutable Messages](https://www.rabbitmq.com/publishers.html#unroutable) explains what features for publisher-side data safety are provided by RabbitMQ/AMQP 0-9-1 client libraries.
