### ISSUE TITLE
After a 3.5.1 to 3.5.3 upgrade rabbitmq-server unable to stop

### ISSUE THREAD

**Issue by midas** [rabbitmq/rabbitmq-server#241]
After upgrading a production environment to v3.5.3 from v3.5.1 that has been running RabbitMQ since January of this year with no issues, we began to have issues with the system.  Specifically, immediately upon upgrading and starting `rabbitmq-server`, the service would not stop when issued the `service rabbitmq-server stop` command.  As a result, the service would have to be killed, which sometimes resulted in the corruption of the mnesia DB.

Additionally, if the system were allowed to run for a period of 6 or more hours, some of the subscriber processes would eventually report a `Failed to create thread: Resource temporarily unavailable`  error.  We also observed sluggishness in the other services running on the same host as the `rabbitmq-server` process.  However, the memory usage was within the expected normal range.

We downgraded to 3.5.1 and restarted all services.  The same results outlined in the prior paragraphs were observed overnight.  The next morning, we attempted to stop the service and it would not stop.  Thus we issued a kill command and the mnesia DB became corrupted yet again.  Our next step was to delete the `/var/lib/rabbitmq/mnesia` directory and start the `rabbitmq-server` service again.  At this point we adjourned to consider a path forward.  When we returned to the site the next morning, we observed that `rabbitmq-server` and all queues were performing as expected.  Additionally, issuing a stop command now works as expected.

It seems that some kind of bug or issue was introduced between 3.5.1 and 3.5.3 that is making some artifact in the `/var/lib/rabbitmq/mnesia` directory cause issues for rabbitmq-server.

We are running on Redhat Linux 6.5.

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users and provide server logs as well as rabbitmqctl report output and ulimit -a one.

**Comment by midas** [comment]
I am most certainly willing to take this course of action, but can you tell me why you consider this a question and not a bug report?

**Comment by michaelklishin** [comment]
> On 29/7/2015, at 20:24, Jason Harrelson <notifications@github.com> wrote:
> 
> some of the subscriber processes would eventually report a Failed to create thread: Resource temporarily unavailable error

The fact that your consumer failed to allocate a thread and eventually the system stabilized suggests the consumer app had to use a higher that usual number of threads. RabbitMQ cannot influence this and it uses fewer than 100 threads by default (unless you have 70 or more cores).

Only logs can help understand what was going on.

rabbitmqctl eval "rabbit_diagnostics:maybe_stuck()." will list threads that are potentially stuck.

**Comment by michaelklishin** [comment]
There is no evidence that this is a bug. Most of such reports end up being environment-specific problems.
