### ISSUE TITLE
STOMP connection not closed after emitting ERROR frame

### ISSUE THREAD

**Issue by eigengrau** [rabbitmq/rabbitmq-server#2410]
As per the STOMP spec, a broker must always close the connection after sending an ERROR frame to a client. However, when using the STOMP and Web STOMP plugins, RabbitMQ sometimes (always?) leaves the connection open. Since clients rely on the assumption that the connection will be closed after any error, they will generally not attempt to renew their subscriptions after encountering an ERROR frame without a subsequent disconnect, resulting in messages not being received.

### Steps to reproduce

1. Connect to a single-node RabbitMQ system
2. Subscribe to a queue `/queue/foo` via STOMP
3. Delete that queue using `rabbitmqctl`
4. Observe that the client has received an ERROR frame with a notification that its subscription was cancelled
5. Observe that the client’s connection to the broker is still alive. If any additional subscriptions were made in step 1, the client will still receive messages for these.

We also observe this behavior in a clustered configuration. A client connected to RabbitMQ node A and subscribed to a queue residing on RabbitMQ node B, when node B receives a SIGTERM, the client will also be sent an ERROR frame, but its connection to node A still remains open.

### RabbitMQ version

RabbitMQ version: 3.8.4

Erlang configuration: Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:64] [hipe]

Enabled plugins:

 * rabbitmq_web_stomp
 * rabbitmq_stomp
 * rabbitmq_management
 * amqp_client
 * rabbitmq_web_dispatch
 * cowboy
 * cowlib
 * rabbitmq_management_agent

**Comment by michaelklishin** [comment]
This works as expected. Deletion of a queue results in a consumer notification. It is not a reason to close the connection: RabbitMQ distinguish between the two. This is different from, say, an unparseable frame.
