### ISSUE TITLE
Force removing a node from a cluster does not remove it from quorum queues it participated in

### ISSUE THREAD

**Issue by gmr** [rabbitmq/rabbitmq-server#2414]
RabbitMQ 3.8.5
ESL Erlang 23.0.2
Ubuntu 18.04
Enabled Plugins:
```
[E*] rabbitmq_auth_backend_cache       3.8.5
[E*] rabbitmq_auth_backend_ldap        3.8.5
[E*] rabbitmq_consistent_hash_exchange 3.8.5
[E*] rabbitmq_management               3.8.5
[e*] rabbitmq_management_agent         3.8.5
[E*] rabbitmq_peer_discovery_common    3.8.5
[E*] rabbitmq_peer_discovery_consul    3.8.5
[E*] rabbitmq_prometheus               3.8.5
[E*] rabbitmq_random_exchange          3.8.5
[E*] rabbitmq_shovel                   3.8.5
[E*] rabbitmq_shovel_management        3.8.5
[E*] rabbitmq_tracing                  3.8.5
[e*] rabbitmq_web_dispatch             3.8.5
```

I ran into an issue with a cluster with 5 nodes using ~75 quorum queues, total throughput ranging between 1k messages/sec to 5k messages/sec. Our application does not carry a backlog of messages and is tuned to keep the queues to a minimal / 0 depth.  2 our of 5 nodes filled on disk space, where the files were segment files for the quorum queues. The other three nodes did not have this problem.  It is worth pointing out the queues that had the old segment files filling up disk space were the queues that have the highest velocities. I imagine there might be some race condition on cleanup or something. It is weird that only 2 out of 5 of the nodes filled up on disk space. This is not the primary issue for this ticket and I do not have a way to reproduce the behavior at this time.

Because the disk was full, I could not start RabbitMQ and decided the best course of action would be to remove the nodes from the cluster, wipe the mnesia directory and add them back. I am using the consul peer discovery plugin, so I enabled maintenance mode on the consul nodes, and then force removed the nodes from the cluster using `rabbitmqctl forget_cluster_node`.

The nodes were removed from the cluster, and I wanted to double check that they were gone from the quorum queues before I added them back in. I ran `rabbitmq-queues  quorum_status` for one of the queues and saw that the two nodes were still part of the quorum configuration with a status of `nodedown`:

```
rabbitmq-queues  quorum_status sm-writer-01
Status of quorum queue sm-writer-01 on node rabbit@analytics-rabbitmq01.production.aweberint.com ...
┌──────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────┬───────────┬──────────────┬────────────────┬──────┬─────────────────────────────────────────────────────────────────────────────┐
│ Node Name                                            │ Raft State                                                        │ Log Index │ Commit Index │ Snapshot Index │ Term │ Machine Version                                                             │
├──────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────────────┼──────┼─────────────────────────────────────────────────────────────────────────────┤
│ rabbit@analytics-rabbitmq05.production.aweberint.com │ follower                                                          │ 46055029  │ 46055029     │ 46054941       │ 2    │ {'%2F_sm-writer-01','rabbit@analytics-rabbitmq05.production.aweberint.com'} │
├──────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────────────┼──────┼─────────────────────────────────────────────────────────────────────────────┤
│ rabbit@analytics-rabbitmq04.production.aweberint.com │ follower                                                          │ 46055029  │ 46055029     │ 46054941       │ 2    │ {'%2F_sm-writer-01','rabbit@analytics-rabbitmq04.production.aweberint.com'} │
├──────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────────────┼──────┼─────────────────────────────────────────────────────────────────────────────┤
│ rabbit@analytics-rabbitmq03.production.aweberint.com │ {nodedown,'rabbit@analytics-rabbitmq03.production.aweberint.com'} │           │              │                │      │                                                                             │
├──────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────────────┼──────┼─────────────────────────────────────────────────────────────────────────────┤
│ rabbit@analytics-rabbitmq02.production.aweberint.com │ {nodedown,'rabbit@analytics-rabbitmq02.production.aweberint.com'} │           │              │                │      │                                                                             │
├──────────────────────────────────────────────────────┼───────────────────────────────────────────────────────────────────┼───────────┼──────────────┼────────────────┼──────┼─────────────────────────────────────────────────────────────────────────────┤
│ rabbit@analytics-rabbitmq01.production.aweberint.com │ leader                                                            │ 46055029  │ 46055029     │ 46054941       │ 2    │ {'%2F_sm-writer-01','rabbit@analytics-rabbitmq01.production.aweberint.com'} │
└──────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────────┴───────────┴──────────────┴────────────────┴──────┴─────────────────────────────────────────────────────────────────────────────┘
```
I inspected 5 other queues and they were all in a similar state (different leaders and index/term values obviously) where the two nodes that are no longer part of the cluster are still in the quorum config for the queues.

Suspecting I may be able to shrink the nodes out of the quorum configs, I ran `rabbitmq-queues shrink abbit@analytics-rabbitmq02.production.aweberint.com` (and for the other node as well). I found that indeed it did remove the from the quorum configs for all of the queues.

With the nodes removed from the cluster and from the quorum config, I felt safe to add the nodes back into the cluster and did so. I didn't see any issues after doing so, and as expected the two nodes were still not part of the quorum configs. I ran 
 `rabbitmq-queues grow rabbit@analytics-rabbitmq02.production.aweberint.com all` (and for the other node as well) and they were added back into the quorum configs without issue.

My expectation of the behavior for any queues or objects in a RabbitMQ cluster is that when a node for a cluster is removed, that all references and usage of that cluster node are removed from the cluster. Manually having to remove the configuration references to get to a "clean" state is an extra, unexpected step.

Please let me know if I can provide any other information, unfortunately to get back to a stable operational state, I can't help with finding the root cause on the raft segment file build-up.

**Comment by michaelklishin** [comment]
Thanks. The intent of the user action is clear here. We should be able to reproduce this reasonably easily.

**Comment by ptitvert** [comment]
@gmr did you find the problem with the segment files growing until the FS was full? We have exactly the same problem, and we are struggling to find why... so any help/hint would be great.
