### ISSUE TITLE
Audit `file_handle_cache:set_maximum_since_use()`

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#244]
While working on removing any use of `erlang:now()`, I stumble upon this code (already converted to use `time_compat`):

``` erlang
set_maximum_since_use(MaximumAge) ->
    Now = time_compat:monotonic_time(),
    case lists:foldl(
           fun ({{Ref, fhc_handle},
                 Handle = #handle { hdl = Hdl, last_used_at = Then }}, Rep) ->
                   TimeDiff = time_compat:convert_time_unit(Now - Then,
                                                            native,
                                                            micro_seconds),
                   case Hdl =/= closed andalso TimeDiff >= MaximumAge of
                       true  -> soft_close(Ref, Handle) orelse Rep;
                       false -> Rep
                   end;
               (_KeyValuePair, Rep) ->
                   Rep
           end, false, get()) of
        false -> age_tree_change(), ok;
        true  -> ok
    end.
```

The `lists:foldl()` walks through opened files and close those which are unused for `MaximumAge` microseconds. In `soft_close()`, it may remove the corresponding entry in the LRU `gb_tree`.

The loop returns `true` if entries were removed from this LRU tree or `false` otherwise. Then, it calls `age_tree_change()` which looks at the LRU tree and sends the oldest timestamp to the central `file_handle_cache` process.

Three points to check:
1. The condition appears reversed to me: `lists:foldl()` returns `true` when the LRU tree may have been modified, however, `age_tree_change()` is called in the `false` branch. If I'm write, it means
2. We have this LRU tree, wouldn't it be simpler to use that to close least recently used files instead of walking through all handles?
3. Last but not least, is this code used at all? I can't find where the `set_maximum_since_use` message (which is supposed to trigger this function) is sent.

**Comment by mkuratczyk** [comment]
`file_handle_cache` is pretty much not used anymore and will be removed altogether soon
