### ISSUE TITLE
Declaring a priority queue via management UI results in a badarith

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#245]
…in the queue process. @priviterag has a stack trace.

**Comment by priviterag** [comment]
=ERROR REPORT==== 30-Jul-2015::15:19:11 ===
Restarting crashed queue 'priority' in vhost '/'.

=ERROR REPORT==== 30-Jul-2015::15:19:11 ===
** Generic server <0.419.0> terminating
** Last message in was {'$gen_cast',init}
** When Server state == {q,{amqqueue,
                               {resource,<<"/">>,queue,<<"priority">>},
                               false,false,none,
                               [{<<"x-max-priority">>,signedint,0}],
                               <0.419.0>,[],[],[],undefined,[],[],live},
                           none,false,undefined,undefined,
                           {state,
                               {queue,[],[],0},
                               {active,1438265951336055,1.0}},
                           undefined,undefined,undefined,undefined,
                           {state,fine,5000,undefined},
                           {0,nil},
                           undefined,undefined,undefined,
                           {state,
                               {dict,0,16,16,8,80,48,
                                   {[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                    [],[]},
                                   {{[],[],[],[],[],[],[],[],[],[],[],[],[],
                                     [],[],[]}}},
                               delegate},
                           undefined,undefined,undefined,undefined,0,running}
** Reason for termination ==
** {badarith,
       [{rabbit_priority_queue,'-info/2-fun-1-',5,
            [{file,"src/rabbit_priority_queue.erl"},{line,381}]},
        {rabbit_priority_queue,fold0,3,
            [{file,"src/rabbit_priority_queue.erl"},{line,413}]},
        {rabbit_amqqueue_process,'-infos/2-lc$^0/1-0-',2,
            [{file,"src/rabbit_amqqueue_process.erl"},{line,808}]},
        {rabbit_amqqueue_process,'-infos/2-lc$^0/1-0-',2,
            [{file,"src/rabbit_amqqueue_process.erl"},{line,808}]},
        {rabbit_amqqueue_process,emit_stats,2,
            [{file,"src/rabbit_amqqueue_process.erl"},{line,882}]},
        {rabbit_event,if_enabled,3,[{file,"src/rabbit_event.erl"},{line,143}]},
        {rabbit_amqqueue_process,init_it2,3,
            [{file,"src/rabbit_amqqueue_process.erl"},{line,171}]},
        {gen_server2,handle_msg,2,
            [{file,"src/gen_server2.erl"},{line,1035}]}]}

**Comment by priviterag** [comment]
this ruby/bunny code also crashes the server: https://gist.github.com/priviterag/1643d0af72b413fa507e

steps to reproduce the error:
from the main rabbitmq-public-umbrella

cd rabbitmq-stomp
make run-in-broker
run the ruby script

**Comment by michaelklishin** [comment]
Queue process, not the server.

**Comment by dumbbell** [comment]
The problem comes from `rabbit_priority_queue:info/2`: it has a special case for `backing_queue_status` and expects all other infos are integers which can be summed.

This is not the case for `head_message_timestamp`, it needs a special case too. I'm adding one.

**Comment by dumbbell** [comment]
The pull requests are against `master` and the milestone is set to 3.6.0 because the `head_message_timestamp` key was added there. It is not supported in 3.5.x.

**Comment by michaelklishin** [comment]
:+1: 

Very good find @priviterag @dumbbell.

**Comment by dumbbell** [comment]
Thanks!

**Comment by michaelklishin** [comment]
This explains why I wasn't able to reproduce it some of the time: I was on the `stable` branch.
