### ISSUE TITLE
`ssl:connection_info/1` is deprecated

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#246]
It is replaced in Erlang 18.0 by `ssl:connection_information/{1,2}`.

We can use the same approach as `time_compat` and call the new API in a try/catch block, then fallback on the old API.

**Comment by michaelklishin** [comment]
`_compat` all the things!

**Comment by dumbbell** [comment]
Do you mean this should go in an `ssl_compat` module for instance?

**Comment by michaelklishin** [comment]
That sounds good to me.

**Comment by dumbbell** [comment]
I will do that.

**Comment by dumbbell** [comment]
Both pull requests depend on each other, so they must be tested at the same time.
