### ISSUE TITLE
Migrate Travis CI from `.org` to `.com` 

### ISSUE THREAD

**Issue by odidev** [rabbitmq/rabbitmq-server#2463]
Hi,

I was trying to build this project for arm64 in travis, but it is failing for arm64. As the time taken by the arm64 jobs exceeds the time provided for the individual jobs i.e; 50 minutes. Due to this reason the test is failing for arm64. This issue can be solved if we use arm64-graviton2.

As per https://blog.travis-ci.com/2020-09-11-arm-on-aws the arm64-graviton support is added for travis-ci.com. I have tested the package over arm64-graviton and it is successfully executed 

Travis Link : https://travis-ci.com/github/odidev/rabbitmq-server/jobs/396913977

It will be very helpful for arm64 users, if we migrate this project from travis-ci.org to travis-ci.com.

Please let me know if any help is required.

**Comment by michaelklishin** [comment]
Open source RabbitMQ has no architecture-specific code. As long as there is a suitable Erlang release, there is no reason for it to not work.

We are moving to a combination of Concourse and GitHub Actions for the long term, and GitHub Actions are already used by key repos in master. Moving to the commercial edition Travis would likely not be considered.

**Comment by michaelklishin** [comment]
There is usually no reason to build RabbitMQ from source in CI. You can install an ARM version of Erlang and use the Debian, RPM or generic binary binary build.
