### ISSUE TITLE
Proposal to stop modifying the default IO thread pool - mostly irrelevant since OTP 21

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-server#2473]
Since Erlang/OTP 21, there are very few linked-in drivers in the default Erlang/OTP distribution that uses the async thread pool. Most of them have been migrated to dirty IO schedulers, meaning that increasing the default async thread pool value is irrelevant for all Erlang/OTP versions that [today's RabbitMQ versions support](https://www.rabbitmq.com/which-erlang.html).

I am proposing that we stop changing this default so that:
* we don't spawn unnecessary system threads (+63 extra ones)
* end up with a more relevant & compact `rabbitmq-diagnostics runtime_thread_stats` output

What do you think? @dumbbell @michaelklishin

https://github.com/rabbitmq/rabbitmq-server/blob/4b320dd21ad099fc7513a55052f7553a719073bc/scripts/rabbitmq-server#L95

## References

* [Erlang VM News Regarding Dirty Schedulers and I/O News from the OTP Team - Roadmap](http://www.erlang-factory.com/euc2017/kenneth-lundin)
* [erl - Emulator Flags](http://erlang.org/doc/man/erl.html#emulator-flags)

**Comment by michaelklishin** [comment]
Makes sense.

**Comment by dumbbell** [comment]
Yes, that's a good idea!

**Comment by lukebakken** [comment]
Backported to `v3.8.x`
