### ISSUE TITLE
delegate calls in rabbit_amqqueue do not have a timeout

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#248]
When channels shut down, they notify queues via `rabbit_amqqueue:notify_down_all/2`, which
ends up using `delegate:call/2` with the timeout of `infinity`. That node may or may not be reachable. As a result, the node takes forever to shut down (eventually channel supervisors begin forcefully terminating children but that takes a long time).

Below is the output from `rabbit_diagnostics:maybe_stuck/0` from 2 nodes:

```
There are 95 processes.
Investigated 12 processes this round, 5000ms to go.
Investigated 12 processes this round, 4500ms to go.
Investigated 12 processes this round, 4000ms to go.
Investigated 12 processes this round, 3500ms to go.
Investigated 12 processes this round, 3000ms to go.
Investigated 12 processes this round, 2500ms to go.
Investigated 12 processes this round, 2000ms to go.
Investigated 12 processes this round, 1500ms to go.
Investigated 12 processes this round, 1000ms to go.
Investigated 12 processes this round, 500ms to go.
Found 12 suspicious processes.
[{pid,<5167.2.0>},
 {registered_name,[]},
 {current_stacktrace,[{gen,do_call,4,[{file,"gen.erl"},{line,220}]},
                      {gen_server,call,3,[{file,"gen_server.erl"},{line,184}]},
                      {app_utils,'-manage_applications/6-fun-0-',6,[]},
                      {lists,foldl,3,[{file,"lists.erl"},{line,1197}]},
                      {app_utils,manage_applications,6,[]},
                      {rabbit,start_apps,1,[]},
                      {rabbit,broker_start,0,[]},
                      {rabbit,start_it,1,[]}]},
 {initial_call,{erlang,apply,2}},
 {dictionary,[]},
 {message_queue_len,0},
 {links,[<5167.0.0>,<5167.44.0>]},
 {monitors,[{process,<5167.7.0>}]},
 {monitored_by,[]},
 {heap_size,6765}]
[{pid,<5167.44.0>},
 {registered_name,rabbit_boot},
 {current_stacktrace,[{rabbit,'-start_it/1-fun-0-',0,[]}]},
 {initial_call,{erlang,apply,2}},
 {dictionary,[]},
 {message_queue_len,0},
 {links,[<5167.2.0>]},
 {monitors,[]},
 {monitored_by,[]},
 {heap_size,233}]
[{pid,<5167.110.0>},
 {registered_name,[]},
 {current_stacktrace,
     [{proc_lib,sync_wait,2,[{file,"proc_lib.erl"},{line,321}]},
      {application_controller,start_appl,3,
          [{file,"application_controller.erl"},{line,1379}]},
      {application_controller,init_starter,4,
          [{file,"application_controller.erl"},{line,1356}]}]},
 {initial_call,{application_controller,init_starter,4}},
 {dictionary,[]},
 {message_queue_len,0},
 {links,[<5167.7.0>,<5167.111.0>]},
 {monitors,[]},
 {monitored_by,[]},
 {heap_size,610}]
[{pid,<5167.112.0>},
 {registered_name,rabbit},
 {current_stacktrace,
     [{mnesia_controller,connect_nodes,2,
          [{file,"mnesia_controller.erl"},{line,443}]},
      {rabbit_mnesia,change_extra_db_nodes,2,[]},
      {rabbit_mnesia,init_db,3,[]},
      {rabbit_mnesia,init_db_and_upgrade,3,[]},
      {rabbit_mnesia,init,0,[]},
      {rabbit,'-run_step/2-lc$^1/1-1-',1,[]},
      {rabbit,run_step,2,[]},
      {rabbit,'-run_boot_steps/1-lc$^0/1-0-',1,[]}]},
 {initial_call,{application_master,start_it,4}},
 {dictionary,[]},
 {message_queue_len,1},
 {links,[<5167.113.0>,<5167.154.0>,<5167.111.0>]},
 {monitors,[]},
 {monitored_by,[<5167.148.0>]},
 {heap_size,2584}]
[{pid,<5167.130.0>},
 {registered_name,[]},
 {current_stacktrace,
     [{mnesia_loader,wait_on_load_complete,1,
          [{file,"mnesia_loader.erl"},{line,329}]},
      {mnesia_tm,apply_fun,3,[{file,"mnesia_tm.erl"},{line,829}]},
      {mnesia_tm,execute_transaction,5,[{file,"mnesia_tm.erl"},{line,809}]},
      {mnesia_loader,init_receiver,5,[{file,"mnesia_loader.erl"},{line,269}]},
      {mnesia_loader,do_get_network_copy,5,
          [{file,"mnesia_loader.erl"},{line,206}]},
      {mnesia_controller,'-load_table_fun/1-fun-3-',5,
          [{file,"mnesia_controller.erl"},{line,2134}]},
      {mnesia_controller,'-load_and_reply/2-fun-0-',2,
          [{file,"mnesia_controller.erl"},{line,2096}]}]},
 {initial_call,{erlang,apply,2}},
 {dictionary,
     [{mnesia_table_sender_node,
          {rabbit_durable_route,'rabbit@broker-rabbit-3'}},
      {mnesia_real_loader,<5167.132.0>},
      {mnesia_activity_state,
          {mnesia,{tid,257061,<5167.130.0>},{tidstore,143399,[],1}}}]},
 {message_queue_len,0},
 {links,[<5167.93.0>,<5167.132.0>,<5167.63.0>]},
 {monitors,[]},
 {monitored_by,[]},
 {heap_size,377}]
[{pid,<5167.131.0>},
 {registered_name,[]},
 {current_stacktrace,
     [{mnesia_loader,wait_on_load_complete,1,
          [{file,"mnesia_loader.erl"},{line,329}]},
      {mnesia_tm,apply_fun,3,[{file,"mnesia_tm.erl"},{line,829}]},
      {mnesia_tm,execute_transaction,5,[{file,"mnesia_tm.erl"},{line,809}]},
      {mnesia_loader,init_receiver,5,[{file,"mnesia_loader.erl"},{line,269}]},
      {mnesia_loader,do_get_network_copy,5,
          [{file,"mnesia_loader.erl"},{line,206}]},
      {mnesia_controller,'-load_table_fun/1-fun-3-',5,
          [{file,"mnesia_controller.erl"},{line,2134}]},
      {mnesia_controller,'-load_and_reply/2-fun-0-',2,
          [{file,"mnesia_controller.erl"},{line,2096}]}]},
 {initial_call,{erlang,apply,2}},
 {dictionary,
     [{mnesia_table_sender_node,{rabbit_exchange,'rabbit@broker-rabbit-3'}},
      {mnesia_real_loader,<5167.133.0>},
      {mnesia_activity_state,
          {mnesia,{tid,257062,<5167.131.0>},{tidstore,147496,[],1}}}]},
 {message_queue_len,0},
 {links,[<5167.93.0>,<5167.133.0>,<5167.63.0>]},
 {monitors,[]},
 {monitored_by,[]},
 {heap_size,377}]
[{pid,<5167.132.0>},
 {registered_name,[]},
 {current_stacktrace,
     [{mnesia_loader,get_data,2,[{file,"mnesia_loader.erl"},{line,418}]},
      {ets,init_table,2,[{file,"ets.erl"},{line,287}]},
      {mnesia_loader,init_table,5,[{file,"mnesia_loader.erl"},{line,463}]},
      {mnesia_loader,do_init_table,8,[{file,"mnesia_loader.erl"},{line,347}]},
      {mnesia_loader,spawned_receiver,8,
          [{file,"mnesia_loader.erl"},{line,320}]}]},
 {initial_call,{mnesia_loader,spawned_receiver,8}},
 {dictionary,
     [{mnesia_table_receiver,
          {rabbit_durable_route,'rabbit@broker-rabbit-3',<6065.30894.80>}}]},
 {message_queue_len,0},
 {links,[<5167.130.0>]},
 {monitors,[]},
 {monitored_by,[]},
 {heap_size,233}]
[{pid,<5167.133.0>},
 {registered_name,[]},
 {current_stacktrace,
     [{mnesia_loader,get_data,2,[{file,"mnesia_loader.erl"},{line,418}]},
      {ets,init_table,2,[{file,"ets.erl"},{line,287}]},
      {mnesia_loader,init_table,5,[{file,"mnesia_loader.erl"},{line,463}]},
      {mnesia_loader,do_init_table,8,[{file,"mnesia_loader.erl"},{line,347}]},
      {mnesia_loader,spawned_receiver,8,
          [{file,"mnesia_loader.erl"},{line,320}]}]},
 {initial_call,{mnesia_loader,spawned_receiver,8}},
 {dictionary,
     [{mnesia_table_receiver,
          {rabbit_exchange,'rabbit@broker-rabbit-3',<6065.30895.80>}}]},
 {message_queue_len,0},
 {links,[<5167.131.0>]},
 {monitors,[]},
 {monitored_by,[]},
 {heap_size,233}]
[{pid,<5167.154.0>},
 {registered_name,[]},
 {current_stacktrace,
     [{mnesia_schema,schema_transaction,1,
          [{file,"mnesia_schema.erl"},{line,589}]},
      {mnesia_controller,try_merge_schema,3,
          [{file,"mnesia_controller.erl"},{line,495}]},
      {mnesia_controller,connect_nodes2,3,
          [{file,"mnesia_controller.erl"},{line,468}]}]},
 {initial_call,{mnesia_controller,connect_nodes2,3}},
 {dictionary,[]},
 {message_queue_len,0},
 {links,[<5167.112.0>]},
 {monitors,[]},
 {monitored_by,[]},
 {heap_size,233}]
[{pid,<5167.155.0>},
 {registered_name,[]},
 {current_stacktrace,
     [{timer,sleep,1,[{file,"timer.erl"},{line,152}]},
      {mnesia_tm,restart,9,[{file,"mnesia_tm.erl"},{line,910}]},
      {mnesia_schema,schema_coordinator,3,
          [{file,"mnesia_schema.erl"},{line,613}]}]},
 {initial_call,{mnesia_schema,schema_coordinator,3}},
 {dictionary,
     [{mnesia_activity_state,
          {mnesia,{tid,257063,<5167.155.0>},{tidstore,180276,[],1}}},
      {random_seed,{10135,4512,28635}}]},
 {message_queue_len,2},
 {links,[<5167.93.0>,<5167.63.0>]},
 {monitors,[]},
 {monitored_by,[]},
 {heap_size,2584}]
[{pid,<5167.159.0>},
 {registered_name,[]},
 {current_stacktrace,[{timer,sleep,1,[{file,"timer.erl"},{line,152}]},
                      {rabbit,await_startup,1,[]},
                      {rpc,'-handle_call_call/6-fun-0-',5,
                           [{file,"rpc.erl"},{line,203}]}]},
 {initial_call,{erlang,apply,2}},
 {dictionary,[]},
 {message_queue_len,0},
 {links,[]},
 {monitors,[]},
 {monitored_by,[<5167.12.0>]},
 {heap_size,233}]
[{pid,<5167.16862.0>},
 {registered_name,[]},
 {current_stacktrace,[{timer,sleep,1,[{file,"timer.erl"},{line,152}]},
                      {rabbit,await_startup,1,[]},
                      {rabbit,stop,0,[]},
                      {rpc,'-handle_call_call/6-fun-0-',5,
                           [{file,"rpc.erl"},{line,203}]}]},
 {initial_call,{erlang,apply,2}},
 {dictionary,[]},
 {message_queue_len,0},
 {links,[]},
 {monitors,[]},
 {monitored_by,[<5167.12.0>]},
 {heap_size,233}]
ok
```

```
There are 308680 processes.
Investigated 71612 processes this round, 5000ms to go.
Investigated 71612 processes this round, 4500ms to go.
Investigated 71612 processes this round, 4000ms to go.
Investigated 71612 processes this round, 3500ms to go.
Investigated 71612 processes this round, 3000ms to go.
Investigated 71612 processes this round, 2500ms to go.
Investigated 71612 processes this round, 2000ms to go.
Investigated 71612 processes this round, 1500ms to go.
Investigated 71612 processes this round, 1000ms to go.
Investigated 71612 processes this round, 500ms to go.
Found 71612 suspicious processes.
[{pid,<5167.224.32>},
 {registered_name,[]},
 {current_stacktrace,
     [{gen,do_call,4,[{file,"gen.erl"},{line,220}]},
      {gen_server2,call,3,[]},
      {delegate,safe_invoke,2,[]},
      {delegate,invoke,2,[]},
      {rabbit_amqqueue,notify_down_all,2,[]},
      {rabbit_channel,notify_queues,1,[]},
      {rabbit_channel,handle_method,3,[]},
      {rabbit_channel,handle_cast,2,[]}]},
 {initial_call,{proc_lib,init_p,5}},
 {dictionary,
     [{{xtype_to_module,direct},rabbit_exchange_type_direct},
      {guid_secure,{{2,'rabbit@broker-rabbit-1',#Ref<5167.0.26.14789>},0}},
      {'$ancestors',
          [<5167.220.32>,<5167.29569.8>,<5167.29564.8>,<5167.29563.8>,
           rabbit_tcp_client_sup,rabbit_sup,<5167.29262.8>]},
      {process_name,
          {rabbit_channel,
              {<<"172.16.202.54:44806 -> 172.16.202.43:5672">>,10005}}},
      {'$initial_call',{gen,init_it,6}}]},
 {message_queue_len,0},
 {links,[<5167.220.32>]},
 {monitors,[{process,<5167.227.32>},{process,<5167.227.32>}]},
 {monitored_by,[<5167.29565.8>,<5167.350.0>]},
 {heap_size,987}]
[{pid,<5167.227.32>},
 {registered_name,[]},
 {current_stacktrace,
     [{gen,do_call,4,[{file,"gen.erl"},{line,220}]},
      {gen_server2,call,3,[]},
      {worker_pool,submit,2,[]},
      {rabbit_misc,execute_mnesia_transaction,1,[]},
      {rabbit_misc,execute_mnesia_tx_with_tail,1,[]},
      {rabbit_amqqueue_process,'-terminate_delete/3-fun-1-',6,[]},
      {rabbit_amqqueue_process,terminate_shutdown,2,[]},
      {gen_server2,terminate,3,[]}]},
 {initial_call,{proc_lib,init_p,5}},
 {dictionary,
     [{{xtype_to_module,direct},rabbit_exchange_type_direct},
      {'$ancestors',
          [<5167.226.32>,rabbit_amqqueue_sup_sup,rabbit_sup,<5167.29262.8>]},
      {process_name,
          {rabbit_amqqueue_process,
              {resource,<<"/">>,queue,
                  <<"x-XXXXXXXXX-46988812436287695-4763366">>}}},
      {'$initial_call',{gen,init_it,6}},
      {guid,{{1148547460,2891436549,1800794511,3716827883},0}}]},
 {message_queue_len,0},
 {links,[<5167.226.32>]},
 {monitors,[{process,<5167.29319.8>}]},
 {monitored_by,[<5167.29316.8>,<5167.29389.8>,<5167.224.32>,<5167.224.32>]},
 {heap_size,2584}]
[{pid,<5167.312.32>},
 {registered_name,[]},
 {current_stacktrace,
     [{gen,do_call,4,[{file,"gen.erl"},{line,220}]},
      {gen_server2,call,3,[]},
      {delegate,safe_invoke,2,[]},
      {delegate,invoke,2,[]},
      {rabbit_amqqueue,notify_down_all,2,[]},
      {rabbit_channel,notify_queues,1,[]},
      {rabbit_channel,handle_method,3,[]},
      {rabbit_channel,handle_cast,2,[]}]},
 {initial_call,{proc_lib,init_p,5}},
 {dictionary,
     [{{xtype_to_module,direct},rabbit_exchange_type_direct},
      {guid_secure,{{2,'rabbit@broker-rabbit-1',#Ref<5167.0.26.15542>},0}},
      {'$ancestors',
          [<5167.309.32>,<5167.29569.8>,<5167.29564.8>,<5167.29563.8>,
           rabbit_tcp_client_sup,rabbit_sup,<5167.29262.8>]},
      {process_name,
          {rabbit_channel,
              {<<"172.16.202.54:44806 -> 172.16.202.43:5672">>,15360}}},
      {'$initial_call',{gen,init_it,6}}]},
 {message_queue_len,0},
 {links,[<5167.309.32>]},
 {monitors,[{process,<5167.315.32>},{process,<5167.315.32>}]},
 {monitored_by,[<5167.29565.8>,<5167.350.0>]},
 {heap_size,987}]
[{pid,<5167.315.32>},
 {registered_name,[]},
 {current_stacktrace,
     [{gen,do_call,4,[{file,"gen.erl"},{line,220}]},
      {gen_server2,call,3,[]},
      {worker_pool,submit,2,[]},
      {rabbit_misc,execute_mnesia_transaction,1,[]},
      {rabbit_misc,execute_mnesia_tx_with_tail,1,[]},
      {rabbit_amqqueue_process,'-terminate_delete/3-fun-1-',6,[]},
      {rabbit_amqqueue_process,terminate_shutdown,2,[]},
      {gen_server2,terminate,3,[]}]},
 {initial_call,{proc_lib,init_p,5}},
 {dictionary,
     [{{xtype_to_module,direct},rabbit_exchange_type_direct},
      {'$ancestors',
          [<5167.314.32>,rabbit_amqqueue_sup_sup,rabbit_sup,<5167.29262.8>]},
      {process_name,
          {rabbit_amqqueue_process,
              {resource,<<"/">>,queue,
                  <<"x-XXXXXXXXX-46989284943025741-8824305">>}}},
      {'$initial_call',{gen,init_it,6}},
      {guid,{{2019276774,43890767,2109865596,3282221493},0}}]},
 {message_queue_len,0},
 {links,[<5167.314.32>]},
 {monitors,[{process,<5167.29319.8>}]},
 {monitored_by,[<5167.29316.8>,<5167.29389.8>,<5167.312.32>,<5167.312.32>]},
 {heap_size,2584}]
[{pid,<5167.384.32>},
 {registered_name,[]},
 {current_stacktrace,
     [{gen,do_call,4,[{file,"gen.erl"},{line,220}]},
      {gen_server2,call,3,[]},
      {delegate,safe_invoke,2,[]},
      {delegate,invoke,2,[]},
      {rabbit_amqqueue,notify_down_all,2,[]},
      {rabbit_channel,notify_queues,1,[]},
      {rabbit_channel,handle_method,3,[]},
      {rabbit_channel,handle_cast,2,[]}]},
 {initial_call,{proc_lib,init_p,5}},
 {dictionary,
     [{{xtype_to_module,direct},rabbit_exchange_type_direct},
      {guid_secure,{{2,'rabbit@broker-rabbit-1',#Ref<5167.0.26.16163>},0}},
      {'$ancestors',
          [<5167.381.32>,<5167.29569.8>,<5167.29564.8>,<5167.29563.8>,
           rabbit_tcp_client_sup,rabbit_sup,<5167.29262.8>]},
      {process_name,
          {rabbit_channel,
              {<<"172.16.202.54:44806 -> 172.16.202.43:5672">>,5501}}},
      {'$initial_call',{gen,init_it,6}}]},
 {message_queue_len,0},
 {links,[<5167.381.32>]},
 {monitors,[{process,<5167.387.32>},{process,<5167.387.32>}]},
 {monitored_by,[<5167.29565.8>,<5167.350.0>]},
 {heap_size,987}]
```

**Comment by michaelklishin** [comment]
We've evaluated this and the real issue lies in `delegate:call/2` which has the timeout of infinity. All its callers I could find are in the `rabbit_amqqueue` module, so we can introduce `delegate:call/3` and apply timeouts on a case-by-case basis.

Ideally to propagate the specific timeout reason to the client, we'd need to introduce a new protocol status code that would mean "a timeout has occurred".

**Comment by spatula75** [comment]
Just to throw an idea out: would there be any value in the additional complexity of a timeout/retry mechanism in the event of a transient failure?  In the Amazon EC2 world, this is probably the most common troublemaking scenario we experience-- short failures that last maybe a few seconds, but which are enough to cause chaos.

One could just as easily argue it would be better to kick it back up to the client and let it decide if a retry is warranted, of course.

**Comment by michaelklishin** [comment]
Naive retries can break more things than they'd fix. Using Raft (and thus having an actual replicated log of operations) is the right solution.

**Comment by binarin** [comment]
Maybe in this particular case of `rabbit_amqqueue:notify_down_all/2` it will be easier to switch to `delegate:cast/2`? Or is there a reason for doing this notification synchronously?

**Comment by michaelklishin** [comment]
Publisher confirms are sent only after a message has been replicated. Using casts at least makes this significantly trickier, turning parts of the system to AP earlier than we intend to do so. Calls are fine as long as they have a sensible timeout.

**Comment by binarin** [comment]
Btw, adding timeout will help, but underlying issue will still be there.

Because the problem is not the absence of timeout, but the fact that a queue process became stuck in some infinite loop or in some receive.

It's not about down/unreachable nodes or unexpectedly terminated queue processes, as this cases are actually handled by `delegate:call/2` (which has `gen_server2:multi_call` underneath) - `erlang:monitor/2` is extensively used there.

**Comment by michaelklishin** [comment]
@binarin I'm not sure how using a cast would solve what you consider the root cause. This issue is about having timeouts and evaluating what kind of unforeseen side-effects that might bring.

**Comment by binarin** [comment]
I mentioned root cause just as a side note.
When looking into a case of a channel hanged on `delegate:call/2` I've noticed that it has monitors to some queue processes and those queue processes weren't emptying their inboxes. So if this behaviour of queues could be fixed there will be no need to add any timeouts to `notify_down_all`.

**Comment by michaelklishin** [comment]
The above assumes nothing can go wrong with a cross-node call. I wouldn't be so optimistic. Not having timeouts is an opinionated idea that has been proven to be wrong over and over in RabbitMQ history.

We are investigating a couple of things that block processes, e.g. #581, too. Regardless of what we find and fix elsewhere, calls must use a sensible timeout.

**Comment by binarin** [comment]
This optimism is based on `erlang:monitor/2`, which should detect all problems with remote node/process. And `gen_server`, which should correctly use those monitors. Not trusting this mechanisms while writing distributed Erlang code will lead one to insanity )

**Comment by michaelklishin** [comment]
We've been hearing this exact argument for a good couple of years. What happens in practice is that when a queue/node/entire cluster lock up, technical ops never inspect things to provide us any info. They kill things left and right to make things functional again. If anything, having a sane finite timeout would serve as a circuit breaker.

After discussing this with @Ayanda-D we decided to use a value of `net_ticktime` + 10 seconds. This way `DOWN` messages have a good chance of being handled first but channels, and, in turn, connections and possibly entire nodes (e.g. during shutdown) do not lock up completely.

**Comment by Ayanda-D** [comment]
> Ideally to propagate the specific timeout reason to the client, we'd need to introduce a new protocol status code that would mean "a timeout has occurred".

Some suggestions with regards to what error we propagate back to the client. I think we have two options here;

1. Introduce a distinct timeout reason to return to the client as @michaelklishin suggests.  
2. Or, we could classify timeout exceptions as [benign exits](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_misc.erl#L77). 

The latter would mean that delegate timeouts triggered by AMQP calls would result in either `not_found` or `absent` errors being returned to the client, depending on whether the queue is in the db that is. & note, all channel calls in question here eventually call `rabbit_misc:with_exit_handler`.

What'd you guys think?

**Comment by Ayanda-D** [comment]
& another thing, @michaelklishin, i think our idea of caching `channel_operation_timeout` in the channel's process dictionary will only work if we're 100% certain that all functions in `rabbit_amqqueue`, which will be accessing timeout from this dictionary entry, will only be from channels. 

I'm now concerned with the initial idea, seeing that `rabbit_amqqueue` is not exclusive to any process, and can be used by anyone/anywhere. Otherwise we'll have to make do with accessing the timeout from application controller on every channel call :(

**Comment by michaelklishin** [comment]
A more thorough call sites inspection suggests that `delegate:call/2` is not used on the critical path (maybe in request/response heavy systems):

 * `queue.delete`
 * stats emission
 * `queue.purge`
 * message re-queueing
 * `basic.get` (the closest it gets to the critical path)
 * `basic.consume`
 * `basic.cancel`
 * Manual mirror sync and sync cancellation

`basic.deliver`, `basic.ack`, `basic.reject`, and QoS settings changes use `delegate:cast/2`. Therefore it should be fine to load the timeout from application config.

**Comment by Ayanda-D** [comment]
@michaelklishin okay cool. if performance won't be compromised, then its okay. thanks for that.

**Comment by binarin** [comment]
@michaelklishin, I still think you're putting wrong emphasis on cross-node calls. Timeouts are indeed needed. But they are needed to alleviate results of bad processes behaviour (**BOTH** remote and local).

Same as for #62 - if timeouts will be added only to cross-node calls, it will not help.

Adding timeouts has nothing to do with remote node failures. And so it doesn't make sense to calculate timeout from value of `net_ticktime`. Suppose we have scenario where we pass to `delegate:call/2` 200 pids: 100 for local processes and 100 for processes on single remote node. So in worst case this `delegate:call/2` will return in approx `200*net_ticktime` seconds - just some value that doesn't have any meaningful connection to real world.

And then there is a problem that remote delegate process could become stuck itself (e.g. because it was handed bad batch of work). So `multi_call` at https://github.com/rabbitmq/rabbitmq-server/blob/master/src/delegate.erl#L119 should also has some sort of sensible timeout - but definitely not proportional to `net_ticktime` :smile: 

Another possible fix that'll improve system responsiveness and will prevent delegate processes from becoming stuck is spawn new process for every request at https://github.com/rabbitmq/rabbitmq-server/blob/master/src/delegate.erl#L217

**Comment by michaelklishin** [comment]
We don't argue with the fact that there are other issues that are simply revealed by this problem. In fact, in the last week we've discovered at least 3 of them, resolved in #581, #541 (we have a partial fix on a branch for `rabbit_channel_sup`), and more. Some are the consequences of a known `mnesia_locker` bug(s).

But this needs to be addressed as well.

**Comment by Ayanda-D** [comment]
See implementation of delegate timeouts, thus far, along with [rabbitmq-common/rabbitmq-server-248](https://github.com/rabbitmq/rabbitmq-common/tree/rabbitmq-server-248).  Any feedback welcome.

**Comment by Ayanda-D** [comment]
Seperating this issue from #166. Some concerns regarding end-to-end side effects on service, when delegates do timeout. Changes for delegate timeouts to be added as part of #166, as an ongoing feature with more analysis and tests of potential side effects to continue. 

Focusing this issue only on timing out when `rabbit_amqqueue:notify_down_all/2` is called by the channel (as initially planned).

**Comment by michaelklishin** [comment]
This specific issue is fixed. Closely related: #166.

**Comment by dumbbell** [comment]
@Ayanda-D: The `channel_operation_timeout:notify_down_all()` test case fails with the following output:
```
channel_operation_timeout
-------------------------
notify_down_all: [setup] [running]rabbit_test_runner: make_test_multi...*failed*
in function gen_server:call/3 (gen_server.erl, line 212)
in call from channel_operation_timeout:notify_down_all/1 (test/src/channel_operation_timeout.erl, line 59)
in call from rabbit_test_runner:'-make_test_multi/7-fun-2-'/3 (src/rabbit_test_runner.erl, line 143)
**exit:{{shutdown,
     {connection_closing,{server_initiated_close,541,<<"INTERNAL_ERROR">>}}},
 {gen_server,call,[<0.93.0>,{close,200,<<"Goodbye">>},infinity]}}
  output:<<"">>
```

Line 59 of `test/src/channel_operation_timeout.erl` is:
```erlang
amqp_channel:close(HareCh),
```

It fails to close the channel because the channel process crashes here (in `rabbit_channel.erl`, line 898):
```erlang
handle_method(#'channel.close'{}, _, State = #ch{reader_pid = ReaderPid}) ->
    {ok, State1} = notify_queues(State),
```

`notify_queues()` returns the following error, which causes a `badmatch` exception:
```erlang
{{error,{channel_operation_timeout,5000}}, ...}
```

The exception causes the channel process to be terminated and, as a consequence, the call from `amqp_channel` to be aborted with an exception (not caught by the test case).

I don't know what is the best solution here: either handling the error returned by `notify_queues()` or handled the exception in the test case. I think I prefer the second one (ie. let the channel process terminates with a server error). What do you think?

**Comment by Ayanda-D** [comment]
@dumbbell oh, I see the change which addressing this was reverted https://github.com/rabbitmq/rabbitmq-common/commit/02752f1c4c0b3f9226c30ad2811e01d24f481a36. Okay, we'll keep the channel state update in `notify_queues/1` then, and only remove the strict match in `#'channel.close'` handler :)

**Comment by dumbbell** [comment]
Thank you! I confirm the test passes now.
