### ISSUE TITLE
rabbitmq-priority-queue - Java client

### ISSUE THREAD

**Issue by abuqura** [rabbitmq/rabbitmq-server#249]
Hello,
I am trying to use the "rabbitmq-priority-queue" - Java client, its work only in special cases:
1-When the consumer runs after the queue has the messages then will take them in prioritized way.
2-When close the channel connection after every message the consumer takes the messages in prioritized way from the queue.

My question is:
Is there a solution to get messages in prioritized way while the consumer is running and without closing the connection after every message (lazy connection)?

**Comment by michaelklishin** [comment]
This [was answered](https://groups.google.com/d/msg/rabbitmq-users/oWr8wA2FG9k/nLIrmiFwCgAJ) on `rabbitmq-users` — please use the list for questions.

Messages that never go to the message store (can be delivered to a consumer immediately) are not prioritised. This is [documented](http://www.rabbitmq.com/priority.html).
