### ISSUE TITLE
Binding arguments are exported as blank

### ISSUE THREAD

**Issue by shark300** [rabbitmq/rabbitmq-server#2500]
* RabbitMQ version: 3.8.9
* Erlang version: 23.1.2
* RabbitMQ server and client application log files:
There is no log relevant message.
* A runnable code sample, terminal transcript or detailed set of
  instructions that can be used to reproduce the issue
```bash
rabbitmqctl export_definitions C:\Temp\definitions.file.json
```
* RabbitMQ plugin information via `rabbitmq-plugins list`
  * rabbitmq_management
  * rabbitmq_web_dispatch
  * rabbitmq_management_agent
* Client library version (for all libraries used)
* Operating system, version, and patch level
  * Windows

![image](https://user-images.githubusercontent.com/1255546/98726632-112b0d00-2397-11eb-96b6-990aba41a19f.png)

I've tried to export configurations of this node, but the export does not contain any arguments regarding to headers exchange. Due to this one, I can not import this export file without any modifications on another node.

**Comment by lukebakken** [comment]
Please provide a script or commands we can run to create an environment that matches yours. Ideally, HTTP API calls using `curl` or `rabbitmqadmin` would be used. Thank you.

**Comment by shark300** [comment]
@lukebakken 
Yes, sure.

```bash
curl -i -u guest:guest -H "content-type:application/json" -XPUT http://localhost:15672/api/vhosts/foo
curl -i -u guest:guest -H "content-type:application/json" -XPUT -d"{""type"":""headers"",""durable"":true}" http://localhost:15672/api/exchanges/foo/sample.ex
curl -i -u guest:guest -H "content-type:application/json" -XPUT -d"{""durable"":true, ""arguments"":{""x-queue-type"":""classic""}}" http://localhost:15672/api/queues/foo/sample.q
curl -i -u guest:guest -H "content-type:application/json" -XPOST -d"{""arguments"":{""type"":""form"",""subtype"":""validation""}}" http://localhost:15672/api/bindings/foo/e/sample.ex/q/sample.q
```

And exported file is: 
[definitions.file.json.zip](https://github.com/rabbitmq/rabbitmq-server/files/5520846/definitions.file.json.zip)

**Comment by michaelklishin** [comment]
This seems legit:

```
rabbitmqctl list_bindings
# => Listing bindings for vhost /...
# => source_name	source_kind	destination_name	destination_kind	routing_key	arguments
# => 	exchange	cq.1	queue	cq.1	[]
# => hx	exchange	cq.1	queue		[{"subtype","validation"},{"type","form"}]
```

While the definition output contains

``` json
  "bindings": [
    {
      "arguments": {},
      "destination": "cq.1",
      "destination_type": "queue",
      "routing_key": "",
      "source": "hx",
      "vhost": "/"
    }
```

**Comment by michaelklishin** [comment]
It was a pretty trivial fix that we previously had to do for exchange and queue arguments. The result is

``` json
  "bindings": [
    {
      "arguments": {
        "subtype": "validation",
        "type": "form"
      },
      "destination": "cq.1",
      "destination_type": "queue",
      "routing_key": "",
      "source": "hx",
      "vhost": "/"
    }
  ]
```

**Comment by shark300** [comment]
Thank you!
