### ISSUE TITLE
Prometheus: expose a metric for network partition observed on the node

### ISSUE THREAD

**Issue by Artimi** [rabbitmq/rabbitmq-server#2508]
Hi,
I'm happy that RabbitMQ got its own Prometheus exporter. :+1: also for prepared Grafana dashboard, it looks great.
I was using [deadtrickster prometheus rabbitmq exporter](https://github.com/deadtrickster/prometheus_rabbitmq_exporter) before. It allowed me to monitor network partition with its `rabbitmq_node_up` metric https://github.com/deadtrickster/prometheus_rabbitmq_exporter#nodes because it shows whether one node is connected to another. I have three nodes in my cluster for now and thus I can write an alert
```
sum(rabbitmq_node_up{app="rabbitmq"}) != 9
```
To check that each RabbitMQ node is connected to the other two. When it is not I'm alerted. Would it be possible to add something similar to this plugin?

**Comment by ggustafsson** [comment]
Is someone looking at this? We have been bitten by this a few times at work now so I would really like to see this being implemented. I wanted to fix this myself but after having looked at the code I quickly realized that there is just no way I could do this in a reasonable time because I have no prior knowledge of Erlang. Any help would be greatly appreciated!

**Comment by michaelklishin** [comment]
Those who need this metric are welcome to look into it. Since this is a piece of node-local state, it can be a list of nodes the reporting node sees as disconnected. Visualising and alerting this would be easier if this list was checked for emptiness but for extra context, this should be reported as a list of [observed as] unavailable peers.

**Comment by frittentheke** [comment]
I just had a RabbitMQ node of a three node cluster split of into a partition. The management interface reported:

> Network partition detected
> Mnesia reports that this RabbitMQ cluster has experienced a network partition. There is a risk of losing data. Please read https://www.rabbitmq.com/partitions.html

also so did the rabbitmqctl cluster_status:

> Network Partitions
> Node rabbit@node1 cannot communicate with rabbit@node2, rabbit@node3                              


I have all dashboards available but was unable to spot any indication of this partitioning.
When searching through this repo to find the proper metric to be alerted on, I found this issue.


Am I reading this correctly, that there is currently no metric available that would have allowed be to be alerted on such a massive disruption in the RabbitMQ clustering?

**Comment by gomoripeti** [comment]
I am happy to have a look.
If I see it correctly prometheus does not support list of strings as values.
would the following format be acceptable:
`rabbitmq_partitioned{from="rabbit@<host>"} 1` for each element in the partitions list

If there is no netsplit, no such metric is returned
Alarm could be configured for something like `sum(rabbitmq_partitioned) > 0`

**Comment by ggustafsson** [comment]
> I am happy to have a look. If I see it correctly prometheus does not support list of strings as values. would the following format be acceptable: `rabbitmq_partitioned{from="rabbit@<host>"} 1` for each element in the partitions list
> 
> If there is no netsplit, no such metric is returned Alarm could be configured for something like `sum(rabbitmq_partitioned) > 0`

That looks perfect to me! Defintely something that should be added to the Grafana dashboard afterwards.

**Comment by michaelklishin** [comment]
#9465 introduces a very similar metric that should be enough, and will be forward compatible with 3.13 and 4.0: the number of unreachable cluster peers.

E.g. with three nodes running in a cluster of five, or with two nodes disconnected from peers you'd get

```
# TYPE rabbitmq_unreachable_cluster_peers_count gauge
# HELP rabbitmq_unreachable_cluster_peers_count Number of peers in the cluster the current node cannot reach.
rabbitmq_unreachable_cluster_peers_count 2
```

**Comment by michaelklishin** [comment]
It is sufficient to determine whether or not there is a partition. Obviously this is a per-node metric that must be monitored on all nodes.

There isn't a magical metric not derived from intractable peer count that would work better. Ask yourself how do you determine if a node has lost its connection to any peers. Voilà, that's exactly what we offer as a per-node metric.

**Comment by michaelklishin** [comment]
Our team has no plans to go back to the way partitions were reported in the "pre-Prometheus" era.

This metric is per node and not per cluster, but so are all Prometheus metrics in general for a fairly obvious reason. These metrics allow you to detect a partition for alerting or Grafana visualization purposes. Time to move on from trying to convince the core team that somehow the old metric was superior. It was not and it does not fit the Prometheus scraping approach where each node only reports its own metrics.
