### ISSUE TITLE
Expose a metric that reports mirrored queues which do not have any synchronized mirrors

### ISSUE THREAD

**Issue by MarcialRosales** [rabbitmq/rabbitmq-server#2510]
# Motivation

Customers who chose not to manually synchronize their mirror queues wished to know when they are at risk of loosing all the data should the master crashed with all slaves unsynchronized. 

Customers would like to know which/how-many mirrored queues do not have any fully synchronized slaves to failover. Today this information is somehow available via the management api but not as metric. Customers have to calculate it based on `slaves_nodes` and `synchronised_slave_nodes` json attributes of a queue. 

Ideally, they would want to know how many messages are missing in the slaves so that they can trigger a manual synchronization when the delta is over certain threshold. I would imagine the delta would be the best delta, i.e. the delta from the most up-to-date queue. But this has certainly less priority than having metric that tells us which queues have no synchronized slaves.

**Comment by ansd** [comment]
Mirrored classic queues got removed in RabbitMQ 4.0.
