### ISSUE TITLE
Retry EC2 API endpoint requests up to N times

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#2529]
Suggested by @dimmy-timmy [on the mailing list](https://groups.google.com/forum/#!topic/rabbitmq-users/7xcssx5pXqU).

Currently EC2 API requests such as `DescribeInstances` are not retried. If they fail (and sometimes they do), so will peer discovery. We should retry up to N times with a reasonably short delay (a few seconds?)

**Comment by fiksn** [comment]
Is this issue still relevant? My thoughts were that after https://github.com/rabbitmq/rabbitmq-peer-discovery-aws/commit/d4fa517cd3b376d9017d41e970ee2a3d7146ecbf this should be fixed or am I mistaken? Or actually https://github.com/rabbitmq/rabbitmq-server/commit/437df60292104230a2df36b819dcebd71617a157 in this repository which should correspond to 3.8.10+ RabbitMQ. 

We are also experiencing this issue with 3.8.3 and now I am just wondering whether we should upgrade to a more recent version immediately or wait for this to get closed (if there is perhaps a seperate problem causing the same symptoms).
