### ISSUE TITLE
Allow configuration of which field retrieves the user name

### ISSUE THREAD

**Issue by morsok** [rabbitmq/rabbitmq-server#2548]
Hello,

When trying to integrate RabbitMQ with this plugin and Azure Active Directory we had an insurmountable issue, we found out in the code that we were able to define an additional field to retrieve permission scopes (would be nice to add that to the doc, very useful feature !), but it seems the plugin will always look for the client_id field to retrieve the username and deems invalid the token if the field is not there.

Currently, we cannot have this field with Azure AD, however, there is similar fields with the same information, so I am creating this issue to enquire if you would accept to make this a configuration option with a default value to 'client_id'?

**Comment by ngbrown** [comment]
The OAuth plugin currently falls back from `client_id` to `sub` then to the passed `Username`.

See: https://github.com/rabbitmq/rabbitmq-server/blob/bea9306ff99ad8cc13e3620121d24b35cdf0802b/deps/rabbitmq_auth_backend_oauth2/src/rabbit_auth_backend_oauth2.erl#L280-L297

So far, I have been able to configure the `scope` field in AAD and that did work.

After modding the plugin, I could then configure the plugin to use the `scope` field. There seems to be a general confusion between `extra_scopes_source`, `additional_rabbitmq_scopes`, and `additional_scopes_key` in the plugin. I'll open a separate issue for that.

```ini
auth_backends.1 = rabbit_auth_backend_internal
auth_backends.2 = rabbit_auth_backend_oauth2
auth_oauth2.resource_server_id = api://YOUR_GENERATED_GUID
auth_oauth2.jwks_url = https://login.microsoftonline.com/common/discovery/keys
auth_oauth2.additional_scopes_key = roles
```

**Comment by michaelklishin** [comment]
#4103 is highly relevant here.

**Comment by MarcialRosales** [comment]
This issue is addressed by this [PR](https://github.com/rabbitmq/rabbitmq-server/pull/6015) . We are now able to tell which token's claim or attribute carries the username . @michaelklishin

**Comment by michaelklishin** [comment]
#6015 for visibility
