### ISSUE TITLE
Evaluate what settings can be exposed using new style configuration

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#2549]
See rabbitmq/rabbitmq-auth-backend-oauth2#46 for the background. We likely can support some basic settings in new style configuration format. This issue is about evaluating what can be exposed and whether this would make much sense (actually simplify configuration).

**Comment by Radiergummi** [comment]
In case someone is going to look into this: I'm currently struggling to configure the [preferred username claims]() in the new style configuration format. It isn't clear from the documentation how I can pass multiple values to `auth_oauth2.preferred_username_claims` - I tried the dictionary structure:
```ini
auth_oauth2.preferred_username_claims.1 = "name"
auth_oauth2.preferred_username_claims.2 = "email"
```
...but that yielded an error I didn't expect:
```
You've tried to set auth_oauth2.preferred_username_claims.1, but there is no setting with that name.
```

Is it supposed to be the following?
```

**Comment by michaelklishin** [comment]
@Radiergummi please use GitHub Discussions for questions.

**Comment by michaelklishin** [comment]
According to [the schema of the OAuth 2 plugin](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_auth_backend_oauth2/priv/schema/rabbitmq_auth_backend_oauth2.schema#L70-L73), `auth_oauth2.preferred_username_claims` is expected to be a string.

The [README](https://github.com/rabbitmq/rabbitmq-server/blob/2faaad40f871e01069580250d760ceafb2631365/deps/rabbitmq_auth_backend_oauth2/README.md?plain=1#L215) has to be updated.

**Comment by michaelklishin** [comment]
@MarcialRosales I assume this is due to the OAuth 2 IDP changes from the last couple of months?

**Comment by michaelklishin** [comment]
@MarcialRosales has confirmed it to me that the new style config value has to be updated. Its underlying advanced config value had been changed to be a list at some point but the `rabbitmq.conf` config schema had not.

**Comment by MarcialRosales** [comment]
@michaelklishin I think we can close this issue given that every single setting available in the old style is also available in the new style. Unless we want to make this issue extensible to other plugins not only oauth2 backend.
