### ISSUE TITLE
Extra parameters in resource access requests

### ISSUE THREAD

**Issue by folt** [rabbitmq/rabbitmq-server#2552]
I build the server part with the participation of this module. I was faced with the fact that the client (java) that third-party developers are building declares queues with additional parameters which should not be. Is it possible to add to the request body any additional arguments that were used to declare the queue/exchanger ?

`POST
/resource_path/
{
username: root,
...
arguments: [
x-message-ttl: 1000,
.....
]
}`

To solve this problem, I now use a proxy that modifies the request and displays the values I need, but this is not the best solution.

**Comment by michaelklishin** [comment]
There hasn't been much interest in this => closing.
