### ISSUE TITLE
MQTT v5.0 support

### ISSUE THREAD

**Issue by wrsrap** [rabbitmq/rabbitmq-server#2554]
Are there plans to support MQTT v5.0 in this plugin？Thank you.

**Comment by petersilva** [comment]
in case it is helpful, the feature that most interests me is shared queues.   with AMQP 0.9 you just have multiple processes connect to the same queue to do sharing.  with MQTTv3, only one consumer at a time.  there is a concept of shared queues that promises to address that.  Very interested in that feature in particular.

**Comment by michaelklishin** [comment]
That will be provided by streams in 3.9.

**Comment by petersilva** [comment]
No need for new features on the rabbit side.  The existing sharing of queues (has been there last ten years or so) is fine... I just have multiple subscribers connect to the same queue with a prefetch, and I can have 40 subscribers share a high speed queue (that does not build up.)  I don't see a way to do that with MQTTv3.  I think v5 might help.

**Comment by adiroiban** [comment]
For the reference, a document with differences between v3.1.1 and v5 - https://github.com/mqtt/mqtt.org/wiki/Differences-between-3.1.1-and-5.0

**Comment by briggySmalls** [comment]
For me a big appeal of v5.0 is the "Reason code on all ACKs" (in same link as @adiroiban).

If a client attempts to publish/subscribe to a topic that an ACL denies them, the MQTT 3.x specs silently accept the operation. MQTT 5.x introduces the return code for "Not authorised".

**Comment by petersilva** [comment]
What would be really cool for v5 support:
   -- map each topic exchange to the root of mqtt topic tree.
   -- prepend with $share/queue_name/exchange/ .... rest of the topics.

If the exchange is not a topic exchange, it does not participate in the mapping.
That way, people can connect to the same broker with either protocol and access the entire broker.

example:

I want five processes to use the same queue "worker" bind to  "canada.public" topic on the "xwarnings" exchange  in AMQP sharing the messages among the five.  That should be equivalent to subscribing to "$share/worker/xwarnings/canada.public" in MQTT plugin.

**Comment by petersilva** [comment]
fwiw... I use this mapping here:
https://github.com/MetPX/sarracenia/tree/v03_wip/sarracenia/moth

There are MQTT and AMQP sub-classes of the "Messages Organized by Topic Header" I use mosquitto for the MQTT stuff, because the rabbitmq isn't rich enough currently.

**Comment by BastianMattes** [comment]
Any updates on when MQTT 5 will be supported? Do you have a roadmap somewhere on planned features?

**Comment by lukebakken** [comment]
Anyone asking about MQTT 5.0 support should read @michaelklishin 's comment ([link](https://github.com/rabbitmq/rabbitmq-server/issues/2554#issuecomment-617485816)):

> It is still scheduled to be implemented but we offer no ETA as there are too many higher priority items on our roadmap. This is open source software so those who need MQTT v5.0 support can contribute it, or at the very least document all the differences from 3.1.1 which would greatly help with assessing the amount of work it would take.

Note that there is _useful work_ that people could do that would speed the process up yet we have not yet received assistance from the community.

**Comment by BastianMattes** [comment]
This reads like this project is understaffed. That's important to know if you need to decide between different MQTT brokers. Thanks for the honest answer, @lukebakken !

**Comment by BastianMattes** [comment]
@yaronp68 Thank you for asking, but we don't plan to have any AMQP clients, so if we were to use another MQTT broker, there would be no need for us to have a bridge to RabbitMQ since we wouldn't need RabbitMQ anymore at all.

**Comment by tsturzl** [comment]
@BastianMattes You're not paying for a support license, and there's not enough interest in this feature. AFAIK you can pay for commercial support for RabbitMQ: https://tanzu.vmware.com/rabbitmq

The idea that RabbitMQ is run by a skeleton crew is kind of silly. The reality is you're either banking on the free time of contributors to implement a niche feature, or you're hoping a company will implement it, but you're not paying that company. If this had more interest it might get done faster, but as far as message queues that also support MQTT they basically all only support v3.1.1. You can go pay for HiveMQ or use the community version of VerneMQ if you're really really sure MQTTv5 actually provides all the features you need.

**Comment by BastianMattes** [comment]
Thanks for the suggestion, @tsturzl , we will consider this in the future.

**Comment by couling** [comment]
For those of us not familiar with the project, is there a comment on why this issue was closed besides being open for a long time with little progress?

Has it now been deemed that rabbitmq will never support MQTT5?

**Comment by michaelklishin** [comment]
Before RabbitMQ supports MQTTv5 we decied to significantly optimize the MQTTv3.1 implementation we have. Chances are, MQTTv5 can ship around the 3.12 time frame, and hopefully it will be in the open source edition (the core team cannot guarantee that).

**Comment by lukebakken** [comment]
#5895 is a prerequisite for MQTT 5.0 support.

**Comment by lukebakken** [comment]
@t03apt @feixuenihaoma @liamdiprose @yyyyeeeeesss @ramlongcat @hiepthai @gogangipark @andrew-kratik @An0nymous0 @lazystone @msallin @siaron @lddhappy @monkalways @niburhsoj @alaendle @fungiboletus @lhoste-bell @zaksnet @jonaskello @phaseOne @maxlein @BastianMattes @paulojoao @nouzun @damikun @Daschi1 @couling @tsturzl @petersilva @briggySmalls @adiroiban @An0nymous0 @ajayb0507 


Hello! Everyone who has asked "When will RabbitMQ support MQTT 5" or thumbed-up this issue, *PLEASE* take the time to test this new feature. It's the _least_ you can do! The following docker image contains the code in PR #7263 -

```
pivotalrabbitmq/rabbitmq:mqtt5-otp-max-bazel
```

**Comment by alaendle** [comment]
@lukebakken - Thanks for pinging us; I'm currently testing MQTT5 support. Looks all good to me - connect with userproperties; publish with userproperties; qos 0/1 - maybe one small improvement idea: is it possible to somehow show the connect userproperties in the management UI? I would have expected to see them below "Client properties"
![grafik](https://github.com/rabbitmq/rabbitmq-server/assets/969523/8314bc35-0877-4be2-b2d3-faf7e69603c5)

**Comment by ansd** [comment]
Thank you @alaendle for testing MQTT 5 and your feedback.
I like your idea and implemented it in https://github.com/rabbitmq/rabbitmq-server/pull/8681.

**Comment by couling** [comment]
@lukebakken Is the shovel plugin not working in this image? Our setup for MQTT has an edge/extranet broker with shovel to/from a core broker. For me to stress test this I'd need that working, but I'm just getting `Shovel 'Dispatch Instructions' could not connect to source` when I try.

**Comment by ansd** [comment]
When testing MQTT 5, please start using docker image `pivotalrabbitmq/rabbitmq:main-otp-max-bazel` since PR https://github.com/rabbitmq/rabbitmq-server/pull/7263 was merged into `main` branch. (I updated Luke's comment above).

@couling the shovel plugin is supposed to work in this image. The plugin is disabled by default, but you can enable it. The error message you pasted does not provide useful information: I added the error reason to the log in https://github.com/rabbitmq/rabbitmq-server/pull/8686
If you think that the [MQTT 5 PR](https://github.com/rabbitmq/rabbitmq-server/pull/7263) broker the shovel plugin (I would be surprised if it did), please provide us reproducible steps including all config files (ideally create a separate GitHub repo with reproduction steps).

**Comment by michaelklishin** [comment]
> @lukebakken Is the shovel plugin not working in this image? Our setup for MQTT has an edge/extranet broker with shovel to/from a core broker. For me to stress test this I'd need that working, but I'm just getting `Shovel 'Dispatch Instructions' could not connect to source` when I try. Note I've basically dropped this in place of an existing instance with the same config, so this shouldn't be subject to firewall issues etc.

We will not allow this thread to be hijacked to troubleshoot Shovels. Use [Troubleshooting Networking](https://rabbitmq.com/troubleshooting-networking.html), collect logs on both sides, and if TLS is used, [Troubleshooting TLS](https://rabbitmq.com/troubleshooting-networking.html). If you find something you cannot explain, start a new discussion.

**Comment by couling** [comment]
@michaelklishin apologies, I wasn't looking for general troubleshooting only pointing out that the provided docker image provided here doesn't seem to work in a way I can test MQTT5 in a way that's meaningful to me.

**Comment by alaendle** [comment]
@lukebakken - also the "standard" mqtt library for JS doesn't seem to be compatible with RabbitMQ (from my perspective due to a bug in mqtt.js https://github.com/mqttjs/mqtt-packet/issues/92). However other broker seem to be more reluctant to protocol violation.

**Comment by alaendle** [comment]
@ansd - And many thanks for implementing my suggestion ❤️ - things now show up as expected:
![grafik](https://github.com/rabbitmq/rabbitmq-server/assets/969523/fa37fd3a-d99d-435d-9d54-d2a2a19092b2)

**Comment by ansd** [comment]
Thanks for your feedback @alaendle 🎉
https://github.com/rabbitmq/rabbitmq-server/pull/8752 fixes this issue.

**Comment by ansd** [comment]
MQTT 5.0 blog post:
https://blog.rabbitmq.com/posts/2023/07/mqtt5

**Comment by petersilva** [comment]
Fantastic Progress! I can't use it... as my usage requires shared subscriptions which the announcement says is deferred.  I already described a mapping earlier in the thread that should make it straight-forward, as far as I can tell...  map shared subscription group names to AMQP queue names, and everything should "just work." 

Still pleased to hear of the progress.
