### ISSUE TITLE
Gracefully handle more connection termination cases

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#2555]
In a pretty varied range of scenarios we see that the "[let it crash](https://learnyousomeerlang.com/errors-and-exceptions)" philosophy, while does its job of continued service for future client connections and simplifying the code to a certain extent, causes users to freak out and either
ask for details about the massive log messages (most recently rabbitmq/rabbitmq-mqtt#173) or claim that RabbitMQ
logs sensitive information when the runtime just dumps all of connection state into the log.

It would be beneficial to everyone if more cases were handled explicitly and did not result
in an abnormal connection process termination that leads to connection state dumped to the log.

Connection negotiation, parsing and authentication are three primary areas.

**Comment by murraybo** [comment]
One additional scenario which can cause crash reports but should normally handled in a more graceful way is:

`Web MQTT disconnecting a client with duplicate ID .... `

The process for the existing/old connection terminates with a crash report similar to this:

` [error] <0.3527.0> CRASH REPORT Process <0.3527.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.3772.0>, {close,200,<<"Goodbye">>}, 60000) in gen_server:call/3 line 24`

**Comment by ansd** [comment]
Fixed in recent RabbitMQ versions.
