### ISSUE TITLE
Retained messages are only delivered to clients for which a queue currently exists

### ISSUE THREAD

**Issue by chriswue** [rabbitmq/rabbitmq-server#2557]
Hi,

if I publish a message under a topic with the RETAIN flag set to true and QoS 1 and then subscribe with a new client for the first time (again QoS 1) the retained message doesn't get delivered. However it works if the client has connected before and a durable queue has been created. 

Simple example:

Publisher:

    import paho.mqtt.client as mqtt

    client = mqtt.Client(client_id="pub", clean_session=False)
    client.connect("localhost", 1883, 60)
    client.publish(topic='test', qos=1, payload="This is a test")
    client.loop()

Subscriber:

    import paho.mqtt.client as mqtt

    def on_connect(client, userdata, flags, rc):
        print("Sub connected with result code " + str(rc))
        client.subscribe("#", qos=1)

    def on_message(client, userdata, msg):
        print("Message for topic {} received: {}".format(msg.topic, str(msg.payload)))

    client = mqtt.Client(client_id="testsub", clean_session=False)
    client.on_connect = on_connect
    client.on_message = on_message
    client.connect("localhost", 1883, 60)

    client.loop_forever()

* Run the publisher: it will publish the message and then quit.
* Now run the subscriber for the first time: It will not get the retained message delivered
* Kill the subscriber
* Run the publisher again: it will publish the message and then quit.
* Run the scriber again (with the same client id): it will now get the retained message delivered

It looks like the RETAIN flag is implemented by delivering the message to all existing persistent queues but there is no persistence beyond that (e.g. for new clients or clients which where disconnected for more than a day - since the default expiry time for persistent queues is 1 day)

To me this sounds like a spec-violation bug:

> When a new subscription is established, the last retained message, if any, on each matching topic name MUST be sent to the subscriber [MQTT-3.3.1-6]

**Comment by MartyMcFlyInTheSky** [comment]
Does this mean that there is no way that NEW (unknown) devices will ever receive the retention message an a certain toppic?

**Comment by ansd** [comment]
This issue is old and misleading. I'm closing it in favour of https://github.com/rabbitmq/rabbitmq-server/issues/8824.

**Comment by chriswue** [comment]
@ansd So the functionality of delivering retained messages to clients that were never subscribed before now actually works?

**Comment by michaelklishin** [comment]
@chriswue this issue was moved to #8824.

**Comment by ansd** [comment]
@chriswue yes, delivering retained messages to clients that were never subscribed before works with the following limitations:
1. If the topic filter contains wildcards (e.g. `#` as in your example above), no retained messages are sent: https://github.com/rabbitmq/rabbitmq-server/issues/8824
2. Retained messages are stored only node local. That is, if a client publishes a retained messages to node A, and another client subsequently subscribes to node B, that subscribing client won't receive any retained messages: https://github.com/rabbitmq/rabbitmq-server/issues/8096

So, the functionality of retained messages in RabbitMQ is currently very limited.

An example that works:
Client publishes a message to node A with topic `topic/1` and thereafter another client connected to node A subscribes with topic filter `topic/1`. (Note in this example everything is local to node A, and the client does not use wildcards in its topic filter).
