### ISSUE TITLE
Configurable maximum (frame, headers) size limits

### ISSUE THREAD

**Issue by laurentluce** [rabbitmq/rabbitmq-server#2567]
The STOMP specification says that a STOMP server MAY place a limit on the maximum size of a frame body.

https://stomp.github.io/stomp-specification-1.2.html#Size_Limits

It would be helpful to have it as part of the STOMP adapter section in the configuration file.

**Comment by ikvmw** [comment]
I added `max_frame_size` option. Default is 4Mb. User is free to allocate however needed.

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-server/pull/8802
