### ISSUE TITLE
rabbit_amqqueue:pid_of/1 clause for default vhost calls

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-server#2572]
Thanks for rabbitmq/rabbitmq-server#826, useful & already using it :) & sorry to nitpick for a/another `pid_of/1` clause for `pid_of/2` calls with default vhost.

**Comment by michaelklishin** [comment]
An attempt to address this almost introduced a critical regression that would break the message routing path.

I'd prefer to not have this extra helper than take on this risk.
