### ISSUE TITLE
rabbitmq-amqp1.0-common: publish to hex.pm

### ISSUE THREAD

**Issue by bettio** [rabbitmq/rabbitmq-server#2577]
This library should be published on hex.pm in order to publish `amqp10_client` to hex.pm as well.
At the moment using `amqp10_client` is a quite painful process.

**Comment by alexcastano** [comment]
Hello, 

Any updates for this issue? I really appreciate a Hex.pm package.

In order to use this repo in a Elixir project, we are doing the following:

```
  defp deps do
    [
      ...
      {:rabbitmq_server,
       github: "rabbitmq/rabbitmq-server",
       app: false,
       runtime: false,
       compile: false,
       override: true},
      {:amqp10_common, path: "deps/rabbitmq_server/deps/amqp10_common", compile: "make"},
      {:amqp10_client, path: "deps/rabbitmq_server/deps/amqp10_client", compile: "make"},
```

Maybe it is helpful for other people, or maybe there is a better way :)

**Comment by lhoguin** [comment]
> Also, @essen will soon start to work on official support for Hex.pm publish in Erlang.mk, not based on Rebar 3 (and thus mix misbehavior). This should solve the problem for good.

Most recent Erlang.mk has this, for what it's worth. So I suppose the only thing left to do is publishing.

**Comment by drmartinberger** [comment]
> Hello,
> 
> Any updates for this issue? I really appreciate a Hex.pm package.
> 
> In order to use this repo in a Elixir project, we are doing the following:
> 
> ```
>   defp deps do
>     [
>       ...
>       {:rabbitmq_server,
>        github: "rabbitmq/rabbitmq-server",
>        app: false,
>        runtime: false,
>        compile: false,
>        override: true},
>       {:amqp10_common, path: "deps/rabbitmq_server/deps/amqp10_common", compile: "make"},
>       {:amqp10_client, path: "deps/rabbitmq_server/deps/amqp10_client", compile: "make"},
> ```
> 
> Maybe it is helpful for other people, or maybe there is a better way :)

@alexcastano Thank you for your workaround! Helped us!

**Comment by starbelly** [comment]
bump 😄

**Comment by starbelly** [comment]
@lukebakken Yup, currently using the work around. I believe @lhoguin stated this can be done with erlang.mk now, is that native or still require a plugin?

**Comment by essen** [comment]
Native. No plans to move to rebar, our only work in build tools is Bazel related.

**Comment by lukebakken** [comment]
🤷 I'm mainly concerned with _when_ these packages are published. I'm sure it involves our build processes.

**Comment by lukebakken** [comment]
@starbelly @drmartinberger @alexcastano @AntoineGagne @bettio 

Alright everyone -

https://hex.pm/packages/amqp10_client
https://hex.pm/packages/amqp10_common

Here's my test repo -
https://github.com/lukebakken/amqp10_test

**Please test this out and report back!**

**Comment by starbelly** [comment]
@lukebakken Tested on OTP 24, works beautifully! Thanks so much and look forward to making contributions 🚀
