### ISSUE TITLE
rabbitmq-amqp1.0-client: publish hex package

### ISSUE THREAD

**Issue by patrickdet** [rabbitmq/rabbitmq-server#2580]
Hey all,

great library, thank you so much for it. This might not be the place for it but would it be possible to get this library published on hex.pm? It's really hard for me to get it's to build properly from Elixir. A simple: `{:amqp10_client, github: "rabbitmq/rabbitmq-amqp1.0-client", compile: "make"}` in the `mix.exs` file leads to make errors whereas building it from the the `rabbitmq-amqp1.0-client` root folder works without a hitch. I suspect that the `rabbitmq_codegen` stage is problematic here. Have you considered publishing the package on Hex?

Thanks again :)

**Comment by azhi** [comment]
Any plans on this moving forward? Hex package would be really appreciated.

Unfortunately mix doesn't support monorepoes well, currently you can't add a dependency on `amqp10_client` at all, which makes things worse.

Ive forked `amqp1.0-client` and `amqp1.0-common` into separate repoes and tried to make it work without the rest of monorepo, and it was working for a while. But now something broke in building process, and debugging unfamiliar make-based build system is quite troublesome :(.

**Comment by lukebakken** [comment]
As of RabbitMQ 3.9.16 hex publishing is integrated into our build pipelines -

https://hex.pm/packages/amqp10_common
https://hex.pm/packages/amqp10_client
