### ISSUE TITLE
Support for queue:// and topic:// prefixes

### ISSUE THREAD

**Issue by gotthardp** [rabbitmq/rabbitmq-server#2583]
The [Apache ActiveMQ documentation](http://activemq.apache.org/amqp.html) says:
_You should prefix destination address with `queue://` to use Queue based destinations or `topic://` to use topic based destinations. If an AMQP address is used without the prefix, it will be used as a Queue._

The direct routing to a Queue works with RabbitMQ the same way. However, publishing to a destination with some prefix fails because it's treated as a queue name, which is invalid. I propose to define a new routing options and say that
- Sending to "topic://RK" behaves like sending to "/topic/RK"
- Sending to "queue://Q" behaves like sending to "/queue/Q"

It doesn't harm anything and it increases compatibility.
If you agree I can do the coding.

**Comment by mkuratczyk** [comment]
I'm not even sure what the state of AMQP-1.0 support was in 2015, but with RabbitMQ 4.0, we support 2 addressing schemes: https://www.rabbitmq.com/docs/next/amqp#addresses
They are different than ActiveMQ uses but I don't think we are interested in adding the third pattern.
