### ISSUE TITLE
Add support for anonymous senders

### ISSUE THREAD

**Issue by andreas-eberle** [rabbitmq/rabbitmq-server#2587]
Quarkus 1.3 switched to using layered extension mechanism for their AMQP connections. This currently makes it impossible to use Quarkus with RabbitMQ-amqp1.0 plugin. 

Please refer to the details in https://github.com/quarkusio/quarkus/issues/7885. Especially this comment https://github.com/quarkusio/quarkus/issues/7885#issuecomment-600037009.

Is it possible to add this functionality in this plugin?

**Comment by ansd** [comment]
Anonymous terminus is supported in RabbitMQ 4.0:
https://www.rabbitmq.com/docs/next/amqp#target-address-v2
