### ISSUE TITLE
badarith in rabbit_queue_consumers:use_avg/3

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#259]
Noticed [this in the SASL log](https://gist.github.com/michaelklishin/ecbd39ec0ca6d9fe0767) when running .NET tests on Windows with Erlang 18.0. This seems related to the recent changes in #233.

**Comment by dumbbell** [comment]
I believe it's fixed by 7f3ab57c3846b98f7a8de055a384465013d02f82.

@michaelklishin: Can you confirm it fixes the issue for you too?

**Comment by michaelklishin** [comment]
I can no longer reproduce this exception.
