### ISSUE TITLE
Link detach does not set closed to true

### ISSUE THREAD

**Issue by vcabbage** [rabbitmq/rabbitmq-server#2594]
Hi! I maintain an AMQP 1.0 client for Go (https://github.com/vcabbage/amqp). While investigating https://github.com/vcabbage/amqp/issues/60 I noticed that closing a link was hanging.

It seems when the client send it's detach, with Closed=true, RabbitMQ responds with a detach with Closed=false. (Technically it's sending it with a null value for Closed, but the [default is false](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#type-detach).)

To my knowledge, non-closing detaches are used to detach from a link and [reattach later](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#doc-idp339696). I'm not sure that's something RabbitMQ supports (my client doesn't). In any case, I believe it would be correct for RabbitMQ to respond with a closing detach.

The [spec also says](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#doc-closing-a-link):
> Note that one peer MAY send a closing detach while its partner is sending a non-closing detach. In this case, the partner MUST signal that it has closed the link by reattaching and then sending a closing detach.

Do you agree with this assessment? I can provide debug logs and/or packet captures if it would be helpful.

Thanks!

**Comment by ansd** [comment]
Fixed in RabbitMQ 4.0.
