### ISSUE TITLE
Consider implementing `dynamic` for queue targets.

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/rabbitmq-server#2599]
Discussed in rabbitmq/rabbitmq-amqp1.0#7 

The stomp adaptor allows users to pass headers to control the queue properties for stomp generated queues. amqp 1.0 could use the `dynamic` flag combined with `dynamic-node-properties` to do the same. Currently `dynamic` isn't supported but we could allow it when establishing a link where the target is a queue.

**Comment by ansd** [comment]
This seems to be a duplicate of https://github.com/rabbitmq/rabbitmq-server/issues/2602
