### ISSUE TITLE
dont end the session upon attach from a client supporting the modified outcome

### ISSUE THREAD

**Issue by gemmellr** [rabbitmq/rabbitmq-server#2600]
Currently with broker version 3.6.5 if a client which supports the modified outcome tries to attach a link with it included in its source outcomes, the broker ends its parent session indicating it doesnt support the modified outcome. It would significantly aid client interoperability if an alternate approach could be taken.

Implementing some level of support for the Modified outcome would be one approach. Being less aggressive in not supporting it would be another option. For example in the case of a producer, if the client for some reason decided to and was actually able to modify the message before the server gave it an outcome and settled it, that just means discard the message. In the case of a consumer a nicer option would be to exclude modified from the source outcomes returned when sending the link attach response, since the servers view is definitive there, and the spec says peers should not preempt whether the actual properties of the terminus will satisfy their partners requirements. The server could then react forcefully (by closing the link rather than session perhaps?) only if the consumer actually went on to use the modified outcome.

**Comment by ansd** [comment]
Fixed in RabbitMQ 4.0.
