### ISSUE TITLE
Support vhost selection

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#2601]
À la MQTT plugin. Our original attempt at parsing out vhost was using hostnames because of a client library-specific design decision. We should consider doing what MQTT plugin does.

**Comment by mkuratczyk** [comment]
Support added in RabbitMQ 4.0.
https://www.rabbitmq.com/docs/next/amqp#virtual-hosts

**Comment by michaelklishin** [comment]
@mkuratczyk just FTR, our AMQP 1.0 implementation supported virtual host selection before 4.0 but I can no longer remember the version. It must have been a version from 2020 or so, since Tanzu RabbitMQ relies on this feature :)
