### ISSUE TITLE
Get connection per user

### ISSUE THREAD

**Issue by laurentluce** [rabbitmq/rabbitmq-server#2617]
Finding out the connection state for a particular user is costly today since we have to retrieve the full list of connections and then extract the ones related to this user.  The GET connections request can take few seconds to complete on a setup with 1000s of connections.  It would be helpful to add support for a `user` parameter in the URL similar to what was done for the `name` parameter.

`
http://localhost:15672/api/connections?user=bob
`

rabbitmq/rabbitmq-management#76

**Comment by michaelklishin** [comment]
I think this has been effectively addressed in https://github.com/rabbitmq/rabbitmq-server/issues/607, #2380.

**Comment by rept** [comment]
@michaelklishin should the API now support this: http://localhost:15672/api/connections?user=bob ?

The issues you referred to are max user limits.

When I do:

    /api/connections?columns=user

I get

    [{"user":"ATFAXX"},{"user":"VYKPAA"},{"user":"backend"}]

When I do:

    /api/connections?user=ATFAXX

It returns all the connections, regardless of user.

**Comment by lukebakken** [comment]
@rept what @michaelklishin means by "effectively addresses" is that the per-user limits implemented should remove much of the need for listing a user's connections.

**Comment by rept** [comment]
@lukebakken ok thx.  Too bad.  I wanted to use this to check if a certain user was still connected or not.

**Comment by michaelklishin** [comment]
With per-user connection tracking it should be fairly straightforward to add basic filtering to the `GET /api/connections` endpoint (or a new endpoint, which is almost always what I'd prefer).

Contributions would be considered. This is open source software after all.
