### ISSUE TITLE
Make the UI display time in local time zone time as well as UTC

### ISSUE THREAD

**Issue by zengzhenbo** [rabbitmq/rabbitmq-server#2620]
In the file [rabbit_mgmt_format.erl](https://github.com/rabbitmq/rabbitmq-management/blob/stable/src/rabbit_mgmt_format.erl#L203-L210)
`now_to_str(unknown) ->`
 `unknown;`
`now_to_str(MilliSeconds) ->`
`BaseDate = calendar:datetime_to_gregorian_seconds({{1970, 1, 1},`
`{0, 0, 0}}),`
`Seconds = BaseDate + (MilliSeconds div 1000),`
`{{Y, M, D}, {H, Min, S}} = calendar:gregorian_seconds_to_datetime(Seconds),`
`print("~w-~2.2.0w-~2.2.0w ~w:~2.2.0w:~2.2.0w", [Y, M, D, H, Min, S]).`

the result of now_to_str/1 is UTC time, and these times will be showed on the management ui, users may misunderstand these time.
now_to_str/1 should converts from UTC to local time by call calendar:universal_time_to_local_time/1 before print/1

**Comment by hueifeng** [comment]
This issue can be closed, see https://github.com/rabbitmq/rabbitmq-server/pull/4331
