### ISSUE TITLE
rabbitmq-server 3.5.4 release is not on packagecloud

### ISSUE THREAD

**Issue by jpackagejasonc** [rabbitmq/rabbitmq-server#263]
Hi!
I was looking at the packagecloud yum repository and it appears that 3.5.4 was not uploaded as part of the release process. You can see the repo contents here:
https://packagecloud.io/rabbitmq/rabbitmq-server
Is this a conscious move away from providing the packages at that location or just a bug in the process?
Thanks!

**Comment by michaelklishin** [comment]
Sadly for non-technical reasons we probably won't be using Package Cloud as much as we'd like to. We'll release `3.5.4` and likely keep the most recent release available there.

**Comment by jpackagejasonc** [comment]
thanks for the quick response! is there a yum repository method that is preferred over packagecloud?

**Comment by michaelklishin** [comment]
Not at the moment. We are considering hosting our own vs. using services such as Package Cloud (but not PC specifically, even though our team likes it a lot).

**Comment by jpackagejasonc** [comment]
it would be nice to have a rabbitmq yum repo analogous to the deb repos already provided on the downloads site (at least for my use case anyway). I'll use packagecloud for now and keep an eye out for any changes here. thanks!

**Comment by videlalvaro** [comment]
@michaelklishin pushed these packages already
