### ISSUE TITLE
ANSI escape code characters should be avoided on Windows

### ISSUE THREAD

**Issue by pjk25** [rabbitmq/rabbitmq-server#2634]
For example, `Help:` gets printed as `[1mHelp[0m:`.

![Screen Shot 2020-01-21 at 10 01 21 AM](https://user-images.githubusercontent.com/217064/72792408-4106f980-3c39-11ea-8842-947e5873f9c6.png)

This is because we are attempting to print "Help:" in bold via ANSI escape codes, which don't appear to be supported on Windows (at least for common configurations).

Apparently the necessary APIs to properly detect support for these codes isn't provided by Erlang, so my suggestion would be that we fall back to unformatted output when running on Windows.

**Comment by boldMahoney** [comment]
Hi
Is there any news about subject?

**Comment by lhoguin** [comment]
It is not a priority right now as we are fairly busy with more impactful changes. A PR would be most welcome though.

**Comment by boldMahoney** [comment]
Ok, thanks for info

**Comment by michaelklishin** [comment]
Making all functions [in this module](https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbitmq_cli/lib/rabbitmq/cli/core/ansi.ex) to return values as is on Windows should be all there is to do.
