### ISSUE TITLE
NSIS installer silent install not supported in Windows upgrades

### ISSUE THREAD

**Issue by ryanzink** [rabbitmq/rabbitmq-server#264]
I currently have a large number of servers that have v3.2.4 installed. I am trying to automate the upgrade process to v3.5.4 through a scripted install. I tried using the standard NSIS silent parameter by executing the following: 
`.\rabbitmq-server-3.5.4.exe /S`
However, the installer has not been configured to be fully silent... I am facing the following issues:
* The "RabbitMQ is already installed" dialog box appears even when the installer is run in silent mode. NSIS installers can be set up to have a default option for silent installs (examples are here: http://nsis.sourceforge.net/Examples/silent.nsi) to override the message box from appearing.
* Installing in silent mode as an upgrade between versions does not perform the same actions that a non-silent install does. I haven't performed an exhaustive analysis, but right away a major issue is that the RabbitMQ service does not get installed after the previous version is uninstalled.

**Comment by michaelklishin** [comment]
How can we make the installer do what you want?

**Comment by ryanzink** [comment]
To correct the dialog box, it appears the installer needs to have an /SD switch added to the MessageBox so the OK button is selected by default. There's documentation here: http://nsis.sourceforge.net/Docs//Chapter4.html#silent

As far as the service not getting installed, it looks like it is failing to install because the installer detects the environment variable ERLANG_HOME is not present. I see when the uninstall runs it removes ERLANG_HOME variable and when the install runs in non-silent mode it creates the ERLANG_HOME variable, but maybe there is a timing issue that prevents the environment variable from being created when it has been removed in the past second or so as the uninstall/reinstall occurs.

**Comment by michaelklishin** [comment]
@ryanzink we do not know much about NSIS or Windows installer automation. If you'd contribute a PR that does the necessary changes, and a way for us to test it, we would be happy to include your work in 3.5.5.

**Comment by michaelklishin** [comment]
Good point about `ERLANG_HOME`. To alleviate this, we need a way to make the installer aware that this is an upgrade and not an uninstall: is there a standard way to do that?

**Comment by ryanzink** [comment]
@michaelklishin Unfortunately there isn't a standard way to do that. NSIS has a lot of limitations in that department. However I think passing parameters to the uninstall process could work. If there was a parameter that indicated the Uninstall was temporary, it could provide a workaround. I'll see what I can dig up.

**Comment by ryanzink** [comment]
I don't know if this is an issue that can be remedied, but I'd like to add that we have found that the NSIS installer run with the /S argument for silent mode install cannot be run as the system account "NT AUTHORITY\SYSTEM". When it is run this way, some of the functionality of the installer is bypassed. In particular, the installer ignores the installer configuration environment variables listed [here](https://www.rabbitmq.com/relocate.html), specifically RABBITMQ_BASE, leading to the failure to create the db and logs folders.

**Comment by dumbbell** [comment]
Hi!

I built your `rabbitmq-server-264` branch to produce a test installer. However, I had to comment out line 116:
https://github.com/ryanzink/rabbitmq-server/blob/rabbitmq-server-264/packaging/windows-exe/rabbitmq_nsi.in#L116

Otherwise, I got the following error:
```
makensis -V2 rabbitmq-3.5.6.264.nsi
Error: can't load same language file twice.
Error in macro MUI_LANGUAGE on macroline 9
Error in script "rabbitmq-3.5.6.264.nsi" on line 116 -- aborting creation process
make[1]: *** [dist] Error 1
```

I have no idea if this is correct. Could you please take a look and push a fix to your branch?

**Comment by ryanzink** [comment]
Yes, I had to use that line as the language looks like it is set otherwise in your build process and neglected to remove it. I have removed it and pushed the changes to my branch, however I am seeing this in the new version of the installer:
![image](https://cloud.githubusercontent.com/assets/13768946/10700674/f7a2365e-7984-11e5-8421-a30e6ca6e410.png)

The final page of the installer looks like it is missing some sort of content. I validated this across a few different machines. I don't believe my changes impacted that but I wanted to know if that is something that you are seeing on your side as well.

**Comment by dumbbell** [comment]
Hi @ryanzink!

I made some fixes to the Windows installer today. While I'm at it, what is the state of your branch? If you think it's ready for testing, please submit a pull request.

**Comment by ryanzink** [comment]
My branch is ready for testing. I have compiled and the installer silently successfully but am wondering if you were able to replicate the issue I posted above with the white installer pages...

**Comment by dumbbell** [comment]
I'm working on your pull request.

Just to confirm the problem:
* If I do a fresh install using `.\rabbitmq-server-3.6.0.exe /S`, I get a dialog asking if I want to allow this program from an unknown vendor, then two cmd.exe windows. The installed files seem ok, the service works.
* If I upgrade using silent mode, I get the same dialog warning about the unknown vendor, then three cmd.exe windows. The install is totally busted: the install directory only contains:

 ```
RabbitMQ Server
`-- rabbitmq_server-3.6.0
        `-- sbin
```

I don't remember who suggested that but we have a problem during upgrade: the installer does not wait for the uninstall to complete. When using the interactive mode, it is usually not a problem because the user slow enough that the uninstall finishes before the install. When running in unattended mode, the install finishes before the uninstall (which needs to stop the service for instance). I believe that's why all files are removed after the installer finished in this case.

**Comment by dumbbell** [comment]
I first changed the installer to wait for uninstall before proceeding in 4dd361c.

The solution is documented here:
http://nsis.sourceforge.net/When_I_use_ExecWait_uninstaller.exe_it_doesn't_wait_for_the_uninstaller

**Comment by dumbbell** [comment]
Thank you @ryanzink for your patch, it fixed the "unattended" install needing interaction :)

Note that instead of merging your branch, I took the liberty to squash your commits into one and I also modified the style (removed trailing spaces and used 2-space indentation instead of tabs).

**Comment by dumbbell** [comment]
By the way, I never had the blank page so far, before or after your patch.
