### ISSUE TITLE
Are there recomended testing when upgrading a rabbitMQ version?

### ISSUE THREAD

**Issue by KobiLankri** [rabbitmq/rabbitmq-server#265]

**Comment by michaelklishin** [comment]
Please ask questions on rabbitmq-users in the future.

You can copy RabbitMQ's directory (ideally when the server isn't running) to back it up, then try upgrading on another machine from the copy, making sure that node name matches. Also keep in mind that the node will try to contact the nodes it has seen online if this is in a cluster.
