### ISSUE TITLE
Expose resource alarms as Prometheus metrics

### ISSUE THREAD

**Issue by dcorbacho** [rabbitmq/rabbitmq-server#2653]
Alarms could make it into a core metrics table as binary entries and be reported by Prometheus. 
CC @MarcialRosales

**Comment by michaelklishin** [comment]
Good idea.

**Comment by deadtrickster** [comment]
I can write a collector that calls rabbit_alarm:get_alarms and exposes alarms as metrics with nodes as labels. Is this what you had in mind?

**Comment by deadtrickster** [comment]
this is how one of the unofficial exporters handles alarms: 

https://github.com/kbudde/rabbitmq_exporter#node---counter

**Comment by gerhard** [comment]
That sounds like a great idea @deadtrickster!

[This comment](https://github.com/prometheus/docs/pull/1414#issuecomment-520534451) from a larger 2019 discussion with @brian-brazil explains why node labels should not be used. Has this recommendation changed? This is the reason why we make extensive use of `* on(instance) group_left(rabbitmq_cluster, rabbitmq_node)` in all our PromQL.

I'm thinking:

```
rabbitmq_memory_alarm 0
rabbitmq_disk_alarm 0
```

By the way: https://github.com/rabbitmq/rabbitmq-server/blob/a1561ff53f4696a402a77e51433e0e3f22c7d871/deps/rabbitmq_prometheus/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl#L24-L29

**Comment by deadtrickster** [comment]
ok right, instance label is enough already. so boolean metrics for each resource type without any labels.

**Comment by lhoguin** [comment]
Anything else worth importing from the unofficial exporter?

**Comment by johanneswuerbach** [comment]
> Anything else worth importing from the unofficial exporter?

In our setup we also use the `rabbitmq_partitions` metric, would it also make sense to port this one?

There is another issue open for that though https://github.com/rabbitmq/rabbitmq-server/issues/2508
