### ISSUE TITLE
Dynamic shovels that are deleted can be resurrected in clustered environments

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#2655]
Reported here:
https://groups.google.com/g/rabbitmq-users/c/k4Qwge4mC08

Script to reproduce:
https://github.com/lukebakken/deleted-queue-restored-k4Qwge4mC08/blob/master/repro.sh

What's happening is that even though the dynamic shovels are set to auto delete, the `rabbit_shovel_dyn_worker_sup_sup` remains alive. The process survives a full cluster restart thanks to `mirrored_supervisor`, and after a full restart several of the deleted queues are re-created.

You can see that the dynamic shovel parameters have been cleared out as expected when the shovels delete themselves.

This does not happen in single-node environments as there is no way for the supervisor to survive the restart.

@dcorbacho @michaelklishin ideas?

**Comment by simoelmou** [comment]
We have also the same problem in production where auto-delete shovels re-appear after a cluster restart (node by node)
Is there any news about this issue please?

**Comment by lukebakken** [comment]
https://groups.google.com/g/rabbitmq-users/c/wW_UhhAU8NM

**Comment by michaelklishin** [comment]
We can reproduce.
