### ISSUE TITLE
"make distclean" no longer recurses into deps/ directories

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#2663]
To reproduce, run `make distclean` in the top-level of this repo while cloned. `deps/*` sub-dirs are not visited.

Workaround: use `git clean -fxd`

**Comment by pjk25** [comment]
I added a `make monorepo-distclean` goal that will do this, but I agree it would be nice if the standard `make distclean` did the right thing.

**Comment by pjk25** [comment]
At this point in time I believe the proper way to address this is to move the vendored deps, those that are checked into the `deps` dir, into an `apps` dir, according to https://erlang.mk/guide/deps.html#_many_applications_in_one_repository

However, this might cause release pipeline breakage in the case of any hard coded paths. I will give it a quick try locally, though I haven't heard people complain about it enough that I'm sure it's worth the effort.

**Comment by pjk25** [comment]
After a small amount of trying the `deps` -> `apps` change out, there are a few quirks that would need addressing. One is that Erlang.mk does not have an equivalent to `BUILD_DEPS` that works with deps in the `apps` directory right now. I suspect `LOCAL_BUILD_DEPS` would be sensible, but it is a feature that would need to be added to Erlang.mk. The same is probably true for `TEST_DEPS` - a `LOCAL_TEST_DEPS` would need to be added.

**Comment by pjk25** [comment]
#3133 is the proper fix for this
