### ISSUE TITLE
Rabbit MQTT Plugin failing to start

### ISSUE THREAD

**Issue by tiaan-lg** [rabbitmq/rabbitmq-server#2665]
We have set up a cluster of 3 nodes on VM's behind a load balancer

We are using the RabbitMQ MQTT plugin for the messaging protocol and then doing a load test.

After some time the client connections start to drop and one/multiple nodes crash

When they reboot they fail to work at all, and just go into a loop of rebooting.

We looked at the logs and can see that specifically, the rabbitmq_mqtt plugin is failing to start giving the following error

`Application rabbitmq_mqtt exited with reason: {timeout,{gen_statem,call,[{mqtt_node,'rabbit@fsk-apnli000000'},trigger_election,5000]}}`

The MQTT plugin then never starts again.

This then brings down our entire cluster

We are not sure how to fix this other than clearing everything from the db and re setting up the cluster from scratch

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.
