### ISSUE TITLE
Handle the case where definitions.json file is missing expected queue arguments

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#2668]
Reported in this `rabbitmq-users` discussion:

https://groups.google.com/g/rabbitmq-users/c/izPLZUYQqEY

To reproduce, use the attached files:

[arguments-missing-definitions-crash-izPLZUYQqEY.zip](https://github.com/rabbitmq/rabbitmq-server/files/5631526/arguments-missing-definitions-crash-izPLZUYQqEY.zip)

**Comment by michaelklishin** [comment]
I would be happy to take this over since I've started looking at #2667.
