### ISSUE TITLE
Cluster node startup takes longer than 2 hours

### ISSUE THREAD

**Issue by motmot80** [rabbitmq/rabbitmq-server#2679]
## Description ##
Cluster node restart takes **longer than two hours** without consuming system ressources.

## Reproduction ##
1. Fillup node with setup below
2. Stop one node
3. Restart node

## Rabbit MQ setup ##
**Rabbit MQ-Version**: 3.8.1 (Erlang 22.1.6)
**Nodes count**: 3 
**Node hardware**: 8 CPUs - 32 GB RAM each

## Expected ##
Node starts within a few minutes

## Actual ##
Node start always takes longer than **120 minutes**.
1h:40m without logging (debug) any progress.
Except `[Re-]registered this node` which seems to be something like a cluster heart beat ([empd] 25762).
See log analysis below.

## Reproduction setup ##
|Type|Count|Description|
|---|---|---|
|Queues (lazy)|80 000|20 000 per node|
|Queues (non-persistent)|20||
|Queues (HA)|1||
|Exchanges|32||
|Bindings|1 200 000||
|Messages ready|20 000 000|in lazy queues|

## Log analysis ##
|Duration|Count occur.|Phase|
|---|---|---|
|6s|1|Started
|2m:12s|1|Prelaunch
|13m:12s|23300|ERROR - in an old incarnation (3) of this node (1)
|**1h:2m:10s**|1|NO OPERATION - after WARN rabbit_sysmon_handler busy_dist_port
|4s|1|Supervisor started
|1m:24s|1|Started message store 
|7s|1|Rebuilding message location index started
|<1s|1|Rebuilding message location index finished
|<1s|1|Started message store of type persistent
|7s|8006|start_links *LAZY-QUEUES*
|**41m:16s**|1|NO OPERATION - after WARN lager_error_logger_h dropped 646 messages
|1s|1|start_link *HA-QUEUE*
|1s|1|Application started..
|<1s|1|Plugins starting
|7s|1|Finished

## System load during startup ##
**CPU**: < 25 %
**RAM**: < 15 %
**Network**: < 2 MB/s
**Disk I/O**:  < 1 MB/s (14 MB/s peak during lazy queu initialization)

**Comment by motmot80** [comment]
Unfortunately we don't know where to continue dig deeper.

Any help would be highly appreciated.

Thanks in advance
Thomas

**Comment by lukebakken** [comment]
Please provide a script we can run to load a 3-node cluster with your exact configuration and message load. The `rabbitmqadmin` tool would be useful for this. Exporting definitions would also work, but we would need to know how messages are distributed among nodes, as well as information like message size.
