### ISSUE TITLE
Improve validation for private keys that cannot be read [in rabbitmq.conf]

### ISSUE THREAD

**Issue by ThorAsgardDev** [rabbitmq/rabbitmq-server#2685]
Hello,

I tried to activate TLS (following https://www.rabbitmq.com/ssl.html) and encountered an issue.
The server starts without any error but all clients get rejected during handshake without any error in rabbitmq logs (even in debug)
After investigation, the issue comes from bad file permissions on the rabbit.ssl_options.keyfile.
The file permissions was: -rw------- 1 root     rabbitmq 1675 Dec 17 12:07 private_key.pem

If I change them to:
-rw-r----- 1 root     rabbitmq 1675 Dec 17 12:07 private_key.pem
or
-rw------- 1 rabbitmq     rabbitmq 1675 Dec 17 12:07 private_key.pem
then it works correctly.

According to #1653 I understand that, since the version 3.7.X, the server should check the read access to this file at start and report an error.

I'm using version 3.8.7 of rabbitmq.

Thanks

**Comment by michaelklishin** [comment]
We agree that it would be nice. But RabbitMQ does not implement TLS, Erlang/OTP does. It's a behavior that has to change in the Erlang TLS implementation: it should return sensible errors and log errors (there's a standard system logger it can use). It currently doesn't really do either. One important factor here may be that all certificates loaded on the node are loaded in a lazy manner and there's a certificate cache involved. In other words, for as long as some of this lazy behavior exists, the earliest the node can find out that the private key file is not readable is when it receives a client connection.

RabbitMQ nodes will validate file existence and readability for file (including certificate) paths if `rabbitmq.conf` is used at node startup time. If `advanced.config` or legacy `rabbitmq.config` is used, no validation is performed. Erlang's TLS implementation can verify the file path options in some cases but again, potentially the earliest it can happen is on the first load attempt which can be tied to the inbound connection lifecycle.

This belongs at https://bugs.erlang.org.

**Comment by ThorAsgardDev** [comment]
@michaelklishin 
Thanks for your answer.
You say that "RabbitMQ nodes will validate file existence and readability for file (including certificate) paths if rabbitmq.conf is used at node startup time" however this is not what I observe in my case. I'm using rabbitmq.conf containing a path to a private key file that cannot be read by rabbitmq server and it doesn't log any error at startup.

**Comment by lukebakken** [comment]
@ThorAsgardDev in your environment, even though the file permissions were this:

```
-rw------- 1 root rabbitmq 1675 Dec 17 12:07 private_key.pem
```

The permissions on the _directory_ containing this file still allowed the `rabbitmq` user to `stat` the file this way:

https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbit/priv/schema/rabbit.schema#L1771-L1775

I know this because I just verified it in my local environment. The following permissions prevent RabbitMQ from starting - note the permissions on the `result` directory itself:

```
[root@shostakovich result]# ls -la .
total 53
drwx------ 2 root    root      10 Nov  5 05:46 .
drwxr-xr-x 6 lbakken lbakken   10 Nov  5 05:46 ..
-rw-r--r-- 1 lbakken lbakken 1208 Nov  5 05:46 ca_certificate.pem
-rw------- 1 lbakken lbakken 1708 Nov  5 05:46 ca_key.pem
-rw-r--r-- 1 lbakken lbakken 1164 Nov  5 05:46 client_certificate.pem
-rw------- 1 lbakken lbakken 2421 Nov  5 05:46 client_key.p12
-rw------- 1 lbakken lbakken 1708 Nov  5 05:46 client_key.pem
-rw-r--r-- 1 lbakken lbakken 1253 Nov  5 05:46 server_certificate.pem
-rw------- 1 lbakken lbakken 2485 Nov  5 05:46 server_key.p12
```

I'm running RabbitMQ as user `lbakken:lbakken` and here is the startup:

```
07:52:54.715 [debug] Validation
07:52:54.716 [error] ssl_options.cacertfile invalid, file doesn't exist or isn't readable
07:52:54.716 [error] ssl_options.certfile invalid, file doesn't exist or isn't readable
07:52:54.716 [error] ssl_options.keyfile invalid, file doesn't exist or isn't readable
07:52:54.716 [error] management.ssl.certfile invalid, file doesn't exist or isn't readable
07:52:54.716 [error] management.ssl.keyfile invalid, file doesn't exist or isn't readable
07:52:54.716 [error] management.ssl.cacertfile invalid, file doesn't exist or isn't readable
07:52:54.716 [error] Error preparing configuration in phase validation:
07:52:54.716 [error]   - ssl_options.cacertfile invalid, file doesn't exist or isn't readable
07:52:54.716 [error]   - ssl_options.certfile invalid, file doesn't exist or isn't readable
07:52:54.716 [error]   - ssl_options.keyfile invalid, file doesn't exist or isn't readable
07:52:54.716 [error]   - management.ssl.certfile invalid, file doesn't exist or isn't readable
07:52:54.716 [error]   - management.ssl.keyfile invalid, file doesn't exist or isn't readable
07:52:54.716 [error]   - management.ssl.cacertfile invalid, file doesn't exist or isn't readable
07:52:54.719 [error] 

07:52:54.720 [error] BOOT FAILED
BOOT FAILED
07:52:54.720 [error] ===========
===========
07:52:54.720 [error] Error during startup: {error,failed_to_prepare_configuration}
Error during startup: {error,failed_to_prepare_configuration}
07:52:54.720 [error] 
```

However, if I change the `result` directory permissions to allow the `lbakken` user to stat files, RabbitMQ startup is successful.

```
[root@shostakovich result]# ls -la
total 53
drwx------ 2 lbakken lbakken   10 Nov  5 05:46 .
drwxr-xr-x 6 lbakken lbakken   10 Nov  5 05:46 ..
-rw-r--r-- 1 lbakken lbakken 1208 Nov  5 05:46 ca_certificate.pem
-rw------- 1 lbakken lbakken 1708 Nov  5 05:46 ca_key.pem
-rw-r--r-- 1 lbakken lbakken 1164 Nov  5 05:46 client_certificate.pem
-rw------- 1 lbakken lbakken 2421 Nov  5 05:46 client_key.p12
-rw------- 1 lbakken lbakken 1708 Nov  5 05:46 client_key.pem
-rw-r--r-- 1 lbakken lbakken 1253 Nov  5 05:46 server_certificate.pem
-rw------- 1 lbakken lbakken 2485 Nov  5 05:46 server_key.p12
-rw------- 1 root    root    1708 Nov  5 05:46 server_key.pem
```

Even though the `lbakken` user can't open `server_key.pem`, the user can still `stat` the file and startup is successful. We'll have to make validation a little more robust somehow.

**Comment by ThorAsgardDev** [comment]
Hello @lukebakken,
I'm happy that you're able to reproduce the problem.
Is it possible to reopen the issue as to improve validation as you suggest?

**Comment by lukebakken** [comment]
> Is it possible to reopen the issue as to improve validation as you suggest?

Sure, I'll re-open it but the problem should be addressed at the [`ranch`](https://github.com/ninenines/ranch) or the [OTP](https://github.com/erlang/otp) level to be honest.

**Comment by ThorAsgardDev** [comment]
Thanks for reopening. I agree that it should also be addressed in Erlang itself, but making validation more robust on your side would be very helpful in the meantime.

**Comment by lukebakken** [comment]
> making validation more robust on your side would be very helpful in the meantime

@ThorAsgardDev RabbitMQ is open source and free to use. You could implement the feature yourself and we would appreciate it.
