### ISSUE TITLE
Make prelaunch / boot logging more synchronous

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#2687]
Currently, the `rabbit_prelaunch` debug logging does not log messages "as they happen". While working on #2656 this confused me quite a bit as it seemed as though boot functions weren't completing when they should have been. I worked around this by inserting my own logging like this:

```
io:format(standard_error, "@@@@@@@@ MY OBVIOUS MESSAGE~n", [])
```

Ideally, during RabbitMQ bootup, debug messages would be logged and flushed ASAP.

**Comment by dumbbell** [comment]
Could you please describe how to reproduce the problem? I don't see any delay locally.

**Comment by lukebakken** [comment]
I will attach a startup log today with and without my added `standard_error` messages.

**Comment by pjk25** [comment]
I will close this since the issue does not appear to have come up again.
