### ISSUE TITLE
Add client ip and queue labels to channel metrics

### ISSUE THREAD

**Issue by chicocvenancio** [rabbitmq/rabbitmq-server#2689]
None of the channel metrics have the channel name or client ips in them. It would be useful to be able to match the metrics with the clients.
Queue labels are present in some metrics, but not on most. It would also be useful to match queues to channel metrics.

**Comment by michaelklishin** [comment]
Channels know nothing about client IP addresses (with some rare exceptions around authZ backend context). A channel name is a number scoped to its connection.

**Comment by chicocvenancio** [comment]
@michaelklishin I must be using the wrong terminology here. I do mean the connection name and number.
