### ISSUE TITLE
Strengthen password encryption algorithm to meet FIPS 180

### ISSUE THREAD

**Issue by freemansoft** [rabbitmq/rabbitmq-server#270]
The password store should be protected with stronger encryption

A security team I'm working with noted:
>MD5 is an insecure password hashing algorithm which does not meet the definition of “a strong, one->way cryptographic algorithm" based on FIPS 180 . Acceptable algorithms include SHA-1, SHA-256, {SHA-512.  SHA-1 is not recommended because of known issues with it.

**Comment by michaelklishin** [comment]
Main open question with switching to SHA-256 is how to provide a migration path, including for users
who may be importing definitions.

One way would be to store the algorithm used in the user record and fall back to MD5 if none given, assuming it's a legacy database.

**Comment by gmr** [comment]
Agreed with storing the hash type in the new format, defaulting to sha256 and setting to md5 on conversion. Might be overkill, but you might want to consider a configurable salt as well for the new password hashing implementation.

**Comment by freemansoft** [comment]
The salt should be somehow configurable also.

>PA-DSS requires that each password must have a unique input variable that is concatenated with the password before the cryptographic algorithm is applied

**Comment by michaelklishin** [comment]
@freemansoft @gmr we [already have a salt](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_auth_backend_internal.erl#L204-211) value. What do you mean by "configurable" when it comes to salt?

**Comment by gmr** [comment]
A string you can define in rabbitmq.config. Based upon the code, it appears the auto-generated salt is stored with the user record. I'm not sure what value that provides, security wise, since you're providing the all the data required to validate the data with the data. OTOH, one could argue that you could get at that value via ``application:get_env/2`` if it were configurable and thus is not more secure than the dynamically computed salt.

**Comment by michaelklishin** [comment]
@gmr agreed. We can make that part pluggable, too. `application:get_env/2` wouldn't be an option if you only steal on disk data, so it can be an improvement for some users.

**Comment by essen** [comment]
With regards to security, the key point of salting is that there's a unique salt per user. Storing it separately or not does very little. Having a single salt in a configuration file does very little security-wise.

People here explain better than me: https://stackoverflow.com/questions/1219899/where-do-you-store-your-salt-strings

**Comment by michaelklishin** [comment]
thanks @essen.

So, trying to narrow down the scope here:

 * We need hashing and password verification functions to be pluggable
 * We need to use sha256 by default

do we care about pluggable ways to generate salt values? In master we already use local time and a unique integer: is this good enough?

**Comment by noahhaon** [comment]
@michaelklishin as @essen stated, the most important property of a salt is that it is unique for each user - the point is to prevent precompute "rainbow table" style attacks.  

I think that your description of the salt algorithm in master meets that criteria, I don't see any value in changing it or otherwise making it pluggable.

**Comment by michaelklishin** [comment]
@noahhaon thank you for the input!

**Comment by michaelklishin** [comment]
PR submitted: https://github.com/rabbitmq/rabbitmq-server/pull/310.

**Comment by baiyusysu** [comment]
In previous RabbitMQ, the password hashing algorithm is that to store the password as :4 bytes salt + md5(4 bytes salt + password).Is this Algorithm changed like salt + sha-256(4 bytes salt + password)?

**Comment by michaelklishin** [comment]
@baiyusysu please use rabbitmq-users for questions. The only thing that has changed is that hashing functions are [now pluggable](http://rabbitmq.com/passwords.html), with SHA-256 being the new default.
