### ISSUE TITLE
Redeliver exclusive queue's message when auto-deleted

### ISSUE THREAD

**Issue by pycuichen** [rabbitmq/rabbitmq-server#271]
When exclusive queue is auto-deleted, the unconsumed message in the queue will be lost, is there a way to redeliver them to another exchange or queue just before it's auto-deleted ?

**Comment by michaelklishin** [comment]
@pycuichen please ask questions on the mailing list. We have ask you to do that before.

There is no. The right thing to do here would be to make queue deletion dead letter all messages in it, but this is potentially a very expensive operation, so we haven't decided on that yet.

**Comment by pycuichen** [comment]
@michaelklishin Okay, got that. I won't do it again.

Thanks for your response.
