### ISSUE TITLE
gRPC protocol

### ISSUE THREAD

**Issue by zs-dima** [rabbitmq/rabbitmq-server#2717]
Could be nice to add gRPC protocol to this list:
https://www.rabbitmq.com/protocols.html

**Comment by michaelklishin** [comment]
This issue foes not have any specifics. What exactly would such "gRPC support" look like? gRPC is based around API endpoints. For what operations? Why do we need this given that we support four protocols already?

 I'm afraid we require issues and ideas to be a little more specific than this. Consider starting a mailing list thread first to discuss this and share some specific examples.
