### ISSUE TITLE
Make The Node Name Settable

### ISSUE THREAD

**Issue by pnovotnak** [rabbitmq/rabbitmq-server#272]
I think this might be a dupe or at least partial dupe of #73, but it's really crampin' my style, so I'd like to make sure you folks upstream know about it, because I cannot imagine I'm the only one.

My use case is; I'm trying to run an application inside of Kubernetes with a Rabbit broker. However, I need persistence. Since I cannot set the hostname via Kubernetes (reported, [as issue 4825](https://github.com/kubernetes/kubernetes/issues/4825) I cannot run Rabbit in the cluster.

For reference: https://github.com/docker-library/rabbitmq/issues/6

**Comment by michaelklishin** [comment]
You [can set node name](http://www.rabbitmq.com/configure.html). If that's not possible with Kubernetes, this sounds like a Kubernetes limitation to me.

**Comment by michaelklishin** [comment]
Running two nodes on the same host is perfectly possible: change the part before the `@`. For example, some of our test suites use `rabbit@hostname` and `hare@hostname`.

**Comment by pnovotnak** [comment]
Sorry for my ignorance! I had seen the RABBITMQ_NODENAME but was not setting up my container correctly.
