### ISSUE TITLE
Fix wording in 3.8.10 release page

### ISSUE THREAD

**Issue by s4uliu5** [rabbitmq/rabbitmq-server#2725]
Hi,

https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.10 page states

> RabbitMQ 3.8.10 is  **a preview** of a maintenance release.

I believe v3.8.10 is not "a preview", so the page could be updated accordingly.

**Comment by michaelklishin** [comment]
Corrected, thanks.
