### ISSUE TITLE
error: Could not get shadow information for NOUSER

### ISSUE THREAD

**Issue by piiskop** [rabbitmq/rabbitmq-server#2726]
I use ONLYOFFICE and ONLYOFFICE uses _rabbit-mq.server_. Every time I restart the server machine where both run, I have to purge and reinstall _rabbit-mq.server_ as it won't restart. Therefore, I first [reported the issue for ONLYOFFICE maintainers](https://github.com/ONLYOFFICE/DocumentServer/issues/1129). From there, I got the suggestion to report it to you.

**Comment by ShockwaveNN** [comment]
> I got the suggestion to report it to you

I suggested that because seems that stopping ONLYOFFICE DocumentServer alltogether and restarting machine without running DocumentServer will cause this error still, so I think it's something wrong on rabbitmq side
