### ISSUE TITLE
RabbitMQ-wrapper-script breaks if "sed" does not have "-E" option.

### ISSUE THREAD

**Issue by nishan** [rabbitmq/rabbitmq-server#273]
rabbitmq-wrapper-scripts break if sed does not have "-E" option.

Not all machines have a version of "sed" which supports "-E" option. Perhaps "-r" is a safer option to use.

I found this on a CentOS 5.11 machine.  I tested on CentOS 6 and Debian 7, where I found the same problem.

**Comment by michaelklishin** [comment]
Kudos to @nishan for submitting #275. The change looks good, so it's a matter of small technicalities to get it in.

**Comment by nishan** [comment]
Thanks @michaelklishin. I have raised a new pull request on stable branch.

https://github.com/rabbitmq/rabbitmq-server/pull/276

**Comment by michaelklishin** [comment]
@nishan I will pull your changes manually in a bit.

**Comment by nishan** [comment]
Oops! Sorry.  Let's try one more time?

https://github.com/rabbitmq/rabbitmq-server/pull/277

**Comment by michaelklishin** [comment]
Note: this was in a packaging script and since recent OS X versions have a modern `sed`, this only needed testing on Linux.

**Comment by dumbbell** [comment]
Since RabbitMQ 3.5.2.
