### ISSUE TITLE
Downgrade rabbitmq-server from version 3.8.9 to 3.7.11

### ISSUE THREAD

**Issue by anandtripathi5** [rabbitmq/rabbitmq-server#2734]
I want to downgrade the rabbitmq-server to a specific version and also the erlang cause the classic format of config is not supported in the newer version of rabbitmq-server. I'm looking for a solution for Ubuntu 18 version.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
