### ISSUE TITLE
Shovel: for AMQP 1.0 sources, message properties are not propagated

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#2745]
This [C# example](https://github.com/olovhoglund/rabbitmq/blob/main/RabbitMQ.AmqpTest/Program.cs) demonstrates publishing of an AMQP 1.0 message with custom application properties. When a Shovel with an AMQP 1.0 source consumes it, it will not propagate the properties to the destination.

**Comment by woppa684** [comment]
Apart from the custom application properties, also not all standard AMQP1.0 properties (see the [spec](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#type-properties)) are propagated. For example "subject" is [missing](https://github.com/rabbitmq/rabbitmq-server/blob/a4cc096728e955168fa8c7e92be7aa26afd759bc/deps/rabbitmq_shovel/src/rabbit_amqp10_shovel.erl#L347), although the spec states:
```
The properties section is part of the bare message; therefore, if retransmitted by an intermediary, it MUST remain unaltered.
```

**Comment by MistarzJan** [comment]
Hey, is there any ETA/progress on this issue? @michaelklishin

**Comment by michaelklishin** [comment]
Besides the fact that by 3.11 or 3.12 AMQP 1.0 will be the message container used internally by RabbitMQ for all protocols, I don't have much to share. We do not offer ETA, this is open source software. If you want something done, contribute it.

**Comment by michaelklishin** [comment]
Message containers in 3.13 largely address this, if any specific property is missing, please file new specific issues.

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-server/issues/7508 is highly relevant, too.
