### ISSUE TITLE
how can i set path_prefix for windows version

### ISSUE THREAD

**Issue by ElanCao** [rabbitmq/rabbitmq-server#2760]
Dears,
From this [official page](https://www.rabbitmq.com/management.html) i understand i can set path_prefix for rabbitmq server.
but this guide is for linux, how can i set this param for windows version after i run `rabbitmq-plugins enable rabbitmq_management`?
Thank you guys.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
