### ISSUE TITLE
which one is better for saving messages in a chat app, rabbitmq rpc or rabbitmq work(task) queues?

### ISSUE THREAD

**Issue by hosmoh** [rabbitmq/rabbitmq-server#2779]
I have a chat application that is written with node.js and consists of two micro-services: one for connecting to the database and storing messages and the other which is for chat and uses socket.io.

These two micro-services have been deployed on the server using docker.

When a user sends a message, I immediately broadcast that message in the chat and then use RabbitMQ to save it to the database.

Am i doing this right and if the answer is yes, which is more suitable for me between RabbitMQ RPC and RabbitMQ Work Queues ?

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
