### ISSUE TITLE
rabbitmq prometheus metrics error

### ISSUE THREAD

**Issue by jiangxinlingdu** [rabbitmq/rabbitmq-server#2780]
i use rabbitmq 3.8.5 
![image](https://user-images.githubusercontent.com/6373972/106577710-a80ffb80-6579-11eb-9202-346538154573.png)

![image](https://user-images.githubusercontent.com/6373972/106577763-b78f4480-6579-11eb-9836-a1a190662a67.png)
rabbitmq prometheus metrics  rabbitmq_queue_messages_published_total  is counter type but have a little problem，rabbitmq_queue_messages_published_total   can down 
![image](https://user-images.githubusercontent.com/6373972/106577978-fc1ae000-6579-11eb-9d38-c4ca7681561b.png)
This question bothers me a little……

i use http api, also have are problems
![image](https://user-images.githubusercontent.com/6373972/106578350-63d12b00-657a-11eb-9774-ea7717d2c93b.png)

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
