### ISSUE TITLE
Schedulers continue running at max load for an extra 12 minutes after 50k queues import - exchange and queue bindings fail to create - no crashes reported

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-server#2800]
Importing 50k queues from definitions finishes, the Erlang VM continues working at max load for an extra 12 minutes, and then everything returns back to normal, but the exchange and the queue bindings never complete importing. No crashes or errors in the logs.

This is single node RabbitMQ 3.8.11 running on Erlang 23.2.3 via `rabbitmq:3.8.11-management` Docker image.

I am attaching the exact definitions that exhibit this behaviour. Does anything look wrong with it? [rabbitmq-definitions.json.zip](https://github.com/rabbitmq/rabbitmq-server/files/5945923/rabbitmq-definitions.json.zip)

What is the worker pool doing during this period?

<img width="2707" alt="Screenshot 2021-02-08 at 18 11 36" src="https://user-images.githubusercontent.com/3342/107264127-8069d900-6a3a-11eb-9561-eb0f949cb75d.png">

related to https://github.com/rabbitmq/rabbitmq-server/discussions/2785

**Comment by gerhard** [comment]
I have just noticed that the exchange didn't have a `topic` entry. I've added it back, and trimmed the queue bindings. Re-running import for the attached definitions. [rabbitmq-definitions-trimmed.json.zip](https://github.com/rabbitmq/rabbitmq-server/files/5945978/rabbitmq-definitions-trimmed.json.zip)

The worker pool works just as hard as before, with many `rabbit_queue_location_min_masters`, `rabbit_queue_master_location_misc and even more `ets` calls.

![image](https://user-images.githubusercontent.com/3342/107266437-6d0c3d00-6a3d-11eb-9a15-7d85daed0134.png)

**Comment by michaelklishin** [comment]
Definition import exits when all import tasks have been submitted. Starting 50K can take several minutes and the process is now concurrent. The calls to `rabbit_queue_location_min_masters` must be from the declarations performed by the import.

There is a dedicated definition work pool, its backlog would be a good indication of whether there are still any items being imported.

**Comment by gerhard** [comment]
The first problem is that the queue bindings never get created.

The second problem is that the exchange doesn't get created.

The last problem is that while creating queues from definitions is faster than declaring them via a single channel (as PerfTest does), the CPU is fully satured for 12 minutes **after** queues are created.

Maybe the exchange fails to create, and then all the bindings fail to create too. Or maybe there is another reason that we are yet to discover. The end-result is that importing the definitions attached above doesn't complete, and it doesn't fail either, so the user won't know what to do. While I can work-around this problem, it seemed worth bringing up.

This is the queue creation timeline & CPU pressure when a single PerfTest declares 50k queues:
![image](https://user-images.githubusercontent.com/3342/107417601-af9d4a80-6b0d-11eb-970b-9546e88f4bcd.png)
![image](https://user-images.githubusercontent.com/3342/107417688-c2b01a80-6b0d-11eb-91fd-027036c4faea.png)

This is when the same 50k queues get imported from a definitions file via the Management UI:
![image](https://user-images.githubusercontent.com/3342/107417965-02770200-6b0e-11eb-87d9-8016e2bd2c58.png)
![image](https://user-images.githubusercontent.com/3342/107418031-1458a500-6b0e-11eb-9496-7f014cca2cdb.png)

> As an aside, notice above that we don't emit metrics for queue creation when importing from definitions.

Queues take 34mins to declare vs 9mins to import (concurrent process with 8 workers explains the elevated CPU utilisation), and that is good, but what seems peculiar is that the CPUs continue running at full speed for another 12 minutes afterwards:
![image](https://user-images.githubusercontent.com/3342/107418234-541f8c80-6b0e-11eb-871e-b106427d9a48.png)

**Comment by michaelklishin** [comment]
I have imported large definitions files recently and haven't noticed this after all virtual hosts are started on all nodes. 

A similar behavior can still happen in environments where the number of CPU cores is too low for the number of virtual hosts in other resources but then it is not really something pathological.
