### ISSUE TITLE
Allow shovel deletion from any node

### ISSUE THREAD

**Issue by oyviaase** [rabbitmq/rabbitmq-server#2807]
Reproduction steps: 
- Start a 3-node cluster
- Create a shovel on any node
- Delete the shovel from a node that it's not running on 
- Experience an error message, unless you do this with the http API then the shovel is deleted but still present on the "Shovel Status" page

The error message seems to be an result of this issue: https://github.com/rabbitmq/rabbitmq-shovel/issues/68 except that it does not work when using the http API

Resolution: RabbitMQ should delete the shovel on the correct node regardless of which node that receives the delete request

**Comment by chadknutson** [comment]
There is also a minor issue deleting the shovel using rabbitmqctl from a different node than the shovel.  The shovel is removed from the list of shovels, but the shovel status view in manager still shows the shovel.  The status shows running, but the shovel in fact is not operational.

The only way I have found to remove from the shovel status view is to restart the shovel plugin on the node where it was running.
