### ISSUE TITLE
Multiple policies for a queue

### ISSUE THREAD

**Issue by lechen26** [rabbitmq/rabbitmq-server#2818]
Hi

i'm using rabbitmq 3.8.2 and recently noticed only single policy get applied to queue.

i have a policy that sets ha-all on all queues and another one that deleted queue (expiration) after specific time of not used, except specific queues which i wanted to exclude.
seems like only the first policy get applied and i see now its by design.

was there any improvements here?
create a single policy with both things will cause the excluded queues to not have also the first policy so its not somethiing we want.

any idea?
10x

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
