### ISSUE TITLE
Force listen sockets to use the binary option

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#282]
[See this thread](https://groups.google.com/forum/#!topic/rabbitmq-users/J4_A3jrRv3c). The binary option is implied but we don't really enforce it. This is not great usability.

@essen it would be great if we can handle this better on your Ranch branch as well.

**Comment by dumbbell** [comment]
I agree, it would be better to enforce it.

Options `{packet, raw}` and `{reuseaddr, true}` should be enforced as well, IMHO. For example, someone on the mailing-list had problems overriding `tcp_listen_options` because he omitted `reuseaddr`.

**Comment by essen** [comment]
When the project switches to Ranch, those options will be enforced at the listening socket level: `[binary, {active, false}, {packet, raw}, {reuseaddr, true}]`

Setting one of these options, or an unknown option, will trigger a warning in the logs.
