### ISSUE TITLE
Prometheus Plugin "rabbitmq_disk_space_available_limit_bytes " parse error

### ISSUE THREAD

**Issue by Sukiyakijango** [rabbitmq/rabbitmq-server#2825]
hi
used versions: RabbitMQ 3.8.9 Erlang 23.2.2 Prometheus 2.23.0
Prometheus plugin seems to have a conversion problem with "rabbitmq_disk_space_available_limit_bytes", on startuo everything was fine 3GB of the config was converted to bytes... but after 4 days the metric turned from float to string and couldnt be parsed by prometheus anymore making all the metrics of rabbitmq unreachable. 

```
rabbitmq_disk_space_available_limit_bytes "3GB"
# TYPE rabbitmq_erlang_processes_limit gauge
# HELP rabbitmq_erlang_processes_limit Erlang processes limit
```

![image](https://user-images.githubusercontent.com/11349326/108347928-6f129080-71e1-11eb-9b6b-33ad187e48ae.png)

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
