### ISSUE TITLE
Is it possible to restart a dynamic shovel via the HTTP API ?

### ISSUE THREAD

**Issue by fgheysels** [rabbitmq/rabbitmq-server#2834]
We've an issue where we've defined a dynamic shovel on a device (actually a vessel) which has an unreliable / shaky connection.
Often, the shovel stops working because it was unable to connect for x times in a certain period of time.

We were thinking of creating a service which regularly checks the status of the shovel and restart the shovel if the shovel is down.  We'd to this via the HTTP API.
I've found [this](https://github.com/rabbitmq/rabbitmq-shovel-management/pull/34) PR which makes this functionality available, but I cannot find anything regarding getting the status of a shovel or restarting a shovel via the HTTP API.

Could you please extend the documentation with information on how to check the status of a shovel / restart a shovel via the REST API ?
Next to that, it would also be nice if the documentation could be enriched by specifying some details on how many connection attempts in which period of time need to happen before the shovel is terminated.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
