### ISSUE TITLE
channel.open timeout

### ISSUE THREAD

**Issue by wangdonghello** [rabbitmq/rabbitmq-server#2840]
com.rabbitmq.client.ChannelContinuationTimeoutException: Continuation call for method #method<channel.open>(out-of-band=)on channel AMQChannel (amqp://xxx@ip:5672/xxx,4)(#4) time out
    at com.rabbitmq.client.impl.AMQChannel.wrapTimeoutException(AMQChannel.java:308)
    .........

channel.open the number 4 often fail

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
