### ISSUE TITLE
`make package-rpm-rhel7` always fails

### ISSUE THREAD

**Issue by pjk25** [rabbitmq/rabbitmq-server#2848]
As does `make package-deb` and other related goals (but not `make docker-image` or `make package-generic-unix`)

This an unintended side effect of #2823 

The difficulty lies in that `make package-rpm-rhel7` depends on the `RPMS/Fedora/rabbitmq-server.spec` file in https://github.com/rabbitmq/rabbitmq-packaging. However, since that file needs to be updated as part of the release process, we cannot move that file back into this repository without also holding any pushes to the given release branch while the release pipeline is running.

My current thinking is to leave the `package-generic-unix`, `docker-image` and any other non-mutating goals in place, but move `package-rpm-rhel7` (and similar) back to the rabbitmq-packaging repo.

**Comment by michaelklishin** [comment]
@pjk25 can this be closed now?

**Comment by pjk25** [comment]
Yes, thanks @michaelklishin
