### ISSUE TITLE
3.7.3 to 3.8.9 ,  High memory usage about quorum_queue_procs (20G, 80%!!!)

### ISSUE THREAD

**Issue by feiniao886** [rabbitmq/rabbitmq-server#2862]
3.7.3 to 3.8.9 ,  High memory usage about quorum_queue_procs (20G, 80%!!!)

but  queue type: Classic, not Quorum

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
