### ISSUE TITLE
tcp_listener from config file is not respected by the Windows service

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#288]
See #287. Only affects 3.5.4, in which the batch files changed quite a bit.

**Comment by michaelklishin** [comment]
From #287, effective value ends up being:

```
{tcp_listeners,[{"auto",5672}]}
```

instead of

```
{tcp_listeners,[9999]}
```

(where `9999` is the desired port).

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-server/commit/1f61e4fae109561572beca3f0ddc9c7624622126,
https://github.com/rabbitmq/rabbitmq-server/commit/77052f42d1389caedff1f4febdb384a81535d49b,  and  https://github.com/rabbitmq/rabbitmq-server/commit/374901966f8aa6262bed374b55b844ded2eccf21 by @Jakauppila seem to be relevant (and merged after `3.5.4`.

**Comment by michaelklishin** [comment]
This indeed seems to be fixed by the commits above. Will merge `stable` into `master` tomorrow or so and leave a nightly build link to try it out.

sukinsky FYI.

**Comment by michaelklishin** [comment]
@sukinsky please see above.

**Comment by sukinsky** [comment]
@michaelklishin it's ok, will wait for 3.5.5

**Comment by michaelklishin** [comment]
@sukinsky well, I'd like to get a fix confirmation from someone running into this in an environment different from mine. Up to you, of course :)

**Comment by michaelklishin** [comment]
@sukinsky sorry, I was referring to a comment in #287. If you contact me at `michael` in rabbitmq domain, I'd be happy to send you a build of the tip of the `stable` branch (what will be `3.5.5` fairly soon).
