### ISSUE TITLE
Peer discovery: forced removal due to cleanup does not remove it from quorum queues

### ISSUE THREAD

**Issue by f-panahi** [rabbitmq/rabbitmq-server#2882]
rmq version:
3.8.14

enabled_plugins: 

`[rabbitmq_management,rabbitmq_tracing,rabbitmq_peer_discovery_aws,rabbitmq_federation,rabbitmq_federation_management,rabbitmq_shovel,rabbitmq_shovel_management].`

I have a cluster of 3 rmq nodes using AWS peer discovery with tags. I enabled cluster formation node cleanup, to force remove the unknown instances.

```
cluster_formation.node_cleanup.interval = 90
cluster_formation.node_cleanup.only_log_warning = false
```

The issue that I am facing is that the quorum queue does not shrink automatically. If I remove the node from the cluster by `forget_cluster_node` the node will automatically be removed from the quorum queue. But when it is deleted by automatic node cleanup, it does not work.

The expected behavior for any queues or objects in a Rabbitmq cluster is that when a node is removed, all references to be removed including the queue members.

Thanks,

**Comment by ReadyElbow** [comment]
@michaelklishin Is there any update on this? Has it been implemented yet or still outstanding?

**Comment by michaelklishin** [comment]
No updates that I know of. Those who need this behavior are welcome to contribute it.
