### ISSUE TITLE
Improve reduce_memory_usage performance when persisting message to the queue index.

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-server#289]
According to fprof and cachegrind, `push_betas_to_deltas` spends quite a lot of time with `rabbit_queue_index:publish` and FHC bookkeeping, mostly because those functions are called 100k+ times when there's memory pressure and too many messages need to be paged out. Same applies for the `rabbit_variable_queue:stats/3` function. What the function is doing is fine, but perhaps it's easier to update it once with the final value, since while paging, the stats function is called with some defaults that null most of the calculations inside stats.

**Comment by javaforfun** [comment]
After `push_betas_to_deltas`, lots of garbage generated. Paging will continue if no implicit GC happen. I think it's better to do explicit GC after most msg paged, and reduce memory_monitor and update_ram_duration timer (`DEFAULT_UPDATE_INTERVAL` and `RAM_DURATION_UPDATE_INTERVAL`).

**Comment by videlalvaro** [comment]
@javaforfun thanks for the feedback. I've created a separate issue: https://github.com/rabbitmq/rabbitmq-server/issues/290
