### ISSUE TITLE
How to close the process of epmd port

### ISSUE THREAD

**Issue by xhsky** [rabbitmq/rabbitmq-server#2896]
After I use the command (rabbitmqctl stop) to shut down mq, the epmd process is not shut down. How can I shut down the epmd process while shutting down mq?

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
