### ISSUE TITLE
Improve how RabbitMQ handles binary garbage collection

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-server#290]
See comments in #289

**Comment by michaelklishin** [comment]
I don't think this is a blocker for `3.5.5` (given our other recent improvements) but it also doesn't have to wait for `3.6.0`, so labelling this for `3.5.6`, per discussion with @dumbbell.

**Comment by videlalvaro** [comment]
See discussion https://groups.google.com/d/msg/rabbitmq-users/vj_9YGUfDgg/-_fx2BkqAwAJ and follow up messages
