### ISSUE TITLE
rabbitmq-queues broken after upgrade from 3.8.5 to 3.8.14

### ISSUE THREAD

**Issue by gmr** [rabbitmq/rabbitmq-server#2901]
I upgraded a few RabbitMQ clusters from 3.8.5 to 3.8.14 using official deb packages today and noticed an issue with the `rabbitmq-queues` cli.

From a user perspective it errors out with:

```
Re-balancing leaders of classic queues...
Error:
{:noproc, {:gen_server2, :call, [#PID<11978.2586.771>, {:info, [:messages]}, :infinity]}}
```

In the crash logs this is seen as:

```
2021-03-17 17:41:14 =ERROR REPORT====
** Connection attempt from node 'rabbitmqcli-679-rabbit@NODE' rejected. Invalid challenge reply. **
```

This made me think it's a cookie issue, but I am able to run `rabbitmqctl` and `rabbitmq-diagnostics` without issue.

In addition, the info.log looks like the command connected in and started the process:

```
2021-03-17 18:10:22.504 [info] <0.13198.0> Starting queue rebalance operation: 'classic' for vhosts matching '.*' and queues matching '.*'
```

Erlang Version: 23.2.7
RabbitMQ 3.8.14
Ubuntu 16.04.6 LTS

Interestingly I was able to reproduce this on all nodes that upgraded from 3.8.5 to 3.8.14, but on nodes where the cluster was upgraded from 3.7.16, the problem does not exist.

Please let me know if there is any other info you'd like me to collect.

**Comment by gmr** [comment]
I should point out the upgrades were performed as a rolling upgrade. Node 1 was taken offline, packages upgraded, and added back to the cluster, followed by Node 2, etc.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
