### ISSUE TITLE
store queue_index_embed_msgs_below in BQ state so it's not read from the env for every publish

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-server#291]
For every message that enters the broker, we have to determine if the message will be persisted to the msg_store or to the queue_index. To do that we need to determine what's the configured IndexMaxSize value. At the moment this value is fetch from the application environment for every publish.

See: https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_variable_queue.erl#L1473

**Comment by michaelklishin** [comment]
Assuming this is safe for `3.5.5`.

**Comment by videlalvaro** [comment]
@michaelklishin the only thing we lose, kinda, is the ability to change this value at runtime. Not sure anyone is doing that. We can still change it with some rabbit eval magic
