### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [rabbitmq/rabbitmq-server#2912]
[jw@cn05 rabbitmq-server]$ make VERBOSE=1 -j$(proc)
-bash: proc: command not found
make[1]: Entering directory '/home/jw/rabbitmq-server/deps/rabbit_common'
Error: No Makefile to build dependency /home/jw/rabbitmq-server/deps/jsx.
make[1]: *** [erlang.mk:4512: deps] Error 2
make[1]: Leaving directory '/home/jw/rabbitmq-server/deps/rabbit_common'
make: *** [erlang.mk:4512: deps] Error 2
[jw@cn05 rabbitmq-server]$

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
