### ISSUE TITLE
Web MQTT connection is not closed when JWT token expires

### ISSUE THREAD

**Issue by fcovatti** [rabbitmq/rabbitmq-server#2922]
I am testing a mqtt connection from the a paho mqtt client into the RabbitMQT Websocket MQTT authenticating with the OAuth plugin.

I have setup a OAuth token expiration of 30 minutes.

I keep sending messages every 2 to 3 minutes to the broker.

The keep alive from the client is 30 seconds.

The behaviour I am seeing is that for 30 minutes I have data reaching the broker, and after that for some 20 minutes of no data reaching the broker queues and then the connection is closed.

After investigating this issue with MQTT debug on_log messages, I was able to figure out the problem.

What happens is that I have a dead loop on the connection between the MQTT client and the broker.

The MQTT client connects to the broker and authenticates using the JWT which authorizes the client to publish to specific topics.

When the token used to authenticate to the broker expires, the broker does not close the MQTT websocket connection and keeps responding the MQTT keep alive packets.

So the MQTT client keeps trying to publish the readings into the broker.

Only when the max_inflight_messages is reached (by default the number is 20 for the MQTT Client) that the client drops the connection and reconnects. The inflight_messages are the number of messages to be published. As we use QoS=1, the MQTT client keeps trying to publish the messages until the broker confirms them.

I could not find out if there is a configuration in the RabbitMQ to force the connection to be closed when the token exipres or to make the keep alive packets stop being answered.

A workaround that I have performed is to monitor on the client side the connection expiration (JWT expiration time) and then restart the connection from the client.

But I believe this broker behavior is not correct and we should be able to drop the connection once the token expires or to stop answering keep alive packets once the user is not authenticated anymore.

Some of the logs:

```
2021-03-22 18:15:00.398 [error] <0.8705.0> Provided JWT token has expired at timestamp 1616436899 (validated at 1616436900)

2021-03-22 18:15:00.398 [error] <0.8705.0> access to exchange 'amq.topic' in vhost '/' refused for user 'xyz', backend rabbit_auth_backend_oauth2 returned an error: "Provided JWT token has expired at timestamp 1616436899 (validated at 1616436900)"

2021-03-22 18:15:00.399 [error] <0.8705.0> Channel error on connection <0.8674.0> (10.40.2.46:49928 -> 10.40.3.72:15675, vhost: '/', user: 'xyz'), channel 2:

operation basic.publish caused a channel exception access_refused: access to exchange 'amq.topic' in vhost '/' refused for user 'xyz', backend rabbit_auth_backend_oauth2 returned an error: "Provided JWT token has expired at timestamp 1616436899 (validated at 1616436900)"
```

**Comment by michaelklishin** [comment]
We are aware of this but there is no easy solution for MQTT and specifically Web MQTT users. For AMQP 0-9-1 we have introduced a new protocol frame that allows clients to refresh the token (using a refresh token which is typically issued for JWT tokens) and update the token used by the connection. Unfortunately we cannot do the same for MQTT: we do not maintain any MQTT clients and MQTT development process is very slow moving. In addition, unlike STOMP, MQTT is not an extensible protocol and it has terrible limitations around server-to-client error communication. So we cannot provide a sensible error to the client either.

Closing the connection is not a great solution. The OAuth 2 way is to use a refresh token but for long-lived connections there needs to be a way for clients to detect when the token has expired and refresh it one way or another.

What you have implemented is actually an optimal approach. The only sensible and easy to implement option for me is to stop sending keepalive responses.

**Comment by michaelklishin** [comment]
Now that I thought of how this would work for MQTT, it can still lead to a lot of confusion if an expired token led to missed keepalive responses: both apps and operators could interpret it very differently.

Since there is no decent solution without MQTT protocol evolution that would allow for sensible server-to-client communication, we won't work on this in the foreseeable future. So your workaround is the best approach.
