### ISSUE TITLE
User limit `max-queues` reported as not valid

### ISSUE THREAD

**Issue by aitorpazos** [rabbitmq/rabbitmq-server#2928]
[In release `3.8.10`](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.10) it was mentioned that `max-queues` can be set as a user limit.

```
# limits user "user-e8d3f85c" to up to five connections, ten channels and a fifty queues
rabbitmqctl set_user_limits "user-e8d3f85c" '{"max-connections": 5, "max-channels": 10, "max-queues": 50}'

# clears the maximum number of queues limit for the user
rabbitmqctl clear_user_limits "user-e8d3f85c" "max-queues"
```

However, trying to set it in `3.8.14` I get an error:
```
$ rabbitmqctl set_user_limits 'admin' '{\"max-connections\": 750, \"max-channels\": 1500, \"max-queues\": 200}'
Setting user limits to "{"max-connections": 750, "max-channels": 1500, "max-queues": 200}" for user "admin" ...
Error:
Unrecognised terms [{<<"max-queues">>,200}] in user-limits
```
Also it is not showing in the UI:

![image](https://user-images.githubusercontent.com/2015196/112512537-5fabd780-8d8b-11eb-96df-218143653fcc.png)

**Comment by michaelklishin** [comment]
Yes, that is a copy-and-paste artifact. `max-queues` is a per-virtual host limit. Per-user limits are limited to connections and channels (https://github.com/rabbitmq/rabbitmq-server/pull/2380).

**Comment by michaelklishin** [comment]
The release notes were updated. Thanks for spotting this.
