### ISSUE TITLE
`rabbitmqctl report` should accept `--formatter` command line option

### ISSUE THREAD

**Issue by roylez** [rabbitmq/rabbitmq-server#2932]
I get it the new default formatter is more human friendly, but for people who understand Erlang, verbatim Erlang terms makes more sense. Also `--formatter erlang` would make the output backward compatible.

If `status` and `cluster_status` all accept `--formatter erlang` I do not see why this should not be an option for `report`. 

Also, outputting escape sequences like `\e[m` in report does not make any sense.

**Comment by michaelklishin** [comment]
The reason why not every command can accept `--formatter` or support every formatter is that not every output makes sense in, say, JSON.

`rabbitmq-diagnostics report` has never produced "Erlang output" and I honestly fail to see how that would make much sense. Not only it can output really substantial amounts of data which can be moderately difficult to read,
converting that to an Erlang term will make it even worse.

`rabbitmq-diagnostics report` is a combination of `rabbitmq-diagnostics status` and several `rabbitmq-diagnostics list_*` commands, most of which individually accept some alternative formatters.

Those "output sequences" are for section header formatting in bold.

**Comment by michaelklishin** [comment]
Here is what the header formatting (reused from `rabbitmq-diagnostics status`) looks like:

![Screenshot 2021-03-26 at 15 32 39](https://user-images.githubusercontent.com/1090/112631892-8419b980-8e48-11eb-9ca3-b52ea16e574f.png)

Introduced in 3.8, this has been positively received. I'm afraid this is the first time someone wants `report` to dump an Erlang term. But the key issue here is that `report` is literally a combination of a few more specific commands,
for some of which this kind of formatting would be possible and for others, it would not.

I think our team would rather spend out time elsewhere. We want RabbitMQ to produce less Erlang output, not more, since
99% of users do not want to look at Erlang terms.

**Comment by roylez** [comment]
I am not saying the new output is bad. Actually I think the new default
output formatter for commands like `rabbitmqctl status` and `rabbitmqctl
cluster_status` is a lot better than before. However, `rabbitmqctl report`
command is a different thing.

Like `free` command output is for someone to quickly get an idea of general
memory usage, `cat /proc/meminfo` is for more skilled people to do in
detail analysis. They are targeting different use cases. It is better to be
more human friendly for the former, and it is better to make it script
friendly and more informative for the latter.

`rabbitmqctl report`, if I am not misunderstanding it, designed to get as
much info as possible from the cluster so that someone could carry out an
analysis using it to tell if the cluster is okay and where the problem
could be. In this kind of use case,

- Escape sequence does not make it nicer but only makes parsing a little
more difficult, as the output will be dumped to a file. Last report file I
got was 87MB in size, and I doubt some bold fonts in it would make it more
readable as I would use more awk on it than less.

- Humanized breakdown of node status does not make it more helpful because
the more stable the structure, the more likely people could reuse previous
tools on it. Previous versions' change of section heading is okay..ish, but
for 3.8, I could not even expect section content format to be stable any
more. I do not mind the output is csv or json or Erlang, as long as it is
stable across versions, but humanized text? Definitely not something I
would put trust on.

- I forgot to mention previous version of report includes detailed
node/cluster status and environment from the other nodes. Now they are all
gone. The idea of a report is to dump EVERYTHING. No more memory, file
descriptor, sockets, process, disk and other statistics from the other
nodes. If it is not complete, why should we use it instead of running a
bunch of commands individually?

I am the first one complaining here because probably very most people
relies on individual commands rather than full reports, but for people who
almost exclusively work on full reports, changes in 3.8 report format is a
big step backwards.

**Comment by michaelklishin** [comment]
Our team talks to our users every day and we often ask people to produce reports or get them via [support tools](https://github.com/rabbitmq/support-tools). This is the first time someone describes new output is a big step backwards.
So I'm afraid this is not a common perception in the community and so we won't be changing it.

`rabbitmq-diagnostics report` was not meant to be parsed. It is meant to be inspected by a human as is. And it produces a lot of information, in fact, often people feel it is too much.

Some of the commands that are included into it (e.g. `rabbitmqctl list_*`) may support alternative formatters.

I'm pretty sure `report` never included environment information from other nodes. There is `rabbitmq-diagnostics cluster_status`  focuses on cluster membership and alarm/maintenance/partition state of each individual node.

Finally, starting with 3.7 RabbitMQ CLI tools can be extended from plugins so you can produce your own version of `report`.
