### ISSUE TITLE
[Wrong format rabbitmqctl list_permissions]

### ISSUE THREAD

**Issue by letanloc1998** [rabbitmq/rabbitmq-server#2947]
```shell
rabbitmqctl list_permissions -p vhost-gateway-desktop-sendktop-send
Listing permissions for vhost "vhost-gateway-desktop-send" ...
user    configure       write   read
user-gateway-desktop    .*      .*      ^$
user-service    .*      ^$      .*
```

wrong tab header when run command `rabbitmqctl list_permissions`

Thank

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
