### ISSUE TITLE
Docker secrets for default users not loading.

### ISSUE THREAD

**Issue by nblazincic** [rabbitmq/rabbitmq-server#2962]
Docker image 3.8.14-management-alpine not loading default user/password  via RABBITMQ_DEFAULT_USER_FILE or PASS variable pointing to docker secrets (ie, /run/secrets/rmq_username)

rolling back to 3.8.5 image works.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
