### ISSUE TITLE
Management UI displays default Prometheus TLS port even if it is overridden

### ISSUE THREAD

**Issue by josetesan** [rabbitmq/rabbitmq-server#2975]
Thank you for using RabbitMQ.

I'm using rabbitmq 3.8.14 on RHEL7, and have changed default prometheus port ( via prometheus.ssl.port on rabbitmq.conf ) to 9090.

But the UI displays SSL port as 15691, whilst the 9090 is the one configured and , actually, working.

## Prometheus snippet on rabbitmq.conf

prometheus.ssl.port = 9090

## Actual UI

![imagen](https://user-images.githubusercontent.com/383401/114717906-d0fcfb80-9d35-11eb-8303-2d2ace91bb8a.png)

**Comment by michaelklishin** [comment]
What does

``` shell
rabbitmq-diagnostics listeners -q
```

output?

**Comment by josetesan** [comment]
nterface: [::], port: 15691, protocol: https/prometheus, purpose: Prometheus exporter API over TLS (HTTPS)

**Comment by michaelklishin** [comment]
Then it has nothing to do with management UI. The listener is stored with the default port instead of the actual effective one.
