### ISSUE TITLE
Replicate rabbitmq_auth_backend_cache table across the cluster

### ISSUE THREAD

**Issue by mced** [rabbitmq/rabbitmq-server#2977]
I've a suggestion to make about `rabbitmq_auth_backend_cache`.

For now, `rabbitmq_auth_backend_cache` uses a ETS table, thus it is not replicated across the cluster, it only exists on the node.

Is there a way to make the backend caches replicated ?

Indeed `rabbitmq_auth_backend_cache` installed on a n-nodes cluster behind a dns loadbalancer won't behave like it was setup on single node.

context: https://groups.google.com/g/rabbitmq-users/c/0yo5xX-FoJ4

**Comment by michaelklishin** [comment]
Sorry but we won't do it. It's not worth the effort. The plugin solves the problem it was developed to solve: cut the absolute majority of traffic to external services (LDAP, HTTP), with its current design.

The only downside is that the first operation to encounter a cache miss will happen every N seconds or minutes on every node.
