### ISSUE TITLE
when publish message  with confirm, confirm  ack wait long time will lead  create channel spent long time ?

### ISSUE THREAD

**Issue by CrackerGit** [rabbitmq/rabbitmq-server#2997]

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
