### ISSUE TITLE
Join_Cluster returning error 'src/rabbit_mnesia.erl', line: 227

### ISSUE THREAD

**Issue by jlalanda** [rabbitmq/rabbitmq-server#3008]
Hello,

I have posted my problem on the google groups and didn´t got any response.

So this is my problem:

I cannot create a cluster of two windows machines running the same rabbitmq Version and erlang version. (RabbitMQ 3.8.14 and Erlang 23.3.1)

-Both machines ping each other by ip and by its hostname. And for reassuring that i configured the ip and FQDN on the hosts file
-cookie is exactly the same between the folders of the user running the windows service and the windows folder
-All of the ports are opened between both machines (i have done the telnet client test for all ports)
-Both nodes run rabbitmq successfully 
-Also run the following commandos stop_app, reset and start_app on the other onde just to guarantee that is all ok.

When i try to join clusters this is the error im getting:

Clustering node rabbit@Machine1 with rabbit@Machine2
Error:
{:badarg, [{:rpc, :rpcify_exception, 2, [file: 'rpc.erl', line: 467]}, {:rpc, :call, 5, [file: 'rpc.erl', line: 410]}, {:lists, :foldl, 3, [file: 'lists.erl', line: 1267]}, {:rabbit_mnesia, :discover_cluster, 1, [file: 'src/rabbit_mnesia.erl', line: 795]}, {:rabbit_mnesia, :join_cluster, 2, [file: 'src/rabbit_mnesia.erl', line: 227]}]}

This are the commands i am doing:
-reset
-stop_app
-join_cluster rabbit@Machine2

This is the group i posted my problem:
https://groups.google.com/g/rabbitmq-users/c/tQBttqsQKz4/m/AbQBqAvcAwAJ

Can you please check what is the problem?

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
