### ISSUE TITLE
Getting 403 Forbidden Error while trying to download rabbitmq-server rpm

### ISSUE THREAD

**Issue by Yogiraj-Suryakant-Tambake** [rabbitmq/rabbitmq-server#3018]
Steps to reproduce

wget https://dl.bintray.com/rabbitmq/all/rabbitmq-server/3.7.14/rabbitmq-server-3.7.14-1.el7.noarch.rpm
or 
curl https://dl.bintray.com/rabbitmq/all/rabbitmq-server/3.7.14/rabbitmq-server-3.7.14-1.el7.noarch.rpm

You will receive 403 Forbidden Status.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
