### ISSUE TITLE
rabbitmq_peer_discovery_aws appears to be missing from 3.8.15

### ISSUE THREAD

**Issue by KyronSr** [rabbitmq/rabbitmq-server#3023]
I have an automated process which downloads RabbitMQ and installs it as part of my daily build process.  Yesterday, 3.8.14 was downloaded and ran through just fine.  Today, 3.8.15 was downloaded and my process failed.  Tracked it down to this error:

[exec] amazon-ebs: rabbitmq_peer_discovery_aws
--
[exec] ==> amazon-ebs: Error:
[exec] ==> amazon-ebs: {:plugins_not_found,   [:rabbitmq_peer_discovery_aws]}

I script I am using is pretty simply to install:
(as part of a packer sript):

`
	"curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash",
	"curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash",
	"sudo yum install rabbitmq-server -y",
	"sudo rabbitmq-plugins --offline enable rabbitmq_peer_discovery_aws"
`

I tried this manually on a local server so I could see what was installed and it does appear the plugin is entirely missing:

![aws missing](https://user-images.githubusercontent.com/16656890/116986798-263d8480-acc6-11eb-969f-0fc1b3a57f1c.png)

Was this intentional and is there an alternative way to install?

**Comment by KyronSr** [comment]
Note, using the same steps above but, instead, forcing 3.8.14, it works:

`
sudo yum install rabbitmq-server-3.8.14 -y
`
![3 8 14](https://user-images.githubusercontent.com/16656890/116989262-723df880-acc9-11eb-8e89-984821e0e6e2.png)

**Comment by michaelklishin** [comment]
It wasn't intentional.

You can build the plugin and copy it to the plugins directory just like you can with any other plugin.

**Comment by mh21** [comment]
Hi Michael,

for clusters running on aws with peer discovery and with automatic package updates enabled (eg. via dnf-automatic), this prevents the rabbitmq server from coming up again after the update, basically bringing down the cluster.

Cheers

Michael

**Comment by michaelklishin** [comment]
We understand that and `3.8.16` will ship shortly,

**Comment by KyronSr** [comment]
Thanks!  Temporarily, I've specified the 3.8.14 version in my scripts but once this has been fixed, I can go back to getting the latest.

**Comment by michaelklishin** [comment]
`3.8.16` is being produced. I have verified that the plugin is included into it using and alpha build (and several package types).

**Comment by michaelklishin** [comment]
[`3.8.16`](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.16) is out.

**Comment by KyronSr** [comment]
I can confirm the new release has solved our problem.  Thank you for the quick turnaround.
