### ISSUE TITLE
Consider non-Erlang alternative for configuration files

### ISSUE THREAD

**Issue by curtisleefulton** [rabbitmq/rabbitmq-server#3031]
Many of the RabbitMQ core plugin configurations files use the Erlang language format instead of JSON or YAML. This makes your docs difficult to understand, as most of us do not speak Erlang. Additionally, the Erlang format also takes considerable whitespace as compared to other configuration formats, which makes your docs difficult to navigate.

Please consider standardizing on a configuration format that is not Erlang.

**Comment by michaelklishin** [comment]
We already have: [an ini-style format](https://www.rabbitmq.com/configure.html#config-file) has been available since 3.7.0 (October 2019).

**Comment by michaelklishin** [comment]
Almost all doc guides already use the "new" ini-style format. Please elaborate as to what specifically you have found difficult to read?

`advanced.config` examples are used either where they are necessary (Erlang term queries) or where it makes sense to provide at least one broad example in both formats (TLS listener settings) because some of them may eventually have to move to the Erlang term format.

**Comment by michaelklishin** [comment]
[`rabbitmq.conf.example`](https://github.com/rabbitmq/rabbitmq-server/blob/v3.8.x/deps/rabbit/docs/rabbitmq.conf.example) demonstrates most common settings in the "new" format.
It has an `advanced.config` counterpart that is now limited only to the settings not supported in the ini format.

**Comment by curtisleefulton** [comment]
The "new" ini-style format is lovely. I don't see it used in these plugins (perhaps just a docs issue?):

- https://www.rabbitmq.com/shovel-static.html#example-config
- https://www.rabbitmq.com/ldap.html#ldap-tls

**Comment by curtisleefulton** [comment]
The shovel example config is particular incomprehensible, it's what prompted me to file this issue. :)

**Comment by michaelklishin** [comment]
Static Shovel and LDAP queries is one example of complex data structures that cannot realistically be expressed in the ini-style format.

Use [dynamic Shovels](https://www.rabbitmq.com/shovel-dynamic.html), their definitions are JSON documents (just like with all runtime parameters).
