### ISSUE TITLE
exchange.deleted is missing arguments when deleting exchanges implicitly via deleting its virtual host

### ISSUE THREAD

**Issue by copiltembel** [rabbitmq/rabbitmq-server#3042]
`exchange.deleted` (amq.rabbitmq.event) is missing properties.headers.arguments when deleting exchanges implicitly via deleting their vHost

How to reproduce:

1. Run a listener on /amq.rabbitmq.event for `exchange.created` and `exchange.deleted`
2. Create a new vHost
3. Create an exchange in your vHost with some arguments (I used a boolean value). You should receive an `exchange.created` event containing those arguments.
4. Delete the vHost. You should receive an event  `exchange.deleted` for the above created exchange. This event DOES NOT contain the above arguments.
Hope this helps!

**Comment by michaelklishin** [comment]
I'm surprised that those individual exchange deletion events are event emitted. Why do you need this information? If a virtual host is deleted, you cannot do much with the entities in it.

**Comment by copiltembel** [comment]
Just to react to the deletion of the exchange. I have an app that creates some entities when a new exchange is created, and it needs to destroy them when the exchange is deleted.

I could react to the deletion of the vHost, but it just makes more sense to me to react to opposite events.

**Comment by michaelklishin** [comment]
We won't emit an event for every single entity deleted in it. It is a lot more pragmatic to react to virtual host deletion instead.

**Comment by michaelklishin** [comment]
I cannot observe any difference between deletion of an individual exchange vs. its entire virtual host.

When deleting a single exchange:

``` ruby
{
  "user_who_performed_action"=>"guest",
 "name"=>"x2.to-delete",
 "vhost"=>"vh1",
 "timestamp_in_ms"=>1621236332564
}
```

When deleting an entire virtual host:

``` ruby
{
  "user_who_performed_action"=>"rmq-cli",
  "name"=>"x2.to-be-deleted",
  "vhost"=>"vh1",
  "timestamp_in_ms"=>1621236547332
}
```

**Comment by michaelklishin** [comment]
`exchange.delete` does not contain all of the same properties that `exchange.created` does:

``` ruby
```

``` ruby
# Consumed an event of type exchange.created
{
 "user_who_performed_action"=>"guest",
 "policy"=>"",
 "arguments"=>[],
 "internal"=>false,
 "auto_delete"=>false,
 "durable"=>true,
 "type"=>"direct",
 "name"=>"x3",
 "vhost"=>"vh1",
 "timestamp_in_ms"=>1621236753749
}
```

``` ruby
# Consumed an event of type exchange.deleted
{
 "user_who_performed_action"=>"guest",
 "name"=>"x3",
 "vhost"=>"vh1",
 "timestamp_in_ms"=>1621236779903
}
```
