### ISSUE TITLE
Connection and Queue tab details are missing when rabbitmq is deployment in kubernetes environment

### ISSUE THREAD

**Issue by pachalk** [rabbitmq/rabbitmq-server#3053]
We have two environments where Rabbitmq servers are deployed one is docker-compose and other is kubernetes clusters, we have same configurations for both the environments but we are not getting details when clicking on "Connection" and "Queue" tab in kubernetes environment but its working in docker-compose. 
In kubernetes we are using rabbitmq:3.8.5-alpine, can anyone help me to resolve this issue

![image-2021-04-19-11-32-46-209](https://user-images.githubusercontent.com/51923946/118996312-a73e8200-b93c-11eb-91e5-93bb2523b4f1.png)

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
