### ISSUE TITLE
Reconnect to LDAP via load balancer hostname

### ISSUE THREAD

**Issue by davelee53** [rabbitmq/rabbitmq-server#3088]
hi,
   We are running into the issue that our RabbitMQ LDAP plugin is failing to reconnect to the LDAP cluster via a loadbalancer.  We have some ldap server nodes that are all connected via the loadbalancer hostname like ldaps://ldap.  
We periodically have to cycle our ldap server nodes for maintenance.  Therefore any cached/pooled connections to the ldap node that is being cycled will be disconnected. It seems this ldap plugin is not able to purge those connections if they were established via virtual or load balancer hostname.   We are currently using RabbitMQ v3.7.25 which should have the fix from this [previous reported issue.](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/issues/65#issuecomment-295654745)
Our current configurations:
auth_ldap.servers.1 = ldap   (a single connection to the loadbalancer host)
auth_ldap.connection_pool_size = 256
auth_ldap.idle_timeout = 50000  

Thanks!

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
