### ISSUE TITLE
Sovel Does not restart after "socket_closed_unexpectedly"

### ISSUE THREAD

**Issue by LeonKarabchevsky** [rabbitmq/rabbitmq-server#3105]
We are using a shovel to forward messages between 2 machines.
Sometimes we get the following error: " Shovel ##### in virtual host '/' detected destination connection failure: socket_closed_unexpectedly"
After this message rabbitmq memory consumption raises significantly until hitting the "memory high watermark" and staying in this state until we manually restart the sovels. Looking at the shovels statuses they appear as **running** 
Attached are the logs and "rabbitmqctl report".

[report.txt](https://github.com/rabbitmq/rabbitmq-server/files/6654161/report.txt)
[log.txt](https://github.com/rabbitmq/rabbitmq-server/files/6654163/log.txt)

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
