### ISSUE TITLE
Slow subscribers on federation cluster

### ISSUE THREAD

**Issue by bassrob** [rabbitmq/rabbitmq-server#311]
Hi team,

Not so much an issue but this has the potential to be problematic...

Should a subscriber, whose queue is bound to a federated exchange, be able to consume more than ~1,500 sub 50 byte, non-mandatory, non-immediate, non-persisted messages per second?

Using the official .NET client for RabbitMQ (from NuGet), with no frills publishing or subscribing (one connection and one channel for each), I'm able to publish 50,000 messages in under 2 seconds but the subscriber (connected to the federated cluster) is *extremely* slow to catch up; consuming only around ~1,500 messages per second.

I've also wrapped the .NET client to achieve a higher throughput for both the publisher and the subscriber but the subscriber on the federated cluster still suffers the same symptoms:

**Publish Cluster**
![slow federation - publish cluster](https://cloud.githubusercontent.com/assets/10614665/9851177/3fc54dae-5aef-11e5-8af6-3fbc6198b00f.png)

**Subscriber Cluster**
![slow federation - subscriber cluster](https://cloud.githubusercontent.com/assets/10614665/9851179/3fcb2206-5aef-11e5-98c9-0e0c2b9d9dae.png)

Is this expected?

My setup:

* Cluster of 2 virtual Windows nodes for publishing, both dual core 2.67GHz with 4GB RAM
* Cluster of 2 virtual Windows nodes for subscribing, both dual core 2.67GHz with 4GB RAM
* All exchanges are federated, with a policy matching anything ending with ".exchange"

**Comment by bassrob** [comment]
Just to follow up, the publishing nodes are running version 3.5.1 of the RabbitMQ server and the subscriber nodes are running 3.5.1 and 3.5.4.  All are running on Windows.


Thanks guys,

Rob

**Comment by michaelklishin** [comment]
Please ask questions on the mailing list.

1.5K messages is not a high number. There can be many reasons for what you see, from [low consumer utilisation](https://www.rabbitmq.com/blog/2014/04/14/finding-bottlenecks-with-rabbitmq-3-3/) to #227 to consumer getting overwhelmed or being blocked by something.

Feel free to try 3.5.5.RC2. Given that you use .NET client 3.5.x, it has concurrent delivery dispatch with per-channel ordering guarantees.
