### ISSUE TITLE
Setting X-Content-Type-Options for HTTP API responses

### ISSUE THREAD

**Issue by kamilbrodowski5** [rabbitmq/rabbitmq-server#3111]
Hi, I had a security audit in which we do a scan using tools like OWASP, Qualys .

An application should have  headers like the below :

X-Content-Type-Options HTTP Header missing on port 8443.

X-Content-Type-Options HTTP Header missing on port 9060.

X-XSS-Protection HTTP Header missing on port 9060.

 

8443 is managment plugin port HTTPS

9060 is managment plugin port HTTP

 

I have below setting in advanced.config and this headers works:

   {rabbitmq_management,

    [

        {content_security_policy, "script-src 'self' 'unsafe-eval' 'unsafe-inline'; object-src 'self' "},

        {strict_transport_security,"max-age=31536000; includeSubDomains"}

    ]}

 

how can I set X-Content-Type-Options and X-XSS-Protection ?

**Comment by lhoguin** [comment]
Neither seem to be supported at the moment. Though `X-XSS-Protection` doesn't seem terribly useful nowadays since it's handled by `Content-Security-Policy` now.

**Comment by michaelklishin** [comment]
You don't have to use `advanced.config` to control [CSP](https://www.rabbitmq.com/management.html#csp) or HSTS.

**Comment by kamilbrodowski5** [comment]
@lhoguin is adding this headers in plans? When?

**Comment by lhoguin** [comment]
There are no plans that I know of. It would be a fairly trivial contribution since you can copy what has been done for `content_security_policy` for example.

**Comment by michaelklishin** [comment]
I'm going to close this but we'd consider a pull request that adds support for one more header. Here's my reasoning:

 * `X-XSS-Protection` is [effectively superseded by `Content-Security-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) according to MDN. We already [support CSP](https://www.rabbitmq.com/management.html#csp)
 * You can run RabbitMQ behind Nginx, Apache or any proxy of you liking and have full control over what HTTP headers are used that way. There is no way RabbitMQ HTTP API can match the configurability of a full blown HTTP server or proxy
