### ISSUE TITLE
RabbitMQ on Apple Silicon not working

### ISSUE THREAD

**Issue by thsubaku9** [rabbitmq/rabbitmq-server#3128]
RabbitMQ doesn't seem to be working on apple silicon (tried using rosetta and installed using brew). Reproduction steps as follows ->

1.` arch -x86_64 brew install rabbitmq`
2. start the brew service-> local socket address is not accessible
3. alternatively don't start the brew services and run `rabbitmq-server` 
/usr/local/sbin/rabbitmq-server: line 153: 51226 Segmentation fault: 11  start_rabbitmq_server "$@"

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
