### ISSUE TITLE
missing eldap plugin in directory 

### ISSUE THREAD

**Issue by spham** [rabbitmq/rabbitmq-server#3130]
hi

```
sudo rabbitmq-plugins enable eldapEnabling plugins on node rabbit@adrmq01d:
eldap
Error:
{:plugins_not_found, [:eldap]}
```

ls /usr/lib/rabbitmq/lib/rabbitmq_server-3.8.17/plugins | grep eldap

not return any eldap plug in

test on redhat 7.9

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
