### ISSUE TITLE
rabbitmq boot failed

### ISSUE THREAD

**Issue by fansgit** [rabbitmq/rabbitmq-server#315]
`rabbitmq-server-generic-unix-3.5.4` with default configuration [installed](https://www.rabbitmq.com/install-generic-unix.html) on `Erlang/OTP 18` 

$ sbin/rabbitmq-server

```txt
BOOT FAILED
===========

Error description:
   {error,{missing_dependencies,[eldap,xmerl],
                                [rabbitmq_management,
                                 rabbitmq_auth_backend_ldap,mochiweb,
                                 amqp_client]}}
```

**Comment by michaelklishin** [comment]
Please use rabbitmq-users for questions. Your Erlang lacks eldap and xmerl: see if you may need to install additional packages.
