### ISSUE TITLE
inclusive terminology initiative 

### ISSUE THREAD

**Issue by lretrain91** [rabbitmq/rabbitmq-server#3159]
Hello,
I wonder if you have plan to follow the inclusive terminology initiative 
https://inclusivenaming.org/language/word-list/ 

I'm asking because my company is doing and we have some documentation link that include some of theses words.
Just to know if i just removed them or if there are going to change.

I understand that this is a special question.
Just let me know.

**Comment by michaelklishin** [comment]
@lretrain91 are there any specific guides or places that you have in mind? I can think of a few fields that CLI tools use but that's only for backwards compatibility.

We have switched everything that would not break compatibility to leader/follower a few years ago, for example. An example of what you are referring to would help. Thanks.

**Comment by lretrain91** [comment]
Here are the link a found :
On CLI :
slave_pids
queue_master_locator=min-masters

And links to the documentation  : 
everything under https://github.com/rabbitmq/rabbitmq-server/tree/master/
like : "https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbit/docs/rabbitmq.conf.example"

But i suppose all of these aren't be changed for backward compatibility right ?

**Comment by michaelklishin** [comment]
We cannot easily change field names, metric names, CLI commands and doc sections that refer to them (both guides and man pages). `grep -R` on the website suggests that at least a couple of unfortunate terms are no longer used beyond those cases.

Renaming default Git branch to `main` will also involve updating a lot of CI/CD configuration but it should be done in the next month or two.

I could find a few places in man pages can be improved. I will update them now.

**Comment by michaelklishin** [comment]
I think the only places left in the docs, man pages and examples are the ones that cannot be changed without breaking
backwards compatibility. They will go away naturally when classic queue mirroring is removed in a future version.
New replicated queue types already use "leader" and "follower" everywhere.

Thank you for bringing this up.

**Comment by lretrain91** [comment]
Ok thanks to you.
