### ISSUE TITLE
Does delayed message support cancellation ahead of its expiration? In other words, remove the message based a 'descriptor'

### ISSUE THREAD

**Issue by 985496501** [rabbitmq/rabbitmq-server#3160]
In our many bussiness scenarios, we manipulates this Excellent MQ to play a role of Scheduler.  We define a delayed Queue, send a message, and listen to the queue.  Sometimes, some events fire the delayed task to invoke ahead, therefore, the delayed message in the delayed-queue does not make any sense. Should it be cancelled, or remove from the queue?

Thanks!

**Comment by michaelklishin** [comment]
The only mechanism for message removal in queues is acknowledgement and message TTL. So there is no clear way of "canceling" a message that hasn't been published yet.

This plugin is on life support and won't get any new features. A different approach will eventually replace it (no ETA promises) but even then, the above problems will still be applicable.

Queues are not key-value stores, so arbitrary deletions are not really a supported operation.

**Comment by 985496501** [comment]
Get it, thanks.
