### ISSUE TITLE
High CPU in rabbitmq 

### ISSUE THREAD

**Issue by xjlixd** [rabbitmq/rabbitmq-server#3161]
**RabbitMQ 3.7.18,Erlang 21.3.8.6.**

Firstly,epmd-starter process  3701 is startting,maybe the start-time is 15:11,the command result as follow:
 ****3701 41924 Thu Jun 24 15:11:13 2021    01:56:48  100 52376 /usr/lib64/erlang/erts-10.3.5.4/bin/beam.smp -- -root /usr/lib64/erlang -progname erl -- -home /var/lib/rabbitmq -- -sname epmd-starter-167737917 -noshell -eval halt().****

and the command is : 
**_# ps -eo pid,ppid,lstart,etime,pcpu,rss,cmd | grep beam.smp | grep -Ev "grep|rabbit@hcapp-test"_**
 
Now , the RabbitMQ's process  Id is 40203, its CPU usage is 101.0% .
When I kill the process 3701 ,the CPU usage of  RabbitMQ will be work normally.

![image](https://user-images.githubusercontent.com/1635651/123934137-91a18b00-d9c5-11eb-96a3-81b68cb85f18.png)

and meanwhile the GC and context switch of Rabbitmq is very high, and the most CPU intensive thread is **rabbit_epmd_monitor**, the detail  info as following image.
![i mage](https://user-images.githubusercontent.com/1635651/123935798-23f65e80-d9c7-11eb-893b-5b9bedf62a52.png)

So，I want to how to solve this problem, and the root cause of this phenomenon.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
