### ISSUE TITLE
Quorum queues frequent memory issues

### ISSUE THREAD

**Issue by liorhasson** [rabbitmq/rabbitmq-server#3198]
Hi,

Summary: 
Rabbitmq 3.8.16, with hundreds of quorum queues (~900).
Cluster of 3 nodes, on k8s, memory limit up to 4G per node.

What goes wrong?

1. The memory is keep on growing in a moderate manner, although the number of queues and connections are stable.
2. Node restarting taking more and more time, at the beginning it took ~2 min, now after 2 weeks, it takes ~10 min.

Attachment of one node memory usage in 14 days time range:
![Screen Shot 2021-07-18 at 15 36 16](https://user-images.githubusercontent.com/492604/126067325-f4994ad9-8848-4c7c-96db-5c3aa67c00de.png)

![Screen Shot 2021-07-18 at 11 55 59](https://user-images.githubusercontent.com/492604/126067391-ae842449-7139-4ece-b310-e8f507cc3381.png)

Regards

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
