### ISSUE TITLE
Improve log message when a client connects to a non-existent host

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#320]
Right now we have

```
=ERROR REPORT==== 24-Sep-2015::00:37:05 ===
closing AMQP connection <0.306.0> (127.0.0.1:55301 -> 127.0.0.1:5672):
{handshake_error,opening,0,
                 {amqp_error,access_refused,
                             "access to vhost 'skhskjdhfsdf' refused for user 'guest'",
                             'connection.open'}}
```

which is not entirely unhelpful but could be clearer.

**Comment by michaelklishin** [comment]
See https://github.com/ruby-amqp/bunny/issues/352 for one example.

**Comment by michaelklishin** [comment]
Should probably go into `3.5.7` or `3.5.8` because `3.5.6` will have to go out early, see #324.

**Comment by michaelklishin** [comment]
User experience is already better thanks to #237 but I really would like to get this into both `3.5.7` and `3.6.0`.

**Comment by videlalvaro** [comment]
I'd assume nobody is parsing that log message, so changing it for something more readable should help. At the same time we could add a disclaimer somewhere on the website that the 

```erlang
{handshake_error,opening,0,
                 {amqp_error,access_refused,
                             "access to vhost 'skhskjdhfsdf' refused for user 'guest'",
                             'connection.open'}}
```

part of log messages might change without notice. ie: the Erlang terms part,

**Comment by michaelklishin** [comment]
Changed milestone to `3.6.0` because doing the same change twice is pretty fiddly and `3.6.0` ships this month.
