### ISSUE TITLE
Integrate Khepri as the new metadata store

### ISSUE THREAD

**Issue by yaronp68** [rabbitmq/rabbitmq-server#3207]

**Comment by michaelklishin** [comment]
There will be at least half a dozen steps to this, the whole point of Kherpi is that it can be adopted incrementally, unlike Mnevis.

**Comment by the-mikedavis** [comment]
Initial support for Khepri shipped in 3.13.0 behind the experimental `khepri_db` feature flag

**Comment by michaelklishin** [comment]
For the sake of completeness, in 4.0 we will ship a much more mature version of Khepri and eventually Mnesia's use in RabbitMQ will cease to exist beyond the elements necessary for upgrades/migration.
