### ISSUE TITLE
/usr/sbin/rabbitmqctl contains bash functionality while running sh

### ISSUE THREAD

**Issue by EmilienM** [rabbitmq/rabbitmq-server#321]
/usr/sbin/rabbitmqctl is running /bin/sh but contains bash functionality:
`if [ $(uname -s) == "Linux" ]; then`

Introduced by https://github.com/rabbitmq/rabbitmq-server/commit/b82a9fdb0fbc0f675facccdbcdf8dd8d753f2899

It should be:
`if [ $(uname -s) = "Linux" ]; then`

Co-debugged with Denis Egorenko.

**Comment by degorenko** [comment]
rabbitmqctl -q list_users
/usr/sbin/rabbitmqctl: 19: [: Linux: unexpected operator
guest	[administrator]

**Comment by EmilienM** [comment]
It's actually fixed in master by 6964e8ac1559cf76b9245394b46aaec5822f4178
We might need a new release.

**Comment by degorenko** [comment]
No, 3.5.5 has this, but anyway broken.

**Comment by EmilienM** [comment]
Right, we need a 3.5.6 as soon as possible.

**Comment by videlalvaro** [comment]
My colleague @dumbbell is working on a fix for this.

**Comment by dumbbell** [comment]
We are recreating the RPM and Debian packages with the script fixed. I will let you know when it's done.

**Comment by michaelklishin** [comment]
We are looking at building a new package revision. Packages other than Debian and RPM are not affected. 3.5.4 is still available from Bintray and Package Cloud.

**Comment by degorenko** [comment]
We need backport this:

https://github.com/rabbitmq/rabbitmq-server/commit/67c24aa1ccf5209660d54ad49033a1d1e3cc0502

**Comment by michaelklishin** [comment]
Denis,

If you check the stable branch you would notice that we already did.

We appreciate how proactive you are but really, we are well aware of what needs to be done and why.

**Comment by degorenko** [comment]
Michael,

Ok, thanks, just for information and bug log.

**Comment by dumbbell** [comment]
The rerolled packages were delayed by #325. The new build is now in progress.

We are sorry for these two bugs. We really need to improve the testing of the Debian and RPM packages (the broken script is only used in those packages)...

**Comment by dumbbell** [comment]
New packages (3.5.5-3) were uploaded. Thank you reporting the problem!

**Comment by EmilienM** [comment]
Thank you guys for your responsiveness. Much appreciated.
