### ISSUE TITLE
logged password in  plain text 

### ISSUE THREAD

**Issue by smile0ai** [rabbitmq/rabbitmq-server#3210]
Hi guys maybe this issue is not actual but i seen in our  logs  rabit mq login and password in plain text how can i shadow it?
i found https://github.com/rabbitmq/rabbitmq-server/issues/1837  it the actual? use RBAC for logs? 
or maybe i can shadow password in logs?
with best regards and be healthy.
..amqp_params_network,<<"user1">>,
                                <<"pass1">>,<<"/">>,
                                "host1",5672
..

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
