### ISSUE TITLE
Build arch-agnostic Debian and RPM packages

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#322]
Currently, they are made for 32-bit x86 architectures but they carry Erlang modules only.

**Comment by michaelklishin** [comment]
Should probably go into `3.5.7` because `3.5.6` will have to go out early, see #324.

**Comment by dumbbell** [comment]
In fact, our package are architecture-independent already. I was misled by the fact we build on a i386 VM, not an amd64.
