### ISSUE TITLE
Federation question

### ISSUE THREAD

**Issue by kotyara85** [rabbitmq/rabbitmq-server#3234]
Hello,
I have two separate clusters and want to federate them to fanout messages from one cluster to another.
I did setup exchanges, policies, upstreams, but when I send a message from cluster1 -> cluster2 I don't see this message in demo queue on cluster2

Any suggestions?

Thank you

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
