### ISSUE TITLE
Unable to run rabbitmqctl utility as a non root or non rabbitmq user.

### ISSUE THREAD

**Issue by kaushiksrinivas** [rabbitmq/rabbitmq-server#3238]
We are unable to run the rabbitmqctl tool, without being a root user or being a rabbitmq user. In our k8s containers, we do not wish to run this utility as a root or as a rabbitmq user. When looked at the contents of this script, there are explicit checks if the user is a root user or rabbitmq user, if not the script just terminates.

What is the reason behind this hard coded checks and any possible safe work arounds for this ?

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
