### ISSUE TITLE
 rabbitmqctl unable to pass arguments containing '*'

### ISSUE THREAD

**Issue by CVTJNII** [rabbitmq/rabbitmq-server#325]
Rabbitmqctl is unable to pass arguments containing '*' as the shell expands them.  For example, running the user setup commands from the [Sensu install guide](https://sensuapp.org/docs/0.20/install-rabbitmq) fails:

```
root@c20dc47d849f:/# rabbitmqctl set_permissions -p /sensu sensu ".*" ".*" ".*"
Setting permissions for user "sensu" in vhost "/sensu" ...
root@c20dc47d849f:/# tail -n 2 /var/log/rabbitmq/rabbit@c20dc47d849f.log
=INFO REPORT==== 24-Sep-2015::17:09:21 ===
Setting permissions for 'sensu' in '/sensu' to '....dockerenv.dockerinit', '....dockerenv.dockerinit', '....dockerenv.dockerinit'
```

The wrapper is expanding .* as a path.  This appears to be bug introduced by 7fe2c61ac3764865b784dcf34131358dba0d722d when 'printf %s $arg' was added.  Note that $arg is unescaped.

The following resolves this for my particular use case, however I have not tested the other use cases for which the print was added:

```
diff --git a/packaging/common/rabbitmq-script-wrapper b/packaging/common/rabbitmq-script-wrapper
index 67fa669..ed4c276 100644
--- a/packaging/common/rabbitmq-script-wrapper
+++ b/packaging/common/rabbitmq-script-wrapper
@@ -22,7 +22,7 @@ fi
 
 for arg in "$@" ; do
     # Wrap each arg in single quotes and wrap single quotes in double quotes, so that they're passed through cleanly.
-    arg=`printf %s $arg | sed $SED_OPT -e "s/'/'\"'\"'/g"`
+    arg=`printf %s "$arg" | sed $SED_OPT -e "s/'/'\"'\"'/g"`
     CMDLINE="${CMDLINE} '${arg}'"
 done
```

**Comment by ben-page** [comment]
You're right. My PR broke that. I was just about to create a PR to fix it, but @CVTJNII beat me to it.

**Comment by dumbbell** [comment]
Thank you!
