### ISSUE TITLE
get host ip

### ISSUE THREAD

**Issue by githubcheng2978** [rabbitmq/rabbitmq-server#3251]
how dose rabbitmq server obtain get host ip of the client when it is deployed in the container

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
