### ISSUE TITLE
Allow selective, on-demand queue master rebalancing

### ISSUE THREAD

**Issue by pickettphil** [rabbitmq/rabbitmq-server#332]
Since masters (in a cluster) are selected at random and don’t change for as long as the nodes are running, it is possible that one or few nodes become masters for all or most queues, thus not leveraging all nodes. It would be helpful if there was a way to tell Rabbit to elect a different master for a queue, or to rebalance across all queues, or even to rebalance automatically. The only way to force rebalancing at this time is seemingly to restart the node acting as the master for many queues. If so, this is too disruptive.

**Comment by michaelklishin** [comment]
Different master selection strategies are already implemented in master.

**Comment by michaelklishin** [comment]
See #121.

**Comment by igreenfield** [comment]
@michaelklishin #121 only apply to new nodes.
if I already have many masters on one node how I can rebalance it?

**Comment by michaelklishin** [comment]
@igreenfield this is not a support forum. Please ask questions to rabbitmq-users and search the archives, in which [this trick](https://groups.google.com/d/msg/rabbitmq-users/bJNcrDVhWiU/6oMO0DjNQ4oJ) can be found.

**Comment by michaelklishin** [comment]
There are plans to introduce a way to move queue masters and perhaps do some kind of online migration, for 4.0.0 (or possibly 3.8.0, depends on how things go).

**Comment by igreenfield** [comment]
Can you point me to a card to track this? it is very important to me organization.

**Comment by michaelklishin** [comment]
There are no specific plans about how we should approach this or much planning for 4.0 at the moment, so there is no GitHub issue. We will file one as plans solidify.

**Comment by Itxaka** [comment]
@michaelklishin Hi! Is there any update on this? has any planning has been done or is there any spec that we can look at? Just wondering if this may be in for 3.8/4.0 :)

Thanks!

**Comment by michaelklishin** [comment]
No updates besides [this rebalancing script](https://github.com/rabbitmq/support-tools/blob/master/scripts/rebalance-queue-masters).

**Comment by igreenfield** [comment]
I write same in python: [rebalance](https://gist.github.com/igreenfield/d5c3162c150cff924b4a1d10e4a3c371)

**Comment by Itxaka** [comment]
thank you guys for the comments, much appreciated! 👍
