### ISSUE TITLE
Receive an email/alert if "an empty queue stays for more than x minutes"

### ISSUE THREAD

**Issue by venubabu452** [rabbitmq/rabbitmq-server#3320]
I have a bunch of empty queues in my queue list
![image](https://user-images.githubusercontent.com/48302908/129938812-83aaa996-fc7e-46b2-a200-904d4daf920c.png)

I need rabbitmq to send an alert/notification/email, if an empty queue stays for more than x minutes.
x minutes= threshold time {that I'll set later}

Is there a way to do so? I'm okay to do so via GUI or CLI. Please let me know. 
Thanks,
Venu

**Comment by michaelklishin** [comment]
This is a good idea that should be handled by alerting tools, not RabbitMQ. Prometheus metrics and alerting ecosystem would be a great place for such feature.
