### ISSUE TITLE
Make `consumer_timeout` configurable via TLS Parameters

### ISSUE THREAD

**Issue by chrisjsewell** [rabbitmq/rabbitmq-server#3344]
#2990, it's fair to say, is not a universally loved change; for myself, it kind of breaks our whole program 😢.

One compromise I believe makes sense, is to allow `consumer_timeout` to be set by the consumer, as part of the connection URI (preferably allowing for `false`), since it seems reasonable the client should have a say in how long it may take to complete a task.

See: https://www.rabbitmq.com/uri-query-parameters.html#tls

_Originally posted in https://github.com/rabbitmq/rabbitmq-server/issues/2990#issuecomment-908405800_

**Comment by chrisjsewell** [comment]
No experience with erlang; but happy to try a PR if what I suggest seems amenable 😬

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
