### ISSUE TITLE
RabbitMQ cookie should support encryption

### ISSUE THREAD

**Issue by EricLin89** [rabbitmq/rabbitmq-server#3348]
RabbitMQ cookie should support encryption. Since it acts as the "authentication credential" for inter-node communication. Once it's obtained by a malicious attacker, he can join his node into the attacked cluster, this can cause potential information leak. Also he can use this cookie to run rabbitmqctl against the attacked cluster, this causes information leak and breaks integrity of the system.

**Comment by michaelklishin** [comment]
The cookie is managed [by the runtime](https://github.com/erlang/otp/). I'd say it won't change much since you'd have to store a decrypting key in plain text anyway *somewhere* but you are welcome to suggest it to them.
