### ISSUE TITLE
The passphrase for TLS private key password encryption is stored in plaintext

### ISSUE THREAD

**Issue by EricLin89** [rabbitmq/rabbitmq-server#3349]
The passphrase for TLS private key password encryption is stored in plaintext, there is still risk of information leak, this does not comply with security regulations of commercial scenarios. I know there's a prompt way to set the passphrase but it's not friendly to script automation. Maybe RabbitMQ should implement some more secure way to store sensitive configurations.

**Comment by lhoguin** [comment]
You should be able to encrypt the TLS private key password by following the documentation at https://www.rabbitmq.com/configure.html#configuration-encryption

**Comment by michaelklishin** [comment]
TLS is implemented [by the runtime](https://github.com/erlang/otp/), not RabbitMQ. I'd say it won't change much since you'd have to store a decrypting key in plain text anyway *somewhere* but you are welcome to suggest it to them.
