### ISSUE TITLE
Shovel creates channel with undefined peer_port

### ISSUE THREAD

**Issue by mheidt** [rabbitmq/rabbitmq-server#3358]
Hello,

There is the following issue in the hop project:
https://github.com/rabbitmq/hop/issues/247

The connection/channel that is created by the shovel doesn't have peer_host und peer_ip. But unfortunately the values "undefined" are set when calling api/consumers. Which is especially  bad for the port, because an integer is expected.
{
"arguments": {},
"ack_required": true,
"active": true,
"activity_status": "up",
"channel_details": {
"connection_name": "rabbit@10-244-108-91.1628951087.17337.1",
"name": "rabbit@10-244-108-91.1628951087.17337.1 (1)",
"node": "rabbit@10-244-108-91",
"number": 1,
"peer_host": "undefined",
**"peer_port": "undefined",**
"user": "shovel"
},
"consumer_tag": "amq.ctag-uLSmF70x9pQEDL34OCbkvg",
"exclusive": false,
"prefetch_count": 1000,
"queue": {
"name": "amq.gen-vIuezFJTmuEAOB2SouuafQ",
"vhost": "PROD"
}
},
Could you rather return 0 oder -1? Or unset the value?

**Comment by acogoluegnes** [comment]
Could you please provide steps to reproduce?

**Comment by michaelklishin** [comment]
Shovel opens direct Erlang client connection to the local node. This is **not** a regular client connection and it does not have ephemeral range port associated with it because all communication happens on the node itself using Erlang distribution/message passing.

Shovel will use regular network connections when connecting to remote hosts.

**Comment by michaelklishin** [comment]
The only realistic solution is to make field serialisation in Hop take those "undefined" values into account. We can also consider making the returned value `null` as it is a more common thing to do in JSON documents.

However, the port is actually absent (that's it, not by mistake) and that must be accounted for.

**Comment by mheidt** [comment]
Yes, I am concerned about the string of "undefined". Either a real null or don't let the REST service return the value at all.
I don't expect a real value here.

**Comment by mheidt** [comment]
@michaelklishin 
Could you please reopen the issue. I think, you misunderstood my concern.

**Comment by mheidt** [comment]
And maybe this helps convincing:

https://stackoverflow.com/questions/13796751/json-undefined-value-type#:~:text=undefinedis%20nota%20valid%20JSON%20value%2C%20even%20though%20it,use%20nullinstead%20of%20undefined%3A%20%7B%20%22something%22%3A%20null%20%7D

**Comment by michaelklishin** [comment]
I have filed #3362 with a more specific description. This issue won't be a priority for our team in the near future but you are welcome to contribute a fix: this is open source software you get for free after all.
