### ISSUE TITLE
Feature request: Queue TTL with ifEmpty flag (not just unused)

### ISSUE THREAD

**Issue by DrParanoia** [rabbitmq/rabbitmq-server#3364]
Hi there!

Would be great to be able to specify an `ifEmpty` flag when configuring TTL for a queue. Basically, it should function as existing queue TTL, but the timer starts when the queue is unused + no messages are in the queue.

We have a setup where a lot of dynamic queues are created, however, with regular TTL there is a risk that messages will be lost in case the queue is not processed in time (during a major failure or day-long maintenance for example).

I think this feature will be super useful and will allow expanding use-cases for RabbitMQ.

Thanks!

**Comment by michaelklishin** [comment]
This is [how queue TTL works](https://rabbitmq.com/ttl.html#queue-ttl) but it will be virtually impossible to do this for message TTL as none of the message store code is aware of queue metrics. I don't think this will be a priority compared to a lot of other things our team has going or planned.

**Comment by DrParanoia** [comment]
@michaelklishin I am sorry, but I am not talking about message TTL. And this is not how queue TTL currently works. Current queue TTL will delete all messages because the TTL only looks at the consumer count or the last time the queue was declared.

What I am suggesting, is to not delete the queue with TTL if there are still messages in it. Please reconsider 😆
