### ISSUE TITLE
Do not return nodes in maintenance mode as active stream replicas

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/rabbitmq-server#3370]
After the `rabbitmq-upgrade drain` command runs and succeeds, that node gets placed in maintenance mode, meaning that all TCP sockets will close (including stream ones). The stream coordinator should not return nodes that are in maintenance in the metadata, because clients will fail to connect to them. This is how the Go Stream client currently fails to connect:

```
2021/09/06 16:09:43 [info] - Silent (0.13-alpha) Simulation, url: [rabbitmq-stream://Z5U5eSZbPmaWvuJUPnOQab1R_WF7SaZS:Y0quG0xQGiZhrvzXrHL2b4LRqHvf_ntL@rabbitmq:5552/%2f] publishers: 0 consumers: 10 streams: [stream-large]
2021/09/06 16:09:43 [info] - Declaring streams: [stream-large]
2021/09/06 16:09:43 [info] - stream stream-large, meta data: leader rabbitmq-server-1.rabbitmq-nodes.lre-3-9:5552, followers rabbitmq-server-0.rabbitmq-nodes.lre-3-9:5552rabbitmq-server-2.rabbitmq-nodes.lre-3-9:5552
2021/09/06 16:09:43 [info] - End Init streams :[stream-large]
2021/09/06 16:09:43 [info] - Starting 10 consumers...
2021/09/06 16:09:43 [info] - Starting consumer number: stream-large-0, form first
2021/09/06 16:09:44 [info] - Starting consumer number: stream-large-1, form first
2021/09/06 16:09:44 [error] - Error creating consumer: dial tcp 10.118.1.70:5552: connect: connection refused
```

We should probably not return nodes in maintenance mode in the `rabbitmq-streams` command either - create a new issue if you think this is valid.

_Originally posted by @gerhard & @Gsantomaggio in https://github.com/rabbitmq/opportunities/issues/99_

**Comment by mkuratczyk** [comment]
I've verified this after the many changes on the server and client side since the issue was originally reported and it's still a problem - I can reproduce it using stream-perf-test 0.9 and `main`:

```
$ bazel run start-cluster

# declare a stream with leader on rabbit-0 and publish some messages
$ stream-perf-test --leader-locator client-local -y 0 --time 5

# put a node in maintenance mode
$ rabbitmq-upgrade -n rabbit-2 drain

# try to consume from the stream; it may work (when connected to the running node), but sometimes doesn't (when the node under maintenance is selected):
$ stream-perf-test -x 0
com.rabbitmq.stream.StreamException: Error while creating stream connection to mkuratczykPF0JR:5554
```

If I actually stop `rabbit-2` (eg. using `stop_app`) it works 100% of the time, since `rabbit-2` gets removed from stream metadata.
