### ISSUE TITLE
Queues are looking fine but flow control is active

### ISSUE THREAD

**Issue by maordavidov** [rabbitmq/rabbitmq-server#3372]
I'm trying to figure out what's wrong with my RabbitMQ, my queues are looking fine, but for some reason my producers are hitting a flow control. I tried to split my queue to 10 different queues in order to get more threads - but it doesn't seems to help.

Image of my queues:

![image](https://user-images.githubusercontent.com/14234032/132270503-423e92bf-55a1-4851-b736-b5471c1028e1.png)

Image of my publishers connections:
![image](https://user-images.githubusercontent.com/14234032/132270526-29b99bf6-0edc-415f-9bce-724841e41c44.png)

Some context - my queues are defined with limit of 50K messages, non durable, with single node RabbitMQ

How can I understand what's going on / disable flow control?

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
