### ISSUE TITLE
Streaming- offset- specifying message so it reads from it

### ISSUE THREAD

**Issue by suprunka** [rabbitmq/rabbitmq-server#3376]
Is it possible to specify message somehow, so the stream is not read from first/last/next/offset, but the message with some property. I would like to have a property on message that would specify the stream start reading from this. Would it be possible, othewise how x-stream-offset for timestam in .net works. Can I read only message that have been published after that timestamp, because I feel it reads the timestamp as offset and it says that 'Value of type 'DateTime' cannot appear as table value'.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
