### ISSUE TITLE
With ~500 consumers `rabbitmq-streams  list_stream_consumers`  fails with  {:noproc...

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-server#3388]
Given a cluster 3 nodes cluster running :
- `rabbitmq v3.9 latest` and with ~500 consumers 
-  cpu: 2 memory: 16Gi

`rabbitmq-streams  list_stream_consumers` doesn't work in the right way.

```
root@rabbitmq-server-0:/# rabbitmq-streams  list_stream_consumers
Listing stream consumers ...
%Protocol.UndefinedError{description: "", protocol: Enumerable, value: {:badrpc, {:EXIT, {:noproc, {:gen_server, :call, [#PID<12838.15984.0>, :which_children, :infinity]}}}}}

root@rabbitmq-server-0:/#
```

pair with @gerhard

**Comment by mkuratczyk** [comment]
I can't reproduce. I deployed a 3-node cluster with 1 stream, 1 publisher and 1000 consumers. The system was very much overloaded (on the followers, the leader wasn't too busy) but `rabbitmq-streams list_stream_consumers` still worked fine (it took 15-20s to list all those consumers but that's something we can look into separately). I've tried other CLI commands and the checked that the Management UI was fairly responsive.
