### ISSUE TITLE
rabbitmq.conf validation fails when max_message_size is set to 536870912

### ISSUE THREAD

**Issue by Whitespirit0** [rabbitmq/rabbitmq-server#3390]
Hello,

When I set `max_message_size = 536870912` in RabbitMQ configuration file, it fails to start with the following logs:

> 2021-09-09 10:37:54.290911+00:00 [erro] <0.130.0> Error preparing configuration in phase validation:
2021-09-09 10:37:54.290987+00:00 [erro] <0.130.0>   - max_message_size invalid, Max message size should be less than 512MB and gre than 0

If I set it to `536870911`, it starts fine.

I'm surprised because the max value for this parameter is supposed to be `536870912` according to https://www.rabbitmq.com/configure.html.

I've reproduced this issue with two Docker images (didn't check other ones): rabbitmq:3.8.7-management and rabbitmq:3.9.5-management.

Thanks for your attention.

**Comment by michaelklishin** [comment]
The answer can be found in the validator code in `rabbit.schema`:

``` eel
Size > 0 andalso Size < 536870912
```

we highly recommend against such extremely large messages. Put them in a blob store and pass the blob ID around.

**Comment by Whitespirit0** [comment]
OK I see. Well I don't know if it's the validator or the doc that is correct, but they should be coherent.
Unfortunately, we can't introduce a blob storage for now. But we'll keep this in mind for the future.
