### ISSUE TITLE
Persistent Messages show 0 in the UI

### ISSUE THREAD

**Issue by lancepowell** [rabbitmq/rabbitmq-server#3393]
UI Bug: Persistent Messages show as 0, however messages are persistent and the message body bytes show correctly.

This is on 3.9.5.

![image (8)](https://user-images.githubusercontent.com/1454879/132698980-9f3d1909-6c1b-441c-a422-73758e7f6ca6.png)

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
