### ISSUE TITLE
Unable to enforce access control to topic exchange by routing key

### ISSUE THREAD

**Issue by tomheinan** [rabbitmq/rabbitmq-server#340]
I'm looking for a way to ensure that a particular user (say, with user ID 123) can only publish to a set of known topics, e.g. `users.123.messages`. I've got a back-end service subscribed via the STOMP plugin to `users.*.messages`, and I'd like to use the destination of incoming messages to positively identify their origin, but I can only do that if I'm sure that only user 123 can write to `users.123.*`.

I've implemented a custom authentication plugin that takes care of making sure connections are tagged with appropriate user IDs, but the problem is that `check_resource_access/3` doesn't contain any routing information when publishing to the `amq.topic` exchange. For example:

```erlang
check_resource_access(AuthUser, #resource{virtual_host = VHost, kind = Type, name = Name}, Permission) ->
    rabbit_log:info("~p wants to ~p on ~p ~p~n", [AuthUser#auth_user.username, Permission, Type, Name]),
    true.
```

```txt
=INFO REPORT==== 1-Oct-2015::13:33:04 ===
accepting STOMP connection <0.668.0> (192.168.99.1:52159 -> 192.168.99.100:6080)

=INFO REPORT==== 1-Oct-2015::13:33:04 ===
Authenticated as <<"user123">> with tags [user,123]

=INFO REPORT==== 1-Oct-2015::13:33:42 ===
<<"user123">> wants to write on exchange <<"amq.topic">>
```

Since I don't know what the routing key is that user123 intends to access, I can't know whether to allow or deny their write to `amq.topic`.

In `rabbit_channel.erl:903`, the `basic.publish` clause of `handle_method/3` looks like it could be modified to include something like

```erlang
ExchangeName = rabbit_misc:r(VHostPath, exchange, ExchangeNameBin, RoutingKey),
```

if the resource record was updated to something like

```erlang
r(VHostPath, Kind, Name, RoutingKey) ->
    #resource{virtual_host = VHostPath, kind = Kind, name = Name, routing_key = RoutingKey}.
```

Apologies if this isn't the right forum for this kind of issue, or if there's a better way to achieve what I'm trying to do that I have overlooked. I'm happy to give it a shot in PR form, but wanted to make sure this wasn't in progress elsewhere first.

**Comment by michaelklishin** [comment]
Please use rabbitmq-users for questions. Access control over routing keys is not available: use separate exchanges.

**Comment by michaelklishin** [comment]
Including routing key may be a fair idea but it is not a part of the exchange, so doesn't beling to the resource record. Let's continue on the list.
