### ISSUE TITLE
Queue TTL deletes all messages (improvement suggestion)

### ISSUE THREAD

**Issue by DrParanoia** [rabbitmq/rabbitmq-server#3408]
Hi there! From reading the documentation on [Queue TTL](https://rabbitmq.com/ttl.html#queue-ttl) currently, this is true:
- Queue TTL timer starts when last consumer disconnects
- Queue TTL timer resets when the queue is declared/re-declared
- Queue TTL will DELETE the queue even if there are messages inside

Proposed addition/change to TTL mechanics (possibly add a `x-expires-if-empty` option):
- Queue TTL timer starts when last consumer disconnects AND last message is gone from the queue
- Queue TTL timer resets when queue is declared/re-declared

So the goal is to NOT ALLOW the queue to be deleted if there are still messages inside. I believe this will be a huge improvement for systems requiring a lot of dynamic queues since it will allow to safely delete the queues that are actually no longer needed without any data loss.

P.S.
I am really sorry for creating a "duplicate" of [this issue.](https://github.com/rabbitmq/rabbitmq-server/issues/3364) But the official answer got me thinking, that possibly I was not clear enough with my proposal.

**Comment by michaelklishin** [comment]
The answer is still the same as inl #3364. The definition of a "used queue" is a queue with consumers. Queues without consumers can be listed using the HTTP API, an HTTP API client or CLI tools and deleted using any logic you like.
