### ISSUE TITLE
Close the journal handle before trying to erase the queue index folder

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-server#341]
See https://groups.google.com/d/msg/rabbitmq-users/eDgz6nlC_hg/qRFmwaeAAwAJ

**Comment by codenaked** [comment]
@videlalvaro thanks much! How often do you put out release builds?

**Comment by michaelklishin** [comment]
4-6 weeks for point releases. We can produce a one-off build and post it to the list: do you need a Windows installer or binary build?

**Comment by codenaked** [comment]
A windows installer would be perfect. Thanks!

**Comment by michaelklishin** [comment]
@codenaked can you please ping us on the original list thread about this, so that we can upload a build to it? I can't find it, sorry.

**Comment by codenaked** [comment]
Sure it's at the top of this thread, but here it is also: https://groups.google.com/forum/#!msg/rabbitmq-users/eDgz6nlC_hg/qRFmwaeAAwAJ

Thanks!

**Comment by michaelklishin** [comment]
@codenaked OK, I'll upload a build first thing in the morning. `3.5.6` can ship any day now anyway but hey, we try delivering on what we promise ;)
