### ISSUE TITLE
Problems with Sharding Plugin in RabbitMQ version 3.9.5

### ISSUE THREAD

**Issue by reichowc** [rabbitmq/rabbitmq-server#3414]
Hello, I'm using sharding plugin in RabbitMQ version 3.8.18 without problems, but, when I change to version 3.9.5 the following problem happens: When one node (RabbitMQ) is down, I can't get it up again if I have some policy created. 

So, if I delete the policy and try to start the node again, this is possible. Then I need to recreate the policy with the node up to make things work again.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
