### ISSUE TITLE
Batch writes to index when requeueing

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-server#343]
This area could also batch operations when writing to the index.

It's quite critical to have this as fast as possible, since slave promotion into master does requeue'ing

**Comment by michaelklishin** [comment]
@videlalvaro is this still relevant?

**Comment by videlalvaro** [comment]
it could be improved when many rejects are sent at the same time, but I'm not sure the gains will be too big

**Comment by michaelklishin** [comment]
`basic.nack` with `multiple` set to `true` is probably the only realistic scenario.

**Comment by essen** [comment]
Just found out about https://github.com/rabbitmq/rabbitmq-server/commit/d85792bd6fe579b291533deb35cc7166510cac40 (there's already a rabbitmq-server-343 branch it seems). The good news is that what I did is basically the same so I guess I'm on the right tracks. I need to experiment with calling update index twice though. I'll push/open a PR tonight but I'll want to do more testing next week.
