### ISSUE TITLE
Error TLS MQTT (Rabbitmq)

### ISSUE THREAD

**Issue by ruem2802** [rabbitmq/rabbitmq-server#3433]
Hi, i have a issuae, a config rabbitmq with /etc/rabbitmq/rabbit.conf and a add plugin mqtt, 
In rabbitmq.conf i config:
# default TLS-enabled port for MQTT connections
mqtt.listeners.tcp.1 = 8883
mqtt.listeners.tcp.default = 1883

ssl_options.cacertfile = /etc/rabbitmq/tls-gen/basic/result/ca_certificate.pem
ssl_options.certfile   = /etc/rabbitmq/tls-gen/basic/result/server_certificate>
ssl_options.keyfile    = /etc/rabbitmq/tls-gen/basic/result/server_key.pem

ssl_options.verify     = verify_peer
ssl_options.fail_if_no_peer_cert  = true

i want to use tls mqtt in port 8883 
But in client i use MQTTBox and MQTTfx, i cant connect to server MQTT (Rabbitmq  - port 8883)
Can U help me about that!
In my server i add : ca_certificate.pem, client_certificate.pem and client_key.pem
Thank!

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
