### ISSUE TITLE
Rabbitmq fails in validation step as when security context set as readOnlyRootFileSystem - openshift

### ISSUE THREAD

**Issue by Mdirfan6** [rabbitmq/rabbitmq-server#3435]
I am trying to install the latest version rabbitmq version 3.9.5 with image 3.9.5-debian-10-r10.
In openshift we have to setcurity context as readOnlyRootFileSystem to true. But when I keep this true.

 I get the following error
 
 ERROR ==> The variable RABBITMQ_COMBINED_CERT_PATH must be set to either an existant file or a non-existant file in a writable directory.
/opt/bitnami/scripts/libvalidations.sh: line 200: cannot create temp file for here-document: Read-only file system
/opt/bitnami/scripts/libvalidations.sh: line 202: ip_array[0]: unbound variable

I tried to set the variable "RABBITMQ_COMBINED_CERT_PATH" in statefullset.yaml to path /opt/bitnami. yet I get the same error. 

I am not sure how this has to be done. As I noticed variable not being set even after we add it in yaml.
Any info on this will help.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
