### ISSUE TITLE
Typo in schema for max_message_size?

### ISSUE THREAD

**Issue by karsten42** [rabbitmq/rabbitmq-server#3459]
I was looking up the `max_message_size` config and stumbled upon this line. Seems like a typo. 
https://github.com/rabbitmq/rabbitmq-server/blob/b1b995ca9f7eb45c90cbfb31194c81af3e798321/priv/schema/rabbit.schema#L557

`msx` vs `max`

**Comment by michaelklishin** [comment]
This is [not the case in master](https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbit/priv/schema/rabbit.schema#L745-L746), [`v3.9.x`](https://github.com/rabbitmq/rabbitmq-server/blob/v3.9.x/deps/rabbit/priv/schema/rabbit.schema#L745-L746) or [`v3.8.x`](https://github.com/rabbitmq/rabbitmq-server/blob/v3.8.x/deps/rabbit/priv/schema/rabbit.schema#L621-L622).
