### ISSUE TITLE
`time_compat`: Get rid of try/catch

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#346]
We can use two module files, one for Erlang 18+, one for Erlang up-to 17, both named `time_compat` internally. The correct module is manually loaded during startup.

As the modules will be in `rabbitmq-common`, we need to determine how to do this load:
* Do we need an application module?
* Can we do this from an `-on_load()` directive? Is this supported by Erlang R16B03?

**Comment by dumbbell** [comment]
The same solution will be applied to `ssl_compat` (#347).

**Comment by michaelklishin** [comment]
Note that we can fix this for `3.7.0` only and thus consider solutions that require Erlang 17.5+.

**Comment by dumbbell** [comment]
I propose the following solution, tested in the following repository:
https://github.com/dumbbell/erlang-time-compat

The idea is to build three modules from the same source file (`time_compat.erl`):
 * `time_compat_old.beam`, using the old Time API (ie. based on `erlang:now/0`);
 * `time_compat_new.beam`, using the new Time API;
 * `time_compat.beam`, a module which replaces itself with one of the other modules.

See `swap_module()` and `do_swap_module()` in `time_compat.erl`.

This example is incomplete because it only exports `unique_integer/0`.

The solution can be used for `ssl_compat` (#347), though the following test needs to be adapted:
https://github.com/dumbbell/erlang-time-compat/blob/master/time_compat.erl#L57

I believe the other tricky part is how to plug this solution to the build system (ie. building three modules out of one source file).

**Comment by dumbbell** [comment]
@michaelklishin: Why not for 3.6.1? The change should be transparent for the consumers of `time_compat` and `ssl_compat`. It should be an implementation detail.

**Comment by michaelklishin** [comment]
`3.6.1` sounds good. I was just mentioning it is a possibility.

**Comment by dumbbell** [comment]
Ok. I think we should target 3.6.x because the basic try/catch can be a performance penalty, though I didn't measure anything.

**Comment by dcorbacho** [comment]
The `-on_load()` directive cannot be used, as doing an external call to the module itself causes a deadlock http://www.erlang.org/doc/reference_manual/code_loading.html#id88557. This happens, at least, when trying to load the new module.

Adding an application behaviour to rabbit_common is a very complex issue, because of rabbit startup. The scripts try to use rabbit_common without trying to initialise the application. Thus, it would require touching the release, packages, etc.
```
isis:rabbit dianacorbacho$ make run-broker PLUGINS='rabbitmq_management' GEN    dist DIST   plugins/rabbit_common-0.0.0.ez
 GEN    dist
 GEN    /var/folders/5q/vkjhc27d4w9_hc69p7q3vd1w0000gp/T//rabbitmq-test-instances/rabbit/enabled_plugins
init terminating in do_boot ()
{"init terminating in do_boot",{undef,[{erlang,monotonic_time,[],[]},{rabbit_nodes,random,1,[{file,"src/rabbit_nodes.erl"},{line,209}]},{rabbit_nodes,ensure_epmd,0,[{file,"src/rabbi
t_nodes.erl"},{line,217}]},{rabbit_cli,start_distribution,1,[{file,"src/rabbit_cli.erl"},{line,133}]},{rabbit_cli,main,3,[{file,"src/rabbit_cli.erl"},{line,52}]},{init,start_it,1,[]
},{init,start_em,1,[]}]}}
init terminating in do_boot ()
make: *** [/var/folders/5q/vkjhc27d4w9_hc69p7q3vd1w0000gp/T//rabbitmq-test-instances/rabbit/enabled_plugins] Error 1
```
I found a much easier solution that only implies a little bit of coding:
https://github.com/rabbitmq/rabbitmq-common/tree/rabbitmq-server-346

The `time_compat` module will dynamically re-load itself the first time one of the affected functions is called, which in the general case is on startup. This module contains three functions for each affected function, for example:

```
monotonic_time() ->
    code_version:update(?MODULE),
    time_compat:monotonic_time().

monotonic_time_post_18() ->
	erlang:monotonic_time().

monotonic_time_pre_18() ->
    erlang_system_time_fallback().
```
The `code_version` then reads the abstract code, modifies, compiles and loads it. If we are in Erlang 18, it will delete `monotonic_time` and `monotonic_time_pre_18`, and rename `monotonic_time_post_18` to `monotonic_time`. It will also remove the unused exports.

This solution works also doing dynamic load of modules, which would be more complex if it were an application doing it.
```
1> time_compat:monotonic_time().
-576460747892153029
2> l(time_compat).
{module,time_compat}
3> time_compat:monotonic_time().
-576460743998363885
```
Performance wise, it shouldn't affect the system at all.

@michaelklishin @dumbbell What do you think of this approach? If you agree with it, I'll add the documentation and finish the changes to `time_compat` itself.

**Comment by michaelklishin** [comment]
Sounds reasonable to me (or at least as reasonable as we can make dynamic code loading ;)). Note that I'm definitely not an expert on the mechanics of dynamic code loading in BEAM.

**Comment by dcorbacho** [comment]
PR for both #346 and #347 in https://github.com/rabbitmq/rabbitmq-common/pull/42

**Comment by dumbbell** [comment]
Hi @dcorbacho!

Even if your solution is more complex than the proposed solution, it has the benefits of allowing a per-function selection. I like this flexibility. However, you don't use this possibility by hard-coding the switch between before and after Erlang 18.0.

Could you please update this patch so the condition is inside the `version_support` attribute? For instance, we'll need a `rand_compat` module because `random` is deprecated in Erlang 19.0.

As for the syntax, what do you think of:
```erlang
-erlang_version_support([
    {unique_integers, 0, % I would keep the arity near the function name.
     18, % Condition: ErlangVersion >= 18.
     unique_integers_post_18, % Condition evaluates to true
     unique_integers_pre_18}, % Condition evaluates to true
    {new_api, 0,
     19, % Condition: ErlangVersion >= 19.
     new_api_post_19,
     new_api_pre_19},
    % More functions depending on any Erlang version...
  ]).
```

Or maybe:
```erlang
-erlang_version_support([
    {18, [ % Condition: ErlangVersion >= 18.
     {unique_integers, 0,
      unique_integers_post_18, % Condition evaluates to true
      unique_integers_pre_18}, % Condition evaluates to true
     % More functions depending on Erlang 18.0...
     ]},
    {19, [ % Condition: ErlangVersion >= 19.
     {new_api, 0,
      new_api_post_19,
      new_api_pre_19},
     % More functions depending on Erlang 18.0...
     ]}
  ]).
```

By the way, as noted in this example, I would rename the attribute to `erlang_version_support` because `version_support` is to vague/generic. Also, I would keep the arity near the function real name.

I prefer the second example because the condition is not repeated.

What do you think?

Also, we must remember to update `rabbit_hipe.erl` in rabbitmq-server. The use of `code_version` reverts the module to a non-native version of the module if it was hipe-compiled on the fly. `rabbit_hipe` uses the value of `Mod:module_info(native)` (which is back to `false`) to determine if the module should be hipe-compiled. So it needs to look at a second condition (maybe the presence of the `erlang_version_support` attribute?) to avoid recompiling such a module.

**Comment by dumbbell** [comment]
Here are some numbers to evaluate the impact of the try/catch and the proposed solution; probably something we should have done before working on this to know the impact :-)

To measure the impact, I use PerfTest to transmit 200,000 messages, five times in a row:
```
$ for i in $(seq 1 5); do ./PerfTest.sh -C 200000 -D 200000; done
```

I played with Erlang 17.5.6 and Erlang 18.2.2; only the latter has the new Time and Time Correction API. For each Erlang version, `time_compat` is based on:

1. direct calls to the underlying API (so either only the direct call to the new API, or only the replacement for Erlang 17);
2. code reload, as posted in rabbitmq/rabbitmq-common#42;
3. try/catch, ie. plain `stable` branch.

With Erlang 18.2.2:
```
$ ministat -w 74 {direct-calls,code-reload,try-catch}-18
x direct-calls-18
+ code-reload-18
* try-catch-18
+--------------------------------------------------------------------------+
|+        x * *     x    x                  x  ++ *      +  *           ** |
|           |_|____|_____M______A_________A_A___M_M_|_____________|_______||
+--------------------------------------------------------------------------+
    N           Min           Max        Median           Avg        Stddev
x   5         14369         14494         14408       14424.2     49.956981
+   5         14348         14492         14463         14450     58.749468
No difference proven at 95.0% confidence
*   5         14375         14524         14469       14454.2     73.489455
No difference proven at 95.0% confidence
```

So in this scenario, we loose nothing with the try/catch. This is expected because the new Time and Time Correction API is used (almost) directly in the three cases.

With Erlang 17.5.6:
```
$ ministat -w 74 {direct-calls,code-reload,try-catch}-17
x direct-calls-17
+ code-reload-17
* try-catch-17
+--------------------------------------------------------------------------+
|*     *               ** * +     +      +  +     x x+     x          x   x|
|    |__________A______M____|  |________AM_______||________M_A__________|  |
+--------------------------------------------------------------------------+
    N           Min           Max        Median           Avg        Stddev
x   5         13892         14062         13959       13969.6     75.830733
+   5         13740         13911         13828       13821.4     65.683331
Difference at 95.0% confidence
	-148.2 +/- 103.46
	-1.06088% +/- 0.740608%
	(Student's t, pooled s = 70.9387)
*   5         13546         13724         13703         13653     81.067873
Difference at 95.0% confidence
	-316.6 +/- 114.478
	-2.26635% +/- 0.819476%
	(Student's t, pooled s = 78.493)
```

Here, going through an ever-failing try to always fallback on the catch causes a 2% performance penalty in this scenario. With code rewritten on the fly, the penalty is down to 1%. Why 1%, I don't know; could Erlang apply some optimization we loose by doing on-the-fly reload?

**Comment by dcorbacho** [comment]
I only can think of those additional try/catch and the fact that is not hipe-compiled.

**Comment by dcorbacho** [comment]
See hipe compilation in https://github.com/rabbitmq/rabbitmq-server/pull/572

**Comment by dumbbell** [comment]
Hi!

@dcorbacho: I finally tested your branch again. I want to run a few more tests but I feel it's ready to be merged.

One last point, in the following code:
```erlang
-erlang_version_support(
   [{18,
     [{monotonic_time, monotonic_time_pre_18, monotonic_time_post_18, 0},
      {monotonic_time, monotonic_time_pre_18, monotonic_time_post_18, 1},
```

What do you think of moving the arity right after the real function name? Soemthing like:
```erlang
-erlang_version_support(
   [{18,
     [{monotonic_time, 0, monotonic_time_pre_18, monotonic_time_post_18},
      {monotonic_time, 1, monotonic_time_pre_18, monotonic_time_post_18},
```

I find it more readable. What do you think?

**Comment by dcorbacho** [comment]
@dumbbell That sounds reasonable, I'll change it now.

**Comment by dumbbell** [comment]
Thank you!

**Comment by dcorbacho** [comment]
Done

**Comment by dumbbell** [comment]
Thank you! I finished testing. I will merge it just after 3.6.1.
