### ISSUE TITLE
Document exit codes for command line tools

### ISSUE THREAD

**Issue by PenelopeFudd** [rabbitmq/rabbitmq-server#3464]
Hi;

Today my ansible playbook failed when the command `rabbitmq-plugins list -E -m` had an exit code of 70 and a stderr output of 
```
{:query, :********@fm-f-d4v", {:badrpc, :timeout}}
```
1. Looked at the [Command Line Tools](https://www.rabbitmq.com/cli.html) and [Plugins](https://www.rabbitmq.com/plugins.html) pages and the [rabbitmq-plugins man page](https://www.rabbitmq.com/rabbitmq-plugins.8.html), but could not find the list of exit codes and what an exit code of 70 meant.
2. Found [exit_codes.ex](https://github.com/rabbitmq/rabbitmq-server/blob/b62c5499cefa2f57d8516f3948543383d8387d4b/deps/rabbitmq_cli/lib/rabbitmq/cli/core/exit_codes.ex) for my version of rabbitmq-plugins, which gave the names for the exit codes.
3. It looks like the error code for `{:badrpc, :timeout}` should be exit_tempfail (rc = 75), not exit_software (rc = 70), but I don't really know Erlang well enough to be sure: https://github.com/rabbitmq/rabbitmq-server/blob/b62c5499cefa2f57d8516f3948543383d8387d4b/deps/rabbitmq_cli/lib/rabbitmq/cli/core/exit_codes.ex#L46

Requests/questions: 
1. Could you put the exit codes into the man pages and other documentation, wherever seems appropriate?
2. In this case, is the exit code right, or the stderr message, or both?  The problem was probably a timeout, as the command worked when retried, but I'm not certain.
3. Some projects embed URLs into error messages, linking to an error page on their documentation website or wiki.  That may be too much work to tackle right now, but it sure would be nice to have.  Here's an example error message from rsyslogd: 
```
rsyslogd: version 7.1.11, config validation run (level 3), master config /etc/rsyslog.conf
rsyslogd: error during parsing file /etc/rsyslog.conf, on or before line 51: syntax error [try http://www.rsyslog.com/e/2207 ]
rsyslogd: CONFIG ERROR: could not interpret master config file ‘/etc/rsyslog.conf’. [try http://www.rsyslog.com/e/2207 ]
rsyslogd: run failed with error -2207 (see rsyslog.h or try http://www.rsyslog.com/e/2207 to learn what that number means)
```

Thanks for all the hard work!

**Comment by michaelklishin** [comment]
There are too many things that can go wrong to document them all across some 70+ commands.

We could not find a standard set of codes. The closest there is was [this set of BSD conventions](https://www.freebsd.org/cgi/man.cgi?query=sysexits&apropos=0&sektion=0&manpath=FreeBSD+4.3-RELEASE&format=html), which our CLI tools use.
