### ISSUE TITLE
queue specific metrics for Prometheus

### ISSUE THREAD

**Issue by curuvija** [rabbitmq/rabbitmq-server#3467]
Would it be possible to extend Prometheus metrics to include queue specific metrics. Something like these:

Rabbitmq dead letter queue filling up - Dead letter queue is filling up (> 1 msg) (mandatory)
Rabbitmq too many messages in queue - Queue is filling up (> 1000 msgs) (mandatory)
Rabbitmq slow queue consuming - Queue messages are consumed slowly (> 60s) (mandatory)

Currently for these we are using this exporter https://github.com/kbudde/rabbitmq_exporter. It would be nice to have this out of the box and not use another exporter. I have to say I am not a programmer and I cannot contribute much on this topic besides installation and testing if that helps at all.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
