### ISSUE TITLE
Number of connections a lot more than number of channels

### ISSUE THREAD

**Issue by thayhoang** [rabbitmq/rabbitmq-server#3481]
We're publishing messages to Rabbitmq using Mqtt protocol. On our production environment, I noticed the number of connections is a lot more than number of channels. As my understanding, to connect to an AMQP cluster, you need at least 1 channel.  What's happening here? Does my cluster have any problem?

![image](https://user-images.githubusercontent.com/17960508/134336379-4a1b3d1d-117a-463e-b498-e9663dfcaca2.png)

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
