### ISSUE TITLE
default_user with special characters does not get configured correctly using rabbitmq.conf file.

### ISSUE THREAD

**Issue by kaushiksrinivas** [rabbitmq/rabbitmq-server#3484]
We are using rabbitmq server with both the configuration files i.e rabbitmq.conf and advanced.config file.

The observation is that, the server does not get created with correct username (usernames are randomly picked as substrings of the actual content given for default_user in rabbitmq.conf file) when the user provided in rabbitmq.conf contains special characters, where as the same works when configured through advanced.config file. 
config property : default_user

Are there any restrictions for the default_user when configured in the rabbitmq.conf file ?

**Comment by kaushiksrinivas** [comment]
One example of user name
user_@2!&*

**Comment by mkuratczyk** [comment]
Everything works as expected for me with this username:

```
$ cat user.conf
default_user = user_@2!&*
default_pass = foobar

$  RABBITMQ_CONFIG_FILE=user.conf rabbitmq-server

$ rabbitmqctl list_users
Listing users ...
user	tags
user_@2!&*	[administrator]

$ rabbitmqctl authenticate_user 'user_@2!&*' 'foobar'
Authenticating user "user_@2!&*" ...
Success
```

Please provide the exact commands and version you are using.

**Comment by kaushiksrinivas** [comment]
@mkuratczyk 
Sorry for the confusion. The above user name worked for me as well.
Can you please try with this user name ?

user_@#$%&*

**Comment by mkuratczyk** [comment]
`#` starts a comment so the rest of the line is discarded. [In the docs](https://www.rabbitmq.com/configure.html#config-file) we only mention that lines that with `#` are comments but in-line comments are supported as well. We can explicitly mention this in the docs (feel free to submit a PR to the docs if you want). I believe everything works as expected, you just need to avoid `#`.
