### ISSUE TITLE
Trust store for TLS/x509 certificates

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#350]
E.g. [Riak has a feature in this area](http://docs.basho.com/riak/latest/ops/running/security-sources/#Certificate-based-Authentication).

Originally this issue explored the possibility of adding Certificate Revocation List support. However, several users indicated that whitelisting (à la JDK, .NET) of certificates via a trust store makes more sense and works better in practice. Therefore this issue now focusses on that.

**Comment by rtraschke** [comment]
One way to get started on this road, would be to make use of the SSL verify_fun hook that allows checking details of certificates.

As a motivating example, here's how you could create a static check for whitelisted client peer cert serial numbers.

The config file needs to include the `verify_fun` entry in the `ssl_options` list, something like this:

```erlang
[
    {rabbit, [
        {ssl_listeners, [5671]},
        {ssl_options, [
            {cacertfile, "/Users/rtr/Downloads/rabbitmq_server-3.5.6/testca/cacert.pem"},
            {certfile, "/Users/rtr/Downloads/rabbitmq_server-3.5.6/server/cert.pem"},
            {keyfile, "/Users/rtr/Downloads/rabbitmq_server-3.5.6/server/key.pem"},
            {verify, verify_peer},
            {fail_if_no_peer_cert, false},
            % check if peer client cert has valid serial number
            {verify_fun, {ssl_verify, check, [1, 2, 3, 4, 5, 6, 14410040307426354783]}}
        ]}
    ]}
].
```

This makes every SSL cert check call the function `ssl_verify:check/3` with the user defined list of serial numbers as one of the arguments (plus the cert and event triggering the check).

This function may be implemented along these lines:

```erlang
-module(ssl_verify).
-export([check/3]).

-include_lib("public_key/include/public_key.hrl").

% default verify_fun option in verify_peer mode,
% with added failure on non-whitelisted client cert serial number
% (see http://www.erlang.org/doc/man/ssl.html about verify_fun)

check(_, {bad_cert, _} = Reason, _SerialNumberWhiteList) ->
	{fail, Reason};
check(_, {extension, _}, SerialNumberWhiteList) ->
	{unknown, SerialNumberWhiteList};
check(_, valid, SerialNumberWhiteList) ->
	{valid, SerialNumberWhiteList};
check(OtpCert, valid_peer = Event, SerialNumberWhiteList) ->
	% rabbit_log:info("ssl_verify( ~p, ~p, ~p ).~n", [OtpCert, Event, SerialNumberWhiteList]),
	Serial = OtpCert#'OTPCertificate'.tbsCertificate#'OTPTBSCertificate'.serialNumber,
	case lists:member(Serial, SerialNumberWhiteList) of
		true -> {valid, SerialNumberWhiteList};
		false -> {fail, invalid_serial}
	end.
```

The compiled `ssl_verify.beam` would need to be available in the code path of Rabbit MQ.

**Comment by michaelklishin** [comment]
The above can work but it's not very user-friendly. I suggest that we develop a plugin that provides a verification function that uses a list of certificates e.g. from a directory, driven via config file.

**Comment by Dzol** [comment]
So, the goal is to __whitelist__ clients through their certificates (as opposed to what revocation lists would normally do)?

**Comment by michaelklishin** [comment]
@Dzol no. The goal is pretty standard. But there can be multiple ways to implement it. This is up for debate. I think whitelisting of certificates from a directory can be a reasonable way in some cases.

**Comment by michaelklishin** [comment]
@uvzubovs do you have an opinion on how CRLs should work in RabbitMQ, from a user's perspective?

**Comment by uvzubovs** [comment]
CRL doesn't work for us. It's an availability risk (happened a few times). 

What works is how Java, .NET, DataPower, and other enterprise systems handle this: there is a trust store (Java Key Store, folder, file, etc.) that contains the public key certificates that match the private keys of the authorized clients. Only those clients are allowed to connect regardless of the CA. This seems to work very well, and has been tested both functionally and secure over the past decade having integrated with dozens of business partners. 

White-listing clients may not be palatable when the list is very large, i.e. public Internet and IoT, which is for what CRL was invented. Systems typically implement both strategies: first, see if the cert is in the trust store; if not, then check with the CA.

**Comment by michaelklishin** [comment]
@uvzubovs thank you for the input.

**Comment by michaelklishin** [comment]
I updated the description that we'll focus on certificate whitelisting (providing a trust store) first. CRL (blacklisting) may come later if there's enough interest (and we can find a way to make the two work together in a sensible way).

**Comment by uvzubovs** [comment]
Thank you. For backward compatibility you may implement the strategy to check the trust store first, and if not in the trust store then check if the cert was issued by a particular CA, i.e. fallback to current implementation. If someone wants to disable the latter (like us), they would upload a cert that is not a CA, i.e. of a non-existent CA.

**Comment by david-mohr** [comment]
+1 for CRL.  Riak has implemented this already: https://github.com/basho/riak_api/pull/39/files.  Exporting a function similar to `validate_function` would allows users to opt in for CRL support.

**Comment by Dzol** [comment]
Trust-Store
-----

A [`verify`](http://www.erlang.org/doc/man/ssl.html) function would become a default SSL setting (for listeners from every plugin) if `rabbit` is configured with a valid `trusted_certificates` tuple. Essentially, a procedure (say `whitelisted/1`) will interface with the plugin, which keeps hold of trusted certificate __information__, i.e. in a generic server. The __issuer name__ and __serial number__ being those attributes which uniquely identify certificates [1]. The entry in the configuration file would look something like:

```Erlang
[
    {rabbit, [
       ...
        {trusted_certificates, "/path/to/them/"},
       ...
    ]}
].
```

References
-----

[1] PKI Certificate & CRL Profile, 4.1.2.2. Serial Number: https://tools.ietf.org/html/rfc5280#section-4.1.2.2

**Comment by michaelklishin** [comment]
@Dzol where `/path/to/them` assumes a `/path/to/directory`, correct?

By the way, this doesn't have to be a plugin. If we can make it one, and compatible with `3.6.x`, all the better but if we can't, I think this should then be a core feature in `3.7.0` instead.

**Comment by Dzol** [comment]
> @Dzol where /path/to/them assumes a /path/to/directory, correct?

Yes, that's correct, a path to a directory: edited that part.

This should be `3.6.*` compatible: the only change `rabbit` and plugins will need is to introduce the `{verify_fun, {fun (), term ()}}` option on an SSL socket if necessary. It can can fall back to validation as @uvzubovs suggests.

What should we be aware of w.r.t. `3.6.*` compatibility?

**Comment by michaelklishin** [comment]
@Dzol my point is that we should target (develop & test against) `3.6.x`. If small core changes are necessary, they likely can go into a future `3.6.x` version.

**Comment by bodgit** [comment]
+1 for CRL and/or OCSP support. I'm creating a large number of client certificates on the fly and so putting them into a directory on the server just isn't a feasible solution. When a client certificate is revoked I'm removing the matching ACL from RabbitMQ so if a CRL is temporarily unavailable the user can technically connect to the server, but they can't log in anymore.

While I was looking I noticed in http://www.erlang.org/doc/man/ssl.html that there is `crl_check` along with `crl_cache`. Are those not usable somehow? (Disclaimer: I know -><- this much about Erlang)

**Comment by Dzol** [comment]
> While I was looking I noticed in http://www.erlang.org/doc/man/ssl.html that there is crl_check along with crl_cache. Are those not usable somehow? (Disclaimer: I know -><- this much about Erlang)

@michaelklishin & @bodgit Those are great for CRL, but they wouldn't make it into a `3.6.*` release because they're a recent addition in `18.0`, that is if CRL is still on the table.

**Comment by Dzol** [comment]
__Update__: I have plugin boilerplate in place and will make a start on tests.

**Comment by biiiipy** [comment]
Just wanted to chime in that this feature is critical and I completely agree with what @uvzubovs said - certificate whitelist in a trust store (specifically windows certificate store) would be the best fit for our use case. CRLs work for global scale, not so good for a managed application.

**Comment by michaelklishin** [comment]
@biiiipy we are not looking to support Windows certificate store at first but that's certainly a sensible idea.

**Comment by michaelklishin** [comment]
Now that https://github.com/rabbitmq/rabbitmq-trust-store is open sourced (although we don't consider it to be finished, leave alone have much community feedback on it), I think this can be closed. All new ideas belong to the trust store plugin repo.
