### ISSUE TITLE
lazy queues

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-server#351]
This bug is to experiment with the idea of introducing "lazy queues". The idea is to support use cases where consumers are disconnected for long periods of time, but where we want to support a constant message ingress rate.

Lazy queues are `rabbit_variable_queues` that can work in two modes: `lazy` and `default`. 

**Default** mode is what RabbitMQ supports today: queues maintain a cache of messages in memory, and from time to time, depending on memory pressure, they page some of those messages to disk. The problem with this mode is that if there are too many messages to page out, the queue can become unresponsive, making it hard to predict the behaviour/performance of a queue.

**Lazy** mode: this mode will force queues to write to disk every message as they enter the queue via `basic.publish`. In this case the variable queue _will not cache messages in memory_. Whenever a consumer requests a message, the variable queue will load messages from disk into memory in batches of QI's `?SEGMENT_ENTRY_COUNT` msgs (16384). 

The modes should be configurable either by queue.declare arguments `x-queue-mode = "lazy"`, assuming "default" in the case when no argument is provided.

Queue modes can also be specified via the `queue-mode` policy.

Queue modes can be switched back and forth by setting/unsetting policies.

**Comment by videlalvaro** [comment]
Initial tests with `./runjava.sh com.rabbitmq.examples.PerfTest -p -x 1 -y 1 -s 1000 -q 1000 -f persistent` show that lazy queues have similar performance as default queues when messages are published as persistent.

During the test one can dynamically change policies by calling:

`./scripts/rabbitmqctl set_policy lazy "" '{"queue-mode":"lazy"}'` or
`./scripts/rabbitmqctl set_policy lazy "" '{"queue-mode":"default"}'

**Comment by videlalvaro** [comment]
Comparing RAM usage between queue modes **without consumers** shows the following:

**lazy queue**:    7'805'517 msgs, 75 MB of RAM for the whole node, 19 MB used by the queue.

**default queue**: 4'440'778 msgs, 1.6 GB of RAM for the whole node, 762 mb of RAM used by the queue.

In both cases messages where published by running the following during 360 seconds:

./runjava.sh com.rabbitmq.examples.PerfTest -e sdmp -u sdmp_queue -f persistent -s 1000 -x1 -y0

The default queue accepted less messages because since there are no consumers, from time to time it has to page messages to disk.

**Comment by javaforfun** [comment]
awesome. no paging, no speed drop :-)
