### ISSUE TITLE
Reject with custom reason

### ISSUE THREAD

**Issue by esditm** [rabbitmq/rabbitmq-server#352]
Feature request.

It would be very handy if it was possible to rejected a message with a reason.
In case it's dead lettered then the the reason should be added to the x-death header.

The content of the reason could be an exception. Which would make it very easy to figure out why a message was rejected, and then go fix it :)

**Comment by videlalvaro** [comment]
As you can see [here](http://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.reject.delivery-tag), `basic.reject` in AMQP doesn't support a parameter where you could set a reason.

**Comment by michaelklishin** [comment]
This would be a breaking protocol change, unfortunately.

**Comment by esditm** [comment]
Ah snap. A breaking protocol change is no good :/
