### ISSUE TITLE
The execution of "rabbitmq-diagnostics.bat -q check_running" fails when a rabbitmq-env-conf.bat file is placed in a path with a blank space in the windows environment

### ISSUE THREAD

**Issue by alloy-duralumin** [rabbitmq/rabbitmq-server#3537]
The following steps reproduce the error in the execution of "rabbitmq-diagnostics.bat -q check_running".

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.9.4\sbin>rabbitmq-diagnostics.bat -q check_running
** (FunctionClauseError) no function clause matching in :string.trim_l/2

    The following arguments were given to :string.trim_l/2:

        # 1
        {:error, '\'c:/Program\' ', [<<130, 205, 129, 65, 147, 224, 149, 148, 131, 82, 131, 125, 131, 147, 131, 104, 130, 220, 130, 189, 130, 205, 138, 79, 149, 148, 131, 82, 131, 125, 131, 147, 131, 104, 129, 65, 13, 10, 145, 128, 141, 236, 137, 194, 148, 92, ...>>]}

        # 2
        ['\r\n', 9, 10, 11, 12, 13, 32, 133, 8206, 8207, 8232, 8233]

    (stdlib 3.15) string.erl:841: :string.trim_l/2
    (stdlib 3.15) string.erl:274: :string.trim/3
    src/rabbit_env.erl:1723: :rabbit_env.post_port_cmd_output/3
    src/rabbit_env.erl:1703: :rabbit_env.collect_conf_env_file_output/4
    (stdlib 3.15) lists.erl:1267: :lists.foldl/3
    src/rabbit_env.erl:93: :rabbit_env.get_context/0
    (rabbitmqctl 3.8.0-dev) lib/rabbitmq/cli/core/config.ex:98: RabbitMQ.CLI.Core.Config.get_system_option/2
    (rabbitmqctl 3.8.0-dev) lib/rabbitmq/cli/core/config.ex:23: RabbitMQ.CLI.Core.Config.get_option/2

- Steps to reproduce
1. Install Erlang (otp_win64_24.0.exe)

2. Install rabbitmq(rabbitmq-server-3.9.4.exe)

3. Set the RABBITMQ_BASE to rabbitmq-defaults.bat as follows to place the log files and configuration files in the directory below the installation directory.

set "RABBITMQ_BASE=C:\Program Files\RabbitMQ Server\rabbitmq_server-3.9.4\etc\rabbitmq"

4. Create the configuration file (rabbitmq-env-conf.bat) as follows to change the RABBITMQ_NODENAME and RABBITMQ_NODE_PORT from the default.

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.9.4\etc\rabbitmq\rabbitmq-env-conf.bat

5. Follow these steps to perform a reinstallation and boot.

C:\Program Files\RabbitMQ Server\rabbitmq_server-3.9.4\sbin>rabbitmq-service.bat remove
C:\Program Files\RabbitMQ Server\rabbitmq_server-3.9.4\sbin>rabbitmq-service.bat install
C:\Program Files\RabbitMQ Server\rabbitmq_server-3.9.4\sbin>rabbitmq-service.bat start

6. Run "rabbitmq-diagnostics.bat -q check_running"

- Assumed causes
From the following three points of the verification result, it is assumed that the path resolution fails when the rabbitmq-env-conf.bat file is loaded, if the file is placed in a path that contains a blank space.

1. The execution of "rabbitmq-diagnostics.bat -q check_running" succeeds when the rabbitmq-env-conf.bat file is not placed.
2. The execution of "rabbitmq-diagnostics.bat -q check_running" fails even when a file that does not contain anything in rabbitmq-env-conf.bat is placed.
3. The execution of "rabbitmq-diagnostics.bat -q check_running" succeeds when rabbitmq-env-conf.bat is placed on a path that does not have spaces like C:\test\rabbitmq_server-3.9.4\etc\rabbitmq\rabbitmq-env-conf.bat.

**Comment by lukebakken** [comment]
Here are my reproduction steps. All commands are executed using Powershell:

* Create the `RABBITMQ_BASE` directory:
    ```
    mkdir 'C:\ProgramData\RabbitMQ Server'
    ```
* Start Powershell as an administrator to set a system-wide environment `RABBITMQ_BASE`:
    ```
    [System.Environment]::SetEnvironmentVariable('RABBITMQ_BASE', 'C:\ProgramData\RabbitMQ Server', [System.EnvironmentVariableTarget]::Machine)
    ```
* Open a new Powershell window as administrator and confirm the environment variable:
    ```
    PS C:\Users\bakkenl> dir env:\RABBITMQ_BASE

    Name                           Value
    ----                           -----
    RABBITMQ_BASE                  C:\ProgramData\RabbitMQ Server
    ```
* Proceed to install RabbitMQ. Ensure that "RabbitMQ Service" checkbox is selected so that the service starts:
    ```
    PS C:\Users\bakkenl\Downloads> .\rabbitmq-server-3.10.7.exe
    ```
* Ensure that RabbitMQ is running:
    ```
    PS C:\Users\bakkenl\Downloads> cd 'C:\Program Files\RabbitMQ Server\rabbitmq_server-3.10.7\'

    PS C:\Program Files\RabbitMQ Server\rabbitmq_server-3.10.7> .\sbin\rabbitmqctl.bat status
    Status of node rabbit@bakkenl-z01 ...
    ←[1mRuntime←[0m

    OS PID: 4416
    OS: Windows
    Uptime (seconds): 35
    Is under maintenance?: false
    RabbitMQ version: 3.10.7
    Node name: rabbit@bakkenl-z01
    Erlang configuration: Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]
    Crypto library: OpenSSL 1.1.1d  10 Sep 2019
    Erlang processes: 317 used, 1048576 limit
    Scheduler run queue: 1
    Cluster heartbeat timeout (net_ticktime): 60
    ...
    ...
    ...
    PS C:\Program Files\RabbitMQ Server\rabbitmq_server-3.10.7> sc query rabbitmq

    SERVICE_NAME: rabbitmq
            TYPE               : 10  WIN32_OWN_PROCESS
            STATE              : 4  RUNNING
                                    (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
            WIN32_EXIT_CODE    : 0  (0x0)
            SERVICE_EXIT_CODE  : 0  (0x0)
            CHECKPOINT         : 0x0
            WAIT_HINT          : 0x0

    PS C:\Program Files\RabbitMQ Server\rabbitmq_server-3.10.7> .\sbin\rabbitmqctl.bat eval 'os:getenv(\"RABBITMQ_BASE\").'
    "C:\\ProgramData\\RabbitMQ Server"
    ```
* Create the `rabbitmq-env-conf.bat` file:
    ```
    PS C:\Program Files\RabbitMQ Server\rabbitmq_server-3.10.7> cat $env:RABBITMQ_BASE\rabbitmq-env-conf.bat
    @echo off
    set NODENAME=rabbit@localhost
    set NODE_PORT=5673
    ```
* Stop, re-install, and restart RabbitMQ. Notice that the node name has changed, but the node port hasn't. That's a bug.
    ```
    PS C:\Program Files\RabbitMQ Server\rabbitmq_server-3.10.7> .\sbin\rabbitmq-service.bat stop
    The RabbitMQ service is stopping.
    The RabbitMQ service was stopped successfully.

    PS C:\Program Files\RabbitMQ Server\rabbitmq_server-3.10.7> .\sbin\rabbitmq-service.bat remove
    C:\tools\erl-25.0.3\erts-13.0.3\bin\erlsrv: Service RabbitMQ removed from system.

    PS C:\Program Files\RabbitMQ Server\rabbitmq_server-3.10.7> .\sbin\rabbitmq-service.bat install
    C:\tools\erl-25.0.3\erts-13.0.3\bin\erlsrv: Service RabbitMQ added to system.

    PS C:\Program Files\RabbitMQ Server\rabbitmq_server-3.10.7> .\sbin\rabbitmq-service.bat start
    The RabbitMQ service is starting.
    The RabbitMQ service was started successfully.

    PS C:\Program Files\RabbitMQ Server\rabbitmq_server-3.10.7> .\sbin\rabbitmqctl.bat status
    Status of node rabbit@localhost ...
    ←[1mRuntime←[0m

    OS PID: 7872
    OS: Windows
    Uptime (seconds): 13
    Is under maintenance?: false
    RabbitMQ version: 3.10.7
    Node name: rabbit@localhost
    Erlang configuration: Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]
    Crypto library: OpenSSL 1.1.1d  10 Sep 2019
    Erlang processes: 317 used, 1048576 limit
    Scheduler run queue: 1
    Cluster heartbeat timeout (net_ticktime): 60

    ←[1mPlugins←[0m

    Enabled plugin file: c:/ProgramData/RabbitMQ Server/enabled_plugins
    Enabled plugins:


    ←[1mData directory←[0m

    Node data directory: c:/ProgramData/RabbitMQ Server/db/rabbit@localhost-mnesia
    Raft data directory: c:/ProgramData/RabbitMQ Server/db/rabbit@localhost-mnesia/quorum/rabbit@localhost

    ←[1mConfig files←[0m


    ←[1mLog file(s)←[0m

    * <stdout>
    * c:/ProgramData/RabbitMQ Server/log/rabbit@localhost.log
    * c:/ProgramData/RabbitMQ Server/log/rabbit@localhost_upgrade.log
    ...
    ...
    ...
    ```
* **FINALLY**, run the diagnostics command, which works:
    ```
    PS C:\Program Files\RabbitMQ Server\rabbitmq_server-3.10.7> .\sbin\rabbitmq-diagnostics.bat -q check_running
    RabbitMQ on node rabbit@localhost is fully booted and running
    ```

**Conclusion:**

In your environment, you should set `RABBITMQ_BASE` as a *SYSTEM* environment variable like I did.
