### ISSUE TITLE
Extend rabbitmqctl to list down nodes

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-server#357]
Currently, there is no direct means of listing down nodes with `rabbitmqctl`. When using 
`./rabbitmqctl cluster_status` for example, more info than required is returned when the need would be to only view a list of down nodes. You'd have to analyse the results to some extent to figure out which cluster nodes are down.

**Comment by jiajunsu** [comment]
For getting down nodes, there is a method by rabbitmqctl eval "rabbit_mnesia:cluster_nodes(all)--rabbit_mnesia:cluster_nodes(running)." 
But this method may not work if all running nodes have been restarted(stop_app then start_app) after several nodes down. (cause restart may flush the 'all' nodes)

**Comment by Ayanda-D** [comment]
@michaelklishin we had some discussions on idea of listing down nodes, as part of  `./rabbitmqctl cluster_status` response, under a `down_nodes` tag. WDYT? Or shall we have a separate command for listing down nodes?

**Comment by michaelklishin** [comment]
No, `cluster_status` sounds appropriate to me.

**Comment by Ayanda-D** [comment]
Changing this into two separate features. Leaving this for listing down nodes.

**Comment by michaelklishin** [comment]
Fixed in #706, closing w/o milestone in favour of #688.
