### ISSUE TITLE
RabbitMq Node statistics not available in the third node(RabbitMQ 3.9.8 Erlang 24.1)

### ISSUE THREAD

**Issue by rajamadhu** [rabbitmq/rabbitmq-server#3674]
I have installed RabbitMQ in centos in node1(master) and node2(slave) is 3.8.2 Erlang 22.2 lower version and added new node 3 (slave) is RabbitMQ 3.9.8 Erlang 24.1,when i clustered node1 and node 2 is shows fine and but node 3 is i can able to join the cluster when i see the RabbitMQ Overview Node statistics not available in the node3.

when check the cluster status all three nodes are able to see and policy
i compared both version management plugin enabled.
enabled rabbitmq-plugins rabbitmq_management and restarted services.

node1 and node 2 when i check the management below screen shot.
 ![alt text](https://i.stack.imgur.com/rejnu.png)

when i check the 3rd node  UI management console below screen shot.
 ![alt text](https://i.stack.imgur.com/cMzxn.png)

kindly suggest if anything i missed.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
