### ISSUE TITLE
rabbitmq-management not working 3.9.8 (IE 11)

### ISSUE THREAD

**Issue by LordR7** [rabbitmq/rabbitmq-server#3686]
The web management site does not work on the current RabbitMQ Release 3.9.8 with Internet Explorer 11 (site is empty). 3.9.7 works without problems. With Firefox the problem does not occur.
Maybe the issue is in:
dispatcher.js, Row: 194, column: 47

If i copy the dispatcher.js from Release 3.9.7 to 3.9.8 the site works again.

![grafik](https://user-images.githubusercontent.com/94077993/141186990-ee4b71f3-c723-4fbd-b95f-a45ac050e14f.png)

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
