### ISSUE TITLE
queue-master-locator policy has the wrong name

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-server#369]
See here: https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_queue_location_validator.erl#L28

Policies don't have the `x-` prefix. That's only for declare parameters.

**Comment by michaelklishin** [comment]
@videlalvaro so we'd still keep the `queue.declare` arguments key prefixed with an `x-`? So far I've updated the docs to only mention setting locator via policies, to not have to explain this difference.

**Comment by videlalvaro** [comment]
Yes. Arguments have the x- prefix because they are protocol extensions.
Policies don't use that.

**Comment by michaelklishin** [comment]
@videlalvaro https://github.com/rabbitmq/rabbitmq-server/pull/380, https://github.com/rabbitmq/rabbitmq-test/pull/6, https://github.com/rabbitmq/rabbitmq-website/pull/98 are ready. The `queue.declare` argument key is unchanged.

**Comment by michaelklishin** [comment]
#380 is no longer relevant, see https://github.com/rabbitmq/rabbitmq-server/pull/390. https://github.com/rabbitmq/rabbitmq-test/pull/6 has been updated.

**Comment by michaelklishin** [comment]
@videlalvaro friendly reminder that this is waiting QA.

**Comment by videlalvaro** [comment]
@michaelklishin once I'm able to run the tests I will QA this and other PRs

**Comment by videlalvaro** [comment]
Fixed via https://github.com/rabbitmq/rabbitmq-server/pull/390 and related tickets
