### ISSUE TITLE
Allow quorum queues with `max-in-memory=0` to take state machine checkpoints to speed up recovery after restart

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/rabbitmq-server#3693]
Quorum queues that don't keep messages in memory and instead re-read them from the log when consumed could comfortably take occasional "checkpoints" of the machine state to speed up recovery. A checkpoint is like a snapshot but it does not truncate the log. for example a quorum queue with 1M messages may:
* Have a log from index 10000 to 1010000
* Have a snapshot at index 10000
* Have a checkpoint at index 1000000

On recovery the server would read the checkpoint state at index 1000000 and only then have to read an additional 10k entries from the log to recover the current state which should be substantially faster than reading over 1M of entries from the log.

This feature would require support in Ra.

**Comment by mkuratczyk** [comment]
Quorum queues in RabbitMQ 4.0 use checkpoints to speed up recovery
https://www.rabbitmq.com/blog/2024/08/28/quorum-queues-in-4.0#faster-recovery-of-long-queues
