### ISSUE TITLE
Document x-stream-offset "interval offset"

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#3695]
`parse_offset_arg` -> `check_max_age`

**Comment by acogoluegnes** [comment]
If I get right from the code, it's using the same syntax as the `x-max-age` argument for policies.

![image](https://user-images.githubusercontent.com/514737/141752107-7eeca04d-ad4a-44b4-aaa7-9f3413ce58d3.png)

The duration is converted into milliseconds and subtracted to the current time. This is then used as a `{timestamp, Offset}` offset specification.
