### ISSUE TITLE
queue-master-locator policy documentation is not correct

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-server#370]
See: https://github.com/rabbitmq/rabbitmq-website/blob/master/site/ha.xml#L141

and related server bug https://github.com/rabbitmq/rabbitmq-server/issues/369

**Comment by michaelklishin** [comment]
If only the docs are incorrect, shouldn't this be in `rabbitmq-website`?

**Comment by michaelklishin** [comment]
This seems like a natural part of #369, so closing.
