### ISSUE TITLE
error on consumer cancel for a quorum queue containing messages

### ISSUE THREAD

**Issue by s-at-ik** [rabbitmq/rabbitmq-server#3729]
Hello,

I've been encountering weird problems with pika's `basic_cancel` and I've been able to trace it back to quorum queues, specifically when they contain messages. I'm submitting the issue here as I believe quorum queues to be a rabbitmq-specific feature and I do not believe pika to be doing anything fancy in this case.

Minimal python code to replicate the problem:

```
import pika
import time

def dummy():
    pass

def test(queue, arguments, message):
    try:
        print(f"declaring {queue}")
        connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
        channel = connection.channel()
        channel.queue_declare(queue=queue, durable=True, arguments=arguments)
        if message:
            channel.basic_publish(exchange="", routing_key=queue, body="test")
        ctag = channel.basic_consume(queue, on_message_callback=dummy)

        state = channel.queue_declare(queue=queue, passive=True)
        print(f"current consumers {queue}: {state.method.consumer_count}")

        print(f"cancelling {queue}")
        channel.basic_cancel(ctag)
        time.sleep(2)

        state = channel.queue_declare(queue=queue, passive=True)
        print(f"current consumers {queue}: {state.method.consumer_count}")

        print()
        channel.close()
        connection.close()
    except Exception as e:
        print(f"error: {e}")


test(queue="queue", arguments={}, message=False)

test(queue="quorum_queue", arguments={"x-queue-type": "quorum"}, message=False)

test(queue="queue_with_message", arguments={}, message=True)

test(queue="quorum_queue_with_message", arguments={"x-queue-type": "quorum"}, message=True)
```

When run against rabbitmq 3.8:

```
declaring queue
current consumers queue: 1
cancelling queue
current consumers queue: 0

declaring quorum_queue
current consumers quorum_queue: 1
cancelling quorum_queue
current consumers quorum_queue: 0

declaring queue_with_message
current consumers queue_with_message: 1
cancelling queue_with_message
current consumers queue_with_message: 0

declaring quorum_queue_with_message
current consumers quorum_queue_with_message: 1
cancelling quorum_queue_with_message
current consumers quorum_queue_with_message: 1
```

When run against rabbitmq 3.9:

```
declaring queue
current consumers queue: 1
cancelling queue
current consumers queue: 0

declaring quorum_queue
current consumers quorum_queue: 1
cancelling quorum_queue
current consumers quorum_queue: 0

declaring queue_with_message
current consumers queue_with_message: 1
cancelling queue_with_message
current consumers queue_with_message: 0

declaring quorum_queue_with_message
current consumers quorum_queue_with_message: 1
cancelling quorum_queue_with_message
error: (541, 'INTERNAL_ERROR')
```

[log for the internal error](https://github.com/rabbitmq/rabbitmq-server/files/7539238/rabbitmq.log)

**Comment by lukebakken** [comment]
Thank you for the detailed report and reproduction steps. We will look into it.

**Comment by lukebakken** [comment]
@s-at-ik I have reproduced this error using the `master` branch of RabbitMQ. @kjnilsson I'll need assistance looking into this.

**Comment by lukebakken** [comment]
I can trigger an error with RabbitMQ 3.8.25: [rabbit-v3.8.25.log](https://github.com/rabbitmq/rabbitmq-server/files/7548767/rabbit-v3.8.25.log)

**Comment by lukebakken** [comment]
Using RabbitMQ 3.8.0, there is no crash, but the consumer isn't cancelled as expected:

```
declaring quorum_queue_with_message
current consumers quorum_queue_with_message: 1
cancelling quorum_queue_with_message
current consumers quorum_queue_with_message: 1
```

Log file: [rabbit-v3.8.0.log](https://github.com/rabbitmq/rabbitmq-server/files/7548833/rabbit-v3.8.0.log)

**Comment by lukebakken** [comment]
No 3.8.x versions exhibit this error, but they do show that consumers aren't cancelled as expected.

**Comment by lukebakken** [comment]
Yep, the issue first presents itself using RabbitMQ 3.9.0. It appears that `ra_fifo_client:handle_delivery/4` in the 3.8 series has a default value for `maps:get`, while the default was removed in 3.9:

* 3.8 - https://github.com/rabbitmq/rabbitmq-server/blob/v3.8.x/deps/rabbit/src/rabbit_fifo_client.erl#L707
* 3.9 - https://github.com/rabbitmq/rabbitmq-server/blob/v3.9.x/deps/rabbit/src/rabbit_fifo_client.erl#L741

Next I'll test restoring the default value. I expect to see the same incorrect behavior as 3.8.x but without a crash.

**Comment by lukebakken** [comment]
This is a bonus. Restoring the default value fixes the crash and something else has fixed the erroneous behavior:

```
declaring quorum_queue_with_message
current consumers quorum_queue_with_message: 1
cancelling quorum_queue_with_message
current consumers quorum_queue_with_message: 0
```

PR on the way.

**Comment by s-at-ik** [comment]
Thank you for the fix :+1:
