### ISSUE TITLE
Crash RabbitMQ using `RABBITMQ_LOGS` or `RABBITMQ_SASL_LOGS` from 3.5.4 and greater

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-server#375]
Env:
RabbitMQ version 3.5.4  and greater.
Windows 2012 server.

Setting these two variables :

set RABBITMQ_SASL_LOGS=C:\myfolder\log\
set RABBITMQ_LOGS=C:\myfolder\log\

RabbitMQ crash on startup, report:

    =ERROR REPORT==== 21-Oct-2015::03:11:57 ===
    application_controller: unterminated string starting with "=/RABBITMQ_ENABL": {file,"\=/RABBITMQ_ENABLED_PLUGINS_FILE:\=/RABBITMQ_PLUGINS_DIR:\=/RABBI
    TMQ_PLUGINS_EXPAND_DIR:\=/RABBITMQ_MNESIA_DIR:\=/RABBITMQ_SERVER_START_ARGSRABBITMQ_DIST_ARGSTAR
    
    =INFO REPORT==== 21-Oct-2015::03:11:57 ===
    Error description:
       {case_clause,
           {error,
               {bad_environment_value,
                   "{file,\"\\=/RABBITMQ_ENABLED_PLUGINS_FILE:\\=/RABBITMQ_PLUGINS_DIR:\\=/RABBITMQ_PLUGINS_EXPAND_DIR:\\=/RABBITMQ_MNESIA_DIR:\\=/RABBITM
    Q_SERVER_START_ARGSRABBITMQ_DIST_ARGSTAR"}}}
     

Using RabbitMQ version 3.4.1, these two variables does **not** work as documented [here](https://www.rabbitmq.com/relocate.html), but RabbitMQ does't crash.

**Comment by michaelklishin** [comment]
Fixed in #376, thank you @Gsantomaggio.
