### ISSUE TITLE
Connection closed with INTERNAL ERROR (541) upon basic.publish of response of a federated request

### ISSUE THREAD

**Issue by robkut** [rabbitmq/rabbitmq-server#3751]
Hi,

Client connection get closed with 541 - INTERNAL ERROR on basic.publish of a direct reply-to response, if the request is originated in a different cluster and routed via federated exchange.

We open a discussion: 
https://groups.google.com/g/rabbitmq-users/c/B2Fq8SnohO4
and found a second one:
https://groups.google.com/g/rabbitmq-users/c/KoazHyNL484
with a good scenario description:
1. we have two clusters setup (A and B) with federation links configured from A to B and from B to A for all of the queues. Both clusters have same set of queues.
2. app from cluster A sends message to some queue using https://www.rabbitmq.com/direct-reply-to.html
3. in case when that queue doesn't have any consumers in cluster A the message is being moved to cluster B by federation plugin
4. consumer from cluster B receives the message and tries to reply to the queue provided in replyTo header
5. since that reply to queue with generated name is unknown to cluster B we saw a routing error here

attached a trace of the amqp messages
[internal_error_541.zip](https://github.com/rabbitmq/rabbitmq-server/files/7553604/internal_error_541.zip)

**Comment by michaelklishin** [comment]
Direct reply-to cannot be used across channels, leave alone clusters. It's not really a queue, it's a piece of channel state,
and any attempt to use it in a different channel is expected to fail deserialization (the reply-to value encodes certain identifiers).

**Comment by robkut** [comment]
@michaelklishin thanks for the (definitive) answer!

**Comment by robkut** [comment]
@michaelklishin we previously used rabbitmq in version 3.8.3, there connections weren't closed upon direct reply-to via federation. Did we use a loop hole? Or is this behavior (connection close) introduced because of a specific reason?

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-server/pull/2842 and https://github.com/rabbitmq/rabbitmq-server/pull/2857 are some recent changes to how "reply-to" identifiers are encoded. Previously there was virtually no chance it could possibly
fail. Now they embed cluster-specific node name hashes (to avoid overflowing with very long node names).

Direct reply-to was never meant to be used together with federation. It's a more efficient request-reply mechanism that avoids declaration of a very short lived reply queue. It never was mean to be and cannot be aware of federation message transfers.

**Comment by robkut** [comment]
Thanks!
