### ISSUE TITLE
rabbitmq management plugins support with TLSV1.3

### ISSUE THREAD

**Issue by kaushiksrinivas** [rabbitmq/rabbitmq-server#3756]
Documentations refer to tlsv1.3 for rabbitmq server only. Is TLSv1.3 officially supported for the management plugin api of the rabbitmq server ?

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
