### ISSUE TITLE
Querying the message count of a stream with `queue_declare`'s returned message count is inconsistent across cluster nodes

### ISSUE THREAD

**Issue by Raz-Hemo** [rabbitmq/rabbitmq-server#3758]
We have a cluster setup of 3 rabbitmq nodes. I was trying to read the size of a queue of type stream on the cluster using the message_count field sent by rabbit when declaring a queue, but it gave varying results depending on which node I connected to - one gave the real message count, while the others gave different values. 

Surprisingly enough the node that gave the correct answer was not the stream leader.

**Comment by lukebakken** [comment]
Thanks for the report.

I would really appreciate a script or program we could run to demonstrate the issue. It should also set up the stream queue in exactly the same manner you have. I could _guess_ at how you're doing everything but there's a very good chance I would do something differently and get a different result.

**Comment by Raz-Hemo** [comment]
Sorry for the delay.

We used rust with the lapin library for this. Here is a stripped-down version of the code with only relevant bits:
```
let connection = Connection::connect("amqp://guest:guest@rabbitmq//", properties).await?;
let mut channel = connection.create_channel().await?;

channel
    .basic_qos(1000u16, BasicQosOptions { global: false })
    .await?;

let mut queue_args = FieldTable::default();
queue_args.insert(
    ShortString::from("x-queue-type"),
    AMQPValue::LongString("stream".into()),
);
queue_args.insert(
    ShortString::from("x-max-length-bytes"),
    AMQPValue::LongLongInt(20000000000),
);
queue_args.insert(
    ShortString::from("x-queue-leader-locator"),
    AMQPValue::LongString("least-leaders".into()),
);
queue_args.insert(
    ShortString::from("x-stream-max-segment-size-bytes"),
    AMQPValue::LongLongInt(500000000),
);

.queue_declare(
    "my_stream",
    QueueDeclareOptions {
        durable: true,
        auto_delete: false,
        ..Default::default()
    },
    queue_args.clone(),
).await?;

channel
    .queue_bind(
        "my_stream",
        "my_exchange",
        "",
        Default::default(),
        FieldTable::default(),
    )
    .await?;

// ...
// Here you should push some messages to the stream
// ...

// This part of the code will yield different results depending on the connection you use - after pushing the messages, run this against every node in the cluster
let mut consumer = channel
    .basic_consume(
        stream_name,
        "predictions-processor-stream-offset-retreiver",
        BasicConsumeOptions {
            no_ack: false,
            ..Default::default()
        },
        FieldTable::default(),
    )
    .await?;

let (_, delivery) = consumer.next().await.context("Failed to consume a message from stream")??;
match delivery
    .properties
    .headers()
    .as_ref()?
    .inner()
    .get("x-stream-offset")?
{
    AMQPValue::LongLongInt(stream_offset) => {println!("{:?}", *stream_offset as u64);},
    _ => ()
}
```

**Comment by Raz-Hemo** [comment]
Actually I found a stupid mistake on my end - the code that checks the last offset doesn't use `x-stream-offset=last`. I use it now and it seemed to fix the issue.
Excuse me for the inconvenience 😅

**Comment by dcorbacho** [comment]
Thanks for the report @Raz-Hemo, this PR solves the issue: https://github.com/rabbitmq/rabbitmq-server/pull/3814

Please take into account that the metrics update happens periodically (defaults to 5s) so it might take a bit for the actual value to be returned by `queue.declare` on existing queues.

**Comment by Raz-Hemo** [comment]
Thanks :) I think the small delay is acceptable given the fact that it's a distributed system, so it's only natural.
