### ISSUE TITLE
RabbitMQ Streams timestamp incorrect value in delivered message chunk

### ISSUE THREAD

**Issue by wrobell** [rabbitmq/rabbitmq-server#3769]
First check timestamp of messages

1. Start RabbitMQ broker.
2. Store some messages in a stream.
3. Receive the messages - timestamp is correct.

Now, put laptop to sleep and *without* restarting the RabbitMQ broker

1. Store new messages in the stream.
2. Receive the messages - timestamp is incorrect. It is shifted by about the time the laptop slept.

Restart Rabbit MQ broker

1. Store new messages in the stream.
2. Receive the messages - timestamp is correct.

I would expect the timestamp to always match the actual time.

**Comment by lhoguin** [comment]
Hello!

RabbitMQ is built using Erlang/OTP. Erlang/OTP is built for server applications, devices that do not go to sleep. That said, not all is lost!

By default Erlang will do time correction, meaning the Erlang system time slowly moves toward the OS system time. If you continue storing and reading messages, it will at some point catch up with the real time. But this can take a while.

By default Erlang does NOT do time warps. This is what you would expect in your case. RabbitMQ is not configured for time warps either. With time warps, Erlang can immediately correct time when your laptop wakes up from sleep. You can find more information here: https://www.erlang.org/doc/apps/erts/time_correction.html#time-warp-modes - and this page has all the details for time correction if you are curious.

If you want to use time warps, you can export `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` and set `+C multi_time_warp` for example.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
