### ISSUE TITLE
Mitigate effects of repeated re-queues in quorum queues.

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/rabbitmq-server#3778]
#3776 outlines a potential approach for quorum queues to handle repeated re-queues better. This is a breaking change however and will require a new machine version.

To reduce the impact in the short term we could do the following which does not require any changes to the v1 quorum queue state machine code.

When the channel (`rabbit_fifo_client`) receives a re-queue return for a quorum queue we don’t send it to the queue immediately. Instead we hold on to it for a few seconds in the channel before sending it. This has two effects:
If a client returns many messages after each other we can batch them into a single command which reduces log disk use (without having to change the data format)
It provides a bit of back-pressure as the returned messages won’t be immediately re-delivered back to the consumer for another failed processing attempt.

**Comment by dumbbell** [comment]
I like this idea.

Does it mean that the rejected message could be re-delivered to the consumer without going through the queue?

**Comment by kjnilsson** [comment]
> Does it mean that the rejected message could be re-delivered to the consumer without going through the queue?

No it needs to go back to the queue to have its delivery_count incremented and so on. This just throttles stuff a bit.

**Comment by kjnilsson** [comment]
Another approach would be to have the `rabbit_fifo_client` detect when a certain number of delivery attempts have been made for a message and if this message is returned again the client republishes the message as a new enqueue request and rejects the old message _without_ requeue. This will put the message at the back of the queue and we will lose the delivery_count (but could record it in a header perhaps). This does mess a bit with the requeue semantics but that is perhaps better than allowing the raft log to grow unbounded.

**Comment by kjnilsson** [comment]
Closing as we are implementing #3776 as part of #3121
