### ISSUE TITLE
Static Shovel creates a classic queue instead of a quorum queue

### ISSUE THREAD

**Issue by Jaqy** [rabbitmq/rabbitmq-server#3782]
When creating a static shovel and declaring the queue as quorum as follows: 
```
...
[{'queue.declare', 
  [{queue, <<"test_shovel_queue">>}, 
    [{durable, true},
     {arguments, 
      [{<<"x-queue-type">>, longstr, <<"quorum">>},
       {<<"x-quorum-initial-group-size">>, long, 3}
      ]}
    ]
  ]}
  ...
  ```
  
  the shovel create a `classic queue` instead of `quorum queue`.
  
  I have been looking into the code of the shovel and I think the error might be in the `rabbit_shovel_parameters.erl` file 
  On line 453: 
```
ensure_queue(Conn, Queue, XArgs) ->
    {ok, Ch} = amqp_connection:open_channel(Conn),
    try
        amqp_channel:call(Ch, #'queue.declare'{queue   = Queue,
                                               passive = true})
    catch exit:{{shutdown, {server_initiated_close, ?NOT_FOUND, _Text}}, _} ->
            {ok, Ch2} = amqp_connection:open_channel(Conn),
            amqp_channel:call(Ch2, #'queue.declare'{queue     = Queue,
                                                    durable   = true,
                                                    arguments = XArgs}),
            catch amqp_channel:close(Ch2)

    after
        catch amqp_channel:close(Ch)
    end.
```

From my understanding would this my queue declaration in this function always pass the `try`, and it is not until in the `catch exit` that we we call the `queue.declare` with the `XArgs` arguments. 

I think that's why my static shovel is creating a `classic queue` instead of a `quorum queue`

**Comment by michaelklishin** [comment]
Simply declare the queue ahead of time, using any type or parameters you need. Making Shovels aware of every feature and type is not particularly important since the topology can be declared earlier, in particular in case of static Shovels.

**Comment by Jaqy** [comment]
Thanks for your reply and I am aware that this is possible :smiley: 

But by allowing the shovel to do declare the queue and set the bindings, can the shovel restore the connection itself between 2 rabbits in case the source queue disappears for some reason.

I was under the impression that the `static shovel` is suppose to be able to do this with the `XArgs`. 

If that is not the case, what is than the intended functionally is for the `XArgs` params ?
