### ISSUE TITLE
Need help to set up RabbitMQ SSL to use certificates from azure key vault

### ISSUE THREAD

**Issue by nikhithamantri** [rabbitmq/rabbitmq-server#3785]
Hi Team,
We are running RabbitMQ with SSL certificates residing in RabbitMQ config path in respective VMs.
As per project recommendation, these certs should be migrated from RabbitMQ VMs to azure key vault for security reason.
Does RabbitMQ support reading the certificates remotely from azure key vault rather than on the same VM?
If yes,Is there a documentation or guidance available to achieve this objective?
Currently we have the certs in path
ssl_options.cacertfile = /etc/rabbitmq/testca/DigiCertCA.crt
ssl_options.certfile   = /etc/rabbitmq/testca/cbxprrabbit_prod_etransfercbx_cibc_com.crt
ssl_options.keyfile    = /etc/rabbitmq/testca/cbxprrabbit.prod.etransfercbx.cibc.com.key

We are trying to pull it from Rabbit MQ using azure key vault API like below.
ssl_options.certfile: https://common-kv-nonprod.vault.azure.net/certificates/sitmiddleware-etransfercbx-cibc-com/90b4c522e178428cbb00eea61cd3d63e
Any help would be much appreciated.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
