### ISSUE TITLE
Blocked connection due to multiple resource alarms may be cleared by a single node in a cluster

### ISSUE THREAD

**Issue by noahhaon** [rabbitmq/rabbitmq-server#379]
Steps to reproduce:

1. Cause 2 of 3 nodes in a cluster to raise a disk resource alarm
2. Observe publisher connections enter `blocked` state
3. Clear the disk resource alarm on 1 of 2 nodes
4. Observe resource alarm remaining on 1 node
5. Observe publisher connections leaving `blocked` state despite 1 node still in a resource alarm state

**Comment by videlalvaro** [comment]
Can I assume that a memory alarm would cause the same symptoms?

**Comment by videlalvaro** [comment]
>Observe publisher connections leaving blocked state despite 1 node still in a resource alarm state

So what happens if we unblock publishers and then they publish a message that has to be replicated to the node that still has the resource alarm?

**Comment by michaelklishin** [comment]
Any alarm should behave the same way. We should not clear the alarm if there is at least 1 node online that is in alarmed state. That has been the intent all along.

**Comment by noahhaon** [comment]
> Can I assume that a memory alarm would cause the same symptoms?

> So what happens if we unblock publishers and then they publish a message that has to be replicated to the node that still has the resource alarm?

I seem to recall running into this case with earlier versions of RMQ, and it leading to node crashes as the publishers would become unblocked and memory pressure on the affected node would continue to increase. I believe in that case it was for a slave of a mirrored queue.  We still need to verify the recent improvements/fixes to mirrored queue performance, but I suspect those issues were the root cause of the memory exhaustion.

The publishers may enter a flow control state, but that seems like it was incidental to the alarm.

**Comment by michaelklishin** [comment]
PRs mergeable into master:

 * https://github.com/rabbitmq/rabbitmq-server/pull/395
 * https://github.com/rabbitmq/rabbitmq-common/pull/1

**Comment by michaelklishin** [comment]
Fixed in master. Thank you, @binarin.
