### ISSUE TITLE
Closed connections are not detected during resource alarm

### ISSUE THREAD

**Issue by binarin** [rabbitmq/rabbitmq-server#384]
Steps to reproduce:

1) Set some resource alarm
2) Connect to server through amqp and try to publish message, become blocked
3) Do ungraceful shutdown of blocked connection (I've used `kill -9` on publisher)
4) Observe that there is nothing in logs about lost connection
5) Clear resource alarm
6) Observe message(s) about lost connections

So, mechanism intended to protect cluster from resource starvation, coupled with impolite clients, can actually result in more memory consumption.

The only part of the system that is aware of lost connection is heartbeater process SendFun, which tries to send heartbeats through dead socket, and receives `closed` and `notconn`, but happily ignores them - it even has `catch` there.

Given that on receiving side `{active, once}` option is used and it is not being set when throttling is in effect, `rabbit_net:send/2` in the `SendFun` is the only place where lost connection could be detected.

**Comment by michaelklishin** [comment]
We are aware of this. From our research it is not possible to know that a connection is closed by the peer without reading from the socket. So far nobody could come up with a workaround.

**Comment by michaelklishin** [comment]
To clarify: we would be interested in solving this but so far none of the suggestions we've seen can avoid the fact that peer disconnection can only be detected when/after a socket read is performed. Now that
we are going to require `R16B03` for `3.6.0` and 18.x for later versions, there may be OTP updates that would pave a way for us to finally solve this. But so far there's been no success in 4 years or so.

**Comment by binarin** [comment]
As heartbeater process is doing constant `rabbit_net:send/2` to client socket, it is possible to detect dead socket after 2 heartbeat intervals. And it will be possible to notify parent process about lost connection at that point. So at least some sort of fix is possible now.

There is no portable way to detect lost connection without doing `send` or `recv`, and looks like it is not an Erlang problem, but just the way sockets work.

I haven't looked into other OSes, but on linux you can use linux-specific `getsockopt` `TCP_INFO` and if state!=`ESTABLISHED`, you can infer that socket is dead. So if this `getsockopt` call is wrapped into NIF, than on some OSes it will be possible to detect dead sockets faster than 2 heartbeat intervals. Will be the patch with such NIF accepted?

**Comment by michaelklishin** [comment]
Reopening as @binarin may have found a sensible solution.

**Comment by michaelklishin** [comment]
This looks reasonable but there is one important aspect we need to consider: with many clients, a blocked connection won't be considered to be dead due to heartbeats. It's debatable whether it should be
but that's certainly the case for some clients.

If this is merged, with lower-ish heartbeat intervals (e.g. 5-10 seconds, which is not uncommon), connections would be dropped by the server fairly quickly when it encounters a resource-based alarm.

Is this nonetheless a better outcome than what we have today for end user?

**Comment by michaelklishin** [comment]
Some experiments suggest that I may be wrong: only connections of disconnected clients end up being cleaned up, which is what we want.

**Comment by binarin** [comment]
When connection is blocked due to resource alarm, heartbeat receiver is paused and no heartbeat checks are being performed. But heartbeat sender is not stopped and periodically sends data over network. And only when it is not able to send another packet to the network, it'll notify parent process.

So this change should only affect the behaviour of dropped connections.

The only "incompatibility" I can see is that `rabbit_reader:stop/2` could be called with different `Reason` (compared to pre-patch code). But it'll require very precise timing of events and the outcome will be still the same - a properly stopped connection.

**Comment by michaelklishin** [comment]
Right, which makes sense, because we only stop reading from the socket but writing still succeeds as long as the peer is alive/reachable.

**Comment by michaelklishin** [comment]
@binarin merged. If you feel this has to also be in `3.5.7`, you know what to do ;) Thank you for figuring out a straightforward and effective solution. This issue has been open for much of RabbitMQ's existence.

**Comment by belesev** [comment]
Do I understand right that before RMQ Server v3.6.0 the behavior after _resource alarm_ was like that:
several TCP connections could hang on server side per 1 real client autorecovery connection?

We encountered the behavior like that in exactly 3.6.0 (we know it's time to upgrade, we've already done that on the other server node) with enabled heartbeats (60s) on both server and client side.
And even RMQ Server restart won't help: all connections would be re-established.
So we have 3-4 times more TCP connections than we usually used to.

BUT we have haProxy between the server and the clients. Could haProxy be an explanation?

**Comment by lukebakken** [comment]
@belesev - please post your question to the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users). Thanks.
