### ISSUE TITLE
[khepri] Definition import terminates when the leader disappers

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/rabbitmq-server#3859]
[khepri] This issue is related to the upcoming integration with Khepri (branch: `use-khepri-metadata-store`).

I'd say that's low priority but if the Khepri leader terminates during definitions import, the import process errors out:

1. Start a 3-node cluster
2. Check where Khepri's leader is (`ra:members(metadata_store).`), for this example let's say that rabbit-1 is the leader
3. Start a long import on a different node: `rabbitmqctl -n rabbit-2 import_definitions lots_of_users.json`
4. Stop the leader (`rabbit:stop()` from the leader's shell)
5. Import fails with
```
$ rabbitmqctl -n rabbit-2 import_definitions users-50000.json
Importing definitions in JSON from a file at "users-50000.json" ...
Error:
{:shutdown, {:gen_statem, :call, [{:metadata_store, :"rabbit-1@mkuratczyk-a01"}, {:leader_call, {:command, :normal, {:"$usr", {:tx, {:standalone_fun, :"ktx__rabbit_auth_backend_internal__-with_user_in_khepri/2-fun-0-__107251876", <<70, 79, 82, 49, 0, 0, 2, 116, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 213, 0, 0, 0, 11, 75, 107, 116, 120, 95, 95, 114, ...>>, 0, ["u170", {:standalone_fun, :"ktx__rabbit_auth_backend_internal__-update_user_in_khepri/2-fun-0-__6984835", <<70, 79, 82, 49, 0, 0, 2, 184, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 198, 0, 0, 0, 11, ...>>, 0, ["u170", {:standalone_fun, :"ktx__rabbit_auth_backend_internal__-change_password_hash/3-fun-0-__82055721", <<70, 79, 82, 49, 0, 0, 2, 88, 66, 69, 65, 77, 65, 116, 85, 56, 0, ...>>, 1, [<<3, 26, 223, 125, 6, 164, 38, 50, 255, 242, 34, 135, 152, 128, ...>>, :rabbit_password_hashing_sha256]}]}]}}, :await_consensus}}}, 5000]}}
```

As I said, I think it's low priority but I'd expect the process to handle this and continue once the new leader is elected.

**Comment by dcorbacho** [comment]
I'm not sure at which point that issue was fixed, this issue has been opened for a long time, but it currently returns an appropiate error message:

```
dparracorba-a01:rabbitmq-khepri-25 dparracorbacho$ time ./sbin/rabbitmqctl -n rabbit-2 import_definitions q0-with-100k-topic-bindings.json
Importing definitions in JSON from a file at "q0-with-100k-topic-bindings.json" ...
Error:
Metadata store is unavailable. Please try again.
```

I think that asking the user to retry is an acceptable behaviour.

**Comment by mkuratczyk** [comment]
Indeed, if I follow the steps precisely, I also get a request to try again now.

I think we can ignore this since it behaves the same way on `main`/with Mnesia, but if I stop the node that the import is running against, it just hangs forever.
```
$ time rabbitmqctl -n rabbit-0 import_definitions ~/sample-configs/topic-bindings/q0-with-100k-topic-bindings.json
Importing definitions in JSON from a file at "/home/mkuratczyk/sample-configs/topic-bindings/q0-with-100k-topic-bindings.json" ...
```

And the number of bindings doesn't change.

It feels like something we should fix but I don't recall a single report of that issue, so I guess it's very unlikely in practice.
