### ISSUE TITLE
[khepri] Importing definitions is slower than simple declaration

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/rabbitmq-server#3860]
[khepri] This issue is related to the upcoming integration with Khepri (branch: use-khepri-metadata-store).

Importing definitions with Khepri seems slower than with Mnesia, even though simply declaring the objects is just as fast. I guess using a worker pool just doesn't make sense with Khepri but perhaps the problem is elsewhere. We can re-test this later with more kinds of definitions supported by Khepri but these are my results right now (on a single node):

```
# import 50k users to Khepri
$ time ./sbin/rabbitmqctl import_definitions users-50000.json
Importing definitions in JSON from a file at "users-50000.json" ...
Successfully started definition import. This process is asynchronous and can take some time.

real    2m11.143s
user    0m2.318s
sys     0m0.475s


# add 50k users directly (Khepri enabled)
> T = os:timestamp(). [rabbit_auth_backend_internal:add_user(list_to_binary(string:concat("u", integer_to_list(X))), <<"secret">>, <<"test">>) || X <- lists:seq(1,50000)]. io:format("time: ~f seconds~n", [timer:now_diff(os:timestamp(), T) / 1000000]).
...
time: 73.544202 seconds
ok
```

For comparison, results with Mnesia:
```
# import 50k users to Mnesia
$ time ./sbin/rabbitmqctl import_definitions users-50000.json
Importing definitions in JSON from a file at "users-50000.json" ...
Successfully started definition import. This process is asynchronous and can take some time.

real    1m12.773s
user    0m2.437s
sys     0m0.440s

# add 50k users directly (Khepri disabled)
> T = os:timestamp(). [rabbit_auth_backend_internal:add_user(list_to_binary(string:concat("u", integer_to_list(X))), <<"secret">>, <<"test">>) || X <- lists:seq(1,50000)]. io:format("time: ~f seconds~n", [timer:now_diff(os:timestamp(), T) / 1000000]).
...
time: 72.116451 seconds
ok
```

**Comment by mkuratczyk** [comment]
This gets even more interesting on a 3-node cluster (in my case on GKE). Import took 13m30s and the Erlangy way, 2m30s - over 5 times faster.

**Comment by mkuratczyk** [comment]
This gets better and better - results from a cluster with Mnesia:
import: 3m49s
directly from Erlang shell: 7m35s

Unless I'm missing something, Khepri is significantly slower with import, while Mnesia is significantly slower with direct declarations. Without any additional analysis, it looks like Khepri is faster but Mnesia handles concurrency better.

**Comment by dcorbacho** [comment]
I tested this with the current `khepri-queues` branch and I'm getting the same times for both mnesia and khepri. @mkuratczyk could you test it again?

Single node on my macbook:

| | Import 100k users | Declare 100k users | 
| mnesia | 0m53.915s | time: 212.256229 seconds |
| khepri | 0m49.909s | time: 226.415912 seconds |

**Comment by mkuratczyk** [comment]
Yes, this was reported a long time ago and doesn't seem to be the case anymore.
