### ISSUE TITLE
Server not useable after clean injected D status

### ISSUE THREAD

**Issue by polaris-alioth** [rabbitmq/rabbitmq-server#3910]
In our reliability test scenario, we inject D status to the main process '***bin/beam.smp -W w -MBas ageffcbf -MHas ageffcbf***', then clean the D status, the process restore to S status, but server is not useable again. Is it normal?

**Comment by michaelklishin** [comment]
@polaris-alioth please use discussions instead of issues for questions. We need more Information on what you mean by "not useable".
