### ISSUE TITLE
Add cluster-wide resource alarm status to `cluster_status` output

### ISSUE THREAD

**Issue by binarin** [rabbitmq/rabbitmq-server#392]
As `status` returns this list limited to the current node, the only way to get that information for whole cluster is `rabbitmqctl eval`. Maybe it's a good idea to always report this info in `cluster_status` output.

**Comment by hairyhum** [comment]
There are `rabbitmqctl report` which prints `status` for every node in cluster. Looks like the same thing.

**Comment by michaelklishin** [comment]
@hairyhum yes but it also prints a ton of other stuff. So this can still be useful. @dumbbell WDYT?

**Comment by Dzol** [comment]
> @hairyhum yes but it also prints a ton of other stuff. So this can still be useful.

How about printing something like this (alarms on the last line):
```
$ ./deps/rabbit/scripts/rabbitmqctl cluster_status
Cluster status of node rabbit@dizzy ...
[{nodes,[{disc,[rabbit@dizzy]}]},
 {running_nodes,[rabbit@dizzy]},
 {cluster_name,<<"rabbit@dizzy">>},
 {partitions,[]},
 {alarms, []}]
$ 
```
This commit https://github.com/rabbitmq/rabbitmq-test/commit/a9056ea475a180520c0dd2ded1fb962a4cecdab1#diff-991a3fd99f60cf5a5188bf184e9422b1R494 tests things as they currently are.

Presumably the output should be similar to the `alarms` tuple in the `status` output?

**Comment by Dzol** [comment]
This is what the output looks like (following [this](https://github.com/rabbitmq/rabbitmq-server/commit/ecaac0c0c66529dde8d2060a2e6d9862f15eea08#diff-0791814e0c4904b21e083a7378194669R366) change):

```
Cluster status of node a@dizzy ...
[{nodes,[{disc,[a@dizzy,b@dizzy]}]},
 {running_nodes,[b@dizzy,a@dizzy]},
 {cluster_name,<<"a@dizzy">>},
 {partitions,[]},
 {alarms,[{b@dizzy,[]},{a@dizzy,[]}]}]
```
The test [here](https://github.com/rabbitmq/rabbitmq-test/commit/cc7b600471ffe517e5bb2d73abe7b3e70847524f#diff-991a3fd99f60cf5a5188bf184e9422b1R494) could be improved. E.g.:

* test that the `alarms` tuple does in fact contain information for each node
* test that if an alarm is raise it is printed

@michaelklishin: please advise before I make a pull request.

**Comment by michaelklishin** [comment]
@Dzol the proposed improvements sound good to me.

**Comment by Dzol** [comment]
The above pull requests should close this issue __with__ the proposed improvements.
