### ISSUE TITLE
[CQv2] Perfromance degradation to be investigated

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/rabbitmq-server#3929]
This is an issue related to an unreleased feature (branch: https://github.com/rabbitmq/rabbitmq-server/tree/modern-classic-queue-index).

@lhoguin we discussed this already. I'm sharing here so we don't forget to look into this in January.

The degradation seems to be triggered when there are many publishers and `x-max-length` is set but perhaps other factors are important as well.

Screenshot below shows 5 tests with `x-max-length=1000000` and the next 5 tests with exactly the same cluster/workload, except without `x-max-length` set at all. 
<img width="1282" alt="Screenshot 2021-12-22 at 08 08 38" src="https://user-images.githubusercontent.com/9566114/147051643-0370bbab-93e7-48be-b4d4-0f2a44eff0d8.png">

The correlation with `x-max-length` being set is hard to ignore. It seems like this triggers the issue or at least makes it occur sooner.

This test was performed with the following perf-test flags:
```
        - -x
        - "5000"
        - -y
        - "0"
        - -r
        - "1"
        - -jb
        - "1000"
        - -p
        - -u
        - cq-v2-lazy-mirrored
        - --queue-args
        - "x-max-length=1000000"
        - --auto-delete
        - "false"
        - -f
        - persistent
        - -c
        - "1"
        - --heartbeat-sender-threads
        - "1"
        - --use-millis
```

**Comment by lhoguin** [comment]
Interesting that one test does not result in any problems.

**Comment by mkuratczyk** [comment]
There have been many improvements to CQv2 since this issue was reported. We can no longer reproduce the problem.
