### ISSUE TITLE
Oauth plugin does not require username in the token

### ISSUE THREAD

**Issue by luos** [rabbitmq/rabbitmq-server#3931]
Hi,

This concerns the Oauth Plugin, which uses the token to authenticate a user. 

We've noticed that if the token does not have a username then the username provided by the client application will be used. You can provide a token where the `client_id` property is missing, then RabbitMQ will pick up the username from the `username` field.

https://github.com/rabbitmq/rabbitmq-server/blob/ba238053c20c19b2cf7d7ec26d235ecfc2c17f0a/deps/rabbitmq_auth_backend_oauth2/src/rabbit_auth_backend_oauth2.erl#L281-L297

We are thinking this has some low chance of being used as injecting some data into RabbitMQ, though it is easily avoided by just adding a username into the token, so it is essentially controlled by the token issuer (if they rely on this feature).

Removing this option would be a breaking change for applications who rely on tokens without a `client_id` or similar property. Also, I think originally this was implemented so it is visible "who" is trying to log in in the log messages.  

Usually the tokens should have `client_id` or `sub` in them and in that case RabbitMQ always picks those.

We think it may be a good idea to remove this functionality or default to the `undefined` value as other branches in the code do. What do you think?

**Comment by michaelklishin** [comment]
We don't know how many JWT token users do not specify the username or why. In any case, if your token can authenticate but carries an unusual username, how much harm can this do? XSS-style attacks must be the primary motivation and those should be handled anyway.

I don't think it's worth the risk. If an attacker has a way of crafting JWT tokens that authenticate successfully, they can still inject a bogus `client_id` into them, right?

**Comment by luos** [comment]
Yep, if someone can craft tokens then it can do anything. 

This issue concerns when someone has a valid token but the token does not have `client_id` in it, in this case can login under "any" username.

Yes, mostly the issue can be with XSS or maybe misleading in the logs, though as the user already has a valid token, not sure it can be a big issue.
