### ISSUE TITLE
Disk space analysis on Windows fails if locale has different thousands-separator

### ISSUE THREAD

**Issue by Entropy0** [rabbitmq/rabbitmq-server#3972]
(Regarding the contributing guideline: Yes, I am quite certain that I have identified a bug, complete with a link to the specific code in question; the only reason I am not providing a fix together with the bug report is that I have zero knowledge of Erlang.)

---

When running rabbit on an Windows OS configured with a locale that has different number separators than English (most commonly "1.000.000,00" in most of continental Europe instead of "1,000,000.00" in English), free disk space analysis will only see the first digits of the actual amount of free disk space.
That's because the `win32_get_disk_free_fsutil` function [here](https://github.com/rabbitmq/rabbitmq-server/blob/dcb8e0f877566c763bce5c34c478431dfba72821/deps/rabbit/src/rabbit_disk_monitor.erl#L281) calls `fsutil.exe`, which formats its output according to the current locale and expects it to return a number separated by commas.

So in the example in the comment of the function, it would see "Total quota free bytes  :   812.733.878.272" and throw up a warning because it thinks there are only 812 bytes available.

If you want to hold on to parsing fsutil output, I would suggest splitting the string on the open parenthesis, taking the left hand side and discarding anything that isn't a digit instead of trying to add special handling for every possible thousands-separator (there's also localse that use ` ` and even `'`!). Although it would probably make more sense to use a more robust approach alltogether.

**Comment by lhoguin** [comment]
We are fixing it here by no longer using `fsutil`: https://github.com/rabbitmq/rabbitmq-server/pull/3970

Thanks for the report!

**Comment by lukebakken** [comment]
> Although it would probably make more sense to use a more robust approach alltogether.

Yep, we're just going to use Powershell.
