### ISSUE TITLE
Add support for priority queues for quorum queues before RabbitMQ 4.0

### ISSUE THREAD

**Issue by jefftrimm** [rabbitmq/rabbitmq-server#3973]
With the removal of Classic Queue mirroring, there remains no queue types that support different message priorities.  This is a critical feature for many users.  

This is to request support for message priority support for quorum queues, and to do so before classic mirrored queues are deprecated in RabbitMQ 4.0 to allow for a migration process for existing priority queue users.

https://www.rabbitmq.com/priority.html

**Comment by michaelklishin** [comment]
Quorum queues were never meant to be a feature-for-feature, 100% equivalent of classic queues. The whole idea behind having queue types is that they optimize for different things. Quorum queues do not optimize for priority access, and chances are, never will. We won't repeat the same mistake of putting every conceivable feature into one queue type again.

**Comment by michaelklishin** [comment]
Non-mirrored priority queues will remain even after 4.0. It's perfectly reasonable to use a non-replicated queue type for some things, and a quorum queue or stream for other things. Supporting every possible combination of features is not a priority and likely will not be worth the engineering effort. We have ample evidence that most users do not use priority queues, and when they do, it is only to avoid messages of one type from building up behind others, which can be achieved by using a queue or group of queues per message type.

**Comment by jefftrimm** [comment]
Removing support for highly available priority queues is a pretty major deprecation of functionality that will likely impact some important existing integrations out in the wild dependent on this?  Message priorities are pretty much table stakes for any modern message broker.

If it's decided to not support message priority in quorum queues, can it at least be considered to retain the ability of having mirrored queues continue to support this functionality?

**Comment by michaelklishin** [comment]
@jefftrimm classic queue mirroring is a *broken and unfixable design*. Willingly using it means you don't value your data that much, which means you should be able to just roll with non-mirrored priority queues which are not going to be removed.

While we cannot measure it, our team's impression of how widely used priority queues are does not match yours. Like I said, very often priority queues are used to untangle two or more message types to avoid head-of-the-queue blocking problems but not any prioritisation beyond that. This can be easily achieved by using multiple queues.

This is discussion material.
