### ISSUE TITLE
Add rabbitmqctl command for node health check

### ISSUE THREAD

**Issue by binarin** [rabbitmq/rabbitmq-server#398]
In Vancouver Michael has mentioned one-shot command for performing health-check on rabbit node.

I don't know what was the idea then, but here is the list of checks from OCF script:
- BEAM is running, 'kernel' and 'rabbit' OTP applications are running.
- Checks (with timeout) that `rabbitmqctl list_channels` works and returns something.
- Checks whether memory alarm is set for this node.
- Checks (with timeout) if queues can be listed with `rabbitmqctl list_queues`.

So the new command should collect at least the same date, but in a less kludgy way. And maybe extended with additional checks, if somebody would come up with them )

**Comment by michaelklishin** [comment]
@binarin that sound OK but should perhaps be combined with what the aliveness check HTTP API resource does: opens a connection, declares a queue, publishes one messages and consumes it with `basic.get`.

This would be a decent health check for a single node.

**Comment by jiajunsu** [comment]
I think it's better adding a rabbitmqctl cli instead the management aliveness check.

If server's health-check depend on management plugin, when management got crash for an internal error, we could not know whether the server is fine.

**Comment by michaelklishin** [comment]
I'm growing convinced that there should be two improvements made:

 * Single node health check improvements plus a `rabbitmqctl` command
 * Cluster state health check (the specifics are not yet clear), which should be a separate issue

**Comment by dcorbacho** [comment]
I implemented a first version of the rabbitmqctl command in: https://github.com/rabbitmq/rabbitmq-server/tree/rabbitmq-server-398.

However, there is an issue if we want to include what the aliveness check HTTP API does, as it requires the amqp_client application. Neither rabbit nor rabbit_common depend on it, and I don't think we want to add that dependency.

@michaelklishin what are your thoughts now?

**Comment by michaelklishin** [comment]
I'd rather avoid the dependency. Declaring a topology and publishing messages using the internal RabbitMQ API is easy, I am less sure about consuming messages.

@binarin's list of features for this check does not involve publishing messages, and many people don't find that particular check important (at least the way it works today). So we can even leave publishing out if it proves to be difficult without a client library.

**Comment by binarin** [comment]
Yes, I no longer think that just publishing something is a useful test. Especially without taking into account a lot of site-specific thing, like whether clustering or HA is used.

And problems are usually more subtle and involve existing queues/channels.

**Comment by dcorbacho** [comment]
This change is made of 3 PRs:
https://github.com/rabbitmq/rabbitmq-management/pull/139
https://github.com/rabbitmq/rabbitmq-common/pull/60
https://github.com/rabbitmq/rabbitmq-server/pull/652

I moved `rabbit_cli:call_rpc` to the `rabbit_common` application so it can be used by the common health checks code. If that is fine, I can squash all rabbitmq_server commits into one to have a cleaner history.

**Comment by michaelklishin** [comment]
#44 and friends look good. We'll pull them after `3.6.1` is released.

**Comment by michaelklishin** [comment]
#652 and rabbitmq/rabbitmq-common#60 are merged. rabbitmq/rabbitmq-management#139 doesn't report failure details in a human-readable way and needs more work.

**Comment by dcorbacho** [comment]
Formatting done in https://github.com/rabbitmq/rabbitmq-management/commit/0715d48adb6ad41ba13b6396f654cbd2274e408c

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-management/pull/139 was merged, closing.
