### ISSUE TITLE
Backport rabbitmq/rabbitmq-server#3421 in 3.8.x

### ISSUE THREAD

**Issue by sherifkayad** [rabbitmq/rabbitmq-server#3982]
This issue here is to report that we would like to have #3421 backported to RabbitMQ versions 3.**8**.x. 

The PR was flagged for backporting into 3.8.x, however, this didn't happen. It seems like the original PR was only backported to RabbitMQ versions 3.**9**.x

**Comment by michaelklishin** [comment]
We do not intend to backport everything to `3.8`. In fact, we want to only backport bug fixes there. We'll see if this unintentionally slipped through the cracks or was never meant to be backported but in general, we won't backport every single change that isn't breaking all the way to 3.8.

**Comment by michaelklishin** [comment]
Several members of our team voted for not backporting to `v3.8.x` as it is a new feature and that branch is very mature by now (pushing its 30th patch release).
