### ISSUE TITLE
"Absurdly large distribution output data buffer" strikes again.

### ISSUE THREAD

**Issue by lemenkov** [rabbitmq/rabbitmq-server#399]
I hate to say that but it seems that the issues 25965 and 25952 were not addressed fully (or there is another source of the issue). We've got this message again.

A little bit of explanation. Our rabbitmq-powered cluster misbehaves. One of the message queues grows due to malfunction somewhere in a reader/writer logic, and once it grows big enough (tens of gigabytes of memory) Erlang VM dies throwing this message.

Yes, we should fix how readers and writers are talking first, so it's definitely a low-priority from your point of view, but still - I believe that rabbitmq shouldn't crash VM no matter what.

We don't have any additional information to share at this moment. We'll try to find more soon.

**Comment by michaelklishin** [comment]
If you don't have any information to share, there is nothing for us to do. Please start a mailing list conversation instead, we use issues for specific actionable items.
