### ISSUE TITLE
Management plugin of RabbitMQ Server error

### ISSUE THREAD

**Issue by jsmfr77** [rabbitmq/rabbitmq-server#400]
I'm looking for some help on the management plugin of RabbitMQ Server.
I have fallowed the installation procedure on Winows 10 and when I login with guest I have a "Got response code 500 with body {"error":"Internal Server Error","reason":"{error,{exit,{ucs,{bad_utf8_character_code}..." 
The problem is from the "xmerl_ucs.erl" file line 186 and "lists.erl" line 1262.
I am stuck with this!
If somebody could help me. Maybe the answer is simple...

![screen shot 11-02-15 at 11 55 am_resultat](https://cloud.githubusercontent.com/assets/15609459/10882247/5d6c8430-8169-11e5-8b2a-7481ee3bc9b9.jpg)

**Comment by michaelklishin** [comment]
Please ask questions on the mailing list.

**Comment by michaelklishin** [comment]
For example, [this thread](https://groups.google.com/forum/#!searchin/rabbitmq-users/bad_utf8_character_code%7Csort:relevance/rabbitmq-users/IhxqihCO3cc/4HXLu_MKJUIJ) explains how to deal with entities that use non-UTF8 characters in them.
