### ISSUE TITLE
rabbitmqctl.bat status badarith

### ISSUE THREAD

**Issue by utweric** [rabbitmq/rabbitmq-server#4001]
Hi,
On a fresh install on windows 2019 server, when launching status command i have 
```
Status of node rabbit@My-Machine ...
Error:
:badarith
```
RabbitMQ 3.9.12/Erlang 24.2

**Comment by lukebakken** [comment]
Fixed by this PR - https://github.com/rabbitmq/rabbitmq-server/pull/3970

This will be fixed in 3.9.13, which should be released this week.
