### ISSUE TITLE
 Free disk space monitor encountered an error

### ISSUE THREAD

**Issue by utweric** [rabbitmq/rabbitmq-server#4002]
Hi,
On a fresh install on Windows 2019 Server, I have these kind of entries in rabbit log file :
`Free disk space monitor encountered an error (e.g. failed to parse output from OS tools): {{'EXIT', {{case_clause,"Nombr"}, [{rabbit_disk_monitor,win32_get_disk_free_fsutil,1,[{file,"rabbit_disk_monitor.erl"},{line,295}]},{rabbit_disk_monitor,get_disk_free,2,[{file, "rabbit_disk_monitor.erl"},{line,255}]},{rabbit_disk_monitor,enable,1,[{file,"rabbit_disk_monitor.erl"},{line,383}]},{rabbit_disk_monitor,handle_info,2,[{file,"rabbit_disk_monitor.erl"},{line,164}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,695}]},{gen_server, handle_msg,6,[{file,"gen_server.erl"},{line,771}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}},8588865536}, retries left: 5`
Any idea to correct this ?

**Comment by michaelklishin** [comment]
This was addressed in #3974.
