### ISSUE TITLE
Diskspace incorrectly shows as 0 and blocks new messages from comming in

### ISSUE THREAD

**Issue by dustin-auby** [rabbitmq/rabbitmq-server#4003]
Hi, i have just installed rabbit server on windows and it cant seem to detect the drive size properly. it is showing 0gb free in the status output and also is showing a warning in the web interface. All new messages coming into the queue are blocked because of this error.

Here is the output from the "rabbitmqctl status" command
![disk space output](https://user-images.githubusercontent.com/38311779/149837982-7420bc62-d3c3-46a5-8c1f-e460cb58482c.PNG)

This is the free space on the drive that the server is installed on
![free space](https://user-images.githubusercontent.com/38311779/149838005-fed135e7-cc08-41c2-b934-d402684f06c0.PNG)

this it the warning in the web interface
![space error](https://user-images.githubusercontent.com/38311779/149838016-b1fd87ba-0160-4c75-8c32-0a6da003480c.PNG)

When publishing a new message i get the error "low on disk".

Any help with this would be greatly appreciated. Thanks in advance

**Comment by lukebakken** [comment]
Fixed by this PR - https://github.com/rabbitmq/rabbitmq-server/pull/3970

You don't say which version of RabbitMQ you're using but I'm guessing it's 3.9.12. This will be fixed in 3.9.13.

Are you using a language other than English?

**Comment by dustin-auby** [comment]
> Fixed by this PR - #3970
> 
> You don't say which version of RabbitMQ you're using but I'm guessing it's 3.9.12. This will be fixed in 3.9.13.
> 
> Are you using a language other than English?

Hi yes the version is 3.9.12. i am only using english
