### ISSUE TITLE
Investigate if we can provide more context when Erlang distribution fails

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#401]
See [this thread](https://groups.google.com/forum/#!topic/rabbitmq-users/cslVlwhz2uA). Some are very unhappy about the error message we have. I'm not sure how realistic it is for us to provide more info but it'd be great to try (even if the outcome would be "bug the OTP team about it or contribute upstream").

**Comment by Ayanda-D** [comment]
Replicating [this thread](https://groups.google.com/forum/#!topic/rabbitmq-users/cslVlwhz2uA) is pretty straight forward, however providing error messges of more context when erlang distribution fails would involve making [diagnose_connect/2](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_nodes.erl#L151) provide more information than just [ok](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_nodes.erl#L157) when the [TCP connection succeeds but Erlang distribution fails](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_nodes.erl#L156). Currently exploring some possible operations to carry out prior to [closing the socket](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_nodes.erl#L156), which can help provide a more informative return than just [ok](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_nodes.erl#L157).

**Comment by michaelklishin** [comment]
Another point of improvement. When there's a cookie mismatch, RabbitMQ will log

```
=ERROR REPORT==== 25-Jan-2016::16:08:25 ===
** Connection attempt from disallowed node 'rabbitmq-cli-7344@ip-172-31-XY-XYZ' **
```

We should make it clear that this is an authentication failure and the cookie must match. Also, nodes do not reload cookies once they are change.

**Comment by dcorbacho** [comment]
I've been investigating what [`net_adm:ping/1'](https://github.com/erlang/otp/blob/maint/lib/kernel/src/net_adm.erl#L61) does, and it's simply `gen:call({net_kernel, Node}, '$gen_call', {is_auth, node()}, infinity)`. The call itself will always return 'yes' if it reached the other node, but the trick is on how the connection is established. [`gen:call/4`](https://github.com/erlang/otp/blob/maint/lib/stdlib/src/gen.erl#L154) users `erlang:monitor/2` and `erlang:send/3`. These are NIFs, so I didn't follow them. But, somehow it triggers [`inet_tcp_dist:setup/5`](https://github.com/erlang/otp/blob/maint/lib/kernel/src/inet_tcp_dist.erl#L268) and the difference there between a connection that succeeds (but might fail on the handshake before of the cookies) and one that fails to connect is the call to `erl_epmd:port_please/2`.

Here we have a failed attempt to reach the remote node (it is down):
```
<0.1353.0>) call erl_epmd:port_please("rabbit2",{127,0,0,1})
(<0.1353.0>) call erl_epmd:port_please("rabbit2",{127,0,0,1},infinity)
(<0.1353.0>) returned from erl_epmd:port_please/3 -> noport
```
And here is succeeds, but will later fail on the handshake (wrong cookie):
```
(<0.1362.0>) call erl_epmd:port_please("rabbit2",{127,0,0,1})
(<0.1362.0>) call erl_epmd:port_please("rabbit2",{127,0,0,1},infinity)
(<0.1362.0>) returned from erl_epmd:port_please/3 -> {port,25673,5}
(<0.1362.0>) returned from erl_epmd:port_please/2 -> {port,25673,5}
```
I'll check if it is viable to use `erl_epmd:port_please/2` as part of [`diagnose_connect/2`](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_nodes.erl#L151)

**Comment by dcorbacho** [comment]
I've been going around it and there is nothing we can do from the Rabbit side. I'll work on a contribution to increase logs in OTP.

**Comment by dcorbacho** [comment]
There is one way to improve the rabbit logs with the potential OTP patch.

* Part 1: Add error reasons to the logs as done for TLS here: https://github.com/legoscia/otp/commit/5f49de9d6e8ae247b10e37c085bf1d1dc9945ac8 These detailed logs can be generated by setting the verbose level in [net_kernel:verbose/1](https://github.com/erlang/otp/blob/maint/lib/kernel/src/net_kernel.erl#L177)
* Part 2: Set the logs to verbose and install an error_logger handler in [rabbit_nodes:diagnostics/1](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_nodes.erl#L64). The error_handler will select the relevant net_kernel logs that could be then printed with the output of rabbitmqctl. These logs could be parsed and pretty-printed for the final user, or refer to Rabbit documentation for details.

See it working below, `{shutdown,{recv_challenge_failed,no_node,"rabbit@t-srv-rabbit01"}}` is one of the possible new logs to notify that the hostname doesn't match.
```
isis:scripts dianacorbacho$ PATH=/Users/dianacorbacho/tools/otp_src_18.2.1/bin:$PATH  ./rabbitmqctl join_cluster 'rabbit@rabbit1'
Clustering node rabbit@isis with rabbit@rabbit1 ...
Error: unable to connect to nodes [rabbit@rabbit1]: nodedown
{shutdown,{recv_challenge_failed,no_node,"rabbit@t-srv-rabbit01"}}

DIAGNOSTICS
===========

attempted to contact: [rabbit@rabbit1]

rabbit@rabbit1:
  * connected to epmd (port 4369) on rabbit1
  * epmd reports node 'rabbit' running on port 25672
  * TCP connection succeeded but Erlang distribution failed
  * suggestion: hostname mismatch?
  * suggestion: is the cookie set correctly?
  * suggestion: is the Erlang distribution using TLS?

current node details:
- node name: 'rabbitmq-cli-04@isis'
- home dir: /Users/dianacorbacho
- cookie hash: 9gfN63OW21CerY4A3v1jEQ==
```

@michaelklishin what do you think of this?

It would require some periodic updates with new Erlang releases (and would not work with old ones), but I don't think it is likely to change often and the patch might easily be accepted as the TLS one.

**Comment by dcorbacho** [comment]
I still have to do work on the TLS information, but here is how it could look like the previous proposal could look like:
https://github.com/rabbitmq/rabbitmq-common/tree/rabbitmq-server-401
https://github.com/dcorbacho/otp/tree/dist_util_logs

**Comment by dcorbacho** [comment]
Erlang/OTP PR in https://github.com/erlang/otp/pull/980

**Comment by dcorbacho** [comment]
The OTP PR is merged into master, it should be available on the next Erlang release

**Comment by michaelklishin** [comment]
This will only have an effect on Erlang/OTP 18.4 but exactly the kind of improvement I had in mind. Thank you, @dcorbacho.

**Comment by dcorbacho** [comment]
I thought it would be the next minor release, but it is in fact for the next major release Erlang/OTP 19.
master branch -> major release
maint branch -> minor release

**Comment by michaelklishin** [comment]
OK, Erlang/OTP 19 then.
