### ISSUE TITLE
vhost in tag queries not work

### ISSUE THREAD

**Issue by spham** [rabbitmq/rabbitmq-server#4018]
Hi
I have created 2 groups 
host_administrator and host_monitoring

and it's with tihs pattern, 
```
"CN=${vhost}_administrator,OU=RabbitMQ,OU=SVC,OU=France,DC=toto,DC=com"
```
and it return false .

my rabbitmq 3.9.5 on centos 7.

```
[{rabbit,
  [{
     auth_backends, [rabbit_auth_backend_ldap, rabbit_auth_backend_internal]
   }
]},
{rabbitmq_auth_backend_ldap,[
    {tag_queries, [
           {administrator,  {in_group,"CN=${vhost}_administrator,OU=RabbitMQ,OU=SVC,OU=France,DC=toto,DC=com"}},
           {monitoring,     {in_group,"CN=${vhost}_monitoring,OU=RabbitMQ,OU=SVC,OU=France,DC=toto,DC=com"}}
    ]},
    {vhost_access_query, {in_group, "CN=${vhost}}},OU=RabbitMQ,OU=SVC,OU=France,DC=toto,DC=com"}}
  ]}].
```

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
