### ISSUE TITLE
"headers" exchange crashes rabbit, when rabbit has high connection counts

### ISSUE THREAD

**Issue by SStorm** [rabbitmq/rabbitmq-server#403]
Hi guys,
 I've checked bug list extensively but couldn't find anything relevant to this, so here you go: 

RabbitMQ version: 3.4.4
Box size: AWS m3.medium (3.8 GB RAM, 1 CPU core)
Enabled plugins:
```
root@ip-10-0-160-94:/var/log/rabbitmq# rabbitmq-plugins list
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status:   * = running on rabbit@localhost
 |/
[e*] amqp_client                              3.4.4
[  ] brod                                     1.4-rmq0.0.0-git9e9e870
[  ] cowboy                                   0.5.0-rmq3.4.4-git4b93c2d
[  ] erlzk                                    0.4.0-rmq0.0.0-gite6495a1
[E*] lager                                    2.0.0-rmq0.0.0-git9719370
[e*] mochiweb                                 2.7.0-rmq3.4.4-git680dba8
[  ] rabbitmq_amqp1_0                         3.4.4
[  ] rabbitmq_auth_backend_ldap               3.4.4
[E*] rabbitmq_auth_mechanism_ssl              3.4.4
[  ] rabbitmq_consistent_hash_exchange        3.4.4
[  ] rabbitmq_federation                      3.4.4
[  ] rabbitmq_federation_management           3.4.4
[E*] rabbitmq_management                      3.4.4
[e*] rabbitmq_management_agent                3.4.4
[  ] rabbitmq_management_visualiser           3.4.4
[  ] rabbitmq_mqtt                            3.4.4
[E*] rabbitmq_shovel                          3.4.4
[  ] rabbitmq_shovel_management               3.4.4
[  ] rabbitmq_stomp                           3.4.4
[  ] rabbitmq_test                            3.4.4
[  ] rabbitmq_tracing                         3.4.4
[e*] rabbitmq_web_dispatch                    3.4.4
[  ] rabbitmq_web_stomp                       3.4.4
[  ] rabbitmq_web_stomp_examples              3.4.4
[  ] sockjs                                   0.3.4-rmq3.4.4-git3132eb9
[e*] webmachine                               1.10.3-rmq3.4.4-gite9359c7
```

Scenario: 
1. Create a "direct" exchange (A) where these messages are routed to
2. Connect 1500+ clients, get them all to produce messages to (A) with same routing key (tested with 200 msg/s TOTAL, but less might be enough)
3. Create a separate "headers" (B) exchange
4. Bind (A) to (B) with same routing key

Expected:
Messages get routed to (B) successfully

Actual:
RabbitMQ becomes unresponsive almost immediately. 

Reproducibility: 100%

Message counts don't seem to have an impact here, only connection counts. Anything less than 1k connections and it seems to work fine, only above this does it tip over. 

Happy to provide additional info.

**Comment by michaelklishin** [comment]
3.4.x is no longer supported. Please try 3.5.6.

Headers exchange is by far the least efficient exchange type. This could also be #227.

However, if a certain connection count triggers the issue, you may want to look into the logs and see if you are running into alarms or similar. See [Networking](http://www.rabbitmq.com/networking.html) and [Production checklist](http://www.rabbitmq.com/production-checklist.html) for more info.

**Comment by venikkin** [comment]
Hi michaelklishin, 

I can reproduce this issue on RabbitMQ 3.5.6, except step 2) requires 5000+ connections to make RabbitMQ unresponsive. 

CPU usage becomes 100% and memory usage rises almost double after step 4)

Can we re-open this issue please?

**Comment by michaelklishin** [comment]
@venikkin sorry but #619 is no different: you use an outdated version, provide no logs, no code samples, and there is simply no evidence that it is an issue with headers exchanges. We keep issues to specific, reasonably well defined cases that are still true with the most recent release.
