### ISSUE TITLE
User authenticated successfully but then blocked

### ISSUE THREAD

**Issue by valentyn-bulakh** [rabbitmq/rabbitmq-server#4039]
Can someone help to troubleshoot problem with RabbitMQ,
I have strange problem and can't find how to fix it?

I see in rabbit logs this message:
"2022-01-25 11:16:00.700868+00:00 [info] <0.11605.3> Supervisor {<0.11605.3>,rabbit_channel_sup}: child channel started (<0.11609.3>): {rabbit_channel,start_link,[1,<0.11546.3>,<0.11606.3>,<0.11546.3>,<<"10.0.0.49:57410 -> 10.142.0.12:5672">>,rabbit_framing_amqp_0_9_1,{user,<<"k8s-prod">>,[],[{rabbit_auth_backend_internal,none}]},<<"/">>,[{<<"publisher_confirms">>,bool,true},{<<"exchange_exchange_bindings">>,bool,true},{<<"basic.nack">>,bool,true},{<<"consumer_cancel_notify">>,bool,true},{<<"connection.blocked">>,bool,true},{<<"authentication_failure_close">>,bool,true}],<0.11547.3>,<0.11607.3>]}"

but before this message I get "User 'k8s-prod' authenticated successfully by backend rabbit_auth_backend_internal"

confused why it's blocked then?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.
