### ISSUE TITLE
User tags should be a list in management API documentation

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-server#4050]
![image](https://user-images.githubusercontent.com/514737/151391393-93ec306d-c749-44bc-834c-aa8027366574.png)

should be

```json
"tags": [
  "administrator"
],
```

References https://github.com/rabbitmq/rabbitmq-server/issues/2667.

**Comment by rishidyno** [comment]
Hi, I would like to work on this issue. Could you please assign and guide me to work on this issue?

**Comment by mkuratczyk** [comment]
@rishidyno I believe this is a docs-only issue at this point. You're welcome to make the changes to https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_management/priv/www/api/index.html (PR to the `live` branch).

Functionality seems to be ok:
```
> rabbitmqctl export_definitions - | jq .users
[
  {
    "hashing_algorithm": "rabbit_password_hashing_sha256",
    "limits": {},
    "name": "guest",
    "password_hash": "R6E9qfPEJdFukXXnPVSLgHbfXm7dNsszOC0GBqQ1C1ivOz8L",
    "tags": [
      "monitoring",
      "guest"
    ]
  }
]
```

**Comment by michaelklishin** [comment]
Addressed in https://github.com/rabbitmq/rabbitmq-server/pull/10246.
