### ISSUE TITLE
Inaccurate host name recorded by rabbit until first reboot

### ISSUE THREAD

**Issue by ldelossa** [rabbitmq/rabbitmq-server#406]
Hey guys,

I'm on centos7.1.1503

I install rabbitmq from the RPM files via yum. Everything starts and is fine, but when I go to use the rabbitmqctl tools, it looks for rabbit@localhost and not the correct host name. Reboot fixes problem. Specifying -n {hostname} fixes the issue also.

Would be nice to get around this. Also I set my hostname using the hostnamectl command.

**Comment by michaelklishin** [comment]
Per your own words the issue is with OS configuration and has nothing to do with RabbitMQ. Please use rabbitmq-users for questions.

**Comment by michaelklishin** [comment]
Plus [node name can be overridden](http://www.rabbitmq.com/configure.html#define-environment-variables) using `RABBITMQ_NODENAME`.
