### ISSUE TITLE
I enabled rabbitmq mqtt plugin but can not connect to it?

### ISSUE THREAD

**Issue by w3hacker** [rabbitmq/rabbitmq-server#409]
When I use mosquitto_sub to connect to it.It gives me
Connection Refused: not authorised

How can I change the mqtt plugin's configuration.

**Comment by michaelklishin** [comment]
Please post questions to `rabbitmq-users`. Most likely reason is that you try to connect from a remote host with [default credentials](http://www.rabbitmq.com/access-control.html), which is not allowed by default.
