### ISSUE TITLE
Monitor stream local member in stream queue

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-server#4133]
The stream queue module does not monitor the local member of its consumers, so if it goes away for some reasons, the consumer will hang.

This can happen if the node a stream is on is restarted: all the stream member process are restarted, so any local state is wiped out. This means basic consumers wait for (Erlang) messages from dead processes, and they won't dispatch any messages to client, even if the stream see new messages after the election of a new leader.

**Comment by acogoluegnes** [comment]
Note consumer cancel is not sent if the queue is deleted. This should be fixed as well.

**Comment by acogoluegnes** [comment]
Follow-up issue for basic.cancel notification: #4192.

**Comment by devkits** [comment]
Hi, 

Is there a way to determine release milestone(s) where this fix may end up in, e.g. 3.9.14, 3.10.X, etc? 

Thanks.

**Comment by acogoluegnes** [comment]
The fix will go into 3.9.x and 3.10.x. We're currently working on it.
