### ISSUE TITLE
Error running Consul health check due to Consul API update

### ISSUE THREAD

**Issue by maestroes** [rabbitmq/rabbitmq-server#4149]
### Problem description
Due to API update in Consul 1.11 the HTTP response code changed from 500 to 404 when an attempt is made to de-register or update non-existent check ID: https://github.com/hashicorp/consul/pull/11950.

This causes an issue on node restart: if the node starts longer than cluster_formation.consul.deregister_after, subsequent attempts to re-register fail with `Error running Consul health check: "404"` error.

### Proposal
It seems like 404 HTTP response code should be handled the same way as 500 in rabbit_peer_discovery_consul `send_health_check_pass()` with logging a warning and calling `maybe_re_register()`: https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbitmq_peer_discovery_consul/src/rabbit_peer_discovery_consul.erl#L501.

### Environment
RabbitMQ 3.8.22
Erlang 23.3.4.6

rabbitmq_peer_discovery_consul 3.8.22
rabbitmq_shovel 3.8.22
rabbitmq_shovel_management 3.8.22
rabbitmq_stomp 3.8.22

cluster_formation.consul.svc_ttl = 30
cluster_formation.consul.deregister_after = 60

node start time ~ 2 min

**Comment by michaelklishin** [comment]
Agreed. Thanks for reporting this change in Consul. Our team never really understood why it responded with a `500` in that case.
