### ISSUE TITLE
Quorum queues backup

### ISSUE THREAD

**Issue by Alexanator** [rabbitmq/rabbitmq-server#4159]
### Discussed in https://github.com/rabbitmq/rabbitmq-server/discussions/4158

<div type='discussions-op-text'>

<sup>Originally posted by **Alexanator** February 16, 2022</sup>
Hi! Got question about backuping messages from quorum queues.
Official documentation [says](https://www.rabbitmq.com/backup.html#manual-messages-backup) that in case of using mirrored queues It needs to stop entire cluster before backup.
But what about quorum queues? Can't find any information about it. Do I need stop entire cluster or is it enough to stop and start nodes one by one?
Please help if you have any experience. </div>

**Comment by mkuratczyk** [comment]
Let's stick to the discussion.
