### ISSUE TITLE
Ctl calling process can get stuck

### ISSUE THREAD

**Issue by essen** [rabbitmq/rabbitmq-server#417]
This ticket describes the issue the tests highlight (test suite gets stuck indefinitely). I do not know if this issue affects more than the tests themselves, although the issue definitely comes from the server side of things.

The issue occurs when there is an error during a command (user doesn't exist, or arguments are incorrect, for example) AND the command in question uses the stream method to obtain the results (the node sending the result as a series of messages rather than just returning it and letting rpc:call handle it).

The following tests fail because the user doesn't exist:

* list_user_permissions: https://github.com/rabbitmq/rabbitmq-test/blob/8b7fda416329cf51226e8b4ae5a3e94c5f1837bf/test/src/rabbit_tests.erl#L1009
* list_permissions: https://github.com/rabbitmq/rabbitmq-test/blob/8b7fda416329cf51226e8b4ae5a3e94c5f1837bf/test/src/rabbit_tests.erl#L1009

The following tests fail because of a bad argument:

* list_queues: https://github.com/rabbitmq/rabbitmq-test/blob/8b7fda416329cf51226e8b4ae5a3e94c5f1837bf/test/src/rabbit_tests.erl#L1223
* list_exchanges: https://github.com/rabbitmq/rabbitmq-test/blob/8b7fda416329cf51226e8b4ae5a3e94c5f1837bf/test/src/rabbit_tests.erl#L1232
* list_bindings: https://github.com/rabbitmq/rabbitmq-test/blob/8b7fda416329cf51226e8b4ae5a3e94c5f1837bf/test/src/rabbit_tests.erl#L1235
* list_connections: https://github.com/rabbitmq/rabbitmq-test/blob/8b7fda416329cf51226e8b4ae5a3e94c5f1837bf/test/src/rabbit_tests.erl#L1250
* list_channels: https://github.com/rabbitmq/rabbitmq-test/blob/8b7fda416329cf51226e8b4ae5a3e94c5f1837bf/test/src/rabbit_tests.erl#L1258

The reason they fail is because the info_action function has a test for an invalid argument, demonstrating this issue: https://github.com/rabbitmq/rabbitmq-test/blob/8b7fda416329cf51226e8b4ae5a3e94c5f1837bf/test/src/rabbit_tests.erl#L1882

Of note, @videlalvaro added a function info_action_t (with a timeout) that doesn't have the offending line, spot the differences: https://github.com/rabbitmq/rabbitmq-test/blob/master/test/src/rabbit_tests.erl#L1876 Adding this line also shows this issue.

The reason these tests fail is more interesting.

There are two ways for a call to be made to the remote node:

* A plain rpc:call (https://github.com/rabbitmq/rabbitmq-server/blob/9ce5036edd3d9ef116285565c8de8124601389e4/src/rabbit_control_main.erl#L761) which calls a function on the remote node and return the result
* An asynchronous rpc:call (https://github.com/rabbitmq/rabbitmq-server/blob/9ce5036edd3d9ef116285565c8de8124601389e4/src/rabbit_control_main.erl#L772) which calls a function on the remote node and expects the result to be sent back as messages to the given pid

The issue only occurs on errors. On errors, the remote node does this, for example, if there are no users of that name: https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_misc.erl#L505

This then goes here, and the error is thrown: https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_misc.erl#L538

In the first case, a simple rpc:call, this results in the thrown value to be returned to the calling node, because rpc:call catches it and returns it as the result.

In the second case, the same happens; however the rpc:call function was in a spawn_link call and the returned value is ignored and that process ends normally. The function that then waits for messages either timeouts or gets stuck indefinitely depending on the timeout value.

The wait_for_info_messages (https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_control_misc.erl#L70) should probably monitor the spawn_link'd process and return the error if something happened, or the spawn_link'd process should send a message to the parent process, or something similar, to inform that an error happened and no results will get sent.

**Comment by michaelklishin** [comment]
To me, reporting errors to the parent/accumulator makes most sense. Thanks for looking into this, @essen.

**Comment by michaelklishin** [comment]
This was introduced in this cycle as part of #62.

**Comment by videlalvaro** [comment]
Thanks for investigating, I think the spawn process should send the errors back, and probably also be monitored just in case.
