### ISSUE TITLE
Erlang download link used by the Windows installer has moved

### ISSUE THREAD

**Issue by yatmanov** [rabbitmq/rabbitmq-server#4226]
RabbitMQ Server 3.9.13 official installer's Erlang download link points to non-existent page: "https://www.erlang.org/download.html"

![installer](https://user-images.githubusercontent.com/23621240/156569980-cd42b2ac-60e8-45ea-a938-6ed4336d4984.png)

![page](https://user-images.githubusercontent.com/23621240/156569999-cbe10f6c-4ae1-4338-bb21-e4586e8b6158.png)

**Comment by michaelklishin** [comment]
https://www.erlang.org/downloads is the new location.

**Comment by michaelklishin** [comment]
Backported for `3.9.14`, `3.8.28`
