### ISSUE TITLE
How the remote client simply waits for rabbitmq-server to be ready

### ISSUE THREAD

**Issue by lizhifengones** [rabbitmq/rabbitmq-server#4279]
I see that rmq has added a lot of cool health checks (https://github.com/rabbitmq/rabbitmq-management/issues/844).

I am a rookie of rabbitmq. When I have some microservices in k8s that depend on rabbitmq, I will consider using init-container to wait for rabbitmq, but I have not found a good way.

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
