### ISSUE TITLE
Move rabbit_ctl_misc.erl functionality to rabbit_control_misc.erl, and discard it

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-server#428]
Following the implementation of #119 and #62, which took place in near succession, we now have two modules [rabbit_ctl_misc.erl](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_ctl_misc.erl) and [rabbit_control_misc.erl](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_control_misc.erl), respectively, which are meant to serve the same purpose. Only one of these is required, and hence `rabbit_ctl_misc.erl` functionality must be moved to `rabbit_control_misc.erl`, then be discarded, and it references updated to `rabbit_control_misc`.

**Comment by michaelklishin** [comment]
Milestone: `n/a` because this is a refactoring piece that is only relevant to master.
