### ISSUE TITLE
RABBITMQ_LOGS=- prevents logging to other sources altogether

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#4303]
https://groups.google.com/g/rabbitmq-users/c/j1AY7lBWI6c/m/kUMOb5wnAwAJ

When you run RabbitMQ from an official docker image, the following env variable is set:

```
RABBITMQ_LOGS=-
```

This is what prevents the logging exchange from starting, even though that exchange is defined in the configuration file. I can reproduce the behavior outside of Docker if I run RabbitMQ like this:

```
RABBITMQ_LOGS=- RABBITMQ_ALLOW_INPUT=true RABBITMQ_CONFIG_FILE="/home/lbakken/development/lukebakken/rabbitmq-users-j1AY7lBWI6c/rabbitmq.conf" ./sbin/rabbitmq-server
```

As a workaround, you can build an image with a custom entrypoint that unsets the `RABBITMQ_LOGS` env variable. I have updated this repo with just that workaround and it DOES fix the issue:

https://github.com/lukebakken/rabbitmq-users-j1AY7lBWI6c/blob/main/Dockerfile

After reading the source code, it looks like setting the `RABBITMQ_LOG` env var may be a better solution for Docker, but I can't seem to figure out the right syntax to enable both the console log and exchange log.

https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbit/src/rabbit_prelaunch_logging.erl#L1094

The above suggests the following should work:

```
RABBITMQ_LOG='console=debug,+color,exchange=debug'
```

But it does not enable the exchange logger. In addition, I don't see how [the parsing](https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbit_common/src/rabbit_env.erl#L637-L685) could work since commas are used to delineate per-logger configuration as well as the overall loggers themselves. This form makes more sense:

```
RABBITMQ_LOG='console=debug,+color:exchange=debug'
```

@dumbbell we should discuss.

**Comment by michaelklishin** [comment]
Those who use `rabbitmq.conf` settings should have none of these problems.

**Comment by lukebakken** [comment]
@michaelklishin unfortunately the env vars take precedence.

**Comment by dumbbell** [comment]
Environment variables in general are meant to override any configuration files to allow one to quickly run RabbitMQ with a different setting without touching those configuration files. So yes, setting `RABBITMQ_LOGS=...` is expected to override the configuration file. In other words, `RABBITMQ_LOGS` and `RABBITMQ_LOG` are only useful when starting RabbitMQ to try or debug things. They are not designed to configure RabbitMQ in production.

`RABBITMQ_LOG` syntax is a list of the following elements:
* `$level` (`debug` to emergency`)
* `$category=$level`, where `$category` is something like "prelaunch", "channel", "mirroring", ...
* `$modifier`, where `$modifier` is "+color", "-color", "+json", "-json", ...

In particular, `exchange` or `console` are not categories.

To enable the exchange logging output, you should be able to set `RABBITMQ_LOG=exchange:`.

**Comment by dumbbell** [comment]
To me, the following is a bug in the docker image:
> When you run RabbitMQ from an official docker image, the following env variable is set:
> ```
> RABBITMQ_LOGS=-
> ```

**Comment by lukebakken** [comment]
How does `RABBITMQ_LOG=exchange:` fit into the syntax you described? I'd like to document that variable better.

It sounds like we need to change how the Docker image configures logging. I'll open a related issue in that repo.

**Comment by dumbbell** [comment]
Sorry, I meant `RABBITMQ_LOGS=exchange:` in my previous comment. I fixed it.

**Comment by dumbbell** [comment]
RabbitMQ now supports several configuration files. On Unix, it will load all files found in `$SYS_PREFIX/etc/rabbitmq/conf.d` by default.

It should be easy to people packaging RabbitMQ to write their default values in `$SYS_PREFIX/etc/rabbitmq/conf.d/00-default.conf` for instance. Then users can add their own configuration snippets in additional files in that directory.

**Comment by lukebakken** [comment]
I like it @dumbbell. I'll open an issue and PR for the docker image, and will get to documenting these vars a bit better on the website.

Have a great weekend!

**Comment by lukebakken** [comment]
https://github.com/docker-library/rabbitmq/pull/555

**Comment by jeremy-evidos** [comment]
Hello,

Looks like omitting `RABBITMQ_LOGS=-` from the Dockerfile seems to break JSON logging set with `RABBITMQ_LOG=+json`. When adding `RABBITMQ_LOGS=-` again JSON logging starts working again. If there is a configuration option for enabling JSON logging I can add to `/etc/rabbitmq/conf.d/` I'd prefer that but it seems only the environment variable was extended according to https://github.com/rabbitmq/rabbitmq-server/pull/2861.

Best,

Jeremy

**Comment by michaelklishin** [comment]
``` ini
log.file.formatter = json
```

**Comment by jeremy-evidos** [comment]
Thanks! Adding `log.console.formatter = json` did the trick.

**Comment by lukebakken** [comment]
Fixed by the following:

https://github.com/docker-library/rabbitmq/pull/555
https://github.com/rabbitmq/tanzu/issues/7
https://github.com/rabbitmq/tanzu/pull/8
https://github.com/rabbitmq/bitnami-docker-vmware-tanzu-rabbitmq/pull/2
