### ISSUE TITLE
High Level Rabbit Vs. Kafka

### ISSUE THREAD

**Issue by DigitalBlasco** [rabbitmq/rabbitmq-server#4353]

**Comment by johanrhodin** [comment]
This looks like blog spam and is not an actionable issue with rabbitmq-server

**Comment by michaelklishin** [comment]
@johanrhodin we are working on some process changes, so this may end up in a different place. @DigitalBlasco is a product person on our team who's started recently. So this may be "spam" but we are spamming ourselves :)
