### ISSUE TITLE
Accept RAM and disk watermark values in megabytes

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#448]
See #207 and #447. Using megabytes makes much more sense in 2015 but we need things to be consistent for RAM and disk watermarks.

Therefore I think RabbitMQ should support values such as `{absolute_in_mb, N}` for both disk and RAM watermarks. Values in bytes will remain for backwards compatibility.

**Comment by michaelklishin** [comment]
References #378.

**Comment by hairyhum** [comment]
In disk_free_limit there are absolute values by default, should there be `absolute_` prefix in that case?

**Comment by hairyhum** [comment]
And it looks like `rabbit_disk_monitor` operate in megabytes as 10^6, while `vm_memory_monitor` operate in 1048576 MB. Is it OK?

**Comment by michaelklishin** [comment]
@hairyhum we need to introduce a new value, `{absolute_mb, N}` (the best name I could come up with given that `absolute` is already taken).

Unifying [MB vs. MiB](https://en.wikipedia.org/wiki/Mebibyte) along the way is possible. I believe we are supposed to use `10^6` these days, although in my (no longer very young) mind a megabyte is still `1024 * 1024` bytes :)

**Comment by dumbbell** [comment]
Beside disk vendors, I have the impression everybody use MiB naturally :-)

As for the syntax, I like when applications accept a suffix; for instance:
```erlang
{limit, "64"}, % bytes
{limit, "256k"},
{limit, "200M"},
{limit, "1G"},
```
This would require us to parse the string, but in the end, it's more user-friendly and it avoids any confusion about the implicit unit. As for error handling, we already do none if the term is not an integer, so it would not change. What do you think?

We would still need to choose between MiB and MS :-1: )

**Comment by michaelklishin** [comment]
@dumbbell that sounds good but the number of prefixes we might need to support is a bit alarming: `kb`, `k`, `KB`, `KIB`, and so on.

A Google search for "1 megabytes in bytes" yields `10^6`, so I still vote for MB.

**Comment by dumbbell** [comment]
I wasn't suggesting we use the complete suffix, just `k`, `M`, `G` and `T`. For the unit, I more used to power of two, but that's a matter of taste; I'm ok with power of ten if we are consistent everywhere.

**Comment by michaelklishin** [comment]
OK, I think we can support

 * `k`, `K`, `kb`, `KB`
 * `m`, `M`, `mb`, `MB`
 * `g`, `G`, `gb`, `GB`

as suffixes, as well as numerical values that mean bytes.

@hairyhum thoughts?

**Comment by hairyhum** [comment]
Power of two is used a lot in `vm_memory_monitor`, it can be confusing to get rid of it there. 
So there could be no "special tuple", but just a string in place of integer in limit config? That will do, I guess. Not so explicit though.

**Comment by michaelklishin** [comment]
@hairyhum confusing for whom? A megabyte is 10^6 bytes these days, not `1024 * 1024`, so if we use megabytes in memory monitor, we need to correct it. It won't be a major breaking change in practice, I think.

**Comment by hairyhum** [comment]
@michaelklishin I don't know, maybe someone rely on it. There are some parsing of system memory data and limits defined as 256*1024*1024*1024*1024 for example. It's looks like OS opinion about what megabyte is.

**Comment by michaelklishin** [comment]
@hairyhum setting RAM watermark as an absolute value is an unreleased feature new in 3.6.0, so we can pretty much assume there are no users who rely on it.

**Comment by dumbbell** [comment]
Yeah, in Unix, "MB" is always 2^20, as opposed to SI's 10^6.

We can distinguish input and output. On the input side, as I previously said, I prefer the Unix tradition (ie. power of two) if the unit is implicit (eg. "200M"). If we support the full unit as a suffix, I would follow SI ("MB" = 10^6, "MiB" = 2^20) and both suffixes should be accepted.

On the output side (the log files or the management UI), we should always explicitely specify the unit. In this case, I prefer "MiB".

**Comment by michaelklishin** [comment]
I agree with @dumbbell.

**Comment by dumbbell** [comment]
To be explicit on the input side, that means:
```erlang
"1" == 1 % One byte.
"1k" == "1kiB" == 1024 % A suffix w/o unit is Unix tradition.
"1kB" == 1000
```

**Comment by hairyhum** [comment]
It looks a more consistent, but should be documented. Let's continue with this decision. 
There will be `{vm_memory_high_watermark, {absolute, limit()}}` and `{disk_free_limit, limit()}`
Where `limit() :: integer() | string()`
And string can be integer or integer with unit:
k, K, KiB - kibibytes
m, M, MiB - mebibytes
g, G, GiB - gibibyte
kb, KB - kilobytes
mb, MB - megabytes
gb, GB - gigabytes

**Comment by dumbbell** [comment]
If we want to be consistent with SI, this must be case sensitive: "m" and "M" mean totally different things. We should stick to "k" (lowercase) and "M", G", and "T" (uppercase).

**Comment by hairyhum** [comment]
So it will be
k, kiB - kibibytes
M, MiB - mebibytes
G, GiB - gibibyte
kB - kilobytes
MB - megabytes
GB - gigabytes

**Comment by hairyhum** [comment]
And if we use strings with strict parse rules there will be invalid strings. I guess we should use some error reporting for this case. Is there some error reporting about bad config?

**Comment by michaelklishin** [comment]
Log an error and ignore the value. Don't terminate node startup.

**Comment by michaelklishin** [comment]
Error reporting for `rabbitmqctl`is fairly obvious.

**Comment by hairyhum** [comment]
Then it will be parsed on startup or changing and used as {absolute, integer()} in internal state.

**Comment by hairyhum** [comment]
And we have no action to set disk limit in rabbit_control_main, it can be set only from config. Do we need it?

**Comment by michaelklishin** [comment]
@hairyhum please file a separate issue for that

**Comment by hairyhum** [comment]
Since `vm_memory_high_watermark` is required when starting `vm_memory_monitor` "ignoring" value means use `infinity`?

**Comment by michaelklishin** [comment]
It means falling back to the relative setting, which has a default.

**Comment by hairyhum** [comment]
How can you fall back to relative setting, when it was overriden in application env, since it was specified in rabbitmq.config? Or maybe I missing something?

**Comment by michaelklishin** [comment]
It currently has a default: 0.4 of available RAM. Use that instead of infinity.
