### ISSUE TITLE
rabbitmq-plugins script reading from wrong env variable

### ISSUE THREAD

**Issue by gigablah** [rabbitmq/rabbitmq-server#451]
Apparent mistake introduced by this commit on Jan 28:

https://github.com/rabbitmq/rabbitmq-server/commit/cc040e95d6ee7e0703547338848c2849b39e59ec#diff-8938c4358ef17da8f0f0f976f727f87c

The variable is supposed to be `RABBITMQ_CTL_ERL_ARGS`  but was added as `RABBITMQ_PLUGINS_ERL_ARGS` in `rabbitmq-plugins`. This variable is never processed in `rabbitmq-env` and thus will be empty.

**Comment by michaelklishin** [comment]
Thanks. It may or may not be intentional, only @videlalvaro can say for sure :)

**Comment by videlalvaro** [comment]
@gigablah is correct.

**Comment by michaelklishin** [comment]
Fixed by #452.

**Comment by michaelklishin** [comment]
This can be cherry-picked to `3.5.x` => marking as such.
