### ISSUE TITLE
Prometheus plugin is missing process_start_time_seconds metric

### ISSUE THREAD

**Issue by ViliusS** [rabbitmq/rabbitmq-server#4539]
It seems that RabbitMQ's Prometheus plugin is missing process_start_time_seconds metric which is required by some metric scrappers. For example prometheus-to-sd from Google produces this warning:
```Metric process_start_time_seconds invalid or not defined for component rabbitmq. Using 1970-01-01 00:00:01 +0000 UTC instead. Cumulative metrics might be inaccurate.```

In effect this produces incorrect metrics in monitoring or issues like https://github.com/GoogleCloudPlatform/k8s-stackdriver/issues/202

I see that an old 3rd-party Prometheus plugin had this metric https://github.com/deadtrickster/prometheus_process_collector/search?q=process_start_time_seconds

It should be trivial to implement. I could have done it myself, but I don't know erlang sadly :|

**Comment by ikvmw** [comment]
In that plugin I use OS-specific NIFs. Will have to look how others implement it, if it's possible to do without NIFs

**Comment by ViliusS** [comment]
@ikvmw Thank you for your patch! This issue is not really a big showstopper for me, so I can wait for the official release. One note though, you probably meant to have it named "prometheus_process_colle**c**tor" instead of "prometheus_process_colletor" :)

**Comment by ikvmw** [comment]
thanks for the catch. @michaelklishin shall I open the new issue regard `prometheus_process_collector` and close this one or leave this one open for the future reference? what do you think?

**Comment by michaelklishin** [comment]
@ikvmw just submit a new correcting PR.
