### ISSUE TITLE
Add using rabbit.config to set queue-master-locator strategies to documentation

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-server#460]
Queue master location strategies can also be defined in `rabbit.config`. This is missing in the [documentation](https://github.com/rabbitmq/rabbitmq-website/blob/master/site/ha.xml#L132).

Ref: #121

**Comment by michaelklishin** [comment]
Fixed in https://github.com/rabbitmq/rabbitmq-website/pull/112.
