### ISSUE TITLE
UNIX exit code when rabbitmq-server fails to load its config file is 0

### ISSUE THREAD

**Issue by Subito** [rabbitmq/rabbitmq-server#464]
```
# /usr/local/sbin/rabbitmq-server
{"could not start kernel pid",application_controller,"error in config file \"/usr/local/etc/rabbitmq/rabbitmq.config\" (none): no ending <dot> found"}
# echo $?
0
```
That makes it unnecessary hard to detect if the startup worked correctly. If the exit-code could indicate an  error, the rc-scripts could respond to that and not just report it started all the time even if it could't even parse the config.

**Comment by michaelklishin** [comment]
The failure above is, unfortunately, in the code that executes before RabbitMQ is started. Perhaps something can be improved in the shell script.

What version do you use?

**Comment by michaelklishin** [comment]
Related: #396.

**Comment by videlalvaro** [comment]
I think the problem might be related to this line: https://github.com/rabbitmq/rabbitmq-server/blob/master/scripts/rabbitmq-server#L164

We should store in a variable the last exit code and probably return that once the wait exits

**Comment by hairyhum** [comment]
`wait` command can wait for specific background job only and will return exit code for it.

**Comment by dumbbell** [comment]
This issue is fixed by #468.

**Comment by michaelklishin** [comment]
Thank you, @hairyhum!

**Comment by Subito** [comment]
Nice, thanks!
