### ISSUE TITLE
rabbitmqctl.bat on Windows with spaces in Erlang Install Path can't execute inet_gethost.exe

### ISSUE THREAD

**Issue by StevenBonePgh** [rabbitmq/rabbitmq-server#4669]
I first noticed this in RabbitMq 3.9.7 and it persists in 3.9.16, when running against Erlang 24.3.2 and 24.3.3, on Windows, where there are spaces in the path to ERLANG_HOME. I do not know if this is related to RabbitMq or Erlang, however, Erlang 24.3.3 mentions a bugfix for  OTP-17958 which addressed the following:
> erlang:open_port({spawn, _},_) has been fixed on Windows to handle whitespace characters in the path correctly.
> 
> This could, for example, cause execution of the resolver helper program inet_gethost to fail and instead possibly execute a different program.

To see the error I am referring to, if you execute the following (with spaces to your erlang installation):
`rabbitmqctl.bat 2>c:\error_output.txt await_startup`
and view the file created (`c:\error_output.txt`), you will see the following:
```
C:\Program: Unknown option "Files\Ctr.Rabbit.Erlang\Erlang\erts-12.3.1\bin\inet_gethost.exe"
Usage: C:\Program [-d [-d ...]] [-g <greedy threshold>] [<number of workers>]
```
The command appears to work as intended if you are just looking at the standard output stream if you used the command on the console without error output redirection. Similar output can be seen with the `list_users` argument. The other batch files I typically use:, `rabbitmq-plugins.bat` and `rabbitmq-service.bat`, do not have such error stream output.

Something in the workflow of the batch file is attempting to execute `inet_gethost`. The only mention to 'inet_gethost' that I can find in the RabbitMq source code is in [rabbit_networking.erl](https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbit/src/rabbit_networking.erl) as a comment before calling `inet_parse:address`. 

Obviously, this is an issue with not quoting the path properly, like as specified in the OTP issue quoted above. Likewise, this is a relatively mild or moderate [security issue](https://securityboulevard.com/2018/04/windows-privilege-escalation-unquoted-services/) as if someone used the default Erlang path and was already able to have permissions to add a file "C:\program.exe", it could be executed with the callers permissions (requiring the actor to previously been on the other side of the 'airtight hatchway').

Could you please shed some light on this, specifically if there would be some other unforeseen runtime issues related to this, and if this is a RabbitMq issue or if it should be raised with the Erlang team. If it is the latter - with Erlang - I don't know the appropriate way to report an issue other than perhaps a forum post.

**Comment by michaelklishin** [comment]
Such paths are explicitly called out [in the docs](https://rabbitmq.com/windows-quirks.html).

RabbitMQ does not call `inet_gethost` directly. We have addressed a few similar escaping issues in our own batch scripts but this seems to be a never-ending source of pain. I'd just consider
installation paths with spaces to be unsupported. It's extremely rare to see users on other OSes to use spaces in installation paths, so presumably it's a pretty easy requirement to adhere to.

**Comment by StevenBonePgh** [comment]
In all fairness, the documentation does not call out spaces in the paths being a Windows quirk. It mentions non-ASCII character sets.

**Comment by michaelklishin** [comment]
Maybe it was there at some point but then deleted as (years ago) we considered it a solved problem. We can add a note to that guide or even better, [this section](https://rabbitmq.com/install-windows.html#installer) in the main Windows installation guide.

I'll try to get to it in the upcoming couple of days.

**Comment by StevenBonePgh** [comment]
Thank you, that would be helpful for future me and others!

**Comment by lukebakken** [comment]
Hm, I've used the default Erlang install path with RabbitMQ and have never seen this issue. When using Erlang installed to the default location setting `ERLANG_HOME` isn't necessary. Just my $0.02

**Comment by StevenBonePgh** [comment]
I did post on the [Erlang forum](https://erlangforums.com/t/inet-gethost-execution-with-spaces-in-path-fails-on-windows-perhaps-related-to-otp-17958/1356), and after the reply, verified that a C:\program.exe does not get executed - at least on Windows 11, so it is not any level of security concern. In fact, Windows Explorer on startup warns you about this filename and offers to rename it. He also says that they changed the way this tool is called, so it may not appear at all on Erlang 25. And like I said, everything appears to work fine. So this makes me feel much better.
