### ISSUE TITLE
Allow quorum queues for internal use by Federation

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#4683]
Related to these items:
* https://github.com/rabbitmq/rabbitmq-server/issues/2544
* https://pivotal-esc.atlassian.net/browse/VESC-1034

Currently, if you federate an exchange the upstream node creates an internal queue from which the downstream consumes. These internal queues _can_ be mirrored, but only with classic mirroring. Quorum queues should be an option.

This addresses the scenario in which the node hosting the internal queue for federation on the upstream goes down. Without being mirrored this effectively stops federation.

**Comment by d4nnyx** [comment]
+1

**Comment by d4nnyx** [comment]
D h Vbbfsgcytyrjeueuttuckxncfmerjhfhshshfhdhfhdhfhdjfyghdjfjdjddjdjsjfjdjddjdududugjjvjvugrueudjjefjedjx
