### ISSUE TITLE
RabbitMQ doesn't rotate category logs

### ISSUE THREAD

**Issue by illotum** [rabbitmq/rabbitmq-server#4697]
RabbitMQ v3.9.x and later do not rotate category logs.

`rabbit_prelaunch_logging:normalize_cat_log_config/1` does not attempt to parse any rotation rules and no rules are applied from other sources in `rabbit_prelaunch_logging:create_handler_conf/3`. 

Unless I am missing something, configuration like this simply is not implemented:

```
log.channel.file = channel.log
log.channel.rotation.size = 30000
log.channel.rotation.size = 3
```

**Comment by michaelklishin** [comment]
FTR, this was discussed in our community Slack. During the migration from Lager to the standard OTP logger in 3.9.0, some Lager features were left behind, in particular around log rotation.
