### ISSUE TITLE
'rabbitmqctl forget_cluster_node' attempts to impersonate reachable nodes

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-server#470]
#348 shows a case where `rabbitmqctl forget_cluster_node` attempts to impersonate a reachable node. Offline in the context of RabbitMQ means the rabbit application is not running and the node is unreachable. Node impersonation by `rabbitmqctl forget_cluster_node` must only work for unreachable nodes.

**Comment by michaelklishin** [comment]
@Ayanda-D can this go into `3.5.7`? If so, can you please rebase #471 against `stable`?

**Comment by Ayanda-D** [comment]
@michaelklishin this can go into `3.5.7`. Rebasing #471 a bit of overkill for this fix. Recreated branch off stable & resubmitted PR #476.
