### ISSUE TITLE
Telnet to the RabbitMQ Stomp adapter just hung

### ISSUE THREAD

**Issue by rezoan** [rabbitmq/rabbitmq-server#474]
I am using RabbitMQ server 3.5.6 on windows 8.1 and Windows 7 x64.

I have to access the Stomp Adapter embedded with the RabbitMQ Server.

So i have configured it from https://www.rabbitmq.com/stomp.html

it shows that it is successfully enabled and configured the rabbitmq_stomp.

After doing this i have restarted my computer and try to telnet to the localhost 61613 (the default socket of the rabbitmq_stomp) and it just hung in there saying connecting.

![untitled](https://cloud.githubusercontent.com/assets/1701375/11590761/bdac3b9e-9abc-11e5-94be-29e1a27cfaf0.png)

The RabbitMQ server log says:

=INFO REPORT==== 4-Dec-2015::17:53:29 ===
accepting STOMP connection <0.327.0> ([::1]:49397 -> [::1]:61613)

what did i do wrong? any help would be appreciated.

**Comment by michaelklishin** [comment]
Please ask questions on rabbitmq-users.

The Telnet connection was successful as confirmed by the log. Telnet does not log when a connection is established. It then waits for your protocol-specific commands to be entered.
