### ISSUE TITLE
Logging upgrade category output to stdout

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#4792]
Prior to https://github.com/rabbitmq/rabbitmq-server/issues/4303, setting `RABBITMQ_LOGS=-` would also send the upgrade log file to stdout.

We should allow using configuration entries like this:

```
log.upgrade.file = -
log.upgrade.file = stdout
```

This should also be valid for the other log files.

**Comment by michaelklishin** [comment]
The example here folds categories and targets together. Should we start with figuring out why the upgrade category doesn't inherit the default target? I'd expect most environments to choose
to either log everything into files, or everything to standard streams, or everything to Syslog.

**Comment by dumbbell** [comment]
This upgrade file was kept when RabbitMQ was switched to Lager. To support this, there is a special configuration in RabbitMQ just for this category. I would be in favor of getting rid of this legacy and treat it like other categories. It would mean that the default log file would be used out-of-the-box for upgrade logs. Perhaps there is something special with upgrades that I don't picture which is better served with a dedicated log file though.

**Comment by lukebakken** [comment]
This issue has been rendered moot by @dumbbell's PR - https://github.com/rabbitmq/rabbitmq-server/pull/5415
