### ISSUE TITLE
Include source IP address in log messages

### ISSUE THREAD

**Issue by MichalMichalak** [rabbitmq/rabbitmq-server#483]
As per mailing list conversation(1), I'd like to fill in feature request. Currently log messages does not contain source IP address. Such address would make troubleshooting much easier. Could you please consider improvement of logging system? Thanks.

(1) https://groups.google.com/forum/#!topic/rabbitmq-users/CBUYqqBwlg0

**Comment by Ayanda-D** [comment]
Heads up, to update [rabbit_webmachine_error_handler.erl](https://github.com/rabbitmq/rabbitmq-web-dispatch/blob/master/src/rabbit_webmachine_error_handler.erl#L55) then check for other places where client IP address logging would be relavant, and update if necessary.

**Comment by michaelklishin** [comment]
@MichalMichalak as part of investigating this we found out that we do, in fact, log source IP addresses, just in different logs:

 * Client connections have an IP address logged
 * HTTP API requests (which is what your original thread was concerned with) are logged in a dedicated log file

I don't know if mentioning IP addresses in every error message would be beneficial or not. We decided to add a test and close this issue.
