### ISSUE TITLE
Control over Federation queue auto-delete property

### ISSUE THREAD

**Issue by sphtd** [rabbitmq/rabbitmq-server#4896]
Hi, referring to the messages on Slack, I decided to write here as well. It is more like an idea or an implementation.

More specifically, it is about adding an auto-delete selection option when creating a federation. Now this is deafultly set to true, we need an option where this can be changed.

PS. We also need more information on this:

resource-cleanup-mode: never

**Comment by lukebakken** [comment]
It's important to include a link to the Slack conversation:

https://rabbitmq.slack.com/archives/C1EDN83PA/p1653390852313819
