### ISSUE TITLE
Error when calling rabbitmqctrl join_cluster

### ISSUE THREAD

**Issue by gonace** [rabbitmq/rabbitmq-server#49]
rabbit@adp-rabbitmq01:~# rabbitmqctl join_cluster --ram rabbit@adp-rabbitmq02 rabbit@adp-rabbitmq03

    Error: {'EXIT',
           {function_clause,
               [{rabbit_control_main,action,
                    [join_cluster,'rabbit@adp-rabbitmq01',
                     ["rabbit@adp-rabbitmq02","rabbit@adp-rabbitmq03"],
                     [{"-q",false},
                      {"-n",'rabbit@adp-rabbitmq01'},
                      {"--ram",true}],
                     #Fun<rabbit_control_main.11.121822165>],
                    []},
                {rabbit_cli,main,3,[]},
                {init,start_it,1,[]},
                {init,start_em,1,[]}]}}

I've followed the guidelines at http://www.rabbitmq.com/ha.html but can't seem to add nodes to the cluster.

adp-rabbitmq01/02/03 is resolving to their assigned ip-addresses and I can telnet to each of them from all nodes. The eralang cookie is allso checked (several times) and is the same on all machines/nodes.

I can't seem to find anything wrong with what I'm doing.

Runing RabbitMQ 3.4.3 on all machines!

**Comment by michaelklishin** [comment]
This repository is a mirror. Please post questions to rabbitmq-users.

**Comment by michaelklishin** [comment]
You are providing too many arguments to `join_cluster`. It should be given a single node to contact. Also, I assume you mean http://www.rabbitmq.com/clustering.html, as http://www.rabbitmq.com/ha.html doesn't have a clustering transcript.

**Comment by gonace** [comment]
So I've tried to add one node instead of two and that works, and I've allso checked that I can add booth separatly. But only one at a time can be clustered.

    root@adp-rabbitmq01:/var/lib# rabbitmqctl join_cluster rabbit@adp-rabbitmq02
    Clustering node 'rabbit@adp-rabbitmq01' with 'rabbit@adp-rabbitmq02' ...
    rabbit@adp-rabbitmq01:/var/lib# rabbitmqctl join_cluster rabbit@adp-rabbitmq02 rabbit@adp-  rabbitmq03
    Error: {'EXIT',
           {function_clause,
               [{rabbit_control_main,action,
                    [join_cluster,'rabbit@adp-rabbitmq01',
                     ["rabbit@adp-rabbitmq02","rabbit@adp-rabbitmq03"],
                     [{"-q",false},
                      {"-n",'rabbit@adp-rabbitmq01'},
                      {"--ram",false}],
                     #Fun<rabbit_control_main.11.121822165>],
                    []},
                {rabbit_cli,main,3,[]},
                {init,start_it,1,[]},
                {init,start_em,1,[]}]}}
rabbit@adp-rabbitmq01:/var/lib#

**Comment by gonace** [comment]
Okei, but when I add one then the other the first is removed from the cluster.

**Comment by michaelklishin** [comment]
That's how it is currently done: you cluster a node with another node. The node `rabbitmqctl` contacts (which is only 1 by definition) is joining the cluster, not the other way around.

**Comment by michaelklishin** [comment]
@gonace sorry, that can't be true. Adding nodes cannot remove other nodes. Please reset all nodes and follow the transcript on http://www.rabbitmq.com/clustering.html step by step. There is not a lot of room to make it even more detailed.

**Comment by gonace** [comment]
I'm sure that I'm the one missing something, I'll take a look at the documentation you provided. Thanks!
