### ISSUE TITLE
RabbitMQ on Windows is confused with non-ASCII chars in the path

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#493]
The most common sympton is when a user account contains non-ASCII characters, the management UI breaks. Therefore `%APPDATA%` expands to eg. `C:\Users\Jean-Sébastien\AppData\Roaming`.

If I understand correctly, Windows stores filenames using UTF-16. However, cmd.exe and batch files do not handle that and filenames are converted to one-byte-wide charsets (Windows-1252/CP 850 in my case). Once passed to Erlang through our scripts (`rabbitmq-server.bat`, `rabbitmqctl.bat`, `rabbitmq-env.bat`, etc.), filenames may be incorrects.

In the case of the management UI, the problem is that the `/api/nodes` endpoint wants to put the path to the configuration file (eg. `C:\Users\Jean-Sébastien\AppData\Roaming\RabbitMQ\rabbitmq.config`) in the JSON payload. The `é` encoded in Windows-1252 is obviously an invalid UTF-8 character and the endpoint returns an error. This endpoint is queried on the management UI homepage so once logged in, the user can't do much.

**Comment by dumbbell** [comment]
The tested approach is to use short filenames. For example, `C:\Users\Jean-Sébastien` becomes `C:\Users\JEAN-S~1`. Short filenames are inherited from the era when Windows needed to support 8.3 filenames from DOS to remain backward compatible with earlier versions of Windows and DOS. Short filenames contain only US-ASCII characters, no spaces and are limited to the 8.3 naming.

Using short filenames works nicely when the file already exists. If it doesn't exist, we can't use short filenames, otherwise, the file would be created with its short name on disk.

So far, the only downside is that those short filenames are ugly. But it makes RabbitMQ work out-of-the-box, including the management UI.

I played a bit with PowerShell scripts, but I couldn't find anything promising. They seem nice for sysadmins who want to automate their own stuff, but they look not designed to write startup scripts.

**Comment by michaelklishin** [comment]
Fixed in #582.
