### ISSUE TITLE
rabbitmq_server-3.5.4 hangs all clients on windows

### ISSUE THREAD

**Issue by joaoportela** [rabbitmq/rabbitmq-server#497]
I have a rabbitmq server on my windows machine for local development, and it sometimes (quite rarely) starts in a "corrupted" state that somehow accepts connections but hangs *forever* on all other interactions.

I detected the same issues on both my python client (pika==0.10.0) and .NET client (RabbitMQ.Client v3.5.4)

Example code:

```python
connection = pika.BlockingConnection(pika.ConnectionParameters(
                host=os.getenv('ABYSSAL_RABBITMQ_HOST'),
                heartbeat_interval=0))
            channel = connection.channel()
            channel.queue_declare(queue=RPC_QUEUE) # BLOCKS HERE
```

I confirmed that the .NET client also hangs on `IModel.QueueDeclare` and also on `IModel.Close`.

Restarting the corresponding windows service fixes this issue.
I haven't found out yet how to force it to happen, it just happens after a reboot.

Which log files should I attach?

**Comment by michaelklishin** [comment]
Please post questions to `rabbitmq-users`. There are only 2 log files. First thing to check is if your apps can be running into [disk alarms](http://www.rabbitmq.com/alarms.html).
