### ISSUE TITLE
centos 7 support for rabbitmq 3.10

### ISSUE THREAD

**Issue by ramarm** [rabbitmq/rabbitmq-server#4979]
Hey,

We really like the new features came in 3.10 and we want to start running on it.
Unfortunately we run on centos 7 and I couldn't find a rpm supporting this version of centos.

Is there an option to support centos 7?

Thanks!

**Comment by mkuratczyk** [comment]
https://blog.rabbitmq.com/posts/2022/04/centos-7-support-discontinued/

**Comment by michaelklishin** [comment]
CentOS 7 support has been [discontinued last month](https://blog.rabbitmq.com/posts/2022/04/centos-7-support-discontinued/).
