### ISSUE TITLE
"Cluster links" in management UI are broken when TLS dist is enabled

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#4981]
I discovered this issue while testing #4932 

Repro steps:
* Start cluster with inter-node TLS enabled.
* Open management UI, click on cluster node
* "Cluster links" will not have data

The problem is due to [this check](https://github.com/rabbitmq/rabbitmq-server/blob/cca1164afe1b39df4067de5d8ba74360cb0f010b/deps/rabbitmq_management_agent/src/rabbit_mgmt_external_stats.erl#L361): [code](https://github.com/rabbitmq/rabbitmq-server/blob/cca1164afe1b39df4067de5d8ba74360cb0f010b/deps/rabbitmq_management_agent/src/rabbit_mgmt_external_stats.erl#L361). `is_port/1` returns `false` for a TLS link.

I'm investigating if there is a workaround.

**Comment by gomoripeti** [comment]
I also hit this issue with a custom distribution module. For example in case of the [example provided by OTP](https://github.com/erlang/otp/blob/master/lib/kernel/examples/gen_tcp_dist/src/gen_tcp_dist.erl) also it's not the owner who has the port linked. I guess the best way would be if OTP would provide a documented API to get these stats. In absence of such maybe RabbitMQ could provide an API to report or could allow to register a callback to return those metrics. This would be a nice, generic solution for all dist modules. (I can imagine some distribution protocols don't use ports at all, they might use the new sockets or whatever strange transport)

**Comment by michaelklishin** [comment]
The failures are unrelated as @pjk25 and I have figured. It's something specific to BuildBuddy's networking setup, some AMQP 1.0 clients fail to connect to/from localhost.
