### ISSUE TITLE
Add flag to transfer CMQs leadership during maintenance mode.

### ISSUE THREAD

**Issue by illotum** [rabbitmq/rabbitmq-server#4986]
While CMQs are planned to be deprecated, and a valid justification is given to why this is not done automatically, power users should be able to transfer CMQ's leadership during `rabbitmq-upgrade drain` without resorting to `rabbitmqctl eval`.

I suggest to add flag `--classic` to the above command, passed to `rabbit_maintenance:do_drain()`, that lets perform this operation. Flag name subject to discussion of course.

Optionally, consider adding sanity checks to make this mode of drain safer to invoke.

**Comment by michaelklishin** [comment]
When maintenance mode was first introduced in Nov 2020, it seemed like a great idea to transfer CMQ leaders. However, we ended up removing that step in c7b9c393527fa69633383b856700a6d151c27e3d. Quorum queue and stream leader transfer is cheap and predictable but CMQ leadership transfer is not.

Those who want to do that can develop a plugin that ships with a single command, and do it before or after draining a node. However, we concluded that it does not yield much benefit
compared to what would happen should the target node be simply shut down.

Such transfer is best combined with a leader rebalancing one, and that's definitely not in scope for maintenance mode.

**Comment by michaelklishin** [comment]
Also, this is a great example of why CLI tools after 3.7.0 are extensible: we expected some operators to have completely different opinions about what health checks or maintenance commands should exist.

So just follow a naming convention, pick a scope, implement a module in Elixir or Erlang, and you can add any command to any tool provided (not just `rabbitmqctl`, can be `rabbitmq-upgrade`, too).

**Comment by illotum** [comment]
I researched the history of leadership transfer, no qualms about your decision.

Do I understand correct @michaelklishin, that you would rather not see this flag merged into mainline `rabbitmqctl`? A plugin would require research on behalf of the user.

**Comment by michaelklishin** [comment]
Yes, a single module plugin would do.
