### ISSUE TITLE
set x-max-age when using the stomp plugin

### ISSUE THREAD

**Issue by tomlissen** [rabbitmq/rabbitmq-server#5003]
Currently there is no way to set the x-max-age header when using stomp. Recently there was a commit adding x-stream-offset. Would it be possible to also add the x-max-age header?

Regards,
Tommy

**Comment by michaelklishin** [comment]
Do you have a link to said commit?

**Comment by michaelklishin** [comment]
[Found it](https://github.com/rabbitmq/rabbitmq-server/commit/065b92114dce48acd41dbfb4f5bbeba1bf322951)
