### ISSUE TITLE
Can't set net_ticktime on Windows via advanced.config

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#5055]
Reproduction steps:

* Create `%AppData%\RabbitMQ\advanced.config` with the following content:
    ```
    [{kernel, [{net_ticktime, 600}]}].
    ```
* Install RabbitMQ 3.10.5 from exe installer.
* Note that `rabbitmqctl status` shows `60` for the tick timeout.

Reported here:
https://groups.google.com/g/rabbitmq-users/c/Fj16HE_C5sw

I quickly tested `master` on Arch Linux and the `net_ticktime` _is_ correctly set when starting the broker this way:

```
make RABBITMQ_ADVANCED_CONFIG_FILE=/path/to/advanced.config PLUGINS=rabbitmq_management run-broker
```

**Comment by ChingYuTsai** [comment]
Thanks Luke.
How can I start the broker in your way? Is it doable by any configuration?

**Comment by lukebakken** [comment]
This is due to how the Erlang VM is run as a service on Windows. Erlang distribution is started at an earlier phase than on Linux, so you must set net_ticktime via a VM argument. To do so, create the `%AppData%\RabbitMQ\rabbitmq-env-conf.bat` file with the following contents

```
> cat C:\Users\bakkenl\AppData\Roaming\RabbitMQ\rabbitmq-env-conf.bat
@echo off
set SERVER_ADDITIONAL_ERL_ARGS=-kernel net_ticktime 600
```

Then, uninstall and install the service again:

```
cd C:\Program Files\RabbitMQ Server\rabbitmq_server-3.10.5\sbin
.\rabbitmq-service.bat stop
.\rabbitmq-service.bat remove
.\rabbitmq-service.bat install
.\rabbitmq-service.bat start
```

@michaelklishin this should probably be reflected in the docs, eh? I can get that next week.

**Comment by ChingYuTsai** [comment]
@lukebakken It works well now. Thanks for your help.
