### ISSUE TITLE
Add date time value to maybe_stuck()

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-server#506]
On the function `rabbit_diagnostics:maybe_stuck` can be useful add the current timestamp  for each process stack.
Can help to find the correspondences to the log files.

Like this:
`14-Dec-2015::16:50:23:  Investigated 30 processes this round, 500ms to go.`
`14-Dec-2015::16:50:24: Found 30 suspicious processes.`
`14-Dec-2015::16:50:25:  [{pid,<5418.668.0>},`
 `{registered_name,[]},`

**Comment by michaelklishin** [comment]
@Gsantomaggio thanks to @hairyhum this has made it into 3.6.0 :)

**Comment by Gsantomaggio** [comment]
Great! Thank you @hairyhum  ! :+1:
