### ISSUE TITLE
Find configuration file bug when set CONFIG_FILE in RabbitMQ Environment

### ISSUE THREAD

**Issue by znoodl** [rabbitmq/rabbitmq-server#51]
I writed configuration file Environment in `/etc/rabbitmq/rabbitmq-env.conf`
`CONFIG_FILE=/etc/rabbitmq/rabbitmq.config` or `RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.config`,
and restart the rabbitmq-server, but `rabbitmq.config` doesn't work.
Node message: `Config file	/etc/rabbitmq/rabbitmq.config (not found)` on web monitor page with plugin rabbitmq_management.

When i remove it from `/etc/rabbitmq/rabbitmq-env.conf`, it worked. I don't know why, maybe it's a bug.

rabbitmq-server-3.4.4-1.noarch.rpm and os is Centos6.4 x64.

**Comment by michaelklishin** [comment]
This repository is a mirror. Please post your questions to rabbitmq-users.

It should be

```
CONFIG_FILE=/etc/rabbitmq/rabbitmq
```

as mentioned on http://www.rabbitmq.com/configure.html.
