### ISSUE TITLE
Khepri integration: AMQP declaration performance

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/rabbitmq-server#5101]
NOTE: this issue is related to an unreleased Khepri integration (branch khepri-queues). 
NOTE2: This issue has been significantly edited with a simpler test case

On my system `perf-test -p -e amq.topic -t topic -qp q-%d -qpf 1 -qpt 10000 -y 0 -c 1 -C 1` takes 30 seconds with Mnesia and 80 seconds with Khepri. This is 10000 classic queues + 10000 topic bindings + 10000 direct bindings.

It's interesting to consider this story together with https://github.com/rabbitmq/rabbitmq-server/issues/5106. Definitions import is generally faster with Khepri with a dataset of this size, but it is almost 3 times slower when performed by an AMQP client.

**Comment by dcorbacho** [comment]
@mkuratczyk This should be solved on https://github.com/rabbitmq/rabbitmq-server/tree/khepri-queues-rebase/, commit https://github.com/rabbitmq/rabbitmq-server/commit/85a456b9ade158aeb467ae5aeee4f070f188411d

**Comment by mkuratczyk** [comment]
Update after almost a year of development. Tests performed on the [`khepri` branch](https://github.com/rabbitmq/rabbitmq-server/commit/623b3443af368b6af0a1b656ad365fdafcfc761a) with `khepri_db` FF disabled/enabled.
1. `perf-test -p -e amq.topic -t topic -qp q-%d -qpf 1 -qpt 10000 -y 0 -c 1 -C 1`
mnesia: 36s
khepri: 227s

1. `perf-test -p -e amq.topic -t topic -qp q-%d -qpf 1 -qpt 10000 -y 0 -c 1 -C 1 --skip-binding-queues`
mnesia: 27s
khepri: 127s


Nothing clearly stands out (flamegraph captured for 200s during the first of the above tests), unless `khepri` somehow makes the `rabbit_mgmt_metrics_collector` slower.
![issue-5101](https://github.com/rabbitmq/rabbitmq-server/assets/9566114/6459f6ce-b65d-4664-b7ee-ce7ab40d07ac)

For comparison, 20s captured when running against Mnesia:
![mnesia](https://github.com/rabbitmq/rabbitmq-server/assets/9566114/5a3bbdfd-dccc-4de9-b72d-dc56232167d5)
