### ISSUE TITLE
Khepri integration: `rabbitmq-diagnostics memory_breakdown` should report the metadata store RAM usage

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/rabbitmq-server#5102]
NOTE: this issue is related to an unreleased Khepri integration (branch khepri-queues). 

With many definitions, the metadata store can use GBs of RAM. All that memory is currently reported under `other_proc`.
We should report this separately.

**Comment by dcorbacho** [comment]
Detailed memory breakdown added in https://github.com/rabbitmq/rabbitmq-server/commit/c55d20d9d1de550feddae9bc71576655d2587b25, branch `khepri-queues`

**Comment by mkuratczyk** [comment]
```
$ rabbitmq-diagnostics memory_breakdown
Reporting memory breakdown on node rabbit@kura...
metadata_store: 0.4195 gb (72.47%)
code: 0.0449 gb (7.75%)
other_proc: 0.0325 gb (5.61%)
...
```

Nice. Thanks
