### ISSUE TITLE
Consul peer discovery TLS options are not exposed to rabbitmq.conf

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#5116]
As reported here:

https://groups.google.com/g/rabbitmq-users/c/euqt9iBKB4M

Note that the etcd peer discovery plugin has quite a few `ssl_options` available that should be made available to the consul plugin.

https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbitmq_peer_discovery_etcd/priv/schema/rabbitmq_peer_discovery_etcd.schema#L166-L279

**Comment by fbushman** [comment]
I encountered the same limitation today. When setting the `cluster_formation.consul.scheme = https` setting the RabbitMQ server fails during startup with the following warning:

```
rabbitmq-server1  | 2022-07-04 12:13:19.283199+00:00 [warning] <0.314.0> Description: "Authenticity is not established by certificate path validation"
rabbitmq-server1  | 2022-07-04 12:13:19.283199+00:00 [warning] <0.314.0>      Reason: "Option {verify, verify_peer} and cacertfile/cacerts is missing"
rabbitmq-server1  | 2022-07-04 12:13:19.283199+00:00 [warning] <0.314.0> 
rabbitmq-server1  | 2022-07-04 12:13:19.303054+00:00 [error] <0.221.0> Failed to lock with peer discovery backend rabbit_peer_discovery_consul: "Error while creating a session, reason: {failed_connect,[{to_address,{\"consul-server1\",8500}},{inet,[inet],nxdomain}]}"
```

However, as @lukebakken points out, the options referred to are only available for k8s and etcd:

[https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbitmq_peer_discovery_consul/priv/schema/rabbitmq_peer_discovery_consul.schema](url)
