### ISSUE TITLE
"/metrics" endpoint went down with "strconv.ParseFloat: parsing "unknown": invalid syntax" error

### ISSUE THREAD

**Issue by Arun-N** [rabbitmq/rabbitmq-server#5142]
## Describe the bug
RabbitMQ-Overview Grafana dashboard was showing no data today. When I checked the targets on Prometheus, http://10.2.0.74:15692/metrics endpoint was **down** (see screenshot below) 

## To Reproduce
Steps to reproduce the behavior: No steps.

**Expected behavior**
http://10.2.0.74:15692/metrics endpoint should be **up**

## Screenshots
<img width="1776" alt="image" src="https://user-images.githubusercontent.com/20704424/176991500-a5435361-c8af-405c-8726-a3315e568415.png">

## Version and environment information
- RabbitMQ: 3.10.2-management
- RabbitMQ Cluster Operator: 1.14.0
- Kubernetes: 1.23
- Cloud provider: Linode (LKE)
 
## Additional context
- Everything was working fine yesterday.
- http://10.2.0.74:15692/metrics/detailed endpoint is working fine (1/1 up). Only http://10.2.0.74:15692/metrics is down

**Comment by mkuratczyk** [comment]
Seems like some metric returned `undefined` as the value (which should be a float number). Can you `curl 10.2.0.74:15672/metrics` and share the result with us, so that we know which metric that is?

**Comment by michaelklishin** [comment]
`strconv.ParseFloat: parsing "unknown"` is a message from a C# client of sorts, not RabbitMQ. Clients should be ready to handle `undefined` values.
