### ISSUE TITLE
Incompatible erlang-nox with new rabbitmq-server 3.6.0

### ISSUE THREAD

**Issue by tasmaniski** [rabbitmq/rabbitmq-server#515]
Hello, 

Using Install documentation  http://www.rabbitmq.com/install-debian.html 
I made install script which works on Vagrant box hashicorp/precise32 
(A standard Ubuntu 12.04 LTS 32-bit box). 

After today release (3.6.0) the installation doesn't work due to incompatible version with **erlang-nox**. 

```
$ sudo apt-get install rabbitmq-server
...
The following packages have unmet dependencies:
 rabbitmq-server : Depends: erlang-nox (>= 1:16.b.3) but 1:14.b.4-dfsg-1ubuntu1 is to be installed or
                            esl-erlang but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by michaelklishin** [comment]
Please ask questions on rabbitmq-users. This is not a RabbitMQ issue by any means. If you intend to use Ubuntu 12.04, you need to make sure you have a way to provision [the minimum required Erlang version](http://www.rabbitmq.com/which-erlang.html). Or use an older release of RabbitMQ.

**Comment by michaelklishin** [comment]
In case the error message (coming from apt, not RabbitMQ) isn't clear: the minimum required version is R16B03, your Ubuntu release only has R14B04. Erlang Solutions provides [most recent version of Erlang](https://www.erlang-solutions.com/resources/download.html) for a bunch of OSes. Chances are their Debian packages supports Ubuntu 12.04 (it certainly works fine on older releases).

**Comment by tasmaniski** [comment]
Yes, it was clear.. With older version RabbitMQ (3.5.7) works fine (as before release) so I removed 
```deb http://www.rabbitmq.com/debian/ testing main``` 
in exchange for hard-coded version of .deb package.

**Comment by michaelklishin** [comment]
@tasmaniski we've made it pretty clear in release notes for 3.6.0 that it now requires a newer Erlang version.

**Comment by tasmaniski** [comment]
Yeah, sure.. I solved a problem immediately, before post it here. 
I just wanted to point out for others folks that default "installation guide" doesn't works anymore.  
Probably that should be part of some other issue board, sorry on that, my mistake :)

**Comment by rodvela** [comment]
Hello tasmaniski how did you installed an older version of RabbitMQ?

Thanks

**Comment by tasmaniski** [comment]
Yap sure. My install shell script is:

**Install Erlang**
cd /tmp/
wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
sudo dpkg -i erlang-solutions_1.0_all.deb
sudo apt-get update -y
sudo apt-get install erlang -y


**Install RabbitMQ from source**
cd /tmp/
echo 'echo "deb http://www.rabbitmq.com/debian/ testing main" >> /etc/apt/sources.list' | sudo -s
wget https://www.rabbitmq.com/rabbitmq-signing-key-public.asc
sudo apt-key add rabbitmq-signing-key-public.asc
sudo apt-get update -y
sudo apt-get install rabbitmq-server -y

**Comment by michaelklishin** [comment]
@tasmaniski minor nitpick: this is not installing RabbitMQ from source. You install a binary Debian package.

@rodvela's question was answered in https://groups.google.com/forum/#!topic/rabbitmq-users/GDpuD8NQkFY.
