### ISSUE TITLE
OAuth 2.0 authentication and authorisation

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#517]
To integrate OAuth 2.0 rabbitmq need to support access control by authorisation tokens. 
Token should be used to authenticate with RabbitMQ (like username and password) and should be associated with some access scope, which in rabbitmq case is vhost and resource permissions.
Most obvious way to provide token on connect is use it as username when connecting to rabbitmq.
There are several ways to check validity and permissions of this token later.
- `rabbitmq_auth_backend_http` can be used to check token using http access point on authorisation server. In this case rabbitmq does not need to know anything about scopes and expiry of token, but authorisation server have to implement handlers to respond to http backend, described [here](https://github.com/rabbitmq/rabbitmq-auth-backend-http)
- some kind of permission table can be used to store association between access token and scope permissions. Maybe `rabbitmq_auth_backend_internal` can be used. But rabbitmq should be aware of expiry, refreshing and association between OAuth scope and internal permissions. Also authorisation server should send information about new tokens and their scopes to rabbitmq some way.

**Comment by michaelklishin** [comment]
There are several decisions we need to make as part of this. First of all, what Authorisation Grant types do we care about? `implicit` is going to be quite common for e.g. Web apps. We also need to integrate with Cloud Foundry's UAA server. Which leads to another decision: should we support external authorisation servers, provide or own, or both? Certainly the former (to integrate with UAA) but likely
also the latter, to make sure a basic server is available without deploying external services.

All that has to fit with existing features (e.g. authentication and authorisation backends are pluggable) and future features such as #505. So it's easy to underestimate the scope.

**Comment by hairyhum** [comment]
Authorisation server can be plugin as well, and we can implement some specific endpoints to communicate with rabbitmq authorization backend plugin. I think there should be two plugins: one is auth backend and another is authorisation server. If users want to use their own authorisation server - they can use backend only.

**Comment by hairyhum** [comment]
Current progress is here https://github.com/rabbitmq/rabbitmq_auth_backend_oauth
