### ISSUE TITLE
Auto-forward of messages on federation

### ISSUE THREAD

**Issue by mohammednaseef** [rabbitmq/rabbitmq-server#519]
Refer https://groups.google.com/d/topic/rabbitmq-users/GRx30aYGzYo/discussion.

It would be nice to have an auto-forward functionality for he federation plugin for messages from downstream to upstream (presently the same happens only for bindings).

**Comment by michaelklishin** [comment]
Can you be more specific? Exchange federation replicates messages, while queue federation moves them as needed (for better data locality). What exactly isn't covered?

**Comment by mohammednaseef** [comment]
As mentioned in the rabbitmq group,

Can an auto-forward functionality be added to the federation plugin for messages from downstream to upstream (presently the same happens only for bindings).

This would be useful if we want to use federation for logical distribution of nodes. 

eg, Exchange EMaster can be federated into ESlave1 and ESlave2. All requests sent to ESlave1 & ESlave2 should be forwarded automatically to EMaster, whereas responses received by EMaster should be sent only to the corresponding slaves based on their subscription.

In exchange federation, presently only bindings are forwarded from downstream to upstream. Can the same be done for messages also.

**Comment by michaelklishin** [comment]
So you want two-way exchange federation. You already can set it up today. We'll consider this at a future point.

**Comment by michaelklishin** [comment]
Closing as this does not belong to this repo (and we haven't decided how useful this feature would be).
