### ISSUE TITLE
Error when using min-masters Queue Master Location via Policy

### ISSUE THREAD

**Issue by vikinghawk** [rabbitmq/rabbitmq-server#521]
Details and reproducible code at: https://groups.google.com/forum/#!topic/rabbitmq-users/4c0KtDNQis0

**Comment by michaelklishin** [comment]
@vikinghawk just to clarify: your system had at least one exchange-to-exchange binding, correct? I think we have a fix merged thanks to @Ayanda-D, can produce a one-off server build for you to verify :)

**Comment by vikinghawk** [comment]
Yep there would have been a topic exchange to header exchange binding on the system. If you can get me a rpm build I can test it. Thanks!

**Comment by michaelklishin** [comment]
@vikinghawk can you contact me at `michael` in RabbitMQ domain so I know where to send the file/link?

**Comment by vikinghawk** [comment]
Did you mean michael@rabbitmq.com?

**Comment by michaelklishin** [comment]
Yes.

**Comment by michaelklishin** [comment]
tarball sent.
