### ISSUE TITLE
Import Khepri-related preparation work

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#5214]
@dcorbacho and I have several changes in our respective branches that could go into `master` and then a RabbitMQ release way before we start to import Khepri bits. This would make the review of Khepri much much easier.

This would be mostly a reorganization of the code, no functional changes.

Consider this a "meta-issue" to track all changes we would like to import into `master`.

**Comment by the-mikedavis** [comment]
I believe this preliminary work was merged in https://github.com/rabbitmq/rabbitmq-server/pull/6430 released in 3.12.x
