### ISSUE TITLE
RabbitMQ 3.6.0 and IE 11 - Login Broken

### ISSUE THREAD

**Issue by Michael-Ekkert** [rabbitmq/rabbitmq-server#522]
Hi,

I upgraded one of our QA clusters yesterday and found that I am no longer able to login to RabbitMQ when using IE 11 (even with KB3008923 applied).  I do not have issues with the prior RabbitMQ 3.5.3 installation.  I have also attempted to force compatibility view to see if it helped; it didn't.

When I bring up the developer console in IE, I can see an error in main.js:
HTML1527: DOCTYPE expected. Consider adding a valid HTML5 doctype: "<!DOCTYPE html>".
File: svcsmsg.internal.local:15672, Line: 1, Column: 1
SCRIPT1004: Expected ';'
File: main.js, Line: 1068, Column: 32

Thanks,
Mike E.

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users. Sounds like a blank page is served.

**Comment by Michael-Ekkert** [comment]
Hi Michael,

Why would this be closed when it’s a rendering defect in RabbitMQ 2.6.0 when used with IE 11..

The page shows all of the JS as shown below but displays as a blank page..

[cid:image001.png@01D14264.2093B950]

**Comment by michaelklishin** [comment]
There is no evidence that it is a RabbitMQ issue. We do not use issues for discussions. See what markup is returned and what JS errors there may be. Management is easily the most popular plugin, this issue hasn't been reported to date.

**Comment by Michael-Ekkert** [comment]
I included the error that was rendered from main.js.  This issue came up once I upgraded to 3.6.0 and not in the prior release that I upgraded from..  The below is what is returned when requesting the login page:

<html>
  <head>
    <title>RabbitMQ Management</title>
    <script src="js/ejs.min.js" type="text/javascript"></script>
    <script src="js/jquery-1.6.4.min.js" type="text/javascript"></script>
    <script src="js/jquery.flot.min.js" type="text/javascript"></script>
    <script src="js/jquery.flot.time.min.js" type="text/javascript"></script>
    <script src="js/sammy-0.6.0.min.js" type="text/javascript"></script>
    <script src="js/json2.js" type="text/javascript"></script>
    <script src="js/base64.js" type="text/javascript"></script>
    <script src="js/global.js" type="text/javascript"></script>
    <script src="js/main.js" type="text/javascript"></script>
    <script src="js/prefs.js" type="text/javascript"></script>
    <script src="js/help.js" type="text/javascript"></script>
    <script src="js/formatters.js" type="text/javascript"></script>
    <script src="js/charts.js" type="text/javascript"></script>

    <link href="css/main.css" rel="stylesheet" type="text/css"/>
    <link href="favicon.ico" rel="shortcut icon" type="image/x-icon"/>


  </head>
  <body>
    <div id="outer"></div>
    <div id="debug"></div>
    <div id="scratch"></div>
  </body>
</html>


The error presented in the console of IE developer tools is:
SCRIPT1004: Expected ';'
File: main.js, Line: 1068, Column: 32

**Comment by michaelklishin** [comment]
@Michael-Ekkert moved to https://github.com/rabbitmq/rabbitmq-management/issues/98.

**Comment by beermattuk** [comment]
I'm also having this issue.  What exacerbates the problem is by default RabbitMQ only accepts logins from localhost, so I can't even log into it from another machine with a different browser.  I don't want to have to install a 3rd party browser on the server.  This needs re-opening!

**Comment by michaelklishin** [comment]
@beermattuk this was moved to https://github.com/rabbitmq/rabbitmq-management/issues/98 which was fixed for `3.6.1`.

**Comment by beermattuk** [comment]
Great thanks
