### ISSUE TITLE
Use more than 1 Ranch acceptor (and make the number configurable)

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#528]
See [this mailing list thread](https://groups.google.com/forum/#!topic/rabbitmq-users/xmC4erXqMJI).

I think `4` or `8` is a good default number.

**Comment by essen** [comment]
Depending on the machine the ideal number tends to be between 10 and 100. A default of 10 is probably fine, these processes don't tend to take much memory.

I know it is already configurable in some places (web stomp i think?) so I will check everywhere and make it an option where it is missing.

**Comment by michaelklishin** [comment]
10 or 16 sounds good.

**Comment by essen** [comment]
Ready for review.
