### ISSUE TITLE
disk_free_limit doesn't seem to support memory units as advertised

### ISSUE THREAD

**Issue by muikrad** [rabbitmq/rabbitmq-server#531]
I had success setting disk_free_limit to absolute numbers, but it doesn't seem to support memory units as advertised by the doc.

using {disk_free_limit, 100000000} will correctly show statistics on the overview page of the management plugin.

unfortunately, using {disk_free_limit, "10GB"} will show "(not available)" under the Disk Space element.

I'm not sure how I can test/validate these values outside of the management plugin; is this only a UI bug?

**Comment by michaelklishin** [comment]
It does so starting with 3.6.0.
