### ISSUE TITLE
Khepri: can't migrate users from Mnesia

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/rabbitmq-server#5341]
NOTE: this issue is related to an unreleased feature

1. `make run-broker` from `khepri-queues` branch
2. `rabbitmqctl add_user foo bar`
3. `rabbitmqctl enable_feature_flag raft_based_metadata_store_phase1`

Error:
```
Feature flags: failed to enable `raft_based_metadata_store_phase1`:
{error,
 {migration_failure,
  {function_clause,
   [{rabbit_auth_backend_internal,
     mnesia_write_to_khepri,
     [rabbit_user,
      [{internal_user,
        <<"foo">>,
        <<228,182, 96,166, 241,119, 139,140, 198,41, 245,178, 136,64, 208,66, 16,113, 246,68, 225,225, 152,249, 95,211, 205,4, 63,216, 208,150, 19,170, 142,114>>,
        [],
        rabbit_password_hashing_sha256,
        #{}},
       {internal_user,
        <<"guest">>,
        <<113,1, 161,100, 237,242, 140,39, 151,180, 25,205, 190,156, 229,69, 105,125, 145,79, 128,200, 123,166, 215,144, 213,90, 75,239, 196,152, 234,127, 150,26>>,
        [administrator],
        rabbit_password_hashing_sha256,
        #{}}],
      #{}],
     [{file, "rabbit_auth_backend_internal.erl"}, {line, 1681}]},
    {rabbit_core_ff, do_copy_from_mnesia_to_khepri, 6,
     [{file, "rabbit_core_ff.erl"}, {line, 497}]},
    {rabbit_core_ff, copy_from_mnesia_to_khepri, 2,
     [{file, "rabbit_core_ff.erl"}, {line, 460}]},
    {rabbit_core_ff, migrate_tables_to_khepri_run, 2,
     [{file, "rabbit_core_ff.erl"}, {line, 409}]}]}}}
```

Notes:
1. it's strange because it works for the default `guest` user (if I don't add the `foo` user)
2. If I enable the feature flag first and then add/import users, everything works just fine.

**Comment by dcorbacho** [comment]
This was broken when the batching was introduced. The code was updated to receive a list with one element to migrate, as a first step to the batching. It should have been extended to support a list of any size once the batching was ready as it happened with everything on `rabbit_store`. It was an oversight on my part, as the khepri integration is still split in two phases.

**Comment by dcorbacho** [comment]
Solved in https://github.com/rabbitmq/rabbitmq-server/commit/eb07b4b9b8ce34ac0759f5295b11380c027c5543
