### ISSUE TITLE
Improve cluster synchronization when adding a new node

### ISSUE THREAD

**Issue by noahhaon** [rabbitmq/rabbitmq-server#536]
Apologies if this is the wrong venue, but this has been an ongoing operational issue for us with large RMQ clusters.  

When adding a new node on a cluster with many dozen queues and thousands of bindings, the new nodes get stuck in "rebuilding indices from scratch" for quite some time (hours in some cases) with no progress indicator.  This happens after autoclustering, with no queues assigned to the new node by policy, or otherwise.  

An improvement would be to add support for batch synchronization of configuration information (or whatever it is synching, the logging is vague here) and improve the logging to give some sort of indication of progress.

**Comment by michaelklishin** [comment]
Batch sync is available in 3.6. Building indices has little to do with that, however.

**Comment by noahhaon** [comment]
Great - but what is being indexed on an brand new node that has no queues?  Seems like it is synching something with the rest of the cluster but it is unclear exactly what, and it takes hours to do.

**Comment by michaelklishin** [comment]
No need to guess: is there a lot of CPU and some disk activity going? Or a constant stream of network I/O (not necessarily very high) the entire time?

See [rabbit.mirror_sync_batch_size](https://github.com/rabbitmq/rabbitmq-server/blob/master/docs/rabbitmq.config.example#L258) and lets continue this on rabbitmq-users as there's currently no specifics to work with.

**Comment by noahhaon** [comment]
@michaelklishin Hi, no there are no publishers, no messages.  The cluster is entirely quiescent.

**Comment by noahhaon** [comment]
will take this to rmq users ...
