### ISSUE TITLE
3.11: definition import ignores virtual hosts' default queue type setting

### ISSUE THREAD

**Issue by ikvmw** [rabbitmq/rabbitmq-server#5399]
This is in follow-up to #5305. As reported by @adamcasey in https://github.com/rabbitmq/rabbitmq-server/pull/5330#discussion_r932081302:

---
I do think `rabbitmqctl import_definitions` isn't picking this setting up

1. Create vhost-def.json containing `{"vhosts":[{"limits":[],"metadata":{"default_queue_type":"quorum","description":"","tags":[]},"name":"manual-dqt-test"}]}`
    1. Worth noting `export_definitions` does give this output
3. `rabbitmqctl import_definitions vhost-def.json`
4. `rabbitmqctl ctl list_vhosts name,default_queue_type` shows all vhosts as default queue type undefined and client-declared queues default to classic

The export / import behaviour here is a little tricky besides this though - imo the perfect outcome would be all queues were declared on import as though the client had re-sent the queue.declare method. I suspect this would require storing what the `x-queue-type` declaration property was alongside the default queue type though.

**Comment by michaelklishin** [comment]
Boot time imports were not updated either.

All initial work was done on client operations because that's what the user who needs it at massive scale described.

**Comment by ikvmw** [comment]
@michaelklishin shall I continue with boot time imports?

**Comment by michaelklishin** [comment]
@ikvmw sure

**Comment by ikvmw** [comment]
It looks like boot time imports work now too.

**Comment by michaelklishin** [comment]
Somewhat related https://github.com/michaelklishin/rabbitmq-3.13-dqt-bug-reproduction.
