### ISSUE TITLE
Ensure supervisors use bounded timeouts

### ISSUE THREAD

**Issue by dcorbacho** [rabbitmq/rabbitmq-server#541]
We currently use in most, if not all, of the supervisors an almost infinity timeout (16#ffffffff == 4294967295 ms == 1193 hours). From the operations perspective this is not great, but we could probably work with a timeout of 30s in most of the cases.

The supervisors across nodes need special care, where the timeout must be at least `kernel.net_ticktime`. Local supervisors should never block node shutdown, such as resource monitors. 

Derives from https://github.com/rabbitmq/rabbitmq-federation/issues/7

**Comment by hairyhum** [comment]
Supervisors shutdown set to `infinity`, all workers shutdown set to `30000` by default.
@dcorbacho can you please clarify what "supervisors across nodes" are in this context?

**Comment by dcorbacho** [comment]
I recall discussing this ticket with @michaelklishin, but I am not sure about that part. I guess that it refers to mirrored supervisors, as supervising workers in another nodes is not a common OTP pattern (not fully supported either, if the node is down the supervisor wouldn't know what to do).

**Comment by michaelklishin** [comment]
@dcorbacho @hairyhum we certainly can introduce another constant, `DISTRIBUTED_SUPERVISOR_WAIT`, and make it 70s by default (`kernel.net_ticktime` default + 10s). However, ideally we should make these values configurable.
