### ISSUE TITLE
Spike: per-queue and per-consumer delivery acknowledgement timeout

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#5437]
I won't recite the discussion in #4099 but there's some interest on our team in making [consumer delivery acknowledgement timeout](https://www.rabbitmq.com/consumers.html#acknowledgement-timeout) configurable per virtual host, queue or consumer, and not just globally.

Starting with 3.11, virtual host metadata is a pre-enabled feature flag, so there is interest in using it more.

This may bring us closer to taking the setting from the optional queue arguments, if any, but this is not in scope for the spike.

Suggested duration: no more than two full days.

**Comment by ikvmw** [comment]
@michaelklishin are you on it? I'm happy to take care of this

**Comment by michaelklishin** [comment]
@ikvmw go ahead.

**Comment by ikvmw** [comment]
As per slack discussion:
- won't do per-vhost;
- will do per queue (like with dead lettering x- and policy)
- will do per consumer.

Precedence Per consumer, per queue, global.
