### ISSUE TITLE
rabbitmq_global_publishers & rabbitmq_global_consumers fail to handle unclean client termination

### ISSUE THREAD

**Issue by coro** [rabbitmq/rabbitmq-server#5462]
## Overview

When a client terminates uncleanly, the global counters for publishers and consumers do not handle this gracefully.

For the consumer metric, the value of the gauge does not decrease after the termination, and so the value ever-increases.
For the publisher metric, the value of the gauge decreases below zero and does not recover, leading to a ever-decreasing negative value on the gauge.

Note that the non-global equivalent of these metrics are **unaffected** by this behaviour, and the metrics reported match my expectation (oscillating between 0 and 1).

I discovered this by using a script which ran `while true; do bin/runjava com.rabbitmq.perf.PerfTest --time 60; sleep 10; done`.

## Repro (with observability stack to spot this)

On k8s, assuming you have the `kubectl rabbitmq` plugin [installed](https://www.rabbitmq.com/kubernetes/operator/kubectl-plugin.html#install):

```bash
# Install Cluster Operator & observability stack
kubectl rabbitmq install-cluster-operator
curl -L https://raw.githubusercontent.com/rabbitmq/cluster-operator/main/observability/quickstart.sh | bash

# Create RabbitmqCluster and perf-test Pod
kubectl rabbitmq create sample --image rabbitmq:3.10-management --replicas 3
kubectl wait --for=condition=AllReplicasReady=true rmq/sample
kubectl rabbitmq perf-test sample --time 20
kubectl -n kube-prometheus port-forward svc/prom-kube-prometheus-stack-prometheus 9090
```
Then navigate to the [prometheus service](http://localhost:9090/graph?g0.expr=sum(rabbitmq_global_consumers)&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=15m&g1.expr=sum(rabbitmq_global_publishers)&g1.tab=0&g1.stacked=0&g1.show_exemplars=0&g1.range_input=15m), and you will see that the values either increase over time with every restart of the perf-test Pod (for `rabbitmq_global_consumers`) or decrease below zero over time (for `rabbitmq_global_publishers`).
<img width="1761" alt="Screenshot 2022-08-08 at 17 34 09" src="https://user-images.githubusercontent.com/23215294/183468050-ca283a67-1038-40c1-806f-56cb38a27293.png">
<img width="1756" alt="Screenshot 2022-08-08 at 17 34 22" src="https://user-images.githubusercontent.com/23215294/183468060-3de08c20-cd43-48e4-9b6e-cf0f44958fb4.png">
You will see that the metrics continue to deviate from 0. Note that the exponential back off due to the PerfTest Pod timing out after 20s will cause the time between 'steps' to increase over time.

See also that the non-global equivalents of these metrics are unaffected:
![Screenshot 2022-08-08 at 17 43 48](https://user-images.githubusercontent.com/23215294/183469892-fa529c0b-ffbc-429d-bf3a-488096c39183.png)
![Screenshot 2022-08-08 at 17 44 18](https://user-images.githubusercontent.com/23215294/183469897-ba326509-1b7d-4520-a30a-12573bfb1d46.png)

## Additional info

Reproduced on both k8s and docker-compose environments, all with perf-test.
Affects RabbitMQ 3.9.x and 3.10.x.

**Comment by coro** [comment]
Here is a bit of a clearer pattern without the exponential backoff in k8s:

![Screenshot 2022-08-08 at 15 25 23](https://user-images.githubusercontent.com/23215294/183470380-73246932-8a57-442b-90f0-786b77275578.png)

**Comment by kjnilsson** [comment]
It looks like for publishers the delete happens for `publishing_mode=false` and not `true` as one would expect:

https://github.com/rabbitmq/rabbitmq-server/blob/fdad0e99b199c1d936dba0cc023f0f0c7e8379db/deps/rabbit/src/rabbit_channel.erl#L2908-L2911


For consumers we don't decrease in `terminate/2` at all which is why that is ever increasing.
