### ISSUE TITLE
Use a more user-friendly format for configuration file

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#550]
E.g. using YAML is going to be a lot more user-friendly plus easier to generate for tools such as Chef and Puppet.

This is a long standing idea previously discussed with @videlalvaro and @dumbbell.

Why YAML and not JSON? A few reasons:

 * JSON doesn't allow comments
 * YAML works quite well for Cassandra and ElasticSearch
 * @dumbbell maintains an Erlang YAML parser/generator

Alternatively we can consider using [Cuttlefish](https://github.com/basho/cuttlefish), which is used by Riak.

Things to keep in mind: how Cuttlefish's config file generation approach might work with our current way of configuring a `.config` file path; how this can affect upgrades.

**Comment by michaelklishin** [comment]
See https://github.com/rabbitmq/rabbitmq-server/issues/551 for preliminary discussion of Cuttlefish, their approach and how the sysctl format deals with collections.

@hairyhum lets continue here.

**Comment by hairyhum** [comment]
Here is `cuttlefish` schema and example config for this schema.
https://gist.github.com/hairyhum/a73c30672acc55125643

There are `rabbitmq.example.config` parts in comments with examples and docs in both files above each setting.
There should be more validations to check config values and maybe some other mappings.

You can run `cuttlefish` escript with this files to generate `rabbitmq.config`.

**Comment by hairyhum** [comment]
`cuttlefish` has support for `bytesize` datatype https://github.com/basho/cuttlefish/wiki/Datatypes#bytesize which correlates with #448 
@dumbbell, @michaelklishin, do you think we should use our (more flexible) format or cuttlefish `bytesize` and get rid of parsing code?

**Comment by michaelklishin** [comment]
We can't break existing configuration files that use our values. It's not a lot of code and I think our format works OK. I'd keep it.

**Comment by michaelklishin** [comment]
The above comment raises a couple of questions:

 * Given we will be introducing a new config format, how can we support existing configs? That would be highly desirable.
 * For the new format, how many breaking changes can we tolerate, given that this will ship in Q4 2016, so even relatively new features such as byte size formats will be used in a lot more installations.

The former question is much more important and if we can do it, it will largely take care of the latter.

Another question: if `rabbitmq.config` is an "advanced" pure Erlang config, what should the sysctl version be (should we go with that over YAML)? `rabbitmq.conf` will be an awful lot similar to `rabbitmq-env.conf` to some. On the other hand, we used to see people name the config `rabbitmq.conf`, so maybe the `-env` part is, in fact, a good differentiator? Just something to think about.

**Comment by hairyhum** [comment]
`cuttlefish` supports `translators`, which can transform config values to any erlang term, so it will be no breaking changes at all, since we generate exactly same config.

We will include cuttlefish in our shell scripts anyway so there are two options:
1. If there is any `.config` file - use it as is, otherwise - generate it from `.conf` and `.schema`
2. Generate always. Use `.config` file as `additional` config to merge with generation result

I will post more comments about collections and possible use of YAML, when finish with current config .

**Comment by michaelklishin** [comment]
If we can things backwards compatible and Cuttlefish has a data type which is effectively what we reinvented, I think we should use Cuttlefish with a backwards-compatible translation function.

**Comment by michaelklishin** [comment]
Per discussion with @hairyhum and @dumbbell, we're going to proceed with sysctl format/Cuttlefish over YAML with forked Cuttlefish.

**Comment by dumbbell** [comment]
Cuttlefish's syntax looks simple and straightforward, I like it.

**Comment by michaelklishin** [comment]
We've found an interesting problem with this branch: https://github.com/rabbitmq/rabbitmq-server/issues/649 :) The history repeats itself. `rabbitmq.conf` was once used to set environment variables, and later became `rabbitmq-env.conf`. So we need to eliminate all warnings related to that change as part of this branch.

**Comment by michaelklishin** [comment]
Merged. We will be refining the config syntax in the upcoming months, so if you have feedback on it, please post it to rabbitmq-users or here.

Great job, @hairyhum.

**Comment by michaelklishin** [comment]
One follow-up issue discovered recently: https://github.com/rabbitmq/rabbitmq-server/issues/987.
