### ISSUE TITLE
Scripts should verify presence of mandatory environment variables

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#553]
Related to this [mailing list thread](https://groups.google.com/forum/#!topic/rabbitmq-users/1OgdpOgsLdc)

Some variables required by start script are being set from defaults if empty. But if defaults are empty as well - there are no checks and validations. So `erl` process can fail with unrelated exception. 

Maybe there should be validation of required variables just before running `erl` and reporting to user?

**Comment by michaelklishin** [comment]
That's a good idea. Can get pretty hairy — thanks, shell script! — as well.

**Comment by Gsantomaggio** [comment]
Fixed by https://github.com/rabbitmq/rabbitmq-server/pull/674
