### ISSUE TITLE
khepri: metadata sync mail crash a vhost

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/rabbitmq-server#5532]
```
bazel run start-cluster
rabbitmqctl -n rabbit-0 enable_feature_flag raft_based_metadata_store_phase1
rabbitmqctl -n rabbit-0 stop_app

# this part may need to be adjusted based on how powerful a given environment is; the idea is to have a lot of metadata to sync
rabbitmqctl -n rabbit-1 import_definitions ~/sample-configs/topic-bindings/q0-with-100k-topic-bindings.json
rabbitmqctl -n rabbit-1 import_definitions ~/sample-configs/topic-bindings/q1-with-100k-topic-bindings.json
rabbitmqctl -n rabbit-1 import_definitions ~/sample-configs/topic-bindings/q2-with-100k-topic-bindings.json
rabbitmqctl -n rabbit-1 import_definitions ~/sample-configs/topic-bindings/q3-with-100k-topic-bindings.json
rabbitmqctl -n rabbit-1 import_definitions ~/sample-configs/topic-bindings/q4-with-100k-topic-bindings.json
rabbitmqctl -n rabbit-1 import_definitions ~/sample-configs/topic-bindings/q5-with-100k-topic-bindings.json

# at this point everything seems to work as expected, however
rabbitmqctl -n rabbit-0 start_app

rabbitmqctl -n rabbit-0 list_vhosts name cluster_state
Listing vhosts ...
name    cluster_state
/       [{'rabbit-1@kura', stopped}, {'rabbit-2@kura', stopped}, {'rabbit-0@kura', stopped}]
```

The vhost is now down and `rabbitmqctl restart_vhost --vhost /` doesn't help.

[rabbit-0@kura.log](https://github.com/rabbitmq/rabbitmq-server/files/9352218/rabbit-0%40kura.log)
[rabbit-1@kura.log](https://github.com/rabbitmq/rabbitmq-server/files/9352219/rabbit-1%40kura.log)
[rabbit-2@kura.log](https://github.com/rabbitmq/rabbitmq-server/files/9352220/rabbit-2%40kura.log)

**Comment by mkuratczyk** [comment]
This particular scenario now works. I wonder if there is a higher-level problem though. Whatever timeout we set, it could happen that it gets exceeded. The fact that a node startup can cause a vhost failure feels wrong...

**Comment by mkuratczyk** [comment]
It might be a problem that requires a different solution but I just stopped 2 out of the 3 nodes and when I started them, the vhost is down (10 minutes later), so the longer timeout helps, but we may need more than that:
```
name    cluster_state
/       [{'rabbit-1@kura', stopped}, {'rabbit-0@kura', running}, {'rabbit-2@kura', stopped}]
```

**Comment by mkuratczyk** [comment]
I can reproduce this 2-nodes down scenario even with an empty metadata_store. Perhaps we should consider this a separate issue? It seems like it can't recover from a "partition":

```
rabbitmqctl -n rabbit-0 enable_feature_flag raft_based_metadata_store_phase1
rabbitmqctl -n rabbit-0 stop_app
rabbitmqctl -n rabbit-1 stop_app

rabbitmqctl -n rabbit-0 start_app
rabbitmqctl -n rabbit-1 start_app

# the / vhost is down but should be up
```

**Comment by dcorbacho** [comment]
> This particular scenario now works. I wonder if there is a higher-level problem though. Whatever timeout we set, it could happen that it gets exceeded. The fact that a node startup can cause a vhost failure feels wrong...

I thought about this timeout issue many times before, operations can timeout anywhere and for multiple reasons, and I believe we have to do two things:
1. Increase default timeout as we did here, not sure if 30s is still the right value
2. Set an infinity value to operations like recovery and maybe a few others.

**Comment by dcorbacho** [comment]
> I can reproduce this 2-nodes down scenario even with an empty metadata_store. Perhaps we should consider this a separate issue? It seems like it can't recover from a "partition":
> 
> ```
> rabbitmqctl -n rabbit-0 enable_feature_flag raft_based_metadata_store_phase1
> rabbitmqctl -n rabbit-0 stop_app
> rabbitmqctl -n rabbit-1 stop_app
> 
> rabbitmqctl -n rabbit-0 start_app
> rabbitmqctl -n rabbit-1 start_app
> 
> # the / vhost is down but should be up
> ```

I haven't tested anything like this before, but I'll have a look. Probably a different issue as you said? Not sure

**Comment by dcorbacho** [comment]
Vhost and bindings recovery now hangs forever until Khepri replies, see https://github.com/rabbitmq/rabbitmq-server/commit/533a26c3b5ce8c8c5780c4d2d0628c6ef4080c8d

@mkuratczyk could you please test it again? We might have to extend the timeout on more operations, but at the moment I just identified those as problematic

**Comment by mkuratczyk** [comment]
Thanks. Works for me now.
