### ISSUE TITLE
CloudFoundry UAA authorization plugin

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#555]
Cloud Foundry UAA server supports [endpoint](https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst#id32) to check access tokens.
So it is possible to implement lightweight authorization backend for RabbitMQ to work with UAA.
This plugin will decode `/check_token` data format and determine resource access from `scope`.
Main question is what scope format should be used to define RabbitMQ resource access.
Prototype is here: https://github.com/hairyhum/rabbitmq-auth-backend-uaa It doesn't yet implement scope to resource mapping and just returns `true` for all resources.

Related to #517 because also uses scopes

**Comment by michaelklishin** [comment]
Two things to consider:

 * Tokens can and in practice will come from the clients, e.g. Web clients, so implicit grants should be supported.
 * Tokens need renewals, e.g. Cloud Foundry Java client performs token renewals automatically.

**Comment by hairyhum** [comment]
This plugin won't worry about grants or renewals. UAA will deal with all of it. Plugin only connect user authorization to UAA with token from client.

**Comment by michaelklishin** [comment]
A [prototype is available and undergoing evaluation](https://github.com/rabbitmq/rabbitmq-auth-backend-uaa) (e.g. if the feature set offered makes sense).

**Comment by michaelklishin** [comment]
We have not one but two prototype plugins now plus a library that works with the JW* soup. There are still open ended questions around UAA and OAuth 2.0/OpenID Connection integration but this part is done.
