### ISSUE TITLE
Average time per "Seek" operation increasing all the time

### ISSUE THREAD

**Issue by firewave** [rabbitmq/rabbitmq-server#557]
https://groups.google.com/forum/#!topic/rabbitmq-users/Uuco79Yv0OA

Since this issue still persists I am opening an issue for this now. We are running 3.5.6 on Windows Server 2012 x64 and the server contains about 2 million messages. The average seek time is shown as  3,580 ms at the moment.

**Comment by michaelklishin** [comment]
Can you briefly describe your workload? E.g. median message rates, how many queues are used, etc (approximates are fine).

**Comment by firewave** [comment]
I made some screenshots - I hope those help.

last 10 minutes:
![mq_stats_10m](https://cloud.githubusercontent.com/assets/242857/12421915/a263e680-bec4-11e5-859b-930008d4e6c2.png)
![mq_queue_10m](https://cloud.githubusercontent.com/assets/242857/12422080/733bdf74-bec5-11e5-8a1c-6e88c77f6d47.png)

last hour:
![mq_stats_1h](https://cloud.githubusercontent.com/assets/242857/12421925/b4c6fc4a-bec4-11e5-9ac4-89bc6f047937.png)
![mq_queue_1h](https://cloud.githubusercontent.com/assets/242857/12422084/76aacc2e-bec5-11e5-9bde-8eb60d0db4ee.png)

last 8 hours:
![mq_stats_8h](https://cloud.githubusercontent.com/assets/242857/12421930/b792b1ee-bec4-11e5-9e0d-f6e8e64ec915.png)
![mq_queue_8h](https://cloud.githubusercontent.com/assets/242857/12422086/781ec9e8-bec5-11e5-8aff-d1445cb63b92.png)

The server gets about 150k messages every 3 minutes and processes them and the queue is always empty afterwards. But as you can see in the charts the seek times increase and persist even if there are no messages in the queue at all.
The values is back to two-digit milliseconds since I had to restart it because of a configuration change

Tell me if you need more or different data.

**Comment by firewave** [comment]
Since it doesn't seem to impact the performance at all no matter what the value says it appears to me that it might just be a display/calculation error.

**Comment by michaelklishin** [comment]
It can be; we need to reproduce to tell for sure ;)

**Comment by michaelklishin** [comment]
Thank you for the data.

**Comment by firewave** [comment]
Another screenshot that shows the increase and how it doesn't seems to affect the performance at all:

![mq_stats_1d](https://cloud.githubusercontent.com/assets/242857/12445191/2a9d1a46-bf63-11e5-81bf-7919b64a5460.png)

**Comment by dcorbacho** [comment]
I can reproduce this on my MacBook with PerfTest and rabbit 3.6.1. 
```
sh runjava.sh com.rabbitmq.examples.PerfTest -y25 -x 25 -u myqueue.test -f persistent -p
```
<img width="561" alt="screen shot 2016-03-02 at 16 26 48" src="https://cloud.githubusercontent.com/assets/646577/13467550/a8c68016-e096-11e5-9821-62719cbfdaad.png">

I'll investigate the issue.

**Comment by c-datculescu** [comment]
Hello. We are having this issue since months as well, but while seek operations are atm shown at around 4-6 seconds we do not see any degradation in service.

Would be cool to fix it though.

**Comment by dcorbacho** [comment]
All the `I/O average time per operation` times are miscalculated. The management agent performs the calculations of the averages and notifies them as such in the events, but the event collector treats them as any other simple metric and calculates rates per second instead. That also led to negative rates and samples.

I'm finalising the testing, but with the correction of the calculations the seek times seem stable under a constant load:

<img width="530" alt="screen shot 2016-03-07 at 22 20 43" src="https://cloud.githubusercontent.com/assets/646577/13595150/fbfc4bda-e500-11e5-9e41-c5dbb7c1bc99.png">

**Comment by dcorbacho** [comment]
After some further testing I improved the previous fix to provide instant rates in the samples (not accumulated), which are used to plot the graphics. In this way, we provide a view that truly reflects the current state of the system. The seek operation no longer increases, but keeps a global average of 0.09ms in my test (vs 4ms in the old implementation).

<img width="773" alt="screen shot 2016-03-08 at 17 58 14" src="https://cloud.githubusercontent.com/assets/646577/13629750/122a53e8-e5d3-11e5-8dc2-89f12ad207fb.png">
<img width="749" alt="screen shot 2016-03-08 at 17 58 20" src="https://cloud.githubusercontent.com/assets/646577/13629751/122df8c2-e5d3-11e5-84d2-56bc2d603e19.png">

<img width="778" alt="screen shot 2016-03-09 at 07 37 20" src="https://cloud.githubusercontent.com/assets/646577/13629735/fd543f92-e5d2-11e5-814f-42bf6654f916.png">
<img width="759" alt="screen shot 2016-03-09 at 07 37 27" src="https://cloud.githubusercontent.com/assets/646577/13629736/fd578184-e5d2-11e5-9662-09df0b9e6b89.png">

PRs https://github.com/rabbitmq/rabbitmq-management/pull/150 and https://github.com/rabbitmq/rabbitmq-management-agent/pull/13
