### ISSUE TITLE
Channel Interceptors should be enabled/disabled together with plugins

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-server#559]
When a plugin that provides an interceptor is disabled, then running channels should reflect the changes.

There could be a function similar to this one: https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_channel.erl#L334 that handles updating the channel state in order to remove the interceptor.

In a similar way, when enabling a plugin, then channels should be notified of new interceptors, if any.

**Comment by michaelklishin** [comment]
As part of this we need to update plugins that provider interceptors. For example, []() fails to activate with  https://github.com/rabbitmq/rabbitmq-server/pull/578 and https://github.com/rabbitmq/rabbitmq-common/pull/49 checked out.

**Comment by hairyhum** [comment]
@michaelklishin what do you mean by 'fails to activate'? I have been testing the feature using this plugin.

**Comment by michaelklishin** [comment]
I'm getting an `undef` when I `make run-broker` with `rabbitmq-server-559` checked out. I will give it another try.

**Comment by michaelklishin** [comment]
I confirm that with manual testing against `rabbitmq_message_timestamp`, disabling the plugin does have effect on newly opened channels, and so does re-enabling. However, test suites in `rabbitmq_test` and `rabbitmq_federation` fail.

**Comment by hairyhum** [comment]
I have set up clean umbrella clone, checked up `rabbit`, `rabbit_common`, `rabbitmq_test`, and `rabbitmq_federation`. Tests passed (except clustering management, which is unrelated).
