### ISSUE TITLE
RabbitMQ appears to start but doesn't in Windows 2012

### ISSUE THREAD

**Issue by randylcain** [rabbitmq/rabbitmq-server#561]
RabbitMQ appears to start but rabbitmqctl status says it isn't following installation with all defaults on a new clean server instance. rabbitmq-service remove and then rabbitmq-service install fixes the problem.

**Comment by michaelklishin** [comment]
Please ask questions on `rabbitmq-users`.

**Comment by michaelklishin** [comment]
You are not specifying *any* information that can be used to reproduce: neither RabbitMQ version nor any error messages. There's also a page on [Windows quirks](https://www.rabbitmq.com/windows-quirks.html).

**Comment by randylcain** [comment]
I'll investigate this more. It is repeatable but could be that the Windows installer is not completing the installation. I have 4 new servers with new 2012 installs that I will use for the testing. I have noticed that after the remove/install steps using the batch file have enabled proper operation, I am no longer seeing the problem, even after uninstalling and reinstalling both RabbitMQ and Erlang.
Erlang 18.2RabbitMQ 3.6Windows 2012 R2

Sent from Yahoo Mail on Android 
 
  On Tue, Jan 19, 2016 at 10:09 PM, Michael Klishin<notifications@github.com> wrote:   
Closed #561.
