### ISSUE TITLE
Extremely high latency difference between VM and barebone machine (factor of 40)

### ISSUE THREAD

**Issue by AVVS** [rabbitmq/rabbitmq-server#564]
Hi everyone, I'm at a loss here - have been experimenting with rabbitmq and stumbled across a weird issue, which I can't fix anyhow. 

If I run rabbitmq on my dev machine, without any virtualization, installed from brew with the default configuration and erlang VM args: `-W w -A 64 -P 1048576 -K true -B i -kernel inet_default_connect_options [{nodelay,true}]` by running a simple test:

1. pre-create queue (amqp.gen-* on '' direct exchange)
2. pre-create consumer on topic exchange, listen to route 'nice.consumer'

do the test for 1 / 100, etc messages:

1. publish message to 'nice.consumer' with appropriate correlationId and replyTo payload
2. receive message on the consumer
3. send message via direct exchange to `replyTo` with a given correlation id and extra payload
4. get latency

On a barebone machine I would see round-trip time of 0.75 to 1.5ms per message, but on any virtual machine - in the google cloud, virtualbox or in my colocation with KVM I would see 40ms per message.
Naggle is turned off as well, but either way it must not give a 40 times difference.

Complete ps aux | grep rabbitmq on barebone machine:

```
vitaly          45963   1.3  0.2  2608280  32964   ??  S    11:49am   1:22.51 /usr/local/Cellar/erlang/18.2.1/lib/erlang/erts-7.2.1/bin/beam.smp -W w -A 64 -P 1048576 -K true -B i -- -root /usr/local/Cellar/erlang/18.2.1/lib/erlang -progname erl -- -home /Users/vitaly -- -pa /usr/local/Cellar/rabbitmq/3.6.0/ebin -noshell -noinput -s rabbit boot -sname rabbit@localhost -boot /usr/local/opt/erlang/lib/erlang/bin/start_clean -config /usr/local/etc/rabbitmq/rabbitmq -kernel inet_default_connect_options [{nodelay,true}] -rabbit tcp_listeners [{"127.0.0.1",5672}] -sasl errlog_type error -sasl sasl_error_logger false -rabbit error_logger {file,"/usr/local/var/log/rabbitmq/rabbit@localhost.log"} -rabbit sasl_error_logger {file,"/usr/local/var/log/rabbitmq/rabbit@localhost-sasl.log"} -rabbit enabled_plugins_file "/usr/local/etc/rabbitmq/enabled_plugins" -rabbit plugins_dir "/usr/local/Cellar/rabbitmq/3.6.0/plugins" -rabbit plugins_expand_dir "/usr/local/var/lib/rabbitmq/mnesia/rabbit@localhost-plugins-expand" -os_mon start_cpu_sup false -os_mon start_disksup false -os_mon start_memsup false -mnesia dir "/usr/local/var/lib/rabbitmq/mnesia/rabbit@localhost" -kernel inet_dist_listen_min 25672 -kernel inet_dist_listen_max 25672
```

On VM (this one has an older erlang, but I've tried with 18.x too and hipe precompilation enabled - there was no difference):

```
rabbitmq  8638 15.0  2.6 1115104 49536 ?       Sl   10:45   0:00 /usr/lib/erlang/erts-5.10.4/bin/beam.smp -W w -A 6
4 -P 1048576 -K true -B i -- -root /usr/lib/erlang -progname erl -- -home /var/lib/rabbitmq -- -pa /usr/lib/rabbitm
q/lib/rabbitmq_server-3.6.0/ebin -noshell -noinput -s rabbit boot -sname rabbit@instance-1 -boot start_sasl -kernel
 inet_default_connect_options [{nodelay,true}] -sasl errlog_type error -sasl sasl_error_logger false -rabbit error_
logger {file,"/var/log/rabbitmq/rabbit@instance-1.log"} -rabbit sasl_error_logger {file,"/var/log/rabbitmq/rabbit@i
nstance-1-sasl.log"} -rabbit enabled_plugins_file "/etc/rabbitmq/enabled_plugins" -rabbit plugins_dir "/usr/lib/rab
bitmq/lib/rabbitmq_server-3.6.0/plugins" -rabbit plugins_expand_dir "/var/lib/rabbitmq/mnesia/rabbit@instance-1-plu
gins-expand" -os_mon start_cpu_sup false -os_mon start_disksup false -os_mon start_memsup false -mnesia dir "/var/l
ib/rabbitmq/mnesia/rabbit@instance-1" -kernel inet_dist_listen_min 25672 -kernel inet_dist_listen_max 25672
```

**Comment by AVVS** [comment]
Some ugly code, which was put on top of tests, but would be sufficient enough to reproduce it.
https://github.com/makeomatic/ms-amqp-transport/blob/tests/latency/test/amqp-transport.js#L66-L109

Requires node.js 5.x and npm 3.x to run

**Comment by michaelklishin** [comment]
Please ask questions on `rabbitmq-users`.
