### ISSUE TITLE
3.6.0 service fails to start properly on Windows 10 with Erlang 18.2.1

### ISSUE THREAD

**Issue by Fydon** [rabbitmq/rabbitmq-server#565]
I installed Erlang and RabbitMQ on a new Windows 10 Pro PC, so it didn't have any previous version of either software installed. The RabbitMQ service successfully starts, but running `rabbitmqctl.bat status` displays the following:

    attempted to contact: [rabbit@TDPC2]

    rabbit@TDPC2:
      * connected to epmd (port 4369) on TDPC2
      * epmd reports: node 'rabbit' not running at all
                      other nodes on TDPC2: ['RabbitMQ']
      * suggestion: start the node

    current node details:
    - node name: 'rabbitmq-cli-13480@TDPC2'
    - home dir: C:\Users\td
    - cookie hash: JiIMuMYi5u4Cs5kaaeJj5g==

running `.\rabbitmq-server.bat status` then displays the follow

                  RabbitMQ 3.6.0. Copyright (C) 2007-2015 Pivotal Software, Inc.
      ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
      ##  ##
      ##########  Logs: C:/Users/td/AppData/Roaming/RabbitMQ/log/rabbit@TDPC2.log
      ######  ##        C:/Users/td/AppData/Roaming/RabbitMQ/log/rabbit@TDPC2-sasl.log
      ##########
                  Starting broker... completed with 6 plugins.

At this point RabbitMQ works correctly. I then terminated the batch file and stopped the RabbitMQ service and ran `.\rabbitmq-server.bat status`, which displays the following:

    ERROR: epmd error for host Protocol: inet_tcp: register/listen error: econnrefused: nxdomain (non-existing domain)

This leave an instance of `epmd.exe` running in the background, so running `.\rabbitmq-server.bat status` again results in the broker starting again.

I tried creating a configuration file with debug logging, but nothing is written when the `econnrefused` error happens. Is there anything I can I do to provide more details?

**Comment by hairyhum** [comment]
Please post questions to `rabbitmq-users` google group.
Looks like you should check node name of rabbitmq server node (you can use `WMIC` to show processes command line args)
