### ISSUE TITLE
Lazy queues: a RAM duration of 0 causes the queue to be slow

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#569]
The `test_variable_queue_dynamic_duration_change()` test in `rabbit_tests.erl` is slower when lazy queues are used than when default queues are used. We talk about 4 minutes for the former versus 40 seconds for the latter, when the RAM duration is set to 0. The whole testsuite is also slower.

**Comment by lhoguin** [comment]
On main there are no lazy queues anymore and the queue no longer reduce memory use.
