### ISSUE TITLE
Can't publish via HTTP API with "Accept: application/json"

### ISSUE THREAD

**Issue by carlhoerberg** [rabbitmq/rabbitmq-server#57]
In RabbitMQ 3.4.2 if you publish a message via the http/mgmt api and set the Accept header to application/json if fails with 406. But if you set it to anything else it works.

```
curl -i -XPOST -u guest:guest http://localhost:15672/api/exchanges/%2f/amq.default/publish -H "Content-Type: application/json" -H "Accept: application/json" -d'{"properties":{},"routing_key":"a","payload":"b","payload_encoding":"string"}'
HTTP/1.1 406 Not Acceptable
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
Date: Sun, 01 Mar 2015 15:24:09 GMT
Content-Type: application/json
Content-Length: 58

{"error":"Not Acceptable","reason":"\"Not Acceptable\"\n"}
```

```
curl -i -XPOST -u guest:guest http://localhost:15672/api/exchanges/%2f/amq.default/publish -H "Content-Type: application/json" -H "Accept: */*" -d'{"properties":{},"routing_key":"a","payload":"b","payload_encoding":"string"}'

HTTP/1.1 200 OK
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
Date: Sun, 01 Mar 2015 15:25:12 GMT
content-type: application/json
Content-Length: 16
Cache-Control: no-cache

{"routed":false}
```

Also note how the casing of the response header "Content-Type" differ between the two requests.

**Comment by carlhoerberg** [comment]
Sorry, wrong project

**Comment by techmng** [comment]
Hi 
I am unable to post messages always seeing {routed:false} in response. Can someone help how I can post message using curl and then view it


[cloud-user@manojp-centos-7 rabbitmq]$ sudo curl -i -u guest:guest -H "content-type:application/json"  -XPOST -d '{"properties":{},"routing_key":"queue_test","payload":"message test","payload_encoding":"string"}' http://localhost:15672/api/exchanges/%2f/manoj_exchange/publish
HTTP/1.1 200 OK
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
Date: Tue, 15 Mar 2016 17:57:52 GMT
Content-Type: application/json
Content-Length: 16
Cache-Control: no-cache

{"routed":false}[cloud-user@manojp-centos-7 rabbitmq]$

**Comment by michaelklishin** [comment]
@techmng questions belong to rabbitmq-users. `"routed": false` simply means you message wasn't routed to any queue, not that there was an error of any kind.

**Comment by voicesoft** [comment]
> Hi
> I am unable to post messages always seeing {routed:false} in response. Can someone help how I can post message using curl and then view it
> 
> [cloud-user@manojp-centos-7 rabbitmq]$ sudo curl -i -u guest:guest -H "content-type:application/json" -XPOST -d '{"properties":{},"routing_key":"queue_test","payload":"message test","payload_encoding":"string"}' http://localhost:15672/api/exchanges/%2f/manoj_exchange/publish
> HTTP/1.1 200 OK
> Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
> Date: Tue, 15 Mar 2016 17:57:52 GMT
> Content-Type: application/json
> Content-Length: 16
> Cache-Control: no-cache
> 
> {"routed":false}[cloud-user@manojp-centos-7 rabbitmq]$

First your need to create topic/queue name

**Comment by tessa2003** [comment]
curl -i -u admin:admin -H "content-type:application/json" -XPOST -d '{"properties":{},"routing_key":"queue_test","payload":"message test","payload_encoding":"string"}' http://localhost:15672/api/exchanges/%2f/test/publish
HTTP/1.1 500 Internal Server Error
content-length: 0


I created routing_key = "queue_test" and queue_name= "queue_test" before
But I received error

**Comment by michaelklishin** [comment]
Please post your questions to the mailing list and provide server logs and RabbitMQ version information. We cannot suggest anything from a single HTTP response line.
