### ISSUE TITLE
3.6.0 source tarball from website is missing some files

### ISSUE THREAD

**Issue by binarin** [rabbitmq/rabbitmq-server#576]
When trying to build deb-package from source tarball by calling `make package-deb`, I get the following error:

```
 GEN    /home/binarin/tmp/rabbitmq-server-3.6.0/PACKAGES/rabbitmq-server-3.6.0
cat: packaging/common/LICENSE.head: No such file or directory
Makefile:251: recipe for target '/home/binarin/tmp/rabbitmq-server-3.6.0/PACKAGES/rabbitmq-server-3.6.0' failed
```

After copying `packaging` directory from git checkout of rabbitmq, deb-package builds successfully.

**Comment by michaelklishin** [comment]
Is this still relevant with `3.6.6`?

**Comment by binarin** [comment]
Yes, there is still the same error. But not sure if it worth fixing.

My expectation was that release source tarball is a full equivalent of `rabbitmq-server-release` checkout with all dependencies downloaded. But currently unpacked tarball knows about all make targets, just some of them are non-functional.

**Comment by michaelklishin** [comment]
@binarin I believe this expectation is fair, so we'll leave it open.

**Comment by eurake** [comment]
in 3.6.9  have

**Comment by michaelklishin** [comment]
I'll close this, @binarin feel free to re-open if there's anything specific we still can do.
