### ISSUE TITLE
Extensible command line tools

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#577]
We've been thinking about overhauling our command line tools to make them both produce 
better error messages, and extensible from plugins (e.g. some plugins need their own "status" commands).

Elixir has a nice CLI library, so we have  a good excuse to port them to Elixir, too ;)

Here are relevant areas of the codebase: 
- https://github.com/rabbitmq/rabbitmq-server/tree/master/scripts
- https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_control_main.erl
- https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_plugins_main.erl

**Comment by michaelklishin** [comment]
@essen what was the Elixir `erlang.mk` plugin you recommended again?

**Comment by bdshroyer** [comment]
Is there a particular form that we need to support for plugin status commands, or are plugins supposed to supply their own commands?

**Comment by michaelklishin** [comment]
Plugins supply their own commands. We need to account for clashes, however.

**Comment by michaelklishin** [comment]
This complicates things quite a bit, by the way:

 * CLI tools will need to account for plugin expansion
 * Loading CLI extensions from plugins will slow down tool startup, as demonstrated by Leiningen and likely CF CLI

We can consider using a git-like system where commands are convention-based and if such a command is used (e.g. `rabbitmqctl federation-plugin status`), we translate it into a function call, e.g. `rabbit_federation_cli:status(Args)`. This does not free us from having to worry about the items above, just thinking out loud.

**Comment by essen** [comment]
The plugin list is here http://erlang.mk/guide/plugins_list.html and the Elixir plugin here https://github.com/botsunit/elixir.mk

**Comment by hairyhum** [comment]
New CLI tools repository:
https://github.com/rabbitmq/rabbitmq-cli

**Comment by michaelklishin** [comment]
`effort-medium` => `effort-high` because the sheer number of commands in our CLI tools made the total effort several man-months, not man-weeks.
