### ISSUE TITLE
Consul peer discovery plugin doesn't allow multiple endpoints like the etcd peer discovery plugin does

### ISSUE THREAD

**Issue by jamielinux** [rabbitmq/rabbitmq-server#5792]
Hi there! Thanks again for [implementing](https://github.com/rabbitmq/rabbitmq-server/issues/5116) TLS options for the consul peer discovery plugin :relaxed: 

I noticed in [rabbitmq_peer_discovery_etcd.schema#L10-L61](https://github.com/rabbitmq/rabbitmq-server/blob/2e7ef58bc5ac4008644cde247494bdc12d516c8c/deps/rabbitmq_peer_discovery_etcd/priv/schema/rabbitmq_peer_discovery_etcd.schema#L10-L61) that you can tell RabbitMQ to try connecting to multiple etcd endpoints. (The `host`/`port`/`scheme` settings are marked as deprecated.)

Looking at [rabbitmq_peer_discovery_consul.schema#L8-L50](https://github.com/rabbitmq/rabbitmq-server/blob/2e7ef58bc5ac4008644cde247494bdc12d516c8c/deps/rabbitmq_peer_discovery_consul/priv/schema/rabbitmq_peer_discovery_consul.schema#L8-L50), I can only tell RabbitMQ about a single consul `host`/`port`/`scheme`, which means it's a SPOF.

It would be great if the consul plugin could get the same functionality as the etcd plugin. It would be much appreciated if you could consider this!

**Comment by jamielinux** [comment]
Hi @lukebakken, thanks for re-opening, though I'm actually not sure anymore that this makes sense for Consul. Sorry, I should have commented when I closed:

I was previously running a central cluster of 3 Consul servers, and had RabbitMQ containers on other hosts connect to one of the Consul servers to register themselves as a service. Turns out, a better way of doing things is to also run Consul in client-mode on downstream hosts (ie, where RabbitMQ is running), so that downstream applications can connect to its local Consul client, which in turn connects to your Consul servers redundantly (ie, if a Consul server goes down, the Consul client still has lines of communication with the other Consul servers).

I still consider my experience with Consul to be rather fresh, so I'm not 100% sure of my conclusion. But I think the way that service registration works with Consul, an application can't actually register itself as a service with one Consul node and then start talking to another node instead. Service registration seems tied to a specific Consul node, which makes more sense if you're for example running Consul on every single host that needs to run applications of interest. At least that's my understanding at the moment..

**Comment by michaelklishin** [comment]
Service registration, just like other Consul state, is meant to be distributed.

More importantly for this plugin, if it had a list of nodes it could connect to, it would be slightly more resilient to failures. This is exactly why this feature was added to other plugins such as `etcd`.

**Comment by jamielinux** [comment]
Thanks for your reply @michaelklishin !

On [this Consul docs page](https://developer.hashicorp.com/consul/docs/architecture) it says:

> Consul clients report node and service health status to the Consul cluster. In a typical deployment, you must run client agents on every compute node in your datacenter.

That suggests to me that the downstream application (eg, RabbitMQ) is meant to connect to a Consul client that's running on the same compute node, and not meant to connect to Consul on any other node. One can build resilience into the Consul client by configuring it to connect to all of your centralized Consul servers, rather than building the resilience into the downstream application.

I did previously try to put Haproxy in between RabbitMQ and my 3-node Consul cluster to round-robin the connections, but that ended up with Consul errors. It seems that when an application instance (eg, a RabbitMQ container) registers with a Consul node (whether to a Consul server or to a Consul client), that specific Consul node becomes responsible for that application instance (until the application instance unregisters). The Consul UI dashboard does seem to support this conclusion too: suppose you have a `rabbitmq` service with 3 instances of RabbitMQ, in the dashboard each of those downstream application instances will have `Node name` in its metadata, which indicates which specific Consul node that instance registered with.

I'm happy to be told I'm wrong, just wanted to share my understanding so far. IIUC it's currently already possible to have resilience by telling RabbitMQ to connect to a local Consul client, and it seems Consul doesn't intend for downstream applications to register with more than one node.

**Comment by michaelklishin** [comment]
Alright, [this Consul community discussion](https://discuss.hashicorp.com/t/how-to-make-a-client-for-multiple-hosts/29617) reaches the same conclusion as @jamielinux, so I guess this issue can be closed.

**Comment by lukebakken** [comment]
Thanks everyone!

**Comment by jamielinux** [comment]
Yes, thank you both for bearing with me, and apologies for requesting a feature that in hindsight doesn't even make sense! :sweat_smile:
