### ISSUE TITLE
I hava problem with rabbitmq dashboarad

### ISSUE THREAD

**Issue by pingliu** [rabbitmq/rabbitmq-server#586]
![image](https://cloud.githubusercontent.com/assets/6415493/12643307/53c9013e-c5f6-11e5-90fb-91f7b82c73d9.png)

what the meaning of the stats??
what is effect of the stats??

thanks

**Comment by michaelklishin** [comment]
Please ask questions on rabbitmq-users. `Stats` indicates that the node hosts statistics database which is used by the management plugin.
