### ISSUE TITLE
Support for PROXY protocol (ELB, HAproxy, etc)

### ISSUE THREAD

**Issue by checkmypi** [rabbitmq/rabbitmq-server#589]
This is a feature request to add support for ELB proxy protocol

Last year there were few people who expressed interest in this feature.

https://groups.google.com/forum/#!searchin/rabbitmq-users/ELB$20proxy$20protocol/rabbitmq-users/bZbPDrTrnoc/6JcsR3VxC4oJ

More about ELB Proxy Protocol
http://aws.amazon.com/about-aws/whats-new/2013/07/30/elastic-load-balancing-now-supports-proxy-protocol/

Thanks & regards
m

**Comment by michaelklishin** [comment]
From what I see [in the docs](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-proxy-protocol.html), it would require client library modifications. I'm afraid we can't do it.

**Comment by damoxc** [comment]
@michaelklishin It doesn't require any client library modifications, it's only server side in the communication between loadbalancer -> backend, the client -> loadbalancer connection doesn't include any modification in how the connection works. It would prevent a client from directly connecting to the server, although you could delegate how the connection is handled based on the actual source IP of the connection, configure `proxy_ips` that will then read the proxy header.

**Comment by carlhoerberg** [comment]
It could be a server option, eg. `{proxy_protocol, true}` for servers that's always behind proxies

**Comment by carlhoerberg** [comment]
The protocol is actually designed to be easily identified at connection start. And yes, no client lib modifitaion is required, this is a server-side-only thing. http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt

**Comment by williamsandrew** [comment]
Has there been anymore discussion about this feature? I think this would be really useful for those of us running Rabbits behind any kind of proxy.

**Comment by michaelklishin** [comment]
@williamsandrew not on our team. I trust @carlhoerberg's judgement that no client modifications will be necessary. We will consider this for `3.7.x` or `3.8.0`.

**Comment by michaelklishin** [comment]
We have a working prototype, looks like this can go into `3.7.0` with little risk (and no delays).

**Comment by michaelklishin** [comment]
We have contributed a couple of fixes upstream and they were accepted, this is approaching the finish line.

**Comment by michaelklishin** [comment]
PRs for AMQP 0-9-1, MQTT, STOMP are merged. AMQP 1.0 is left to be done.

**Comment by uvzubovs** [comment]
I am not skilled with the proxy protocol. Will this work with F5 LTM (local traffic manager, a.k.a. the load balancer/IP-sprayer)?

**Comment by Jakauppila** [comment]
@uvzubovs At a preliminary glance it looks like you can use an iRule on the Virtual Server to implement Proxy Protocol v1; but there isn't anything baked into the appliance to enable the functionality.

**Comment by michaelklishin** [comment]
At this point the Proxy Protocol is supported by enough popular vendors/projects (from HAproxy and Nginx to AWS ELB) that it's on F5 to add support to their products.

@Jakauppila thank you, your input is very helpful as always. May I ask you to share a small example, either here or on rabbitmq-users? :) I'd happily add a note for F5 users to our docs.

**Comment by uvzubovs** [comment]
How would this work with client auth SSL? Proxy needs to terminate SSL to add client info to the connect frame, but it does not have client's SSL cert when connecting to Rabbit; it will present it's own. Will Rabbit's client auth SSL logic be updated to recognize certain client SSL cert as that of a proxy, and so then get the true client SSL cert name from the client info in the connect frame?

**Comment by michaelklishin** [comment]
Not all proxies terminate TLS. This protocol sends a bit of data before any other protocol-specific data, at that point TLS upgrade has been completed. The protocol only relays some basic client information such as the real IP address.
