### ISSUE TITLE
Add HTTP API endpoint to retrieve effective configuration

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#6016]
Not everyone can execute `rabbitmq-diagnostics environment` so an endpoint would be helpful.

https://www.rabbitmq.com/configure.html#verify-configuration-effective-configuration

[internal Slack discussion](https://vmware.slack.com/archives/C0RDGG81Z/p1661875569765949)

**Comment by SimonUnge** [comment]
Looking into it

**Comment by michaelklishin** [comment]
My only concern is that it would return sensitive values. Maybe those should be filtered out and the endpoint should require the user to be tagged with `administrator`.

**Comment by SimonUnge** [comment]
Sure, I will get something working then reach out to finalize details?

**Comment by michaelklishin** [comment]
Sounds good.
