### ISSUE TITLE
Bundle rabbitmqadmin cli too with the main install package

### ISSUE THREAD

**Issue by geekpete** [rabbitmq/rabbitmq-server#605]
It's a bit odd having to curl a command from a webpage and manually install it on a server rather than it be provided and installed by the installation package itself.

Or a the very least make it a separate installable package that is optional, if there's a good reason to leave it off by default.

https://www.rabbitmq.com/management-cli.html

**Comment by michaelklishin** [comment]
`rabbitmqadmin` ships with the management plugin. If you have specific suggestions in mind, please file an issue there https://github.com/rabbitmq/rabbitmq-management/.

**Comment by michaelklishin** [comment]
One fairly obvious idea is to produce a symlink to it somewhere in PATH. That wouldn't work for all package types and the tool wouldn't work if `rabbitmq_management` isn't enabled. So it's not a no-brainer.

I suggest starting a `rabbitmq-users` thread.

**Comment by geekpete** [comment]
We'll look to bandaid this with our config management for now.

But I do see your point in that different OSes would behave differently and if the plugin wasn't enabled, then you'd not want that too to be available until it is.

It gets a bit hairy.

**Comment by michaelklishin** [comment]
It's not OSes but packages. For example, for Debian and RPM we have a chance to run post-install scripts to copy/link `rabbitmqadmin`. In generic UNIX packages post-install scripts simply don't exist.

**Comment by wyardley** [comment]
See also #692
