### ISSUE TITLE
New plugin to stamp messages with origin node

### ISSUE THREAD

**Issue by johnfoldager** [rabbitmq/rabbitmq-server#608]
We would like to be able to (optionally) have the receiving RabbitMQ node (not the producer as it might not know which node it connects to because of load balancers etc) stamp a 'x-origin-node' (or something similar) header to every message it receives. The idea is similar to https://github.com/rabbitmq/rabbitmq-message-timestamp.

See discussion here: https://groups.google.com/d/msg/rabbitmq-users/KcIed5Alg68/0QFqJ63DAAAJ.

**Comment by michaelklishin** [comment]
I'd like to be clear: this is a low priority as this is a feature requested by a single user.

"receiving node" is ambiguous. I assume what you mean is the node that accepts a message from  client?

**Comment by michaelklishin** [comment]
Sorry but there will be no per-protocol configuration. The plugin will inject a header and if protocol is extensible with optional headers (e.g. STOMP), such headers should be propagated. Some protocols, e.g. MQTT, are not extensible.

**Comment by johnfoldager** [comment]
Yes the node that accepts the message from client.
Okay with the not-per-protocol configuration.
Okay with the low-priority.

**Comment by michaelklishin** [comment]
See https://github.com/rabbitmq/rabbitmq-routing-node-stamp.

**Comment by johnfoldager** [comment]
Cool. Thanks!
Michael, you added this for 3.6.1 milestone but the GitHub page says it is "This plugin targets RabbitMQ 3.6.0 and later versions."
Also on the GitHub page at the bottom it says "...process in order to add the current timestamp as seen by the broker." - notice "timestamp" which be broker node or something similar.

**Comment by michaelklishin** [comment]
It was developed during the `3.6.1` cycle, I cannot think of a better milestone (if we set one at all).

**Comment by bdshroyer** [comment]
@michaelklishin I can fix the timestamp copy in the README.

**Comment by johnfoldager** [comment]
Ok. Will it be downloadable as a .ez file from somewhere and/or be available in the RabbitMQ 3.6.1 release when released?

**Comment by michaelklishin** [comment]
It should appear on the binary [Community Plugins page](https://www.rabbitmq.com/community-plugins.html) later this week.

**Comment by michaelklishin** [comment]
@bdshroyer sure, you don't need my permission to make such changes ;)
