### ISSUE TITLE
Tune scheduling flags for Erlang VM

### ISSUE THREAD

**Issue by sega-yarkin** [rabbitmq/rabbitmq-server#612]
By default the Erlang VM doesn't pin their threads to vCPU and when multi-core server has big load we have huge context switching (8.3k per vCPU in our case). But the Erlang VM gives to us ability to configure [scheduler bind type](http://erlang.org/doc/man/erl.html#id176181), this can helps to reduce context switching. The flag name is `+stbt`, in our installation we're using `+stbt ts`, it reduced context switching for 4 times (2k per vCPU).

It looks like easy tuning which gives a nice result for reducing unnecessary CPU context switching and I think it can be considered for including to default configuration. But `ts` value might be not the best choice for every platforms, it should be tested before (we've tasted only VMware virtual machines).

https://groups.google.com/forum/?hl=en#!topic/rabbitmq-users/WIprYZF5T8Q

**Comment by michaelklishin** [comment]
@dumbbell @hairyhum @essen @bdshroyer any objections?

**Comment by hairyhum** [comment]
I think we can make `db` bind type default and introduce environment variable to change it.

**Comment by michaelklishin** [comment]
I think @sega-yarkin's point is that it should be `ts` by default. Introducing an environment variable for easy overriding is a good idea.

**Comment by hairyhum** [comment]
According to docs `db` and `ts` will have different behaviour only on NUMA nodes. But `db` is called default, so it's more expected.

**Comment by michaelklishin** [comment]
I don't think many users even know you can tune scheduler-to-CPU bindings, so there are no particular expectations. @sega-yarkin provides a realistic example where the default is clearly sub-optimal.

Perhaps @dcorbacho @Dzol and @Ayanda-D have an opinion on this?

**Comment by dcorbacho** [comment]
I think it is a good idea to add that option. In a particular case, I found a good performance improvement in a load testing tool by using `+sbt db`. However, care must be taken on the implementation of the flag in the rabbit side, because the default may not be optimal in some platforms (add a warning?) or the option not allowed (if my memory doesn't fail, OS X doesn't accept the `+sbt db` flag and fails on startup).

**Comment by hairyhum** [comment]
@dcorbacho `+stbt` should be more safe. `+sbt` will fail to start VM if runtime cannot support scheduler binding or cpu topology, while `+stbt` will just ignore it.

**Comment by dcorbacho** [comment]
Thanks @hairyhum, I hadn't notice that option before!

**Comment by sega-yarkin** [comment]
@hairyhum `db` now is equal to `thread_no_node_processor_spread` that spreads threads over one NUMA node only. It's good to pin threads to one NUMA node if we'll use local memory only.

If we have system with 2 NUMA nodes (for example 16GB RAM per node) and we use `db` and we want to use all available memory (32GB) threads will have access to non-local NUMA node (and this access will be slower than access to local NUMA node). But at the same time we'll use only half of available CPU cores.
So, if we use only local NUMA memory it'll be good to use only its CPU cores, but if we use all system memory there no reason to not use all CPU cores.

**Comment by sega-yarkin** [comment]
I've tested behavior of Erlang with different values of `+stbt` parameter.
My system:
```
# numactl -H
available: 2 nodes (0-1)
node 0 cpus: 0 1 2 3
node 0 size: 16383 MB
node 0 free: 11142 MB
node 1 cpus: 4 5 6 7
node 1 size: 16384 MB
node 1 free: 10289 MB
node distances:
node   0   1
  0:  10  20
  1:  20  10

# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 37
Model name:            Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz
Stepping:              1
CPU MHz:               2300.000
BogoMIPS:              4600.00
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0-3
NUMA node1 CPU(s):     4-7
```
RMQ works without async I/O threads (`RABBITMQ_IO_THREAD_POOL_SIZE=0`).
The first run was without `+stbt` parameter and I had:
```
# ps -T -H -o spid --no-headers --ppid `cat /var/run/rabbitmq/pid` | xargs -n1 taskset -p
pid 3105's current affinity mask: ff
pid 3112's current affinity mask: ff
pid 3113's current affinity mask: ff
pid 3114's current affinity mask: ff
pid 3116's current affinity mask: ff
pid 3117's current affinity mask: ff
pid 3118's current affinity mask: ff
pid 3119's current affinity mask: ff
pid 3120's current affinity mask: ff
pid 3121's current affinity mask: ff
pid 3122's current affinity mask: ff
pid 3123's current affinity mask: ff
pid 3124's current affinity mask: ff
pid 3353's current affinity mask: ff
pid 9488's current affinity mask: ff
```
The second one with `+stbt ts`
```
pid 9488's current affinity mask: ff
pid 20035's current affinity mask: ff
pid 20049's current affinity mask: ff
pid 20061's current affinity mask: ff
pid 20063's current affinity mask: ff
pid 20073's current affinity mask: 1
pid 20074's current affinity mask: 2
pid 20075's current affinity mask: 4
pid 20076's current affinity mask: 8
pid 20077's current affinity mask: 10
pid 20078's current affinity mask: 20
pid 20079's current affinity mask: 40
pid 20080's current affinity mask: 80
pid 20081's current affinity mask: ff
pid 20101's current affinity mask: ff
```

`+stbt db`:
```
pid 9488's current affinity mask: ff
pid 20648's current affinity mask: ff
pid 20658's current affinity mask: ff
pid 20661's current affinity mask: ff
pid 20675's current affinity mask: ff
pid 20677's current affinity mask: 1
pid 20678's current affinity mask: 2
pid 20679's current affinity mask: 4
pid 20680's current affinity mask: 8
pid 20681's current affinity mask: 10
pid 20682's current affinity mask: 20
pid 20683's current affinity mask: 40
pid 20684's current affinity mask: 80
pid 20685's current affinity mask: ff
pid 20950's current affinity mask: ff
```

`+stbt nnps`:
```
pid 9488's current affinity mask: ff
pid 28959's current affinity mask: ff
pid 28966's current affinity mask: ff
pid 28967's current affinity mask: ff
pid 28968's current affinity mask: ff
pid 28969's current affinity mask: 1
pid 28970's current affinity mask: 2
pid 28971's current affinity mask: 4
pid 28972's current affinity mask: 8
pid 28973's current affinity mask: 10
pid 28974's current affinity mask: 20
pid 28975's current affinity mask: 40
pid 28976's current affinity mask: 80
pid 28977's current affinity mask: ff
pid 29481's current affinity mask: ff
```

I dunno why, but behavior is equal)

**Comment by binarin** [comment]
https://youtu.be/tW49z8HqsNw?t=11m2s - WhatsApp is using `tnnps` (same as `db`).

**Comment by michaelklishin** [comment]
Scheduler migration between cores is becoming something we see reported more and more often. We should consider picking a value other than default soon.

Thanks for the data point, @binarin.

**Comment by michaelklishin** [comment]
Related: #1528.
