### ISSUE TITLE
RabbitMq Stomp : Unable to create durable subscription

### ISSUE THREAD

**Issue by darshanmehta10** [rabbitmq/rabbitmq-server#614]
RabbitMQ Version : 3.3.4

> Exchange Details:
> Name : stream_exchange
> Type : topic
> Parameters : (durable : true)

I am sending a Stomp subscription request to the above exchange, with following parameters:

> SUBSCRIBE
> auto-delete : false
> durable : true
> expires : 20000
> id : sub-0
> destination : /exchange/stream_exchange

The connection is successful, and as a result, a new temporary queue is created. However, the parameters passed in subscribe request (auto-delete, durable and expires) have no effect. The queue has auto-delete set to true and it gets deleted once the client disconnects.

As per the [rabbitmq documentation](https://www.rabbitmq.com/stomp.html), it should result in a durable subscription and queue should be durable. Basically, I don't want the queue to be deleted if a client disconnects for any reason, resulting in loss of messages. I want it to exist for 'expires' amount of time at least.

**Comment by michaelklishin** [comment]
`3.3.x` isn't getting any more releases, please upgrade to `3.6.0`.

**Comment by michaelklishin** [comment]
@darshanmehta10 the docs currently cover RabbitMQ `3.6.0`, queue parameter adjustment via STOMP headers isn't available in `3.3.x`.

**Comment by darshanmehta10** [comment]
@michaelklishin thanks for the prompt reply. :) 
Does this apply for policies as well? I tried setting some policies based on queue name pattern but none of the policies apply when queue gets created.

**Comment by michaelklishin** [comment]
Policies only control optional arguments ("x-arguments"), not durability, exclusivity or auto-deletion.
