### ISSUE TITLE
Mirrored queues can cause a node to run out of memory

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#616]
When a slave queue is syncing messages from a master queue, the sync process continues to send messages even if the node is above its memory high watermark. This can lead to a crash of the slave node.

**Comment by michaelklishin** [comment]
Fixed in #617.

**Comment by juliocr-ciandt** [comment]
Hi guys, 
We continue with this problem happening in version 3.6.12,  3 node configured with 2GB, 1800MiB of watermark and 1,500,000 messages in the queue, when a node need to be sync, this one exceeds the WM several times until the node crash the node. Can some one help? thank you

**Comment by michaelklishin** [comment]
@juliocr-ciandt we do not use GitHub issues for investigations, discussions and such. Please post your findings to rabbitmq-users, our public mailing list.

**Comment by michaelklishin** [comment]
@juliocr-ciandt there is no shortage of threads on the list that explain how to get a really detailed memory usage breakdown from a node, e.g. using rabbitmq-top (which ships with 3.6.12).

**Comment by michaelklishin** [comment]
@juliocr-ciandt there are also existing threads and [a doc guide]9http://www.rabbitmq.com/production-checklist.html) that mention what VM high memory watermark values are recommended and what easy to try alternative queue properties (such as lazy queues or durable queues + messages published as persistent) you can try.
