### ISSUE TITLE
'rabbitmq-server.bat -detached' can fail unpredictably

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-server#618]
As [reported](https://issuetracker.springsource.com/browse/VESC-594), having installed RMQ 3.6.0 in Windows 7 using manual install mode, `rabbitmq-server.bat` starts the broker and works, however running `rabbitmq-server.bat -detached` can work or fail in an unpredicted manner.

**Comment by Ayanda-D** [comment]
@michaelklishin after carrying more tests, we've concluded that using `-detached` flag with `erl` does indeed seem problematic on a Windows environment. Currently, our options are;
- Fix `erl` to handle `-detached` as expected (might take a while),
- Use http://erlang.org/doc/man/werl.html instead,
- Use http://erlang.org/doc/man/erlsrv.html.
 
which option is best going forward in resolving this problem?

**Comment by michaelklishin** [comment]
Using `werl` makes sense to me. Will discuss the pros and cons of using `erlsrv` on Slack.

**Comment by Ayanda-D** [comment]
Okay, as discussed, going with second option for **3.6.x**, of updating the `rabbitmq-server.bat` to use `werl` command whenever the `-detached` flag is passed. To investigate `erlsrv` for future releases.

**Comment by Ayanda-D** [comment]
@michaelklishin note; above feedback/findings from @rtraschke an internal ESL team member, who are currently focused on this issue. Just waiting for more feedback from them on how they're looking to get this to work.

**Comment by michaelklishin** [comment]
Thanks for the update, @Ayanda-D.

**Comment by Ayanda-D** [comment]
@michaelklishin using the `-detached` flag still fails in an unpredictable manner when using `werl`. The team has filed an [OTP bug](http://bugs.erlang.org/browse/ERL-98), and once this is fixed, and shipped with an erlang release (which we'll confirm), `rabbitmq-server.bat` script will be updated to cater for the `-detached` flag.

**Comment by michaelklishin** [comment]
@Ayanda-D thanks for the update.

**Comment by ttmonica** [comment]
@Ayanda-D Thanks for your sharing information! wait for the fix or new updates!

**Comment by michaelklishin** [comment]
I'm not sure what this should be labeled with, we need a label for blocked/waiting issues and possibly OTP bugs.

**Comment by GauravSharmaDA** [comment]
Hi, Any update on this? I am still getting this issue on our rabbitmq. 
If I do 
**_RabbitMq-Server.bat start_** 
Then 
RabbitMQCtl cluster_status  works fine.

If I do
**_RabbitMq-Server.bat start -detached_**
I get
_Cluster status of node rabbit@DARBTCH01 ...
Error: unable to connect to node rabbit@DARBTCH01: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@DARBTCH01]

rabbit@DARBTCH01:
  * connected to epmd (port 4369) on DARBTCH01
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on DARBTCH01
  * suggestion: start the node

current node details:
- node name: 'rabbitmq-cli-18@DARBTCH01'
- home dir: C:\Users\GauravS_admin.DIRECTAXIS
- cookie hash: Kec5RbLAXMvcIzxRRzRjpQ==
Cluster status of node rabbit@DARBTCH01 ...
Error: unable to connect to node rabbit@DARBTCH01: nodedown

DIAGNOSTICS
===========

attempted to contact: [rabbit@DARBTCH01]

rabbit@DARBTCH01:
  * connected to epmd (port 4369) on DARBTCH01
  * epmd reports: node 'rabbit' not running at all
                  no other nodes on DARBTCH01
  * suggestion: start the node_

Please help!!

**Comment by michaelklishin** [comment]
@GauravSharmaDA our team does not use GitHub issues for questions, investigations, RCA and so on. Please take this to rabbitmq-users.

As for an update, we have identified a known Erlang/OTP issue that makes `-detached` on Windows not 100% reliable. Not sure if it was addressed in recent releases.

**Comment by michaelklishin** [comment]
RabbitMQ Windows installer sets up a service that runs the node in foreground. That's the recommended way of doing it (just like service managers are on Debian and RPM-based Linux distributions, even though `-detached` doesn't have any known issues there).

**Comment by mkuratczyk** [comment]
Closing this with the assumption that it's no longer relevant.
