### ISSUE TITLE
"headers" exchange crashes rabbit 3.5.6, when rabbit has high connection counts 

### ISSUE THREAD

**Issue by venikkin** [rabbitmq/rabbitmq-server#619]
Hi, 
This is actually a clone of issue #403. This issue is reproducible for 3.5.6 for us as well, but RabbitMQ fails with higher connection counts. 
RabbitMQ version: 3.5.6
Box: AWS c3.2xlarge (15 GB RAM, 8 CPU cores)
Plugins: 
```
root@ip-10-0-142-111:~$ rabbitmq-plugins list
 Configured: E = explicitly enabled; e = implicitly enabled
 | Status:   [failed to contact rabbit@localhost - status not shown]
 |/
[e ] amqp_client                              3.5.6
[  ] brod                                     1.4-rmq0.0.0-git9e9e870
[  ] cowboy                                   0.5.0-rmq3.5.6-git4b93c2d
[E ] erlzk                                    0.4.0-rmq0.0.0-gite6495a1
[E ] lager                                    2.0.0-rmq0.0.0-git9719370
[e ] mochiweb                                 2.7.0-rmq3.5.6-git680dba8
[  ] rabbitmq_amqp1_0                         3.5.6
[  ] rabbitmq_auth_backend_ldap               3.5.6
[E ] rabbitmq_auth_mechanism_ssl              3.5.6
[  ] rabbitmq_consistent_hash_exchange        3.5.6
[  ] rabbitmq_federation                      3.5.6
[  ] rabbitmq_federation_management           3.5.6
[E ] rabbitmq_management                      3.5.6
[e ] rabbitmq_management_agent                3.5.6
[  ] rabbitmq_management_visualiser           3.5.6
[  ] rabbitmq_mqtt                            3.5.6
[E ] rabbitmq_shovel                          3.5.6
[  ] rabbitmq_shovel_management               3.5.6
[  ] rabbitmq_stomp                           3.5.6
[  ] rabbitmq_test                            3.5.6
[  ] rabbitmq_tracing                         3.5.6
[e ] rabbitmq_web_dispatch                    3.5.6
[  ] rabbitmq_web_stomp                       3.5.6
[  ] rabbitmq_web_stomp_examples              3.5.6
[  ] sockjs                                   0.3.4-rmq3.5.6-git3132eb9
[e ] webmachine                               1.10.3-rmq3.5.6-gite9359c7
```

Scenario: 
1. Create a "direct" exchange (A) where these messages are routed to
2. Connect 5000+ clients, get them all to produce messages to (A) with same routing key 
3. Create a separate "headers" (B) exchange
4. Bind (A) to (B) with same routing key

Expected:
Messages get routed to (B) successfully

Actual:
RabbitMQ becomes unresponsive almost immediately.

Reproducibility: 100%

There are no related alerts or warning in logs. 

Thank you

**Comment by michaelklishin** [comment]
Just like in #403, you are using a version that's not getting any more updates. Please use `3.6.0`. I'm also not convinced that what you observe has anything to do with a specific exchange types. Your node is probably hitting a RAM alarm (connections use RAM, a few MBs per connection unless [you configure TCP socket options](http://rabbitmq.com/networking.html)).

This belongs to rabbitmq-users. Please use 3.6.0 and provide full server logs.
