### ISSUE TITLE
3.6.0 uses different hostname case in RABBITMQ_NODENAME default

### ISSUE THREAD

**Issue by StevenBonePgh** [rabbitmq/rabbitmq-server#620]
Windows (obviously), 64 bit, using 32 bit erlang 18.1.0 and 18.2.1.  I am using %% to surround something to indicate it is an environment variable in this issue.

In at least version 3.5.6 and previous, if %RABBITMQ_NODENAME% was not set, rabbitmq-env.bat would set it to the value of rabbit@%COMPUTERNAME%.  In 3.6.0, it is now being set by shelling out to erlang.  Where %COMPUTERNAME% was returning uppercase, erlang is returning lowercase, so this changes the value.

The impact of this is felt (at least) when running rabbitmq-service.bat install with %RABBITMQ_NODENAME% unset, as it calls rabbitmq-env.bat, which sets %RABBITMQ_NODENAME% to the lowercase version, which sets HKLM\Software\[Perhaps Wow6432Node]\Ericsson\Erlang\ErlSrv\[Service Name]\SName to that value, which then 'breaks' a previously existing node database due to the casing difference in node name with the error message "Cluster upgrade needed" even though there was not a clustered node.

More details as to exactly how this prevents the node from starting can be found here:
https://groups.google.com/d/msg/rabbitmq-users/ykoK-bepR6g/m-qaZIlyBAAJ

**Comment by michaelklishin** [comment]
Thanks for digging this one out, @StevenBonePgh. I think the right thing to do here would be to normalize (e.g. force lowercase) and de-duplicate node lists. With that it may or may not matter if we revert to using uppercase hostnames.

@dumbbell @hairyhum thoughts?

**Comment by michaelklishin** [comment]
I've submitted a PR that upper cases calculated hostname. This restores the case used in `3.5.7` and will only affect those upgrading from `3.6.0` (or simply set `RABBITMQ_NODENAME`): https://github.com/rabbitmq/rabbitmq-server/pull/637.

@StevenBonePgh what do you think of this solution?

**Comment by michaelklishin** [comment]
Now that I think of it, perhaps lowercasing was the point of https://github.com/rabbitmq/rabbitmq-server/commit/1fb451090a2557f35a2800f9d04c476ff1ad6a22 and thus the solution for those upgrading from `3.5.x` should be to set `RABBITMQ_NODENAME` explicitly. We need to discuss with the team.

**Comment by michaelklishin** [comment]
Someone points out that using lowercase has one advantage: it is consistent across all platforms. We found that `%COMPUTERNAME%` value can use either case. Since there is a workaround for this issue — simply set `RABBITMQ_NODENAME` — I think perhaps we should mention this in the release notes but keep the current behaviour.

**Comment by michaelklishin** [comment]
After discussing this with the team, we decided to keep the behaviour 3.6.0 has. It's not necessarily better or worse than what we had with `%COMPUTERNAME%` but it is more predictable and consistent across OSes.

A workaround is to set the `RABBITMQ_NODENAME` environment variable to a value that uses the desired hostname case. We will update the docs and release notes. Again, thank you for your help, @StevenBonePgh!
