### ISSUE TITLE
Diagnostics CLI tool

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#621]
It could be useful to have `rabbitmqctl` for reports only and without ability to change things in broker. Maybe it can be done using config parameter or with separate script.

**Comment by michaelklishin** [comment]
We have a separate repo for next gen CLI tools (not yet public) but the issue can stay here. I think `rabbitmq-diagnostics` is a good idea. `rabbitmqctl report` and friends cannot be removed immediately but we can switch all the docs to use `rabbitmq-diagnostics`.

**Comment by michaelklishin** [comment]
@bdshroyer @dumbbell @camelpunch WDYT?

**Comment by bdshroyer** [comment]
@michaelklishin Is there any additional functionality that would go into a `rabbitmq-diagnostics` tool, or is it just the `report` contents?

**Comment by michaelklishin** [comment]
`report`, `status` for starters. We can introduce a new operation for `rabbit_diagnostics:maybe_stuck/0` there, too.

**Comment by camelpunch** [comment]
I'm presuming that you'd want this to use on boxes that didn't have too much functionality in their tools for security reasons. Is it worth considering git-style delegation to sub commands to retain the existing interface from rabbitmqctl?

**Comment by michaelklishin** [comment]
`rabbitmqctl` has a lot of stuff in it. Sub command delegation can be used to retain backwards compatibility but we can fairly easily do the same thing without it.
