### ISSUE TITLE
Add ability to monitor the queues for the number of messages

### ISSUE THREAD

**Issue by atuljangra** [rabbitmq/rabbitmq-server#622]
A queue has producers and consumers. Essence of a queue is to be used as a message passing service. Ideally there shouldn't be too many messages in the queue if the queue and consumers are healthy.
This issue states that we should have an ability to add hooks to the queues to monitor the number of messages in the queue and if the number of messages is greater than a certain threshold then some alert should be issued.

**Comment by noahhaon** [comment]
We solve this using any number of monitoring tools that can consume JSON via the management interface.  The management plugin has a very comprehensive REST API and emits JSON which just about anything can consume.  You can even do this with curl jq and bash if need be.

**Comment by michaelklishin** [comment]
Plenty of people do this by polling (using HTTP API or passive `queue.declare`). I'm not sure how you expect alerts to be triggered but this is something that belongs to a separate plugin and might be easier done in a small separate app.

**Comment by atuljangra** [comment]
Yes agreed that this should be done in separate app or plugin.
Thanks for the responses.
