### ISSUE TITLE
RHEL7 rpm packages?

### ISSUE THREAD

**Issue by raphaelbadawi** [rabbitmq/rabbitmq-server#6288]
I've been surprised to find out the last RHEL7 package is for rabbitmq 3.10 and RHEL7 packaging seems to have been discontinued.

For rabbitmq 3.11 we had to convert the deb to rpm using alien.

RHEL7 is still widely used in production.

Can we hope for their return?

Thanks

**Comment by michaelklishin** [comment]
No, you can't. There are no modern OpenSSL versions for CentOS 7, which means modern Erlang versions cannot run on it.
