### ISSUE TITLE
RabbitMQ Stomp : subscribe requests doesn't use the existing queue

### ISSUE THREAD

**Issue by darshanmehta10** [rabbitmq/rabbitmq-server#633]
I am using the following code to create Stomp subscription to RabbitMQ server:

    var Stomp = require('stompjs');
    var SockJS = require('sockjs-client');
    var stompConnect = function() {
	var sock = new SockJS(options.url);

	stomp = Stomp.over(sock);
	stomp.connect({}, function(frame) {
		debug('Connected: ', frame);

		var id = stomp.subscribe('<url>', function(d) {
			console.log(d);
			
		}, {'auto-delete' : false, 'id' : '1234', 'durable' : true});
	}, function(err) {
		debug('error', err, err.stack);
		// through.emit('error', err);
		setTimeout(stompConnect, 10);
	});
    };

Upon executing, a new queue is created (with name ^stomp-<some text>) and messages get printed in the console. In the RabbitMQ Admin, I can see a queue with one consumer having T_1234 as a consumer tag.

However, when I kill the script (ctrl + c) and restart it again with the same id, a new queue gets created, it is not using the existing queue. For the new queue, I can see a consumer with T_1234 as  a consumer tag.

I am using RabbitMQ 3.6.0 and as per the [documentation](https://www.rabbitmq.com/stomp.html),  it should create a durable subscription and same queue should be used when the client reconnects.

**Comment by michaelklishin** [comment]
Please ask questions on rabbitmq-users. STOMP supports [multiple destinations](http://www.rabbitmq.com/stomp.html) and in 3.6.0, even allows you to override queue name and properties. All that is headers-based and should be available to Web STOMP (which is what you use).

**Comment by michaelklishin** [comment]
Also note: queue names and subscription IDs are not the same thing to RabbitMQ, in particular you can have multiple subscribers/consumers on a shared queue. But then again, whether a server-generated or client-provided queue name is used, depends on the destination type and client-provided headers.

That is [an issue](https://github.com/rabbitmq/rabbitmq-stomp/issues/58) in 3.6.0 which ignored the `durable` header in some cases. `persistent`, and older value, should work like before. I suspect this also can make RabbitMQ generate a queue name in your case.
