### ISSUE TITLE
migrate from rabbit 3.5.1 to 3.6.0

### ISSUE THREAD

**Issue by quxiaojing** [rabbitmq/rabbitmq-server#643]
i load a json config backup from 3.5.1, but cannot login with the original password，
it the default password hash rule changed ？ any  advices？

**Comment by michaelklishin** [comment]
Please ask questions on rabbitmq-users.

See http://www.rabbitmq.com/passwords.html and https://github.com/rabbitmq/rabbitmq-management/issues/117.

**Comment by quxiaojing** [comment]
Thanks !
