### ISSUE TITLE
Verify run-broker on debian with package installed

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#649]
On debian (ubuntu trusty) system with installed `rabbitmq` package running `make run-broker` from dev repository dir fail with error
```
Error: The following plugins could not be found:
  WARNING:
  ignoring
  /etc/rabbitmq/rabbitmq.conf
  --
  location
  has
  moved
  to
  /etc/rabbitmq/rabbitmq-env.conf
```

**Comment by michaelklishin** [comment]
@hairyhum a long long time ago config file names were `rabbitmq.config` and `rabbitmq.conf` (the latter is `rabbitmq-env.conf` now). So on #550, this error seems confusing. We should simply remove that warning in #550.
