### ISSUE TITLE
Priority queue badmatch prioritising message read from disk

### ISSUE THREAD

**Issue by simonmacmullen** [rabbitmq/rabbitmq-server#65]
See bug report: https://groups.google.com/d/msg/rabbitmq-users/bD0Pex1LXAE/mPvEjFdiXUkJ

The line badmatching is here: https://github.com/rabbitmq/rabbitmq-server/blob/7803bd29ead635464b9f780388c2ffdea83a8a61/src/rabbit_priority_queue.erl#L533

I am pretty sure the problem is that it's looking at a message which has been read from disk (user says you need a large queue) and doesn't have decoded content, hence `{badmatch, none}`.

**Comment by simonmacmullen** [comment]
I guess it would be polite to backport this to the 3.4.x plugin when fixed...

**Comment by dumbbell** [comment]
Since 3.5.0.
