### ISSUE TITLE
Line feeds in queue and exchange names

### ISSUE THREAD

**Issue by davidvanlaatum** [rabbitmq/rabbitmq-server#656]
Running RabbitMQ 3.5.4 we managed to accidentally create queues and exchanges with a new line on the end of their name but were then unable to delete them via the management UI as it inserted a \<br/\> in the url and json it used to delete them resulting in a not found message. Resending the delete request with the \<br/\> removed successfully deleted them

**Comment by michaelklishin** [comment]
I'm not sure what you request is about but this repository is for the core server.

**Comment by michaelklishin** [comment]
FTR: while the issue as reported is in the management plugin, the right thing to do here is to strip line breaks in the server (or reject queue declaration when queue name contains it), so we've filed #710
in this repo. Thanks, @davidvanlaatum.
