### ISSUE TITLE
rabbitmq_sharding plugin race condition on node restart

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#6582]
Reported in the following discussions:

* https://github.com/rabbitmq/rabbitmq-server/discussions/3415
* https://github.com/rabbitmq/rabbitmq-server/discussions/6429

cc @reichowc @faithfull @gaima8

By following the reproduction steps given [here](https://github.com/reichowc/rabbitmq-sharding-plugin) (thank you @reichowc), I was able to reproduce this issue _once_ using Docker. If I run a cluster using `make start-cluster`, I can't reproduce the issue. Note that I am working on a way to reliably reprodue the issue [here](https://github.com/lukebakken/rabbitmq-server-3415-6429).

Here is the sequence of events that causes [the error](https://github.com/rabbitmq/rabbitmq-server/discussions/3415#discussioncomment-1436194) ([link](https://github.com/rabbitmq/rabbitmq-server/discussions/3415#discussioncomment-1436194)):

* Cluster node boots and reaches the `rabbit_sharding_exchange_decorator` boot step, which only requires the `rabbit_registry` step to have completed.
* This boot step causes `rabbit_registry:register/3` to be called.
* The above function eventually leads to [this line](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit_common/src/rabbit_registry.erl#L78) being called, which in this case is `rabbit_exchange_decorator:added_to_rabbit_registry/2` being called.
* In the above module, `maybe_recover/1` is called, which leads to `rabbit_sharding_exchange_decorator:create/2` being called.
* In the above module, `create/2` eventually leads to `rabbit_sharding_shard:ensure_sharded_queues/1` being called, which tries to created the sharded queues. **NOTE**: at this time the vhost may not yet be running, and the error is triggered.

The `rabbit_sharding_exchange_decorator` boot step enables the `recovery` boot step, which is where vhosts are recovered. It seems as though this boot step should require the `recovery` step to have completed, and it shouldn't enable anything.

cc @michaelklishin

**Comment by lukebakken** [comment]
Aha, I added some debug logging and somehow managed to trigger this using `make start-cluster` and rebooting `rabbit-2`:

[rabbit-2.log](https://github.com/rabbitmq/rabbitmq-server/files/10168290/rabbit-2.log)

**Comment by lukebakken** [comment]
@michaelklishin #6583 only addresses the `rabbitmq_sharding` startup. There are a couple other plugins that are exchange decorators that may need a similar change ... or not?

**Comment by michaelklishin** [comment]
@lukebakken I can imagine there are. Good catch!

**Comment by lukebakken** [comment]
OK I will follow up.
