### ISSUE TITLE
Use powershell if handle.exe is missing or reports an error

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#6613]
Related issues:
* https://github.com/rabbitmq/rabbitmq-management-agent/issues/67
* https://github.com/rabbitmq/rabbitmq-management-agent/issues/90
* https://github.com/rabbitmq/rabbitmq-server/discussions/6612

The issue is that, for some Windows users, `handle.exe` sometimes does **not** output the data line starting with `File` that the stats monitor expects. We have no idea why this happens, and have not been able to reproduce it. However, you _can_ use Powershell to get the total number of handles for a process, which should be a "good enough" fallback.

Here is the output of each command on Windows 11, while I have PerfTest running with 10 consumers and producers:

```
(rabbit@bakkenl-z01)12> string:tokens(os:cmd("handle.exe /accepteula /nobanner /s /p " ++ os:getpid()), "\r\n").
["Handle type summary:","  <Unknown type>  : 2",
 "  <Unknown type>  : 119","  ALPC Port       : 8",
 "  Desktop         : 1","  Directory       : 2",
 "  Event           : 158","  File            : 62",
 "  IoCompletion    : 18","  IoCompletionReserve: 1",
 "  IRTimer         : 6","  Key             : 17",
 "  Mutant          : 2","  Process         : 3",
 "  Section         : 3","  Semaphore       : 8",
 "  Thread          : 23","  TpWorkerFactory : 3",
 "  WaitCompletionPacket: 15","  WindowStation   : 2",
 "Total handles: 453"]

(rabbit@bakkenl-z01)13> os:cmd("pwsh.exe -NoLogo -NoProfile -NonInteractive -Command (Get-Process -Id " ++ os:getpid() ++ ").Handles").
"453\r\n
```

When connections increase, the `File` count goes up (as expected) as do a couple others. But, it is linear, and gives a useful stat. Since the statistic is not used for alarms or rate-limiting RabbitMQ using this as a fallback seems reasonable.

@michaelklishin - thoughts?

**Comment by michaelklishin** [comment]
@lukebakken our plan at some point was to develop a cross-platform OSS equivalent because the worst part about `handle.exe` is that it is a black boxed controlled by a single person.

That said, using Powershell sounds like a great stop-gap measure to me.

**Comment by lukebakken** [comment]
@wsficke yes, that is what I did here - https://github.com/rabbitmq/rabbitmq-server/pull/6614/files

Note that this method is *not* a drop-in replacement for `handle.exe` because powershell does not segregate handle count by type like `handle.exe` does.
