### ISSUE TITLE
AMQP 1.0 - support mandatory and publisher confirms

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#6669]
`amqp:not-found` could be returned in situations where `mandatory` would have been used in AMQP 0.9.1

@kjnilsson -

> This may be an opportunity to return the modified delivery state. Maybe it could be enabled as a Target capability request. This does mean it will be a link level configuration and not per message as in AMQP 0.9.1.

[Internal discussion](https://vmware.slack.com/archives/C0RDGG81Z/p1667828392961979)

**Comment by ansd** [comment]
done in https://github.com/rabbitmq/rabbitmq-server/pull/8015
