### ISSUE TITLE
Priority queue does not sensibly report ram duration, queue might not page out under memory pressure

### ISSUE THREAD

**Issue by simonmacmullen** [rabbitmq/rabbitmq-server#67]
Noticed while working on #65.

The priority queue `ram_duration/1` implementation takes the *sum* of all the ram durations of the sub-queues. That means, if a single sub-queue has a ram duration of `infinity` (which is very likely!) then the entire queue does.

I didn't really think that through. The point of what we're trying to do here is identify fast-moving queues so they can use more ram. Ideally each sub-queue would have its own ram duration, but in the absence of that we should probably take the minimum of the sub-queue ram durations, not the sum of them.

**Comment by dumbbell** [comment]
Since 3.5.0.
