### ISSUE TITLE
Delete Queue Button should be red and read "Delete Queue" instead of "Delete" 

### ISSUE THREAD

**Issue by dkoen** [rabbitmq/rabbitmq-server#670]
We had an issue with permissions where someone meant to purge a queue and accidentally clicked the delete button which caused us some minor problems. Would it be possible to make the difference between the buttons more clear? As it stands it's pretty hard to tell (popup withstanding).

**Comment by michaelklishin** [comment]
This belongs to https://github.com/rabbitmq/rabbitmq-management/.
