### ISSUE TITLE
Node not running

### ISSUE THREAD

**Issue by iveeshal** [rabbitmq/rabbitmq-server#677]
Hi ,

I have a federated clustered of two nodes. When I see the admin panel it says one node is down but when i manually go and see the other nodes ,its up and running  and vice-versa for admin panel for other nodes. What can be the possible problem? Is clustering
![prod_status](https://cloud.githubusercontent.com/assets/7278834/13554542/7e508858-e3d0-11e5-8d0d-415edfb6e406.png)
 not working?

**Comment by michaelklishin** [comment]
Please ask questions on rabbitmq-users. I'm not sure what "federated clustered" means as federation links do not appear as cluster nodes (they are not cluster members). So please clarify that part in the mailing list thread.
