### ISSUE TITLE
Configured IP address gets lost somewhere in ETS_TABLE

### ISSUE THREAD

**Issue by fin-ger** [rabbitmq/rabbitmq-server#6836]
I am currently investigating on an issue regarding the `rabbitmq-diagnostics listeners` and `check_port_connectivity` commands. Both commands **always** report the binding interface for all ports to be `[::]` regardless of the configuration. On my setup this leads to failed connectivity checks although the ports are open and running.

I investigated the code and first found that the `check_port_connectivity` is [not using the configured binding interface but instead is resolving the hostname](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/diagnostics_helpers.ex#L15) to connect to a service port.

However, this logic is not used to create the console output of `listeners` which explicitly states that all services are running behind `[::]`. I investigated where this output is produced and found out that the code [reads the interface (or ip-address) from a `listener` record](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_cli/lib/rabbitmq/cli/core/listeners.ex#L67).

I figured out that this [`listener` record is fetched](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/commands/listeners_command.ex#L44) from [the `ETS_TABLE`](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_networking.erl#L469).

I checked the contents of the `ETS_TABLE` with

```console
$ rabbitmqctl eval 'lists:nth(1, ets:tab2list(rabbit_listener_ets)).'
{listener,'rabbit@myhost',http,"myhost.my.domain",
          {0,0,0,0,0,0,0,0},
          15672,
          [{cowboy_opts,[{sendfile,false}]},{ip,"127.0.0.1"},{port,15672}]}
```

I found the [definition for the `listener` type in the `ETS_TABLE`](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_table.erl#L424) which references the [`listener` record](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit_common/include/rabbit.hrl#L109). This shows that the IP address is the fourth element in the record, so it should be `{0,0,0,0,0,0,0,0}` as derived from the output. However, this is wrong. I explicitly set this to `127.0.0.1` (e.g. via `prometheus.tcp.ip = 127.0.0.1` and `management.tcp.ip = 127.0.0.1`). In fact, the value is always `{0,0,0,0,0,0,0,0}` regardless of configuration.

I searched further and first found that [the IP address is missing from the type definition](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit_common/src/rabbit_types.erl#L94). Second, the `listener` instance used to create and start a `tcp_listener` is altered in a couple of functions before being inserted into the `ETC_TABLE`. After a [listener has been successfully started](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_web_dispatch/src/rabbit_web_dispatch_registry.erl#L140) a [`listener_info` is created](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_web_dispatch/src/rabbit_web_dispatch_registry.erl#L149) which [somehow fetches the `IPAddress` from the `Port`](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_networking.erl#L178). I did not fully understand this code and don't know whether a fault occurs here. After that, the new listener is being [registered in the `ETS_TABLE`](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_networking.erl#L359). The data stored after this point seems to be faulty as the data read from the `ETS_TABLE` does not include the correct binding interface. It has to be noted that all services are running on the correct ports and interfaces (checked with `netstat`). Only the data in the `ETS_TABLE` is wrong.

As I do not know Erlang nor Elixir, I am not sure whether my analysis is correct, however I think that the handling of the `ip_address` field in the `listener` record is wrong. First during registration of the listener in the `ETS_TABLE` and later when using the `listener` record in the diagnostics tools.

**Comment by lukebakken** [comment]
What version of RabbitMQ and Erlang are you using?

**Comment by michaelklishin** [comment]
What configuration can we use to reproduce?

**Comment by michaelklishin** [comment]
CLI tools [health check](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_cli/lib/rabbitmq/cli/diagnostics/diagnostics_helpers.ex#L15) is not aware of the interface configuration. It does what most clients would do: connect using a hostname and a port. What specific interface should be used to connect is out of scope for most clients and this health check.

To analyze the rest of the code flow we need to know what configuration you've used and what your expectations are.

**Comment by fin-ger** [comment]
> What specific interface should be used to connect is out of scope for most clients and this health check.

IMHO this must be documented. Additionally, giving the interface in the console output is misleading as it suggests that the interface address is used to connect to the service. However, the value here will be whatever the hostname resolves to. Additionally, I think this is not what most people do. I think, most people have HTTP APIs behind a reverse proxy. The URL and domain of the reverse proxy are completely unknown to rabbitmq. Using the hostname for connections is IMHO a wild guess. I would expect rabbitmq to just use the IP address that is configured in the configuration file. Any other connectivity checks are out of scope for rabbitmq.

**Comment by michaelklishin** [comment]
In what console output? It's one thing if it's listed in listener information and another in the check itself.

@fin-ger you are making wild claims about what most people do or do not do. I will make one, too: you are the first person to complain about this check in a couple of years of its existence.

Most people do not override listeners, and listeners can be configured to use `::` or `0.0.0.0`, what IP address should the check use then?

I'll how realistic it might be to use a specific IP address if it's available but to me
it sounds like you should build your own health check, as a RabbitMQ plugin or an external tool of any kind.
