### ISSUE TITLE
CLI: check_port_connectivity could use specific IP addresses for listeners that are configured to use one

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#6852]
See #6851 for the background.

For listeners that use `::` or `0.0.0.0` hostname resolution is the only "automatic" approach
but if a listener is bound to a particular address, that actual address can be used
instead of hostname resolution.

**Comment by lukebakken** [comment]
https://github.com/rabbitmq/rabbitmq-server/discussions/6851#discussioncomment-4657719

**Comment by ikvmw** [comment]
mind if I take it?

**Comment by michaelklishin** [comment]
@ikvmw no, feel free
