### ISSUE TITLE
Introduce optional parameters for 'rabbitmqctl list_queues', to filter down/up queues.

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-server#688]
Initially proposed as part of #357.

Adding optional parameters for `list_queues` to display up or down queues only would also be useful. Possible usage would maybe be as follows; 
`list_queues [--up] [--down] [-p <vhostpath>] [<queueinfoitem> ...]`

**Comment by binarin** [comment]
I'm going to implement it for `master` in https://github.com/rabbitmq/rabbitmq-server/pull/683
Is the `stable` version needed at all or it could just wait for the PR above?

**Comment by michaelklishin** [comment]
@binarin we wouldn't mind shipping it in `3.6.x`.

**Comment by binarin** [comment]
`rabbit_cli.hrl` contains `--offline` and `--online` options, may I use them instead of `--down` and `--up`?

**Comment by michaelklishin** [comment]
@binarin that sounds reasonable. I wouldn't mind using `--available` and `--unavailable` over `--up` and `--down` if we were after the most descriptive names.

I personally think that `--online` and `--offline` are good enough.
