### ISSUE TITLE
Consider making rabbitmqadmin available in PATH for Debian and RPM packages

### ISSUE THREAD

**Issue by wyardley** [rabbitmq/rabbitmq-server#692]
I get that you may want to pre-configure it for the right URL, but it would be great if you could ship some kind of version of rabbitmqadmin suitable for config management packages to install or modify (even if it's a template of some sort, or only has default values, e.g., localhost / 15672 in default options).

For example, in Puppet, it has to do a curl of the admin interface using a username to connect in order to get the file, which seems like a really kludgy way to do it:
https://github.com/puppetlabs/puppetlabs-rabbitmq/blob/master/manifests/install/rabbitmqadmin.pp
https://tickets.puppetlabs.com/browse/MODULES-3098

**Comment by michaelklishin** [comment]
It's a zero-dependency Python script. Why not bundle it with the Puppet module?

Producing a .deb package for `rabbitmqadmin` sounds like an overkill. I'm inclined to think we should consider making it available on `PATH` in the server package.

**Comment by wyardley** [comment]
The Puppet module (and presumably modules for other config management tools) may manage multiple versions of RabbitMQ, which I would think might be the reason they're pulling it from the admin interface?
I wasn't suggesting having it as a separate package, but including the file in the server package would be fantastic, and I imagine would make things easier.

**Comment by michaelklishin** [comment]
Fair enough. `rabbitmqadmin` and the HTTP API do not change often, and if they simply were in `PATH` it would take care of versioning anyway.
