### ISSUE TITLE
Incorrect output for down queues

### ISSUE THREAD

**Issue by epretha** [rabbitmq/rabbitmq-server#696]
In a cluster of two nodes (in this example), the following incorrect output was displayed for the rabbitmqctl command to list all the queues:

```
user@VirtualBox:$ ./rabbitmqctl -n hare list_queues name state durable pid
Listing queues ...
t_queue_4   running false   <hare@VirtualBox.2.758.0>
t_queue_3   running false   <hare@VirtualBox.2.754.0>
d_queue_4   running true    <hare@VirtualBox.2.750.0>
d_queue_3   running true    <hare@VirtualBox.2.746.0>
d_queue_2   [name, state, durable, pid] true    <rabbit@VirtualBox.2.215.0>
d_queue_1   [name, state, durable, pid] true    <rabbit@VirtualBox.2.212.0>
task_queue  [name, state, durable, pid] true    <rabbit@VirtualBox.2.209.0>
```

The last three queues d_queue_2, d_queue_1 and task_queue are down and the output for the "state" item for those three queues is displayed as a list of the queue items we sent with the rabbitmqctl command.

Kindly note that the incorrect output happens only for the remote durable queues that are down.

In order to reproduce the problem, please follow the following steps:

1. Start new RabbitMQ nodes named "rabbit" and "hare".
2. Cluster together both the "rabbit" and "hare" nodes.
3. Create some transient and durable queues on both the nodes.
4. Run "./rabbitmqctl -n rabbit stop_app" to stop the application on the "rabbit" node. Now, the durable queues on the "rabbit" node will be seen as down queues on the "hare" node.
5. Run the command "./rabbitmqctl -n hare list_queues name state durable pid" as shown above to get the strange output.

**Comment by michaelklishin** [comment]
Fixed in rabbitmq/rabbitmq-common#75.
