### ISSUE TITLE
Investigate support for mixed Erlang versions in a cluster

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#698]
We are constrained by the compatibility of internal OTP libraries that we currently use, namely `mnesia` and `global`, between major OTP releases. It would be great if we could support at least a range of versions, e.g. 17.x and 18.x.

**Comment by hairyhum** [comment]
We have started cluster with erlang versions `17.0` and `18.3`.
We did tests on `mnesia` and `global` apps.
Then we have started RabbitMQ cluster of two nodes (17.0 and 18.3) and run java functional and server tests.
Also tested a bit using management and mirrored queues.
Everything worked for this setup.

**Comment by michaelklishin** [comment]
Thanks. We need to find out if Mnesia has an inter-node communication protocol versioning.

Given that 3.6.x supports R16B03, it's worth testing with that version instead of 17.0, too. Or all 3 of them.

Also note that `ant test-functional` in the Java client repo does not use mirrored queues, there is a separate set suite/setup scenario for that and it's going to be tricky to coerce it into using different VMs.

**Comment by hairyhum** [comment]
Same tests work with `R16B03`.

**Comment by hairyhum** [comment]
According to `mnesia` [changelog](http://erlang.org/doc/apps/mnesia/notes.html), it can have incompatible versions, but changelog is only way to know it.

**Comment by michaelklishin** [comment]
Surely we can spend some time (a couple of days, for example) to
investigate Mnesia internals to see if they have any internal communication
versioning that we can track. Change logs are great but they are rarely
written well, or have 100% of the changes listed.

On Tue, Mar 22, 2016 at 6:19 PM, Daniil Fedotov <notifications@github.com>
wrote:

> According to mnesia changelog
> <http://erlang.org/doc/apps/mnesia/notes.html>, it can have incompatible
> versions, but changelog is only way to know it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rabbitmq/rabbitmq-server/issues/698#issuecomment-199861899>
>



-- 
MK

Staff Software Engineer, Pivotal/RabbitMQ

**Comment by hairyhum** [comment]
Looks like `mnesia` have `protocol_version`, that can be accessed using `mnesia:system_info(protocol_version)`. 
Mnesia supports communication with two versions, so called `current` and `previous`. 
Only current version can be accessed directly, while previous is using during `mnesia_monitor:negotiate_protocol(Nodes)` when adding new nodes.
Last changes in protocols were:

| OTP version | previous | current |
| ----------- |:--------:| -------:|
| R14B04      | 7,6      | 8,0     |
| R15B        | 8,0      | 8,1     |
| 18.2.3      | 8,1      | 8,2     |

**Comment by michaelklishin** [comment]
I suggest that we use that to negotiate version compatibility (the same "current version" is accepted).
8.1 and 8.2 can be considered compatible if we are confident they are for our needs. This means testing RabbitMQ version upgrades on mixed Erlang versions.

In the docs we should perhaps recommend the same thing we do today, for now. So this will be a change primarily for PCF that we consider an experiment.

**Comment by michaelklishin** [comment]
After spending some time on this, alternatively we could do the following: eliminate the restriction and log warnings when major Erlang versions and/or Mnesia protocol versions do not match. So, turn the requirement into a recommendation.

**Comment by hairyhum** [comment]
We can check known nodes for protocol compatibility by calling `negotiate_protocol`, which will return list of compatible nodes, so we don't need to explicitly check protocol version.

**Comment by michaelklishin** [comment]
@hairyhum we really care about the list of *incompatible* nodes. Are they also returns or do we have to rely on the total cluster member list?

**Comment by hairyhum** [comment]
We can do this:
```
get_incompatible_nodes(KnownNodes) ->
    CompatibleNodes = mnesia_monitor:megotiate_protocol(KnownNodes),
    KnownNodes -- CompatibleNodes.
```
