### ISSUE TITLE
RABBITMQ_IO_THREAD_POOL_SIZE is ignored on rabbitmq-server.bat

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-server#705]
`rabbitmq-server.bat` tests [`RABBITMQ_IO_THREAD_POOL_SIZE` ](https://github.com/rabbitmq/rabbitmq-server/blob/rabbitmq-server-703/scripts/rabbitmq-server.bat#L100)  and sets   [`RABBITMQ_IO_THREAD_POOL_ARG`](https://github.com/rabbitmq/rabbitmq-server/blob/rabbitmq-server-703/scripts/rabbitmq-server.bat#L101) 

Currently it does not work:
  ```
   {os,{win32,nt}},
     {erlang_version,"Erlang/OTP 18 [erts-7.2.1] [64-bit] [smp:2:2] [async-threads:0]\n"},

```
As [`rabbitmq-service.bat`](https://github.com/rabbitmq/rabbitmq-server/blob/rabbitmq-server-703/scripts/rabbitmq-service.bat#L168), the correct one is `RABBITMQ_IO_THREAD_POOL_SIZE` used on [startup](https://github.com/rabbitmq/rabbitmq-server/blob/rabbitmq-server-703/scripts/rabbitmq-server.bat#L123) 

At this point `RABBITMQ_IO_THREAD_POOL_ARG` on `rabbitmq-server.bat` is unnecessary.

**Comment by michaelklishin** [comment]
Fixed by @Gsantomaggio in #708. Thank you!
