### ISSUE TITLE
script/rabbitmq-env: error during installation on Ubuntu 14.04

### ISSUE THREAD

**Issue by FrancescoErmini** [rabbitmq/rabbitmq-server#707]
On Ubuntu 14.04 LTS, when running the package rabbitmq-server v 3.6.1-1 the installation process stop and the given error is:

``/usr/lib/rabbitmq/bin/rabbitmq-env: eval: line 127: syntax error near unexpected token `(' ``

The line with the issue is:

` eval "$var=$(rmq_normalize_path "$path")" `

I think it's a portability issues caused by bash (see [http://wiki.bash-hackers.org/commands/builtin/eval#portability_considerations](url) )  but I'm not able to solve it. 

I wonder if this could be a bug, If it's not sorry for the opened issue.

**Comment by michaelklishin** [comment]
I installed our Debian package on the same Ubuntu release just yesterday. I believe it was vanilla Ubuntu, so the shell should be `dash`.

Do you do anything beyond installing the package? What if you try a generic UNIX binary build?

**Comment by FrancescoErmini** [comment]
I don't change dash (bin/sh -> dash as default). But I change the first line of 
`/etc/init.d/rabbitmq-server` from #!/bin/sh to #!/bin/bash as I get the same error.

I didn't try the unix binary build, but I will. 

Anyway if you hadn't problems, it mean there is an error on my enviroment....so it is not an issue

**Comment by michaelklishin** [comment]
We haven't heard of any similar reports, and Debian packages are possibly the most common way of deploying RabbitMQ. That said, it would be interesting to get to the root cause, so lets keep this open.

**Comment by FrancescoErmini** [comment]
Ok, the distribution it's an Ubuntu server that run on VM. Tomorrow (or tonight) I will create a new, fresh VM and try to install the package again, then I'll update.

**Comment by FrancescoErmini** [comment]
Sorry for the late reply. I did a fresh installation of ubuntu and then install rabbitmq-server via apt package manager and everything just work fine.  
Thanks! it's ok now to close the issue?

**Comment by michaelklishin** [comment]
OK, thank you for the update.
