### ISSUE TITLE
rabbitmq-server.ocf deletes /var/run/rabbitmq directory

### ISSUE THREAD

**Issue by jmcmeek** [rabbitmq/rabbitmq-server#71]
When the rabbitmq-server pacemaker resource agent deletes the pid file, it also deletes the entire /var/run/rabbitmq directory.   On RHEL 7, using the systemctl service, if I want to use systemctl to work with the resource after using pacemaker, I have to recreate that directory and set the owner before I can start rabbitmq-server as a service again.

**Comment by dumbbell** [comment]
@jmcmeek, I'm looking at this issue but I don't know Pacemaker.

Currently, `/var/run/rabbitmq` is handled by the init script, not the package. So after a fresh install or after stopping RabbitMQ, this directory is missing.

Could you please explain to me how Pacemaker works and why it needs this directory to be there, even if the pidfile is missing?

**Comment by jmcmeek** [comment]
Its not the pacemaker agent that requires the directory.  The problem is using the agent on RHEL 7 with the systemd systemctl command.  The RHEL 7 systemd scripts expect /var/run/rabbitmq to be created during install of the rabbitmq-server RPM.  Since the pacemaker resource agent deletes the directory, you cannot later run "systemctl start rabbitmq-server" without first recreating that directory and setting proper permissions.

**Comment by dumbbell** [comment]
The init script is supposed to create `/var/run/rabbitmq` on startup and delete it on shutdown, like the OCF Resource Agent script. See:
* [`packaging/RPMS/Fedora/rabbitmq-server.init`, line 42](https://github.com/rabbitmq/rabbitmq-server/blob/stable/packaging/RPMS/Fedora/rabbitmq-server.init#L42)
* [`packaging/RPMS/Fedora/rabbitmq-server.init`, line 62](https://github.com/rabbitmq/rabbitmq-server/blob/stable/packaging/RPMS/Fedora/rabbitmq-server.init#L62)

I tested this again on Fedora 21 with RabbitMQ 3.5.0 RPM downloaded from www.rabbitmq.com and it worked. What version of RabbitMQ are you using?

**Comment by michaelklishin** [comment]
Closing after 90 days of inactivity.
