### ISSUE TITLE
Strip (or reject) line feeds from queue/exchange/etc names

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#710]
The spec says queue and exchange names must only contain ASCII characters. This does include line feeds, which should be stripped off, because they create [usability issues](https://github.com/rabbitmq/rabbitmq-management/issues/140#issuecomment-202288489) similar to [this one](https://groups.google.com/forum/#!searchin/rabbitmq-users/unprintable/rabbitmq-users/IhxqihCO3cc/zp7wtqKDoyYJ): it is non-trivial to delete such queue.

The right thing to do is to strip off line feeds in the server as opposed to working around it in CLI tools and HTTP API independently.

**Comment by davidvanlaatum** [comment]
While stripping is better could also cause issues for things that inspect the queues and then don't find a match. I would personally error at them

**Comment by michaelklishin** [comment]
@davidvanlaatum my idea was to strip them across the board. But thank you for the suggestion, responding with an error is also an option. We already perform basic queue name validation and had to deviate from the spec slightly where it improved usability.

**Comment by hairyhum** [comment]
By the way, current implementation does not require exchange and queue names to be ASCII. 
https://github.com/rabbitmq/rabbitmq-common/blob/master/src/rabbit_channel.erl#L834

**Comment by michaelklishin** [comment]
@hairyhum yes, and it is too late to add significant restrictions but stripping off line feeds and possibly unprintable characters makes sense. We only see people shooting themselves in the foot with both.

**Comment by naag** [comment]
How about tabs? We've seen some cases where users copy pasted queues names from the management interface into the "Move messages" > "Destination queue" field and ended with queues with tabs in front of the queue name. If the queue name is longer than the display length of the input field, the user will not see that there's a tab at the beginning.

**Comment by michaelklishin** [comment]
@naag not covered by this issue. Can be considered for 3.7.0 in a follow-up one. With tabs it's less obvious if they may serve a useful purpose. Please start a rabbitmq-users thread so we can discuss?

**Comment by naag** [comment]
@michaelklishin Ok, I'll do that!
