### ISSUE TITLE
Target QQ replica count policy

### ISSUE THREAD

**Issue by SimonUnge** [rabbitmq/rabbitmq-server#7110]
Currently rabbitmq only stores the `x-quorum-initial-group-size` - or defaults to
3 if missing. But this value can not be changed.

Suggestion: Add an policy `target-qq-replica-count <size>`

This value can be used for future features such as automatically add node to QQ group when a node is added to a
cluster, if the current group size is less than target-qq-replica count.

Register as operator policy and add to default_policy.operator in Cuttlefish

**Comment by michaelklishin** [comment]
Sounds reasonable. We have a target node count hint in `rabbitmq.conf` for similar reasons but only use it lightly in some tooling at the moment.

**Comment by michaelklishin** [comment]
Team RabbitMQ decided that this cannot be done in a "one step at a time" manner and needs a single issue that will serve as a design document. I will put together something that would capture our current understanding of the goal of dynamic QQ replica management with the goal of maintaining an operator-set minimum.
