### ISSUE TITLE
Lock operator policies from HTTP API

### ISSUE THREAD

**Issue by illotum** [rabbitmq/rabbitmq-server#7131]
Since in certain environments the infrastructure operators do not get accounts _in_ RabbitMQ, I'd like to add a config switch that prohibits operator policies from being changed via HTTP API. Tentatively `prohibit_remote_operator_policies=true`

Broker will return a well-formed error to `PUT /api/operator-policies`, and the only way to set them becomes by accessing the host: either via rabbitmqctl, or #6687.

Perhaps extra work may be done to hide operator policies from 'policymaker's in the web console as well.

---

I briefly considered adding instead a new type of policies, say "global", to enforce cross-vhost limits. This feels a bit redundant, but I'm open to all arguments.

**Comment by michaelklishin** [comment]
Disabling this kind of feature is fine.

`operator_policies.enabled = (boolean)` is what I'd use.

**Comment by illotum** [comment]
How about then migrating `default_policies.operator` into `operator_policies.default`? With a bit of data transformation cuttlefish allows both mappings to co-exist.

**Comment by michaelklishin** [comment]
Addressed in #7165.
