### ISSUE TITLE
Issue with Limit Tab in 3.11.8

### ISSUE THREAD

**Issue by fontexD** [rabbitmq/rabbitmq-server#7142]
im using the latest RabbitMQ 3.11.8 in k8s.

im getting this error in the limit tab, tried just about everything which google have of solutions

![rabbitmq-admin-limit](https://user-images.githubusercontent.com/514926/216068212-5d004487-3fe3-4138-991c-428f5eb92e84.png)

had the same issue for the user tab to start with, but a refresh of the browser cache fixed that, but cant seem to get it to work on limit tab this is my cm

```
enabled_plugins: |
[rabbitmq_federation,rabbitmq_management,rabbitmq_peer_discovery_k8s,rabbitmq_prometheus].
rabbitmq.conf: |
loopback_users.guest = false
listeners.tcp.default = 5672
cluster_formation.peer_discovery_backend = k8s
cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
cluster_formation.k8s.address_type = hostname
```

ref to issue created in rabbitmq:docker

https://github.com/docker-library/rabbitmq/issues/603

issue replicated by another user, so it shouldt be related to running containerized

**Comment by lukebakken** [comment]
* Please browse to that URL using incognito mode
* Please do the same using Firefox

**Comment by fontexD** [comment]
just tested with 3.11.7 everything works perfect there!

with 3.11.8 firefox

TypeError: users.items is undefined this.process@http://192.168.1.222:15672/js/ejs-1.0.min.js line 1 > eval:149:59 render@http://192.168.1.222:15672/js/ejs-1.0.min.js:1:1885 format@http://192.168.1.222:15672/js/main.js:1156:21 with_update/<@http://192.168.1.222:15672/js/main.js:461:30 with_reqs@http://192.168.1.222:15672/js/main.js:1138:12 with_reqs/<@http://192.168.1.222:15672/js/main.js:1134:26 with_req/req.onreadystatechange@http://192.168.1.222:15672/js/main.js:1215:20 

incognito chrome

TypeError: Cannot read properties of undefined (reading 'length') TypeError: Cannot read properties of undefined (reading 'length') at Array.process (eval at compile (http://192.168.1.222:15672/js/ejs-1.0.min.js:1:6654), :149:75) at EJS.render (http://192.168.1.222:15672/js/ejs-1.0.min.js:1:1885) at format (http://192.168.1.222:15672/js/main.js:1156:21) at http://192.168.1.222:15672/js/main.js:461:24 at with_reqs (http://192.168.1.222:15672/js/main.js:1138:9) at http://192.168.1.222:15672/js/main.js:1134:17 at req.onreadystatechange (http://192.168.1.222:15672/js/main.js:1215:17)

**Comment by lukebakken** [comment]
I can reproduce this issue, and PR https://github.com/rabbitmq/rabbitmq-server/pull/6990 introduced it.
