### ISSUE TITLE
rabbitmqctl set_disk_free_limit mem_relative docs have wrong parameter range

### ISSUE THREAD

**Issue by bdshroyer** [rabbitmq/rabbitmq-server#716]
From the documentation for `rabbitmqctl set_disk_free_limit` `mem_relative` `fraction`:

"Fraction: Limit relative to the total amount available RAM as a non-negative floating point number. Values lower than 1.0 can be dangerous and should be used carefully."

However, when you try to set the memory-relative disk free limit to 1.0 or higher, you get the following error:

```
Error: {{function_clause,
            [{rabbit_resource_monitor_misc,parse_information_unit,
                 [{mem_relative,1.0}],
                 [{file,"src/rabbit_resource_monitor_misc.erl"},{line,29}]},
             {rabbit_disk_monitor,interpret_limit,1,
                 [{file,"src/rabbit_disk_monitor.erl"},{line,241}]},
             {rabbit_disk_monitor,set_disk_limits,2,
                 [{file,"src/rabbit_disk_monitor.erl"},{line,188}]},
             {rabbit_disk_monitor,handle_call,3,
                 [{file,"src/rabbit_disk_monitor.erl"},{line,145}]},
             {gen_server,try_handle_call,4,
                 [{file,"gen_server.erl"},{line,629}]},
             {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},
             {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},
        {gen_server,call,
            [rabbit_disk_monitor,
             {set_disk_free_limit,{mem_relative,1.0}},
             infinity]}}
```

I am assuming that `rabbit_disk_monitor` is correct, and that the memory-relative option should be between 0 and 1. Assuming that values lower than 1.0 are indeed dangerous (which makes sense), perhaps the documentation should be something like:

"Fraction: The limit relative to the total amount of available RAM as a floating-point number between 0.0 and 1.0. This option can be dangerous and should be used carefully--if you are unsure, use an absolute disk limit."

**Comment by michaelklishin** [comment]
@bdshroyer values lower than 1.0 are dangerous because this means RabbitMQ and the OS cannot swap out all or even most of the data. This `function_clause` is probably an issue in `rabbit_resource_monitor_misc:parse_information_unit/1`, it (or another function that calls it) simply [doesn't expect to get this value](https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit_resource_monitor_misc.erl).

So it's not the docs that are not correct, it's a bug.

**Comment by bdshroyer** [comment]
Okay. I'll open a new issue then.

**Comment by michaelklishin** [comment]
OK, thank you.
