### ISSUE TITLE
OAuth 2: support variable expansion for topic authorisation

### ISSUE THREAD

**Issue by OLibutzki** [rabbitmq/rabbitmq-server#7178]
Currently variable expansion is only supported by the internal authorisation backend. As discussed with @ansd [here](https://github.com/rabbitmq/rabbitmq-server/discussions/7145#discussioncomment-4861372), it makes sense in the context of `rabbit_auth_backend_oauth2`, too.

As a practical example, I currently have to add a lot of client scopes in order to build specific permissions per user. Having a Client scope which contains `{username}` would easy this setup a lot.

**Comment by MarcialRosales** [comment]
The expansion variables could be:
- `username` whose value is determined by the [Preferred username claims](https://github.com/rabbitmq/rabbitmq-oauth2-tutorial#preferred-username-claims)
- `vhost`
-  or probably any claim of type `string`. For instance, `sub` or `client_id`. Most likely if there is a `username` claim, it is going to be part of one of [Preferred username claims](https://github.com/rabbitmq/rabbitmq-oauth2-tutorial#preferred-username-claims)

E.g. Given a token with the claim `client_id: abz` and scope `rabbitmq.read:*/{client_id}-*` means it has read access on any queue whose name starts with `abz-` on any vhost.

**Comment by ansd** [comment]
> Given a token with the claim client_id: abz and scope rabbitmq.read:*/{client_id}-* means it has read access on any queue whose name starts with abz- on any vhost.

@MarcialRosales this feature request is only about [topic authorisation](https://www.rabbitmq.com/access-control.html#topic-authorisation) - not about queues.

**Comment by OLibutzki** [comment]
Using any claim of type `string` would be great as it makes the solution much more flexibel.
