### ISSUE TITLE
rabbitmq-server.ocf stop action returns before the rabbitmq processes have stopped

### ISSUE THREAD

**Issue by jmcmeek** [rabbitmq/rabbitmq-server#72]
When pacemaker attempts to restart rabbitmq and rabbbitmq is already running, the start request frequently fails.  I found that the previous beam.smp process was still running when the resource agent attempted to start rabbitmq-server.

I saw that the initd script does a "rabbitmqctl stop <pidfile>".  Adding the pidfile parameter to the resource agent appears to fix this problem.

**Comment by michaelklishin** [comment]
Sorry, this is not specific enough. Adding what exactly to what file? (feel free to submit a pull request, by the way)

**Comment by jmcmeek** [comment]
This is in https://github.com/rabbitmq/rabbitmq-server/blob/master/packaging/common/rabbitmq-server.ocf
in rabbit_stop:

302  $RABBITMQ_CTL stop  <=  add $RABBITMQ_PID_FILE

When I get approval from our legal folks to do so, I can look at submitting a pull request.

**Comment by dumbbell** [comment]
I think it's reasonable and would even be consistent with the init scripts from the RPM and Debian packages which already do this.
