### ISSUE TITLE
RABBITMQ_ERLANG_COOKIE deprecation

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#7262]
Examples of user confusion:
* https://serverfault.com/a/1090276/227908
* https://stackoverflow.com/q/75420212/1466825
* https://groups.google.com/g/rabbitmq-users/c/oPAJIe3Cea8
* https://github.com/docker-library/rabbitmq/issues/506#issuecomment-887786516
* https://github.com/docker-library/rabbitmq/issues/508
* https://github.com/docker-library/rabbitmq/pull/467

In RabbitMQ Server, there is no warning when the `RABBITMQ_ERLANG_COOKIE` environment variable is used, but there is a warning printed when a CLI tool uses it:

https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_cli/lib/rabbitmq/cli/core/distribution.ex#L115-L137

Furthermore, it is _not_ listed as deprecated by the docker image:

https://github.com/docker-library/rabbitmq/blob/master/docker-entrypoint.sh#L13-L29

Personally I think the deprecation warning should be removed and support for the existing `RABBITMQ_` env vars preserved.

@dumbbell @michaelklishin ?

**Comment by michaelklishin** [comment]
@lukebakken we can change the warning to day that environment variable use is not recommended over other options and keep what we currently support but not anything else beyond the already added default user credential vars. WDYT?

**Comment by tijoer** [comment]
I was using the "docker -e RABBITMQ_ERLANG_COOKIE=xxx" command mainly to setup a testing environment. The way to handle this in such a scenario is fine for me and in a production environment I would fall back to proper secrets management. However getting the warning that this feature will get removed soon is kind of a bummer, as this means that all tests WILL break soon.

PS: Thanks for your work on this :). Loving RabbitMQ so far.
