### ISSUE TITLE
Feature Request: Improve trailing comma behavior or error message in .config?

### ISSUE THREAD

**Issue by Ashtonian** [rabbitmq/rabbitmq-server#730]
Right now the json config seems a bit strict in that if you leave a trailing comma after adding a line to the config it blows up. 

* Can the json configuration be altered to accept a trailing comma?  
* If not, alternatively could the error message be improved to be more specific?  "could not start kernel pid (application_controller) (error in config file "somepath" (362): syntax error before: ']')" indicates that there is a problem on line 362 but due to comments the actual error is ~100 or so lines above that and it can be very confusing if you don't know to expect this behavior in the first place.

**Comment by michaelklishin** [comment]
Both aspects are actually part of Erlang, not RabbitMQ.

I believe this is addressed by the [new config format](https://groups.google.com/forum/#!topic/rabbitmq-users/uuZqn_4qXXM) that also involves validation and (to much lesser extent) #691.
