### ISSUE TITLE
provide config option value validation

### ISSUE THREAD

**Issue by bilsch** [rabbitmq/rabbitmq-server#733]
reference https://github.com/rabbitmq/rabbitmq-server/issues/732

the rabbitmq-server and other packages should provide configuration validation. At least checking for valid config option values would have saved me a lot of confusion and time googling for help.

**Comment by michaelklishin** [comment]
This is done to the extent we can in #550. We cannot validate every config option in the Erlang term format. #732 focusses on a few specific options.
