### ISSUE TITLE
Specify broker version requirements for community plugins maintained by Pivotal

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#735]
Now that #591 is merged, we can make community plugins maintained by our team specify broker version constraints.

When producing a release, we should specify the current release series. Note that for preview releases, the format is `a.b.c.d` and [the tests we have only cover `a.b.c`](https://github.com/rabbitmq/rabbitmq-test/pull/28/files).

**Comment by hairyhum** [comment]
Given release process we have right now, we can do this:
- for plugins that ship with rabbitmq and automatically versioned, we can automatically set required broker version to current version during build.
- for plugins that ship independently, we can set `3.7.0` and `3.6.0` as basic supported versions and update them manually if there are some incompatibilities or new rabbitmq minor version.

As the result, there will be broker requirement for exact same version in plugins, shipped with rabbitmq and custom requirements in independently shipped plugins.

**Comment by dumbbell** [comment]
Thanks a lot! This feature was badly needed!
