### ISSUE TITLE
Put channel log messages in their own log category

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#74]
Reproduce what is done for connection log messages.

This should be extended to other message sources.

**Comment by dumbbell** [comment]
The problem was reported on the mailing-list:
https://groups.google.com/d/topic/rabbitmq-users/F-Fbc7sxTrY/discussion

**Comment by dumbbell** [comment]
An update to the documentation on the website is ready:
rabbitmq-website@735c99268a1b619b14e45cd94b12a25dade05b1c

**Comment by michaelklishin** [comment]
@dumbbell perhaps you mean https://github.com/rabbitmq/rabbitmq-website/commit/735c99268a1b619b14e45cd94b12a25dade05b1c.

**Comment by dumbbell** [comment]
Yes, thanks!

**Comment by michaelklishin** [comment]
@dumbbell is this ready for QA? I don't see a pull request for it.

**Comment by dumbbell** [comment]
@michaelklishin, yes, it's ready.

**Comment by dumbbell** [comment]
Please QA the following PRs:
* rabbitmq/rabbitmq-server#81
* rabbitmq/rabbitmq-website#2

**Comment by michaelklishin** [comment]
I QA'ed this branch yesterday. Both PRs are now merged => closing.
