### ISSUE TITLE
Admin Interface Users Screen Appears Broken

### ISSUE THREAD

**Issue by coltonbh** [rabbitmq/rabbitmq-server#7425]
The web-based admin interface in `rabbitmq:3.9` images appears to be broken. It works in `3.8` images. I have tried running `rabbitmq:3.9-management` and `rabbitmq:3.9-management-alpine` images, both have the same broken UI. `3.8` images do not.

**To Reproduce**
Start a rabbitmq server using docker and visit the user interface at http://localhost:15672/, click "admin", then click "users" (the default screen). The following error results with a broken UI:

![Screenshot from 2023-02-24 12-51-37](https://user-images.githubusercontent.com/16160630/221290067-6f909935-2297-4ec0-a98e-6ef3369ebb2d.png)

**Comment by lukebakken** [comment]
Thanks, commit 952725bac85866f1974591d614c813267aedb587 introduced this bug.

cc @ikvmw

**Comment by michaelklishin** [comment]
This has already been addressed. There likely won't be any more 3.9 releases, just move to 3.11.

**Comment by michaelklishin** [comment]
@lukebakken I don't think this issue is present in 3.11.9

**Comment by coltonbh** [comment]
@lukebakken thank you very much! Somehow missed that `3.11` had been released. My bad for bringing up a non-current bug. I can confirm the UI works is `3.11`. 🙏

**Comment by michaelklishin** [comment]
@coltonbh no worries, it was a fairly recent issue indeed. You can always find out what release series are available and supported on the [RabbitMQ website](https://rabbitmq.com/versions.html).

**Comment by lukebakken** [comment]
It is only present in 3.9.28 and later. This is something that should be fixed.

**Comment by lukebakken** [comment]
> There likely won't be any more 3.9 releases

Yep this issue is 3.9.28 and later only. I didn't realize we weren't doing any more releases.

**Comment by michaelklishin** [comment]
We can and likely will for an unrelated reason (a fix can be backported) but OSS users should just upgrade to 3.11.
