### ISSUE TITLE
Default schema dir should not be in $RABBIT_HOME

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#750]
Related to [this discussion](https://groups.google.com/forum/#!topic/rabbitmq-users/qMfAwBWfCcI) in user group.
In some repos `$RABBIT_HOME` directory can be not writable by `rabbitmq` user, which cause errors when trying to add plugin schemas to this dir.
`SCHEMA_DIR` should be changed to some writable location.

**Comment by jcasale** [comment]
Do you think that location is maybe better defined as ${install_prefix}/var/lib/rabbitmq/schema? Seems its less config oriented but actually state oriented and a byproduct of configuration.

**Comment by michaelklishin** [comment]
It is not a by product of configuration: schema files ship with plugins and are static.

**Comment by jcasale** [comment]
Right,
Doesn't that mean the enabled_plugins file drives the resulting population and therefor it is "statefull" beling in the ${install_prefix}/var/lib/rabbitmq/* location?

**Comment by hairyhum** [comment]
I agree, it makes sense to put schema files to `/var/lib/rabbitmq`

**Comment by michaelklishin** [comment]
@hairyhum ok, please submit another PR if you'd like to change the path one more time.
