### ISSUE TITLE
Version 3.12 does not import a definitions file correctly

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#7532]
Original discussion starts here: https://github.com/rabbitmq/rabbitmq-server/pull/5895#issuecomment-1458231497

Project to reproduce:
https://github.com/lukebakken/rabbitmq-server-5895-mqtt

`docker compose up` will start up the `pivotalrabbitmq/rabbitmq:v3.12.0-beta.1-otp-max-bazel` and try to import definitions, which won't happen. It's not just docker, as this doesn't work either:

```
make RABBITMQ_CONFIG_FILE="/home/lbakken/development/lukebakken/rabbitmq-server-5895-mqtt/rabbitmq-local.conf" PLUGINS='rabbitmq_management rabbitmq_top' run-broker
```

`RABBITMQ_IMAGE='rabbitmq:3-management' docker compose up` works correctly.

cc @michaelklishin @janiu-001

**Comment by lukebakken** [comment]
I read the `definitions.json` file and `thoas:decode/1` works, so it's not that 😄

**Comment by lukebakken** [comment]
Aha, here's a BIG hint:

```
2023-03-07 16:11:20.252173-08:00 [info] <0.552.0> There are fewer than target cluster size (1) nodes online, skipping queue and binding import from definitions
```

**Comment by janiu-001** [comment]
@lukebakken  please let me know the new image if the fix is ready

**Comment by mkuratczyk** [comment]
Once https://github.com/rabbitmq/rabbitmq-server/pull/7535 is merged, it should be fixed

**Comment by michaelklishin** [comment]
@mkuratczyk has put together a different solution in https://github.com/rabbitmq/rabbitmq-server/pull/7535. The culprit ended up being #7058.

**Comment by janiu-001** [comment]
@michaelklishin  @mkuratczyk  which images could i use for testing?

**Comment by janiu-001** [comment]
@michaelklishin @mkuratczyk  which image is available for testing?
