### ISSUE TITLE
Consider members' syncing status in check_if_node_is_quorum_critical

### ISSUE THREAD

**Issue by tvhong-amazon** [rabbitmq/rabbitmq-server#7547]
> check_if_node_is_quorum_critical
> Health check that exits with a non-zero code if there are queues with minimum online quorum (queues that would lose their quorum if the target node is shut down).

I (and a few other developers I talked to) expect the command to work as follow:

* Say, a queue has replicas [a, b, c], ‘c’ is catching up, the quorum is [a, b].
* A `check_if_node_is_quorum_critical` call on 'a' and 'b' will return an error status, since losing either 'a' or 'b' will break the quorum.

However, this is not what we observed. `check_if_node_is_quorum_critical` on ‘a’ returns a success status (see example below).

If an operator terminates node ‘a’ or ‘b’ after checking `check_if_node_is_quorum_critical`, they can block the quorum queue until node ‘c’ is caught up. This is not a desirable outcome.

I believe the discrepancy is in how we understand “quorum”. In this case, we interpret quorum to only include nodes that have sufficiently caught up to the leader, whereas the command considers all member nodes to be part of the quorum regardless of syncing status.

In this case, does it make sense for `check_if_node_is_quorum_critical` to include a `--with-sync-status` flag that will consider the target node’s syncing status?

---
Example:
```
% rabbitmq-queues quorum_status test-queue-1
Status of quorum queue test-queue-1 on node rabbit@ip-10-0-20-16.us-west-2.compute.internal ...
┌──────────────────────────────────────────────────┬────────────┬───────────┬──────────────┬────────────────┬──────┬─────────────────┐
│ Node Name                                        │ Raft State │ Log Index │ Commit Index │ Snapshot Index │ Term │ Machine Version │
├──────────────────────────────────────────────────┼────────────┼───────────┼──────────────┼────────────────┼──────┼─────────────────┤
│ rabbit@ip-10-0-12-108.us-west-2.compute.internal │ follower   │ 39040     │ 28917882     │ undefined      │ 6    │ 2               │
├──────────────────────────────────────────────────┼────────────┼───────────┼──────────────┼────────────────┼──────┼─────────────────┤
│ rabbit@ip-10-0-20-16.us-west-2.compute.internal  │ follower   │ 28917882  │ 28917882     │ undefined      │ 6    │ 2               │
├──────────────────────────────────────────────────┼────────────┼───────────┼──────────────┼────────────────┼──────┼─────────────────┤
│ rabbit@ip-10-0-4-12.us-west-2.compute.internal   │ leader     │ 28917882  │ 28917882     │ undefined      │ 6    │ 2               │
└──────────────────────────────────────────────────┴────────────┴───────────┴──────────────┴────────────────┴──────┴─────────────────┘
```
```
% rabbitmq-queues check_if_node_is_quorum_critical --node rabbit@ip-10-0-20-16.us-west-2.compute.internal
Checking if node rabbit@ip-10-0-20-16.us-west-2.compute.internal is critical for quorum of any quorum queues ...
Node rabbit@ip-10-0-20-16.us-west-2.compute.internal reported no quorum queues with minimum quorum
```

**Comment by mkuratczyk** [comment]
It'd be a nice addition indeed. It is non-trivial though, since the target is moving - if messages are being published, it's not clear what "caught up" really means.

@kjnilsson suggests that we could implement the part of RAFT that says that members are non-voting until they at least reached the last index written at the time they joined. This is a well defined behaviour and would be a proxy for members being up to date.

**Comment by tvhong-amazon** [comment]
What if RabbitMQ allows users to specify the acceptable delta (in seconds) for nodes to be considered up-to-date?

I haven't looked deep into the code yet, but I'm guessing this can be implemented as a periodic check within each queue process. Every `delta` seconds, the queue process would compare its current index with the lastest index captured in the last period, and record an `is_fresh` metric. `check_if_node_is_quorum_critical` can then query this record upon execution.

An bonus of this implementation is that RabbitMQ can also expose this as a metric on Prometheus, or queue metadata on management API (similar to "synchronized_mirrors").

**Comment by mkuratczyk** [comment]
Given that RabbitMQ 4.0 is coming soon with mirrored queues removed altogether, I'm closing this issue since I don't expect it to ever be implemented. The idea is sound - if you want to contribute it to a 3.13.x patch release, we can discuss this, but it's been 1.5 years since the original report and no one started working on this.
