### ISSUE TITLE
More predictable and firm connection_max for limiting number of connections per RabbitMQ node

### ISSUE THREAD

**Issue by SimonUnge** [rabbitmq/rabbitmq-server#7593]
Today it is possible to limit maximum allowed connections per vhost, per user, or per node.

Running rabbitMQ as a service, having limits like this is very useful, to avoid brokers running out of memory. The current back pressure mechanism for high memory usage (memory alarm) does not stop clients from creating new connections, and thus have no real effect at improving memory usage. 

The per vhost and user logic is handled by rabbitmq, and is set via runtime configuration, and
works as expected, with a nice error when you hit the limit.

For node level connection limit, rabbitmq passes along the limit value, set as config, to ranch. The config parameter is 'connection_max', and its existence is not really advertised.

This works, but has a few drawbacks.
* It is a 'soft' limit, basically max_connections + the number of acceptors.
* Hitting the limit will result in ranch not accepting anymore connections. This will not result in further connections being rejected, and thus no with a user friendly error message, as the kernel option allows queueing incoming connections. Instead, the attempt to create a connection will hang until a timeout is reached.

Suggestion: Similar to how rabbitmq can be configured to limit connections per vhost or per user, add the option to also
limit number of connections per node, handled within rabbitmq, to give a nice informative reason to the client of why 
a connection request is not accepted.

**Comment by SimonUnge** [comment]
@michaelklishin Would like to hear your guys thoughts about a limit like this?

**Comment by michaelklishin** [comment]
I don't have any objections but why not use the same `connection_max` setting name?

**Comment by SimonUnge** [comment]
@michaelklishin Yes, my first draft implementation did use the same configuration setting. The issue with this, though, is that we then would hit the limit in rabbitmq, and ranch, at the same time. Which would start ranch to queue up the connections, so called 'sleepers', until the 10 acceptors are used, and subsequent connections would then hit the same timeout issue - i.e hanging connection attempt until client timeout triggers. 

Perhaps had a config, say, `node_connection_max` and leave `connection_max` as is (default to infinity) and put `node_connection_max` in the documentation and kinda leave connection_max hidden as is?

**Comment by michaelklishin** [comment]
@SimonUnge why not change the implementation but keep the key? If `node_connection_max` is for the node then what is `connection_max`?

It's a good question whether this should apply to all connections regardless of the protocol.

**Comment by SimonUnge** [comment]
Yes, changing the `connection_max` impact is of course also a good option. Was just not sure if that was an option or not. And thus remove the option to set ranch connection_max?

**Comment by michaelklishin** [comment]
If the goal is to add a hard connection limit, I guess the current `connection_max` can be treated (and aliased as) a soft connection max, and a new setting can be called a hard connection max.

If Ranch's `connection_max` does not work very well for us because the kernel will happily accept and queue inbound TCP connections, we indeed can stop using the option and instead
enforce the limit the same way we enforce `channel_max` in RabbitMQ's own code.

One open-ended question is how to keep track of the connections node-wide. By querying Ranch?

**Comment by SimonUnge** [comment]
Good question. Asking ranch, or perhaps rely on `rabbit_connection_tracking:list_on_node/1`?

**Comment by lhoguin** [comment]
Another option is to just keep using the Ranch limit and users can set the `backlog` TCP option to 0. This should prevent clients from being queued up waiting for the connection to be accepted, and they will receive a connect error instead. This won't give them a nice AMQP/protocol error but perhaps that's good enough?

**Comment by SimonUnge** [comment]
@lhoguin I did play with those settings, i.e max_connections to say 10, and backlog set to 0. But I see the same behaviour, i.e ranch allows 10+10 connections, then the connection attempt will hang until client timeout.

**Comment by SimonUnge** [comment]
@lhoguin OK, so you'd prefer using the data in ranch, rather than relying on `rabbit_connection_tracking:list_on_node/1`?

**Comment by lhoguin** [comment]
Yes asking Ranch should be more efficient I think.
