### ISSUE TITLE
open "http://localhost:15672/#/users" error

### ISSUE THREAD

**Issue by FebruaryZhang** [rabbitmq/rabbitmq-server#7596]
the error is this:
![image](https://user-images.githubusercontent.com/32325152/224624543-2b614ade-73ed-438a-ab36-14d5f4c858fb.png)
erlang version and rabbitmq version in the picture.

when i check api, i find this:
![image](https://user-images.githubusercontent.com/32325152/224624907-6ecf5aa0-69d8-4954-a61b-3350e27337dc.png)

**Comment by mkuratczyk** [comment]
This is indeed an issue on the 3.9 branch right now (seems like 3.9.28 and 3.9.29 are affected). The fastest solution is to upgrade to 3.10/3.11, which are not affected and you should upgrade to these version anyway since 3.9 is now out of general support.

**Comment by air133** [comment]
very strange decision. You have 2 recent releases with this bug and don't want to fix them. then it might be worth removing them from the download and leaving 3.9.27 as the latest working version?
