### ISSUE TITLE
Large memory usage by RabbitMQ Management DB causing queues on other nodes to block

### ISSUE THREAD

**Issue by davidhiston** [rabbitmq/rabbitmq-server#761]
I have encountered an issue where a two node PCF RabbitMQ (3.6.1.904, Erlang 18.1) cluster in AWS under load is having its queues blocked due to high memory usage on the node hosting the stats.  The screenshot bellow illustrates this. 

![screen shot 2016-04-19 at 4 34 17 pm](https://cloud.githubusercontent.com/assets/8375252/14670805/8cadd0e8-06e6-11e6-9e84-8f651f0ff73e.png)

**Configuration **

There are 2 servers which have all queues mirrored and the following modification to the collection on stats applied: 

[ 
{rabbit, [ {collect_statistics, none},
              {collect_statistics_interval, 60000}] }, 
{rabbitmq_management, [ {rates_mode, none}] }
].

I used PerfTest to place the cluster under load using the following: ./runjava.sh -Xms2G com.rabbitmq.examples.PerfTest -h amqp://user:password@192.168.0.10/vhost_name -r 1 -R 1000 -x 10 -y 500 

The intention of the above was to weight in favor of the consumers to promote throughout of messages.  

** Issue Description**

After about an hour of running under this load, the memory on the node hosting the stats db steadily increases to the point where it hits the 6Gb high memory watermark and starts to block the producers.  This is an issue because whilst the node with the stats db is using over 6Gb of memory, the other node still has plenty of headroom and was only consuming 3Gb of memory.

The producers remain blocked until the statsdb processes (my assumption) the stats, and then you see it free the memory and producing continues as expected.

**Comment by michaelklishin** [comment]
Moving to rabbitmq-management where it belongs.
