### ISSUE TITLE
Invalid RPM spec file %post section

### ISSUE THREAD

**Issue by jcasale** [rabbitmq/rabbitmq-server#763]
For some reason master contains an RPM spec %post section as follows:

    if [ -f %{_sysconfdir}/rabbitmq/rabbitmq.conf ] && [ ! -f %{_sysconfdir}/rabbitmq/rabbitmq-env.conf ]; then
        mv %{_sysconfdir}/rabbitmq/rabbitmq.conf %{_sysconfdir}/rabbitmq/rabbitmq-env.conf
    else 
        touch %{_sysconfdir}/rabbitmq/rabbitmq-env.conf
    fi

I suspect that is an error, I am not clear why the new style configuration gets renamed to an environment file which of course results in an invalid configuration.

**Comment by michaelklishin** [comment]
Note: this is a follow-up to #550.

The reason why `rabbitmq.conf` is moved to `rabbitmq-env.conf` today is a historical accident: at some point a long time ago (years), `rabbitmq.conf` was the name of what is `rabbitmq-env.conf` today. So the move command was added for a migration period. It now happens to collide with the changes in #550.

Therefore this issue probably should be considered a part of #550 and excluded from release notes.
