### ISSUE TITLE
Classic mirror queue sync uses excessive memory

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#7658]
## Repro steps

* Start a 3-node cluster. I used the `3.11.x` branch with Erlang 25.3
* Publish some messages. Here's the PerfTest command I used:
    ```
    make ARGS="--uris amqp://localhost:5672,amqp://localhost:5673,amqp://localhost:5674 --auto-delete false --flag persistent --flag mandatory --producers 3 --consumers 0 --pmessages 65536 --confirm 128 --queue-pattern vesc-1062-%d --queue-pattern-from 0 --queue-pattern-to 2 --size 8192" run
    ```
* Add a mirroring policy:
  * Pattern `.*`, applies to `queues`
  * `ha-mode: exactly 2`
  * `ha-sync-mode: manual`
* Go to the management "Overview" page, and make a note of the memory usage. In my environment it's about 200MiB per node.
* Go to the "Queues" page, click on an unsynchronized queue, and click to start sync.
* The memory use of the synced mirror will spike. On my system it spikes to 1GiB and stays there.
* Run `rabbitmq-diagnostics -n NODE observer` where NODE is the mirror with memory growth. Enter `b` and you should see a process with a large amount of binary memory use (512MiB in my case):
    <img width="985" alt="image" src="https://user-images.githubusercontent.com/514926/225793294-cfe56c02-289a-42ae-8802-87c25c3fedab.png">
* Exit observer and run the following commands:
    ```
    rabbitmq-diagnostics -n NODE remote_shell
    > recon:proc_count(binary_memory, 5).
    ```
    More than likely the offending process will be the first in the list:
    ```
    {P, _, _} = hd(recon:proc_count(binary_memory, 5)).
    S = recon:get_state(P).
    byte_size(term_to_binary(S)).
    557723020
    ```
    Yikes 😱

Note that it's the `vqstate` record that has all the messages in-memory (in `q4`):
```
{passthrough,rabbit_variable_queue,
                               {vqstate,{0,[],[]},
                                        {0,[],[]},
                                        {delta,undefined,0,0,undefined},
                                        {0,[],[]},
                                        {65536,
                                         [{msg_status,65535,
                                                      <<37,138,216,143,4,...>>,
                                                      {basic_message,{resource,<<...>>,...},[<<...>>],{...},...},
                                                      true,true,rabbit_msg_store,true,...},
                                          {msg_status,65534,
```

**Comment by mkuratczyk** [comment]
Can't reproduce on `main`. First spike (on all nodes) is the initial data load. Then 3 spikes when I sync the queues. The leader is always the smaller spike, the new mirror the larger spike. The second run is with CQv2 - basically the same results, with slightly shorter spikes (because v2 can accept messages faster):
<img width="1955" alt="Screenshot 2023-03-17 at 10 38 05" src="https://user-images.githubusercontent.com/9566114/225868125-c2a2e72b-4d78-4c91-a676-f75cbf19f55a.png">
(you can ignore that small spike at the end of the first run, that was a conversion from v1 to v2 just to see if anything will happen)

I will try on `v3.11.x` next

**Comment by mkuratczyk** [comment]
I did not see this coming! Not only I can reproduce on `v3.11.x`, but the initial data load is already using much more memory.
<img width="1962" alt="Screenshot 2023-03-17 at 11 06 11" src="https://user-images.githubusercontent.com/9566114/225874716-0649c2c8-47a1-481b-b9fb-0022c33091a9.png">

**Comment by mkuratczyk** [comment]
Ok, 3.11 behaves fine when the queues are lazy. So to trigger this we need:
1. 3.11, but not `main`
2. non-lazy queues (v1 or v2, in 3.11 v2 is still quite similar to v1)
3. mirroring

With `main`, even a non-lazy CQv1 doesn't exhibit the problem

**Comment by lhoguin** [comment]
q4 is the in-memory messages, messages got put there because the queue type is default and not lazy, and there were no messages in q3(index on disk)/delta(all on disk) in that mirror. That's just what default CQs did up to and including 3.11.

As demonstrated above the problem does not exist anymore in 3.12 because q4 was removed. Now the number of messages in-memory is limited to a maximum of 2048 depending on the consume rate (so if there's no consumers when you sync it'll just be written to disk).

**Comment by lukebakken** [comment]
Thanks everyone. I just confirmed that switching the queues to `lazy` does address this memory issue. I will ensure that this fixes the issue with the customer, then I will close #7658.

**Comment by lukebakken** [comment]
@mkuratczyk I do see the same spikes as you do when upgrading my all-lazy 3.11 cluster to 3.12. It eventually resolves but this could be problem if customers upgrade clusters with many long queues. Something to keep in mind.

**Comment by mkuratczyk** [comment]
I guess because with `exactly: 2`, new mirrors are created when old nodes go down. Many users use `all` so those mirrors would be there at all times. But yes, short queues are definitely preferable.

**Comment by lukebakken** [comment]
PS I've been testing this morning with `ha-mode: all` and see the spikes. At any rate, `lazy` is the fix.

**Comment by michaelklishin** [comment]
If using lazy queues is the fix and CQv2 will be on by default in 3.12, and eliminate the difference, is there anything else we can/should do?

**Comment by lukebakken** [comment]
> is there anything else we can/should do?

Not at this time. The customer will be testing my process this week. I'm leaving #7658 open just in case something doesn't work as I expect.

**Comment by lukebakken** [comment]
Closing because it has been confirmed that using lazy queues addresses this issue.
