### ISSUE TITLE
Possible broken Doc Guide link in `rabbitmqctl help set_permissions` output

### ISSUE THREAD

**Issue by justinclift** [rabbitmq/rabbitmq-server#7716]
### Describe the bug

When running `rabbitmqctl help set_permissions` (version 3.11.11), part of the output displayed is:

```
Relevant Doc Guides

 * https://rabbitmq.com/access-control.html

 * https://rabbitmq.com/virtual-hosts.html
```

However, that "virtual hosts" url is 404:

![image](https://user-images.githubusercontent.com/406299/226792326-fbe2b9d8-cec4-4b37-86c2-bd0d0181cfe9.png)

Seems like the correct url is instead:

https://rabbitmq.com/vhosts.html

Trying to track down the relevant source code to see if it's broken there (eg needing updating?), I'm only able to get as far as [set_permissions_command.ex](https://github.com/rabbitmq/rabbitmq-server/blob/077f3442a4d9bdc6f24cf1a76c5a2b65f80d87a5/deps/rabbitmq_cli/lib/rabbitmq/cli/ctl/commands/set_permissions_command.ex#L79), which doesn't actually show the link address. :frowning:

```
def usage_doc_guides() do
  [
    DocGuide.access_control(),
    DocGuide.virtual_hosts()
  ]
end
```

Would someone with a better understanding of the source code be ok to check if the link is still busted in current `main`?

Also, ideally there would be an automatic redirect on the server to bounce people to the right location.  No idea if that's feasible though. :smile:

**Comment by michaelklishin** [comment]
I have set up a redirect but the issue was in a type in `doc_guide.ex`.

**Comment by justinclift** [comment]
Awesome.  Good turnaround time too. :smile:
