### ISSUE TITLE
SuperStream doesn't elect the single active consumer

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-server#7743]
### Describe the bug

The super stream doesn't elect the single active consumer when the consumers are restarted.
The consumers stop consuming and the status is always in `waiting` status. see the image:
![Screenshot 2023-03-27 at 10 42 15](https://user-images.githubusercontent.com/386987/227899778-baf33045-7ea9-442b-8842-9dd535f2d195.png)

### Reproduction steps

1. Create super stream with ten partitions `rabbitmq-streams add_super_stream invoices --partitions 10`
2. pump it with a few thousand messages (70k is enough)
3. stop the producer
4. start ten instances of this java client:
```java
    public static void main(String[] args) throws IOException {

        System.out.println("Connecting...");
        Address entryPoint = new Address("127.0.0.1", 5552);


        Environment environment = Environment.builder()
//                .host(entryPoint.host())
//                .port(entryPoint.port())
//                .username("test")
//                .password("test")
                .addressResolver(address -> entryPoint)
                .maxConsumersByConnection(1).
                build();
        String AppName = "reference";
        String stream = "invoices";

        AtomicInteger consumed = new AtomicInteger();
        Date start = new Date();
        for (int i = 0; i < 500; i++) {


            Map<String, Integer> consumedMap = new HashMap<>();
            Consumer consumer = environment.consumerBuilder()
                    .superStream("invoices")
                    .name("reference")
                    .offset(OffsetSpecification.first())
                    .singleActiveConsumer()
                    .messageHandler((context, message) -> {

                        if (consumedMap.containsKey(stream)) {
                            consumedMap.put(stream, consumedMap.get(stream) + 1);
                        } else {
                            consumedMap.put(stream, 1);
                        }

                        if (consumedMap.get(stream) % 10 == 0) {
                            Date end = new Date();
                            System.out.println("Stream: " + context.stream() + " - Consumed " + consumedMap.get(stream) + " - Time " + (end.getTime() - start.getTime()));
                        }


                        try {
                            Thread.sleep(ThreadLocalRandom.current().nextInt(200, 1000));
                        } catch (InterruptedException e) {
                            throw new RuntimeException(e);
                        }

                    }).build();

            try {
                Thread.sleep(60000);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
            System.out.println("Restarting");

            consumer.close();
        }

    }
```
5. Wait a couple of restarts
6.  you will have the issue

### Expected behavior

One single active consumer has to be active 

### Additional context

I noticed that the `invoices-1` is usually the first portion to have problems.
The `invoices-0` partition usually works 
The other partitions, at some point, will have the same issue.

`RabbitMQ 3.11.11`
`Java RabbitMQ Stream / Java 0.10.0-SNAPSHOT`

**Comment by fabiorosa-sn** [comment]
We are currently facing the same problem with version 3.12.10 , Erlang 25.3.2.7.

It happened 2 in the ~ 3 months we are running with SuperStreams.

The only way for us to "fix it" is to scale down the consumer application to 0, and then scale up again.

![screenshot-1](https://github.com/rabbitmq/rabbitmq-server/assets/123068132/64bde081-ca33-4526-9d04-957677d29e08)
![screenshot-2](https://github.com/rabbitmq/rabbitmq-server/assets/123068132/40b5fa30-7bd4-40af-884a-bf3596684ca6)

**Comment by Gsantomaggio** [comment]
@fabiorosa-sn have you enabled `stream_sac_coordinator_unblock_group`? which stream client are you using?

**Comment by fabiorosa-sn** [comment]
yes, it's enabled

**Comment by fabiorosa-sn** [comment]
we are using the java stream client version 0.15.0

**Comment by fabiorosa-sn** [comment]
Here is the result of the command

`rabbitmqctl eval 'rabbit_stream_coordinator:sac_state(rabbit_stream_coordinator:state()).'`

as requested by @Gsantomaggio 

`{rabbit_stream_sac_coordinator,
    #{{<<"/">>,<<"vehiclestatus.stream-0">>,<<"rentalservice">>} =>
          {group,
              [{consumer,<12609.11040.7378>,0,
                   <<"3.76.69.226:5329 -> 192.168.101.6:5551">>,true},
               {consumer,<12215.10962.1759>,0,
                   <<"3.64.93.165:15773 -> 192.168.101.68:5551">>,false},
               {consumer,<12215.12362.1759>,0,
                   <<"3.64.93.165:20442 -> 192.168.101.68:5551">>,false},
               {consumer,<12215.11813.1424>,0,
                   <<"3.64.93.165:26595 -> 192.168.101.68:5551">>,false},
               {consumer,<12215.19834.1799>,0,
                   <<"52.28.43.210:15266 -> 192.168.101.68:5551">>,false}],
              0},
      {<<"/">>,<<"vehiclestatus.stream-1">>,<<"rentalservice">>} =>
          {group,
              [{consumer,<12215.6546.1759>,1,
                   <<"3.76.69.226:6648 -> 192.168.101.68:5551">>,false},
               {consumer,<12215.10962.1759>,2,
                   <<"3.64.93.165:15773 -> 192.168.101.68:5551">>,true},
               {consumer,<12609.20367.7378>,0,
                   <<"3.64.93.165:35415 -> 192.168.101.6:5551">>,false},
               {consumer,<12215.11813.1424>,3,
                   <<"3.64.93.165:26595 -> 192.168.101.68:5551">>,false},
               {consumer,<12215.19834.1799>,2,
                   <<"52.28.43.210:15266 -> 192.168.101.68:5551">>,false}],
              1},
      {<<"/">>,<<"vehiclestatus.stream-2">>,<<"rentalservice">>} =>
          {group,
              [{consumer,<12610.32120.2076>,0,
                   <<"3.76.69.226:21229 -> 192.168.101.178:5551">>,false},
               {consumer,<12610.6618.2077>,0,
                   <<"3.64.93.165:6458 -> 192.168.101.178:5551">>,false},
               {consumer,<12610.7067.2077>,0,
                   <<"3.64.93.165:31434 -> 192.168.101.178:5551">>,true},
               {consumer,<12610.7130.2077>,0,
                   <<"3.64.93.165:33051 -> 192.168.101.178:5551">>,false},
               {consumer,<12610.25806.2119>,0,
                   <<"52.28.43.210:50905 -> 192.168.101.178:5551">>,false}],
              2},
      {<<"/">>,<<"vehiclestatus.stream-3">>,<<"rentalservice">>} =>
          {group,
              [{consumer,<12215.6546.1759>,0,
                   <<"3.76.69.226:6648 -> 192.168.101.68:5551">>,false},
               {consumer,<12609.19602.7378>,0,
                   <<"3.64.93.165:65369 -> 192.168.101.6:5551">>,false},
               {consumer,<12215.12362.1759>,1,
                   <<"3.64.93.165:20442 -> 192.168.101.68:5551">>,false},
               {consumer,<12215.11813.1424>,1,
                   <<"3.64.93.165:26595 -> 192.168.101.68:5551">>,true},
               {consumer,<12609.21361.7397>,0,
                   <<"52.28.43.210:44595 -> 192.168.101.6:5551">>,false}],
              3},
      {<<"/">>,<<"vehiclestatus.stream-4">>,<<"rentalservice">>} =>
          {group,
              [{consumer,<12609.11040.7378>,1,
                   <<"3.76.69.226:5329 -> 192.168.101.6:5551">>,false},
               {consumer,<12215.10962.1759>,1,
                   <<"3.64.93.165:15773 -> 192.168.101.68:5551">>,false},
               {consumer,<12215.12362.1759>,2,
                   <<"3.64.93.165:20442 -> 192.168.101.68:5551">>,false},
               {consumer,<12215.11813.1424>,2,
                   <<"3.64.93.165:26595 -> 192.168.101.68:5551">>,false},
               {consumer,<12215.19834.1799>,1,
                   <<"52.28.43.210:15266 -> 192.168.101.68:5551">>,true}],
              4},
      {<<"/">>,<<"vehiclestatus.stream-5">>,<<"rentalservice">>} =>
          {group,
              [{consumer,<12610.32120.2076>,1,
                   <<"3.76.69.226:21229 -> 192.168.101.178:5551">>,true},
               {consumer,<12609.19602.7378>,3,
                   <<"3.64.93.165:65369 -> 192.168.101.6:5551">>,false},
               {consumer,<12609.20367.7378>,1,
                   <<"3.64.93.165:35415 -> 192.168.101.6:5551">>,false},
               {consumer,<12610.7130.2077>,1,
                   <<"3.64.93.165:33051 -> 192.168.101.178:5551">>,false},
               {consumer,<12609.21361.7397>,3,
                   <<"52.28.43.210:44595 -> 192.168.101.6:5551">>,false}],
              5},
      {<<"/">>,<<"vehiclestatus.stream-6">>,<<"rentalservice">>} =>
          {group,
              [{consumer,<12215.6546.1759>,4,
                   <<"3.76.69.226:6648 -> 192.168.101.68:5551">>,false},
               {consumer,<12609.19602.7378>,4,
                   <<"3.64.93.165:65369 -> 192.168.101.6:5551">>,true},
               {consumer,<12609.20367.7378>,2,
                   <<"3.64.93.165:35415 -> 192.168.101.6:5551">>,false},
               {consumer,<12609.20474.7362>,0,
                   <<"3.64.93.165:48048 -> 192.168.101.6:5551">>,false},
               {consumer,<12215.19834.1799>,3,
                   <<"52.28.43.210:15266 -> 192.168.101.68:5551">>,false}],
              6},
      {<<"/">>,<<"vehiclestatus.stream-7">>,<<"rentalservice">>} =>
          {group,
              [{consumer,<12215.6546.1759>,2,
                   <<"3.76.69.226:6648 -> 192.168.101.68:5551">>,false},
               {consumer,<12609.19602.7378>,1,
                   <<"3.64.93.165:65369 -> 192.168.101.6:5551">>,false},
               {consumer,<12215.12362.1759>,3,
                   <<"3.64.93.165:20442 -> 192.168.101.68:5551">>,true},
               {consumer,<12215.11813.1424>,4,
                   <<"3.64.93.165:26595 -> 192.168.101.68:5551">>,false},
               {consumer,<12609.21361.7397>,1,
                   <<"52.28.43.210:44595 -> 192.168.101.6:5551">>,false}],
              7},
      {<<"/">>,<<"vehiclestatus.stream-8">>,<<"rentalservice">>} =>
          {group,
              [{consumer,<12215.6546.1759>,3,
                   <<"3.76.69.226:6648 -> 192.168.101.68:5551">>,false},
               {consumer,<12609.19602.7378>,2,
                   <<"3.64.93.165:65369 -> 192.168.101.6:5551">>,false},
               {consumer,<12215.12362.1759>,4,
                   <<"3.64.93.165:20442 -> 192.168.101.68:5551">>,false},
               {consumer,<12215.11813.1424>,5,
                   <<"3.64.93.165:26595 -> 192.168.101.68:5551">>,true},
               {consumer,<12609.21361.7397>,2,
                   <<"52.28.43.210:44595 -> 192.168.101.6:5551">>,false}],
              8},
      {<<"/">>,<<"vehiclestatus.stream-9">>,<<"rentalservice">>} =>
          {group,
              [{consumer,<12609.11040.7378>,2,
                   <<"3.76.69.226:5329 -> 192.168.101.6:5551">>,false},
               {consumer,<12215.10962.1759>,3,
                   <<"3.64.93.165:15773 -> 192.168.101.68:5551">>,false},
               {consumer,<12609.20367.7378>,3,
                   <<"3.64.93.165:35415 -> 192.168.101.6:5551">>,false},
               {consumer,<12609.20474.7362>,1,
                   <<"3.64.93.165:48048 -> 192.168.101.6:5551">>,false},
               {consumer,<12215.19834.1799>,4,
                   <<"52.28.43.210:15266 -> 192.168.101.68:5551">>,true}],
              9}},
    #{<12215.11813.1424> =>
          #{{<<"/">>,<<"vehiclestatus.stream-0">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-1">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-3">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-4">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-7">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-8">>,<<"rentalservice">>} =>
                true},
      <12215.6546.1759> =>
          #{{<<"/">>,<<"vehiclestatus.stream-1">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-3">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-6">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-7">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-8">>,<<"rentalservice">>} =>
                true},
      <12215.10962.1759> =>
          #{{<<"/">>,<<"vehiclestatus.stream-0">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-1">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-4">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-9">>,<<"rentalservice">>} =>
                true},
      <12215.12362.1759> =>
          #{{<<"/">>,<<"vehiclestatus.stream-0">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-3">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-4">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-7">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-8">>,<<"rentalservice">>} =>
                true},
      <12215.19834.1799> =>
          #{{<<"/">>,<<"vehiclestatus.stream-0">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-1">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-4">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-6">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-9">>,<<"rentalservice">>} =>
                true},
      <12610.32120.2076> =>
          #{{<<"/">>,<<"vehiclestatus.stream-2">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-5">>,<<"rentalservice">>} =>
                true},
      <12610.6618.2077> =>
          #{{<<"/">>,<<"vehiclestatus.stream-2">>,<<"rentalservice">>} =>
                true},
      <12610.7067.2077> =>
          #{{<<"/">>,<<"vehiclestatus.stream-2">>,<<"rentalservice">>} =>
                true},
      <12610.7130.2077> =>
          #{{<<"/">>,<<"vehiclestatus.stream-2">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-5">>,<<"rentalservice">>} =>
                true},
      <12610.25806.2119> =>
          #{{<<"/">>,<<"vehiclestatus.stream-2">>,<<"rentalservice">>} =>
                true},
      <12609.20474.7362> =>
          #{{<<"/">>,<<"vehiclestatus.stream-6">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-9">>,<<"rentalservice">>} =>
                true},
      <12609.11040.7378> =>
          #{{<<"/">>,<<"vehiclestatus.stream-0">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-4">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-9">>,<<"rentalservice">>} =>
                true},
      <12609.19602.7378> =>
          #{{<<"/">>,<<"vehiclestatus.stream-3">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-5">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-6">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-7">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-8">>,<<"rentalservice">>} =>
                true},
      <12609.20367.7378> =>
          #{{<<"/">>,<<"vehiclestatus.stream-1">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-5">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-6">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-9">>,<<"rentalservice">>} =>
                true},
      <12609.21361.7397> =>
          #{{<<"/">>,<<"vehiclestatus.stream-3">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-5">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-7">>,<<"rentalservice">>} => true,
            {<<"/">>,<<"vehiclestatus.stream-8">>,<<"rentalservice">>} =>
                true}},
    undefined,undefined}`

**Comment by msvechla** [comment]
@Gsantomaggio This issue still exists, we are on `RabbitMQ 3.12.14` `Erlang 26.2.5.5`

We are able to reproduce the issue with 5 active consumers and restarting all of them a couple of times. 

![CleanShot 2025-01-09 at 11 55 46](https://github.com/user-attachments/assets/58529a06-dc8e-4b37-a843-c66acf0fad88)
![CleanShot 2025-01-09 at 12 13 10](https://github.com/user-attachments/assets/1ba6cc8b-b153-42a5-924e-5b9d7fb078fb)

Looking at the screenshots you can see that after some restarts one stream does not have any active consumers, with all consumers being in waiting state.

Can you give some more hints on how to diagnose this further? Thanks!

**Comment by mkuratczyk** [comment]
@msvechla the most helpful step towards solving this problem would be to provide the exact steps for reproducing the issue (even if one of the steps is non-deterministic, like "restart a few times"). Ideally you could use https://github.com/rabbitmq/rabbitmq-stream-perf-test so that we can easily follow the steps, but you can also use your own code, but provide it in a complete, executable format (a GH repo we can clone and build).

Please be precise: start with a fresh RabbitMQ, declare the super-stream (show us how you do it), then run stream-perf-test (or your app) - provide the exact command, etc.

If you can put together such a test case, please open a new issue with all the details.

**Comment by msvechla** [comment]
@mkuratczyk thanks. As we are currently not running this on our infrastructure, but on cloudamqp, we will also check with the support.

Thanks for providing the instructions, we will work on such a reproducible setup in case we can not find the root-cause there.

Just for my understanding: The scenario as shown in my screenshots above, as well as others in this issue here, where there are multiple connected consumers, but all of them are in waiting state, should never happen right?

Why is the RabbitMQ server not determining that there is no active consumer and attempting to elect a new one? Should we not see this in the RabbitMQ server logs somewhere?

**Comment by mkuratczyk** [comment]
> Just for my understanding: The scenario as shown in my screenshots above, as well as others in this issue here, where there are multiple connected consumers, but all of them are in waiting state, should never happen right?

Yes, it should pick one of the available consumers.

> Why is the RabbitMQ server not determining that there is no active consumer and attempting to elect a new one?

Well, that's what we need to understand and reproduction steps would help grately. :)

**Comment by jonnepmyra** [comment]
Hi, i can confirm that the issue still exists, running 3.13.7. This happened after a node restart (in a cluster of 3 rabbitmq nodes). 

Don't know if it matters, but our clusters are relative big, with around 1000 superstreams.... so i guess there's ALOT of SAC-switching happening when we restart a rmq-node

![Image](https://github.com/user-attachments/assets/f08e1c49-85fd-46c6-826a-e813cb8150da)

**Comment by dukhaSlayer** [comment]
Can confirm, issue is still reproducible on 3.13.7

**Comment by michaelklishin** [comment]
@dukhaSlayer `3.13.x` and `4.0.x` are [out of community support](https://www.rabbitmq.com/release-information).

There were several stream SAC changes in `4.1.0`, such as https://github.com/rabbitmq/rabbitmq-server/pull/13671 and https://github.com/rabbitmq/rabbitmq-server/pull/13657.

Time to upgrade.

**Comment by Gsantomaggio** [comment]
>There were several stream SAC changes considered or adopted for 4.1.0, such as https://github.com/rabbitmq/rabbitmq-server/pull/13657 (merged) and https://github.com/rabbitmq/rabbitmq-server/pull/13671 (rejected).

Please also follow this PR:  https://github.com/rabbitmq/rabbitmq-server/pull/13672

**Comment by michaelklishin** [comment]
Thank you, @Gsantomaggio. That's indeed relevant, just hasn't been finished or shipped yet :)
