### ISSUE TITLE
Limit for the number of virtual hosts

### ISSUE THREAD

**Issue by SimonUnge** [rabbitmq/rabbitmq-server#7777]
### Is your feature request related to a problem? Please describe.

Running rabbitMQ as a service, having limits like this is very useful, to avoid brokers running out of memory. The current back pressure mechanism for high memory usage (memory alarm) does not stop clients/users from creating new vhosts. 

To leviate this issue, limits comes handy. There are limits for connections, channels, queues etc, but not for number of create vhosts.

### Describe the solution you'd like

Similar to how rabbitmq can be configured to limit connections node, per vhost or per user, add the option to also
limit number of vhosts.

Add config setting `max_vhost`, set to either infiniity (default) or a positive integer. Upon vhost creation, check if max_vhost setting is present, and if not (or set to infinity), allow the creation of new vhosts, if max_vhost is set to an integer, check current amount of vhosts and either accept or reject the creation of a new vhost.

**Comment by michaelklishin** [comment]
I don't know if `vhost_max` would be any better than `max_vhost` but it would be consistent with `connection_max` and `channel_max` (two awful names introduced more than a decade ago).

**Comment by SimonUnge** [comment]
Ha, ok, yeah I am fine with switching the order!
