### ISSUE TITLE
RabbitMQ 3.6.2 RC1 - Administration UI login error

### ISSUE THREAD

**Issue by johnfoldager** [rabbitmq/rabbitmq-server#780]
Error on the Management login page:

`Got response code 500 with body {"error":"Internal Server Error","reason":"{exit,{noproc,{gen_server2,call,\n [ldap_pool,{next_free,<0.20884.21>},infinity]}},\n [{gen_server2,call,3,[{file,\"src/gen_server2.erl\"},{line,340}]},\n {worker_pool,submit,3,[{file,\"src/worker_pool.erl\"},{line,102}]},\n {rabbit_auth_backend_ldap,user_login_authentication,2,\n [{file,\"src/rabbit_auth_backend_ldap.erl\"},\n {line,64}]},\n {rabbit_access_control,try_authenticate,3,\n [{file,\"src/rabbit_access_control.erl\"},\n {line,91}]},\n {rabbit_access_control,'-check_user_login/2-fun-0-',4,\n [{file,\"src/rabbit_access_control.erl\"},\n {line,77}]},\n {lists,foldl,3,[{file,\"lists.erl\"},{line,1262}]},\n {rabbit_mgmt_util,is_authorized,6,\n [{file,\"src/rabbit_mgmt_util.erl\"},{line,134}]},\n {webmachine_resource,resource_call,3,\n [{file,\"src/webmachine_resource.erl\"},\n {line,186}]}]}\n"}`

What I did:
- Upgrade to 3.6.2 RC1.
- Open the administration interface on port 15672 and login as an administrator in a browser tab.
- Close the browser tab but keep the browser open overnight.
- Open the administration interface on port 15672 in a browser tab.
- Normally I would see the login form but automatically be logged in and then present with the Overview pane.
- Now I only see the login screen and the above error. After a couple of refreshes I'm suddenly logged in.

Screenshot
![administrationloginerror](https://cloud.githubusercontent.com/assets/11851013/14909970/9aa26b96-0de9-11e6-9a42-36fb759ca997.PNG)

**Comment by michaelklishin** [comment]
The error says there are no LDAP connection pool processes available. Log files might suggest why. In any case, this repository is for neither the management or LDAP auth backend plugins.

**Comment by michaelklishin** [comment]
`rabbitmq_auth_backend_ldap.pool_size` controls pool size (which is 10 by default). Process unavailability can be natural and transient, so try bumping that to 64, for example.
