### ISSUE TITLE
AMQP 1.0: notify clients when a message could not be routed to any queues

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/rabbitmq-server#7823]
### Is your feature request related to a problem? Please describe.

Right now when publishing a message using AMQP 1.0 and no queues got routed a disposition frame with the `accepted` outcome is returned (equivalent tp AMQP legacy publisher confirm). To avoid this a different outcome should be selected.

### Describe the solution you'd like

When a message cannot be routed to any queues the `released` outcome should be returned.

In addition we could consider returning an error when a link with a queue target (e.g. `/amq/queue/QueueName`) is attached and the queue does not exist.

This feature should always be active.

**Comment by acogoluegnes** [comment]
I'm investigating an "internal" extension to the mandatory flag mechanism to provide the delivery ID in the callback. Publisher confirms and the mandatory flag would be enabled both anyway, as the AMQP 1.0 settled mode assumes outbound messages are already settled (so no need for the disposition frame).
