### ISSUE TITLE
noarch suse

### ISSUE THREAD

**Issue by belt-ascendlearning** [rabbitmq/rabbitmq-server#784]
/etc/init.d/rabbitmq-server start hangs when using rabbitmq-server-3.6.1 running on erlang-18.3-1.el6 (centos-6.7)
http://www.rabbitmq.com/releases/erlang/erlang-18.3-1.el6.x86_64.rpm
http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.1/rabbitmq-server-3.6.1-1.noarch.rpm

Rabbitmq repo: https://dl.bintray.com/rabbitmq/rabbitmq-server-rpm
Erlang repo: http://packages.erlang-solutions.com/rpm/centos/$releasever/$basearch

**Comment by michaelklishin** [comment]
@belt-ascendlearning that's a bit too terse. Please post your findings to rabbitmq-users.

**Comment by belt-ascendlearning** [comment]
There are reasons I closed the issue. See https://github.com/saltstack/salt/issues/32875 and https://github.com/saltstack-formulas/rabbitmq-formula/issues/33
