### ISSUE TITLE
Add more information on node health check timeout

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#787]
In [this thread](https://groups.google.com/forum/#!topic/rabbitmq-users/-vrONeNLuE8) user was confused by timeout in node health check.
We should provide more information about what operation timed out and possible reasons.

**Comment by AnthonyMastrean** [comment]
I find myself in need of this feature ASAP. I have a node that's taking over 90 sec to report `node_health_check` and pretty much any other command 😢

**Comment by michaelklishin** [comment]
We won't be addressing this. Our team has long concluded that One True Health Check™ is a myth. We have long introduced [more granular checks](https://www.rabbitmq.com/monitoring.html#health-checks). You should use them instead.

**Comment by AnthonyMastrean** [comment]
@michaelklishin OK, but I'm having problems with `rabbitmqctl` generally on this node. I mean, look at this:

```
$ time -p rabbitmqctl help
...
real 148.92
user 0.47
sys 0.14
```

I didn't think that `node_health_check` would even be subject to timeout, since it's not a "list" command.

> Operation timeout in seconds. Only applicable to "list" commands. Default is
"infinity".

And it's successful, but timed out at the same time? That's confusing.

**Comment by michaelklishin** [comment]
@AnthonyMastrean our team does not use GitHub issues for questions. I am highly confident this is not a bug in the CLI tools. Hostname resolution is one very likely reason, in particular on macOS or if a VPN is involved. `strace` and similar tools will provide relevant information. Checking that `/etc/hosts` contains entires for the hostname and `localhost` is never a bad idea either.
