### ISSUE TITLE
Changing '/' vhost default queue type

### ISSUE THREAD

**Issue by nmass-betpawa** [rabbitmq/rabbitmq-server#7874]
It would be very convenient to have the ability to change the default queue type to quorum for the '/' vhost during cluster initialization. Starting from version 3.11, this can be done in the console using the command 
`rabbitmqctl add_vhost NEW_VHOST --default-queue-type quorum`. 
However, it is currently not possible to do this in dynamic environments using the operator.

**Comment by michaelklishin** [comment]
Addressed in #7914. The HTTP API counterpart change is coming up next.
