### ISSUE TITLE
rabbitmqctl report gives exit code 64

### ISSUE THREAD

**Issue by prc33** [rabbitmq/rabbitmq-server#788]
In version 3.6.1, `rabbitmqctl report` prints usage information after the report due to `Error: operation report used with invalid parameter: []` and finally terminates with exit code 64.

**Comment by michaelklishin** [comment]
I'm not sure what's wrong with that. We intentionally use distinct UNIX exit codes in recent versions, see https://github.com/rabbitmq/rabbitmq-server/issues/396. Please ask questions on rabbitmq-users.

**Comment by michaelklishin** [comment]
`rabbitmqctl report` certainly works for me here (when invoked without arguments) and we haven't seen this reported elsewhere.
