### ISSUE TITLE
SNI support

### ISSUE THREAD

**Issue by carlhoerberg** [rabbitmq/rabbitmq-server#789]
Erlang does now support SNI since 18.0, i.e. you can serve multiple TLS certificates over the the same IP/listener. Docs: http://erlang.org/doc/man/ssl.html

Looks like RabbitMQ need to whitelist the `sni_hosts` property though. 

```
{sni_hosts, [{"c2.example.com",
                   [{cacertfile,"/etc/rabbitmq/c2_ca.pem"},
                    {certfile,"/etc/rabbitmq/c2.pem"},
                    {keyfile, "/etc/rabbitmq/c2.key"}]}]},
{ssl_options, [{cacertfile,"/etc/rabbitmq/c1_ca.pem"},
                      {certfile,"/etc/rabbitmq/c1.pem"},
                      {keyfile, "/etc/rabbitmq/c1.key"}
              ]}
```

**Comment by essen** [comment]
It's a little more complex depending on user needs. Just whitelisting will allow using sni options, but still require a default cert defined when sni is not used. Is that good enough?

**Comment by essen** [comment]
Pushed a PR updating Ranch to 1.3.0 which has proper SNI support.

**Comment by michaelklishin** [comment]
@essen that's a good enough start. We will see what more specific requirements come up once the users have a chance to try the SNI option(s).

**Comment by michaelklishin** [comment]
Should be addressed with https://github.com/rabbitmq/rabbitmq-common/pull/150.
