### ISSUE TITLE
CQ index v1: missing delivery marker for messages published before 3.10.0

### ISSUE THREAD

**Issue by gomoripeti** [rabbitmq/rabbitmq-server#7904]
### Describe the bug

This issue is about the classic queue index v1 implementation that is present since 3.10.0 up to on main.

Since 3.10.0 when CQ queue index v2 was introduced, it is assumed that queue index v1 stores also delivery marker on disk when a message is published, as described here https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_variable_queue.erl#L2146-L2154

This assumption is also used when marking messages as delivered-and-acked https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_variable_queue.erl#L1932-L1934 which is used for example in drop_expired implementation (expired messages are marked for removal by adding and ack to them)

However if a queue was created on an earlier RabbitMQ version and a message was published to it, the queue index files will only contain a publish entry and not a delivery marker. After upgrade to any version from 3.10.0+ this will still be the case breaking the above assumption and causing various problems.

One issue that I was able to reproduce (detailed in Reproduction steps) is that when such an "old" message is consumed on the new version, only one marker will be written to the segment file on disk (which is intended as an ack marker because del marker is assumed to be there already) However after an unclean shutdown and restart that marker will be parsed as a del marker, as if the message has not yet been acknowledged, this way a "deleted" message will appear again in the queue.

Another more serious issue (that I havent reproduced yet but I think the reason behind the crashes we see in production) is that some procedure (for example the drop_expired) writes ack markers in the journal file for messages that only has publish entries in segment files. After a restart or upgrade RabbitMQ crashes as bellow and unable to start entirely. (This example is from a restart on 3.11.5)
```
Message store "<vhost>/msg_store_persistent" : recovery terms differ from present
rebuilding indices from scratch
** Generic server <0.393.0> terminating
** Last message in was {'$gen_cast',
                           {submit_async,
                               #Fun<rabbit_classic_queue_index_v2.11.97365384>,
                               <0.392.0>}}
** When Server state == undefined
** Reason for termination ==
** {function_clause,
       [{rabbit_queue_index,journal_minus_segment1,
            [{no_pub,no_del,ack},
             {{true,
                  <<MsgId>>,
                  <<>>},
              no_del,no_ack}],
            [{file,"rabbit_queue_index.erl"},{line,1395}]},
        {rabbit_queue_index,'-journal_minus_segment/3-fun-0-',4,
            [{file,"rabbit_queue_index.erl"},{line,1372}]},
        {array,sparse_foldl_3,7,[{file,"array.erl"},{line,1684}]},
        {array,sparse_foldl_2,9,[{file,"array.erl"},{line,1678}]},
        {rabbit_queue_index,'-recover_journal/1-fun-0-',1,
            [{file,"rabbit_queue_index.erl"},{line,1059}]},
        {lists,map,2,[{file,"lists.erl"},{line,1315}]},
        {rabbit_queue_index,segment_map,2,
            [{file,"rabbit_queue_index.erl"},{line,1183}]},
        {rabbit_queue_index,recover_journal,1,
            [{file,"rabbit_queue_index.erl"},{line,1050}]}]}
```

### Reproduction steps

1. Create server with for example 3.9.27
2. Create a classic queue and publish 2 messages
3. Upgrade server to 3.10.19
4. Get 1 message via Mgmt UI with Ack Mode: Automatic Ack, Messages: 1
5. Now the queue has 1 messages ready according to Mgmt UI
6. Shut down RabbitMQ and delete msg_stores/vhosts/<vhost>/recovery.dets (to simulate an unclean shutdown)
7. Start RabbitMQ
8. The queue shows 2 messages total again.

### Expected behavior

Although classic queue v1 are deprecated and being phased out, they are part of the upgrade path when making the first upgrade step from a pre-3.10.0 version, hence I would expect that all of the queues' features and edge cases still work as before (no crash because of unexpected/inconsistent index file content, no double delivery in an admittedly special sequence of events etc.)
However I'm not sure what the fix could be. To do a conversion after upgrade ensuring del markers are there for every publish entry. Or tolerating pub+no_del+ack combinations.

**Comment by michaelklishin** [comment]
Feel free to look into it, we won't get to it until May.

**Comment by gomoripeti** [comment]
thanks, I will definitely continue investigating as I don't fully understand yet the steps how this root cause leads to certain crashes, and the details of v1 queue index.
I might need to ask for some insights about the current workings, and also May is not that far away :)

**Comment by gomoripeti** [comment]
related discussion https://github.com/rabbitmq/rabbitmq-server/discussions/5197

**Comment by lhoguin** [comment]
Considering v1 is on the way out I suppose the best solution to this issue is to handle the case(s) where there was a pub, no del and an ack, and handle it like if a del was there.

**Comment by gomoripeti** [comment]
thanks for the guidance, I will work on a PR with that solution
