### ISSUE TITLE
Error while upgrading RabbitMq from 3.2.4 to 3.6.1 on ubuntu 14.04

### ISSUE THREAD

**Issue by palaiyacw** [rabbitmq/rabbitmq-server#791]
I was following instruction given in the [link](http://monkeyhacks.com/post/installing-rabbitmq-on-ubuntu-14-04). Updated my repository list and tried to upgrade the version but it gives the following error. Earlier, cluster of two node of rabbitmq 3.2.4 was running

**Error:**
` Reading package lists... Done
Building dependency tree       
Reading state information... Done
rabbitmq-server is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 467 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up rabbitmq-server (3.6.1-1) ...
 * Starting message broker rabbitmq-server                                                                                                      * FAILED - check /var/log/rabbitmq/startup_\{log, _err\}                                                                                                                             [fail]
invoke-rc.d: initscript rabbitmq-server, action "start" failed.
dpkg: error processing package rabbitmq-server (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 rabbitmq-server
E: Sub-process /usr/bin/dpkg returned an error code (1) `

In error log i am getting this :  

`Cluster upgrade needed but other nodes are running [add_ip_to_listener,
                                                    exchange_decorators,
                                                    exchange_event_serial,gm,
                                                    mirrored_supervisor,
                                                    policy_apply_to,
                                                    queue_decorators,
                                                    remove_user_scope,
                                                    semi_durable_route,
                                                    topic_trie,
                                                    topic_trie_node,
                                                    user_admin_to_tags]
and I want [add_ip_to_listener,cluster_name,exchange_event_serial,gm,
            internal_system_x,mirrored_supervisor,policy_apply_to,
            recoverable_slaves,remove_user_scope,semi_durable_route,
            topic_trie,topic_trie_node,user_admin_to_tags,
            user_password_hashing]`

**Comment by michaelklishin** [comment]
Cluster nodes must be upgraded in lock step. See the docs.

**Comment by michaelklishin** [comment]
…between feature releases, which is what you are trying to do.

**Comment by michaelklishin** [comment]
Lastly, the link to "the docs" links to a blog post by someone other than our team. Sorry, that doesn't count for official documentation.

**Comment by palaiyacw** [comment]
Could you please answer properly what do you mean by `must be upgraded in lock step` and link for the official documentation

**Comment by palaiyacw** [comment]
And even if i follow this [OFFICIAL DOC](https://www.rabbitmq.com/install-debian.html) I get the same error. FYI, Information given in both the links was same.

**Comment by palaiyacw** [comment]
:-1:

**Comment by michaelklishin** [comment]
See Upgrading Clusters on http://www.rabbitmq.com/clustering.html.
