### ISSUE TITLE
Change the default queue type on an existing vhost

### ISSUE THREAD

**Issue by stefanmoser** [rabbitmq/rabbitmq-server#7912]
### Is your feature request related to a problem? Please describe.

I want to change the default queue type on a vhost so that I can update it from `classic` to `quorum` after I have migrated my existing classic queues to quorum queues.

Using the ["migrate in place" method described in the quorum queue migration blog post](https://blog.rabbitmq.com/posts/2023/02/quorum-queues-migration/#in-place-migration), any new queues created after migration will still be created with the default queue type, which is likely to be `classic`. (Unless the client code is updated.)

Having this ability would make it possible to migrate from classic queues to quorum queues without any client code updates, assuming that client code did not specify the queue type and relied on the default queue type.

### Describe the solution you'd like

It should be possible to update the default queue type on a vhost.

It's currently possible to update the `description` and `tags` on a vhost via the Management API `PUT /api/vhosts/vhostname` but the `default_queue_type` field is ignored. This API should accept changes to `default_queue_type`.

There should also be a way to update the default queue type via the CLI tools. The only CLI tool I could find that updates the properties of a vhost is `rabbitmqctl set_vhost_tags` (although [it's undocumented](https://www.rabbitmq.com/rabbitmqctl.8.html)). Perhaps a CLI tool such as:
```
update_vhost vhost [--description desc --tags tags --default-queue-type default-q-type]
```

**Comment by michaelklishin** [comment]
An update command sounds OK and would also help #7874. I will take a look.

**Comment by ChunyiLyu** [comment]
People with similar ask from community slack: https://rabbitmq.slack.com/archives/CTMSV81HA/p1681127032288269

**Comment by stefanmoser** [comment]
Thanks so much for the quick response and implementation! I really appreciated it.
