### ISSUE TITLE
rabbitmq-server/rabbitmqctl and TLS distribution env vars

### ISSUE THREAD

**Issue by binarin** [rabbitmq/rabbitmq-server#799]
Currently there is 2 separate variables where you should pass options for TLS distribution:`RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` and `RABBITMQ_CTL_ERL_ARGS`

But in some modes of operation `rabbitmq-server` script will also invoke `rabbitmqctl` - this happens when `rabbitmq-server` runs in foreground mode and converts TERM signals into graceful shutdown commands. So to be sure that this graceful shutdown sequence works, you need to pass both :`RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` and `RABBITMQ_CTL_ERL_ARGS` to `rabbitmq-server` script.

I'm not sure what the proper solution should be. My ideas in order of preference go like this:
- introduce separate variable `RABBITMQ_ERL_DIST_OPTS` which will be used by all scripts
- generate a warning in `rabbitmq-server` when `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` contains something that looks like tls-options but `RABBITMQ_CTL_ERL_ARGS` doesn't
- just update the documentation on web-site

**Comment by michaelklishin** [comment]
Thank you for the idea. We decided to not implement this as there's little demand for this feature and we see a number of issues. For example, the server and CLI tools don't necessarily use their runtime arguments the same way and it is not a given that both should use the same set of flags.
