### ISSUE TITLE
Please include version number in package name on Windows

### ISSUE THREAD

**Issue by CaseyBurnsSv** [rabbitmq/rabbitmq-server#80]
When I install RabbitMq server on windows and open "Add Or Remove Programs" from control panel, RabbitMq appears as "RabbitMQ Server".

When automating deployments using Chef/Puppet it is hard to determine what version is currently installed.

Can this be changed to include the version number in the display name in "Add Or Remove Programs"? For example -- "RabbitMQ Server v3.5.0"

The is the convention that the Erlang and CouchDB follow.

**Comment by PritamUpadhyay** [comment]
Version is being displayed in "Add Or Remove Programs" from control panel," 
Have you checked this? 
![version](https://cloud.githubusercontent.com/assets/10142148/6818593/a8d0749e-d2d8-11e4-913e-297ddf13757d.png)

**Comment by CaseyBurnsSv** [comment]
That is correct, it is displayed in the Version column as expected. However, I am requesting that the version number is included in the name to simplify deployment automation.

**Comment by michaelklishin** [comment]
Why would we include version number in the name if there's already a version column? What's the point of having the version column then?

**Comment by michaelklishin** [comment]
OK, so the argument seems to be "deployment automation". Given how poor the automation story is on Windows, I'd not treat it as silly.
