### ISSUE TITLE
Tab switching with an invalid regex filter runs into an unhandled exception

### ISSUE THREAD

**Issue by philomory** [rabbitmq/rabbitmq-server#8008]
### Describe the bug

If you navigate away from the queues page of the management UI while the filter box contains an invalid regex (and the regex checkbox is checked), then it is no longer possible to navigate back to the queues page without first clearing (or hand-editing) your cookies.

### Reproduction steps

1. Start with an empty server.
2. Create a queue (for the sake of argument, named `foo`).
3. In the `queues` page of the management UI, tick the "regex" box next to the filter.
4. In the filter box, type an invalid regex such as `(foo` and hit return.
5. A popup message will display stating, "Pagination parameters are invalid".
6. Navigate away from the Queues page (for example, navigate to the "Exchanges" page)
7. Attempt to navigate back to the Queues page.
8. A popup will display stating, "Pagination parameters are invalid".
9. It is no longer possible to navigate to the Queues to change the filter, you need to edit or clear your cookies.

### Expected behavior

The page should still load with an invalid filter specified, at least enough for you to correct or remove said filter.

### Additional context

This has been tested on RabbitMQ server 3.8.4, 3.11.3, and 3.12.0-beta.8. It was tested in both Chrome and Firefox.

**Comment by michaelklishin** [comment]
I can reproduce, thanks for providing the steps.

Removing local storage is enough, the filter state is not stored in the cookie. 

Adding some validation before it gets stored, and clearing it when it is loaded, seems sufficient to me.

**Comment by michaelklishin** [comment]
I have a UI change that addresses this in the following way:

 * If the filter expression is not a valid regexp, we send it as a regular text filter
 * If the filter expression is not a valid regexp, we do not store the "regex" checkbox

Previously we would display an error returned by the API that says that the expression is not a valid regexp. Unfortunately we also store all this UI state
and when tabs are switched, use that information to perform a query, so if you leave an invalid regex and switch to a different tab, you would not be able to go back without clearing local storage.

I assume it's fine to not display an error and use a text search if the expression is not a valid regexp. Maybe I can find a reasonable way to display the message, management plugin's UI UI code is originally from 2011, and wasn't built by someone experienced with building UIs even by those standards.

**Comment by michaelklishin** [comment]
With a warning pop-up that says that the filter expression used is not a valid regexp, this looks decent, and it is possible to navigate to a different tab then come back.
