### ISSUE TITLE
Filter box does not support all regex features that the linked regex reference covers

### ISSUE THREAD

**Issue by philomory** [rabbitmq/rabbitmq-server#8009]
### Describe the bug

Next to the filter box on the queues page of the management UI, there is a link to a [regular expression reference](https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions) from Mozilla. However, the regex filtering used on the queues page does not support all the regex features that the reference documents. Most notably, the reference documents using negative lookbehind via `(?<!x)y` constructs, but if you attempt to use such a filter on the queues page, you get an error, "Pagination parameters are invalid".

Notably, the negative lookbehind syntax _is_ considered legitimate and understood by the pattern matching rules used on the server for e.g. policy patterns.

### Reproduction steps

1. Start a fresh RabbitMQ server
2. Create at least one queue (for the sake of argument, name it `foo`)
3. On the queues page of the management UI, enter `(?<!g)oo` in the filter box, and tick the "Regex" check box.
4. You will be presented with the error message, "Pagination parameters are invalid".

### Expected behavior

Preferably: Negative lookbehind should work in the filter box's regex mode.
Alternatively: The regular expression reference linked to should be one that accurately describes the capabilities of the regular expression handling library used by the management UI.

### Additional context

This has been tested on RabbitMQ 3.8.4, 3.11.3, and 3.12.0-beta.8. This has been tested in Chrome and Firefox.

**Comment by michaelklishin** [comment]
It uses the JS regular expression implementation. That's good enough for what it does. Sorry, our small team has significantly more important things to work on.
