### ISSUE TITLE
Mirrored queue crash after promotion while HA policy is being reapplied

### ISSUE THREAD

**Issue by dcorbacho** [rabbitmq/rabbitmq-server#803]
The slave is promoted while the HA policy is removed and applied again, this causes a crash on `start_mirroring` as the backing queue is `rabbit_mirror_queue_master`.

Found while reproducing #687 

```
=INFO REPORT==== 17-May-2016::14:14:23 ===
Mirrored queue 'pri_q2_1' in vhost '/': Slave <rabbit@t-srv-rabbit06.3.11087.1> saw deaths of mirrors <rabbit@t-srv-rabbit05.3.10650.1> <rabbit@t-srv-rabbit04.3.15361.0>

=INFO REPORT==== 17-May-2016::14:14:23 ===
Mirrored queue 'pri_q2_1' in vhost '/': Promoting slave <rabbit@t-srv-rabbit06.3.11087.1> to master

=ERROR REPORT==== 17-May-2016::14:14:23 ===
** Generic server <0.11087.1> terminating
** Last message in was {'$gen_cast',start_mirroring}
** When Server state == {q,
                         {amqqueue,
                          {resource,<<"/">>,queue,<<"pri_q2_1">>},
                          true,false,none,
                          [{<<"x-max-priority">>,long,64}],
                          <0.11087.1>,[],[],[],
                          [{vhost,<<"/">>},
                           {name,<<"ha-all">>},
                           {pattern,<<>>},
                           {'apply-to',<<"all">>},
                           {definition,
                            [{<<"ha-mode">>,<<"all">>},
                             {<<"ha-sync-mode">>,<<"automatic">>}]},
                           {priority,0}],
                          [],[],live},
                         none,false,rabbit_mirror_queue_master,
                         {state,
                          {resource,<<"/">>,queue,<<"pri_q2_1">>},
                          <0.11088.1>,<0.11095.1>,rabbit_priority_queue,
                          {state,rabbit_variable_queue,
                           [{64,
                             {vqstate,
                              {0,{[],[]}},
...
                          {dict,0,16,16,8,80,48,
                           {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                           {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                             []}}},
                          delegate},
                         undefined,undefined,undefined,undefined,5,running}
** Reason for termination == 
** {{badmatch,false},
    [{rabbit_amqqueue_process,handle_cast,2,
                              [{file,"src/rabbit_amqqueue_process.erl"},
                               {line,1196}]},
     {gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1049}]},
     {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,250}]}]}

=ERROR REPORT==== 17-May-2016::14:14:23 ===
Restarting crashed queue 'pri_q2_1' in vhost '/'.
```

**Comment by Gsantomaggio** [comment]
During the tests we also had a crash node
It caused  `crashed` queues as:

![screen shot 2016-05-23 at 15 07 54](https://cloud.githubusercontent.com/assets/386987/15472673/a8437dbe-20fc-11e6-9c0d-58b41938c325.png)

**Comment by dcorbacho** [comment]
The node receiving the set_policy command generates the start/stop_mirroring call based in the previous and new policy as stored by `rabbit_policy`. It generates then a `delegate:cast` message to the master/owner of the queue, in order to change the mirroring status. 

However, the policy in `rabbit_policy` might not match the current status of the system. For example, if the queues have a large amount of messages to synchronise it will take long time to process the policy change, and when a stop_mirroring command arrives the queues can still be synchronising. Policy change messages can then built up in the message queue and produce a continuous start/stop of the mirroring, long after the user has issued the set policy commands.

At the same time, the internal processes issuing the `delegate:call` command change every time, thus there is no guarantee the messages are received in order by the master/owner of the queue. This causes the reported crash, where two start or stop commands can be received consecutively.

**Comment by dumbbell** [comment]
In CI (both Concourse and Jenkins), the `random_policy` testcase in `dynamic_ha_SUITE` fails quite frequently with the following set of policies:
```
[
  {nodes, [NodeA, NodeB]},
  {nodes, [NodeA]}
]
```

I filed #889 and am going to investigate the issue.

**Comment by amulyas** [comment]
we are hitting the same issue .. we have around 200 vHost.. 3 vHost have around 3K Qs each but other are around 3 to 10 Qs ... and all of a sudden we started experiencing this issue.. there is no way to fix it for now .. only way is to turn off HA .. if we turn on HA we can not bring the cluster back .. slave even kill the master .. if we turn off HA on Qs we can bring the cluster back up and running .. but as soon as we turn on HA On Qs cluster go down again ..

**Comment by michaelklishin** [comment]
This was backported to `3.6.6`.
