### ISSUE TITLE
`rabbitmqadmin --version` output error

### ISSUE THREAD

**Issue by khteh** [rabbitmq/rabbitmq-server#8058]
### Describe the bug

```
# rabbitmqadmin --version
rabbitmqadmin %%VSN%%
```

### Reproduction steps

```
# rabbitmqadmin --version
rabbitmqadmin %%VSN%%
```

### Expected behavior

Show version number

**Comment by michaelklishin** [comment]
That is only the case if you download `rabbitmqadmin` from GitHub. If you download it from a running node (it ships with the management plugin) or copy it from the management plugin location, it does have that variable correctly expanded.

Maybe when the package build system is completely migrated to Bazel it would be something for us to look at but right now, there's bigger fish to catch.
