### ISSUE TITLE
Make it possible to relax queue type equivalence check for re-declarations when virtual host has default queue type configured

### ISSUE THREAD

**Issue by SimonUnge** [rabbitmq/rabbitmq-server#8076]
### Is your feature request related to a problem? Please describe.

Classic mirrored queues are deprecated, and will be removed in 4.0.
And, there are good documentation on how to migrate from CMQ to QQ,
both on the service side, and the client side.

In cases the client code is re-declaring a queue, for whatever reason, as a queue type
classic, and the queue has been migrated to a QQ, the declaration will fail, and the channel
process die.

I suggest we allow a separation of coordinating the migration (on the service side) and client code upgrades, with the below solution.

### Describe the solution you'd like

Add an configure option that will allow re-declaring a queue, even if there is an argument mismatch to the already present queue, if the below is true:
* There is a config option to turn on the feature
* The vhost for the queue has a default queue type of Quorum (or stream)
* The queue IS currently of type Quorum (or stream)
* The re-declare specifically specify queue type 'classic'

### Describe alternatives you've considered

N/A

### Additional context

Update `rabbit_amqqueue:assert_equivalence/5` to ignore the equivalence checks if the above criteria is in place.

**Comment by michaelklishin** [comment]
I'd say the option should be "ignore client-provided queue type", and that's it. It can be a virtual host metadata setting, for example.

**Comment by stefanmoser** [comment]
The proposed feature sounds like it is targeted at systems that currently declare classic queues for replicated queues and want to migrate to quorum queues without updating the client code. Clients should still be able to declare both quorum queues and streams, so I don't think the `x-queue-type` should be completely ignored. Maybe values of `classic` could be automatically replaced with `quorum`.

Although, do the maintainers still see value in using classic queues for non-replicated queues in 4.0? Or is the guidance to use quorum queues for non-replicated queues as well?

**Comment by SimonUnge** [comment]
if "ignore client-provided queue type" is only used for a re-declare, it might be enough though

**Comment by stefanmoser** [comment]
Ah, yes, if it ignores the `x-queue-type` only for re-declared queues, then it makes sense to me.

**Comment by michaelklishin** [comment]
@stefanmoser classic queues are kept around for the non-replicated scenarios. Using quorum queues with a single replica does not make much sense to me.

**Comment by michaelklishin** [comment]
The setting name I was considering was `queue.property_equivalence.ignore_type_on_redeclaration`
but if we agree to only limit this to QQs, it could also be `quorum_queue.property_equivalence.ignore_type_on_redeclaration`.

WDYT @SimonUnge @stefanmoser?

**Comment by stefanmoser** [comment]
Ya, it only really seems to make sense for QQs trying to be redeclared as classic. I don't think we'd want to ignore the type of the queue was a stream and was being redeclared as QQ. I would go with the 2nd one.

**Comment by SimonUnge** [comment]
Right, but for me it would make sense that it also covers re-declare of type classic for a queue that is of type 'stream' too?

**Comment by SimonUnge** [comment]
@michaelklishin That means I'll go for a config setting then?

**Comment by SimonUnge** [comment]
@michaelklishin @stefanmoser Right, had a quick chat with Stefan. Simpler for it to cover all cases, but maybe a bit dangerous, and maybe more precise here, as the use case would be a migration from classic to qq.

**Comment by michaelklishin** [comment]
@SimonUnge given that it will entirely depend on an opt-in setting, I doubt we'd surprise anyone.

**Comment by SimonUnge** [comment]
@michaelklishin true. I'll start with ignoring parameters in the current case:
a redeclare of a quorum queue, when the re-declare `x-queue-type` is classic.

Question: As the redeclare is of a new type, should there be any validation of other possible values in the 'argument list'? I currently assume we ignore them all, as classic and quorum arguments differ ?

**Comment by michaelklishin** [comment]
@SimonUnge if other arguments are incompatible with the queue type, I'd expect the redeclaration to fail at some point after.

It's a good question, as a migration tool it should be fine to ignore all arguments.
Maybe that's what we should do for simplicity, and rename the setting to `quorum_queue.property_equivalence.skip_checks_on_redeclaration`.

**Comment by SimonUnge** [comment]
OK, will simplify it alot! I'll do that.

**Comment by michaelklishin** [comment]
@mergifyio backport v3.12.x v3.11.x

**Comment by michaelklishin** [comment]
Manually backported `v3.12.x`, `v3.11.x`.
