### ISSUE TITLE
Disable rabbitmqctl rename_cluster_node if any Ra machines are used in the system.

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/rabbitmq-server#8135]
### Is your feature request related to a problem? Please describe.

Ra machines cease to function if the rabbit node they are running in is renamed (as may be done as part of an offline backup restore). hence we should not allow the `rabbitmqctl rename_cluster_node` command to run if any are used in the RabbitMQ cluster.

### Describe the solution you'd like

Deprecate `rename_cluster_node` and print warning and/or force users to supply a `--force` flag for the command to run.

**Comment by michaelklishin** [comment]
@kjnilsson what Ra API function should be used to determine if there are any running machines?

Adding an execution environment validation check is easy but what exactly should it use
to detect that a Raft-based feature is used?

**Comment by SimonUnge** [comment]
Perhaps enough with running `lists:all(fun(#{servers := S}) -> erlang:map_size(S) =:= 0 end, [ra:overview(X) || X <- rabbit_ra_systems:all_ra_systems()])` ?

i.e, check all current 'ra systems', and make sure all servers are empty?

**Comment by kjnilsson** [comment]
This command is deprecated and a noop since 4.0
