### ISSUE TITLE
Memory Leak/Memory Leftovers

### ISSUE THREAD

**Issue by DenZen1988** [rabbitmq/rabbitmq-server#8190]
### Describe the bug

If the vhost(s) of clients do not have set the correct exchange:
```
no exchange 'ProxyExchange' in vhost 'cache'
```
and there are active connection tries (e.g. faulty configuration) it looks like there are some memory leftovers produced.
Those seem to be not seen by the rabbitmq itself anymore.

Loglines (every 5 seconds form a service connecting to the rabbitmq):
```
Mar 8 00:00:22 <hostname> <servicename>[4317]: E: Failed to bind to exchange ProxyExchange: (404, "NOT_FOUND - no exchange 'ProxyExchange' in vhost 'cache'")
Mar 8 00:00:27 <hostname> <servicename>[4317]: I: Creating outbound channel
Mar 8 00:00:27 <hostname> <servicename>[4317]: I: Creating inbound channel
Mar 8 00:00:27 <hostname> <servicename>[4317]: I: Binding to exchange ProxyExchange, routing_key DesiredState.Proxy.XX, queue amq.gen-GXaTGMIodoDjG35W96Q23A for broadcasts
Mar 8 00:00:27 <hostname> <servicename>[4317]: W: Received remote Channel.Close (404): "NOT_FOUND - no exchange 'ProxyExchange' in vhost 'cache'" on <Channel number=2 OPEN conn=<SelectConnection OPEN socket=('XXX.XXX.XXX.XXX', 13472)->('XXX.XXX.XXX.XXX', 5671) params=<ConnectionParameters host=<hostname> port=5671 virtual_host=cache ssl=True>>>
Mar 8 00:00:27 <hostname> <servicename>[4317]: E: Failed to bind to exchange ProxyExchange: (404, "NOT_FOUND - no exchange 'ProxyExchange' in vhost 'cache'")
```
Loglines from the rabbitmq host:
```
2023-03-06 12:41:37.366823+00:00 [info] <0.11152.180> connection <0.11152.180> (XXX.XXX.XXX.XXX:45482 -> XXX.XXX.XXX.XXX:5671): user '<username>' authenticated and granted access to vhost 'cache'
2023-03-06 12:41:37.387989+00:00 [error] <0.11222.180> Channel error on connection <0.11152.180> (XXX.XXX.XXX.XXX:45482 -> XXX.XXX.XXX.XXX:5671, vhost: 'cache', user: '<username>'), channel 2:
2023-03-06 12:41:37.387989+00:00 [error] <0.11222.180> operation queue.bind caused a channel exception not_found: no exchange 'ProxyExchange' in vhost 'cache'
```
The error appeared roughly around every 6 hours by 8 hosts connecting to 1 rabbitmq instance/server.
After roughly 6 hours the memory exhausted (machine OOM killer) and rabbitmq did not report that it used that much memory.

### Reproduction steps

1. Run 1 instance of rabbitmq
2. Configure 8 clients to connect to the rabbitmq to a non existing vhost
3. Wait for roughly 6 hours
4. The OOM killer should set in
5. As soon a the clients are removed or configured correctly the issue disappears

### Expected behavior

The expected behaviour should either be that rabbitmq reports these memory leftovers so an admin can take action or those should be included in a garbage collector and be cleaned up automatically.

**Comment by lukebakken** [comment]
What version of RabbitMQ and Erlang are you using?

**Comment by denis-walther** [comment]
When the issue appeared the versions have been:
- Erlang: 1:25.2.1-1
- RabbitMQ: 3.11.7-1
