### ISSUE TITLE
rabbit:environment/{0,1} and status/0 should use explicit timeouts

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#820]
For clarity.

**Comment by hairyhum** [comment]
`application:which_applications` uses `5000` timeout by default, should we specify other timeout somehow?

**Comment by michaelklishin** [comment]
In OTP 18.x which I'm looking at it has

```
which_applications() ->
    gen_server:call(?AC, which_applications).    
which_applications(Timeout) ->
    gen_server:call(?AC, which_applications, Timeout).
```

so there is no timeout that I can see.

**Comment by hairyhum** [comment]
`gen_server:call` has default timeout `5000`.

**Comment by michaelklishin** [comment]
OK. I think a value around `30s` is more reasonable for this specific case. It would also be much more obvious what the timeout is.

**Comment by michaelklishin** [comment]
Actually, scratch that. It would still be beneficial to use an explicit timeout in our own code but in `rabbitmqctl environment` specifically it can be closer to `15s`. I was thinking about a different place in the code.

**Comment by hairyhum** [comment]
There is another use of `which_applications`
https://github.com/rabbitmq/rabbitmq-federation/blob/master/src/rabbit_federation_queue_link.erl#L62
