### ISSUE TITLE
Reduce rabbit.queue_index_max_journal_entries

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#821]
The current value of 32K is not particularly safe when server process is `SIGKILL`'ed. See [this mailing list discussion](https://groups.google.com/forum/#!searchin/rabbitmq-users/queue_index_max_journal_entries|sort:date/rabbitmq-users/f0akEFlQATU/txxCQkCTAwAJ), for example. 1K may be a bit too low for a default but a value in the 4-16K range may be an improvement.

**Comment by lhoguin** [comment]
We have tried to SIGKILL the node many times in various conditions, including not using confirms, and the node has always been able to start properly. Messages are guaranteed to be on disk if confirms are used and received back. I do not think we need to lower this value especially considering v1 will be removed eventually. Thoughts? Closing this?

**Comment by michaelklishin** [comment]
It is more than 6 years old, and message stores have evolved quite a bit since then, so yes.
