### ISSUE TITLE
Per-queue consumer timeout is 1 minute longer than configured

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/rabbitmq-server#8221]
### Describe the bug

When using the per-queue consumer timeout (added in #7981, shipped in `3.11.15`), the moment when the timeout is triggered is a 1 minute later than expected: eg, with `x-consumer-timeout=300000` I get it after 6 minutes, instead of 5. I haven't tested per-consumer nor the global timeout if they expose the same behaviour.

This shouldn't be a real issue - the timeout is not meant to be accurate, just to make sure that at some point we will give up waiting on an acknowledgment. However, it's confusing when testing the feature for example.

### Reproduction steps

```
# publish a single message 
perf-test -ad false -f persistent -qa x-queue-version=2,x-consumer-timeout=300000 -u q5m -y 0 -C 1

# start a consumer with very high latency
date; perf-test -ad false -f persistent -qa x-queue-version=2,x-consumer-timeout=300000 -u q5m -x 0 -D 1 -L 1000000000; date

# start another consumer that should get the message after the high-latency consumers times out
date; perf-test -ad false -f persistent -qa x-queue-version=2,x-consumer-timeout=300000 -u q5m -x 0 -D 1; date
```

The timeout is triggered 6 minutes after starting the first consumer (which has a high ack latency).

### Expected behavior

It doesn't have to be super precise but seems like we are adding exactly 1 minute for no obvious reason.

**Comment by kjnilsson** [comment]
This just needs to be documented, no real need to complicate this feature further just to get the granularity down.

**Comment by michaelklishin** [comment]
It is [documented now](https://rabbitmq.com/consumers.html#acknowledgement-timeout). Since this is a protection mechanism, not a consumer latency management feature or something like that, supporting values that are greater than 1m seems perfectly fine to me.
