### ISSUE TITLE
crash dump with no errors

### ISSUE THREAD

**Issue by sradu** [rabbitmq/rabbitmq-server#823]
rabbitmq 3.6.2 is randomly crashing with no error logs. I've attached the crash dump. 

[erl_crash.dump.gz](https://github.com/rabbitmq/rabbitmq-server/files/299247/erl_crash.dump.gz)

**Comment by michaelklishin** [comment]
Unfortunately having a crash dump alone is next to no specific information. It is not necessary that RabbitMQ itself produced it, tools such as rabbitmqctl could do it.

Crash dump are generated upon an unwanted exception in one of the standard modules or runtime so try a different Erlang version and make sure it is 64 bit.

Lastly please post questions to rabbitmq-users in the future.
