### ISSUE TITLE
Plugins seem to report listeners incorrectly

### ISSUE THREAD

**Issue by blowfishpro** [rabbitmq/rabbitmq-server#8242]
### Describe the bug

I've observed this with both the `rabbitmq_management` and `rabbitmq_prometheus` plugins - when I configure them to listen on either `127.0.0.1` or `::1`, running `rabbitmq-diagnostics -s listeners` reports listing to those ports on `[::]` (i.e. all ipv6 interfaces).  Inspecting via `lsof` confirms that they are in fact listening on the configured interfaces.

### Reproduction steps

1. Enable the `rabbitmq_management` or `rabbitmq_prometheus` plugins
2. Configure them to listen on `127.0.0.1` or `::1`, e.g. `management.tcp.ip = ::1`/`prometheus.tcp.ip = 127.0.0.1`
3. Restart RabbitMQ
4. Inspect RabbitMQ's listeners via `rabbitmq-diagnostics -s listeners`
5. Inspect those same listeners via lsof. e.g. `lsof -p :15672` or `lsof -p :15692`

### Expected behavior

`rabbitmq-diagnostics -s listeners` reports the actual interfaces those listeners are using as configured and as used, i.e. `127.0.0.1` or `[::1]`

### Additional context

RabbitMQ version: 3.11.15 installed via Homebrew
OS: Mac OS 13.3.1 (a)

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-server/discussions/6851

**Comment by michaelklishin** [comment]
@ikvmw I could reproduce this with

``` ini
# server-8242.conf
management.tcp.ip = ::1
prometheus.tcp.ip = 127.0.0.1
```

``` shell
bazel run broker RABBITMQ_ENABLED_PLUGINS=rabbitmq_management,rabbitmq_prometheus RABBITMQ_CONFIG_FILE=/tmp/server-8242.conf
```

``` shell
rabbitmq-diagnostics -s listeners
# Interface: [::], port: 15672, protocol: http, purpose: HTTP API
# Interface: [::], port: 15692, protocol: http/prometheus, purpose: Prometheus exporter API over HTTP
# Interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
# Interface: [::], port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0
```

```
# node shell
rabbit_networking:active_listeners().

[{listener,rabbit@sunnyside,http,"sunnyside",
           {0,0,0,0,0,0,0,0},
           15672,
           [{cowboy_opts,[{sendfile,false}]},{ip,"::1"},{port,15672}]},
 {listener,rabbit@sunnyside,'http/prometheus',"sunnyside",
           {0,0,0,0,0,0,0,0},
           15692,
           [{port,15692},
            {protocol,'http/prometheus'},
            {ip,"127.0.0.1"},
            {cowboy_opts,[{sendfile,false}]}]},
 {listener,rabbit@sunnyside,clustering,"sunnyside",
           {0,0,0,0,0,0,0,0},
           25672,[]},
 {listener,rabbit@sunnyside,amqp,"sunnyside",
           {0,0,0,0,0,0,0,0},
           5672,
           [{backlog,128},
            {nodelay,true},
            {linger,{true,0}},
            {exit_on_close,false}]}]
```

**Comment by ikvmw** [comment]
yeah, all things based on web are affected it seems, patch is coming. I'll close it as duplicate
