### ISSUE TITLE
Ubuntu rabbitmq-server NO_PUBKEY 6B73A36E6026DFCA

### ISSUE THREAD

**Issue by tiandavis** [rabbitmq/rabbitmq-server#832]
Hey Folks!

Not sure if this is the best channel, but we're seeing an issue on Ubuntu 12.04 LTS where `rabbitmq-server` fails to install because the package cannot be authenticated.

Our install instructions look like this:
```
# Add key for rabbitMQ repo
wget --quiet -O - http://www.rabbitmq.com/rabbitmq-signing-key-public.asc | apt-key add -
apt-add-repository 'deb http://www.rabbitmq.com/debian/ testing main'
# Install RabbitMQ
apt-get -y install rabbitmq-server
```

And the error message looks like this:
```
vagrant@precise64:/vagrant $ sudo apt-get -y install rabbitmq-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  rabbitmq-server
0 upgraded, 1 newly installed, 0 to remove and 185 not upgraded.
Need to get 0 B/5,247 kB of archives.
After this operation, 5,956 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  rabbitmq-server
E: There are problems and -y was used without --force-yes
vagrant@precise64:/vagrant $ 
```

A `sudo apt-key update`, followed by a `sudo apt-get update` gives a little more info:
```
Fetched 5,213 kB in 14s (362 kB/s)                                
Reading package lists... Done
W: GPG error: http://www.rabbitmq.com testing InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B73A36E6026DFCA
```

The not so happy path is to run w/ the `--force-yes` flag:
```
apt-get -y install rabbitmq-server --force-yes
```

This installs rabbitmq-server, but we'd rather avoid that if at all possible because of the security implications. Not really sure where to proceed next and any help forward would be invaluable. Thanks Folks!

**Comment by michaelklishin** [comment]
The key has changed several weeks ago. It was annouced:

 * [On rabbitmq.com](http://www.rabbitmq.com/news.html)
 * [On rabbitmq-users](https://groups.google.com/forum/#!searchin/rabbitmq-users/OpenPGP/rabbitmq-users/BO5cmEsdEhc/RihGN-r_AgAJ)

as well as on Twitter.

You're using the old key. See [Debian installation docs](http://www.rabbitmq.com/install-debian.html) for instructions.

**Comment by tiandavis** [comment]
Got it. Thanks!
