### ISSUE TITLE
Limit the number of consumers per queue using a policy

### ISSUE THREAD

**Issue by raphaelbergamini** [rabbitmq/rabbitmq-server#8373]
### Is your feature request related to a problem? Please describe.

To prevent to use too many resources at server side, a policy to limit the number of concurrent consummers will be a nice improve

### Describe the solution you'd like

A new policy definition to set the maximum number of concurrent consumers for a queue.

**Comment by michaelklishin** [comment]
Consumers do not have a meaningful resource footprint, connections and channels do.

You already can limit the number of active consumers to [just one](https://rabbitmq.com/consumers.html#single-active-consumer) and limit the number of channels per connection and connections per virtual host.

I would like to see some evidence that this feature is actually needed. Almost certainly what consumed resources in your case was an application leaking channels or connections, not registering a lot of consumers on a single channel.

**Comment by michaelklishin** [comment]
A basic test suggests that

 * 1K channels have a memory footprint of 38 MiB
 * 1K consumers on a single channel have a memory footprint of less than 3 MiB

and connections are even more expensive.

I am not convinced that this limit is needed. It's true that applications can leak consumers
just like they can leak channels, though.

**Comment by michaelklishin** [comment]
Relevant recent changes: #7777, #7856.

**Comment by michaelklishin** [comment]
I discussed this with a few contributors and the conclusion is:

 * It is not a trivial limit to introduce, and the gain will be very limited
 * Per-queue limits are generally not very useful since it's possible to have tens or hundreds of thousands of queues. It is not the same thing with `channel_max` per connection, for example, because channel footprint is higher and it is a much more commonly leaked resource

I think we will pass on this limit, at least for now.

**Comment by gomoripeti** [comment]
just wanted to add info that we did see consumer leak: a client calling `basic.consume` on the same channel every few seconds. It went up to few 100K consumers on a small server before OOM happened. Indeed the memory consumption of a consumer is small, so it takes time and a lot of consumers before it has visible effect.

Would implementing a per-channel limit be easier than per-queue limit? If connections per user, channels per connection AND consumers per channel are all limited, that would be sufficient for an operator to give number of consumers per user an upper bound.

**Comment by michaelklishin** [comment]
@gomoripeti there are no policies for channels, so it can only be a global setting then.
