### ISSUE TITLE
Disk-based message store index plugin

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#838]
Message store index is currently ETS-based. This has one obvious downside: it can only grow so long. Since the interface is quite small, we should provide an alternative version. The downsides of using e.g. LevelDB are also predictable:
- Lower throughput for messages that go into message store and not embedded into QI
- Shipping native code will require build system and distribution changes, opens a can of worms in terms of support

But for some users a HanoiDB or LevelDB/RocksDB-backed option could be worth using.

Related: #740.

**Comment by hairyhum** [comment]
Addressed by https://github.com/rabbitmq/rabbitmq-msg-store-index-eleveldb
