### ISSUE TITLE
log.dir not respected, LOG_BASE not documented

### ISSUE THREAD

**Issue by wrobell** [rabbitmq/rabbitmq-server#8381]
### Describe the bug

I am trying to start RabbitMQ 3.11.16 (generic Unix), which I have downloaded from GitHub. With a minimal configuration, it does not respect `log.dir` setting. After searching internet, I have found that setting `LOG_BASE` variable works.

I have based my configuration on

- https://www.rabbitmq.com/configure.html; no mention of `log.dir` or `LOG_BASE`
- https://www.rabbitmq.com/logging.html; `log.dir` documented, but not `LOG_BASE`

### Reproduction steps

Download and unpack RabbitMQ 3.11.16, generic Unix package.
Create "var/logs" directory.
Create "etc" directory
```
$ cat etc/rabbitmq-env.conf
MNESIA_BASE=/home/wrobell/projects/rb-conf-issue/var/mnesia
CONFIG_FILES=/home/wrobell/projects/rb-conf-issue/etc/conf.d

$ cat etc/conf.d/rabbitmq.conf
log.dir = /home/wrobell/projects/rb-conf-issue/var/logs
```
Start RabbitMQ
```
$ RABBITMQ_CONF_ENV_FILE=$(pwd)/etc/rabbitmq-env.conf ./rabbitmq_server-3.11.16/sbin/rabbitmq-server
2023-05-27 11:08:43.449181+01:00 [notice] <0.44.0> Application syslog exited with reason: stopped
2023-05-27 11:08:43.455310+01:00 [notice] <0.230.0> Logging: switching to configured handler(s); following messages may not be visible in this log output

  ##  ##      RabbitMQ 3.11.16
  ##  ##
  ##########  Copyright (c) 2007-2023 VMware, Inc. or its affiliates.
  ######  ##
  ##########  Licensed under the MPL 2.0. Website: https://rabbitmq.com

  Erlang:      25.3 [jit]
  TLS Library: OpenSSL - OpenSSL 3.0.8 7 Feb 2023
  Release series support status: supported

  Doc guides:  https://rabbitmq.com/documentation.html
  Support:     https://rabbitmq.com/contact.html
  Tutorials:   https://rabbitmq.com/getstarted.html
  Monitoring:  https://rabbitmq.com/monitoring.html

  Logs: /home/wrobell/projects/rb-conf-issue/rabbitmq_server-3.11.16/var/log/rabbitmq/rabbit@greymatter.log
        /home/wrobell/projects/rb-conf-issue/rabbitmq_server-3.11.16/var/log/rabbitmq/rabbit@greymatter_upgrade.log
        <stdout>

  Config file(s): /home/wrobell/projects/rb-conf-issue/etc/conf.d/rabbitmq.conf
```
The logs are created in ` /home/wrobell/projects/rb-conf-issue/rabbitmq_server-3.11.16/var/log/`. They should be created in ` /home/wrobell/projects/rb-conf-issue/var/log/`.

Please note that pointing RabbitMQ to the config file in `etc/conf.d` has the same effect as above, i.e.
```
$ RABBITMQ_CONFIG_FILE=$(pwd)/etc/conf.d/rabbitmq.conf RABBITMQ_CONF_ENV_FILE=$(pwd)/etc/rabbitmq-env.conf ./rabbitmq_server-3.11.16/sbin/rabbitmq-server`
```

After adding `LOG_BASE=/home/wrobell/projects/rb-conf-issue/var/logs` to `rabbitmq-env.conf` file, RabbitMQ starts to log into a proper directory
```
$ RABBITMQ_CONF_ENV_FILE=$(pwd)/etc/rabbitmq-env.conf ./rabbitmq_server-3.11.16/sbin/rabbitmq-server
2023-05-27 11:10:52.926556+01:00 [notice] <0.44.0> Application syslog exited with reason: stopped
2023-05-27 11:10:52.932478+01:00 [notice] <0.230.0> Logging: switching to configured handler(s); following messages may not be visible in this log output

  ##  ##      RabbitMQ 3.11.16
  ##  ##
  ##########  Copyright (c) 2007-2023 VMware, Inc. or its affiliates.
  ######  ##
  ##########  Licensed under the MPL 2.0. Website: https://rabbitmq.com

  Erlang:      25.3 [jit]
  TLS Library: OpenSSL - OpenSSL 3.0.8 7 Feb 2023
  Release series support status: supported

  Doc guides:  https://rabbitmq.com/documentation.html
  Support:     https://rabbitmq.com/contact.html
  Tutorials:   https://rabbitmq.com/getstarted.html
  Monitoring:  https://rabbitmq.com/monitoring.html

  Logs: /home/wrobell/projects/rb-conf-issue/var/logs/rabbit@greymatter.log
        /home/wrobell/projects/rb-conf-issue/var/logs/rabbit@greymatter_upgrade.log
        <stdout>

  Config file(s): /home/wrobell/projects/rb-conf-issue/etc/conf.d/rabbitmq.conf

  Starting broker... completed with 4 plugins.
```

### Expected behavior

I would expected `log.dir` to be respected by RabbitMQ, or `LOG_BASE` variable to be documented.

**Comment by michaelklishin** [comment]
Thank you for the details. We will not be re-introducing `log.dir`. It's a Lager-era setting that was [documented six years ago](https://github.com/rabbitmq/rabbitmq-website/commit/843f00a4546668544ee736a339ec85f86f66481f).

I will add `LOG_BASE` to the list of environment variables. It is much more common to overwrite the location of the main log file or use standard streams. In fact, I have not seen `LOG_BASE` specifically to be used in a long time. Or overwrite the base node data directory, and that's it.

**Comment by michaelklishin** [comment]
Apparently there is `rabbit.log_root`, an application setting that can be set via `advanced.config`. Its value is seeded from `LOG_BASE` if that env variable is set.

**Comment by michaelklishin** [comment]
Doc changes are pushed and will be published live in the next ≈ 5 minutes.

**Comment by michaelklishin** [comment]
``` erl
{mapping, "log.dir", "rabbit.log_root", [
    {datatype, string},
    {validators, ["dir_writable"]}]}.
```

According to `rabbit.schema`, `log.dir` is supported and translates to `rabbit.log_root`.

A quick test and a new integration test added to `rabbit:config_schema_SUITE` suggests that it is effective:

```
RABBITMQ_CONFIG_FILE=/path/to/RabbitMQ/configs/log.dir.conf rabbitmq-server
```

``` ini
# log.dir.conf
log.dir = /tmp
```

``` shell
rabbitmq-diagnostics environment | grep log_root
# =>       {log_root,"/tmp"},
```

**Comment by michaelklishin** [comment]
```
rabbitmq-diagnostics log_location -q
```

suggests that it is not effective, my guess is that the env variable takes precedence (and also has a default), because `RABBITMQ_LOG_BASE=/tmp rabbitmq-server` picks the value up.

So I guess `log.dir` was not supposed to carry over during the logger migration. I don't think
anyone on our team would remember the details.

**Comment by wrobell** [comment]
thx for clarification. LOG_BASE it is then.
