### ISSUE TITLE
Attempting to use rabbit_auth_backend_oauth2 for authentication only fails if token does not have a scope claim

### ISSUE THREAD

**Issue by blowfishpro** [rabbitmq/rabbitmq-server#8391]
### Describe the bug

When the OAuth 2.0 Authentication Backend is used for authentication only, authentication fails if the provided oauth token does not include a `scope` claim.  RabbitMQ's log shows an internal error `error:function_clause`

### Reproduction steps

1. Configure the OAuth 2.0 Authentication Backend to use an identity provider that does not include a `scope` claim in provided tokens (many do not)
2. Configure RabbitMQ to use `rabbit_auth_backend_oauth2` as an authentication backend with the internal database as the authorization backend, e.g.
    ```ini
    auth_backends.1.authn = rabbit_auth_backend_oauth2
    auth_backends.1.authz = internal
    ```
3. Create a user in the internal database whose name matches the `sub` claim of the token you intend to use (or some other claim if configuring `preferred_username_claims`) with whatever permissions you want to use.
4. Attempt to connect to RabbitMQ using this token as your password

### Expected behavior

When the OAuth 2.0 Authentication Backend is used for authentication only, it should not require the `scope` claim to be present

#### Workaround

Set `additional_scopes_key` to the name of some claim that is set to a string or list of strings - nothing will be ultimately used from this claim but it ends up modifying the token in a way that allows successful authentication.
```ini
auth_oauth2.additional_scopes_key = aud
```

#### Real world use case

In Kubernetes the API server acts as an identity provider for service account tokens (assuming [service account token projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#serviceaccount-token-volume-projection) is enabled).  This provides a way to identify pods by their service account with minimal additional configuration.

Here's an example snippet of `rabbitmq.conf` I used for testing this.  This was using Amazon EKS to create the cluster but should be adaptable to many environments with a different `jwks_url` or explicit signing keys.

```ini
auth_backends.1.authn = rabbit_auth_backend_oauth2
auth_backends.1.authz = internal
auth_backends.2 = internal
auth_oauth2.resource_server_id = https://kubernetes.default.svc
auth_oauth2.jwks_url = https://oidc.eks.us-east-2.amazonaws.com/id/44F6670AD56155F288DB3B11C95ADB44/keys
auth_oauth2.https.peer_verification = verify_peer
auth_oauth2.https.fail_if_no_peer_cert = true
auth_oauth2.https.cacertfile = /etc/ssl/certs/ca-certificates.crt
auth_oauth2.additional_scopes_key = aud # this is the hacky workaround mentioned above
```

The tokens provided have a payload looking something like:
```json
{
  "aud": [
    "https://kubernetes.default.svc"
  ],
  "exp": 1716680224,
  "iat": 1685144224,
  "iss": "https://oidc.eks.us-east-2.amazonaws.com/id/44F6670AD56155F288DB3B11C95ADB44",
  "kubernetes.io": {
    "namespace": "example-namespace",
    "pod": {
      "name": "example-pod",
      "uid": "790e3aac-0f25-4c57-ab80-7f09de2c1fa9"
    },
    "serviceaccount": {
      "name": "example-serviceaccount",
      "uid": "6bf127c9-0cd3-4900-bd08-806bb45b4fef"
    },
    "warnafter": 1685147831
  },
  "nbf": 1685144224,
  "sub": "system:serviceaccount:example-namespace:example-serviceaccount"
}
```

(note, it's possible to customize the `aud` claim and use a corresponding `resource_server_id` by [explicitly projecting a token into pods](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#launch-a-pod-using-service-account-token-projection) but the default service account tokens also work fine)

An example RabbitMQ user for this might look like (in the definitions file json format):
```json
{
  "users": [
    {
      "name": "system:serviceaccount:example-namespace:example-serviceaccount"
      "hashed_password": "",
      "tags": ["management"]
    }
  ]
}
```

And then one could test connectivity from a pod with:
```sh
curl -v -H "Authorization: Bearer $(cat /run/secrets/kubernetes.io/serviceaccount/token)" http://rabbitmq.default.svc.cluster.local:15672/api/whoami 
```

For the failure case, (where the workaround is not used), here's what the logs show (with the log level set to debug):
```
[debug] <0.676.0> User '' authentication failed with error:function_clause:
[debug] <0.676.0> [{rabbit_auth_backend_oauth2,validate_payload,
[debug] <0.676.0>                              [#{<<"aud">> => [<<"https://kubernetes.default.svc">>],
[debug] <0.676.0>                                 <<"exp">> => 1716680224,
[debug] <0.676.0>                                 <<"iat">> => 1685144224,
[debug] <0.676.0>                                 <<"iss">> =>
[debug] <0.676.0>                                     <<"https://oidc.eks.us-east-2.amazonaws.com/id/44F6670AD56155F288DB3B11C95ADB44">>,
[debug] <0.676.0>                                 <<"kubernetes.io">> =>
[debug] <0.676.0>                                     #{<<"namespace">> => <<"example-namespace">>,
[debug] <0.676.0>                                       <<"pod">> =>
[debug] <0.676.0>                                           #{<<"name">> =>
[debug] <0.676.0>                                                 <<"example-pod">>,
[debug] <0.676.0>                                             <<"uid">> =>
[debug] <0.676.0>                                                 <<"790e3aac-0f25-4c57-ab80-7f09de2c1fa9">>},
[debug] <0.676.0>                                       <<"serviceaccount">> =>
[debug] <0.676.0>                                           #{<<"name">> => <<"example-serviceaccount">>,
[debug] <0.676.0>                                             <<"uid">> =>
[debug] <0.676.0>                                                 <<"6bf127c9-0cd3-4900-bd08-806bb45b4fef">>},
[debug] <0.676.0>                                       <<"warnafter">> => 1685147831},
[debug] <0.676.0>                                 <<"nbf">> => 1685144224,
[debug] <0.676.0>                                 <<"sub">> =>
[debug] <0.676.0>                                     <<"system:serviceaccount:example-namespace:example-serviceaccount">>}],
[debug] <0.676.0>                              [{file,"rabbit_auth_backend_oauth2.erl"},
[debug] <0.676.0>                               {line,498}]},
[debug] <0.676.0>  {rabbit_auth_backend_oauth2,authenticate,2,
[debug] <0.676.0>                              [{file,"rabbit_auth_backend_oauth2.erl"},
[debug] <0.676.0>                               {line,127}]},
[debug] <0.676.0>  {rabbit_auth_backend_oauth2,user_login_authentication,2,
[debug] <0.676.0>                              [{file,"rabbit_auth_backend_oauth2.erl"},
[debug] <0.676.0>                               {line,65}]},
[debug] <0.676.0>  {rabbit_access_control,try_authenticate,3,
[debug] <0.676.0>                         [{file,"rabbit_access_control.erl"},{line,86}]},
[debug] <0.676.0>  {rabbit_access_control,try_authenticate_and_try_authorize,4,
[debug] <0.676.0>                         [{file,"rabbit_access_control.erl"},{line,77}]},
[debug] <0.676.0>  {lists,foldl,3,[{file,"lists.erl"},{line,1350}]},
[debug] <0.676.0>  {rabbit_access_control,check_user_login,2,
[debug] <0.676.0>                         [{file,"rabbit_access_control.erl"},{line,36}]},
[debug] <0.676.0>  {rabbit_mgmt_util,is_authorized,7,
[debug] <0.676.0>                    [{file,"rabbit_mgmt_util.erl"},{line,280}]}]
[warning] <0.676.0> HTTP access denied: User '' authentication failed with internal error. Enable debug logs to see the real error.
```

#### Additional Thoughts

I could see this being more of a feature request as the plugin documentation doesn't really mention it either way.  So feel free to reclassify it if you wish.  But given that it produces an internal error rather than gracefully failing, and that this seems very close to working, bug seemed more appropriate to me.

**Comment by michaelklishin** [comment]
@blowfishpro thank you for the details. We expect the `scope` field to always be there. I guess we can make it default to something if it is missing. What do you think it should be?

**Comment by MarcialRosales** [comment]
@michaelklishin we are going to remove scope validation from `user_login_authentication` that way if the plugin is only used for authentication, it should not matter if the scope is not present. However, for `user_login_authorization` or any `check_` functions, the plugin will validate the tokens. 

@blowfishpro it is strange that someone may want to authenticate a user via an OAuth2 token and not authorize it. But here you seemed to be the first user who found a use case for it. 
Thanks for reporting it

**Comment by blowfishpro** [comment]
> I guess we can make it default to something if it is missing. What do you think it should be?
In the workaround case the token passes validation even if the set of permissions it provides is empty.  Generally speaking I'd expect this same behavior if the `scope` claim is not present.

**Comment by blowfishpro** [comment]
Oh that's awesome.  Thank you so much!!!
