### ISSUE TITLE
rabbit_mirror_queue_misc:all_nodes/0 belongs to rabbit_nodes

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#84]
I find two things about `rabbit_mirror_queue_misc:all_nodes/0` to be slightly confusing:

 * The module it is in.
 * It returns a list of running nodes, which is not obvious from the name.

I suggest we move it to `rabbit_nodes:all_running/0`.

**Comment by dcorbacho** [comment]
@michaelklishin This is solved in https://github.com/rabbitmq/rabbitmq-server/tree/rabbitmq-server-84
The original function wasn't exported, so it doesn't break any previous API. Do you want the pull request on stable or master?

**Comment by michaelklishin** [comment]
stable. Most  small non-breaking changes can go into stable.

**Comment by michaelklishin** [comment]
Fixed in #360.
