### ISSUE TITLE
Specify a reasonable MAX_WAIT for OTP workers.

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#844]
Currently `MAX_WAIT` is defined as `16#ffffffff` all over the rabbitmq codebase and used as an OTP worker `shutdown` strategy.
Using such big shutdown timeout will cause `rabbit_sup` to wait for termination and `rabbit` application will hang in stopping state. Which in turn can make `application_controller` unresponsive, from our experience.

Reasonable timeouts should be used for workers and `WAIT_TIMEOUT` constant should be changed to much smaller value.

**Comment by michaelklishin** [comment]
We already have an issue for that: https://github.com/rabbitmq/rabbitmq-server/issues/541.
