### ISSUE TITLE
Build issue on alpine linux 3.4 / erlang 18.3.2

### ISSUE THREAD

**Issue by nathanejohnson** [rabbitmq/rabbitmq-server#848]
I have attempted to build rabbitmq-server versions 3.6.2, 3.6.3 milestone 1, and 3.7 milestone 4 and I get stuck at the same place.  This is on alpine linux 3.4, erlang 18.3.2, using GNU Make 4.1, python version 2.7.11.  Here is a link to some sample output during the build:

https://gist.github.com/nathanejohnson/009ea2f0fc5172ebcb25da2093babddd

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.

**Comment by michaelklishin** [comment]
`rabbitmq-components.mk` is out of date in one of the projects. Please post the exact steps you use to the list, e.g. how do you obtain the source and why you need to build from source in the first place.

**Comment by nathanejohnson** [comment]
I am building from source to contribute a package to the alpine linux aports repository.  The rabbitmq-components.mk is out of date in 100% of the source code tarballs I've downloaded from the Releases section of your github repository to date, which includes 3.6.2, 3.6.3 milestone 1, and 3.7.0 milestone 4.  Perhaps that could be an actionable item?  Also, I am not particularly interested in joining another mailing list, so I'll probably just let this fester and I'll halt my efforts.

**Comment by michaelklishin** [comment]
@nathanejohnson well that's too bad. The issue is that `rabbitmq-common` is cloned from github while what's in source tarballs is frozen in time. You can clone the repo and build from the `stable` branch, it will have `rabbitmq-components.mk` in sync with what's in git in `rabbit_common`. We already have an issue for getting rid of this file entirely if possible.

**Comment by michaelklishin** [comment]
In fact [our building instructions](http://www.rabbitmq.com/build-server.html) do just that, clone the repo.

**Comment by nathanejohnson** [comment]
Your tip about rabbitmq-common was enough to get me in the right direction, I noticed from the source rpm bundle you're using the .xz file versus the .tar.gz, which the former looks to include a rabbitmq-common inline that matches the rabbitmq-components.mk.  Using the .xz seems to have made the build happy.  Thanks for the help!  And sorry for using an inappropriate channel, but I am already subscribed to (and ignoring) too many mailing lists to keep up with at the moment, and so far IRC doesn't seem to be terribly active.
