### ISSUE TITLE
rabbitmqctl command to close all connections

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#849]
Similar to the idea in https://github.com/rabbitmq/rabbitmq-server/issues/817 but to force close all active connections, possibly in a particular vhost. This is sometimes useful for technical ops.

This will be a good feature to introduce after #500 is finished and merged. Note: this may be moved into the new CLI tools repository once they mature enough to be open sourced.

**Comment by johnfoldager** [comment]
Can you add an option to make a delay in milliseconds between each force-closing?
If I force-close all connections on a production system today then if their logic is to try to reconnect it will generate a connection storm which can lead to other problems. By specifying a delay I'm able to control this reconnection a bit.

**Comment by johnfoldager** [comment]
Maybe also add an option to specify how many connections (randomly) you want to force-close. This should take into account the time the connection was made to make sure only to force-close connections that was made before this command was issued (in case reconnects happens with the execution time).

**Comment by michaelklishin** [comment]
Adding a delay is a possibility. Closing a subset of connections is not: 99% of those asking for this feature want to close all connections in a vhost, not a random subset of them.

**Comment by michaelklishin** [comment]
This raises another possible request: a `--global` flag that would cover all vhosts. That's really dangerous, though, so I am not sold.

Also related: in master when a vhost is deleted, all connections in it are forcefully closed already.

**Comment by johnfoldager** [comment]
I see these two options as really nice and I can see their usage in several scenarios. I guess the latter will be implemented in a loop, so maybe just set a maximum count (instead of the random approach) which wouldn't be a big change in logic. I would really like this feature in order to be able to disconnect a number of clients and make them reconnect to the load balancer in front of RabbitMQ in order to re-distribute the load one several RabbitMQ nodes.

Regarding the vhost and deletiong of all connections: That makes sense!

**Comment by michaelklishin** [comment]
@johnfoldager I guess a numerical `--limit` is a reasonable request. We will consider it. Thank you for chiming in. It's always good to see specific ideas around new features.

**Comment by michaelklishin** [comment]
Moved to https://github.com/rabbitmq/rabbitmq-cli/issues/155, since that's where all CLI tool issues belong to now.

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-cli/issues/155 is closed.
