### ISSUE TITLE
Add more filtering options for `list_queues`

### ISSUE THREAD

**Issue by binarin** [rabbitmq/rabbitmq-server#851]
We believe it'd be useful to have the ability to list only queues whose master is on the current node, specifically for monitoring, where every host has some collection agent running. It doesn't make sense to collect duplicate statistics from global `list_queues` result.

**Comment by michaelklishin** [comment]
@binarin with #911 merged, should this be closed?

**Comment by binarin** [comment]
I don't know. Regexp filtering is not implemented yet and it can be useful for some use-cases. But we are no longer interested in this feature.

**Comment by michaelklishin** [comment]
OK, let's edit issue description and close it then.
