### ISSUE TITLE
HTTP API: provide equivalents of `rabbitmq-queues {add, remove, grow, shrink}`

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#8532]
Some specific endpoints we have discussed:

 * `POST /api/queues/quorum/{vhost}/{name}/replicas/add`
 * `DELETE /api/queues/quorum/{vhost}/{name}/replicas/remove`
 * `POST /api/queues/quorum/replicas/on/:node/grow`
 * `DELETE /api/queues/quorum/replicas/on/:node/shrink`

**Comment by SimonUnge** [comment]
Hey @michaelklishin If you want to, I can take a stab at this one in my down-time?

**Comment by michaelklishin** [comment]
I am working on it.

**Comment by SimonUnge** [comment]
Would it be possible to add some kind of restriction, say expand `management.restrictions.*` in order to restrict this API?

**Comment by michaelklishin** [comment]
I think so.

**Comment by SimonUnge** [comment]
Perfect! Could of course be a separate issue, but would be useful!
