### ISSUE TITLE
Purge of durable queue leads to unacknowleged messages

### ISSUE THREAD

**Issue by alaendle** [rabbitmq/rabbitmq-server#854]
if I purge messages in a durable queue I think I'm loosing acknowledgements (originally I spotted this in conjunction with the mqtt adapter, so this issue is based on https://github.com/rabbitmq/rabbitmq-mqtt/issues/84 which was closed in favour of further discussion on the google group - https://groups.google.com/forum/#!topic/rabbitmq-users/9a_suP53Dq4).

I've tested the following scenario - I just send a lot of messages (QoS 1) from multiple producers to a persistent/mirrored queue (without any consumers). If I now purge the contents of the queue via management UI some of the producers began to hang. If I record the network traffic via WireShark I can see that ACK's are missing - e.g. I send messages with identifiers 1 to 1000, but I receive only acknowledgements for 1 to 920 - so the client library is waiting for further acknowledgements, but rabbitmq won't send them - just leaving the tcp connection open.

Please take a look at the google group for C#/AMQP example code reproducing the issue (see the mqtt issue for Java/paho code).

I could reproduce this under Windows with RabbitMQ 3.6.2 and 3.7.0.607 and under Ubuntu with the trunk version of RabbitMQ - so I think this is a very general problem.

After doing a few more tests and trying to read some broker code (and I must admit that I'm a totally erlang noob) I think the problem might be related to the way RabbitMQ decides if purge_and_index_reset or purge_when_pending_acks is needed.
If I also consider unconfirmed messages during this decision I could no longer reproduce the problem with missing acks (see also the attached patch).

[rabbit_variable_queue.patch.txt](https://github.com/rabbitmq/rabbitmq-server/files/327549/rabbit_variable_queue.patch.txt)

A lot of additional information can be found in the linked rabbitmq-mqtt issue and on the google group post. So for now I keep short, but for sure I will provide further information if needed/requested ;-)

Thanks in advance.

**Comment by michaelklishin** [comment]
I cannot access the patch file (could be a temporary S3 glitch) so here it is from rabbitmq-users, inline:

``` diff
 src/rabbit_variable_queue.erl | 14 ++++++++++++--
 1 file changed, 12 insertions(+), 2 deletions(-)

diff --git a/src/rabbit_variable_queue.erl b/src/rabbit_variable_queue.erl
index 5b86cbd..f97ea8b 100644
--- a/src/rabbit_variable_queue.erl
+++ b/src/rabbit_variable_queue.erl
@@ -556,14 +556,15 @@ delete_crashed(#amqqueue{name = QName}) ->
     ok = rabbit_queue_index:erase(QName).
 
 purge(State = #vqstate { len = Len }) ->
-    case is_pending_ack_empty(State) of
+    io:format("purge~n"),
+    case is_pending_ack_empty(State) and is_unconfirmed_empty(State) of
         true ->
             {Len, purge_and_index_reset(State)};
         false ->
             {Len, purge_when_pending_acks(State)}
     end.
 
-purge_acks(State) -> a(purge_pending_ack(false, State)).
+purge_acks(State) -> io:format("purge_acks~n"), a(purge_pending_ack(false, State)).
 
 publish(Msg, MsgProps, IsDelivered, ChPid, Flow, State) ->
     State1 =
@@ -1612,10 +1613,12 @@ collect_by_predicate(Pred, QAcc, State) ->
 %% and an ack to the queue index for every message that's being
 %% removed, while the later just resets the queue index state.
 purge_when_pending_acks(State) ->
+    io:format("purge_when_pending_acks~n"),
     State1 = purge1(process_delivers_and_acks_fun(deliver_and_ack), State),
     a(State1).
 
 purge_and_index_reset(State) ->
+    io:format("purge_and_index_reset~n"),
     State1 = purge1(process_delivers_and_acks_fun(none), State),
     a(reset_qi_state(State1)).
 
@@ -1646,8 +1649,15 @@ reset_qi_state(State = #vqstate{index_state = IndexState}) ->
                          rabbit_queue_index:reset_state(IndexState)}.
 
 is_pending_ack_empty(State) ->
+    io:format("is_pending_ack_empty~n"),
+    io:format("~B~n", [count_pending_acks(State)]),
     count_pending_acks(State) =:= 0.
 
+is_unconfirmed_empty(#vqstate { unconfirmed = UC }) ->
+    io:format("is_unconfirmed_empty~n"),
+    io:format("~w~n", [gb_sets:is_empty(UC)]),
+    gb_sets:is_empty(UC).
+
 count_pending_acks(#vqstate { ram_pending_ack   = RPA,
                               disk_pending_ack  = DPA,
                               qi_pending_ack    = QPA }) ->
```

**Comment by dcorbacho** [comment]
@alaendle thanks for the patch.

This bug can be easily reproduced with the Java client using a durable queue, the new tests are in https://github.com/rabbitmq/rabbitmq-java-client/pull/154
