### ISSUE TITLE
Oauth2 http client's cacertfile should not be configured if there is none configured

### ISSUE THREAD

**Issue by MarcialRosales** [rabbitmq/rabbitmq-server#8547]
### Describe the bug

Since OTP 26, ssl option `cacertfile` must have a value, not `undefined`. 

RabbitMQ Oauth2 plugin uses a http client to download signing keys from the configured `jwks_url`. If we do not configure the `cacertfile` option, when running with OTP 26, the http client failed to make the http request because the `cacertfile` has the value `undefined`. 

### Reproduction steps

1. Configure oauth2 backend plugin with jwks_url 
2. Launch RabbitMQ with OTP 26
3. Go to home page
4. Click on "Click here to login"

We get back an error saying "Unauthorized".

### Expected behavior

Only initialize cacertfile when the configuration has a value for it.

### Additional context

https://groups.google.com/g/rabbitmq-users/c/L49wfQwvKeI/m/o9PFJPe6AgAJ

**Comment by patrickmichalina** [comment]
@MarcialRosales this is still happening. Have to downgrade to from 13.13.0 to rabbitmq:3.12.13-management-alpine in order to not be confronted with this bug.

**Comment by lukebakken** [comment]
Re-opening due to @patrickmichalina's comment (cc @MarcialRosales)

**Comment by michaelklishin** [comment]
It's kind of weird that we have a resolved issue that's in 3.12.1 release notes, but is now reopened.

I think we need a new issue instead.

**Comment by michaelklishin** [comment]
https://github.com/rabbitmq/rabbitmq-server/issues/10612
