### ISSUE TITLE
amqp_client failures on OTP 26

### ISSUE THREAD

**Issue by jared-mackey** [rabbitmq/rabbitmq-server#8610]
### Describe the bug

Hi, I am using `amqp_client` and `amqp` hex packages (via Broadway) for my Elixir project and I was upgrading to Elixir 1.15 and OTP 26 and noticed that connections are failing to connect to my RabbitMQ servers.

Elixir Logs

```
module=BroadwayRabbitMQ.Producer [error] Cannot connect to RabbitMQ broker: {:auth_failure, ~c"Disconnected"}
```

RabbitMQ Server logs

```
[error] <0.818.0> {handshake_error,starting,26721,
[error] <0.818.0>                  {amqp_error,frame_error,
[error] <0.818.0>                              "type 99, all octets = <<>>: {frame_too_large,1852269919,4088}",
[error] <0.818.0>                              none}}
```

### Reproduction steps

1. Use an AMQP elixir/erlang client to connect to RabbitMQ on OTP 26.
2. Open connection to RabbitMQ server. (Mine is running in docker, `rabbitmq:3-management`) 
3. Connections fail with logs on Elixir side and on RabbitMQ server.

### Expected behavior

Connections should not close and app should function normally.

### Additional context

Versions

Old
```
elixir 1.15.0-otp-25
erlang 25.3
```

New that throws the errors:
```
elixir 1.15.0-otp-26
erlang 26.0.1
```

My RabbitMQ server is not using these changes and is just using w/e is in docker at the time I pulled. I can get that exact version if it's helpful but I think it might be client side since it hasn't been an issue before upgrading my client.

**Comment by mkuratczyk** [comment]
Use RabbitMQ 3.12:  https://www.rabbitmq.com/which-erlang.html

The latest 3.11 patch release should also work if can't use 3.12 yet.
