### ISSUE TITLE
Table column selection pane cannot be closed on screens with very limited vertical space

### ISSUE THREAD

**Issue by Antsthebul** [rabbitmq/rabbitmq-server#8660]
### Describe the bug

When attempting to add more attributes to the table which displays metrics on existing nodes. The "toolbar" that pops up on the right hand side, containing removeable attributes, is cut off and does not allow scrolling. 

![image](https://github.com/rabbitmq/rabbitmq-server/assets/56587872/943f993f-de55-4467-bd0c-2ff2b6216831)

### Reproduction steps

1. Start rabbitmq server
2. Head to home page
3. select attributes
...

### Expected behavior

To be able to scroll and select necessary attributes, and click the close button

### Additional context

Windows laptop with 15" screen

**Comment by michaelklishin** [comment]
Moving the button to the top would solve this without any need for scrolling.

**Comment by Antsthebul** [comment]
> Moving the button to the top would solve this without any need for scrolling.

Yeah and it cuts off other selectable attributes as well. I can create a PR for it. I basically created overflow:scroll to the div. and it seemed like it worked pretty well

**Comment by SimonUnge** [comment]
@Antsthebul It is now part of rabbitmq-server repo (see deps/rabbitmq_management/)
