### ISSUE TITLE
Consider stopping plugin OTP dependancy applications on disable

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-server#869]
As part of disabling plugins, also consider stopping all OTP dependancy applications, which were started as part of its enable, if, and only if, they aren't used by multiple plugins.

For example, the running applications on a bare minimal node;

```
[{rabbit,"RabbitMQ","3.6.2"},
 {os_mon,"CPO  CXC 138 46","2.3.1"},
 {rabbit_common,[],"3.6.2"},
 {mnesia,"MNESIA  CXC 138 12","4.12.5"},
 {xmerl,"XML parser","1.3.7"},
 {ranch,"Socket acceptor pool for TCP protocols.","1.2.1"},
 {sasl,"SASL  CXC 138 11","2.4.1"},
 {stdlib,"ERTS  CXC 138 10","2.4"},
 {kernel,"ERTS  CXC 138 10","3.2"}]
```

after enabling and disabling `rabbitmq-management`, 
`rabbitmqctl eval 'application:which_applications().'` yields the following;

```
[{ssl,"Erlang/OTP SSL application","6.0"},
 {public_key,"Public key infrastructure","0.23"},
 {crypto,"CRYPTO","3.5"},
 {inets,"INETS  CXC 138 49","5.10.6"},
 {compiler,"ERTS  CXC 138 10","5.0.4"},
 {syntax_tools,"Syntax tools","1.6.18"},
 {asn1,"The Erlang ASN1 compiler version 3.0.4","3.0.4"},
 {rabbit,"RabbitMQ","3.6.2"},
 {os_mon,"CPO  CXC 138 46","2.3.1"},
 {rabbit_common,[],"3.6.2"},
 {mnesia,"MNESIA  CXC 138 12","4.12.5"},
 {xmerl,"XML parser","1.3.7"},
 {ranch,"Socket acceptor pool for TCP protocols.","1.2.1"},
 {sasl,"SASL  CXC 138 11","2.4.1"},
 {stdlib,"ERTS  CXC 138 10","2.4"},
 {kernel,"ERTS  CXC 138 10","3.2"}]
 ```
 
which seems to have left some significant application overhead on the node. Same can be said of other plugins like `rabbitmq_federation`, `rabbitmq_auth_backend_ldap`, etc.

**Comment by michaelklishin** [comment]
@Ayanda-D how do we know if those applications are not used by other plugins or even other apps?

**Comment by Ayanda-D** [comment]
@michaelklishin good question, hence terming this as "Consider" (if feasible). Not sure if we can somehow keep record/relation of which apps are started as part of a plugin's `enable`, and attempt to stop them if used once on `disable`. 

And I agree, drilling down to "which other apps" can get tricky. But the unnecessary/undesired overhead left on the node doesn't seem right when a plugin is no longer required, even node resource wise.

**Comment by michaelklishin** [comment]
If we can find a way to retrieve application dependency graph from e.g. `application_controller` then it makes sense. Rabbit already has a graph of plugin dependencies.

**Comment by hairyhum** [comment]
We do get the list of plugins dependencies during enable/disable, so we know which applications are used by other plugins.
But there is no way to know if application has been started as a dependency or using `application:start`

**Comment by michaelklishin** [comment]
After giving it some thought I'm afraid this is not really feasible: unless we want to depend on `application_controller` ETS tables and such, keeping track of dependencies seems impossible to get right at the moment.

Thank you for the idea, @Ayanda-D!
