### ISSUE TITLE
APT repository slow / down

### ISSUE THREAD

**Issue by vespakoen** [rabbitmq/rabbitmq-server#87]
Failed to fetch:

http://www.rabbitmq.com/debian/pool/main/r/rabbitmq-server/rabbitmq-server_3.5.0-1_all.deb

Happening for a couple of days now, think the server is overloaded?

**Comment by dumbbell** [comment]
Hi!

The Pivotal network is under maintenance, causing www.rabbitmq.com to badly respond. In the meantime, you can get release archives and packages from GitHub:
https://github.com/rabbitmq/rabbitmq-server/releases

Unfortunately, we don't have any Debian repository mirror at this time. We are sorry for the caused troubles.

**Comment by vespakoen** [comment]
Thanks for the heads up!

**Comment by michaelklishin** [comment]
Please see [this mailing list thread](https://groups.google.com/d/msg/rabbitmq-users/wA80u5Xcvy8/AkoOjcoTyxsJ). We do have a repository on Package Cloud now.
