### ISSUE TITLE
 hostname used as a dynamic value on service start although it is statically configured on installation

### ISSUE THREAD

**Issue by hujog** [rabbitmq/rabbitmq-server#871]
The current hostname of the computer (= dynamic) running RabbitMQ is used when the service is started although it is a static value in the configuration.

Suggested solution: RabbitMQ should configure the hostname static on installation and use it on startup of the service. 
As a user this can be done manually via the environment variable "RABBITMQ_NODENAME" ... from then on the hostname of the computer running RabbitMQ can be changed without adverse effect to RabbitMQ. This should be default.

Advantage: Users can change the hostname and RabbitMQ will just work (instead of searching the internet for the issue and finding "solutions" like reinstalling RabbitMQ because of this logic bug).

Disadvantage: None I see.

**Comment by michaelklishin** [comment]
Please post your suggestions to rabbitmq-users first. I have doubts that it is as straightforward as you think it is: hostnames must actually resolve, not just "be statically configured".

**Comment by hujog** [comment]
OK. Did so.
But the point is: The nodename is static. The nodename tried on startup of the service is dynamically created.
RabbitMQ just dies if the statically configured nodename (rabbitmq@<hostnameOnInstallation>) does not match the dynamically determined hostname (rabbitmq@<currentHostName>) on service startup.
I really think it is a bug and not a usability issue to use a static nodename in one part of the solution and a dynamically created one in another part.
If the solution is to use current nodename at both places or static nodenames at both places: I don't know what would be better but it needs to be consistent.

**Comment by michaelklishin** [comment]
Please post your suggestions to rabbitmq-users. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not discussions. Thank you.

**Comment by michaelklishin** [comment]
If an actionable item comes out of a mailing list discussion, we file new issues.
