### ISSUE TITLE
Deadlettering exclusive queues

### ISSUE THREAD

**Issue by marcincinik** [rabbitmq/rabbitmq-server#872]
There should be an option to create exclusive queues, which's content is deadlettered when consumer disconnects.

Why ?

Let's imagine a scenario where I have multiple workers which consume and process messages. They are all the same in terms of functionality and all create exclusive queue and bind to an exchange to consume messages. 
The queue name is random (we work with docker & runshare). **If any consumer ends it's operation pre-maturely (is killed by administrator), then its queue and all pending messages disappear**. 

We cannot use competing consumer pattern, because we use hashed exchange to ensure that a single consumer always processes messages of the same kind. I don't want explain why messages of the same type must be processed in serial - assume that this is a limitation of our legacy software we use behind the scenes.

Timeouts (TTL exchange/queue) are not an option for us. We would need to set very high TTL, because processing of a single message may take long. On the other hand we cannot wait long for fail-over.

So in order to provide high reliability and ensure that all messages are either processed or dead-lettered, we would need to be able to deadlettter exclusive queues' content when they are disconnected.

**Comment by michaelklishin** [comment]
There was (not sure if it was moved to GitHub) a more generic issue about dead-lettering queue contents when it is deleted. There are no currently plans to do that: that potentially can result in many millions of messages being re-published when the user least expects that.

**Comment by michaelklishin** [comment]
Also note that exclusive queues are *only* supposed to be used when you can afford to lose all messages since if your consumer loses network connection then the queue will be deleted, too. So, only dead-lettering transient, consumer-specific state.

**Comment by marcincinik** [comment]
I understand your position 
Consider it though. It's a bit un-logical that you can ensure message to be dead-lettered in every case, except for this particular one. This would really improve functionality of the product.
There is really no better way to address our scenario than this.

... and thanks for so quick response - wow!! :)

**Comment by marcincinik** [comment]
" can result in many millions of messages being re-published "
This may also happen in case of queues with TTL .

"only supposed to be used when you can afford to lose all messages".
We're speaking about extension here - I'm aware of that. I reckon this is a gap in the spec.

**Comment by michaelklishin** [comment]
@marcincinik we understand that dead-lettering of messages when a queue is deleted would be very nice and logical in some cases. However, some features carry a non-trivial amount of risk with them. This is one of those features.
