### ISSUE TITLE
what i should do about rabbitmq lay4 check？

### ISSUE THREAD

**Issue by Michael754267513** [rabbitmq/rabbitmq-server#874]
this is a example about check redis.
option tcp-check
tcp-check send PING\r\n
tcp-check expect string +PONG
tcp-check send QUIT\r\n
tcp-check expect string +OK
[root@QA-PUB01 conf]# telnet 192.168.2.216 6379
Trying 192.168.2.216...
Connected to 192.168.2.216.
Escape character is '^]'.
ping
+PONG
quit
+OK
Connection closed by foreign host.
when i post a command,redis give me a string.but rabbitmq i not found this feature!
how to config about rabbitmq？

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.
