### ISSUE TITLE
rabbitmq-server and rabbitmqctl broken with long names and some bizarre DNS configurations

### ISSUE THREAD

**Issue by binarin** [rabbitmq/rabbitmq-server#890]
When you have a strangely configured system where `hostname -f` returns name without a dot in it (hello, k8s), `erl -name test` fails to start. Some rabbit code expects that this magic will work, i.e. the server prelaunch process and the rabbitmqctl. 

Simplest fix is to unconditionally add `@localhost` when long names are used: in prelaunch and other places. Will it be accepted to `stable`?

Another option is to add yet another environment variable, where you can provide this suffix in case where you know that your name resolving is somewhat broken.

WDYT?

**Comment by binarin** [comment]
Here is one of the lines that I want to change - https://github.com/rabbitmq/rabbitmq-server/blob/db33a5669e3b48f216dd7003a4d076bc3bd992c8/scripts/rabbitmq-server#L80

**Comment by michaelklishin** [comment]
The "unconditionally" above means "when a long name looks like a short name"?

I'll let @dumbbell decide how risky complicating our shell scripts further can be.

**Comment by binarin** [comment]
I thought about it overnight and did some experiments. I think that `@localhost` in prelaunch is completely safe. And with `rabbit_cli.erl` I decided to preserve as much of old behaviour as possible, even if it isn't strictly necessary.

**Comment by binarin** [comment]
If it's OK, should I also make the same change to `rabbitmq-cli`?

**Comment by dumbbell** [comment]
If you are still interested, yes please submit a patch to rabbitmq-cli. Thank you!

**Comment by binarin** [comment]
Yes, I'll try do it in a nearest future.

**Comment by michaelklishin** [comment]
Yes, keeping the new CLI up-to-date would be great. @binarin note that we are reviewing 7 or so pull requests for CLI so I'd wait for a few days until the dust settles.

**Comment by michaelklishin** [comment]
I assume this can be closed now.

**Comment by michaelklishin** [comment]
@binarin now that the new CLI is merged and being dogfooded in master, is backporting this still relevant? and something you'd be interested in doing?

**Comment by binarin** [comment]
Yes, this is still on my TODO list.

**Comment by michaelklishin** [comment]
@binarin thank you!
