### ISSUE TITLE
CLI: some warnings are sent to standard output

### ISSUE THREAD

**Issue by emmanuel-benoit** [rabbitmq/rabbitmq-server#8912]
### Describe the bug

The `rabbitmqctl` tool that comes with RabbitMQ 3.11.20 sends its warnings to the standard output stream instead of the standard error stream. This causes problems with scripts that use it with e.g. `--formatter json`

### Reproduction steps

1. Have some settings that cause a warning to be issued when using `rabbitmqctl` (e.g. disable TLS server authenticity checks).
2. Run e.g. `rabbitmqctl cluster_status --formatter json 2>/dev/null`

### Expected behavior

The command above should only display the JSON-formatted data. Instead, the output starts with warnings and then contains the JSON data.

**Comment by lukebakken** [comment]
> Have some settings that cause a warning to be issued when using rabbitmqctl (e.g. disable TLS server authenticity checks)

Please provide more exact steps to reproduce, thanks.

Currently it appears that `logger` is set to write to stderr - https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbitmq_cli/config/config.exs#L27

Usage of `IO.puts`:

```
lbakken@shostakovich ~/development/rabbitmq/rabbitmq-server/deps/rabbitmq_cli (main $=)
$ git grep '\<IO\.put'
lib/rabbitmq/cli/core/input.ex:17:          IO.puts(prompt)
lib/rabbitmq/cli/core/parser.ex:164:        IO.puts(:stderr, "Error reading aliases file #{aliases_file}: #{err}")
lib/rabbitmq/cli/diagnostics/diagnostics_helpers.ex:30:      IO.puts("Will connect to #{hostname_or_ip}:#{port}")
lib/rabbitmq/cli/diagnostics/diagnostics_helpers.ex:34:          IO.puts("Error connecting to #{hostname_or_ip}:#{port}: #{err}")
lib/rabbitmq/cli/plugins/commands/list_command.ex:65:        IO.puts("WARNING - plugins currently enabled but missing: #{names}\n")
lib/rabbitmq/cli/printers/file.ex:25:      IO.puts(io_device, line)
lib/rabbitmq/cli/printers/file.ex:30:    IO.puts(io_device, output)
lib/rabbitmq/cli/printers/std_io.ex:17:      IO.puts(line)
lib/rabbitmq/cli/printers/std_io.ex:22:    IO.puts(output)
lib/rabbitmqctl.ex:203:    IO.puts("Stack trace: \n")
lib/rabbitmqctl.ex:204:    IO.puts(Exception.format(error_type, error, stacktrace))
lib/rabbitmqctl.ex:249:      IO.puts(device, Helpers.string_or_inspect(line))
lib/rabbitmqctl.ex:321:                for line <- list, do: IO.puts(line)
lib/rabbitmqctl.ex:324:                IO.puts(binary)
```

**Comment by michaelklishin** [comment]
RabbitMQ CLI tools do not log the absolute majority of the warnings, their dependencies do.

We cannot always control what they log, where or why.

Adding `--quiet` should help.

**Comment by emmanuel-benoit** [comment]
Adding `--quiet` does not help in that specific warning's case : 

```
# rabbitmqctl cluster_status --quiet --formatter json 2>/dev/null | grep warning | wc -l
3
```

In addition, the dependency itself hasn't been updated in any way, the only thing being replaced here is the RabbitMQ package.

**Comment by michaelklishin** [comment]
Because it is logged by the Erlang TLS implementation and not RabbitMQ CLI tools.

@emmanuel-benoit yes, the dependencies are updated over time. 3.11.20 was produced with Elixir 1.15, Erlang versions that are used to build and run CLI tools change over time, and so on.

**Comment by michaelklishin** [comment]
@lukebakken the problem here is that there are three things that may potentially log warnings:

 * RabbitMQ CLI tools, they should abide by `--quiet` virtually everywhere (but not in the case of unhandled exception, for instance)
 * Elixir libraries (that usually use Elixir logger settings)
 * Erlang standard library components such as TLS (that in theory always use the standard Erlang logger)

We cannot do much more than set a decent log level in the latter two cases.

Silencing logging entirely for `--formatter`s other than the default one is the only solution I can think of.

Or we can just declare this an acceptable limitation of machine-readable output formats and move on to much more important issues.

**Comment by emmanuel-benoit** [comment]
I meant Erlang's TLS library when saying "the dependency". I am using Erlang 25.3 so that means TLS 10.9.1.1, which hasn't changed in a year. Sorry if that was unclear.

The a0ec65d549cc94a4ca6c1fbb6cac3efe4375657d commit is linked to the Elixir 1.15 change and does affect some logging configuration, may it be related to the problem I'm having ? (I'm clueless when it comes to Erlang though, sorry).

**Comment by michaelklishin** [comment]
Starting with [1.15](https://elixir-lang.org/blog/2023/06/19/elixir-v1-15-0-released/), Elixir now delegates more work to the Erlang `logger`. We only configure the Elixir logger, and it looks like some of the configuration settings have changed with 1.15.

I will try to silence the standard Erlang logger in CLI tools entirely, the only places where we need its output is when CLI tools fail to authenticate to the target node.

**Comment by emmanuel-benoit** [comment]
I will test this first thing tomorrow. Thank you !

**Comment by michaelklishin** [comment]
8916 is included into

 * [`3.12.3-alpha.6`](https://github.com/rabbitmq/rabbitmq-server-binaries-dev/releases/tag/v3.12.3-alpha.6) (there is a .deb package you can install with `dpkg -i`)
 * [This Cloudsmith repo](https://cloudsmith.io/~rabbitmq/repos/rabbitmq-server-all-dev/packages/?q=3.12.3) for development builds. If you choose to use this repo, you *must* [pin the version](https://rabbitmq.com/install-debian.html#apt-pinning) or you will end up with 3.13 alphas very quickly

**Comment by emmanuel-benoit** [comment]
In the meantime, the `3.11.21-alpha.5` package was made available, and it's the one I used to test. It works, warnings are gone.

```
# dpkg -i /tmp/rabbitmq-server_3.11.21.alpha.5-1_all.deb
# tail -n 3 /etc/rabbitmq/rabbitmq-env.conf 
RABBITMQ_CTL_ERL_ARGS="-pa $ERL_SSL_PATH
  -proto_dist inet_tls
  -ssl_dist_opt client_cacertfile /etc/rabbitmq/ssl/ca.pem"
# rabbitmqctl cluster_status --quiet --formatter json 2>/dev/null | grep warning | wc -l
0
# rabbitmqctl cluster_status --formatter json 2>&1 >/dev/null | grep warning | wc -l
0
```

Thank you!
