### ISSUE TITLE
Shovel with Filtering/Header Exchange based Shovel

### ISSUE THREAD

**Issue by VipinEV** [rabbitmq/rabbitmq-server#8978]
### Is your feature request related to a problem? Please describe.

Hello Team,

Would it be good to have the below feature?
 
vhost1 > exchange1 > filter set of messages > vhost2 > exchange2
OR
vhost1 > header-exchange1 > header based filtering > vhost2 > queue2.

Do we have any workaround for this now?

### Describe the solution you'd like

This will help to

1. Use rabbitmq for broadcasting messages to multiple client in other vhosts with message filtering. 

### Describe alternatives you've considered

1. Declare a header exchange in vhost1.
2. Bind a queue - q1.
3. Create shovel from q1 to q2 (in vhost2)

### Additional context

The above approach ends up in creating more and more replication queues in vhost1 per each client.

**Comment by michaelklishin** [comment]
Using exchange to exchange bindings you can do just that on both source and destination ends.
