### ISSUE TITLE
Getting this with rabbitMQ 3.6.3 and erlang 19 

### ISSUE THREAD

**Issue by arnabiitr** [rabbitmq/rabbitmq-server#899]
Getting this error after creating a queue ,reverting back to erlang 18 resolves it .

Got response code 500 with body {"error":"JSON encode error: {bad_term,#{error_logger => true,kill => true,size => 0}}","reason":"While encoding: \n[{total_count,1},\n {item_count,1},\n {filtered_count,1},\n {page,1},\n {page_size,100},\n {page_count,1},\n {items,\n [[{memory,10840},\n {reductions,2043},\n {reductions_details,[{rate,302.4}]},\n {messages,0},\n {messages_details,[{rate,0.0}]},\n {messages_ready,0},\n {messages_ready_details,[{rate,0.0}]},\n {messages_unacknowledged,0},\n {messages_unacknowledged_details,[{rate,0.0}]},\n {idle_since,<<\"2016-07-29 22:56:25\">>},\n {consumer_utilisation,''},\n {policy,''},\n {exclusive_consumer_tag,''},\n {consumers,0},\n {recoverable_slaves,''},\n {state,running},\n {reductions,2043},\n {garbage_collection,\n [{max_heap_size,#{error_logger => true,kill => true,size => 0}},\n {min_bin_vheap_size,46422},\n {min_heap_size,233},\n {fullsweep_after,65535},\n {minor_gcs,0}]},\n {messages_ram,0},\n {messages_ready_ram,0},\n {messages_unacknowledged_ram,0},\n {messages_persistent,0},\n {message_bytes,0},\n {message_bytes_ready,0},\n {message_bytes_unacknowledged,0},\n {message_bytes_ram,0},\n {message_bytes_persistent,0},\n {head_message_timestamp,''},\n {disk_reads,0},\n {disk_writes,0},\n {backing_queue_status,\n {struct,\n [{mode,default},\n {q1,0},\n {q2,0},\n {delta,[delta,undefined,0,undefined]},\n {q3,0},\n {q4,0},\n {len,0},\n {target_ram_count,infinity},\n {next_seq_id,0},\n {avg_ingress_rate,0.0},\n {avg_egress_rate,0.0},\n {avg_ack_ingress_rate,0.0},\n {avg_ack_egress_rate,0.0}]}},\n {node,'rabbit@arnabiitr-PC'},\n {arguments,{struct,[]}},\n {exclusive,false},\n {auto_delete,false},\n {durable,true},\n {vhost,<<\"/\">>},\n {name,<<\"testfirst\">>}]]}]"}

**Comment by michaelklishin** [comment]
Use Erlang 18 or move to RabbitMQ 3.6.4.

**Comment by michaelklishin** [comment]
Duplicate of https://github.com/rabbitmq/rabbitmq-management/issues/244.
