### ISSUE TITLE
Introduce an authentication API module

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#90]
We have a bunch of modules that deal with authentication backends. However, some functions that deal with authentication in general or backend selection are currently scattered in `rabbit_reader`, `rabbit_access_control`, and possibly more places. Not only this conflates authentication with authorisation, I've seen some projects use `rabbit_access_control/check_user_login/2` to verify credentials after Puppet runs, etc.

We could benefit from a new authentication module that would:

 * Contain authentication-related bits that do not belong to backends scattered elsewhere.
 * Introduce a public API.

Note that it may be already too late to remove `rabbit_access_control/check_user_login/2` since the official Puppet module has switched to use it (from `rabbit_auth_backend_internal/internal_check_user_login/2`).

**Comment by simonmacmullen** [comment]
`rabbit_access_control` is meant to be that API.

It might be that bits have escaped and need to be pulled back into it.

**Comment by simonmacmullen** [comment]
Also note that (at the moment) there are not considered to be any public (read: stable) APIs inside the broker; anything can change at a feature release and plugin authors are expected to keep up. You could change that promise of course, but APIs would benefit from some review before becoming frozen.

**Comment by michaelklishin** [comment]
Fortunately this particular API area is very small (1 or 2 functions people care about most).

**Comment by michaelklishin** [comment]
Closing as there seems to be little interest in having one more module. Lets assume `rabbit_access_control` is our public API for the time being.
