### ISSUE TITLE
3.12.2 + keycloak -> "TypeError: Failed to fetch"

### ISSUE THREAD

**Issue by pasztorl** [rabbitmq/rabbitmq-server#9012]
### Describe the bug

I've configured rabbitmq to use oauth2 with the management ui.
When starting the auth flow, rabbitmq redirects to the sso url, after a successful auth the keycloak redirects back, then the rabbitmq ui just says "TypeError: Failed to fetch"
I've adjusted the log.default.level to debug, but nothing showed up in the rabbitmq log about the issue.
How can I debug this issue?

### Reproduction steps

have a working keycloak instance then followed the repos keycloak example

### Expected behavior

auth works or if it is some configuration error I can see some log about it in the rabbitmq log output(s)

**Comment by pasztorl** [comment]
I've checked the js console, and j see this message
`[UserManager] getUser: user not found in storage`
So my guess is that the problem occurs in the odic-client-ts so this is why I can't see log about it in rabbitmq

**Comment by pasztorl** [comment]
It was a cors setting misconfiguration, not related to rabbitmq-oidc, closing the issue.

**Comment by DaYangtuo247** [comment]
> 这是 cors 设置错误配置，与 rabbitmq-oidc 无关，关闭了问题。

Could you tell me how to configure the solution?
