### ISSUE TITLE
Be able to block consuming from a queue throw Rabbit admin 

### ISSUE THREAD

**Issue by shmuel-buchnik** [rabbitmq/rabbitmq-server#903]
Hi 
I would like in some scenarios to block all consumers from consuming a specific queue .
I was surprised to find out there is no such option .
The Idea is that I could click some button and messages can be publish to queue , but no one can consume it until I release the queue from this state.

**Comment by michaelklishin** [comment]
You can [limit specific protocol operations](http://www.rabbitmq.com/access-control.html) on a queue.

This is not a commonly requested feature, so we will focus on other things for now. It's not clear how this is going to work for existing outstanding deliveries, too, so perhaps start a mailing list thread where this can be hashed out and others who have the need for this can chime in to convince our team. Thank you.
