### ISSUE TITLE
RHEL9 RPM labeled as EL8

### ISSUE THREAD

**Issue by rdswett** [rabbitmq/rabbitmq-server#9049]
### Describe the bug

The RPM provided in the EL9 YUM/DNF repo is labeled as "el8". If the RPM is truly agnostic, then I suggest that the distro be removed from the RPM file name.  

### Reproduction steps

1. Download rpm from https://packagecloud.io/rabbitmq/rabbitmq-server/el/9/x86_64
2. Note the "el8" in the file name

### Expected behavior

RPM either has "el9" or no distro in the file name, ie rabbitmq-server-3.12.2-1.noarch.rpm

### Additional context

Managing RPMs for systems not connected to the internet that have both el8 and el9 hosts means that I often have to download packages and rely on the file name to know what distro the RPM is meant for.

**Comment by michaelklishin** [comment]
The suffix is there historically to differentiate between el7 and everything after it. It's exactly the same package. Our small team has more important things to worry about than updating pipelines to change or remove the suffix.

PackageCloud *requires* that a published package is labelled with a distribution name, so we upload the same package N times and label it for N common modern distributions.

Note that PackageCloud is going away this fall, permanently, for bureaucratic reasons. See the [RPM-based distribution installation guide](https://rabbitmq.com/install-rpm.html) to find out what the alternative is.
