### ISSUE TITLE
Access granted for client cert signed by intermediate CA which is not in the cacertfile but is signed by a root CA that is

### ISSUE THREAD

**Issue by ppickett-pivotal** [rabbitmq/rabbitmq-server#907]
I have a 'cacertfile' with 2 certificates, rootCA and intermediateCA-1.

An app can authenticate using the client cert that was issued by that intermediateCA-1, which works as expected.

The app can also authenticate using the client cert issued by a different intermediate CA (i.e., intermediateCA-2). This seems like a problem.

Both intermediateCA-1 and intermediateCA-2 are signed by rootCA.

**Comment by michaelklishin** [comment]
RabbitMQ does not perform peer verification except if the trust store plugin is used. Plus this is very little information to work with. How can this be reproduced with a two sets of certificates generated via [tls-gen](https://github.com/michaelklishin/tls-gen), for example?

Sorry but this belongs to the mailing list or a similar discussion venue.

**Comment by michaelklishin** [comment]
If both intermediate certificates were signed by a **trusted** root CA then their own issued certificates must be treated as valid per [section 6.1 of RFC 5280](https://tools.ietf.org/html/rfc5280#section-6.1). The root CA is the trust anchor in the RFC.
