### ISSUE TITLE
Dynamic Shovel is not executed, only when rebooting the server

### ISSUE THREAD

**Issue by hueby** [rabbitmq/rabbitmq-server#9114]
### Describe the bug

Hey folks,

we are experiencing a strange behavior with shovels in RabbitMq 3.12.2 Erlang 26.0.2. We upgraded from 3.11.15. After the upgrade we migrated to quorum queues and are using 3 nodes for our deployment.
We are using the shovel_plugin via the Management Web UI to transfer failed messages from an error to another queue. In some cases the created shovel does nothing. Under "Shovel Management" in the UI, I can see the shovel, but not in "Shovel status". When I use "rabbitmqctl shovel_status" the response is empty. When I am re-executing the shovel from the queue, nothing happens. When we want to delete the shovel via the UI, we get an error, that the shovel cannot be deleted
However, when I restart the server, the shovel seems to get executed, the messages in the error queue are gone.
The server logs don't show any errors.
This behavior is very seldom, but critical, because we have to restart the cluster, to retry our messages.
Is anyone else experiencing this "bug" I might call it. What can we do to solve this issue?

### Reproduction steps

1. Use RabbitMq server 3.12.2 Erlang 26.0.2 via Management Web UI
2. Open an error_queue and use the "Move messages"-section
3. Paste the destination queue and press "Move messages
4. We are being directed to the "Queues and Streams" page
5. Nothing happens
6. Error_queue is still filled with messages
7. Cannot delete the shovel under "Shovel Management"
8. Rebooting the server executes the shovel

### Expected behavior

1. Use RabbitMq server 3.12.2 Erlang 26.0.2 via Management Web UI
2. Open an error_queue and use the "Move messages"-section
3. Paste the destination queue and press "Move messages
4. We are being directed to the "Queues and Streams" page
5. The shovel gets executed

### Additional context

We are using following plugins:
[E*] rabbitmq_delayed_message_exchange 3.12.0
[E*] rabbitmq_management               3.12.2
[E*] rabbitmq_management_agent         3.12.2
[e*] rabbitmq_peer_discovery_common    3.12.2
[E*] rabbitmq_peer_discovery_k8s       3.12.2
[E*] rabbitmq_prometheus               3.12.2
[E*] rabbitmq_shovel                   3.12.2
[E*] rabbitmq_shovel_management        3.12.2
[e*] rabbitmq_web_dispatch             3.12.2

We have configured a vhost "/" or "%2F" with default_queue_type "quorum".
For deployment we are using the bitnami rabbitmq chart.

**Comment by mkuratczyk** [comment]
I've tried multiple times and it worked fine every time. Please provide logs and/or more detailed reproduction steps

**Comment by hueby** [comment]
Sorry for the late response. The problem is still happening in our cluster, but very, very seldom. It is not consistently reproduceable. Can't provide more informations. We will observe this behavior, maybe there is a way to reproduce this.

**Comment by michaelklishin** [comment]
@HrithikMJ we cannot suggest anything with a two sentence problem descriptions. Hijacking existing issues is also greatly not appreciated.

Collect logs, versions, a way to reproduce and start a new discussion.
