### ISSUE TITLE
High memory usage on mirrored queues configured with reject-publish

### ISSUE THREAD

**Issue by TatianaNeuer** [rabbitmq/rabbitmq-server#9115]
### Describe the bug

Hello, 

We came accross a high memory usage on mirorring nodes with a queue configured with max-length-bytes and reject-publish. When the queue is full, the mirroring nodes start using more and more memory for "mirror_queue_slave" process until their memory usage goes beyond the watermark.

### Reproduction steps

1. Have a 3-node RabbitMQ cluster 
2. Create a policy for all queues with the following arguments:
```
ha-mode: all 
queue-master-locator: min-masters
ha-sync-mode: automatic
```
3. Create a queue with the following arguments:
```
durable 
x-max-length-bytes: 10485760
x-overflow: reject-publish 
```
4. Publish and consume messages from the queue (publish rate > consumer rate) until the memory usage is very high on mirroring nodes

To be precise, we used the following [RabbitTestTool](https://github.com/rabbitmq/RabbitTestTool/tree/main/benchmark) topology:
```
{
	"topologyType": "fixed",
	"benchmarkType": "throughput",
	"topologyGroups": [
		{
			"name": "minimal",
			"exchanges": [
				{
					"name": "exchange-direct",
					"type": "direct"
				}
			],
			"queues": [
				{
					"prefix": "mirrored-limited-queue",
					"scale": 1,
					"properties": [
						{
							"key": "x-queue-mode",
							"value": "default",
							"type": "string"
						},
						{
							"key": "durable",
							"value": true,
							"type": "boolean"
						},
						{
							"key": "x-max-length-bytes",
							"value": 10485760,
							"type": "int"
						},
						{
							"key": "x-overflow",
							"value": "reject-publish",
							"type": "string"
						}
					],
					"bindings": [
						{
							"from": "exchange-direct",
							"bindingKeys": [
								"binding.to.queue"
							]
						}
					]
				}
			],
			"publishers": [
				{
					"prefix": "pub",
					"scale": 5,
					"publishMode": {
						"useConfirms": "false",
						"inFlightLimit": "10"
					},
					"sendToExchange": {
						"exchange": "exchange-direct",
						"routingKeys": [
							"binding.to.queue"
						],
						"routingKeyMode": "MultiValue"
					},
					"deliveryMode": "persistent",
					"messageSize": "350",
					"msgsPerSecondPerPublisher": "100"
				}
			],
			"consumers": [
				{
					"prefix": "sub",
					"ackMode": {
						"manualAcks": true,
						"consumerPrefetch": 10,
						"ackInterval": 1
					},
					"scale": 10,
					"queuePrefix": "mirrored-limited-queue",
					"processingMs": 50
				}
			]
		}
	],
	"dimensions": {
		"fixedDimensions": {
			"durationSeconds": 72000,
			"rampUpSeconds": 30
		}
	}
}
```

### Expected behavior

The mirroring nodes should release more memory.

### Additional context

Here are the metrics, green is the leader node (node on which the queue is located), blue and yellow are the mirroring nodes:
![minimalTest_1queue_zoom_focus](https://github.com/rabbitmq/rabbitmq-server/assets/9024391/d3398764-8bb3-4d77-84d8-892b3ca22785)
- the queue is full in less than 2 minutes, once it is full only the leader node releases memory
- then the mirroring nodes use more and more memory
- around 13:20 flow control is triggered (publishing rate is lower and unstable), however mirroring nodes continue to use more memory 
- around 15:15 we stopped the publishers and the consumers but mirroring nodes released their memory a few hours after
![minimalTest_1queue _focus](https://github.com/rabbitmq/rabbitmq-server/assets/9024391/ae66f968-d316-4164-983a-863be4ef5be6)

Here are the top processes:
Leader node:
![minimalTest_topLeader](https://github.com/rabbitmq/rabbitmq-server/assets/9024391/5f0494ec-6af5-4d04-a8d5-a9b9a206550b)
A mirroring node:
![minimalTest_topMirror1](https://github.com/rabbitmq/rabbitmq-server/assets/9024391/24731557-b5bb-4bca-930c-e5c0c335662c)

**Comment by michaelklishin** [comment]
Classic mirrored queues have been [deprecated for well over two years now](https://blog.rabbitmq.com/posts/2021/08/4.0-deprecation-announcements/). They are scheduled for removal in early 2024.

Please [migrate to quorum queues](https://blog.rabbitmq.com/posts/2023/02/quorum-queues-migration/). All [core team's efforts](https://blog.rabbitmq.com/posts/2023/05/rabbitmq-3.12-performance-improvements/) now go into QQs, streams and non-mirrored classic queues.

We will investigate

A couple of things you can try:

 * After upgrading to 3.12, [use CQv2 for classic queues](https://blog.rabbitmq.com/posts/2023/05/rabbitmq-3.12-performance-improvements/) (`classic_queue.default_version = 2` in `rabbitmq.conf`)
 * Use [bandwidth limiting for CMQ](https://www.rabbitmq.com/ha.html#batch-sync) sync introduced in https://github.com/rabbitmq/rabbitmq-server/pull/3911
