### ISSUE TITLE
Quorum queues and queue federation do not get along

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/rabbitmq-server#9138]
### Describe the bug

VESC-1079
VESC-1082

A customer reported that they must restart Federation links (for federated queues) from time-to-time as these links stop consuming. Even more mysterious is that messages are left in an un-acked state, and do not trigger the consumer timeout.

The Federation links are for queue federation of quorum queues. I have tested this scenario and can reproduce the issue. Changing the federated queues to classic queues with `ha-mode: all` works without issue, and performs better to boot.

### Reproduction steps

* Clone https://github.com/lukebakken/vesc-1079-1082
* `cd pika; pipenv install`
* Ensure you have `docker` and `docker compose` available
* `make DOCKER_FRESH=true RABBITMQ_QUEUE_TYPE=quorum up` will bring up three clusters
* Once the three clusters have started, run `make import` which will import definitions into each cluster, setting up the expected exchanges, queues and federation links
* Once import succeeds, open three terminals, and change to the `pika` directory. In two terminals, set up your consumers for the `wdc` and `odc` clusters:
    ```
    pipenv shell
    python ./consume.py --port=5673 # wdc

    # other terminal
    pipenv shell
    python ./consume.py --port=5674 # odc
    ```
* In the other terminal, start the publisher:
    ```
    pipenv shell
    python ./publish.py --interval=0 --msgcount=100000 # this publishes as fast as possible
    ```

Frequently at this point, even though you have consumers ready, they won't receive any messages! Your publisher will be running and messages will pile up in the `hdc` cluster. If you restart the federation links in `wdc` and `odc` then consuming starts. Then, watch your consumers because before all 100000 messages are consumed, one or both of them usually stops.

To stop your environment and clean up, run `make down`.

To observe a successful run, follow the above instructions but use classic queues:

```
make RABBITMQ_QUEUE_TYPE=classic up
```

### Expected behavior

Federated queues using quorum queues should work the same as classic.

**Comment by mkuratczyk** [comment]
result of `rabbitmqctl eval "sys:get_state(whereis('%2F_inventory-fed'))."` when both federation links hang
[qq.state.erl.gz](https://github.com/rabbitmq/rabbitmq-server/files/12381230/qq.state.erl.gz)

**Comment by mkuratczyk** [comment]
and here's the state on downstream (corresponds to the upstream state above)
[qq-downstream.state.erl.gz](https://github.com/rabbitmq/rabbitmq-server/files/12381250/qq-downstream.state.erl.gz)

**Comment by alphamonkey79** [comment]
Hey Guys
Thanks for the help with this!
Do we have a ballpark figure of when a fix/patch would be available?

**Comment by mkuratczyk** [comment]
We have a fix now. I've been running it for ~5 hours and the issue hasn't occurred so it's good (previously it would occur within 5-10 minutes). There'll be a PR tomorrow, then it's a matter of shipping a new release.

**Comment by michaelklishin** [comment]
A new patch release will ship in the next couple of weeks.

**Comment by lukebakken** [comment]
An improvement that came out of investigating this issue: https://github.com/rabbitmq/rabbitmq-server/pull/9150

@kjnilsson will have a PR soon to fix this issue.

**Comment by alphamonkey79** [comment]
Awesome!Sent from my iPhoneOn Aug 22, 2023, at 2:58 PM, Michal Kuratczyk ***@***.***> wrote:﻿
We have a fix now. I've been running it for ~5 hours and the issue hasn't occurred so it's good (previously it would occur within 5-10 minutes). There'll be a PR tomorrow, then it's a matter of shipping a new release.

**Comment by michaelklishin** [comment]
Addressed in #9158

**Comment by eibbojtir** [comment]
> Addressed in #9158

Thanks! Will this fix make it into 3.11.x?

**Comment by eibbojtir** [comment]
Context: The upgrade to 3.12 is on our roadmap for early 2024. Thus, we're looking for this fix to make it into 3.11.x. Our commercial support for 3.11 runs until July 2024.

@lukebakken @michaelklishin @kjnilsson 

Thanks!

**Comment by kjnilsson** [comment]
It's in the 3.11.23 milestone https://github.com/rabbitmq/rabbitmq-server/milestone/176?closed=1

**Comment by michaelklishin** [comment]
Backported to `v3.11.x` https://github.com/rabbitmq/rabbitmq-server/pull/9164.

`3.11.23` will ship in a couple of weeks.
