### ISSUE TITLE
Intermediate gm group alternations, on removal of dead gm pids from queues aren't handled.

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-server#914]
In case of `gm_deaths` being broadcast to the gm group members, there are instances where intermediate events can occur (another partition for example) in which a slave is promoted to master, whilst removal of dead gm pids from the queue is in procession. The mirror queue coordinator  will be informed of the new master (promoted slave) during this timeframe, which has now deferred from what it was previously expecting. Currently, the mirror queue coordinator only expects the original master prior the slave's promotion, and/or, the case where the queue no longer exists (may have been deleted), in which it terminates. If the master has indeed changed, then this should be handled appropriately without crashing the mirror queue coordinator, which is linked to the initiating queue master process (which hasn't terminated, but merely become a slave), and thus causing more alterations to the gm group. 

Such an event could also potentially result in a slave acquiring more nodes to add mirrors on, than initially expected, in light of a different slave process being promoted to master. Handling of these rare cases needs to be added.

**Comment by michaelklishin** [comment]
@Ayanda-D there are certain issues in GM that can only be solved by replacing GM with something else. If that's not one of those cases, please take a look into a test case and fix :)

**Comment by Ayanda-D** [comment]
@michaelklishin sure, working on it. Minimal handling of this case seems to have been overlooked in the current implementation, and shouldn't be the cause of some of the problems regarding the GM. & as I've mentioned already, the case is rare and just needs to be handled appropriately, so I doubt simulating this scenario in a test case is feasible.

**Comment by noahhaon** [comment]
Hi @Ayanda-D , we've seen a case in our testing multiple nodes in a cluster will crash if a node hosting a master queue and any other node are brought down prior to a new master being selected, and the `ha-mode: all` policy is set on the queue.

Our QA team is working on creating a simplified test case for submission to Pivotal, but they're not quit there yet.

Could it be that we are hitting this case?  If so, is there anything we should be keeping an eye out for in our logs?

**Comment by noahhaon** [comment]
Please disregard my prior comment, spoke with our engineers and it was `pause-minority` causing the "crashes" :)

**Comment by michaelklishin** [comment]
@Ayanda-D please post an update here when you have one.
