### ISSUE TITLE
Display a mid-sized yellow warning in Management UI if any feature flag is not enabled

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/rabbitmq-server#9148]
### Is your feature request related to a problem? Please describe.

We've seen users upgrading to recent versions (that require certain/all FF to be enabled) without having all required feature flags enabled. Upgrade proceeds without errors, but upgraded nodes can't boot. Examples of these occurrences:

- https://github.com/rabbitmq/cluster-operator/issues/1240#issuecomment-1687604168
- [Mailing list thread 1](https://groups.google.com/g/rabbitmq-users/c/wVNQoHsfhOw/m/AvWihapCAQAJ)

### Describe the solution you'd like

A mid-sized yellow warning box displayed in the management UI if there is one or more FF not enabled. For example:

<img width="1508" alt="Screenshot 2023-08-22 at 12 41 42" src="https://github.com/rabbitmq/rabbitmq-server/assets/1515757/ec6c7ef8-00cc-41fa-8795-ba12e6342efe">

**Comment by dumbbell** [comment]
Only stable feature flags should be considered, not all of them (i.e. not experimental ones).

Also, I would phrase the warnings as "Warning: some feature flags should be enabled before the next minor or major version upgrade of RabbitMQ" to emphasize the deadline to do it. Perhaps even "MUST be enabled".

**Comment by michaelklishin** [comment]
I'd keep the banner short and make it display a pop-up that says "All feature flags must be enabled after completing an upgrade. Without enabling all flags, upgrading to future minor or major versions of RabbitMQ may not be possible".

Or we can document this and link to that specific doc section.

**Comment by Zerpet** [comment]
I'm in favour of keeping the banner short and having a pop-up with more details and/or link to the docs.

> Only stable feature flags should be considered

Agreed 👍

**Comment by dcorbacho** [comment]
@michaelklishin @dumbbell I have a proposal to add the warning just in the feature flags page, to avoid adding another HTTP query to every page to check the state of the feature flags. It also adds a `Experimental` tag to those features that need it, otherwise with just the UI the users can't figure out which ones must be enabled. Any thoughts?

I think this will very useful to prepare for 4.0 upgrades.

<img width="1304" alt="Captura de pantalla 2023-11-07 a las 22 56 53" src="https://github.com/rabbitmq/rabbitmq-server/assets/646577/4c5d124b-01ae-4228-bec9-71d0ccb56fff">

**Comment by dumbbell** [comment]
I like this proposal!

About the stable vs. experimental feature flags, I think I would put some kind of warning near the "Enable" button of the stable feature flags. To emphasize that the "bad" situation is the fact that they are not enabled already. This would also put stable and experimental on a different level.

Here is a quick example with Inkscape:

![feature-flags](https://github.com/rabbitmq/rabbitmq-server/assets/159804/8328697b-324c-4908-8f04-07b6c81157e1)

(I don't know why it becomes blurry on GitHub...)

**Comment by lukebakken** [comment]
My $0.02 - if any flags are not enabled, every page on the management UI should indicate it. It should also be logged at the `warning` level every 5 to 10 minutes as well. There _might_ be a chance that someone will notice if we do all of that.

**Comment by dumbbell** [comment]
Logging something (and several other improvements) are scheduled for 4.0 or the next minor branch if we add one.

**Comment by Zerpet** [comment]
> My $0.02 - if any flags are not enabled, every page on the management UI should indicate it. It should also be logged at the `warning` level every 5 to 10 minutes as well. There _might_ be a chance that someone will notice if we do all of that.

I agree with Luke. I think any non-experimental disabled feature flag should be displayed in every page. TBH I didn't even know we had a page in the UI dedicated to FF 🙈 I guess the cost of consultng the FF status is cheap, so it should not be too bad to make this call in every page.

**Comment by michaelklishin** [comment]
Addressed in https://github.com/rabbitmq/rabbitmq-server/commit/5aa35e0570181618422f8e7ad09842900c313090.
