### ISSUE TITLE
I I encountered an error while running rabbimq，it was still normal until today

### ISSUE THREAD

**Issue by ve-weiyi** [rabbitmq/rabbitmq-server#9197]
### Describe the bug

I noticed that my service was down，running it immediately，but I failed . This is error log, I checked rabbitmq.conf and not found key 'classic_mirrored_queue_version' in file. who can help me...

![image](https://github.com/rabbitmq/rabbitmq-server/assets/67481255/c7f94588-005b-4e1d-8c66-55f7d6dca10e)

### Reproduction steps

1. brew update
2. brew install rabbitmq
3. rabbitmq-server
...

### Expected behavior

It can run successfully.

**Comment by mkuratczyk** [comment]
https://github.com/rabbitmq/rabbitmq-server/discussions/9013

**Comment by ve-weiyi** [comment]
> [第9013章](https://github.com/rabbitmq/rabbitmq-server/discussions/9013)

thanks , it is useful!!
