### ISSUE TITLE
Disk monitor fails to parse output on Ubuntu 12.04.5

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#92]
There's probably something environment-specific kicking in, [mailing list thread](https://groups.google.com/forum/#!topic/rabbitmq-users/agWKMcI9KF4).

Not sure if this can be qualified as a bug because it doesn't happen to me with a stock 12.04 VM.

**Comment by dumbbell** [comment]
The same parsing error happens to the reporter of #76.

I couldn't reproduce either.

**Comment by rade** [comment]
We've seen this crop up on a number of occasions in the past, yet have never been able to reproduce it. The condition to trigger this appears to be both environment specific and temporary.

**Comment by michaelklishin** [comment]
We haven't found the root cause specifically for this version but this doesn't seem to be coming up any more.
