### ISSUE TITLE
Content header frame too large (contrary to docs)

### ISSUE THREAD

**Issue by kae** [rabbitmq/rabbitmq-server#921]
Had this entry in rabbitmq log file (RabbitMQ 3.6.5, Erlang 19.0)

"operation none caused a connection exception frame_error: "type 2, all octets = <<>>: {frame_too_large,495535,131064}"

But https://www.rabbitmq.com/amqp-0-9-1-errata.html has 

> 11 frame-max, method and content header frames

>The specification states that frame-max (negotiated in connection.tune and connection.tune-ok) gives an upper limit to total frame size; that is, including the frame header and frame-end octet. However, there's no way to split methods or content headers across multiple frames. RabbitMQ currently ignores the frame-max for methods and content headers.

IMHO, it should be corrected in code or in documentation

**Comment by michaelklishin** [comment]
Please file this for https://github.com/rabbitmq/rabbitmq-website. That page probably wasn't updated since 2007 or so :) Not having a frame limit is not practical, in particular for hosted RabbitMQ scenarios.
