### ISSUE TITLE
Grafana dashboards use deprecated Angular plugins that will be removed in Grafana 10 or 11

### ISSUE THREAD

**Issue by frittentheke** [rabbitmq/rabbitmq-server#9218]
### Describe the bug

When importing / using the dashboards published at https://grafana.com/orgs/rabbitmq into recent versions of Grafana (e.g. Grafana v10.1.0) a warning is issued about the use of deprecated Angular Plugins:

> Angular plugin

> 
> This plugin uses a deprecated, legacy platform based on AngularJS and will stop working in future releases of Grafana.
>     [Read our deprecation notice and migration advice.](https://grafana.com/docs/grafana/latest/developers/angular_deprecation/)
>     [View plugin details](https://grafana.com/docs/grafana/latest/features/panels/graph/)

While the graph plugin is really quite widely used, Grafana commuicates a clear deprecation warning (see https://grafana.com/docs/grafana/latest/developers/angular_deprecation/) and urges everyone to move to newer panels.
In addition to getting rid of the deprecation, using the newer e.g. "timeseries" panels might also enable some new features in visualizing the RabbitMQ metrics ... see https://grafana.com/blog/2021/02/10/how-the-new-time-series-panel-brings-major-performance-improvements-and-new-visualization-features-to-grafana-7.4/

### Reproduction steps

1. Import e.g. the RabbitMQ Quorum queue dashboard (https://grafana.com/grafana/dashboards/11340-rabbitmq-quorum-queues-raft/)
2. Click "Edit" on any of the panels.
3. See warning
...

### Expected behavior

I'd expect official dashboards to not contain or require the use of deprecated features / plugins in Grafana.

**Comment by michaelklishin** [comment]
Thanks. So the solution is to migrate to React.

I wonder what that means for older Grafana users. E.g. if we release a new version based on React, would it work with Grafana 7? 8? The docs do not make it clear to me.

**Comment by frittentheke** [comment]
> Thanks. So the solution is to migrate to React.

Well not to "React", but to newer panel types for the dashboards you provide.

> I wonder what that means for older Grafana users. E.g. if we release a new version based on React, would it work with Grafana 7? 8? The docs do not make it clear to me.

If you look at the references blog about the new panels (https://grafana.com/blog/2021/02/10/how-the-new-time-series-panel-brings-major-performance-improvements-and-new-visualization-features-to-grafana-7.4/) those have been introduced early 2021 and with Grafana 7.4.

Do you really want / have to maintain compatibility with such old Grafana instances? What is keeping those folks from just upgrading their Grafana?

Honestly to me it's the other way around: If "your" dashboards require deprecated plugins, that keeps me from upgrading to newer Grafana versions.

**Comment by mkuratczyk** [comment]
No, we don't need to maintain compatibility. These dashboards should be updated. A PR would be appreciated

**Comment by mkuratczyk** [comment]
Users have full access to these dashboards and absolutely can (and probably should) modify them (it'd be great if they shared their improvements). So we did not prevent anyone from upgrading Grafana.

Anyway, I updated the dashboards:
https://grafana.com/grafana/dashboards/11340-rabbitmq-quorum-queues-raft/
https://grafana.com/grafana/dashboards/11352-erlang-distribution/
https://grafana.com/grafana/dashboards/11350-erlang-memory-allocators/
https://grafana.com/grafana/dashboards/6566-rabbitmq-perftest/
https://grafana.com/grafana/dashboards/10988-erlang-distributions-compare/

**Comment by eightseventhreethree** [comment]
This dashboard is also affected:
https://grafana.com/oss/prometheus/exporters/go-exporter/?tab=dashboards
