### ISSUE TITLE
HTTP API listener: make it possible to disable non-TLS listeners

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#9246]
Plain (non-TLS) [AMQP 0-9-1 and AMQP 1.0 listeners can be disabled](https://rabbitmq.com/ssl.html#enabling-tls). The same should be possible for the non-TLS HTTP API listener.

**Comment by illotum** [comment]
I meant to quickly knock it off, but discovered it can be done already.

If the ssl listener is configered and _no_ `management.tcp` settings are in the config, HTTP socket will be disabled. Can be verified by enabling the plugin with this minimal config (and certs present):

```
management.ssl.port = 8443
management.ssl.certfile = /etc/rabbitmq/example.com.crt
management.ssl.keyfile = /etc/rabbitmq/example.com.key

# management.tcp.port = 8080
```

See `rabbit_mqmq_app:get_listeners_config/0`.
