### ISSUE TITLE
set RABBITMQ_MNESIA_BASE in rabbitmq-env-conf.bat

### ISSUE THREAD

**Issue by fnbk** [rabbitmq/rabbitmq-server#9258]
### Describe the bug

Based on the documentation it should be possible to set `RABBITMQ_MNESIA_BASE` in the `rabbitmq-env.conf` file.

On windows this does not work. I have set the following configuration file:

`%appdata%\RabbitMQ\rabbitmq-env-conf.bat`
```
REM data directory
set RABBITMQ_MNESIA_BASE="E:\rabbitmq"
```

based on this guide: https://www.rabbitmq.com/configure.html#rabbitmq-env-file-windows

### Reproduction steps

1. install RabbitMQ using windows-installer
2. create `%appdata%\RabbitMQ\rabbitmq-env-conf.bat`
```
REM data directory
set RABBITMQ_MNESIA_BASE="E:\rabbitmq"
```
3. re-install RabbitMQ service
```
rabbitmq-service.bat stop
rabbitmq-service.bat remove
rabbitmq-service.bat install
rabbitmq-service.bat start
```

### Expected behavior

**Expected**: `E:\rabbitmq` directory should be created
**Actual**: `%appdata%\RabbitMQ\db` is created

### Additional context

versions: 

- RabbitMQ 3.11.8
- Erlang 25.2.2

**Comment by lukebakken** [comment]
I'll put this on my list.

**Comment by lukebakken** [comment]
Thanks @michaelklishin
