### ISSUE TITLE
Is there a way to redirect rabbitmq logging to UDP port?

### ISSUE THREAD

**Issue by vladimirtsyupko** [rabbitmq/rabbitmq-server#93]
This is not an issue, rather a question about functionality. 
I'm setting up the graylog2 server to aggregate the logs of all our components, but I can't find a way to send rabbitmq logs to the UDP port of our graylog2 input?

**Comment by michaelklishin** [comment]
Please direct questions to [RabbitMQ mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users), we use issues for questions.
