### ISSUE TITLE
Add Fedora/RHEL/CentOS systemd service integration

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/rabbitmq-server#932]
Issue for the remaining work discussed in: https://github.com/rabbitmq/rabbitmq-server/pull/913

Specifically we need to make `make package-rpm` create noarch packages for el6 and el7:

**Comment by michaelklishin** [comment]
Kudos to @harlowja for the original pull request. This will be in `3.6.6`.

**Comment by harlowja** [comment]
Thanks guys and gals!
