### ISSUE TITLE
MQTT: consider making it possible to extract client ID from client-provided certificate

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-server#9323]
This is a companion issue to https://github.com/rabbitmq/rabbitmq-server/issues/9322.

Extracting client ID from the certificate and ignoring the client-provided value may help those users who would like to embed all the client identity (and session) information into the certificates they distribute to devices.

Usernames already can be extracted from the certificate.

**Comment by MarcialRosales** [comment]
We use the following configuration variables to extract the `username` from the certificate:
- `ssl_cert_login_from`
- `ssl_cert_login_san_type`
- `ssl_cert_login_san_index`
The last two variables are only used when `ssl_cert_login_from` = `subject_alternative_name`

In addition to extracting the `username` from the client's certificate, we also want to extract the client_id. We need three more variables, similar to the previous one, but configured in the mqtt plugin. For instance: 
- `ssl_cert_client_id_from`
- `ssl_cert_client_id_san_type`
- `ssl_cert_client_id_san_index`
