### ISSUE TITLE
Declaring a classic priority queue leads to strange "queue storage version"

### ISSUE THREAD

**Issue by walro** [rabbitmq/rabbitmq-server#9370]
### Describe the bug

Declaring a priority queue leads to weird values being presented in the management UI (and via `rabbitmqadmin`), see screenshots.

Here I would expect it to be 1 rather than 11:

<img width="286" alt="Screenshot 2023-09-12 at 12 47 02" src="https://github.com/rabbitmq/rabbitmq-server/assets/2550510/a769488e-3789-4c2d-bea5-9e5e6aa8d227">

and here to be 2 rather than 22:

<img width="282" alt="Screenshot 2023-09-12 at 12 48 27" src="https://github.com/rabbitmq/rabbitmq-server/assets/2550510/f037959b-e0b1-4fc6-800d-a9ad7951ca1c">

### Reproduction steps

1. Create two queues:
   1. `rabbitmqadmin declare queue name=priority-bug1 arguments='{"x-max-priority":10,"x-queue-version":1}'`
   1. `rabbitmqadmin declare queue name=priority-bug2 arguments='{"x-max-priority":10,"x-queue-version":2}'`
1. List the queues:
   1.  `rabbitmqadmin --vhost / list queues name backing_queue_status.version`
1. See the output not having the expected values:
```
+---------------+------------------------------+
|     name      | backing_queue_status.version |
+---------------+------------------------------+
| priority-bug1 | 11                           |
| priority-bug2 | 22                           |
+---------------+------------------------------+
```

It seems like the value becomes something like `(1 + max_priority) * queue_version`?

### Expected behavior

To see versions correspond to the queue version number.

### Additional context

Tried this on 3.12.4, but have observed on 3.12.1 too.

**Comment by michaelklishin** [comment]
Every priority queue is N queues under the hood, so my guess is that the metric tries to aggregate version numbers as it would, say, messages in a certain state.

It should instead just pick the storage version of the first internal queue since they will never differ.
