### ISSUE TITLE
INTERNAL_ERROR with 3.5.0

### ISSUE THREAD

**Issue by PritamUpadhyay** [rabbitmq/rabbitmq-server#95]
Gives an error "Unhandled connection error: INTERNAL_ERROR" while connecting to RabbitMQ from nodeJS using amqp.
The same code was working completely in previous versions and even that code is still working without any issue in versions from 3.3.5 to 3.4.4.

**Comment by michaelklishin** [comment]
* Using node-amqp or amqp.lib? (the former must be avoided as it is abandonware)
 * What is in log files?
 * What does your code look like?

**Comment by PritamUpadhyay** [comment]
I am using node-amqp. I am building chat web-application.
Log file:
=ERROR REPORT==== 2-Apr-2015::12:15:25 ===
** Generic server <0.354.0> terminating
** Last message in was {'$gen_cast',
                           {method,
                               {'queue.bind',0,<<"LoadJs_817">>,
                                   <<"ck-2091eaa753b116e8-pre">>,
                                   <<"demo$817">>,false,[]},
                               none,noflow}}
** When Server state == {ch,running,rabbit_framing_amqp_0_9_1,1,<0.348.0>,
                            <0.352.0>,<0.348.0>,
                            <<"192.168.0.58:55677 -> 192.168.0.58:5672">>,
                            {lstate,<0.353.0>,false},
                            none,1,
                            {[],[]},
                            {user,<<"abc">>,
                                [administrator],
                                [{rabbit_auth_backend_internal,none}]},
                            <<"RMQ">>,<<"LoadJs_817">>,
                            {dict,0,16,16,8,80,48,
                                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            {state,
                                {dict,0,16,16,8,80,48,
                                    {[],[],[],[],[],[],[],[],[],[],[],[],[],
                                     [],[],[]},
                                    {{[],[],[],[],[],[],[],[],[],[],[],[],[],
                                      [],[],[]}}},
                                erlang},
                            {dict,0,16,16,8,80,48,
                                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            {dict,0,16,16,8,80,48,
                                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            {set,0,16,16,8,80,48,
                                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            <0.349.0>,
                            {state,fine,5000,#Ref<0.0.0.1918>},
                            false,1,
                            {{0,nil},{0,nil}},
                            [],
                            {{0,nil},{0,nil}},
                            [],none,0,none}
** Reason for termination == 
** {function_clause,
       [{presence_exchange,deliver,
            [{delivery,false,false,<0.354.0>,
                 {basic_message,
                     {resource,<<"RMQ">>,exchange,
                         <<"ck-2091eaa753b116e8-pre">>},
                     [<<"demo">>],
                     {content,60,
                         {'P_basic',undefined,undefined,
                             [{<<"exchange">>,longstr,
                               <<"ck-2091eaa753b116e8-pre">>}],
                             undefined,undefined,undefined,undefined,
                             undefined,undefined,undefined,undefined,
                             undefined,undefined,undefined},
                         none,none,
                         [<<"{\"action\":\"bind\",\"channel\":\"demo\",\"uuid\":\"817\",\"timestamp\":\"1427957125\"}">>]},
                     <<170,129,170,61,121,106,56,40,71,186,50,9,114,74,111,72>>,
                     false},
                 undefined,noflow}],
            [{file,"src/presence_exchange.erl"},{line,186}]},
        {presence_exchange,add_binding,3,
            [{file,"src/presence_exchange.erl"},{line,217}]},
        {rabbit_binding,x_callback,4,
            [{file,"src/rabbit_binding.erl"},{line,561}]},
        {rabbit_binding,'-add/3-fun-0-',3,
            [{file,"src/rabbit_binding.erl"},{line,193}]},
        {rabbit_channel,binding_action,9,
            [{file,"src/rabbit_channel.erl"},{line,1471}]},
        {rabbit_channel,handle_cast,2,
            [{file,"src/rabbit_channel.erl"},{line,326}]},
        {gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1034}]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}.

**Comment by michaelklishin** [comment]
You are using `presence_exchange`. It needs updating for 3.5.0.

**Comment by michaelklishin** [comment]
Also, please seriously consider switching away from node-amqp. It is has known bugs and is not maintained.

**Comment by PritamUpadhyay** [comment]
Can you please elaborate:  "You are using  presence_exchange . It needs updating for 3.5.0."
What kind of updates do I need to make in presence_exchange ?
And also can you tell me knows bugs of using node-amqp ?

**Comment by michaelklishin** [comment]
Plugins sometimes need updating as internal RabbitMQ modules they may use change.

node-amqp creates connections storms, does not respect max number of channels limit, has internal race conditions, etc. Some hosted RabbitMQ providers outright block it.

**Comment by PritamUpadhyay** [comment]
Okay. Got it..
Thanks.
