### ISSUE TITLE
Bug in erlang_crash.dump reporting in OTP 18 

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-server#956]
OTP 18 has a known bug where `erlang_crash.dump` is not written in the case of memory exhaustion and the `+B` flag was passed to VM.

Currently this parameter is hardcoded in `rabbitmq-server` script.

**Comment by michaelklishin** [comment]
Is there an issue we can link to, e.g. on erlang-bugs?

**Comment by hairyhum** [comment]
I've found it in the OTP-19 changelog
```
OTP-13425    Application(s): erts

               A bug has been fixed where if erlang was started +B on
               a unix platform it would be killed by a SIGUSR2 signal
               when creating a crash dump.
```

**Comment by hairyhum** [comment]
This seems like it https://bugs.erlang.org/browse/ERL-94
