### ISSUE TITLE
"Error: could not connect to server since 2023-10-11 14:44:19. Will retry at 2023-10-11 14:44:26"

### ISSUE THREAD

**Issue by lengyue0803** [rabbitmq/rabbitmq-server#9676]
### Describe the bug

Hi,When I want to add tracing on the web management platform, the UI prompts an error “Error: could not connect to server since 2023-10-11 14:44:19. Will retry at 2023-10-11 14:44:26”. Later I found that when I create new users and queues, I will get this error.This is a rabbitmq service deployed on a Linux server. I originally wanted to add a tracing to monitor the operation.But there was an error like this.I would like to know the cause of this problem and the solution.I have searched a lot of information, but I have not found a solution, so I can only find a solution here.

### Reproduction steps

1.I enabled the tracing function through 'rabbitmq plugins enable rabbitmq_tracing'
2.Open the web management platform and locate tracing under the admin tab, ready to create a new trace
3.When I filled in the information and clicked add trace, the above error message was prompted on the page.
...

### Expected behavior

I suspect that this problem is caused by some adjustments on the server, but I can't find the problem. Moreover, through searching, I found that this problem does not appear many times, and there is relatively little relevant information to learn from, so I want to find the problem here. solution

### Additional context

![error](https://github.com/rabbitmq/rabbitmq-server/assets/147588599/f3dd4523-3589-47c6-88bb-9734624d4c2f)

**Comment by mkuratczyk** [comment]
The error just means that the Management web page cannot connect to the server anymore (you'll get the same message if you open the Management UI and just stop RabbitMQ for example). Check the logs log to see what happened when you enabled tracing.

Please note that 3.9.11 is two years old and the support for 3.9 ended a few months ago. Please open a new issue when you see this problem in a supported version.

**Comment by lengyue0803** [comment]
May I ask if the log mentioned above is a log of rabbitmq running? I have previously output its running log, but when prompted for the above error, the log did not display any error

**Comment by lengyue0803** [comment]
> The error just means that the Management web page cannot connect to the server anymore (you'll get the same message if you open the Management UI and just stop RabbitMQ for example). Check the logs log to see what happened when you enabled tracing.
> 
> Please note that 3.9.11 is two years old and the support for 3.9 ended a few months ago. Please open a new issue when you see this problem in a supported version.
May I ask if the log mentioned above is a log of rabbitmq running? I have previously output its running log, but when prompted for the above error, the log did not display any error，Or maybe I need to upgrade the version of the service

**Comment by mkuratczyk** [comment]
I don't understand the question. I mean that `Error: could not connect to server...` is a JavaScript-level error - the page you are looking at no longer receives updates from the server (normally it's a dynamic page which updates the metrics, etc). So all this message says is there's no connection between your browser and the server.

**Comment by lengyue0803** [comment]
I think I understand what you mean, but what I am curious about is that the management platform can be opened. If there is no connection between the management page and the server, then the management page cannot be opened. But now this error is prompted when adding new functions above.

**Comment by mkuratczyk** [comment]
It could be that enabling tracing causes a crash (of course it shouldn't but there could be a problem). There's also a chance that something terminates the connection after some time, etc.

Anyway, end of support means end of support. Please keep (all) your software up to date.

**Comment by lengyue0803** [comment]
Then I will continue to track the issue and see if I can find a solution by upgrading the version or other means. Thank you very much for your help
