### ISSUE TITLE
Handle or forbid unnamed runtime parameters

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-server#971]
Apparently, it's possible to create an unnamed policy according to this mailing-list thread:
https://groups.google.com/d/topic/rabbitmq-users/o_2zx3E2jN8/discussion

The name of the parameter is then set to `undefined` and is impossible to modify/delete.

We should either prevent that or give an implicit name. The former is probably the preferred method.

**Comment by michaelklishin** [comment]
Backported to `v3.8.x` for `3.8.27`.
