### ISSUE TITLE
Changing shovel parameters shovel may look like it's running twice 

### ISSUE THREAD

**Issue by luos** [rabbitmq/rabbitmq-server#9724]
### Describe the bug

Hi,

When a shovel is updated from a different node where it's currently running on (ie. using Management from behind a load balancer), it will leave an entry in `rabbit_shovel_status`. This will be confusing for users as it will look like the shovel is running twice. 

![kép](https://github.com/rabbitmq/rabbitmq-server/assets/923194/328df475-2fd2-4d4d-a7b7-299cb9bf71ef)

### Reproduction steps

1. Create a shovel from Management of Node A
2. Try to update the same shovel from Node B (with slightly different config, otherwise nothing will happen)
3. Observe the status page showing the shovel running twice

### Expected behavior

Showing the shovel running only once. 

### Additional context

This is caused by https://github.com/rabbitmq/rabbitmq-server/blob/f4e64235a8125fc9f5333174e3edb792eb90fc59/deps/rabbitmq_shovel/src/rabbit_shovel_dyn_worker_sup_sup.erl#L72 only cleaning up the status on the local node. 

The entry is cleaned up on restart of the node.

**Comment by ikavgo** [comment]
Khepri fixes it.

**Comment by michaelklishin** [comment]
Let's assume that 3.13.0 with Khepri enabled is a good enough solution. Mnesia is going away this year, after all.
