### ISSUE TITLE
Reduce the VM GC call intensity for lazy queues

### ISSUE THREAD

**Issue by Gsantomaggio** [rabbitmq/rabbitmq-server#973]
Add a configuration to tune the GC calls inside the `variable_queue`. 
The GC called inside `reduce_memory_use` can impact to the performance, under certain conditions 

This improvement is part of the issue https://github.com/rabbitmq/rabbitmq-server/issues/964. 

The code could be like:

```
increase_or_execute_gc(State = #vqstate {run_count = RunCount} )  when RunCount >= ?GC_THRESHOLD ->
    garbage_collect(),
    State#vqstate{run_count =  0};
increase_or_execute_gc(State = #vqstate {run_count = RunCount}) ->
    State#vqstate{run_count =  RunCount + 1}.
```
the parameter `GC_THRESHOLD` is 250 by default.

**Comment by michaelklishin** [comment]
Note that this will only change for lazy queues.
