### ISSUE TITLE
Use the scope in the resource section of the JWT token generated by the Keycloak

### ISSUE THREAD

**Issue by avarf** [rabbitmq/rabbitmq-server#9758]
### Is your feature request related to a problem? Please describe.

When enabling the authorization for a confidential Keycloak client, you can define resources, scopes, policies and permissions for each resource and connect/map users or user groups to those permissions. This is the suggested method of configuring Keycloak and enables us to have a very fine-grained authorization policy.

Based on my understanding, unfortunately, RabbitMQ and `rabbitmq_auth_backend_oauth2` plugin expect to find the permissions in the scope at the highest level of a JWT token which matches the client scope.

### Describe the solution you'd like

There should be a flag that let RabbitMQ admin to configure the `rabbitmq_auth_backend_oauth2` plugin so either the plugin uses the client-scope policies or uses the resource permissions.

### Additional context

Current expected token structure:
```json
{
  "scope": [
    "rabbitmq.write:*/*/*",
    "rabbitmq.configure:*/*/*",
    "rabbitmq.read:*/*/*"

  ],
  "extra_scope": "rabbitmq.tag:management",
  "aud": [
    "rabbitmq"
  ]
}
```

Example RPT token produced by Keycloak:
```json
{
  "authorization": {
    "permissions": [
      {
        "scopes": [
          "read",
          "create",
          "update",
          "execute",
          "delete"
        ],
        "rsid": "354aa847-74d6-4d70-af58-bf899964a437",
        "rsname": "experiment"
      },
      {
        "scopes": [
          "read",
          "create",
          "update",
          "delete"
        ],
        "rsid": "077ddbe7-f60e-40ad-bcdb-70be6de29741",
        "rsname": "node_type"
      }
    ]
  },
  "scope": "email profile",
  "groups": [
    "sys"
  ]
}
```

**Comment by Zerpet** [comment]
Transferring from the oauth2 tutorial repo, as this issue is a feature request for the OAuth2 plugin.
