### ISSUE TITLE
QQ: Cache {RaftIndex, Timestamp} for oldest_entry_timestamp

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/rabbitmq-server#9791]
### Is your feature request related to a problem? Please describe.

To avoid having to do potentially expensive reads every time the `oldest_entry_timestamp` is evaluated we should cache the last raft index, timestamp value in the aux state and if the smallest raft index is the same just return the cached value.

**Comment by michaelklishin** [comment]
Addressed in https://github.com/rabbitmq/rabbitmq-server/pull/9790.

**Comment by kjnilsson** [comment]
This one is still a TODO!
