### ISSUE TITLE
QQ: Open files appears not be be updated as segments are opened.

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/rabbitmq-server#9792]
### Reproduction steps

1. Create a quorum queue called `q1` and publish a message
2. restart the broker
3. Evaluate `ra:aux_command({'%2F_q1', node()}, oldest_entry_timestamp).`
4. Observe how "Open files" in the mgmt queue pages stays at a 0 compared to, say, `lsof` which should show at least one open segment for the broker. 
...

### Expected behavior

Open files should reflect the number of open segments for the process.

**Comment by michaelklishin** [comment]
Addressed in https://github.com/rabbitmq/rabbitmq-server/pull/9794.
