### ISSUE TITLE
documentation issue - "which does this would look like"

### ISSUE THREAD

**Issue by richlv** [rabbitmq/rabbitmq-server#986]
http://www.rabbitmq.com/access-control.html has "If you wish to allow the guest user to connect from a remote host, you should set the loopback_users configuration item to []. A complete rabbitmq.config which does this would look like:"
that doesn't seem to be a proper sentence

**Comment by richlv** [comment]
re-reading this for the 5th time, it might have been "(A complete rabbitmq.config) (which does this) (would look like):"

if so, it is probably a proper sentence... but it might also be a good idea to rephrase it a bit :)

**Comment by camelpunch** [comment]
Please feel free to submit a PR for content changes like this. Please base it on the `live` branch of rabbitmq-website: https://github.com/rabbitmq/rabbitmq-website/tree/live

**Comment by camelpunch** [comment]
Closing as it's not a server issue.
