### ISSUE TITLE
When applying a 'nodes' policy, master can be chosen outside of the requested set

### ISSUE THREAD

**Issue by camelpunch** [rabbitmq/rabbitmq-server#990]
When applying an HA policy with the 'nodes' type, if the current master is not part of the new policy, then the first synchronised slave is chosen as the new master. This happens even if the node is not part of the new policy.

For example, if we begin with:

Master A
Slaves [B, C]

Then request a new policy of just [C], we will end up with:

Master B
Slaves [C]

We should instead choose the master from the intersection of (nodes in the policy) and (synchronised slaves).

**Comment by dumbbell** [comment]
We found this new issue while working on #889.

**Comment by michaelklishin** [comment]
I believe this can be closed as https://github.com/rabbitmq/rabbitmq-server/commit/c1c56a29b098b7c5ad0915a340a2a039e61a22a3 is already in `stable`.
