### ISSUE TITLE
Per-queue x-consumer-timeout is silently ignored if argument configured as String value

### ISSUE THREAD

**Issue by KirillMakrutin** [rabbitmq/rabbitmq-server#9914]
### Describe the bug

v3.12.8: when configuring a queue with the "Per-queue consumer timeout" feature in RabbitMQ using the x-consumer-timeout argument, an issue arises when providing the timeout value as a String. 
Although this does not impact functionality, it affects the UI, and more critically, it fails to trigger the expected timeout exception PRECONDITION_FAILED - delivery acknowledgement on channel timed out.
Here is how a queue can be created:
<img width="559" alt="image" src="https://github.com/rabbitmq/rabbitmq-server/assets/12656159/80bfcba9-da45-494c-baf7-0d5da6f7bfc6">
Here is how 'Consumer' setup looks like:
<img width="796" alt="image" src="https://github.com/rabbitmq/rabbitmq-server/assets/12656159/f2d166e4-a67a-4018-b503-a50ee41f537b">

### Reproduction steps

1. Create a queue passing x-consumer-timeout in milliseconds as a String type
2. Ensure that 'Consumer Timeout' has been affected
3. Run message processing job that takes more time that expected timeout value

### Expected behavior

Either x-consumer-timeout argument passed as a String should work or it should not be reflected in Consumers UI, (or maybe documented that it should be a number, but not a string argument)

**Comment by michaelklishin** [comment]
There is a [policy](https://rabbitmq.com/parameters.html#why-policies-exist) validator for this key that [only accepts non-negative integers](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/src/rabbit_policies.erl#L83-L87).

Using policies over [optional queue arguments](https://rabbitmq.com/queues.html#optional-arguments) when this is an option has been our recommendation for many years.
