### ISSUE TITLE
Crash dump was written to: erl_crash.dump no more index entries in atom_tab (max=1048576)

### ISSUE THREAD

**Issue by dennysheng** [rabbitmq/rabbitmq-server#992]
Hi,

My rabbitmq server crashed sometimes and got above message. After reading dump files we got following infomation which is atom table was filling up.

But we are sure that our code doesn't write anything (like below pic i attached, highlighted), do you guys have any suggestions on how these elements generated?

![2](https://cloud.githubusercontent.com/assets/12558205/19211812/2a28b532-8d78-11e6-867f-6dd9b5e66a4d.png)

rabbitmq version 3.6.3
Erlang version 5.10.4
OS Ubuntu 14.04

Thanks,

**Comment by michaelklishin** [comment]
Fixed in 3.6.4. See release notes.

**Comment by michaelklishin** [comment]
Specifically in https://github.com/rabbitmq/rabbitmq-management/issues/245.
